### ISSUE TITLE
reduce over-building (galaxy)

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#10016]
This is a long standing issue tracked w/ other issues in #1920, however, this has become more critical w/ galaxy since we now over-build 32x as much

Presently we build (eg):  substitutes.cpp, noc.c, tdma_xmov.c, tmu-crt0.c, tmu-crt0k.c, ncrisc-halt.S
over and over at runtime even though these files have no dynamic dependencies.  These should all be built once during the offline build process then linked at runtime.

Task is to:
1) Grab the command line for a build of each of the above, factor out the common stuff and remove, eg, compile time args, defines, etc
2) Create a makefile for building these.  We could go back in time and base this off of riscv.mk that used to be in the tree, though that already had a lot of legacy dependencies
3) Remove building these files from build.cpp
4) Add .o dependencies in build.cpp for these files where appropriate and update the link lines to pull them in at link

**Comment by aliuTT** [comment]
Initial changes, building `tmu-crt0`, `tmu-crt0k`, `ncrisc-halt` offline and linking them during jit build. https://github.com/tenstorrent/tt-metal/pull/10096

I saw that `substitutes.o`, `noc.o`, `tdma_xmov.o` binaries differed between firmware and different kernels. So need to try CI a bunch more if we want to link those.

**Comment by pgkeller** [comment]
> Initial changes, building `tmu-crt0`, `tmu-crt0k`, `ncrisc-halt` offline and linking them during jit build. #10096
> 
> I saw that `substitutes.o`, `noc.o`, `tdma_xmov.o` binaries differed between firmware and different kernels. So need to try CI a bunch more if we want to link those.

difference could have been time stamp?

**Comment by aliuTT** [comment]
Hmm possible. Although I wasn't seeing a diff in `tmu-crt0.o`, `tmu-crt0k.o` and `ncrisc-halt.o` across the all the built objects. I suspect there are some defines like noc_index that are causing differences in at least the `noc.o`

**Comment by aliuTT** [comment]
Bookkeeping:
- Merged change to build `tmu-crt0`, `tmu-crt0k`, `ncrisc-halt`, `substitutes.o`, `noc.o`, `tdma_xmov.o` offline here 94f6636bf5d34ce42d3621e8455375d88b598218
- Merged change to link `tmu-crt0`, `tmu-crt0k`, `ncrisc-halt` during jit_build at 3c4336d2a49d812488d274191e0bed30f3e69dc8

Next step here is to look into linking `substitutes.o`, `noc.o`, `tdma_xmov.o` as well.

**Comment by aliuTT** [comment]
Linking `substitutues.o`, `noc.o`, `tdma_xmov.o` is added at 0679c1988385f6ac0a78008f14be57b9298d40bd

**Comment by aliuTT** [comment]
Seeing that linking substitutues.o, noc.o, tdma_xmov.o is tanking pgm dispatch perf by 15%. Reverting on main for now

**Comment by aliuTT** [comment]
This has been re-enabled on main with a perf test to catch regressions.
