### ISSUE TITLE
Runtime error: In conv2d for kernel_size=1 (Segformer, Yolox_m)

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#10027]
**Describe the bug**
While running the yolox_m or segformer  model in latest main, I encounter the error `free variable 'ttnn' referenced before assignment in enclosing scope` in conv(Old conv API) operation which has kernel size as 1.

**To Reproduce**
1. Checkout to [harini/ttnn_segformer](https://github.com/tenstorrent/tt-metal/tree/harini/ttnn_segformer)
2. Run `pytest tests/ttnn/integration_tests/segformer/test_segformer_decode_head.py`

**Expected behavior**

Successful execution of the test.

**Please complete the following environment information:**
- OS:  Ubuntu 20.04
- Device : GS

**Additional context**
I didn't face the error on Thursday(04/07/2024) main. Facing this issue from 08/07/2024. The reason for the issue might be due the this commit (https://github.com/tenstorrent/tt-metal/commit/b51240128140d5286fabe99a184bc4ee33d24b0f).

**Comment by punithsekar** [comment]
New conv2D API works fine for kernel_size:1, Didn't try new conv API for segformer and yolox_m model.
Will check it once we work with new conv API for those models.

**Comment by dvartaniansTT** [comment]
@punithsekar have you had a chance to try this again? any updates?

**Comment by punithsekar** [comment]
@dvartaniansTT , Old conv API with kernel_size=1 is not making issue in latest main. The Segformer model is running fine.
Closing this issue, The issue as been resolved.
