### ISSUE TITLE
Binary Bitwise ops

### ISSUE THREAD

**Issue by VirdhatchaniKN** [tenstorrent/tt-metal#10035]
Master issue : #9702 
### Op Requirement :

- ElemwiseBinary/ELEMWISE_BINARY_BITWISEAND
- ElemwiseBinary/ELEMWISE_BINARY_BITWISEOR
- ElemwiseBinary/ELEMWISE_BINARY_BITWISEXOR

**Issues :** 

Unary ops implemented #9437  , #9436 
These ops were directly implemented using their respective operators ( ~ , & , | ) . But the same method cannot be used in binary as these operators are not available outside the kernel.

**Comment by KalaivaniMCW** [comment]
As per conversation with @rtawfik01 , have created a ticket for LLK team to get binary bitwise support - https://github.com/tenstorrent/tt-metal/issues/13582

**Comment by eyonland** [comment]
This work is being tracked instead by #13582
