### ISSUE TITLE
Binary Shift operators

### ISSUE THREAD

**Issue by VirdhatchaniKN** [tenstorrent/tt-metal#10034]
Master issue : #9702 
### Op Requirement :

- ElemwiseBinary/ELEMWISE_BINARY_LEFT_SHIFT
- ElemwiseBinary/ELEMWISE_BINARY_RIGHT_SHIFT

**Issues :** 

Initial Implementation done in #8636
This implementation requires the involvement of a lot of ops, which may lead to performance issues.

**Comment by KalaivaniMCW** [comment]
Hi @rtawfik01  @rdjogoTT 

Is it possible to support shift operation for two tensors (like it is available in bitwise operation)? 
At present, the second operand for shift operation takes only a single integer parameter
![Image](https://github.com/user-attachments/assets/6f412139-3e45-4be8-9bb9-25e58e97707a)

Bitwise ops: 
![Image](https://github.com/user-attachments/assets/986ae708-5907-4e15-a1a1-68564b900639)

**Comment by rdjogoTT** [comment]
LLK added here: https://github.com/tenstorrent/tt-metal/pull/15926

**Comment by cmaryanTT** [comment]
@eyonland - please assign someone for implementation of this. The LLK should be present, per Radomir's comment. This should be high priority because it could be used to address some customer requests.

**Comment by eyonland** [comment]
Pending merge of 
https://github.com/tenstorrent/tt-metal/pull/16055

**Comment by eyonland** [comment]
@VirdhatchaniKN , would you confirm that this can be closed now?

**Comment by VirdhatchaniKN** [comment]
Closing ticket as PR #16055 has been merged to main
