### ISSUE TITLE
Migrate 7 Unary backward ops to TTNN

### ISSUE THREAD

**Issue by VirdhatchaniKN** [tenstorrent/tt-metal#10069]
Unary Backward Tracking Issue : #9874 [ Master issue : #9322 ]
List of ops required to be migrated

- [x] clamp_max_bw
- [x] hardshrink_bw
- [x] softshrink_bw
- [x] leaky_relu_bw
- [x] elu_bw
- [x] celu_bw
- [x] rpow_bw

**Comment by umadevimcw** [comment]
Migrated all the above mentioned ops and submitted PR #10078

**Comment by umadevimcw** [comment]
Completed and merged to main #10078
