### ISSUE TITLE
TTNN eltwise_acosh - fail when input tensor has ROW_MAJOR layout (GS and WH)

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#10081]
ttnn.acosh fails in cases when layout of an input tensor is ROW_MAJOR. During sweep test, for every combination of parameters with layout = ROW_MAJOR, an error occurs in this format:
    
>`Always | FATAL    | For valid non-interleaved buffers page size 2048 must equal buffer size 19008. For interleaved-buffers page size should be divisible by buffer size`
     
Sweep test crashes with Fatal Python error: Floating point exception.

**To Reproduce**
1. Checkout branch amalbasaTT/opsets4and5-unit-tests
2. Run command:
    ```   
    pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_acosh.py
    ```   

**Expected behavior**
Test case should fail with the error:
   
>RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:194:                               (input_tensor_a.get_layout() == Layout::TILE && input_tensor_b.get_layout() == Layout::TILE)
info:
Inputs to eltwise binary must be tilized

**Getting Additional info for the operation under test and its behavior:**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweep test:
```  
pytest tests/ttnn/python_api_testing/sweep_tests/run_sweep_test.py --input-path tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/ttnn_eltwise_acosh_test.yaml --input-method cli --cli-input results_ttnn_eltwise_acosh
```  

To do this, you should:

1. Follow the Getting Started page to setup the repo, environment variables and python-env
2. Activate source build/python_env/bin/activate
3. Checkout amalbasaTT/opsets4and5-unit-tests
4. Run sweeps by using pytest tests/ttnn/python_api_testing/sweep_tests/run_sweep_test.py --input-path tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/ttnn_eltwise_acosh_test.yaml --input-method cli --cli-input results_ttnn_eltwise_acosh
5. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./results_ttnn_eltwise_acosh). There you will find .csv which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique data_seed field.

**Comment by KalaivaniMCW** [comment]
Test file gives the appropriate error
<img width="1512" alt="Screenshot 2024-10-23 at 3 02 40 AM" src="https://github.com/user-attachments/assets/bff79fbd-95a2-458d-9a14-d50a5a0a9530">

<img width="1512" alt="Screenshot 2024-10-23 at 3 03 38 AM" src="https://github.com/user-attachments/assets/7fb35a09-fd38-4b66-9560-c88ed3d4457e">
