### ISSUE TITLE
All Gather Regression

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#10086]
Commit https://github.com/tenstorrent/tt-metal/commit/4fe8c0e717fab7c4f0a402b80ef8d7fb55e88b1d

causes a regression of test 

`pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py::test_all_gather_on_t3000_post_commit[mem_config0-input_dtype0-4-2-input_shape0-0-layout0]`

with error `Always | FATAL    | Max number of packed sub commands are 28 but requesting 32`

**Comment by SeanNijjar** [comment]
Moving to P0 as this is blocking other changes from being tested and merged.

**Comment by tt-aho** [comment]
Merged the fix to main. Confirm it now passes on ci https://github.com/tenstorrent/tt-metal/actions/runs/9892002446
