### ISSUE TITLE
hangs when launch_msg size exceeds 32 bytes

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#10107]
Transaction is getting split leading to go arriving before the kernel config

**Comment by pgkeller** [comment]
This is fixed, leaving open and assigning to @tt-asaigal for a follow on performance improvement

**Comment by pgkeller** [comment]
@tt-asaigal thinking this should be easy to wrap up when you get a chance

**Comment by tt-asaigal** [comment]
Hey @pgkeller, sorry for the lack of communication on this issue.

I tried configuring the TLB ordering modes during runtime and was seeing ND hangs. I didn't get a chance to fully investigate the cause. I can take a look now if we think this is critical.

**Comment by pgkeller** [comment]
not critical, I keep seeing this issue and wondering if it is fixed.  I'm going to close, since the issue as filed is fixed.  please file an issue for the optimization, we'll track that separately...
