### ISSUE TITLE
[Blackhole Bringup] SFPU eager tests

### ISSUE THREAD

**Issue by rtawfik01** [tenstorrent/tt-metal#10102]
SFPU eager tests are mismatching in blackhole. 

Tests:
```
TT_METAL_WATCHER=5 TT_METAL_DPRINT_CORES=0,0 TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_eager/ops/test_eltwise_unary_op
TT_METAL_WATCHER=5 TT_METAL_DPRINT_CORES=0,0 TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_eager/ops/test_sfpu
```

@abhullar-tt @ttmtrajkovic  fyi

**Comment by rtawfik01** [comment]
@ttmtrajkovic fyi

**Comment by rdjogoTT** [comment]
Running the above tests on Wormhole B0 also results in failures. After looking into LOG a bit further, it seems like both ARCHes produce the same outputs. Do we expect these to pass on BH but not on WHB0?

**Comment by abhullar-tt** [comment]
> Running the above tests on Wormhole B0 also results in failures. After looking into LOG a bit further, it seems like both ARCHes produce the same outputs. Do we expect these to pass on BH but not on WHB0?

If these tests are failing on WH then we can skip them on BH for now as well and revisit
