### ISSUE TITLE
TTNN eltwise_atanh - fail when input tensor has ROW_MAJOR layout (GS and WH)

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#10141]
ttnn.atanh fails in cases when layout of an input tensor is ROW_MAJOR. During sweep test, for every combination of parameters with layout = ROW_MAJOR, an error occurs in this format:
> `Always | FATAL    | For valid non-interleaved buffers page size 2048 must equal buffer size 63168. For interleaved-buffers page size should be divisible by buffer size`

Test hangs after several FATAL errors.

**To Reproduce**
1. Checkout branch amalbasaTT/opsets4and5-unit-tests
2. Run command:
    ```   
    pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_atanh.py
    ```   

**Expected behavior**
Test case should fail with the error:
   
>RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:194: (input_tensor_a.get_layout() == Layout::TILE && input_tensor_b.get_layout() == Layout::TILE)
info:
Inputs to eltwise binary must be tilized

**Getting Additional info for the operation under test and its behavior:**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweep test:
```  
pytest tests/ttnn/python_api_testing/sweep_tests/run_sweep_test.py --input-path tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/ttnn_eltwise_atanh_test.yaml --input-method cli --cli-input results_ttnn_eltwise_atanh
```  

To do this, you should:

1. Follow the Getting Started page to setup the repo, environment variables and python-env
2. Activate source build/python_env/bin/activate
3. Checkout amalbasaTT/opsets4and5-unit-tests
4. Run sweeps by using pytest tests/ttnn/python_api_testing/sweep_tests/run_sweep_test.py --input-path tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/ttnn_eltwise_atanh_test.yaml --input-method cli --cli-input results_ttnn_eltwise_atanh
5. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./results_ttnn_eltwise_atanh). There you will find .csv which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique data_seed field.

**Comment by KalaivaniMCW** [comment]
Tests fail with appropriate error 
<img width="1512" alt="Screenshot 2024-10-23 at 3 07 55 AM" src="https://github.com/user-attachments/assets/2143c6fa-7e97-4c14-a84c-2274a0fbb457">

**Comment by KalaivaniMCW** [comment]
Updated test results, got expected results.
