### ISSUE TITLE
TTNN eltwise_logical_andi - fail when immediate = 0 (WH & GS)

### ISSUE THREAD

**Issue by dveizovicTT** [tenstorrent/tt-metal#10143]
**eltwise_logical_andi** fails when immediate equals 0. During sweep testing this error happens:

immediate = 0, input tensor layout = ROW_MAJOR
`"TT_FATAL @ ../ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:193: (input_tensor_a.get_layout() == Layout::TILE && input_tensor_b.get_layout() == Layout::TILE)
info:
Inputs to eltwise binary must be tilized`

**To Reproduce**
1. Checkout dveizovic/sweep-tests-unit-set9
2. Run available unit test with following command:

`pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_logical_andi.py`

**Expected behavior**
Test case should fail with the error:
`RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:193: (input_tensor_a.get_layout() == Layout::TILE && input_tensor_b.get_layout() == Layout::TILE)
E       info:
E       Inputs to eltwise binary must be tilized`

**Additional context**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweep test:

`pytest tests/tt_eager/python_api_testing/sweep_tests/run_sweep_test.py --input-path tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/wormhole/pytorch_eltwise_logical_andi.yaml --input-method cli --cli-input eltwise_logical_andi_output`

fter the run is completed all test sweeps results should be available inside specified output directory (in this case eltwise_logical_andi_output)

**Comment by Aswinmcw** [comment]
Hi @dveizovicTT , during recent migration of ops to TTNN, we have removed the support for tensor, scalar as pytorch supports only tensor, tensor.
cc. @eyonland

**Comment by VirdhatchaniKN** [comment]
> Hi @dveizovicTT , during recent migration of ops to TTNN, we have removed the support for tensor, scalar as pytorch supports only tensor, tensor. cc. @eyonland

@dveizovicTT , Can we close this issue as the op support has been removed as mentioned by @Aswinmcw

**Comment by dveizovicTT** [comment]
> > Hi @dveizovicTT , during recent migration of ops to TTNN, we have removed the support for tensor, scalar as pytorch supports only tensor, tensor. cc. @eyonland
> 
> @dveizovicTT , Can we close this issue as the op support has been removed as mentioned by @Aswinmcw

Sure. I'll close it.
