### ISSUE TITLE
Expand generality of reshape/squeeze/unsqueeze

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/tt-metal#10219]
**Describe the issue**

It is unclear how to support next inputs in `ttnn.reshape`.
We understand the underlying issue and need an input on how to convert from exact torch ops.
```
[1, 256, 1024]    -> [1, 256, 16, 64]
[1, 256, 16, 64]  -> [1, 256, 1024]
```

Add support for last dim in squeeze. 
We only support dim=0 and can't find a way to convert from below to ttnn
```
torch.ops.aten.squeeze(tensor, -1) # tensor.shape = torch.Size([1, 256, 1])
```

**Additional context**
We see it is as a blocker for compilers bringup. Please let us know if there are workarounds.

**Comment by tarafdarTT** [comment]
no known workarounds today, this will need to be addressed.

**Comment by ayerofieiev-tt** [comment]
@tarafdarTT , can you schedule them and get back with some ETA?

**Comment by tarafdarTT** [comment]
Realistically, I or anyone on TMs won't be able to get to it until all TMs are migrated to TTNN. Tentatively I can say end of July.
