### ISSUE TITLE
Plan out compiler integration support for matmul

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-metal#10210]
tt-metal will be used as a lower level for a higher level compiler.

This issue is to plan out the work for this effort for matmul.

Some potential questions to look at are the following.
- What will the interface with BUDA / TT-MLIR / MoAI / PyTorch look like?
- What information can be provided?
- Is there a known hierarchy of kernels in terms of performance?
- Is there a list of transformations that can be done to improve performance?
- How much information can be given at once?
    - E.g. If given all ops, what type of information can be given or IR be output?
- What information is needed?

**Comment by davorchap** [comment]
Thanks.
Also relevant for other integrations:  MoAI -> ttnn, and PyTorch -> ttnn

**Comment by bbradelTT** [comment]
> Thanks. Also relevant for other integrations: MoAI -> ttnn, and PyTorch -> ttnn

Thanks @davorchap 
Updated.

Is there a central document and/or point of contact for the higher level compiler work?

**Comment by bbradelTT** [comment]
Met with @boris-drazic 
Points from discussion:

1. Need to have some way of specifying if the op can have tensors on the host or needs them on device.
Should also factor in multi device support.

2. validation needs to be split in two - check for tensors on device when op is called. Other validation before and when op is called.

3. would need L1/DRAM footprint - pass in everything
footprint:
- CBs
- output tensor

- get size of CBs
- get size of output tensor - and whether on L1 or DRAM ? - maybe a pair

4. would want to return a struct instead of throw for validate results
Just return string of whatever would be printed to screen
Empty string means no errors.

Note: if only pass tensors, validate() can still fail. Also, in a lot of cases will run out of memory.

5. estimate perf is not a blocker for first 3 month effort, but will be needed after that

6. higher level might want to check speed of validate/footprint methods, although mostly if statements and should be ok.

7. For the constraints, would just be given input shape a and input shape b, and generate all possible combinations that would work... including for input shard shapes.
Could be billions of combinations.
Most of these would not have significant perf impact or have perf impact that could not be estimated. 

How would these values be used?
How would the search be performed?

First, find the one that works? - L1 vs DRAM. Should be able to do that from footprint methods, which would depend on uOP parameters. - without worrying about validity - then could give ranges. Would want to focus on this one.

Second, find the one that is the most performant. Don't have to worry about this for a long time. Would probably want to see if perf has convexity on parameters and then could try to generate values as go along.


I'll work on the tasks in following order:
- memory footprint
- validation
- constraints
- estimate of perf

**Comment by bbradelTT** [comment]
Created https://github.com/tenstorrent/tt-metal/issues/10606 for memory footprint and
validation
and https://github.com/tenstorrent/tt-metal/issues/10607 for constraints.

Estimation of perf will be a lot more complex and further out. I'll create an issue later.

Closing.
