### ISSUE TITLE
[Blackhole Bringup] New SFPU functions

### ISSUE THREAD

**Issue by rtawfik01** [tenstorrent/tt-metal#10226]
New SFPU functions are missing for BH like (softplus, remainder, bitwise ops, etc)

@abhullar-tt fyi

**Comment by rdjogoTT** [comment]
I have looked through the `ckernel_sfpu_....h` files in the `tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/` directory and compared to the WHB0 directory, and the differences that still remain are the following:

- [ ] `trunc` OP works but the stack has it disabled for all arches except whb0 - update to also include BH
- [ ] `calculate_int_mask()` missing in `ckernel_sfpu_mask.h`
- [ ] `ckernel_sfpu_recip.h` differ - WHB0 calls on the submodule to calculate
- [ ] `ckernel_sfpu_sqrt.h` differ - WHB0 calls on the submodule to calculate
- [ ] `ckernel_sfpu_reshuffle_rows.h` missing - was never added to BH

**Comment by ncvetkovicTT** [comment]
> I have looked through the `ckernel_sfpu_....h` files in the `tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/` directory and compared to the WHB0 directory, and the differences that still remain are the following:
> 
> * [ ]  `trunc` OP works but the stack has it disabled for all arches except whb0 - update to also include BH
> * [ ]  `calculate_int_mask()` missing in `ckernel_sfpu_mask.h`
> * [ ]  `ckernel_sfpu_recip.h` differ - WHB0 calls on the submodule to calculate
> * [ ]  `ckernel_sfpu_sqrt.h` differ - WHB0 calls on the submodule to calculate
> * [ ]  `ckernel_sfpu_reshuffle_rows.h` missing - was never added to BH

@rdjogoTT Whenever you can, take a look at #11816

**Comment by ncvetkovicTT** [comment]
ckernel_sfpu_reshuffle_rows.h will be addressed in #11816.

**Comment by ncvetkovicTT** [comment]
Reopened until merged.

**Comment by ncvetkovicTT** [comment]
Merged, reshuffle_rows will be addressed in [#11816](https://github.com/tenstorrent/tt-metal/issues/11816).
