### ISSUE TITLE
TTNN - relu_max and relu_min operations incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#10266]
For TTNN relu_max and relu_min ops:
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, it seems that it does support both BFLOAT16 and BFLOAT8_B types;  TILE is supported, but ROW_MAJOR fails with error about buffer size. Ranks up to 4 appear to work. However, SYSTEM_MEMORY is not supported.

**Comment by mouliraj-mcw** [comment]
closing as completed.
