### ISSUE TITLE
Mistral demo README should be updated for v50 release 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#10278]
**Describe the bug**
the demo for WH (n150/n300) fails UNLESS you set the cache dir path to the same path containing tokenizer and the checkpoint which is contradicting with README instructions. 

Please update the README to reflect the expected paths for the model to pass. 

For instance, 
I had to do the following to make it pass: 

1. python models/demos/wormhole/mistral7b/scripts/get_mistral_weights.py --weights_path="models/demos/wormhole/mistral7b/weights_inst" --instruct
2. I had to make the <FOLDER_TO_SAVE_WEIGHTS> to be the same as <weights_cache_dir> to make the demo run. Otherwise, If I made a new <weights_cache_dir> and did `export MISTRAL_CACHE_PATH=<some new dir>`, I would run into errors as `consolidated.00.pth Not Found in path ...`

My working/model passing env variables are: 
export MISTRAL_CKPT_DIR="models/demos/wormhole/mistral7b/weights_inst"
export MISTRAL_TOKENIZER_PATH="models/demos/wormhole/mistral7b/weights_inst"
export MISTRAL_CACHE_PATH="models/demos/wormhole/mistral7b/weights_inst"

**To Reproduce the Error**
Git checkout [v0.50.0](https://github.com/tenstorrent/tt-metal/tree/v0.50.0/models/demos/wormhole/mistral7b)
git submodule update --init --recursive
follow build from WHL instrctions for v50
Following the current README instrcutions for Mistral N150 demo; `mkdir  <weights_cache_dir>` 

```
export MISTRAL_CKPT_DIR="models/demos/wormhole/mistral7b/weights_inst"
export MISTRAL_TOKENIZER_PATH="models/demos/wormhole/mistral7b/weights_inst"
export MISTRAL_CACHE_PATH="models/demos/wormhole/mistral7b/weights_cache_dir".
``` 

run:
pytest models/demos/wormhole/mistral7b/tests/test_mistral_model.py::test_mistral_model_inference[17-generative] 

Error: consolidated.00.pth Not Found in path "models/demos/wormhole/mistral7b/weights_cache_dir"

bigger error message: 
See screen shot attached 
<img width="1727" alt="Screenshot 2024-07-15 at 9 52 40 AM" src="https://github.com/user-attachments/assets/72572809-908f-4a8c-a7c3-1d466d66b38d">

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software ([v0.50.0](https://github.com/tenstorrent/tt-metal/tree/v0.50.0/models/demos/wormhole/mistral7b))
- N150 

**Additional context**
See screen shot attached.

**Comment by tt-rkim** [comment]
@mtairum @yieldthought @uaydonat 
Can we get some help on this?

Hands full w/ other stuff. I can get on it after I'm finished with my other stuff.

**Comment by uaydonat** [comment]
fyi @sraizada-tt

**Comment by sraizada-tt** [comment]
fixed, thanks! https://github.com/tenstorrent/tt-metal/pull/10309
