### ISSUE TITLE
Update install documentation to avoid commonly encountered errors building from SOURCE

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#10276]
**Describe the bug**
the instructions to build from source are in the wrong order [here](https://github.com/tenstorrent/tt-metal/blob/main/INSTALLING.md#option-1-from-source)

update them to: 

```
# If you would like an out-of-the-box virtual environment to use,
./create_venv.sh
source python_env/bin/activate
./build_metal.sh
```

tests will fail if metal is built in the current order. 

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (https://github.com/tenstorrent/tt-metal/blob/v0.50.0/INSTALLING.md)

**Comment by tt-rkim** [comment]
I've asked @dvartaniansTT for examples on how this occurs.

Though environment -> build steps do make more sense, given how our build works, I don't see why this would cause errors.

**Comment by tt-rkim** [comment]
Closing this as no movement and no complaints from community
