### ISSUE TITLE
falcon 7b demo fails when built from whl on N300 release tag v50. The same model demo passed when built from source 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#10319]
**Describe the bug**
Built v50 from whl. Did not see any errors from the build itself but when I ran the falcon7b demo, I ran into the attached error. (see screen shot)

**To Reproduce**
1. Git checkout [v0.50.0](https://github.com/tenstorrent/tt-metal/tree/v0.50.0/models/demos/wormhole/falcon7b)
2. git submodule update --init --recursive
3. pip install <wheel_file.whl>
4. pip install -r tt_metal/python_env/requirements-dev.txt

If I build from the whl inside a virtual env, I see an error running the falcon7b demo. 
If I build from the whl outside of the virtual env, I see a different error when running the falcon7b demo. 
if I build from SOURCE, the model demo passes/no errors. 

**Expected behavior**
WHL installation to work for N300 just like the build from source.

**Screenshots**
build from whl inside the virtual env:
<img width="1920" alt="Screenshot 2024-07-15 at 3 49 26 PM" src="https://github.com/user-attachments/assets/d8a5a61f-8873-4da6-ad2a-abe8c41303a2">

build from whl outside of a virtual env:
<img width="1917" alt="Screenshot 2024-07-15 at 4 04 36 PM" src="https://github.com/user-attachments/assets/cae20364-6919-44f4-b1c6-db2b34313abe">

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software ([v0.50.0](https://github.com/tenstorrent/tt-metal/tree/v0.50.0/models/demos/wormhole/falcon7b))
- N300

**Comment by tt-rkim** [comment]
fixed in newer release.
