### ISSUE TITLE
t3k demos falcon 40b fail

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#10320]
https://github.com/tenstorrent/tt-metal/actions/runs/9929186758/job/27426546286

Consistent Behavior 

failing 
test_falcon_end_to_end_60_layer_t3000_prefill_10_loops.py
test_falcon_end_to_end_t3000_demo_loops

tests removed using @skip_for_wormhole_b0("") at pytest level

**Comment by johanna-rock-tt** [comment]
All pipelines are green again and tests re-enabled on main. See [this PR](https://github.com/tenstorrent/tt-metal/pull/10387#pullrequestreview-2182231698)
