### ISSUE TITLE
t3k mixtral unit test -failing

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#10322]
https://github.com/tenstorrent/tt-metal/actions/runs/9944302102/job/27471920607
https://github.com/tenstorrent/tt-metal/actions/runs/9946578922/job/27477763315

https://github.com/tenstorrent/tt-metal/actions/runs/9948093468

tests removed using @skip_for_wormhole_b0("") at pytest level

**Comment by mtairum** [comment]
Fix merged. https://github.com/tenstorrent/tt-metal/pull/10433
