### ISSUE TITLE
temporarily fix t3k pipelines by disabling broken tests

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#10326]
T3K pipelines are failing and hard to maintain.

Disabled relevant tests and made issues tagging relevant owners

- [x] https://github.com/tenstorrent/tt-metal/issues/10317
- [x] https://github.com/tenstorrent/tt-metal/issues/10321
- [x] https://github.com/tenstorrent/tt-metal/issues/10320
- [x] https://github.com/tenstorrent/tt-metal/issues/10323
- [x] https://github.com/tenstorrent/tt-metal/issues/10324
- [x] https://github.com/tenstorrent/tt-metal/issues/10322

**Comment by mtairum** [comment]
#10322 has been fixed.

**Comment by ttmchiou** [comment]
all t3k workflows back and passing
