### ISSUE TITLE
stable diffusion demo hanging on N300 from v50 release tag

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#10366]
**Describe the bug**
Stable Diffusion demo hangs on v50 building both from source or from the whl. tried several reboots but did not help

**To Reproduce**
1. git checkout [v0.50.0](https://github.com/tenstorrent/tt-metal/tree/v0.50.0/models/demos/wormhole/mistral7b)
2. git submodule update --init --recursive
3. follow build from whl instructions from v50 branch
4. run SD demo: `pytest --disable-warnings --input-path="models/demos/wormhole/stable_diffusion/demo/input_data.json" models/demos/wormhole/stable_diffusion/demo/demo.py::test_demo`
5. the demo hangs mid-way (see screen shot attached)

**Expected behavior**
Demo to run fully and pass. 

**Screenshots**
<img width="1913" alt="Screenshot 2024-07-16 at 1 08 07 PM" src="https://github.com/user-attachments/assets/c7621ad4-29b9-46b4-aad0-9183086ec20f">

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software  [v0.50.0](https://github.com/tenstorrent/tt-metal/tree/v0.50.0/models/demos/wormhole/mistral7b)
- N300

**Comment by mywoodstock** [comment]
related: https://github.com/tenstorrent/tt-metal/issues/7560
