### ISSUE TITLE
Segmentation fault when closing device for Falcon7b decode-seq2048 perplexity test

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#10365]
Segmentation fault occurs after the test finishes as devices are being closed:
![image](https://github.com/user-attachments/assets/ffbe931f-81b1-4c9e-8660-ff31e04499de)

Branch: main
Command: `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/demos/falcon7b_common/tests/perplexity/test_perplexity_falcon.py::test_perplexity[True-decode_2048_l1_sharded] --timeout=1500`
Machine: `sjc-snva-t3018`

Also observed in this CI run: https://github.com/tenstorrent/tt-metal/actions/runs/9960678820/job/27521341341

**Comment by skhorasganiTT** [comment]
@aliuTT Are there still any remaining segfaults you are investigating? Would you be able to take a look?

**Comment by aliuTT** [comment]
Is this a regression or a new test?

**Comment by skhorasganiTT** [comment]
It's an existing test with a new sequence length (2048), so technically new. I previously saw a segfault for the same test with sequence length 1024 in #9268, but that one was fixed so not sure if it's related.

**Comment by aliuTT** [comment]
I probably won't have time to look at this until next week. Let me know if priority increases

**Comment by skhorasganiTT** [comment]
Closing this as I am no longer seeing the issue on latest main (d66ddd1).
