### ISSUE TITLE
Run ttnn single-card nightly on WH as well, as currently we only run GS

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#10395]
We only the ttnn `single_chip/nightly` script on GS.

We should run on X2 WH, see what fails, skip those and file issues, and put the rest in CI.

**Comment by tt-rkim** [comment]
@mywoodstock @vtangTT 
Leggooooo

**Comment by mywoodstock** [comment]
@tt-rkim could we please prioritize this? I would suggest P0 :)

**Comment by tt-rkim** [comment]
Sorry, no P0. This will stay P2.
