### ISSUE TITLE
Interpolate op support needed for Segformer_b0

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#10407]
Need support for ttnn Interpolate operation.

Example :
![Screenshot 1946-04-26 at 9 52 00 PM](https://github.com/user-attachments/assets/d88d80fe-3b60-4d1c-9adc-9136fcb66030)

Note: The above mentioned tensor shape is one the configuration which is used in segformer_b0 model.

**Comment by smehtaTT** [comment]
@mbahnasTT @dvartaniansTT - check for repeat interleave

**Comment by dvartaniansTT** [comment]
@HariniMohan0102 please see the comment above refer to the Stable Diffusion examples in TTNN.

**Comment by punithsekar** [comment]
@dvartaniansTT @smehtaTT , In stable diffusion we had interpolate with mode="nearest". So, we were able to replace interpolate with repeat interleave. Even we can use upsample instead of interpolate but unfortunately we have only ttnn interpolate with mode="nearest" feature only.

**Comment by mywoodstock** [comment]
#5725 https://github.com/tenstorrent/tt-metal/issues/5725

**Comment by shwetankTT** [comment]
@punithsekar Can you please help me with some of the shapes which are used in the Segformer_b0 model.

**Comment by punithsekar** [comment]
Sure @shwetankTT ,
The below are the test_cases for interpolate in segformer_model.
test case 1 : input shape = [1,256,128,128] , size=[128,128]
test case 2 : input shape = [1,256,64,64] , size=[128,128]
test case 3 : input shape = [1,256,32,32] , size=[128,128]
test case 4 : input shape = [1,256,16,16] , size=[128,128]

Note: Interpolate with mode="bilinear" is needed.

**Comment by shwetankTT** [comment]
raised a draft PR https://github.com/tenstorrent/tt-metal/pull/12385

**Comment by mywoodstock** [comment]
this is now in `main`
