### ISSUE TITLE
Demos (SD + Falcon) not working on 0.50.0 build from wheel

### ISSUE THREAD

**Issue by vshenoyTT** [tenstorrent/tt-metal#10412]
**Describe the bug**
Running demos for SD and Falcon throw errors when installation is done from wheel, according to the instructions on this [PR](https://github.com/tenstorrent/tt-metal/blob/81b4bc700f6e85d508d1bd19c6534e57a3972975/INSTALLING.md) using ([v0.50.0](https://github.com/tenstorrent/tt-metal/releases/tag/v0.50.0)). The same demos run properly when the linked instructions are used to install from source instead of wheel, using v0.50.0.

**To Reproduce**
1. Clone the repository `git clone https://github.com/tenstorrent/tt-metal.git'
2. `cd tt-metal`
3. `git submodule foreach 'git lfs fetch --all && git lfs pull'`
4. Download the 0.50.0v [wheel file](https://github.com/tenstorrent/tt-metal/releases/download/v0.50.0/metal_libs-0.50.0+wormhole.b0-cp38-cp38-linux_x86_64.whl)
5. `pip install <wheel_file.whl>`, which is `pip install metal_libs-0.50.0+wormhole.b0-cp38-cp38-linux_x86_64.whl` for this purpose
6. `export PYTHONPATH=$(pwd)`
7. `pip install -r tt_metal/python_env/requirements-dev.txt`
8. Run the demos
9. Falcon: `export WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml` and then `pytest --disable-warnings -q -s --input-method=cli --cli-input="YOUR PROMPT GOES HERE!"  models/demos/wormhole/falcon7b/demo_wormhole.py::test_demo[user_input0-default_mode_stochastic]`
10. SD: `export WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml` and then `pytest --disable-warnings --input-path="models/demos/wormhole/stable_diffusion/demo/input_data.json" models/demos/wormhole/stable_diffusion/demo/demo.py::test_demo`

**Expected behavior**
The demos should run properly. 

**Screenshots**
Both demos currently give the same error, so I have attached one below:
<img width="880" alt="Screenshot 2024-07-17 at 12 19 50 PM" src="https://github.com/user-attachments/assets/323570f0-ed4c-4ddf-8031-e92bd018038d">

**Please complete the following environment information:**
- Version of software ([v0.50.0](https://github.com/tenstorrent/tt-metal/releases/tag/v0.50.0))
- Wormhole N150

**Comment by tt-rkim** [comment]
@vshenoyTT @dvartaniansTT 

I'm not sure how you get that error... that seems to imply you don't have a compatible version of pytest. I also see that you have no conda environment or regular virtual environment, so you're using the system Python. That's a dangerous game.

I logged onto that machine and same account and created `rkim/tt-metal` with `v0.50.0` checked out and repeated your instructions. My run started to work:

```
(rkim_env) ttuser@sjc-lab-t3001:~/rkim/tt-metal$ pip3 install pip install metal_libs-0.50.0+wormhole.b0-cp38-cp38-linux_x86_64.whl

...
(rkim_env) ttuser@sjc-lab-t3001:~/rkim/tt-metal$ env | grep TT
SSH_TTY=/dev/pts/0
(rkim_env) ttuser@sjc-lab-t3001:~/rkim/tt-metal$ env | grep PYTHON
PYTHONPATH=/home/ttuser/vshenoy/tt-metal
CONDA_PYTHON_EXE=/home/ttuser/miniconda3/bin/python
(rkim_env) ttuser@sjc-lab-t3001:~/rkim/tt-metal$ export PYTHONPATH=$(pwd)
(rkim_env) ttuser@sjc-lab-t3001:~/rkim/tt-metal$ pytest --disable-warnings -q -s --input-method=cli --cli-input="YOUR PROMPT GOES HERE!"  models/demos/wormhole/falcon7b/demo_wormhole.py::test_demo[user_input0-default_mode_stochastic]
2024-07-18 14:41:23.885 | DEBUG    | ttnn:<module>:136 - Initial ttnn.CONFIG:
... 
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
                  Metal | INFO     | Enabling program cache on device 0
                  Metal | INFO     | Enabling program cache on device 0
2024-07-18 14:41:26.196 | INFO     | models.demos.falcon7b.demo.demo:run_falcon_demo_kv:184 - Tokenizing inputs...
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
2024-07-18 14:41:26.618 | INFO     | models.demos.falcon7b.demo.demo:preprocess_and_validate_inputs:76 - # of users: 1
2024-07-18 14:41:26.618 | INFO     | models.demos.falcon7b.demo.demo:preprocess_and_validate_inputs:77 - # of input tokens per user: 9
2024-07-18 14:41:26.619 | INFO     | models.demos.falcon7b.demo.demo:run_falcon_demo_kv:199 - Loading weights...
2024-07-18 14:41:26.619 | INFO     | models.demos.falcon7b.demo.demo:run_falcon_demo_kv:202 - Weights not found on machine; downloading weights...
^C^C                  Metal | INFO     | Closing device 0
                  Metal | INFO     | Disabling and clearing program cache on device 0
...
```

**Comment by tt-rkim** [comment]
Note that for the above, I also did

```
python3 -m venv rkim_env
source rkim_env/bin/activate
```

in `~/rkim/tt-metal` before continuing with the commands.

**Comment by vshenoyTT** [comment]
@tt-rkim Interesting, I did not use a venv when building from wheel because the instructions did not specify it. I was trying to follow the instructions exactly as written.

I think it would be good to add the steps of creating a python venv on the installation README for builds from wheel.

**Comment by tt-rkim** [comment]
Sounds good, I will put more explicit language about Python environments and recommending an isolated one in the installation instructions.
