### ISSUE TITLE
tt_lib.fallback and torch ops are not listed in perf sheet

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#10429]
**Describe the bug**
I have used some torch, tt_lib.fallback_ops operations in the pipeline but its not showing in the perf sheet.

**To Reproduce**
1. git checkout punith/perf_sheet_analyse ([punith/perf_sheet_analyse](https://github.com/tenstorrent/tt-metal/compare/main...punith/perf_sheet_analyse))
2. Run the command `./tt_metal/tools/profiler/profile_this.py -n perf -c "pytest /home/ubuntu/punith/tt-metal/models/experimental/perf_sheet_analyse.py"`

Note: Please build the profiling tool before running the above command.

I used the following commands to build the repo:

```
git submodule foreach 'git lfs fetch --all && git lfs pull'
git submodule update --init --recursive
export ARCH_NAME=grayskull
export TT_METAL_HOME=$(pwd)
export PYTHONPATH=$(pwd)
export TT_METAL_ENV=dev

./build_metal.sh
./create_venv.sh
source python_env/bin/activate

pip install -r ./tests/end_to_end_tests/requirements.txt
```

And  the following command to build the profiling, `./scripts/build_scripts/build_with_profiler_opt.sh`

**Environment information:**
- OS: Ubuntu 
- Device : Instance of GS and WH

**Additional context:**
I am attaching the performance sheet which I got from  running the profiling [ops_perf_results_performance_sheet_2024_07_18_06_58_45.csv](https://github.com/user-attachments/files/16279068/ops_perf_results_performance_sheet_2024_07_18_06_58_45.csv).
 I am only able to see the ttnn.add operation listed, which is the only ttnn op used in the pipeline.

**Comment by dvartaniansTT** [comment]
@punithsekar this issue is being reviewed at the moment. Until we get the full resolution please note: 

Basically we should not be using fallbacks
(https://tenstorrent.slack.com/archives/D057FC60YQ0/p1722011514332469)
```
# SPDX-FileCopyrightText: © 2024 Tenstorrent Inc.

# SPDX-License-Identifier: Apache-2.0


import torch
import ttnn

torch_input_tensor = torch.zeros(2, 4, dtype=torch.float32)

input_tensor = ttnn.from_torch(torch_input_tensor, dtype=ttnn.bfloat16)

# Recommended approach
tensor = ttnn.to_torch(input_tensor)
tensor = torch.nn.functional.silu(tensor)
output_tensor = ttnn.from_torch(tensor, dtype=ttnn.bfloat16)

# Alternative approach that works with some operations
output_tensor = ttnn.get_fallback_function(ttnn.silu)(input_tensor)
```

We should be going in and out of torch for “fallback ops”
(https://tenstorrent.slack.com/archives/D057FC60YQ0/p1722011534705609)
similar to the Recommended approach here

The op report will pickup the torch.nn call as a fallback

docs for this are being added
