### ISSUE TITLE
Models common RMS Norm doesn't support interleaved

### ISSUE THREAD

**Issue by mtairum** [tenstorrent/tt-metal#10448]
**Describe the bug**

Current rmsnorm implementation doesn't support interleave memory, only sharded. See file `models/common/rmsnorm.py`.

For Mixtral prefill we rely on the interleaved mode due to different seqlen supported. I've pushed a change that we're using inside the Mixtral prefill PR.
You can check the branch `mtairum/interleaved_rmsnorm` and the diff here: https://github.com/tenstorrent/tt-metal/compare/main...mtairum/interleaved_rmsnorm

**Comment by yieldthought** [comment]
Oh no I knew I forgot _something_, will fix today.

**Comment by yieldthought** [comment]
Merged
