### ISSUE TITLE
[Bug Report] ttnn `tensor_return_value_t = std::tuple<std::optional<Tensor>, ...>` not supported

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#10509]
**Describe the bug**

I am attempting to implement `moreh_layernorm` according to the above document. (https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/adding_new_ttnn_operation.html)

`moreh_layernorm` has three optional outputs(output, mean, rstd), so I set `using tensor_return_value_t = std::tuple<std::optional<Tensor>, std::optional<Tensor>, std::optional<Tensor>>;` , but a build error occurred.

```C++
template <typename concrete_operation_t, typename T>
auto map_execute_on_worker_thread_return_to_launch_op_return(const T&& value) -> Tensors {
    if constexpr (std::is_same_v<std::decay_t<decltype(value)>, Tensors>) {
        return value;
    } else if constexpr (std::is_same_v<std::decay_t<decltype(value)>, Tensor>) {
        return {value};
    } else if constexpr (is_homogenous_tuple<T, Tensor>()) {
        Tensors output_tensors;
        output_tensors.reserve(std::tuple_size_v<T>);
        std::apply(
            [&output_tensors](auto&&... args) {
                (output_tensors.emplace_back(std::forward<decltype(args)>(args)), ...);
            },
            value);
        return output_tensors;
    } else {
        static_assert(
            tt::stl::concepts::always_false_v<concrete_operation_t>,
            "Operation must return either a single Tensor or a vector of Tensors or implement "
            "map_execute_on_worker_thread_return_to_launch_op_return.");
    }
}
```
Looking at the code, it seems that the implementation for optional tensor tuples is still missing.

**To Reproduce**
1. checkout https://github.com/tenstorrent/tt-metal/tree/hyungsuk/debug_tnn_tuple_optional_tensor
2. Please attempt to build it.
3. See error
![image](https://github.com/user-attachments/assets/c90716b4-849e-4735-bdd1-bde78bcebd29)

**Expected behavior**

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)
- arch_name: wormhole_b0

**Additional context**

**Comment by dmakoviichuk-tt** [comment]
Tuple of optional tensors is not supported but I can implement it. 
Doesn't look too hard.

**Comment by dmakoviichuk-tt** [comment]
@hschoi4448 I've added fix to the map_execute_on_worker_thread here DM/debug_tnn_tuple_optional_tensor
It doesn't work yet but I've moved further. Now it requires to implement create_async_output_tensors which should return OptionalTensors in your case.

**Comment by hschoi4448** [comment]
>I've added fix to the map_execute_on_worker_thread here DM/debug_tnn_tuple_optional_tensor
It doesn't work yet but I've moved further. Now it requires to implement create_async_output_tensors which should return OptionalTensors in your case.

So, if I implement `create_async_output_tensors` now, can I use a tuple of optional tensors?
or do I need to wait for another issue to be resolved?

**Comment by hschoi4448** [comment]
>I've added fix to the map_execute_on_worker_thread here DM/debug_tnn_tuple_optional_tensor
It doesn't work yet but I've moved further. Now it requires to implement create_async_output_tensors which should return OptionalTensors in your case.

So, if I implement `create_async_output_tensors` now, can I use a tuple of optional tensors?
or do I need to wait for another issue to be resolved? @dmakoviichuk-tt

**Comment by dmakoviichuk-tt** [comment]
@hschoi4448  I'd like to see if it works. I am not sure about right implementation of the create_async_output_tensors.
If you implement it I'd try to fix next errors if there are any :)

**Comment by hschoi4448** [comment]
```C++
    static inline std::vector<Tensor> create_async_output_tensors(
        const std::vector<Tensor> &input_tensors, const std::vector<std::optional<const Tensor>>& optional_inputs) {
        const auto& input_tensor = input_tensors.at(0);
        return {Tensor(operation::get_workers_for_op_output({input_tensor})),
                                            Tensor(operation::get_workers_for_op_output({input_tensor})),
                                            Tensor(operation::get_workers_for_op_output({input_tensor}))};
    }
```
I tried implementing create_async_output_tensors as shown above, but the build errors still persist. 
in `ttnn/cpp/ttnn/operations/moreh_layernorms/moreh_layernorm/moreh_layernorm.hpp`

I think it would be easier for you to check if I commit the changes I made to `DM/debug_tnn_tuple_optional_tensor`. Is it okay if I commit them?
@dmakoviichuk-tt

**Comment by arakhmati** [comment]
@hschoi4448 do you guys use async mode? if not please use `execute_on_main_thread` method as described here: https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/adding_new_ttnn_operation.html#id5

**Comment by hschoi4448** [comment]
>@hschoi4448 do you guys use async mode? if not please use execute_on_main_thread method as described here: https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/adding_new_ttnn_operation.html#id5

I am not yet sure what async mode exactly is. Where can I find information about this?
Please provide documentation on async mode so I can verify if this feature is needed by our team.
based on the name, it seems necessary for performance optimization.


>@hschoi4448 I'd like to see if it works. I am not sure about right implementation of the create_async_output_tensors.
If you implement it I'd try to fix next errors if there are any :)

The reason I tried to use `create_async_output_tensors` is that I was asked to test it in the comment above.
And using `execute_on_main_thread`, I couldn't set a tuple of optional vectors as `tensor_return_value_t`.

If we can define multiple optional tensor returns properly, the method does not matter.
@arakhmati

**Comment by ayerofieiev-tt** [comment]
@arakhmati can you please share some ETA?
