### ISSUE TITLE
CI: build with address sanitization

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#10504]
Someone recently built w/ ASAN and filed some issues, one of which turned out to be a real bug in UMD (fixed now).
These are the types of errors that could creep in to our code base.
I suggest we build in CI w/ address checking periodically.  I don't think this needs to run on every commit, but perhaps daily?

**Comment by TT-billteng** [comment]
OK sounds good

**Comment by TT-billteng** [comment]
Closing in favor of #11453
