### ISSUE TITLE
Conv fails with OOM issue in unit tests

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#10511]
**Describe the bug**
On unit testing the conv ops of model_k, for the input resolution 256x256:
- Run the following command to reproduce the issue: `pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_model_k_256x256_failing_convs`
- Among 7 convs, 3 convs passed. 4 convs fail with Out of Memory issue.
```
E       RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:143: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 25477120 B L1 buffer across 5 banks, where each bank needs to store 5095424 B
```

On unit testing the conv ops of model_k, for the input resolution 128x128:
- - Run the following command to reproduce the issue: `pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_model_k_128x128_failing_convs`
- Among 7 convs, 4 convs passed. 3 convs fail with Out of Memory issue.
```
E       RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:143: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 4636672 B L1 buffer across 1 banks, where each bank needs to store 4636672 B
```

**To Reproduce**
1. Checkout to the branch[harini/model_k_failing_convs](https://github.com/tenstorrent/tt-metal/compare/harini/model_k_failing_convs)
2. Run the respective commands in each input resolution to reproduce the issues.

**Expected behavior**
To run conv op for the specific input configurations without error.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: n150

**Comment by dvartaniansTT** [comment]
@HariniMohan0102 and @punithsekar please clearly list which convs are failing with details like, input resolution, filter size, input output channels, stride, dilation, ... 

For instance, for Klassify, we lowered the resolution for some convs to get them to pass. However, we still need support for the original resolution and they must be included in the unit tests with the original resolution and marked as failing.

**Comment by HariniMohan0102** [comment]
@dvartaniansTT updated the issue description and Readme with the required details of failing cases. Please check.

**Comment by dvartaniansTT** [comment]
@HariniMohan0102 please test the dilation> 1 and confirm if they pass now.

**Comment by HariniMohan0102** [comment]
@dvartaniansTT On testing, all the dilation >1 input configurations passed.
Further, updated the issue description with the other failing convs (OOM issue).

**Comment by dvartaniansTT** [comment]
@mywoodstock and @HariniMohan0102 can we close this issue now or still valid?

**Comment by HariniMohan0102** [comment]
@dvartaniansTT The issue is still valid.
The conv unit test for higher resolution (256x256) still fails with OOM error.
The conv unit test for lower resolution (128x128) was failing with OOM error when tested previously.
Note: Yet to unit test conv cases with the latest main, especially for lower resolution.

**Comment by mywoodstock** [comment]
@HariniMohan0102 Could you please retry these tests with the latest `main`, I see that only 2 of them fail now with OOM, rest all good. Please let me know what you see.

**Comment by HariniMohan0102** [comment]
@mywoodstock  I'll test with latest main and update soon.

**Comment by HariniMohan0102** [comment]
@mywoodstock I've tested with the latest main. Few convs passed. 
In 256x256 resolution, 3 convs fails.
In 128x128 resolution, 1 conv fails.
I've updated the issue description and unit test branch, please check.
Thank you.

**Comment by pavlejosipovic** [comment]
I've tried it out on latest main (ab3dc0c4f5c3ce9722261c878970bfa92a212fc9) and only this once conv is failing
`(1, 256, 128, 223, 223, 1, 1, 1, 1, 0, 0, 1, 1, 1, True, None, "relu", True), # Fails with L1 issue`
This is conv2d which maps to matmul op (we call matmul device op for this one).
I haven't focused on improving L1 out-of-memory issues for this type of convs yet, as we don't have many issues with them in torch traces, but I have a plan how to go about them. 
Depending on how urgent is to get this one running we can prfioritize this work.

**Comment by HariniMohan0102** [comment]
I'll replace the falling conv with matmul and confirm about the rest of the convs after testing on the latest main.
cc: @dvartaniansTT

**Comment by HariniMohan0102** [comment]
I've tested the convs in latest main, except the failing conv, rest of the convs are passing.
Regarding the failing conv, I've tried flattening the input and weight of conv and used matmul operation. I am able to get the required output shape, but the PCC comparing the torch conv and ttnn matmul is very poor i.e. (0.003)

@mbahnasTT Can we close this issue for now, as we don't use the specific failing configuration(resolution 256x256) in our current model pipeline(resolution 128x128)? Also, do we need to create another issue of specific conv failure on matmul (low pcc) to keep a track of it?

**Comment by pavlejosipovic** [comment]
If you are not using this particular instance that is failing, I would at least demote this issue from P0->P1

**Comment by mbahnasTT** [comment]
I'll demote it for now, because I discussed with Abhinav that we need the high resolution 1k*1k on that model. @mywoodstock will update us by next week.

**Comment by pavlejosipovic** [comment]
I have pull request that resolves the last failing test case 
https://github.com/tenstorrent/tt-metal/pull/15861

**Comment by pavlejosipovic** [comment]
Fix is merged
