### ISSUE TITLE
TTNN - incomplete documentation for backward ops for add, addalpha, addcdiv and addcmul  

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#10514]
**For add_bw (unary):**
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, it seems that it does support both BFLOAT16 and BFLOAT8_B types; both TILE and ROW_MAJOR are supported; Ranks up to 4 appear to work; SYSTEM_MEMORY for input tensors is not supported. 
When grad tensor is on a host device, next error is thrown:

```
E       RuntimeError: TT_THROW @ ../ttnn/cpp/ttnn/experimental/tensor/tensor.hpp:351: tt::exception
E       info:
E       MemoryConfig can only be obtained for a tensor with DeviceStorage
```
, and when an input tensor is on a host device, next this error is thrown:
```
E       RuntimeError: bad_variant_access
```

**For add_bw (eltwise):**
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, it seems that it does support both BFLOAT16 and BFLOAT8_B types; ROW_MAJOR is not supported; Ranks up to 4 appear to work; SYSTEM_MEMORY for the first two tensor arguments is not supported.
When running op with ROW_MAJOR layout, error is thrown:

```
E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:199: (input_tensor_a.get_layout() == Layout::TILE && input_tensor_b.get_layout() == Layout::TILE)
E       info:
E       Inputs to eltwise binary must be tilized
```
When the second tensor argument is on a host device, next error is thrown:

```
E       RuntimeError: TT_THROW @ ../ttnn/cpp/ttnn/experimental/tensor/tensor.hpp:351: tt::exception
E       info:
E       MemoryConfig can only be obtained for a tensor with DeviceStorage
```
, and when the first tensor argument is on a host device, this error is thrown:

```
E       RuntimeError: TT_THROW @ ../ttnn/cpp/ttnn/experimental/tensor/tensor.hpp:338: tt::exception
E       info:
E       Cannot get the device from a tensor with host storage
```

**For addalpha_bw:**
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, it seems that it does support both BFLOAT16 and BFLOAT8_B types; ROW_MAJOR is not supported; Ranks up to 4 appear to work; SYSTEM_MEMORY for input tensors is not supported. When running the op with ROW_MAJOR layout, the error is thrown:

```
E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:199: (input_tensor_a.get_layout() == Layout::TILE && input_tensor_b.get_layout() == Layout::TILE)
E       info:
E       Inputs to eltwise binary must be tilized
```

, and when one of the first two input tensor arguments is on a host device, this error is thrown:

```
E       RuntimeError: TT_THROW @ ../ttnn/cpp/ttnn/tensor/tensor.hpp:338: tt::exception
E       info:
E       Cannot get the device from a tensor with host storage
```

**For addcmul_bw:**
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, it seems that it does support both BFLOAT16 and BFLOAT8_B types; ROW_MAJOR is not supported; Ranks up to 4 appear to work; SYSTEM_MEMORY for input tensors is not supported. When running the op with ROW_MAJOR layout, the error is thrown:

```
E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:199: (input_tensor_a.get_layout() == Layout::TILE && input_tensor_b.get_layout() == Layout::TILE)
E       info:
E       Inputs to eltwise binary must be tilized
```

, and when one of the first two input tensor arguments is on a host device, this error is thrown:

```
E       RuntimeError: TT_THROW @ ../ttnn/cpp/ttnn/tensor/tensor.hpp:351: tt::exception
E       info:
E       MemoryConfig can only be obtained for a tensor with DeviceStorage
```
, and when the third is on a host device, this error is thrown:

```
E       RuntimeError: bad_variant_access
```

**For addcdiv_bw:**
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, it seems that it does support both BFLOAT16 and BFLOAT8_B types; both TILE and ROW_MAJOR are supported Ranks up to 4 appear to work; SYSTEM_MEMORY for input tensors is not supported. When running the op with ROW_MAJOR layout, the error is thrown:

```
E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:199: (input_tensor_a.get_layout() == Layout::TILE && input_tensor_b.get_layout() == Layout::TILE)
E       info:
E       Inputs to eltwise binary must be tilized
```

, and when one of the first two input tensor arguments is on a host device, this error is thrown:

```
E       RuntimeError: TT_THROW @ ../ttnn/cpp/ttnn/tensor/tensor.hpp:351: tt::exception
E       info:
E       MemoryConfig can only be obtained for a tensor with DeviceStorage
```
, and when the third is on a host device, this error is thrown:

```
E       RuntimeError: bad_variant_access

**Comment by VirdhatchaniKN** [comment]
Hi @amalbasaTT 
Issue has been addressed and merged to main. Can we close this ?
<img width="764" alt="Screenshot 2024-08-07 at 12 27 52 PM" src="https://github.com/user-attachments/assets/05a95280-aca7-4fec-a2a5-cbdf3fe67e22">

<img width="747" alt="Screenshot 2024-08-07 at 12 27 18 PM" src="https://github.com/user-attachments/assets/92fe435f-573e-4f7c-85ff-04082fba68ce">
<img width="771" alt="Screenshot 2024-08-07 at 12 27 37 PM" src="https://github.com/user-attachments/assets/f9651a8f-ee9b-49de-8b0f-05e8f9ec01ec">

<img width="786" alt="Screenshot 2024-08-07 at 12 26 56 PM" src="https://github.com/user-attachments/assets/57ef4d2b-0526-4a65-a891-4bca291c6dda">

**Comment by amalbasaTT** [comment]
@VirdhatchaniKN, yes i will close it.
