### ISSUE TITLE
Override runutime args are not matching the non override runtimeargs

### ISSUE THREAD

**Issue by ygiladTT** [tenstorrent/tt-metal#10524]
The override lambda function in the file op_library/concat/multi_core/concat_op_multi_core.cpp
function : s2s_rm_concat_multi_core 
are not matching the actual runtime argument setting earlier in the function , meaning that when there is a cache hit on the op, it is not going to update the runtime arguments correctly.
please make sure to update the override function of this function and potentially test cache hit cases so that such issues could be captured

**Comment by tt-aho** [comment]
@tarafdarTT I think you made changes to this fn/args a while back, and looks like the override wasn't updated

**Comment by tarafdarTT** [comment]
@jaykru-tt could you look at this. It's a matter of modifying the override runtime args to make sure it matches the normal one.

**Comment by ntarafdar** [comment]
Fixed in main.
