### ISSUE TITLE
AddrGens inside dataflow_api.h has inconsistent behaviour regarding page alignment

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#10539]
Ex. `InterleavedAddrGen` will automatically align the passed in page size to a multiple of 32B, whereas `InterleavedPow2AddrGen` does not do any sort of alignment. This behaviour makes it not straightforward for the user since this is somewhat hidden, so for the same page size and different addr gens the user will see different behaviour/issues. The hardcoded alignment is also incorrect for BH, which has 64B dram alignment.

We've recently added an `aligned_page_size` getter to the host buffer api, so from the initial discussion the consensus was to remove the implicit alignment from any addr gens, and have them potentially assert instead. Users writing/using kernels will be expected to pass in aligned page sizes themselves to the addr gen, and use the real page size when issuing reads/writes if needed instead.

fyi @abhullar-tt @pgkeller

**Comment by abhullar-tt** [comment]
Good catch, the reason I haven't hit this on BH yet is because the page sizes provided by host have typically also been 32B aligned

**Comment by tt-aho** [comment]
The addr gens now use the value of ALLOCATOR_ALIGNMENT to align pages instead of being hardcoded to 32.
