### ISSUE TITLE
Width Sharded Height Concat for Row Major Tensors

### ISSUE THREAD

**Issue by ntarafdar** [tenstorrent/tt-metal#10547]
We wish to add a width sharded height concat operation. 

**The Problem**

First lets visualize the full tensors (unsharded) and look at what we mean by height concat.

![image](https://github.com/user-attachments/assets/c48ce223-979a-4463-9a0d-05bb27334b71)

The Height Concatenated tensor will be what the tensor looks like on the host. However the tensors are sharded, meaning that per core in the L1s we will have a subset of the tensor. This is what it looks like per core, not that each core has a portion of both tensors.

![image](https://github.com/user-attachments/assets/196457a9-9047-4bb5-a8df-d50a004b2e5c)

Per core the operation would be a height concat of the respective shards. 

![image](https://github.com/user-attachments/assets/53058c6c-4483-4783-8fcf-2425c6b66021)

**How to Solve It**

We already have implemented a solution for height sharded tensors that need to be width concat.  
1. https://github.com/tenstorrent/tt-metal/blob/main/ttnn/cpp/ttnn/experimental/tt_dnn/op_library/concat/multi_core/concat_op_multi_core.cpp#L156

This is the host code for height sharded, width concat. 
You will see that the tensor is in **Row Major Format**.  This is standard format where the elements are in row-major order. We have the notion of a page , which is the smallest granularity of memory. In a row-major tensor , a page is equivalent to a single row in height, and the width of a shard.
In a height sharded example, that is the entire input tensor. In the width shared case, that will be equivalent to the width of the shard.

2. This is the corresponding kernel. https://github.com/tenstorrent/tt-metal/blob/main/ttnn/cpp/ttnn/experimental/tt_dnn/op_library/concat/kernels/dataflow/reader_height_sharded_width_concat.cpp

**Test Cases**
In order to test we need to make a width Sharded tensor.  This makes a width Sharded tensor 64x32 each across 2 cores . the output data at the end should be the same as concatting the input with itself on dim 2. 

```
    input_data = torch.randn(shape, dtype=torch.bfloat16)
    x = ttnn.from_torch(
        [1, 1, 64, 64],
        device=device,
        layout=ttnn.ROW_MAJOR_LAYOUT,
        memory_config=ttnn.L1_MEMORY_CONFIG,
        dtype=ttnn.bfloat16,
    )
    shard_config = ttnn.create_sharded_memory_config(
        shape=[1, 1, 64, 64],
        core_grid=ttnn.CoreGrid(y=2, x=1),
        strategy=ttnn.ShardStrategy.WIDTH,
        orientation=ttnn.ShardOrientation.ROW_MAJOR,
        use_height_and_width_as_shard_shape=False,
    )
    x_t = ttnn.to_memory_config(x, memory_config=shard_config, dtype=ttnn.bfloat16)
    y_t = ttnn.concat(x_t, x_t, dim=2)
    y_h = ttnn.from_device(x_t)
    output_data = ttnn.to_torch(y_h)
    

```

**Comment by jerrysky3** [comment]
I started working on this and here is my attempt to support width sharded height concat https://github.com/tenstorrent/tt-metal/pull/13314. Please let me know if you have any feedback, thanks!

**Comment by ayerofieiev-tt** [comment]
@ntarafdar , we think it’s done now.
