### ISSUE TITLE
update build script to make it easier to maintain multiple build types at once

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#10552]
At the metal F2F, a couple people were unaware that we still have a build that supports asserts+debug info+optimized (RelWithDebInfo).

w/ the new process I'm finding it hard to leverage building release, RelWithDebInfo and dbg and keep all alive at once.  I wrote some bash functions to handle this, but got them wrong and so have gone back to using the build script

while clearly I need to learn better how to use cmake+ninja, I think the supported build script should contain a way to do the above easily through the script.

I propose 1 cmd line arg of "rel", "dbg", "dev" to build the 3 flavors and put them into their own dirs (build, build_dbg, build_dev).

Filed for tracking/discussion.

**Comment by TT-billteng** [comment]
I was hoping to keep the `build_metal.sh` script as basic as possible and ask devs to run cmake manually with `-DCMAKE_BUILD_TYPE=Debug/RelWithDebInfo/Release` as this is what I'd consider common knowledge for CMake users
