### ISSUE TITLE
Hang Issue in Compute Kernel

### ISSUE THREAD

**Issue by dongjin-na** [tenstorrent/tt-metal#10571]
**Describe the bug**
In general, data flow in CB between Data Movement Kernel (DMVK) and Compute Kernel is as follows.

![cb_flow1 drawio (1)](https://github.com/user-attachments/assets/f950326f-ec31-4285-9680-53132f662cd0)
Fig.1 Data Flow in CB between Data Movement Kernel and Compute Kernel

While implementing the operation, we encountered a hang issue at the seventh step of the `cb_reserve_back` API when the pop and push operations were repeatedly executed within the compute kernel, as shown in the diagram below. 
![cb_flow2 drawio](https://github.com/user-attachments/assets/1888a367-48c7-4ea7-a3fd-c55586e9737f)
Fig.2 Detailed Data Flow and Loop in Compute Kernel

I have added test code in the `hang_in_compute_kernel` branch by slightly modifying moreh_sum code.

The sequence appears to be correct, but we need to verify if this kernel implementation violates any guidelines or if it is indeed a bug.

**To Reproduce**
1. git checkout origin/hang_in_compute_kernel
2. CONFIG=Debug ./build_metal.sh
3. source ./python_env/bin/activate
4. export TT_METAL_DPRINT_CORES=0,0
5. pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_sum.py::test_compute_kernel_hang

**Expected behavior**
No kernel hang occurs.

**Screenshots**
```bash
$ pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_sum.py::test_compute_kernel_hang

 ......

loop 0 / 8
before cb_reserve_back
after cb_reserve_back
loop 1 / 8
before cb_reserve_back
after cb_reserve_back
loop 2 / 8
before cb_reserve_back
```
Related kernels are:
- `ttnn/cpp/ttnn/experimental/tt_dnn/op_library/moreh_sum/moreh_sum_nc_impl/kernels/moreh_sum_nc.cpp`
- `ttnn/cpp/ttnn/experimental/tt_dnn/op_library/moreh_sum/moreh_sum_nc_impl/kernels/reader_moreh_sum_nc.cpp`

**Additional context**
- OS: Ubuntu 20.04 / 172.27.44.100 VM
- Version of software (eg. commit)
commit 0ddee05d93f816d8cab3efba4aaff6040ce0b549 (HEAD -> pack_uint32_to_uint8, origin/main, origin/HEAD)
Author: Nenad Petrovic <109360062+npetrovic-tenstorrent@users.noreply.github.com>
Date:   Mon Jul 22 15:25:21 2024 +0200

    RDIV migration to TTNN (#10389)

    * #10147: Add rdiv test corrections

    * #10147: Corrected the naming of rdiv op test

    * #10147: naming modify

    * #10147: Linter applied

    * #10147: Linter applied

    * #10147: fix opmap

**Comment by amahmudTT** [comment]
The link takes me to a PR that is already merged. If I checkout the mentioned commit ID I do not see any file named or any file containing the string "kernel_hang".  In short I cannot find the code to reproduce the problem. Is this issue supposed to be closed ? @dongjin-na

**Comment by amahmudTT** [comment]
I cannot see any test code, but the pseudocode is using cb_push_back from both the reader and the compute kernels. But the guideline says this will produce nondeterministic  behaviour. See File  ```./tt_metal/include/compute_kernel_api/cb_api.h```

``` * Important note: This operation updates the read pointer of the CB, the CB pointer
 * can only be updated from one thread at a time. Example: if compute kernel has cb_pop_front(input_id, 1)
 * and writer kernel also has cb_pop_front(input_id, 1), these calls will produce non-deterministic behavior because
 * cb pointers are not synchronized across threads. Per circular buffer index, only have one thread pop tiles
 * to update the read pointer
 *
 * Return value: None
 *
 * | Argument  | Description                          | Type     | Valid Range                                                                                       | Required |
 * |-----------|--------------------------------------|----------|---------------------------------------------------------------------------------------------------|----------|
 * | cb_id     | The index of the cirular buffer (CB) | uint32_t | 0 to 31                                                                                           | True     |
 * | ntiles    | The number of tiles to be popped     | uint32_t | It must be less or equal than the size of the CB (the total number of tiles that fit into the CB) | True     |
 */
ALWI void cb_pop_front(uint32_t cbid, uint32_t ntiles) {
    UNPACK(( llk_pop_tiles(cbid, ntiles)  ));
}
```

**Comment by dongjin-na** [comment]
Dear @amahmudTT , thanks for the check.
1. You can run the test script using `the hang_in_compute_kernel` [branch](https://github.com/tenstorrent/tt-metal/tree/hang_in_compute_kernel).
2. Regarding your feedback, as shown in Fig. 2, once the compute kernel (thread) receives a tile from the reader kernel, only the compute kernel handles the CB afterward. This ensures that there is no overlap where more than one thread accesses the same CB simultaneously. What do you think?

**Comment by amahmudTT** [comment]
Seems like the header of the circular buffer is getting corrupted in the compute kernel. As when printed from reader cb 24 gives the following information 

cb_id 24: { size: 128, limit: 7254, page_size: 128, num_pages: 1, rd_ptr: 7126, wr_ptr: 7126, wr_tile_ptr: 0 }

When viewed from the compute kernel it gives this 
UNPACK cb_id 24: { size: 128, limit: 7254, page_size: 128, num_pages: 0, rd_ptr: 7126, wr_ptr: 0, wr_tile_ptr}

Note write pointer is zero and num-ages is also zero

**Comment by amahmudTT** [comment]
Hello @dongjin-na  with some help from @rtawfik01  it seems we cannot write to the same buffer using the same handle from two threads even if we are not doing it at the same time. This way the handle or control flow information including the read write pointers will get corrupted. Sorry it is not made clear in the api for functions like cb_reserve_back, where it says only one thread can write at a time ( I will update the information) . 

But there is a way to still do what you wanted to do. We can write to the same memory location in L1 memory from two threads but we need two separate handles. An example of that can be found in the function 
```tt_metal::Program create_program_single_core``` in file ```./tests/tt_metal/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm.cpp```

I am copy pasting a portion of the code (with removed lines) 

```
tt_metal::Program create_program_single_core (
    tt::DataFormat cb_data_format,
    std::shared_ptr<tt::tt_metal::Buffer> out_cb_addr
) {

    uint32_t out_cb_index = 16;  // output operands start at index 16
    uint32_t interm0_cb_index = 24;
    std::map<uint8_t, tt::DataFormat> partials_and_out_data_format_spec = {
        {out_cb_index, cb_data_format}, {interm0_cb_index, cb_data_format}};
    tt_metal::CircularBufferConfig cb_out_config =
        tt_metal::CircularBufferConfig(out_CB_size, partials_and_out_data_format_spec)
            .set_page_size(interm0_cb_index, single_tile_size)
            .set_page_size(out_cb_index, single_tile_size)
            .set_globally_allocated_address(*out_cb_addr);
    auto cb_out = tt_metal::CreateCircularBuffer(program, CoreRangeSet({all_cores}), cb_out_config); 
}
```

In the above code, circular buffers at index 16 (out_cb_index) and 24(interm0_cb_index) share the same memory, and for your example Reader could probably write to out_cb_index while the compute thread could use the loop on item0_cb_index.

Hope this helps and please let me know if you have any question.

**Comment by dongjin-na** [comment]
Hello, @amahmudTT.

Thanks for the detailed analysis.
I have a question to clarify.
To achieve something like what’s shown in Fig 2, as you suggested, would it be correct to use two CBs that share the same L1 memory like this?

```c++
/////////////////////////
// Reader kernel
/////////////////////////
cb_reserve_back(out_cb, 1);
cb_push_back (out_cb, 1);

/////////////////////////
// Compute kernel
/////////////////////////

//Wait for one tile to be pushed to out_cb.
cb_wait_front(out_cb, 1);

// Now iterm0_cb takes that tile.
cb_reserve_back(iterm0_cb, 1);
cb_push_back(iterm0_cb, 1);

for ( ...... ) {
  cb_wait_front(iterm0_cb, 1);
  // Do something ......
  cb_pop_front(iterm0_cb, 1);

  cb_reserve_back(iterm0_cb, 1);
  pack_tile(0, iterm0_cb, 1);
  cb_push_back(iterm0_cb, 1);
}
```

**Comment by dongjin-na** [comment]
Thanks for the clarification. Please update the documentation with this information. I will go ahead and close this issue. :)
