### ISSUE TITLE
TTNN backward ops - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#10585]
For all TTNN backward ops:
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). 
In practice, it seems that it does support BFLOAT16 and TILE layout.
However, ROW_MAJOR seems not to be supported for any of these ops.
BFLOAT8_B seems to be sometimes supported, but with low PCC.
Supported ranks are also not mentioned, but execution was successful for 2,3,4.

- [x] #11086
- [x] #11084
- [x] #11085

**Comment by mcw-anasuya** [comment]
Docs have been updated with supported types, layouts and range. 
Closing this master issue.
