### ISSUE TITLE
ReduceScatter does not support Async mode

### ISSUE THREAD

**Issue by djordje-tt** [tenstorrent/tt-metal#10584]
ReduceScatter CCL op does not support Async mode of execution. This mode improves e2e perf in LLM models and for efficient using of ReduceScatter we need Async mode supported. 

Here is an example how support is added: https://github.com/tenstorrent/tt-metal/commit/69661dfc136cf91565ae423ecafdcf37269c1874

It's a bit harder to reproduce hang we are seeing since for running Falcon40b it's required ~1hr to download weights and generate binaries before test executes but I will put command here: 
```
TT_METAL_ASYNC_DEVICE_QUEUE=1 WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/demos/t3000/falcon40b/tests/test_perf_falcon.py::test_perf_bare_metal[wormhole_b0-True-falcon_40b-prefill_seq128_bfp8-8chips]
```

**Comment by SeanNijjar** [comment]
Changes have been merged

**Comment by djordje-tt** [comment]
Thanks for the fix!
