### ISSUE TITLE
TTNN backward log and neg - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#10603]
For all TTNN backward ops - neg and log:
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE).
In practice, it seems that it does support BFLOAT16 and TILE layout.
However, ROW_MAJOR seems not to be supported for any of these ops.
BFLOAT8_B seems to be sometimes supported, but with low PCC.
Supported ranks are also not mentioned, but execution was successful for 2,3,4.

**Comment by VirdhatchaniKN** [comment]
Fix provided in #11251

**Comment by VirdhatchaniKN** [comment]
Merged To main
