### ISSUE TITLE
llama on TG codeowners change

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent/tt-metal#10617]
Hi,
Could you please make the following people owners of `models/demos/tg/llama3_70b`?
@cglagovich 
@caixunshiren

**Comment by tt-rkim** [comment]
Hey you could just put up whatever changes to CODEOWNERS and it'll tag me automatically to review

No need for me to block you on this. for example: https://github.com/tenstorrent/tt-metal/pull/10490
