### ISSUE TITLE
[Bug Report] FAILED models/demos/resnet/demo/demo.py::test_demo_sample[20-models/demos/resnet/demo/images/-device_params0] - RuntimeError: TT_FATAL @ ../tt_metal/impl/allocator/allocator.cpp:123: num_shards.value() <= num_compute_banks

### ISSUE THREAD

**Issue by jaebaek** [tenstorrent/tt-metal#10636]
**Describe the bug**
I followed [this paragraph](https://github.com/tenstorrent/tt-metal/blob/6f0bfda1e4b4bd9d05589219b2c797ee6bb2d302/models/demos/resnet/README.md#how-to-run) to test resnet.

**To Reproduce**
1. Download tt-metal and build it based on the https://github.com/tenstorrent/tt-metal/blob/main/INSTALLING.md
2. Run `export TT_METAL_ENV=dev && export TT_METAL_HOME=$PWD && export ARCH_NAME=grayskull && export PYTHONPATH=$TT_METAL_HOME`
3. And run `pytest --disable-warnings models/demos/resnet/demo/demo.py::test_demo_sample[20-models/demos/resnet/demo/images/-device_params0]`

**Expected behavior**
This is my first to run it. I expected it runs fine.

**Screenshots**
The attachment contains the error messages I got.

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Built from
```
commit dee91cfa86b077ddc0ff2bdd941172048693ce93 (HEAD -> main, tag: v0.51.0-rc11, origin/main, origin/HEAD)
Author: Colman Glagovich <114512306+cglagovichTT@users.noreply.github.com>
Date:   Tue Jul 23 20:17:09 2024 -0400

    Update README.md with Llama3.1 numbers (#10630)
```

**Additional context**
- Hardware: GraySkull e75
[log.txt](https://github.com/user-attachments/files/16357086/log.txt)

**Comment by ayerofieiev-tt** [comment]
@jaebaek , most demo models do not support e75 and are aiming higher end cards, including the resnet model. 
It is a gap in our doc and I am working with the team now to address it.

**Comment by jaebaek** [comment]
Thanks. Let me close this issue.

**Comment by kishoryd** [comment]
I have faced the same issue while running on wormhole n300 cards. 

To run the demo: pytest --disable-warnings models/demos/wormhole/resnet50/demo/demo.py::test_demo_sample

[ResNet50-error.txt](https://github.com/user-attachments/files/21888587/ResNet50-error.txt)
