### ISSUE TITLE
TTNN where and sub backward - incomplete documentation 

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#10646]
For all TTNN backward ops - where and rsub:
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE).
In practice, it seems that it does support BFLOAT16 and TILE layout.
However, ROW_MAJOR seems not to be supported for any of these ops.
BFLOAT8_B seems to be sometimes supported, but with low PCC.
Supported ranks are also not mentioned, but execution was successful for 2,3,4.

**Comment by VirdhatchaniKN** [comment]
Hi @npetrovic-tenstorrent 
Issue has been addressed and merged to main. Can we close this issue ? 
<img width="783" alt="Screenshot 2024-08-07 at 12 22 18 PM" src="https://github.com/user-attachments/assets/5dc8de2a-1024-405f-a2b1-587fd59237e3">
<img width="794" alt="Screenshot 2024-08-07 at 12 22 30 PM" src="https://github.com/user-attachments/assets/15b0a9aa-ec23-462b-864c-10d57f29bcfb">

**Comment by npetrovic-tenstorrent** [comment]
> Hi @npetrovic-tenstorrent Issue has been addressed and merged to main. Can we close this issue ? <img alt="Screenshot 2024-08-07 at 12 22 18 PM" width="783" src="https://private-user-images.githubusercontent.com/138196495/355707027-5dc8de2a-1024-405f-a2b1-587fd59237e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDg4OTcsIm5iZiI6MTcyMzA0ODU5NywicGF0aCI6Ii8xMzgxOTY0OTUvMzU1NzA3MDI3LTVkYzhkZTJhLTEwMjQtNDA1Zi1hMmIxLTU4N2ZkNTkyMzdlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxNjM2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWY5MjU0NDI3ZjBlMTU4OWNiN2M2ZjQwOGY1ZjlmZjI5MWVjYjQ2NmZiNzk4MjgxMWMxY2JhZmJiNTRlMzNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.imo4ns2ZHYsDzwOnmy_1BpHAY0aVvrjGzMHUsaYroIc"> <img alt="Screenshot 2024-08-07 at 12 22 30 PM" width="794" src="https://private-user-images.githubusercontent.com/138196495/355707038-15b0a9aa-ec23-462b-864c-10d57f29bcfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDg4OTcsIm5iZiI6MTcyMzA0ODU5NywicGF0aCI6Ii8xMzgxOTY0OTUvMzU1NzA3MDM4LTE1YjBhOWFhLWVjMjMtNDYyYi04NjRjLTEwZDU3ZjI5YmNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxNjM2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2U2YjJjYzBiNzVhOTY0MmI1NjJkZTcxYzNjYjkxZWQ0NGMwZjBjYTE4Y2I2MTRkNGMzM2M3MjMwNjM3NmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ta3iFAQqyskVPc0Qm34ovHkQDcMEV0nHG4fUOL-r-zo">

Thank you, you can close it now.

**Comment by npetrovic-tenstorrent** [comment]
@VirdhatchaniKN Thank you! It is not described in the documentation. You can close the issue.

**Comment by Aswinmcw** [comment]
Issue fixed
