### ISSUE TITLE
[Support request] Error when binding operation to TTNN

### ISSUE THREAD

**Issue by athul-bos-semi** [tenstorrent/tt-metal#10650]
## Problem/Purpose

I am trying to bind an Op to TTNN, and followed the steps shown in the [guide](https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/adding_new_ttnn_operation.html). But I am facing the following error:
```
In file included from ../ttnn/cpp/pybind11/__init__.cpp:14:
In file included from ../ttnn/cpp/pybind11/operations/__init__.hpp:29:
../ttnn/cpp/ttnn/operations/test_ops/test_ops_pybind.hpp:14:44: error: no member named 'test_concat' in namespace 'ttnn'
   14 |     detail::bind_test_concat(module, ttnn::test_concat); 
      |                                      ~~~~~~^
1 error generated.
ninja: build stopped: subcommand failed.

```
Here's a list of changes I made in addition to the guide's instructions:
1. In ttnn/cp/pybind11/operation/__init__.hpp, I added the following two lines inside operations namespace
```
auto m_test = module.def_submodule("test_ops", "Test operations");
test_ops::py_module(m_test);
```
2. Added the file ttnn/ttnn/operations/test_concat.py with the following code:
```
from typing import Tuple, Union, Dict

import sys
import ttnn

test_concat = ttnn.register_operation()(ttnn._ttnn.operations.test_ops.test_concat)

__all__ = []
```

I have submitted a pull request with my changes for your reference.

**Comment by tt-rkim** [comment]
@arakhmati Did you want to comment?

**Comment by ayerofieiev-tt** [comment]
@tt-rkim I left comments in the PR

**Comment by ayerofieiev-tt** [comment]
Closing this ticket in favor of the conversation in the pull request.

**Comment by tt-rkim** [comment]
Thanks, I'll let you take over from here
Let me know if you have issues running CI on the branch. You likely will have to copy it over to a branch on the original repo
