### ISSUE TITLE
Add `git_branch_name` and `github_job_run_link` to `environment.csv` for benchmarks

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#10680]
Requested by @skhorasganiTT

**Comment by tt-rkim** [comment]
@FrancesssZ @skhorasganiTT 
We have difficulty getting `github_job_id` within the actual GitHub running job. It sucks. I can explain more if you'd like.

Because of this, @skhorasganiTT are you ok if we just link to the workflow (whole pipeline)? Rather than the specific job? I propose we change `github_job_run_link` to `github_pipeline_run_link`.

**Comment by skhorasganiTT** [comment]
Discussed this with @tt-rkim , the pipeline link is sufficient for our request.

**Comment by FrancesssZ** [comment]
@tt-rkim @tt-rkim I'll name it as `github_pipeline_link` to align with another column that we already have in the env file called `github_pipeline_id`. Please let me know if you're both good with this.

**Comment by tt-rkim** [comment]
We're both good

**Comment by FrancesssZ** [comment]
Changes on data team have been deployed @tt-rkim @skhorasganiTT

**Comment by uaydonat** [comment]
@tt-rkim this issue is a blocker for us for to be able to use the dashboard in our daily analysis. Do you have an ETA? If not soon, then we can take a look?

**Comment by tt-rkim** [comment]
@skhorasganiTT , for these two fields, edit function `infra/data_collection/github/utils.py:create_csv_for_github_benchmark_environment`:

- Add the two fields to `BENCHMARK_ENVIRONMENT_CSV_FIELDS` at top
- `git_branch_name`: Get the value from `GITHUB_HEAD_REF` environment variable
- `github_job_run_link`: You can generate at the presentation layer by using `github_pipeline_id` and `git_repo_name`: the value should be `https://github.com/<git_repo_name>/actions/runs/<github_pipeline_id>`. Test this first though to make sure. No code changes needed, as this is a field that can be generated from the current data. We don't need to produce.

**Comment by skhorasganiTT** [comment]
Thanks @tt-rkim

**Comment by tt-rkim** [comment]
@skhorasganiTT pls close if done
