### ISSUE TITLE
[Bug Report] Mismatch between the `ttnn` documentation and the actual implementation of ttnn ops.

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#10724]
**Describe the bug**

I am currently working on porting `moreh_layernorm` to ttnn and have been referencing the `eltwise binary` forward implementation because it is the only one that was implemented using` tensor_return_value_t` according to the latest documentation(https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/adding_new_ttnn_operation.html).

However, I recently noticed that the ttnn example was updated, and the implementation in `example/single_core_program_factory` has a very different style compared to `eltwise binary`. (update pr: https://github.com/tenstorrent/tt-metal/pull/10721/files)

Could you tell me which style is more up-to-date or preferable?

For example:
- Creating compute_kernel:
  - eltwise binary: Creates `compute_kernel` in `all_device_core` and sets `per_core_block_cnt` values only for the necessary cores.
  - example: Creates `compute_kernel` only for the necessary cores.
- SetRuntimeArgs:
  - eltwise binary: Called once outside the for loop.
  ```C++
    for (uint32_t i = 0, num_tiles_read = 0; i < num_cores_total; ++i) {
       ...
    }

    if constexpr (initialize_args) {
        SetRuntimeArgs(program, binary_reader_kernel_id, cores, binary_reader_args);
        SetRuntimeArgs(program, eltwise_binary_kernel_id, cores, eltwise_binary_args);
        SetRuntimeArgs(program, unary_writer_kernel_id, cores, unary_writer_args);
    }
  ```
  
  - example: Called n times inside the for loop.
  ```C++
    for (uint32_t i = 0, num_tiles_written = 0; i < num_cores; i++) {
        ...
        tt::tt_metal::SetRuntimeArgs(
            program, unary_reader_kernel_id, core, {src_buffer->address(), num_tiles_per_core, num_tiles_written});

        tt::tt_metal::SetRuntimeArgs(
            program, unary_writer_kernel_id, core, {dst_buffer->address(), num_tiles_per_core, num_tiles_written});
        num_tiles_written += num_tiles_per_core;
    }
  ```
- Compute kernel
  - eltwise binary: use runtime args
  - example: use compile time args

@arakhmati @dmakoviichuk-tt @arakhmati

**Comment by ayerofieiev-tt** [comment]
@arakhmati can you please share some ETA?

**Comment by arakhmati** [comment]
https://github.com/tenstorrent/tt-metal/pull/10903

**Comment by arakhmati** [comment]
The code inside of `create_program` is there to make sure the op works and people see a bigger picture. However, you don't have to write your program this way. The main purpose of the example is to explain the new op infra and not how to write programs and kernels
