### ISSUE TITLE
Bringup Shallow UNet on N300 via data-parallel 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#10754]
**Describe the bug**
We need to meet perf requirements for the shallow UNet. The currently suggested path to achieve this from the metalium team is to bringup the model on N300 via data-parallel. 

We (the customer team) referred to LLM examples with data-parallel. However, CNNs are very different. and LLM examples are not relevant.  We would need some CNN references. Perhaps a pointer to implementation on galaxy or ideally on T3k. Do we have it for ResNet50? 

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- N300

**Comment by dvartaniansTT** [comment]
update received from @tt-aho :

we have 2 files right now for multi device resnet, a perf and functional test:
Perf: models/demos/ttnn_resnet/tests/multi_device/test_perf_ttnn_resnet.py
Functional: models/demos/ttnn_resnet/tests/multi_device/test_ttnn_resnet50_performant.py
The actual model code is in models/demos/ttnn_resnet/tt/ttnn_functional_resnet50_new_conv_api.py and works for both single/multi device.
The preprocessing that happens for Resnet data parallel is currently somewhat convoluted because it does 2 separate preprocessing steps and converts back to torch after the first preprocessing, which needs to be cleaned up.
The main changes are using the device_mesh , and using the mesh mappers/composers. If the underlying ops are already set up to work correctly for multidevice then there shouldnt be too many issues

**Comment by esmalTT** [comment]
Completed since 2035fd074e4e60912763c917a607f7d7401de6b4
