### ISSUE TITLE
Changing model owner for falcon40b

### ISSUE THREAD

**Issue by johanna-rock-tt** [tenstorrent/tt-metal#10770]
Currently @johanna-rock-tt is code owner of falcon40b but there's a change in project assignments, so @djordje-tt is taking over that ownership.

Proposed changes:
- Change the person to be notified via slack messages about broken CI tests to be @djordje-tt 

Keep both @johanna-rock-tt and @djordje-tt as code owners for now.

**Comment by tt-rkim** [comment]
I've put up a PR for your review.

@uaydonat and other management specifically asked all assets to go to the new members after the reorganization.
