### ISSUE TITLE
Program Hash does not include kernel file directory

### ISSUE THREAD

**Issue by yugaoTT** [tenstorrent/tt-metal#10783]
**Describe the bug**
if previous op has the same compile time arg and same kernel name (but they are on different directory) , then it doesn’t change the kernels, and will use the cached one. 

**Expected behavior**
the program hash should include the kernel path

**Repro**
When run the pytests in `tests/tt_eager/python_api_testing/unit_testing/misc/`
the slice op should use `ttnn/cpp/ttnn/operations/data_movement/slice/device/kernels/dataflow/writer_unary_stick_layout_interleaved_start_id.cpp`,
and concat op should use 
`ttnn/cpp/ttnn/deprecated/tt_dnn/kernels/dataflow/writer_unary_stick_layout_interleaved_start_id.cpp`
but when they both run, the slice op will use the file from concat op, which is cached earlier.

**Comment by arakhmati** [comment]
Delete `compute_program_hash` from `ttnn/cpp/ttnn/operations/data_movement/slice/device/slice_op.cpp` and from `ttnn/cpp/ttnn/operations/data_movement/slice/device/slice_op.hpp`. Then the operation will use the default program hash which will always work correctly. And if you want to optimize the hash to map more arguments onto the same program, then make sure the function is correct

**Comment by yugaoTT** [comment]
close this as solved
