### ISSUE TITLE
remove profiler dependence on common_runtime_addres_map

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#10849]
(not urgent)

I'm slowly deprecating that file.  Going forward, dev_mem_map, dev_msgs will export firmware capabilities to the runtime and runtime concepts will be passed to the fw through, eg, the launch message.  This will remove the firmware's dependence on runtime concepts.

**Comment by mo-tenstorrent** [comment]
Being worked on as part of [4984](https://github.com/tenstorrent/tt-metal/issues/4984)
