### ISSUE TITLE
Fix metal_BERT_large_11 tests after various ttnn migrations

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#10899]
After some ttnn migrations for ops like embeddings, we see errors such as shape mismatches in pipelines.

## Shape mismatches

https://github.com/tenstorrent/tt-metal/actions/runs/10161907476/job/28101879126

```
FAILED tests/nightly/common_models/models/demos/metal_BERT_large_11/tests/test_bert_batch_dram.py::test_bert_batch_dram[BERT_LARGE-batch_9-BFLOAT8_B-DRAM] - RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/normalization/layernorm/device/layernorm_op.cpp:31: a.get_legacy_shape() == b.value().get_legacy_shape()
info:
shape is not same!
backtrace:
 --- ttnn::operations::normalization::LayerNorm::validate(std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor const>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor const>>> const&) const
```

## Allocator errors

https://github.com/tenstorrent/tt-metal/actions/runs/10161907476/job/28101879126

```
FAILED tests/nightly/common_models/models/demos/metal_BERT_large_11/tests/test_bert_batch_dram.py::test_bert_batch_dram_with_program_cache[BERT_LARGE-batch_8-MIXED_PRECISION_BATCH8] - RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/algorithms/free_list.cpp:241: tt::exception
info:
Out of Memory: Cannot allocate at an address below 524576. Tried to allocate at 494976
backtrace:
 --- tt::tt_metal::allocator::FreeList::allocate(unsigned long, bool, unsigned long)
```

**Comment by tt-rkim** [comment]
cc: @tt-aho @TT-billteng current issues in nightly pipelines

**Comment by tt-rkim** [comment]
Single card demo tests pass on a commit before https://github.com/tenstorrent/tt-metal/commit/60a00423569da4d4579e26814799b55ad28580fd

https://github.com/tenstorrent/tt-metal/actions/runs/10147583846

**Comment by tt-aho** [comment]
Should note this is also preventing device and E2E perf regression for bert. For GS device perf, we aren't even regressing on other models because the bert test is causing the job to error out.

**Comment by sjameelTT** [comment]
Should fix this issue + all the cascading issues with it.

https://github.com/tenstorrent/tt-metal/commit/5645727c6dc7594b86181343d9ba0fe3d7a763d5
