### ISSUE TITLE
Fix metal_BERT_large_11 with batch size 8 on WH N150 fast dispatch nightly

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#10901]
For N150:

- batch size 8 should work, but doesn't right now
- batch size 12 is expected to not work and should be skipped

We should skips for both for now on N150.

**Comment by tt-rkim** [comment]
@tt-aho owns this test, technically.
Should we make you codeowner for `metal_BERT_large_11`?
cc: @mywoodstock

**Comment by tt-aho** [comment]
I merged the fix. @tt-rkim let me know if it works on your CI branch after removing your original test changes
