### ISSUE TITLE
CCL Ops: all-gather ops refactor

### ISSUE THREAD

**Issue by cfjchu** [tenstorrent/tt-metal#10915]
Request to refactor existing all-gather interface under single-api. Currently we have:
```
ttnn.all_gather()
ttnn.line_all_gather()
```
It would be great if this could be defined under a single-interface that specifies all-gather topology: {ring, line}

**Comment by SeanNijjar** [comment]
Agree. The underlying all gather program creation already operates this way (the same code works with line and ring) so we just need to thread the appropriate information through from the mesh tensor according.

**Comment by davorchap** [comment]
> Agree. The underlying all gather program creation already operates this way (the same code works with line and ring) so we just need to thread the appropriate information through from the mesh tensor according.

We can also infer {ring, line} if user didn't specify / override.

**Comment by SeanNijjar** [comment]
> We can also infer {ring, line} if user didn't specify / override.

Right - I didn't explicitly mention it but this is what I was alluding to. Personally, I think we should do the decision making at mesh tensor level but maybe I'm overlooking something that makes it more useful at op level (under mesh tensor).

**Comment by Aswinmcw** [comment]
This refractor has been added to main, can we close this issue?
