### ISSUE TITLE
ttnn.ones_like and ttnn.zeros_like cause build / cmake build Debug grayskull

### ISSUE THREAD

**Issue by KalaivaniMCW** [tenstorrent/tt-metal#10941]
**Describe the bug**
ttnn::zeros_like and ttnn::ones_like in composite ops implementation causes Cmake Build Error on all post-commits CI run. 
This problem doesn't occur when ttnn::full_like is used with value 1.0 or 0.0 instead. 

CI run : https://github.com/tenstorrent/tt-metal/actions/runs/10179967434/job/28156845494

https://docs.google.com/document/d/1KPPZT7jFPp7bdktOzE5fnKTkCI3ukyNgfVWsIPLBnk4/edit?usp=sharing

**To Reproduce**
1. Reproduce on a Grayskull or Wormhole_b0 machine
2. Checkout 'bug-ttnn-ones-zeros-like'
3. Run commands 
```
cmake -B build -DCMAKE_BUILD_TYPE=Debug -G Ninja
cmake --build build
```

**Expected behavior**
To pass Cmake Build  without errors

**Screenshots**
on local : 
<img width="1512" alt="Screenshot 2024-07-31 at 6 25 35 PM" src="https://github.com/user-attachments/assets/4eb8f89a-d388-4c70-9907-7ebd9d3f8908">

on CI:
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/a7243e79-1b83-4d94-9074-fc66998a6958">

**Comment by KalaivaniMCW** [comment]
Adding some more findings here, 
the above mentioned error doesn't occur when we use ttnn::operations::creation::zeros_like() instead of ttnn::zeros_like() so the issue is maybe with the register operation.. not very sure yet

**Comment by ayerofieiev-tt** [comment]
@KalaivaniMCW it might be picking up on tt::tt_metal:: version of the function

**Comment by ayerofieiev-tt** [comment]
Compiler might just be confused that two variants exist. Someone long time ago added `using tt::tt_metal` into global namespace and this might cause a conflict like that. I am 50% confident that it is related

**Comment by patrickroberts** [comment]
I'm going to try defining `zero_like` without using `REGISTER_OPERATION_FROM_FUNCTION` and see if that fixes it. I notice that `full_like` is not registered with the macro.

**Comment by patrickroberts** [comment]
See https://github.com/tenstorrent/tt-metal/commit/5ced445261d7e903ffd267210fb2cea447e3e87a
