### ISSUE TITLE
Test failing for unary_fmod and unary_remainder

### ISSUE THREAD

**Issue by mouliraj-mcw** [tenstorrent/tt-metal#10942]
### Description:

- Both unary_fmod and unary_remainder has been failing for certain scalar values(23.5, 30.5, 54.5)

Reference Doc: [Fmod and remainder Inputs.pdf](https://github.com/user-attachments/files/16454853/Fmod.and.remainder.Inputs.pdf)

### Test Files:
fmod : `tests/ttnn/unit_tests/operations/test_binary_composite.py::ttest_fmod_ttnn`
remainder : `tests/ttnn/unit_tests/operations/test_binary_composite.py::test_remainder_ttnn`

**Comment by Aswinmcw** [comment]
Fix merged to main
