### ISSUE TITLE
Fix profiler regression to actually show underlying tests that it ran

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent/tt-metal#10949]
Because of the redirect on some of the test in profiler regression. The actual command that started the test doesn't get displayed. 

Fix this by using `tee` for piping the out put to file and stdout/stderr

**Comment by mo-tenstorrent** [comment]
@TT-billteng Is this useful?

https://github.com/tenstorrent/tt-metal/actions/runs/10185517484/job/28175994140#step:8:123

**Comment by TT-billteng** [comment]
looks great :D
