### ISSUE TITLE
Mamba end-to-end perf is much slower on CI than lab machines

### ISSUE THREAD

**Issue by esmalTT** [tenstorrent/tt-metal#10967]
I am seeing a large difference between end-to-end performance (specifically in [this](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) pipeline) on lab machines and CI machines. From my investigation - it seems that this is mainly because the CI machines are considerably less powerful than the lab machines I tested. 

This isn't a huge deal for catching performance regressions, but if we are going to start automatically reporting performance numbers from CI it would be nice if these matched what we observe on development machines since they are best case. 

For example, here are some numbers I collected recently:

|  | tt-metal-large-bm-e09cs01 | yyz-lab-124 |
| -- | -- | -- |
| End-to-end performance (tok/s) | 286.1462 | 389.4207 |
| CPU | AMD EPYC 7352 24-Core Processor | AMD Ryzen 9 7900X 12-Core Processor |
| RAM (GB) | 24 (EDIT: it's 240 GB) | 64 |

Here is a comparison between the two CPUs: [link](https://technical.city/en/cpu/EPYC-7352-vs-Ryzen-9-7900X).

**Comment by esmalTT** [comment]
fyi @tt-rkim

**Comment by TT-billteng** [comment]
so what is the action item on this issue?

**Comment by tt-rkim** [comment]
@esmalTT I think the developer ask here is to have the exact same machine setup on CI as we do on dev.

Unfortunately that's untenable, and something that we've been pretty clear on from the beginning. What are your guys' thoughts on having different thresholds depending on the CI fixture?

**Comment by esmalTT** [comment]
@tt-rkim @TT-billteng Yeah having something comparable (or just better) perf-wise would be ideal.

> What are your guys' thoughts on having different thresholds depending on the CI fixture?

For now we use the lowest observed threshold between all of the tests we are running, but ideally we'd do something like that. This method would be the best way to catch perf regressions, but this particular issue is more about the absolute measurements. 

I guess maybe the core issue is more about us not having a standardized host machines we use to report our official benchmarks (like the ones in the README).

**Comment by tt-rkim** [comment]
We don't have much control over what's on DevInfra or what's on cloud, so I think the way forward here is to do something to tailor measurements for specific environments, or in this case using the fixture to grab a different threshold.

Unfortunately, I have to characterize the ask here as having metal infra team to convince both cloud and internal devinfra to have the same machines. I don't think it's worth the hassle, and we should practice more defensive programming.

It's not like all dev machines people will run mamba on will be the same.

Let us know what you think

**Comment by TT-billteng** [comment]
> I am seeing a large difference between end-to-end performance (specifically in [this](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) pipeline) on lab machines and CI machines. From my investigation - it seems that this is mainly because the CI machines are considerably less powerful than the lab machines I tested.
> 
> This isn't a huge deal for catching performance regressions, but if we are going to start automatically reporting performance numbers from CI it would be nice if these matched what we observe on development machines since they are best case.
> 
> For example, here are some numbers I collected recently:
> 
>  	tt-metal-large-bm-e09cs01	yyz-lab-124
> End-to-end performance (tok/s)	286.1462	389.4207
> CPU	AMD EPYC 7352 24-Core Processor	AMD Ryzen 9 7900X 12-Core Processor
> RAM (GB)	24	64
> Here is a comparison between the two CPUs: [link](https://technical.city/en/cpu/EPYC-7352-vs-Ryzen-9-7900X).

is there actually only 24 GB RAM on CI BM?

**Comment by TT-billteng** [comment]
Take this up with cloud / dev infra, we don't control the type of machines they buy

**Comment by tt-rkim** [comment]
Hmm yeah I just noticed there. 24GB... that's interesting. Not sure where you got that from...
We have 100s of GB of RAM on the BM.

**Comment by tt-rkim** [comment]
If we see no movement or proposed action item from your team by the end of this week on this issue, we will close it.

**Comment by esmalTT** [comment]
> Hmm yeah I just noticed there. 24GB... that's interesting. Not sure where you got that from... We have 100s of GB of RAM on the BM.

Yeah my bad - its actually 240 GB.

> If we see no movement or proposed action item from your team by the end of this week on this issue, we will close it.

Based on the above, I don't think there's any immediate action on you guys. I am fine to close this while we consider how we want to standardize our model perf benchmarks.
