### ISSUE TITLE
[Blackhole xfunc] Get faster BH machines

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#10976]
Two parts:

1. Need faster (and more) hosts so that CI doesn't become a bottleneck as more op owners start to do dev for BH. We currently have 2 machines for CI 
2. Need cards with faster AI CLK to unblock perf testing

FYI @davorchap @pgkeller

**Comment by abhullar-tt** [comment]
@TT-billteng do you know if there are any BHs marked for Cloud/Metal CI that will match the existing CI machine specs.
If not, do you know how many we may need if we eventually want BH to be tested as part of post commit?

**Comment by TT-billteng** [comment]
> @TT-billteng do you know if there are any BHs marked for Cloud/Metal CI that will match the existing CI machine specs. If not, do you know how many we may need if we eventually want BH to be tested as part of post commit?

So the AMD 7950x3d we just ordered should be much faster than any individual cloud VM instance we currently have. If this is still too slow, we need to investigate host perf on BH. Cloud is in the process of densifying the machines with more cards (upgrading each machine to 8 cards from 4). I'm in the process of qualifying perf on 8vCPU VMs (we've been running on 14vCPUs for CI). If BH actually needs far more resources on host side for whatever reason, this will upend cloud's roadmap and we need to let them know ASAP.

**Comment by pgkeller** [comment]
@abhullar-tt can we close this?

**Comment by abhullar-tt** [comment]
yes
