### ISSUE TITLE
moreh: compile kernels from source in a string

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#11005]
(need to sort out details, rough concept below)

Create a new api, something like CreateKernelFromString
The application passes the string in through the API, string contains the source for a kernel
Runtime passes the string to gcc to compile, something like this:
https://stackoverflow.com/questions/2083874/compile-string-of-c-code

Due date, early September

**Comment by sagarwalTT** [comment]
I have made a PR that allows for kernels with the source code passed in as a string to be compiled, however, the source code for the created kernel will be visible in `$TT_METAL_HOME/built/.../kernel_includes.hpp`. Currently when a program is compiled, it generates files under `$TT_METAL_HOME/built` and it is necessary for `$TT_METAL_HOME/built/.../kernel_includes.hpp` to have access to the kernel code so that the program can be compiled properly. We might be able to modify the compilation later on so that the kernel source code won't be visible here, but is it an issue if the source code is visible under `$TT_METAL_HOME/built`?

**Comment by razorback3** [comment]
> I have made a PR that allows for kernels with the source code passed in as a string to be compiled, however, the source code for the created kernel will be visible in `$TT_METAL_HOME/built/.../kernel_includes.hpp`. Currently when a program is compiled, it generates files under `$TT_METAL_HOME/built` and it is necessary for `$TT_METAL_HOME/built/.../kernel_includes.hpp` to have access to the kernel code so that the program can be compiled properly. We might be able to modify the compilation later on so that the kernel source code won't be visible here, but is it an issue if the source code is visible under `$TT_METAL_HOME/built`?

It is best if the kernel source code won't be visible.
Binary code can be visible but raw source code is not preferable.

However, if it is hard to do right now, may be we can break it down and proceed step by step.
Do you have any idea and plan to make it invisible to users?

**Comment by pgkeller** [comment]
> > I have made a PR that allows for kernels with the source code passed in as a string to be compiled, however, the source code for the created kernel will be visible in `$TT_METAL_HOME/built/.../kernel_includes.hpp`. Currently when a program is compiled, it generates files under `$TT_METAL_HOME/built` and it is necessary for `$TT_METAL_HOME/built/.../kernel_includes.hpp` to have access to the kernel code so that the program can be compiled properly. We might be able to modify the compilation later on so that the kernel source code won't be visible here, but is it an issue if the source code is visible under `$TT_METAL_HOME/built`?
> 
> It is best if the kernel source code won't be visible. Binary code can be visible but raw source code is not preferable.
> 
> However, if it is hard to do right now, may be we can break it down and proceed step by step. Do you have any idea and plan to make it invisible to users?

Thanks at @razorback3, we'll proceed w/ the code visible for now.  There are a number of pieces of the build system that need to be reworked, we'll take a look at this w/ that effort.  That won't start for a ~couple months (not yet planned), let us know if you need this piece sooner than that.
