### ISSUE TITLE
ResNet needs bcast removed.

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#11002]
We are attempting to remove bcast from ResNet by replacing the bcast with binary operations add/subtract/multiply.  Under the hood these binary operations uses the same kernels so this should work provided the tensors get updated to reflect the desired location for the bcast by using a 1 in the width/height needed.   We just need an extra hand to update these models.
This work is currently being done on an existing branch `ttnn-9527-remove-bcast` where all these methods have been replaced but we see a failure on CI at ttnn_functional_resentblock2d.py around line 540 where you see:
```
if temb is not None and time_embedding_norm == "default":
            hidden_states = ttnn.add(
                hidden_states,
                temb,
                memory_config=hidden_states.memory_config(),
            )
```

Associated test was `pytest tests/ttnn/integration_tests/stable_diffusion/test_unet_2d_condition_model.py::test_unet_2d_condition_model_512x512[batch_size=2-in_channels=4-input_height=64-input_width=64-device_params=l1_small_size_24576]`

(Pdb) p temb.shape
ttnn.Shape([2, 1, 1[32], 320])
(Pdb) p hidden_states.shape
ttnn.Shape([1, 1, 8192, 320])

hidden_states memory config is...
`MemoryConfig(memory_layout=TensorMemoryLayout::BLOCK_SHARDED,buffer_type=BufferType::L1,shard_spec=ShardSpec(grid={[(x=0,y=0) - (x=4,y=7)]},shape={1024, 64},orientation=ShardOrientation::ROW_MAJOR,halo=0))`

temb memory config is...
`MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::L1,shard_spec=std::nullopt)`

**Comment by mywoodstock** [comment]
@eyonland Its not clear what the requirements are here? E.g. why is it needed to remove bcast from Resnet? What is the bcast equivalent in the replacement?

**Comment by mywoodstock** [comment]
@eyonland OK, so looks like the `bcast` op with bcast along `H` supports multi-batch bcast, so the input shapes to the function are correct (batch for `hidden_states` = 1 and `temb` = 2). I think the `add` op needs to support this case in order to be used here as currently it requires batches to be equal.

**Comment by mywoodstock** [comment]
Assigning back to you :)

**Comment by eyonland** [comment]
@mywoodstock , I suspect this current bcast is not doing what you think it is.

```
@pytest.mark.parametrize("shape_a", [(1, 1, 8192, 320)])
@pytest.mark.parametrize("shape_b", [(2, 1, 1, 320)])
def test_add_with_different_batch(device, shape_a, shape_b):
    torch.manual_seed(0)

    torch_input_tensor_a = torch.rand(shape_a, dtype=torch.bfloat16)
    torch_input_tensor_b = torch.rand(shape_b, dtype=torch.bfloat16)
    torch_output_tensor = torch_input_tensor_a + torch_input_tensor_b

    input_tensor_a = ttnn.from_torch(
        torch_input_tensor_a, layout=ttnn.TILE_LAYOUT, device=device, memory_config=ttnn.DRAM_MEMORY_CONFIG
    )

    compute_with_storage_grid_size = device.compute_with_storage_grid_size()
    device_grid_size = ttnn.CoreGrid(y=compute_with_storage_grid_size.y, x=compute_with_storage_grid_size.x)

    block_sharded_mem_config = ttnn.create_sharded_memory_config(
        shape=(1024, 64),
        core_grid=device_grid_size,  # ttnn.CoreGrid(y=8, x=5),
        strategy=ttnn.ShardStrategy.BLOCK,
        orientation=ttnn.ShardOrientation.ROW_MAJOR,
        use_height_and_width_as_shard_shape=True,
    )

    input_tensor_a = ttnn.to_memory_config(input_tensor_a, block_sharded_mem_config)

    input_tensor_b = ttnn.from_torch(
        torch_input_tensor_b, layout=ttnn.TILE_LAYOUT, device=device, memory_config=ttnn.L1_MEMORY_CONFIG
    )
    # Intend to swap code below with: output_tensor = ttnn.add(input_tensor_a, input_tensor_b, memory_config=ttnn.DRAM_MEMORY_CONFIG)
    output_tensor = ttnn.experimental.tensor.bcast(
        input_tensor_a,
        input_tensor_b,
        ttnn.experimental.tensor.BcastOpMath.ADD,
        ttnn.experimental.tensor.BcastOpDim.H,
        output_mem_config=input_tensor_a.memory_config(),
    )

    output_tensor = ttnn.to_torch(output_tensor)

    # We do not support broadcasting as one would expect,
    # our bcast will return a tensor without the batch 2
    # we also get incorrect pcc as well
    torch_output_tensor = torch_output_tensor[:1]

    assert ttnn.pearson_correlation_coefficient(torch_output_tensor, output_tensor) >= 0.99988
    assert output_tensor.shape == shape_a

```

**Comment by eyonland** [comment]
See results from test above...
```
tests/ttnn/unit_tests/operations/test_add.py:297: AssertionError
===================================================================================== warnings summary ======================================================================================
tests/ttnn/unit_tests/operations/test_add.py::test_add_with_different_batch[shape_b=(2, 1, 1, 320)-shape_a=(1, 1, 8192, 320)]
  tests/ttnn/unit_tests/operations/test_add.py:252: PytestWarning: record_property is incompatible with junit_family 'xunit2' (use 'legacy' or 'xunit1')
    @pytest.mark.parametrize("shape_a", [(1, 1, 8192, 320)])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
------------------------------------------------- generated xml file: /home/eyon/git/tt-metal/generated/test_reports/most_recent_tests.xml --------------------------------------------------
===================================================================================== slowest durations =====================================================================================
2.36s setup    tests/ttnn/unit_tests/operations/test_add.py::test_add_with_different_batch[shape_b=(2, 1, 1, 320)-shape_a=(1, 1, 8192, 320)]
1.97s call     tests/ttnn/unit_tests/operations/test_add.py::test_add_with_different_batch[shape_b=(2, 1, 1, 320)-shape_a=(1, 1, 8192, 320)]
0.01s teardown tests/ttnn/unit_tests/operations/test_add.py::test_add_with_different_batch[shape_b=(2, 1, 1, 320)-shape_a=(1, 1, 8192, 320)]
================================================================================== short test summary info ==================================================================================
FAILED tests/ttnn/unit_tests/operations/test_add.py::test_add_with_different_batch[shape_b=(2, 1, 1, 320)-shape_a=(1, 1, 8192, 320)] - AssertionError: assert 0.018296831743181 >= 0.99988

```

**Comment by mywoodstock** [comment]
Here are my findings:

https://github.com/tenstorrent/tt-metal/blob/main/tests/ttnn/unit_tests/operations/test_add.py#L132
skips this particular case with an issue which is marked complete, but I do not believe its complete. If you unskip this test, it will fail. Moreover, I do not see any commit in relation to the corresponding issue #4005. Also there is this comment in the code: https://github.com/tenstorrent/tt-metal/blob/main/ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp#L61-L62, from which I infer that the sharding needs to match exactly, but in our case we need bcast case where the input sharding will not match.

So, my conclusion is that `add` does not support this case.

**Comment by mywoodstock** [comment]
I would suggest checking with the owner of `add` to confirm if it supports or not.

**Comment by eyonland** [comment]
We need to continue to support bcast given that the functionality is not ready in the ttnn binary op.   The plan is to port from deprecated to operations/experimental for the time being and leave the use of bcast in these cases.

**Comment by eyonland** [comment]
Ported ResNet instead of forcing the removal.
