### ISSUE TITLE
Optimize Distributed LayerNorm for Llama3-TG Decode

### ISSUE THREAD

**Issue by kpaigwar** [tenstorrent/tt-metal#11022]
### Description
Presently, distributed layernorm is the slowest Op in Llama3-TG taking around 17% of the total device time. It only supports DRAM interleaved inputs since it was initially written for prefill.

### Solution
1. Support for sharded input tensors.
2. Run on all cores, use 2D reduction scheme as also dingle device layernorm does

Profiler report
[llama70b_profile3.csv](https://github.com/user-attachments/files/16461544/llama70b_profile3.csv)

**Comment by kpaigwar** [comment]
fyi @uaydonat @kevinmiTT11

**Comment by kpaigwar** [comment]
Our current implementation plan is as follows:
- Reuse layernorm host side code and parts of the kernel code for our new distributed layernorm for sharded inputs
- Extend the host-side code to take a `layernorm_stage` (`none`, `pre_all_gather`, `post_all_gather`). The host side code validates, computes output shapes, creates output tensors etc based on the stage.  
Note: `pre_all_gather_layernorm` has as different output shape, it’s the statistics E(X), E(X**2) and won’t use the optional input tensors such as weight, bias etc. 
`post_all_gather_layernorm` has  the same output shape. In addition to input buffers, we will also pass statistics buffers as input.
```
If layernorm_stage == None:
    1. Call original existing kernels
elif layernorm_stage == pre_all_gather:
   1. Only instantiate intermediate CBs involved in pre_all_gather stage. Also, create an extra output buffers to store global statistics.
   2. Identify pre_all_gather process in Reader, Compute and Writer kernels and split into new Reader, Compute and Writer kernel files postfixed by `...pre_all_gather.cpp`
   3. Call these kernel from the same host code based on the stage.
elif layernorm_stage == post_all_gather:
   1. Pass new global statistic buffers defined as optional input tensors. And set the global statistics CB addresses from the input buffers
   2. Identify post_all_gather process in Reader and Compute and split into new Reader and Compute kernel files postfixed by .`..post_all_gather.cpp`
   3. Call these kernel from the same host code based on the stage.
```

**Comment by johanna-rock-tt** [comment]
@TT-BrianLiu @ayerofieiev-tt @yugaoTT Above is our current plan to implement a sharded distributed layernorm op. Since this is partially going to reuse the existing layernorm implementation and at the same time is the first op where we'd have the distributed version combined inside that op, we'd like to get your opinion and feedback on this.

**Comment by yugaoTT** [comment]
lgtm, think the pre-all gather reader kernel files should be able to re-use instead of creating new files. post-all gather reader kernel does Mcast to all cores. writer file should remain the same for post-all gather, pre-all gather does not have any writer.
