### ISSUE TITLE
Include yaml linting and automatic corrections

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#11034]
Add yamllint and yamlfmt

yamllint serves only for linting yaml and highlighting errors but does not correct
yamlfmt only works on yaml files 

https://github.com/jumanjihouse/pre-commit-hook-yamlfmt

**Comment by ttmchiou** [comment]
@tt-rkim

**Comment by ttmchiou** [comment]
update here:
yamllint only lints and does not format.
yamlfmt does not use yamllint as a backend so these two are not necessarily compatible after playing around with it a bit.

will try with prettier (which has yaml support) and automatic formatting.

**Comment by blozano-tt** [comment]
@ttmchiou is this done?

We have yaml-check and yaml-lint in pre-commit ... run on every commit.

**Comment by ttmchiou** [comment]
I think we can consider this issue closed for now.
We can re-open if we find the need for automatic corrections
