### ISSUE TITLE
Overload complex forward ops for Div and Mul (Set 2 ops)

### ISSUE THREAD

**Issue by VirdhatchaniKN** [tenstorrent/tt-metal#11043]
Tracking Issue : #11041 

List of op to cover : 

- [x] Div
- [x] Mul

**Comment by ayerofieiev-tt** [comment]
@VirdhatchaniKN is this in progress or done? This ticket currently has status Done

**Comment by VirdhatchaniKN** [comment]
> @VirdhatchaniKN is this in progress or done? This ticket currently has status Done

Since the PR has been reverted, I will again PR this today once after another similar PR #11047 gets merged to main.

**Comment by VirdhatchaniKN** [comment]
> @VirdhatchaniKN is this in progress or done? This ticket currently has status Done

Hi @ayerofieiev-tt , the PR is now ready for review and will be merged on approval : #11436

**Comment by VirdhatchaniKN** [comment]
Merged to main #11436

**Comment by VirdhatchaniKN** [comment]
Merged!
