### ISSUE TITLE
Upgrade TG galaxy FW and n150s FW

### ISSUE THREAD

**Issue by mikevin920** [tenstorrent/tt-metal#11055]
All TG frequent CI tests passing locally with the firmware combo:
Galaxy FW: [80.10.1.0](https://yyz-gitlab.local.tenstorrent.com/tenstorrent/syseng/-/issues/3817)
N150 FW: https://github.com/tenstorrent/tt-firmware/blob/main/latest.fwbundle

![image](https://github.com/user-attachments/assets/22d9838b-fe91-41f8-a6b3-d2d9cdd9f5b9)

**Comment by mikevin920** [comment]
@johanna-rock-tt @kpaigwar

**Comment by tt-rkim** [comment]
`g14cs01` updated and will release into pool, taking other galaxy OOS:

<img width="1133" alt="Screenshot 2024-08-07 at 1 27 57
 PM" src="https://github.com/user-attachments/assets/8f6b400a-20d1-4c26-abbb-fe1f52f98af9">
<img width="729" alt="Screenshot 2024-08-07 at 1 28 04 PM" src="https://github.com/user-attachments/assets/7dd8dc1b-6214-45d0-8ed7-d5d5daa60cb8">

**Comment by tt-rkim** [comment]
Letting this job drain: https://github.com/tenstorrent/tt-metal/actions/runs/10287737805/job/28472832597
then will upgrade this one.

**Comment by tt-rkim** [comment]
Updated `g14cs03`:

<img width="1034" alt="Screenshot 2024-08-07 at 3 03 34 PM" src="https://github.com/user-attachments/assets/93d048b9-200b-48a8-90e4-cfd95c6441fa">

**Comment by tt-rkim** [comment]
Let us know if there are any problems, and if there is something urgent, please slack message. Will leave up for 1 day for review.

**Comment by kpaigwar** [comment]
Thanks! running the frequent CI pipeline to verify
