### ISSUE TITLE
[llama] Fuse silu with elt-wise mul	

### ISSUE THREAD

**Issue by mikevin920** [tenstorrent/tt-metal#11062]
- Silu op by itself is very slow even on 64 cores. 
- After silu we have a elt-wise mul for FF1 if we can fuse the silu for FF1 into eltwise_mul that would speed up device time for llama3

### Update
This feature has been supported in main. Although, this feature require additional testing and support for sharded input tensors. Presently it results into a hang with sharded tensors.
### Hang Repro
```
git checkout kpaigwar/eltwise_activation_fuse_bug
pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_eltwise_binary.py
```

**Comment by kpaigwar** [comment]
Update: Tested this feature added by @yugaoTT. Presently, the feature only allows fusing activation when the inputs are interleaved. If the inputs are sharded, the kernel result into a hang.

Please follow the repro instructions as added above.

**Comment by yugaoTT** [comment]
merged
