### ISSUE TITLE
Flash_Decode V2 not running fast enough on TG llama shapes

### ISSUE THREAD

**Issue by mikevin920** [tenstorrent/tt-metal#11068]
Currently running at `32305 ns` at 64 cores with (1, 8, 32, 128) inputs.

Refer to the device perf sheets for more details: [TG llama device perf](https://docs.google.com/spreadsheets/d/1twlJxyfqdjNX6HliQRHsIVBrZjsfeO4j-FCP-3gMRGQ/edit?usp=sharing)

**Comment by caixunshiren** [comment]
This should no longer be an issue as @kpaigwar observed 13us device perf for flash decode on TG using 32 chunk size.
