### ISSUE TITLE
Sharded inputs support in line all-gather  for TG llama 

### ISSUE THREAD

**Issue by mikevin920** [tenstorrent/tt-metal#11069]
Currently line all-gather only supports interleaved inputs which adds s2i and i2s ops to TG llama and slows down e2e and device perf.

Refer to device perf sheet for shapes required for sharded inputs with line all-gather.

**Comment by SeanNijjar** [comment]
Good news! I've got a branch with fully functional sharding support on line allgather.

Additionally, this (rewrite essentially), will provide a lot of other benefits:
- No longer constrained to single-tile high shards (ring and line) - end-to-end op tested
- improved performance for small sharded all-gathers (ring only) bringing it up to speed with interleaved- measured 

These are also coming down the pipe (I'm adding support as I type this - it should be quick - maybe a couple more hours)
- height sharding support (ring and line)
- block sharding support (ring and line)
- reduce scatter sharding support

Also this new infra will be portable between CCL ops, so we'll get this for future CCL ops "for free" now too :D

**Comment by SeanNijjar** [comment]
PR for these changea;
https://github.com/tenstorrent/tt-metal/pull/11074

**Comment by kpaigwar** [comment]
That's great! Thanks!

**Comment by cglagovichTT** [comment]
Reopening until we have sharded line allgather functional in TG tests

**Comment by kpaigwar** [comment]
@cglagovichTT, I don't have a separate issue for failing cases. Let's keep this open and I will attach the failing configuration details in the same.
