### ISSUE TITLE
MCW: Port Additional OPs to TTNN

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#11072]
We need help with porting additional ops to TTNN

- [x] #10124 
- [x] #10121
- [x] #10118
- [x] #10133 
- [x] #10119

**Comment by umadevimcw** [comment]
@eyonland  https://github.com/tenstorrent/tt-metal/issues/10119 is already assigned to Abhinav.

**Comment by KalaivaniMCW** [comment]
Completed porting 4 ops
