### ISSUE TITLE
line_all_gather issue with device async enabled

### ISSUE THREAD

**Issue by kpaigwar** [tenstorrent/tt-metal#11089]
### Description
After integrating new API changes for ttnn.line_all_gather, seeing the below error when enabling the device async on galaxy machine.
```
for i in device_mesh.get_device_ids():
    device = device_mesh.get_device(i)
    device.enable_async(True)
```
### Error
```
Always | FATAL   | Device not found in any view                                                             │·
libc++abi: terminating due to uncaught exception of type std::runtime_error: TT_ASSERT @ ../ttnn/cpp/ttnn/operations/ccl/line_all_gather/device/line_all_gather_op.cpp:162: selected_view !│·
= nullptr                                                                                         │·
info:                                                                                           │·
Device not found in any view
```

### Repro
```
git checkout kpaigwar/repro_async_issue
pytest tests/ttnn/multichip_unit_tests/test_multidevice_TG.py::test_device_line_all_gather_8x4_data_async_issue
```

**Comment by kpaigwar** [comment]
fyi @SeanNijjar @cglagovichTT @uaydonat @djordje-tt

**Comment by SeanNijjar** [comment]
Hey @kpaigwar, which type of machine is this?

**Comment by kpaigwar** [comment]
Hey @SeanNijjar and @cfjchu , this is galaxy machine.
I have added the unit test for repro this issue

**Comment by kpaigwar** [comment]
`pytest tests/ttnn/multichip_unit_tests/test_multidevice_TG.py::test_device_line_all_gather_8x4_data_async_issue`
This will run two tests, you will see first test passing with async_mode turned off and second will run into seg_fault

**Comment by tt-asaigal** [comment]
Hey @kpaigwar, in case you're blocked here's a branch with changes rebased on top your branch that should work: https://github.com/tenstorrent/tt-metal/tree/asaigal/issue_11089
@cfjchu  and I will properly uplift these changes to main.

**Comment by kpaigwar** [comment]
@tt-asaigal and @cfjchu , the fix is working on our demo.

**Comment by cfjchu** [comment]
@kpaigwar fixes are now in main. Please retry and let us know if any issues.

**Comment by kpaigwar** [comment]
@cfjchu, tried from main, issue has been resolved.

**Comment by cfjchu** [comment]
> @cfjchu, tried from main, issue has been resolved.

great to hear - thx!

**Comment by uaydonat** [comment]
close?

**Comment by cfjchu** [comment]
> close?

yes, it's closed
