### ISSUE TITLE
Update documentation for Unary bw ops

### ISSUE THREAD

**Issue by VirdhatchaniKN** [tenstorrent/tt-metal#11086]
Tracking Issue : #10585 

- [x] #11250
- [x] #13934
- [x] #13958
- [x] #14670  
- [x] #14376

**Comment by VirdhatchaniKN** [comment]
Left : 

- bind_unary_backward_shape
- bind_unary_backward_optional_float_params_with_default
- bind_unary_backward_unary_optional_float
- bind_unary_backward_prod_bw
- bind_unary_backward_optional
- bind_unary_backward_op_overload_abs

**Comment by mcw-anasuya** [comment]
Updated and merged to main, hence closing this issue.
