### ISSUE TITLE
[Cloud Support] Wormhole device freezes

### ISSUE THREAD

**Issue by mcw-zwakeelTT** [tenstorrent/tt-metal#11111]
## Problem/Purpose
I have a Wormhole VM: 172.27.45.160
My wormhole device is getting stuck. Recently I updated the python packages, one of the package was this:
https://github.com/tenstorrent/tt-metal/releases/download/v0.50.0/metal_libs-0.50.0+wormhole.b0-cp38-cp38-linux_x86_64.whl

Post update, I seem to be facing this issue where my device is freezing after launch a python program.

<img width="1313" alt="Screenshot 2024-08-06 at 3 53 02 PM" src="https://github.com/user-attachments/assets/73fc0b6b-9e5b-4912-b382-9a4b52ceda7d">

**Comment by tt-rkim** [comment]
Why are you using the wheel? Try using source.

Also, try a tt-smi reset.

**Comment by mcw-zwakeelTT** [comment]
I tried `tt-smi-metal -r 0`, resets the device but still freezes again.
I already have an installation of tt-smi in a virtualenv. Should I delete and install tt-smi again?

**Comment by tt-rkim** [comment]
Have you tried running from source?

**Comment by mcw-zwakeelTT** [comment]
Okay I have installed it from source. The device is responding now. But after closing device, it gets stuck and I am never back to terminal. I am forced to open a new terminal.

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/c61592fe-9c06-4f1a-87d0-650fa34f0943">

Running `tt-smi-metal -r 0` gives this:

<img width="859" alt="image" src="https://github.com/user-attachments/assets/52db248e-0c4d-4112-9ea7-5375b3973847">

**Comment by tt-rkim** [comment]
Can you try some of the basic tt metal C++ and ttnn unit tests with the tt-metal repo?

And can you please do `tt-smi-metal`, press `3`, and send a screenshot of the firmware page?

**Comment by mcw-zwakeelTT** [comment]
I deleted the previous tt-metal installation, cloned it fresh and installed from source. Now device works just fine closes without a hassle. I guess previously I switched to a release branch of tt-metal, now I am back to main again.

Previous installation firmware page:

![image](https://github.com/user-attachments/assets/98e469ef-9559-43ed-a971-bf19c1d579f3)

**Comment by tt-rkim** [comment]
great, please close if done
