### ISSUE TITLE
Increase max num Sem from 4 to 8

### ISSUE THREAD

**Issue by avoraTT** [tenstorrent/tt-metal#11131]
This issue outlines a request to increase the semaphore limit as a to workaround for hitting the per core semaphore limit of 4 in `bmm_op_multi_core_reuse_mcast_2d_optimized.cpp`.

Error output:
```
E       RuntimeError: TT_THROW @ ../tt_metal/tt_metal.cpp:50: tt::exception
E       info:
E       Cannot add semaphore on core (x=0,y=0). Max number of semaphores (4) reached!
E       backtrace:
E        --- /proj_sw/avora/tt-metal/build_Release/lib/libtt_metal.so(+0x20713c) [0x7f190e24113c]
E        --- /proj_sw/avora/tt-metal/build_Release/lib/libtt_metal.so(+0x2068b5) [0x7f190e2408b5]
E        --- tt::tt_metal::CreateSemaphore(tt::tt_metal::Program&, std::__1::variant<CoreRange, CoreRangeSet> const&, unsigned int, CoreType)
E        --- reuse_mcast_optimized_helpers::create_program_mcast_in0_in1(tt::tt_metal::Program&, tt::tt_metal::Device*, MathFidelity, bool, bool, bool, unsigned int, unsigned int, unsigned int, unsigned int, bool, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, bool, std::__1::optional<ttnn::operations::unary::UnaryWithParam>, tt::tt_metal::Buffer*, tt::tt_metal::Buffer*, tt::tt_metal::Buffer*, tt::tt_metal::Buffer*, tt::DataFormat, tt::DataFormat, tt::DataFormat, tt::DataFormat, bool, std::__1::optional<unsigned int*>)
E        --- /proj_sw/avora/tt-metal/ttnn/ttnn/_ttnn.so(_ZN2tt8tt_metal43matmul_multi_core_reuse_mcast_2d_optimized_ERNS0_7ProgramERKNS0_6TensorES5_NSt3__18optionalIS4_EERS3_bNS_3umd7xy_pairENS6_7variantIJNS0_28GrayskullComputeKernelConfigENS0_27WormholeComputeKernelConfigEEEEjjjjjbbNS7_IN4ttnn10operations5unary14UnaryWithParamEEEbNS7_IPjEE+0x74a) [0x7f190e760d6a]
```

## Overview

Currently, we are working on adding support for a new op `ttnn.all_gather_matmul` that overlaps all_gather with matmul (see issue #10415). For this fusion, we need to signal the matmul cores, via semaphores, that the data from all_gather is ready. We need at least 2 more semaphores per `in0_sender_interleaved` core, but this may increase as we work on bringing up this op. As such, a semaphore limit increase to 8 may suffice.

To reproduce:
- Branch: `ccl/all_gather_matmul`
- Build: `./build_metal.sh`
- Run test: `pytest -svv tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather_matmul.py`
- Relavant file: `ttnn/cpp/ttnn/operations/matmul/device/multi_core_reuse_mcast_2d_optimized/bmm_op_multi_core_reuse_mcast_2d_optimized.cpp`

**Comment by avoraTT** [comment]
cc @SeanNijjar @davorchap

**Comment by aliuTT** [comment]
I pushed a commit to main that should increase sem count to 8: https://github.com/tenstorrent/tt-metal/commit/f4ffeb64f999c9b05438c67a7bae5afaa658fc1e. Please give it a try.
