### ISSUE TITLE
[Feature Request] Better error message when device not found in open_device()

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#11148]
**Is your feature request related to a problem? Please describe.**

I didn't noticed I broke my DKMS installation thus making the TT driver not load. tt-metal generated an intimidating error message which lead to me thinking it was an ABI issue as it happened to me a few times - I might have forgot to clean something or the build was partial. And lead me down several clean builds and GDB-ing to figure out which library was malfunctioning. Turns out just be driver problem.

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```

![image](https://github.com/user-attachments/assets/5f4431ac-7b9a-4461-9cfc-f01c4637696a)

**Describe the solution you'd like**

Instead of an exception. It would be nice to print an (fatal?) error stating the device is not available. Along the line of `Failed to open device %z. Index out of range. %z devices avaliable` This would help others in avoiding going down the wrong path.

**Describe alternatives you've considered**

**Additional context**

**Comment by dmakoviichuk-tt** [comment]
Hi @marty1885  I added good error message:
It should be something like this:
""Device index 1 out of range. There are 1 devices available.""
Thanks for report!

**Comment by marty1885** [comment]
Thanks!
