### ISSUE TITLE
watcher: report if eth link retraining occurred during teardown

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#11169]
eth cores have a register which counts how many times the eth link is retrained
watcher should read this register at init and again at teardown and report if retraining occured

**Comment by tt-dma** [comment]
0x1EDC address from ethernet core L1 is the counter

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent/tt-metal/pull/12801 implements this
