### ISSUE TITLE
Process got killed while running Llama3.1_8b in WH n300

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#11185]
**Describe the bug**
While running the whole model test (test_llama_model.py), the is process is getting killed due to high memory accumulation in the init() of feed_forward in transformer_block. We are waiting for @yieldthought's responce.

**To Reproduce**
1. Checkout the branch [keerthanar/llama31_8b_n300_ttnn](https://github.com/tenstorrent/tt-metal/tree/keerthanar/llama31_8b_n300_ttnn)
2. Follow the steps in the [README.md](https://github.com/tenstorrent/tt-metal/blob/2e4d901de58d821bfa5f4fd977a7c2683c8bb1e5/models/demos/wormhole_n300/README.md)

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: WH n300

**Comment by uaydonat** [comment]
do we have a screen shot of the error message?

**Comment by uaydonat** [comment]
@mtairum @sraizada-tt can someone take a look at this while Mark is away?

**Comment by sraizada-tt** [comment]
@keerthana-r-mcw Can't reproduce, on an N300 I see your "before ttnn", "after ttnn" prints without any error

**Comment by punithsekar** [comment]
@sraizada-tt , Can I now the Memory of you VM.
The VM which we use consist of memory around 47.1 GB where only approx 40 GB is available to run the test.

**Comment by yieldthought** [comment]
This is an 8B parameter model. To load on CPU in FP32 requires 4x8=32GB just for the reference weights, before even loading the ttnn weights.

Memory requirements for this test are probably >64GB. You can reduce the number of layers if you want to run the test on low-memory systems in the meantime.
