### ISSUE TITLE
Port yolov4 on WH

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#11187]
Port Yolov4 model on WH(n150) device.

**Comment by punithsekar** [comment]
Merged PR #10775 to main.

ToDo:

- Change maxpool to ttnn once the maxpool issue is resolved #7746.

- Replace the torch ops to ttnn ops in demo file.

**Comment by keerthana-r-mcw** [comment]
Closing this issue, since yolov4 is ported to WH.
