### ISSUE TITLE
MobilenetV2 fails with drop in pcc.

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#11189]
**Describe the bug**
MobilenetV2 ttnn implementation with old conv api test fails with pcc of 0.67.

**To Reproduce**
1. Checkout [keerthanar/mobilenetv2_ttnn](https://github.com/tenstorrent/tt-metal/tree/keerthanar/mobilenetv2_ttnn).
2. Use the command to run the test `pytest tests/ttnn/integration_tests/mobilenetv2/test_tttnn_mobilenetv2.py`.
3. The test will fails with the pcc of 0.67.

**Comment by sankarmanoj-tt** [comment]
I think this file mobilenet_v2-b0353104.pth is needed to run this test case. @keerthana-r-mcw Can you share it?

**Comment by sankarmanoj-tt** [comment]
Why is the old Conv API used? I think the test case consists of the entire network. Do you have test cases for smaller functional blocks of the network?

**Comment by mywoodstock** [comment]
AI: upgrade mobilenetv2 to use latest conv api. @keerthana-r-mcw, assigning back to you.
cc: @dvartaniansTT

**Comment by keerthana-r-mcw** [comment]
https://github.com/tenstorrent/tt-metal/issues/11197 : Port MobilenetV2 model to New Conv API on WH n150

**Comment by mywoodstock** [comment]
@keerthana-r-mcw Let us know once the port to new conv API is done, then we can revisit. Perhaps we can close this issue in favor of #11197 ?

**Comment by saichandax** [comment]
@mywoodstock , We are tracking the status of MobilenetV2 in #11197, where we achieve a PCC of 0.94 for real weights.
We have two issues #12140 and #12141 for 9 failing Convs. Please note.

We can close this issue for now.
Thanks
