### ISSUE TITLE
Permute returns a 2D tensor instead of 3D tensor.

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#11191]
**Describe the bug**
Permute returns a 2D tensor instead of 3D tensor when 0th dimension of tensor is 1. 

**To Reproduce**
Run the following code snippet:
```
import ttnn
import pytest
import torch

@pytest.mark.parametrize("device_params", [{"l1_small_size": 24576}], indirect=True)
def test(device):
    input_a=torch.randn(1,32,256)
    tt_input=ttnn.from_torch(input_a,device=device,layout=ttnn.TILE_LAYOUT,dtype=ttnn.bfloat16)
    output=ttnn.permute(tt_input,(0,2,1)) #Expected [1,256,32] but returns [256,32]
    print("output",output.shape) 
```

**Expected behavior**
Expect to be return a 3D tensor instead of 2D tensor while permuting 3D tensor.

**Please complete the following environment information:**
- OS:  Ubuntu 20.04
- Device : GS,WH

**Additional context**
**Available solution:**
If we reshape the 2D tensor output_tensor using,` ttnn.reshape(output_tensor,(1,output_tensor.shape[0],output_tensor.shape[1]))`.
We get the expected shape but there is additional time taken due to reshape operation which will affect the performance.

**Comment by dvartaniansTT** [comment]
@boris-drazic does the mentioned [PR: 311](https://github.com/tenstorrent/pytorch2.0_ttnn/pull/311) above resolve the issue? If so, do we need to make any changes to the way we call `ttnn.permute`  or the syntax should remain the same as in the unit test shared in this issue description? 

@punithsekar please test this one.
