### ISSUE TITLE
Provide APIs to read inf/NaN sticky registers

### ISSUE THREAD

**Issue by ttmtrajkovic** [tenstorrent/tt-metal#11239]
Add compute API so compute kernels could insert the calls to read register values to trisc and put to DPRINT or to some other memory location (as indicated by the programmer).

Milos

Sticky bits are in debug register RISCV_DEBUG_REG_FPU_STICKY_BITS.
To read sticky bits register: reg_read(RISCV_DEBUG_REG_FPU_STICKY_BITS);
Sticky bits definition:
- **Bit 10**: integer saturation  **[blackhole]**
- **Bits 9-7**: L1 accumulation (overflow/underflow/saturation)
- **Bits 6-4**: fpu (overflow/underflow/saturation)
- **Bit 3**: sfpu nan detected
- **Bit 2**: sfpu inf detected
- **Bit 1**: sfpu denormalized detected
- **Bit 0**: sfpu overflow detected

**Comment by ttmtrajkovic** [comment]
merged as part of https://github.com/tenstorrent/tt-metal/pull/13502.
New API has been added, that executes on MATH thread
```
ALWI uint32_t get_compute_special_value_flags()
ALWI uint32_t get_compute_special_value_flags_fpu(uint32_t special_value_flags_reg) 
ALWI uint32_t get_compute_special_value_flags_sfpu(uint32_t special_value_flags_reg)
ALWI void clear_compute_special_value_flags()
ALWI void store_compute_special_value_flags_to_l1(uint32_t l1_addr)
```

**Comment by razorback3** [comment]
It seems like the above APIs don't have documentation yet.
So I guessed how to use them. Is this a correct to call like this?

```
uint32_t flags = get_compute_special_value_flags();
uint32_t fpu_flags = get_compute_special_value_flags_fpu(flags);    // <-- give flags argument returned from the first API call
uint32_t sfpu_flags = get_compute_special_value_flags_sfpu(flags);  // <-- give flags argument returned from the first API call

// do something depeding on the 'fpu_flags' or 'sfpu_flags' values
```

**Comment by razorback3** [comment]
@ttmtrajkovic
Would you confirm the above usage?

**Comment by ttmtrajkovic** [comment]
@razorback3,
Yes, that is the correct usage. I will add comments to the compute_api.h as well. Those are helper functions to extract fpu or sfpu bits only.
Other functions for reading, clearing and dumping bits to L1 should be self-explanatory.

milos
