### ISSUE TITLE
test_sweep_conv_tt - the test relies on TT_METAL_HOME variable to be set

### ISSUE THREAD

**Issue by dimitri-tenstorrent** [tenstorrent/tt-metal#11257]
Test location:
[test_sweep_conv_tt](https://github.com/tenstorrent/tt-metal/blob/614b053a2ded8ab62c3e35c3bf68751b4962b1d7/tests/tt_eager/python_api_testing/sweep_tests/pytests/test_sweep_conv.py#L105)

Code location:
https://github.com/tenstorrent/tt-metal/blob/614b053a2ded8ab62c3e35c3bf68751b4962b1d7/tests/tt_eager/python_api_testing/conv/pytorch_conv_tb.py#L60

Convert the test case to lookup `conv_sweep_params.yaml` relative to the test location as opposed to TT_METAL_HOME location. This is particularly a problem with the wheel installation.

**Comment by mywoodstock** [comment]
Hey @tt-aho, are you familiar with this script?

**Comment by tt-aho** [comment]
I'm not, this was something @tt-nshanker added/was managing I think

**Comment by dimitri-tenstorrent** [comment]
Fixed in the PR #11132
