### ISSUE TITLE
Move layernorm_distributed

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/tt-metal#11313]
https://github.com/tenstorrent/tt-metal/tree/main/ttnn/cpp/ttnn/deprecated/tt_dnn/op_library/layernorm_distributed

More info
https://github.com/tenstorrent/tt-metal/issues/9322

Most recent example
https://github.com/tenstorrent/tt-metal/pull/11468

Detailed procedure on an example from pad/unpad:
https://github.com/tenstorrent/tt-metal/issues/9745

**Comment by djordje-tt** [comment]
fyi @uaydonat

**Comment by uaydonat** [comment]
@johanna-rock-tt is the owner of this op, she can work on this when she is back from vacation next week.
@djordje-tt is working on the llama sprint, trying to get llama prefill working asap this week.

**Comment by djordje-tt** [comment]
@ayerofieiev-tt, let us know if this works for you!

**Comment by ayerofieiev-tt** [comment]
@djordje-tt , @uaydonat 👍

**Comment by eyonland** [comment]
@yugaoTT mentioned he should be able to pick this up.

We should be able to close #11643

**Comment by johanna-rock-tt** [comment]
I appreciate the offer to help out with this, but I already started working on it yesterday and have a PR ready now. @yugaoTT 
 Would you mind taking a look at my [PR](https://github.com/tenstorrent/tt-metal/pull/11696) since you've already migrated ops to ttnn? Thanks!

**Comment by yugaoTT** [comment]
@johanna-rock-tt left some comment there, overall lgtm!
