### ISSUE TITLE
Automate testing

### ISSUE THREAD

**Issue by ttmtrajkovic** [tenstorrent/tt-metal#11336]
How to automate testing through a script: 
1. set conditions (aiclk, voltage, etc.), 
2. detect hang, 
3. reset card (through tt-smi or reset dongle), 
4. rerun next test

Syseng team already does something similar for VF curve analysis so check with them as well.

**Comment by ttmtrajkovic** [comment]
Work has been completed by @ihamer-tt. Info and guides to be added and then this issue could be closed.

**Comment by ihamer-tt** [comment]
This is implemented in the tt-experiment repo, currently at: https://yyz-gitlab.local.tenstorrent.com/tenstorrent/tt-experiment
