### ISSUE TITLE
Replace tt_lib in functional folders

### ISSUE THREAD

**Issue by KalaivaniMCW** [tenstorrent/tt-metal#11342]
Tracking Issue : #11240 , Master Issue : #10532 

- [x] functional_common (no changes)
- [x] functional_mistral
- [x] functional_roberta
- [x] functional_unet
- [x] functional_vit
- [x] functional_whisper (no changes)
- [x] functional_yolov4 (no changes)
- [x] llama

**Comment by bharane-ab** [comment]
Replaced tt_lib with ttnn support for functional folders and llama folder.
Also removed llama2_70b folder
