### ISSUE TITLE
Add users to metal-developers and possibly other groups

### ISSUE THREAD

**Issue by ttmtrajkovic** [tenstorrent/tt-metal#11369]
Please add the following GH user names to `metal-developers` and possibly other groups so I can assign issues to them:
```
tcolacoTT
smohammadiTT
psethiTT
palexsonTT
```

Please also make sure that this person `skrsmanovicTT` has access to all tt-metal groups as he is part of my team (LLKs) and should be member of same groups as me (I had issues assigning him GH tickets as well).

Milos

**Comment by tt-rkim** [comment]
this is done.

please check if things work. close this issue if there are no longer problems.

**Comment by ttmtrajkovic** [comment]
yes, I can see them now. Thanks @tt-rkim
