### ISSUE TITLE
Move SD unit tests to `models/demo/wormhole/stable_diffusion`

### ISSUE THREAD

**Issue by esmalTT** [tenstorrent/tt-metal#11365]
# Summary 

We should move all of the Stable Diffusion tests so that they are co-located with the implementation.  

It probably makes more sense to store these together since it makes it easier to find all SD-related code, instead of having the SD-functionality scattered around the repository. This is more consistent with what other models are doing.

**Comment by tt-rkim** [comment]
Is this done?
