### ISSUE TITLE
[GH Permissions] Add skrsmanovicTT as contributor to the tt-metal project

### ISSUE THREAD

**Issue by skrsmanovicTT** [tenstorrent/tt-metal#11363]
## What you are trying to do...

Need to be added as contributor to the tt-metal project. I need ability to be issue owner, push code...

## Who needs permissions...

Stefan Krsmanovic, github account name skrsmanovicTT, member of LLK team

## Optional screenshot etc...
@tt-rkim @TT-billteng

**Comment by tt-rkim** [comment]
Please check now that you have access to create a branch and be assigned to an issue

**Comment by skrsmanovicTT** [comment]
Looks like everything works
