### ISSUE TITLE
Replace tt_lib usage in `tests/ttnn/unit_tests` , `operations` , `complex`

### ISSUE THREAD

**Issue by VirdhatchaniKN** [tenstorrent/tt-metal#11367]
Tracking Issue : #11242 , Master Issue : #10532

Updates : 
PR : https://github.com/tenstorrent/tt-metal/pull/11549 - Ready to be reviewed

**Comment by KalaivaniMCW** [comment]
@VirdhatchaniKN Could you please include changes for the entire `tests/ttnn` folder as well in this issue? that way we can avoid conflicting PRs

**Comment by VirdhatchaniKN** [comment]
PR : https://github.com/tenstorrent/tt-metal/pull/11549 - Ready to be reviewed
