### ISSUE TITLE
AllGather op-to-op latency optimization

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent/tt-metal#11398]
AllGather has 20-27us dispatch latency, fairly higher than other ops. Details in https://github.com/tenstorrent/tt-metal/issues/11386

**Comment by SeanNijjar** [comment]
Some comments from our offline discussion about this issue:
- Seems remote chips are much higher latency than local chips (weird for a trace?)
  - about 6-7k cycle difference
- From inspecting the current kernels, they make heavy use of CT args to they point where we'd have unique binaries per worker. 
  - I did previously try moving to runtime args and saw a noticeable performance degradation (not catastrophic, but definitely measurable and noticeable).
    - I will revive this work but make more surgical changes from compile time to runtime args (this should hopefully help with both issues)
  

Also could the dispatcher datapath flush be in anyway contribute to this? (@tt-asaigal)

**Comment by SeanNijjar** [comment]
posting notes from chat with @xuncaiTT for reference:

> ### The 4 kernels:
ttnn/cpp/ttnn/operations/ccl/all_gather/device/kernels/dataflow/worker_interleaved_ring_gather_send_writer.cpp
ttnn/cpp/ttnn/operations/ccl/all_gather/device/kernels/dataflow/worker_interleaved_ring_gather_send_reader.cpp
ttnn/cpp/ttnn/operations/ccl/all_gather/device/kernels/dataflow/worker_interleaved_ring_gather_receive_writer.cpp
ttnn/cpp/ttnn/operations/ccl/all_gather/device/kernels/dataflow/worker_interleaved_ring_gather_receive_reader.cpp

> ### Known fields that will need to be runtime args
num_full_chunks
output_start_page_idx
row_start_idx
eth_*_noc*
eth_*_sem*
eth_*_addr*
rem_num_pages
is_clockwise_direction
row_offset
col_offset
col_start_idx
row_start_idx
output_start_addr_offset
output_start_page_idx
num_full_chunks
input_start_ring_idx

> ### Args I'm unsure of (you'll need to inspect the code:)
output_addr_offset
last_output_addr_offset
output_page_offset
last_output_page_offset

> ### Args that I think are common but might be unique:
num_pages

**Comment by tt-asaigal** [comment]
Hey @SeanNijjar the 6-7us difference on remote chips was because of how the dispatch cores are setup on local vs remote. We tried a hack to make the core placement identical and the delta disappeared. 

Dispatch pipeline flush will contribute to this when running in eager mode. We bypass this flush with trace.

**Comment by uaydonat** [comment]
@SeanNijjar anything else to improve for dispatch latency, or close?

**Comment by SeanNijjar** [comment]
we can close after all changes are merged
