### ISSUE TITLE
Bad PCC on Llama3.1-8B model test with prefill

### ISSUE THREAD

**Issue by mtairum** [tenstorrent/tt-metal#11438]
To reproduce:
`pytest models/demos/wormhole/llama31_8b/tests/test_llama_model_prefill.py::test_llama_model_inference[4096]`

The PCC we are seeing on this test is `0.866`. 

Up until 512 sequence length the PCC are ok (above 0.94).

**Comment by yieldthought** [comment]
@mtairum this looks similar to the Mixtral issue you are investigating, correct?

**Comment by mtairum** [comment]
Not quite. The llama issue is something that is there from start. 
The Mixtral one is caused by some recent change to the code. 

The similarities are that PCC is not great, but the causes seem different for now.

**Comment by mtairum** [comment]
@yieldthought Should we close this issue to condense things into the single codebase?
