### ISSUE TITLE
Runtime Error while running Llama3.1-8B model on n150

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#11445]
**Describe the bug**
Facing run time error while running llama3.1-8B (WH-n150) model which is in main.

**To Reproduce**
1. In main ([#0: remove decorate_as_composite](https://github.com/tenstorrent/tt-metal/commit/f8ff718f60d5bd1e78e699e7cef2632930b1e10b)) branch
2. Setup the environment  for llama using the README available in path `models/demos/wormhole/llama31_8b/README.md`
3. Replace  `state_dict = torch.load(model_args.consolidated_weights_path)`  with `state_dict = torch.load(model_args.consolidated_weights_path, map_location=torch.device("cpu"))` in `models/demos/wormhole/llama31_8b/tests/test_llama_attention.py` file. Since we are using CPU device. 
4. The test will throw error.

**Expected behavior**
Test should Pass.

**Please complete the following environment information:**
- OS:  Ubuntu 20.04
- WH n150

**Additional context**
We face this issue in files `models/demos/wormhole/llama31_8b/tests/test_llama_decoder.py` and `models/demos/wormhole/llama31_8b/tests/test_llama_model.py` files also since its depend on attention sub_module.

We didn't try to resolve it since the issue is on main.

CC: @keerthana-r-mcw @saichandax

**Comment by dvartaniansTT** [comment]
@punithsekar what is the run time error you see here?

**Comment by punithsekar** [comment]
Yes, the above mentioned is the issue we face.

**Comment by cglagovichTT** [comment]
Please try replacing that call with `ttnn.experimental.nlp_concat_heads_decode`. This change was merged recently, and you may see it in other places as well

**Comment by punithsekar** [comment]
Closing this issue. since,In latest main attention module is working fine.
