### ISSUE TITLE
Shallow UNet on n300 gives less FPS

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#11459]
**Describe the bug**
On generating performance sheet of Shallow UNet model on n300 (WH) device and utilizing Tenstorrent Perf Sheet Processor tool gives less FPS. (Current FPS for all ops: 11.144)

**To Reproduce**
1. Checkout to the branch [keerthanar/shallow_unet_n300](https://github.com/tenstorrent/tt-metal/compare/keerthanar/shallow_unet_n300)
2. Build the repo with profiler (`scripts/build_scripts/build_with_profiler_opt.sh`)
2. Run the command: `./tt_metal/tools/profiler/profile_this.py -n shallow_unet_n300 -c "pytest models/experimental/functional_unet_n300/tests/tests/test_unet_shallow_functional.py"`
3. Upload the generated perf in [Tenstorrent Perf Sheet Processor](https://perfsheet.streamlit.app/) tool to get the FPS.
4. Here are the generated perf sheets of Shallow UNet model on n300: [ops_perf_results_shallow_unet_n300.csv](https://github.com/user-attachments/files/16778245/ops_perf_results_shallow_unet_n300.csv)

**Expected behavior**
To get FPS of 1500.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: n300 (WH)

**Comment by mbahnasTT** [comment]
@HariniMohan0102 @saichandax I believe the description of the issue needs some revision. 
Can you share the original perf css generated by profile_this?

**Comment by mbahnasTT** [comment]
@HariniMohan0102 can you file an issue for the upsample regression, per your discussion with @esmalTT ?

**Comment by keerthana-r-mcw** [comment]
https://github.com/tenstorrent/tt-metal/issues/11913: Shard ttnn.upsample input in UNet so that we use more than 1 core
https://github.com/tenstorrent/tt-metal/issues/11912: UNet Shallow device performance has regressed

**Comment by esmalTT** [comment]
Let's close this in favour o

> #11913: Shard ttnn.upsample input in UNet so that we use more than 1 core #11912: UNet Shallow device performance has regressed

@keerthana-r-mcw Please close this in favour of these issues. 👍
