### ISSUE TITLE
Remove -Wno-c++23-extensions 

### ISSUE THREAD

**Issue by cfjchu** [tenstorrent/tt-metal#11488]
@yan-zaretskiy made a good point that we should review `-Wno-c++23-extensions` and why we need this compiler flag. Part of what has caused the recent issue of GCC-compile failing is because we were actually using C++ language features like `static operator ()`. We shouldremove this flag until we actually move to C++23 or we actually get g++-12 going on CI regressions

In `cmake/compilers.cmake` we have:

```
function(ADJUST_COMPILER_WARNINGS)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        target_compile_options(compiler_warnings INTERFACE
            -Wsometimes-uninitialized -Wno-c++11-narrowing -Wno-c++23-extensions -Wno-error=local-type-template-args
            -Wno-delete-non-abstract-non-virtual-dtor -Wno-c99-designator -Wno-shift-op-parentheses -Wno-non-c-typedef-for-linkage
            -Wno-deprecated-this-capture -Wno-deprecated-volatile -Wno-deprecated-builtins -Wno-deprecated-declarations
        )
    else() # GCC-12 or higher
        target_compile_options(compiler_warnings INTERFACE
            -Wno-deprecated -Wno-attributes -Wno-stringop-overread -Wno-stringop-overflow -Wno-maybe-uninitialized -Wno-missing-requires
            -Wno-narrowing -Wno-non-template-friend -Wno-error=non-template-friend
        )
    endif()
endfunction()
```

**Comment by cfjchu** [comment]
fyi @eyonland

**Comment by tt-rkim** [comment]
@TT-billteng does this include any extra library stuff, or is just compile-time extensions?

**Comment by TT-billteng** [comment]
> @TT-billteng does this include any extra library stuff, or is just compile-time extensions?

don't understand your question

**Comment by tt-rkim** [comment]
Never mind, I actually don't understand what I was trying to ask now either.

I think @TT-billteng just merged a debug gcc-12 build into main. Is there a reason to have this flag for clang?

**Comment by TT-billteng** [comment]
think @vtangTT added it when he was doing initial his `CMake` work

**Comment by vtangTT** [comment]
Yep this was added when I initiallly tried enabled clang-17 compiler

**Comment by TT-billteng** [comment]
> Yep this was added when I initiallly tried enabled clang-17 compiler

The name of the flag suggests that we _shouldn't_ be using anything C++23, but @cfjchu is suggesting this flag enables C++23 features???

**Comment by vtangTT** [comment]
My understanding is that this flag will disable warnings that compiler throws when we try to use C++23 features

**Comment by TT-billteng** [comment]
> My understanding is that this flag will disable warnings that compiler throws when we try to use C++23 features

ah so let's remove it

**Comment by vtangTT** [comment]
Flag has been removed, closing. 

Follow up issue to remove the rest of the extra build flags: https://github.com/tenstorrent/tt-metal/issues/11488
