### ISSUE TITLE
Conv2D with 1x1 filter size crashes when program cache is enabled

### ISSUE THREAD

**Issue by esmalTT** [tenstorrent/tt-metal#11490]
### Summary

Convolution with a 1x1 filter size is crashing when program cache is enabled. This is unexpected because the same convolution without program cache works as expected.

This is currently preventing us from enabling program cache in UNet Shallow.

### Steps to reproduce

Run the following test case:

``` python
import pytest
import torch
import ttnn


@pytest.mark.parametrize("enable_program_cache", [True, False])
def test_conv1x1_with_program_cache(device, enable_program_cache):
    ttnn.enable_program_cache(device) if enable_program_cache else ttnn.disable_and_clear_program_cache(device)

   # Shapes are from UNet Shallow output projection
    x = ttnn.from_torch(
        torch.rand((1, 1, 337920, 16)),
        device=device,
        layout=ttnn.TILE_LAYOUT,
        memory_config=ttnn.L1_MEMORY_CONFIG,
        dtype=ttnn.bfloat16,
    )
    weight = ttnn.from_torch(torch.rand((1, 1, 32, 32)), device=device, layout=ttnn.TILE_LAYOUT, dtype=ttnn.bfloat16)

    x, _, _, _, _ = ttnn.conv2d(
        input_tensor=x,
        weight_tensor=weight,
        in_channels=16,
        out_channels=1,
        input_height=1056,
        input_width=160,
        batch_size=2,
        kernel_size=(1, 1),
        stride=(1, 1),
        padding=(0, 0),
        conv_op_cache={},
        device=device,
    )
```

You will see one failed and one passing test case, where the test case using program cache has failed.

```sh
PASSED test_stuff.py::test_conv1x1_with_program_cache[False]
FAILED test_stuff.py::test_conv1x1_with_program_cache[True] - RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp:936: a_shape[-1] == b_shape[-2]
```

**Comment by sankarmanoj-tt** [comment]
The input tensor has 16 channels, but the weights tensor has 32. Is this intended?

**Comment by esmalTT** [comment]
@sankarmanoj-tt I can confirm that is the shape of the weight currently used in UNet.

It might be better to use 16[32] instead - I’ll look into it.

Regardless, we should probably try to keep the same behaviour between the two test cases, even if it is they both fail.

**Comment by esmalTT** [comment]
@sankarmanoj-tt Using 16[32] on the weights will work with the new conv API. Unfortunately there is still an issue when adding the bias:

```python
import pytest
import torch
import ttnn


@pytest.mark.parametrize("enable_program_cache", [True, False])
def test_conv1x1_with_program_cache(device, enable_program_cache):
    ttnn.enable_program_cache(device) if enable_program_cache else ttnn.disable_and_clear_program_cache(device)

    x = ttnn.from_torch(
        torch.rand((1, 1, 337920, 16)),
        device=device,
        layout=ttnn.TILE_LAYOUT,
        memory_config=ttnn.L1_MEMORY_CONFIG,
        dtype=ttnn.bfloat16,
    )
    weight = ttnn.from_torch(torch.rand((1, 1, 16, 1)), device=device, layout=ttnn.TILE_LAYOUT, dtype=ttnn.bfloat16)
    bias = ttnn.from_torch(torch.rand((1, 1, 1, 1)), device=device, layout=ttnn.TILE_LAYOUT, dtype=ttnn.bfloat16)

    x, _, _, _, _ = ttnn.conv2d(
        input_tensor=x,
        weight_tensor=weight,
        bias_tensor=bias,
        in_channels=16,
        out_channels=1,
        input_height=1056,
        input_width=160,
        batch_size=2,
        kernel_size=(1, 1),
        stride=(1, 1),
        padding=(0, 0),
        conv_op_cache={},
        device=device,
    )
```

Fails with: 
```sh
E           RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp:976: bias_shape[-1] == b_shape[-1]
E           info:
E           Unsupported bias shape: last dimension not equal to second input's last dimension.
```

**Comment by sankarmanoj-tt** [comment]
This is a really good test case. There are multiple issues present. 

From my debugging, it looks like the test case should fail , regardless of program cache. However when program cache is disabled, the validate method of the operator is not called, and so it doesn't encounter an error. 

The actual error is due to the mixed use of `tt::tt_metal::Shape` and `ttnn::types::Shape`. `tt::tt_metal::Shape::operator[]` returns the dimension without padding, but  `ttnn::types::Shape::operator[]` returns the dimension with padding. 

In cases where the dimension is not a multiple of 32, these two are not equal, leading to the assertion error.

**Comment by esmalTT** [comment]
I have enabled the unit tests for all UNet shapes except the broken 1x1 convolution. Can you also re-enable this test: [link]( https://github.com/tenstorrent/tt-metal/pull/11589/files#diff-a12e9d2163373764226265abe79f7110f97babe271d8c74af9a745cf88308e33R1102) when this issue is fixed?

**Comment by esmalTT** [comment]
> Thanks @sankarmanoj-tt for the investigation. So in summary:
> 
> 1. The bug is in `validate` of matmul where dimensions from "ttnn shape" and "tt_metal shape" are mixed and compared, where the former takes shape without padding, while the latter with. Simple solution: use `.without_padding()` tt_metal shape when comparing the "unpadded" sizes. [#11490: ttnn and tt_metal shapes are mixed #11723](https://github.com/tenstorrent/tt-metal/pull/11723) cc: @bbradelTT
> 2. `validate` function seems to be called only when `program_cache == True` and not when its `False`. Not sure if this is the intended behavior for `validate`. Will flag it with the ttnn/metal infra. I thought `validate` is always called in Debug mode.

@mywoodstock Thanks for fixing this. 

Now that the behaviour between cached/non-cache is the same, I feel like practically we should properly handle the case where a user runs a _conceptually_ valid convolution - i.e. `in_channels=16`, `out_channels=1` input tensor has 16[32] channels, etc.

Even if we don't handle it properly, we should crash higher in the stack with a better message.
