### ISSUE TITLE
[Feature Request] Enable default parameter for ttnn::untilize memory config in C++ API

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#11499]
**Is your feature request related to a problem? Please describe.**

In the past, untilize has a default memory config so calling `tt::tt_metal::untilize(tensor)` just works. However, the new API requires the 2nd parameter to be set, even though it is a `optional`.

To illustrate. This used to work

```c++
tt::tt_metal::Tensor t = ....;
t = tt::tt_metal::untilize(t);
```

However the new API makes untilizing much more verbose. It also doesn't make sense the optional<> parameter is not actually optional.

```c++
tt::tt_metal::Tensor t = ....;
t = tnn::untilize(t, ttnn::types::MemoryConfig{}); // yeah...
t = tnn::untilize(t, std::nullopt); // not much better
```

**Describe the solution you'd like**
Allow `ttnn::untilize` API to simply take 1 parameter. Reduce API verbosity.

**Describe alternatives you've considered**

**Additional context**
I'll make a PR shortly

**Comment by ayerofieiev-tt** [comment]
Thank you, @marty1885 ! 

CC @tarafdarTT @yan-zaretskiy
