### ISSUE TITLE
Additional TTNN Migration

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#11513]
The original migration effort did not scope in the work for migrating ops located within 

 Migrate tt_lib_bindings.cpp -
- [x] #11693
- [x] #11809
- [x] #11644
- [x] #11645
- [x] #11643
- [x] #11646
- [x] #11651
- [x] #11691
- [x] #11688
- [x] #11989

Track related updates: https://docs.google.com/spreadsheets/d/1iJJ_hH53PFwOpfaNmoBE9fgp7HXWoRMU8xzQVQ633ug/edit?usp=sharing

**Comment by KalaivaniMCW** [comment]
All tasks completed
