### ISSUE TITLE
Automate generation of Sphinx documentation for ops

### ISSUE THREAD

**Issue by yan-zaretskiy** [tenstorrent/tt-metal#11531]
Problem:
- Presently, we have to create individual `.rst` files for every op we want to list in the Sphinx documentation. This creates unnecessary friction to adding documentation.

Solution:
- I propose to create a Sphinx extension that would only require us to list op names in the single `api.rst` file and will generate the corresponding HTML page automatically.

Ops tracking spreadsheet:
https://docs.google.com/spreadsheets/d/1a2xfEWbtvkjAGNxL70es6tJoOeDh64OlAgbvDii-BU8/edit?pli=1&gid=0#gid=0

**Comment by bharane-ab** [comment]
current status:

Total ops 344
completed ops = 287
remaining ops = 57

**Comment by bharane-ab** [comment]
current status:

Total ops 344
completed ops = 344

work need to be addressed:

- Make document similar to PyTorch reference.
- Document valid range.
- Add optional output tensor and Qid.
- Address documentation bug
- Fix math issue for the ops

**Comment by bharane-ab** [comment]
Merged to main.
