### ISSUE TITLE
Investigate huge slowdowns on CI vm-58

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#11609]
For example, https://github.com/tenstorrent/tt-metal/actions/runs/10433494468/job/28895445603

should be passing in a couple of mins, but takes the whole 45 min timeout.

Reported by @pgkeller @tt-aho 

cc: @TT-billteng @ttmchiou

**Comment by TT-billteng** [comment]
could be related to https://github.com/tenstorrent/cloud/issues/3007 as they're mapped to the same BM

**Comment by TT-billteng** [comment]
@pgkeller mentioned that vm-69 became much faster after host reboot. I'd assume the same has happened to 58 as they were mapped to the same BM. Re-open if needed.
