### ISSUE TITLE
Runtime Error in llama3_1.8b model while porting on n300 

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#11602]
**Describe the bug**
I am facing assertion error from linear while running attention_prefill sub_module test for seq_len=4096 but test is passing for seq_len=128.

**To Reproduce**
1. Checkout to [punith/llama31_8b_n300](https://github.com/tenstorrent/tt-metal/compare/main...punith/llama31_8b_n300) branch.
2. Download the weights and set the environment with help of the Readme available in path `models/demos/wormhole/llama31_8b/README.md.`
3. Run `pytest models/demos/wormhole/llama31_8b/tests/test_llama_attention_prefill.py `
4. The test fails.

**Screenshots**
The test will be failing with the below error log in linear,
```
E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_2d_program_factory.cpp:1328: num_blocks_y <= num_cores_y
E       info:
E       Num output blocks along y 8 must be smaller than or equal to the number of rows in compute grid 4!
```
So, I tried changing the per_core_M of that linear to 16(To try this, Change per_core_M in line 239 from 4 to 16 in file  model_config which is available in path models/demos/wormhole/llama31_8b/tt/model_config.py),
Here the test is getting failed due to  Statically allocated circular buffer,
```
E       RuntimeError: TT_THROW @ ../tt_metal/impl/program/program.cpp:507: tt::exception
E       info:
E       Statically allocated circular buffers on core range [(x=0,y=0) - (x=7,y=3)] grow to 2937696 B which is beyond max L1 size of 1499136 B
```

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Device: WH-n300

CC: @saichandax

**Comment by yieldthought** [comment]
The problem appears to be this code:

```
xqkv_fused = ttnn.linear(
    xs_11SH,
    wqkv,
    dtype=ttnn.bfloat16,
    memory_config=ttnn.DRAM_MEMORY_CONFIG,
    compute_kernel_config=self.compute_kernel_config,
    program_config=self.model_config["XQKV_PREFILL_PROGCFG"](seq_len),
)
```

Where:

```
self.model_config["XQKV_PREFILL_PROGCFG"] = lambda seq_len: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
    compute_with_storage_grid_size=(8, 4),
    in0_block_w=4,  # how much inner dim you take each time
    out_subblock_h=1,  # Must be divisible by per_core_M
    out_subblock_w=1,  # Must be divisible by per_core_N, out_subblock_w * out_subblock_h <= 4
    per_core_M=max(
        4, seq_len // (512 if seq_len > 2048 else 256)
    ),  # M / TILE_HEIGHT / Grid_Size (dynamic based on seqlen)
    per_core_N=24,  # N / TILE_WIDTH / Grid_Size
    transpose_mcast=False,
    fused_activation=None,
    fuse_batch=seq_len <= 2048,
    )
```

This is n MxKxN matmul, i.e. multiplying an MxK matrix by a KxN matrix and outputting an MxN matrix. The error message says that the number of output blocks along y (rows) is 8, but the number of rows in the compute grid is 4, and that there must be fewer or equal output blocks to compute rows. 8 > 4 therefore this is an incorrect program config.

I notice that `compute_with_storage_grid_size=(8, 4)` directly sets the rows to 4. I'm not sure why you changed this, but increasing it back to (8, 8) almost works:

`FATAL    | Statically allocated circular buffers on core range [(x=0,y=0) - (x=7,y=7)] grow to 1626976 B which is beyond max L1 size of 1499136 B`

This means we are asking for 1.6MB L1 but only 1.5MB L1 is available. We can save a little bit of L1 by reducing the size of the inner_dim that is processed at once from 4 to e.g. 1:

`in0_block_w=1,`

With these two changes (compute grid to 8,8 and in0_block_w=1) the test passes for me:

`PASSED models/demos/wormhole/llama31_8b/tests/test_llama_attention_prefill.py::test_llama_attention_inference[4096]`

I have not committed and pushed these changes as I am not sure why you reduced the compute grid from 8,8 to 8,4 in the first place, but perhaps you can try and see if this solution works for you?

**Comment by yieldthought** [comment]
per_core_M and per_core_N are not really user-configurable parameters - they have one correct value and that must be set. They tell the config how big the M and N dimensions are respectively and should be set to match the input matrix dimensions. in0_block_w can be freely chosen within L1 constraints, larger values are more efficient. Also it has to divide evenly into the inner dim size.

**Comment by punithsekar** [comment]
Closing this issue, Llama3_1.8b code for n150 which is available in main is working fine in device n300 without any changes.
