### ISSUE TITLE
[Blackhole] ND hangs on BH CI

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#11623]
Opening this issue to track ND issues in BH CI:

e.g. run: https://github.com/tenstorrent/tt-metal/actions/runs/10446932508

The hanging tests pass 10x on IRD (yyzo-bh-26):
```
TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=CommonFixture.MatmulMultiCoreMultiDRAMIn0MCastIn1MCast --gtest_repeat=10

./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=CommonFixture.MatmulLargeBlock --gtest_repeat=10
```

**Comment by abhullar-tt** [comment]
@ttmchiou was also seeing that gh01 and gh02 runners were behaving differently (tests passing on gh01 hang on gh02)

**Comment by ttmchiou** [comment]
For reference sake,
We should also explore the case where this ND behavior is caused by previous test cases too.
Note that gh02 has not been running on CI when this ND bug was filed

**Comment by abhullar-tt** [comment]
> For reference sake, We should also explore the case where this ND behavior is caused by previous test cases too. Note that gh02 has not been running on CI when this ND bug was filed

yes I am currently looping the cpp test suite locally on bh-26

**Comment by abhullar-tt** [comment]
Another case of ND issue: https://github.com/tenstorrent/tt-metal/actions/runs/10484423109/job/29039018451

**Comment by abhullar-tt** [comment]
Seeing the same hang on machine gh02
https://github.com/tenstorrent/tt-metal/actions/runs/10637163877/job/29490937662

**Comment by abhullar-tt** [comment]
- [ ] #12187

**Comment by abhullar-tt** [comment]
Closing this because we haven't seen ND behaviour beyond #12187 which was addressed by enabling the cmd buffer fifo
