### ISSUE TITLE
[Feature Request] Remove flatbuffers from exposed headers

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#11640]
**Is your feature request related to a problem? Please describe.**

Currently UMD pulls in the `flatbuffers` library which is in turn pulled in by CPM. This leads to integrating TTNN from a 3rd party C++ library difficult as the 3rd party project also has to pull in the same version of flatbuffers via CPM or other means. Since the flatbuffers is not used in any API. It would be great to hide flatbuffers from headers.

This is a deal breaker for me as I cannot use CPM in GGML. Nor I can expect distros to happen to use the same version of flatbuffers as TTNN is using.

I have opened 2 PR, one in UMD and one in tt-metal to address the issue. The two PRs does the following respectively

1. Hide flatbuffers from UMD header
2. Include the generated flatbuffers in tt-metal cpp file

The TTNN PR must be merged before UMD is merged and pulled in.

Arguably this is a long(-er) discussion. But I still want to put my patches out and see how can we work towards a solution.

**Describe the solution you'd like**
Do not expose flatbuffers in UMD header.

**Describe alternatives you've considered**

**Additional context**

**Comment by vtangTT** [comment]
Merged by https://github.com/tenstorrent/tt-metal/pull/11766

Please let me know if there are any problems.

**Comment by marty1885** [comment]
Thank you @vtangTT for the quick help! Tested locally, working well! Closing.
