### ISSUE TITLE
ttnn resnet50 xxlarge new fails on nightly single-card regression

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#11667]
`tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet50_xxlarge_new.py` is failing on both N150 and N300. Seems like hangs with no logs: https://github.com/tenstorrent/tt-metal/actions/runs/10471100159/job/29002899016

**Comment by mywoodstock** [comment]
Hmm, unable to repro. Passes fine when I try on n150.

**Comment by tt-rkim** [comment]
How long did it take?

**Comment by mywoodstock** [comment]
```
real	6m45.718s
user	5m57.850s
sys	0m31.830s
```

**Comment by tt-rkim** [comment]
asFSDLAKFJASDKFJAOPMG SDF+aSDFk
We need to increase the TIMEOUT!

There is a overall 5 minute timeout to most test in this pipeline 😆

**Comment by mywoodstock** [comment]
I see. This particular tests takes long partly due to the reference/goldenmodel run takes long.

**Comment by tt-rkim** [comment]
How about other tests? Do we know what can take particularly long there?

**Comment by mywoodstock** [comment]
@tt-rkim we can close this, right?

**Comment by tt-rkim** [comment]
YES SIRRRRRRRRRRR
