### ISSUE TITLE
Debug failing workload with suspect of didt

### ISSUE THREAD

**Issue by ttmtrajkovic** [tenstorrent/tt-metal#11679]
branch: `origin/ppopovic/rebased_didt_tests`
system: `yyz-lab-94`; board id: `0x010001451170c0cf`

Repro steps:
```
cd ~/tt-metal/
export PYTHONPATH=$(pwd)
export TT_METAL_HOME=$(pwd)
export ARCH_NAME=wormhole_b0
./build_metal.sh
source python_env/bin/activate
TT_ENABLE_MATMUL_STAGGER=1 WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/demos/falcon7b/tests/test_falcon_hang.py -k "test_reproduce_lm_head_nd_32 and 1chips"
```

Failing test has ARC alive and healthy, no thermtrip happening.

**Comment by ttmtrajkovic** [comment]
Same signature got on `yyz-lab-210` which is a 4-card t3000 system

**Comment by TT-BrianLiu** [comment]
It's also reproducible on `sjc-snva-t3005`. I will take a look.

**Comment by ttmtrajkovic** [comment]
Detailed debug steps with distinction of post-codes is described here: https://github.com/tenstorrent/tt-metal/issues/13091
No SW problems have been found, this debug is a signature of a failure that we believe is due to high di/dt transitions
