### ISSUE TITLE
TGG UMD close bug

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent/tt-metal#11671]
Seeing UMD device driver close hitting 0xffffffff on MMIO chips 4,5,6,7.

Steps to repro
- log onto `g06cs03`, IP is `172.27.29.29`
- `git checkout aliu/tgg-debug`
- `./build_metal.sh`
- `TT_METAL_ENABLE_REMOTE_CHIP=1 ./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter="CommandQueueSingleCardFixture.TestSingleCbConfigCorrectlyUpdateSizeSentSingleCore"`

Error is ND, sometimes the devices finish closing.

To reset:
- `tt-smi -r tt-metal/mobo_reset.json`

**Comment by aliuTT** [comment]
There are two patches on this branch that may be needed in main for TGG support:
```
inline uint16_t get_umd_channel(uint16_t channel) {
-    return channel & 0x3;
+    return channel & 0x7;
```

```
@@ -222,6 +222,9 @@ void Cluster::assign_mem_channels_to_devices(
    // One WH gateway should have 8 remote deivces in its control group.
    TT_ASSERT(controlled_device_ids.size() <= 9, "Unable to assign each device to its own host memory channel!");
    uint16_t channel = 0;
+    if (mmio_device_id > 3) {
+       channel = 16;
+   }
```

**Comment by aliuTT** [comment]
To try:
- `tt-smi` to check temperature of boards after fail and reset
- Maybe try umd test:
```
tt_SiliconDevice device = tt_SiliconDevice(chip_id=4)
device.close()
```
- Try test on `g07cs01`

**Comment by sagarwalTT** [comment]
The issue was a hardware issue with Device 4 on `g06cs03`. We replaced this device with a fresh one and the test passes now without any issue. https://github.com/tenstorrent/cloud/issues/3083
