### ISSUE TITLE
Runtime Error: Unable to reshape tensor of certain input shape

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#11694]
**Describe the bug**
I am unable to reshape tensor of shape [1,256,256] to [1,256,8,32] by keeping the tensor on device.

**To Reproduce**
1. Checkout to branch, [punith/segformer_issues](https://github.com/tenstorrent/tt-metal/compare/main...punith/segformer_issues)
2. Run command, `pytest models/experimental/functional_segformer/segformer_unit_test_2.py`

**Expected behavior**
The reshape operation should be happening without any issue

**Screenshots**
```
E       RuntimeError: TT_THROW @ ../ttnn/cpp/ttnn/operations/core/core.cpp:61: tt::exception
E       info:
E       Unable to reshape given tensor!
E       backtrace:
E        --- ttnn::operations::core::reshape(tt::tt_metal::Tensor const&, ttnn::types::Shape const&)
```

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Device: GS,WH-n150

**Additional context**
If we remove the tensor from device before passing it into reshape operation the reshape is happening without any issue.

CC: @saichandax

**Comment by sjameelTT** [comment]
> hey @ntarafdar, @sjameelTT , how to differentiate on which dimension to reshape, if 2 dimensions have the same value? like  [1,256,256]

Reshape is based on total volume (multiplication of all dims) not based on splitting a dimension. It won't make a difference.

**Comment by sjameelTT** [comment]
I think normal reshape doesn't mess around with the tiles and just reinterprets the data, but reshape on device may affect the pages. @ntarafdar do you know how it breaks aparts pages?
