### ISSUE TITLE
Use new Conv2D API in UNet Shallow

### ISSUE THREAD

**Issue by esmalTT** [tenstorrent/tt-metal#11706]
### Summary

Refactor UNet to use the new convolution API. This is required because:
- The deprecated Conv2D API does not currently have functional support for multi-device tensors. We need this to implement N300 and T3K data parallel implementation of UNet:
   - https://github.com/tenstorrent/tt-metal/issues/11447 
   - https://github.com/tenstorrent/tt-metal/issues/10754
-  We need to upgrade to the new API to take advantage of new performance improvements like split readers.

**Comment by keerthana-r-mcw** [comment]
Hi @esmalTT, 
Please refer to the new conv-api unit test for all conv variants in shallow unet, which has passed in n300, [Commit](https://github.com/tenstorrent/tt-metal/commit/5824b7bfd45f290ab3476af44a535136721cf21a)
To run the unit test use the following commands,

> `pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_unet_conv_wh`
> `pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_unet_conv_wh_padded_n300`

The shallow UNet has been implemented using the new conv-api in N300. Please refer to the branch for more details. [keerthanar/shallow_unet_n300](https://github.com/tenstorrent/tt-metal/tree/keerthanar/shallow_unet_n300)
