### ISSUE TITLE
Runtime SW assumes too many threads 

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#11717]
Running `time build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch -w 5000 -s 8192 -x 7 -y 6 -kg 7` on BH machine (yyzo-bh-26) consistently takes around 30s Tracy difference between WH and BH: 

![image](https://github.com/user-attachments/assets/a3d60453-cc90-4f0e-962a-88f7c1bacfbd)

`build_firmware` on BH was around ~10s

The above config is ran with taskflow having 32 available threads

Experimented with setting `TT_METAL_THREADCOUNT` to 4 / 8 / 16:
- `build_firmware` _can_ take closer to ~500ms
- `time build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch -w 5000 -s 8192 -x 7 -y 6 -kg 7` takes anywhere from ~9s to ~27s

**Comment by pgkeller** [comment]
@abhullar-tt is this done?

**Comment by abhullar-tt** [comment]
> @abhullar-tt is this done?

Merged one change that helped reduce some compile time issues but I left this open because I think we can do more here.

**Comment by arikTT** [comment]
@pgkeller @abhullar-tt in `JitBuildState::compile`, we spin a new thread for each source, but in the test I'm running, there is always just one source to compile. Spinning a new thread in that case adds some overhead. Are there cases of multiple sources per build state?

**Comment by pgkeller** [comment]
> [@pgkeller](https://github.com/pgkeller) [@abhullar-tt](https://github.com/abhullar-tt) in `JitBuildState::compile`, we spin a new thread for each source, but in the test I'm running, there is always just one source to compile. Spinning a new thread in that case adds some overhead. Are there cases of multiple sources per build state?

maybe the problem is the build?  also, maybe capture the build command line and run it offline and see how long it takes (is this just the filesystem being dog slow)?

**Comment by arikTT** [comment]
I see a compile that takes 12 seconds when running the test, but just 0.5 seconds if I execute it manually at the same directory and all the same settings. Definitely more to investigate.

**Comment by abhullar-tt** [comment]
Per @mo-tenstorrent the unknown threads are are ghost zones. These are threads that were sampled but had not instrumentation. I recall @mo-tenstorrent mentioning that these should not impact the run

**Comment by mo-tenstorrent** [comment]
Could you share the WH and BH `.tracy` files. 

Yes those unknown threads are ghost, i.e. sampled zones. Very likely showing on BH only because its host machine is setup incorrectly and it is exposing highest level of perf data. 

You can replicate the same thing on the WH machine by running the same command in a root / `sudo su` login. 

These are for sure real though something from our main is eventually spinning them up either through our code or something third party.  What does it show when you hover over them? It might hint at a source or .so

**Comment by pgkeller** [comment]
what does "its host machine is setup incorrectly" mean?

**Comment by mo-tenstorrent** [comment]
It is most likely the kernel_perf_paranoid level. 
https://askubuntu.com/questions/1400874/what-does-perf-paranoia-level-four-do

**Comment by pgkeller** [comment]
are you saying that that would explain why tracy results look odd or that could be root cause for the perf issues we are seeing?  (from a skim of the link, seems like it is a measuring thing not a perf thing).

**Comment by arikTT** [comment]
My understanding is that it is the difference in look, running as root showed the same look on WH and BH. Doesn't explain why some compile runs are taking longer

**Comment by mo-tenstorrent** [comment]
Sorry for the confusion caused. This is a case of more perf data (BH run) vs less perf data(WH run). All data presented is correct and in both cases profiling is not the root cause of the diff and in these time scales add no overhead.

**Comment by olofj** [comment]
So, is it a correct observation that the internal metal build flow has essentially implemented `make -j`, spinning up "infinite" parallel threads to build, vs managing it within the resource constraints of the system?

How is the compile launched? Is it manual launches of the compiler, or is it running a `make`? If it's running `make`, what are the arguments to it? Best practices when doing it from a shell is `make -j $(nproc)`, i.e. limiting number of parallel jobs to the number of processors in the system. I'd highly advice doing something similar to the way your compiles run.

**Comment by olofj** [comment]
Having `TT_METAL_THREADCOUNT` default to number of cpus/threads in the system would probably be a good start:

```
#include <iostream>
#include <sched.h>
#include <unistd.h>
#include <stdexcept>

int getNumberOfCPUs() {
    // Define a CPU set
    cpu_set_t cpuSet;
    // Clear the CPU set
    CPU_ZERO(&cpuSet);

    // Get the CPU affinity mask for the current process (pid = 0 means current process)
    if (sched_getaffinity(0, sizeof(cpuSet), &cpuSet) == -1) {
        throw std::runtime_error("Failed to get CPU affinity");
    }

    // Count the number of CPUs in the set
    int numCPUs = CPU_COUNT(&cpuSet);

    return numCPUs;
}
```

**Comment by abhullar-tt** [comment]
The default value for `TT_METAL_THREADCOUNT` is taken from `std::thread::hardware_concurrency()` so I don't think we are launching infinite num of threads

**Comment by arikTT** [comment]
I verified that `std::thread::hardware_concurrency()` returns the correct number of cores on the systems I tested on

**Comment by pgkeller** [comment]
root cause is BH systems were running on 1G eth while WH systems had 100G eth.  Fix is to use /localdev to build/run locally
