### ISSUE TITLE
Official debug tool to probe L1

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#11718]
Metal team has been using deprecated binary from syseng to probe L1 for debug but this isn't an officially supported path from syseng. 

Opening this issue so we can align on what we should be doing instead. 

FYI @pgkeller

**Comment by miacim** [comment]
@tt-vjovanovic, can you explain how the debuda library and debuda.py are set up and how they can be used to probe the L1?

**Comment by miacim** [comment]
The tt-metal repository now includes a script [install_debugger.sh](https://github.com/tenstorrent/tt-metal/blob/main/scripts/install_debugger.sh), which installs [TT-Lens](https://github.com/tenstorrent/tt-lens), a tool designed for debugging and L1 memory probing.

[TT-Lens Demo](https://tenstorrent.sharepoint.com/:v:/s/Software/EXKUSJPFVfZLhhaMn6RyJ38BSqZuiUIZfj1tN7hDkpyyww?e=TVrxkr&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifSwicGxheWJhY2tPcHRpb25zIjp7InN0YXJ0VGltZUluU2Vjb25kcyI6MC43fX0%3D) is available, providing a detailed walkthrough of how to set up and use the tool effectively.
