### ISSUE TITLE
[Bug Report] Mistral-7B demo on Wormhole n150/n300 runs with batch 8 but reported as batch 32

### ISSUE THREAD

**Issue by milank94** [tenstorrent/tt-metal#11710]
**Describe the bug**
Testing out the LLMs on a n150, the Mistral-7B model, only able to get it to run with a batch size of 8. Which looking through the code, is what it is set to, but the reporting table lists perf for batch 32. 

Not able to replicate the perf from the table: https://github.com/tenstorrent/tt-metal/tree/v0.51.0-rc28?tab=readme-ov-file#wormhole-wh-models as that requires batch 32 support.

**To Reproduce**
https://github.com/tenstorrent/tt-metal/blob/v0.51.0-rc28/models/demos/wormhole/mistral7b/demo/demo_with_prefill.py#L431 - set `batch_size=32`

**Expected behavior**
Should be able to reproduce: https://github.com/tenstorrent/tt-metal/tree/v0.51.0-rc28?tab=readme-ov-file#wormhole-wh-models

**Please complete the following environment information:**
- OS:  Ubuntu 20.04
- Version of software: v0.51.0-rc28

**Comment by sraizada-tt** [comment]
Yes, it is because default max_seq_len = 4k. 
To use batch=32, you can reduce the max_seq_len to 1k by setting:
```
model_args.max_batch_size = 32
model_args.max_seq_len = 1024
model_args.kv_seq_len = 1024
```

**Comment by mtairum** [comment]
> is this because the default max seq length=4K and we can only fit 8 users at that seq length?

Correct. Inside `models/demos/wormhole/mistral7b/tt/model_config.py` you can see the default values for these:

```
    # Parameters for our use
    max_batch_size = 8
    max_seq_len = 4096
    kv_seq_len = 4096
```

These can be changed accordingly (batch=32, max len = 1024). 
We can also provide the option to change these inside the main demo code if needed.

**Comment by milank94** [comment]
Thanks @mtairum @sraizada-tt I can communicate this with the customer. 

Having either some documentation or automatically adjusting this in the demo code could help future proof.

**Comment by uaydonat** [comment]
Three action items on us:

- I think we should set the default seq length to 1K because we advertise batch=32 on GH.
- This should be an explicit option when launching the demo
- The README should mention how to adjust seq length and what the limit is, and how it affects the num_users that can be fit.

**Comment by uaydonat** [comment]
While we change the default, we should continue testing the max seq length=4K in the CI.

**Comment by milank94** [comment]
Thanks for the heads up.

I'm testing out the change and unfortunately hitting an error:
```bash
self = FastOperation(python_fully_qualified_name='ttnn.to_device', function=<built-in method to_device of PyCapsule object at...function default_postprocess_golden_function_outputs at 0x7f0a9fdc2550>, is_cpp_operation=False, is_experimental=False)
function_args = (ttnn.Tensor([[[[ 0.00000,  0.00000,  ...,  0.00000,  0.00000],
               [ 0.00000,  0.00000,  ...,  0.00000,  0...128]), dtype=DataType::BFLOAT8_B, layout=Layout::TILE), <ttnn._ttnn.deprecated.device.Device object at 0x7f0a9c5d24f0>)
function_kwargs = {'memory_config': MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)}

    def __call__(self, *function_args, **function_kwargs):
>       return self.function(*function_args, **function_kwargs)
E       RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:141: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 142606336 B DRAM buffer across 12 banks, where each bank needs to store 11884224 B
```

I'm testing Mistral-7B from this version: https://github.com/tenstorrent/tt-metal/tree/v0.51.0-rc28/models/demos/wormhole/mistral7b

The code changes I made were to:

https://github.com/tenstorrent/tt-metal/blob/v0.51.0-rc28/models/demos/wormhole/mistral7b/tt/model_config.py#L27
```python
# Parameters for our use
max_batch_size = 32
max_seq_len = 1024
 kv_seq_len = 1024
```

and to:
https://github.com/tenstorrent/tt-metal/blob/v0.51.0-rc28/models/demos/wormhole/mistral7b/demo/demo_with_prefill.py#L431
```python
    return run_mistral_demo(
        user_input=input_prompts,
        batch_size=32,
        device=device,
        instruct_mode=instruct_weights,
        is_ci_env=is_ci_env,
        num_batches=num_batches,
        print_to_file=False,
    )
```

Any other changes that I need to make to enable batch 32?

**Comment by mtairum** [comment]
Hmm. 1k seqlen should still fit, right @sraizada-tt ?

Can you also try a length of 512?

**Comment by milank94** [comment]
Just tried it, same error but different memory requirements:

```bash
self = FastOperation(python_fully_qualified_name='ttnn.to_device', function=<built-in method to_device of PyCapsule object at...function default_postprocess_golden_function_outputs at 0x7f6cdd96e550>, is_cpp_operation=False, is_experimental=False)
function_args = (ttnn.Tensor([[-0.00488,  0.00391,  ...,  0.00195,  0.00488],
             [ 0.00000, -0.00586,  ...,  0.00049, -0.002...336]), dtype=DataType::BFLOAT4_B, layout=Layout::TILE), <ttnn._ttnn.deprecated.device.Device object at 0x7f6cda1132b0>)
function_kwargs = {'memory_config': MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)}

    def __call__(self, *function_args, **function_kwargs):
>       return self.function(*function_args, **function_kwargs)
E       RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:141: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 33030144 B DRAM buffer across 12 banks, where each bank needs to store 2752704 B
```

**Comment by milank94** [comment]
Naive question, but anything to do with any sort of caching or saved memory from previous runs?

I ran the batch 8 with 4096 seq len before that, could anything have been cached that would impact subsequent runs?

**Comment by mtairum** [comment]
> could anything have been cached that would impact subsequent runs?
No, the device is closed between runs.

We'll look into the issue 👍

**Comment by mtairum** [comment]
@milank94 Just had a quick look. Found the problem.

On model config can you also change `sliding_window` to 1024?

```
    sliding_window = 1024
    vocab_size = 32000

    # Parameters for our use
    max_batch_size = 32
    max_seq_len = 1024
    kv_seq_len = 1024
```

This passes for me.

I'm finishing off another PR. When that's done I'll update Mistral with support choice for batch of 32 and 1k seqlen, vs batch=8 / seqlen=4k

**Comment by mbahnasTT** [comment]
@milank94 shall we close this issue?

**Comment by mtairum** [comment]
I think this issue can be closed. 

We haven't started working on an update for the demo, but we have an issue to track it here https://github.com/tenstorrent/tt-metal/issues/11951

It just went a bit down on priority so don't expect it this week.
