### ISSUE TITLE
Runtime Error: Unable to permute bfloat8 tensor

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#11769]
**Describe the bug**
Unable to do permute operation for input which is in bfloat8_b dtype, Tile layout and device. Permute expects the tensor to be in bfloat16 or bfloat32.

**To Reproduce**
1. Run the following code snippet.
```
import ttnn
import pytest
import torch

@pytest.mark.parametrize("device_params", [{"l1_small_size": 24576}], indirect=True)
def test(device):
    input_a=torch.randn(1,160,32,32)
    tt_input=ttnn.from_torch(input_a,device=device,layout=ttnn.TILE_LAYOUT,dtype=ttnn.bfloat8_b)
    output=ttnn.permute(tt_input,(0,2,3,1))
```

**Expected behavior**
Permute operation should happen without any error.

**Screenshots**
```
E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_op.cpp:61: input_tensor.get_dtype() == DataType::BFLOAT16 || input_tensor.get_dtype() == DataType::FLOAT32
E       backtrace:
E        --- ttnn::operations::data_movement::Transpose::validate(std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&) const
```

**Please complete the following environment information:**
- OS:  Ubuntu 20.04
- Device: WH-n150

CC: @saichandax

**Comment by sjameelTT** [comment]
This will take a while to implement. Is it possible to typecast to bfloat16 and run in the meantime?

`import ttnn
import pytest
import torch

@pytest.mark.parametrize("device_params", [{"l1_small_size": 24576}], indirect=True)
def test(device):
    input_a=torch.randn(1,160,32,32)
    tt_input=ttnn.from_torch(input_a,device=device,layout=ttnn.TILE_LAYOUT,dtype=ttnn.bfloat8_b)
    tt_input=ttnn.typecast(tt_input,ttnn.bfloat16)
    output=ttnn.permute(tt_input,(0,2,3,1))`

**Comment by punithsekar** [comment]
Yes, We can typecast it.
But I notice the whole model PCC is dropping too much due to this.

I will try to reproduce the PCC drop by maxpool for bf8 and will add it here.

**Comment by sjameelTT** [comment]
Is the model PCC dropping because of the addition of the typecast operation? By unmaking the tiles and remaking them this could be an inherent bf8 issue.

**Comment by punithsekar** [comment]
Sorry, The above comment was for another issue.
