### ISSUE TITLE
need to run unit_test_fast_dispatch on ethernet cores in post commit

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#11763]
We currently don't have any coverage of FD from eth in post commit.
Running the fd tests w/ TT_METAL_DPRINT_ETH_CORES=all should provide decent coverage

**Comment by TT-billteng** [comment]
please add the relevant command to the right scripts, we don't own the tests

**Comment by pgkeller** [comment]
closing, looks like this is already running
