### ISSUE TITLE
Watcher PAUSE() Issue

### ISSUE THREAD

**Issue by N0Woan** [tenstorrent/tt-metal#11768]
After I followed [Watcher Guide](https://docs.tenstorrent.com/tt-metal/latest/tt-metalium/tools/watcher.html) and didn't disable any feature, I tried to: 
- Add `#include "debug/pause.h"` to tt_metal/programming_examples/matmul_common/kernels/compute/bmm.cpp​ 
- Run the tt_metal/build_metal.sh
- Run /home/namnguyen/tt-metal/build_Release/programming_examples/matmul_single_core 
I got **aborted (core dumped)** . I tried to figure out this issue and found that the `watcher_pause()` function in `pause.h` has problem because when I comment the body of the function, the program didn't get **aborted (core dumped)** anymore. 

Is there any problem with the code or I have installed the Watcher in the wrong way? How to fix it if the code is not the problem?  

<img width="273" alt="issue_pausing" src="https://github.com/user-attachments/assets/65908184-3cb3-4e1f-b189-5469741d96cf">

**Comment by tt-dma** [comment]
Thanks for catching this, there was a bug in the watcher code and I've just merged the fix. I was able to reproduce the issue and confirm the fix works on our end. Please let me know/re-open the issue if it persists for you!

**Comment by N0Woan** [comment]
Thank you, I have applied the fix and it works!
