### ISSUE TITLE
[MCW] Tensor Parallel (TP) implementation of Llama3.1_8b on n300

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#11807]
Implement TP implementation of whole model, taking reference from [Llama3.1_8b](https://github.com/tenstorrent/tt-metal/tree/main/models/demos/wormhole/llama31_8b)

- [ ]  Implement Whole Model using Tensor Parallelism.
- [ ]  Compare the performance of the model, with TP and without TP on n300.
- [ ]  Look for improvements if there is a scope to improve performance via TP.

**Comment by mtairum** [comment]
N300 supported now in main. Check PR https://github.com/tenstorrent/tt-metal/pull/13160 for more details
