### ISSUE TITLE
[MCW] Tensor Parallel (TP) implementation of RMSNorm sub-module of Llama3.1_8b on n300

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#11804]
Implement TP implementation of RMSNorm sub-module, taking reference from [Llama3.1_8b](https://github.com/tenstorrent/tt-metal/tree/main/models/demos/wormhole/llama31_8b)

- [x]  Test RMSNorm sub-module on n150, check perf results.
        - Tested RMS Norm submodule on n150, PCC = 0.99
        - Perf sheet: [n150_RMSNorm_perf.csv](https://github.com/user-attachments/files/16818661/n150_RMSNorm_perf.csv)
```
Op                   Time (us)
LayerNorm                64 ±     0
Tokens/s/user: 15727.23 (63.6 us latency)
```
- [x] Implement RMSNorm sub-module using Tensor Parallelism. _(Distributed RMSNorm is available in [Llama2_70B](https://github.com/tenstorrent/tt-metal/blob/530b64c502338bca28644b54071a197779977532/models/demos/t3000/llama2_70b/tt/llama_decoder_optimized.py#L227), please refer to it)_
       - Implemented and Tested RMS Norm submodule with Tensor Parallelism, PCC = 0.99
       - Branch: [harini/llama31_n300_tensorparallel](https://github.com/tenstorrent/tt-metal/compare/harini/llama31_n300_tensorparallel)
 
- [x]  Compare the performance of the sub-module, with TP and without TP on n300.
       - Without Tensor Parallelism:
       - Tested RMS Norm submodule on N300 without Tensor Parallelism, PCC = 0.99
       - Perf sheet: [n300_MLP_batch32_withoutTP_perf.csv](https://github.com/user-attachments/files/16818726/n300_MLP_batch32_withoutTP_perf.csv)
```
Op                   Time (us)
LayerNorm                64 ±     0
Tokens/s/user: 15698.09 (63.7 us latency)
```
- With Tensor Parallelism:
- Perf sheet: [n300_RMSNorm_TP_perf.csv](https://github.com/user-attachments/files/16818753/n300_RMSNorm_TP_perf.csv)
```
Op                   Time (us)
LayerNorm                35 ±     0
Tokens/s/user: 28643.45 (34.9 us latency)
```
- [ ]  Look for improvements if there is a scope to improve performance via TP.
        - Implementing distributed RMS Norm, to compare the token/s of distributed norm and usual rms norm.
        - Testing distributed RMS Norm is currently blocked due to shape mismatch error of inputs to ttnn.rms_norm_post_all_gather
        - Work of distributed RMS Norm updated to [harini/llama31_distributed_rmsnorm](https://github.com/tenstorrent/tt-metal/compare/harini/llama31_distributed_rmsnorm)

**Comment by saichandax** [comment]
Currrently blocked. Need further inputs for optimisation

**Comment by mtairum** [comment]
N300 supported now in main. Check PR https://github.com/tenstorrent/tt-metal/pull/13160 for more details
