### ISSUE TITLE
[MCW] Refactor Segformer_b0 to use new Conv API on n150

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#11817]
Taking reference from #8859, implement the model with new Conv API on n150.

**Comment by punithsekar** [comment]
This is the current [commit](https://github.com/tenstorrent/tt-metal/compare/main...punith/segformer_with_new_conv_api) for segformer on n150.

A conv which was working on yesterday [main](https://github.com/tenstorrent/tt-metal/commit/e6f4c7023b882a46e0ad38bf28cdf9a9d78bb7de) is not working on today's main.

I have updated on this in #8868  issue.
Currently, Working on old main.

**Comment by saichandax** [comment]
#8868 is closed.
Need to test it in n150

**Comment by saichandax** [comment]
Bringup of segformer_b0 on n150 with new ConvAPI is complete. Hence closing this task.
Optimisation is tracked on #11880
