### ISSUE TITLE
[MCW] Bringup Segformer on e150 (with new Conv API)

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#11818]
Taking reference from implementation executed on WH (n150), to run on GS (e150).

**Comment by punithsekar** [comment]
[Commit](https://github.com/tenstorrent/tt-metal/compare/main...punith/segformer_on_gs) for segformer in Gs.

Perf sheet for the same: 

[segformer_gs_versionmain.csv](https://github.com/user-attachments/files/16793019/segformer_gs_versionmain.csv)
