### ISSUE TITLE
 make dispatcher track just the last block rather than N blocks

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#11832]
Today dispatcher tracks blocks of pages to free back to prefetcher
The buffer is broken into N blocks, where N is currently 4
Bookkeeping is done to track when each block can be freed
Generally, when dispatcher is done w/ block N it can free block N-1.  Occasionally dispatcher runs further ahead and can only free block N-2
This bookkeeping is non-trivial, and most of the dispatcher code is riscv bound

This issue is to consider/evaluate:
 - Only track the most recent block
 - When dispatcher is done w/ block N, stall until block N-1 can be freed, then track block N for the next iteration
 
Biggest concern is that w/ small buffer sizes on eth cores this could be a loss.  On the other hand, w/ small block sizes on eth cores holding onto say 1/2 the buffer could be a net loss as well (ie, may be better stalling and freeing)

This may be best evaluated once #11830 and mux/demux paths aren't restricted to 2^N sized buffers

**Comment by pgkeller** [comment]
@tt-aho is this done?

**Comment by tt-aho** [comment]
Yes, closing.
