### ISSUE TITLE
Add E75 Tests to Post Commit

### ISSUE THREAD

**Issue by tt-asaigal** [tenstorrent/tt-metal#11879]
E75 is a product that is currently in use externally, and we have no testing for it. I'm not sure if the Metal Team has access to any E75 machines through IRD. This leads to issues like [these](https://github.com/tenstorrent/tt-metal/issues/11877), where basic failures go unnoticed for days and lead to a negative customer experience.

We should have a few basic tests running on this configuration to verify that a user can at least start a device and run a few kernels correctly.

@tt-rkim, assigning to you for now, please feel free to delegate as needed. We can help out with creating a test suite.

**Comment by tt-rkim** [comment]
#3484 We've closed E75 CI issue. We don't support it, and we do not list it as a possible card you can use in our installation instructions.

I'll leave this open for more discussion, but I'm inclined to treat this as lowest possible priority, and likely will not do as we transition to newer generations of chips.

Unless of course, someone has bandwidth to bring up the E75 machines for us and integrate them into CI and lead the effort to fix / disable the broken tests.

cc: @TT-billteng

**Comment by tt-rkim** [comment]
Otherwise, I'm going to close this by end of week.
