### ISSUE TITLE
[MCW] Systematic Perf Optimisation/Utilisation analysis of every Conv/MM

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#11880]
@punithsekar , Please update this ticket description (not in comment), with brief summary of what's done and add what is pending.

**Comment by punithsekar** [comment]
Please find the [commit](https://github.com/tenstorrent/tt-metal/compare/main...punith/segformer_linear_with_different_grid) for a Linear configuration with different core_grids. 

The perf sheets are: 

[segformer_configuration_grid8x2.csv](https://github.com/user-attachments/files/16751603/segformer_configuration_grid8x2.csv)
[segformer_configuration_grid8x4.csv](https://github.com/user-attachments/files/16751601/segformer_configuration_grid8x4.csv)
[segformer_configuration_grid8x8.csv](https://github.com/user-attachments/files/16751602/segformer_configuration_grid8x8.csv)


The graph for the utilization percentage for different core_grid is:

![Image](https://github.com/user-attachments/assets/5014f114-7b54-4df1-9952-b02aa81cb23a)

**Comment by punithsekar** [comment]
The MM in whole pipeline is sharded. It's available in branch [punith/segformer_on_gs](https://github.com/tenstorrent/tt-metal/compare/main...punith/segformer_on_gs).
I compared between Gs and Wh(Kept torch conv for convs which all GS is making issue) for the version which is on the [branch](https://github.com/tenstorrent/tt-metal/compare/main...punith/segformer_on_gs) , version 2 and version 3 of your reference.
I see the average utilization of all three versions are same for MM, Whereas the version available in the [commit](https://github.com/tenstorrent/tt-metal/compare/main...punith/segformer_on_gs) has better performance.

I was also looking on conv optimization and will try to improve the utilization of conv and MM further with different configs

Attaching the perf sheet of MM for model which is in the branch,



[segformer_gs_versionmain_MM.csv](https://github.com/user-attachments/files/16764077/segformer_gs_versionmain_MM.csv)
[segformer_wh_versionmain_MM.csv](https://github.com/user-attachments/files/16764078/segformer_wh_versionmain_MM.csv)

**Comment by punithsekar** [comment]
Latest perf sheet of segformer_model:
[segformer_1.csv](https://github.com/user-attachments/files/16819407/segformer_1.csv)

**Comment by saichandax** [comment]
On Hold currently, as the optimisations are complete and shared the observations accordingly in the parent ticket, with latest perfs and branch.
