### ISSUE TITLE
`test_resnet_with_module_cache` fails when writing to `/home/ubuntu/.cache/torch/hub`

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#11917]
It appears that the folder is created by `root` user somewhere else. We need to track which other test is writing to this as `root` user

**Comment by eyonland** [comment]
The error could be occurring if we have a job that is running as sudo.   Basically if a docker container is running as a root user by default (related:  https://github.com/tenstorrent/tt-metal/blob/0d8d07a058b867fdfba9ec001487d56fff3673ba/.github/actions/docker-run/action.yml#L65-L66) then torch.hub.load() will likely cause this issue.

**Comment by TT-billteng** [comment]
test was deleted [here](https://github.com/tenstorrent/tt-metal/commit/22c123c757af492f5b4072396a4ac34effe5ddf3#diff-0c25591b36c7548edd7c5894fda53eb8c0b6af117f1f7c8c5fdcf20b5d0ae6e8) during what appears to be a refactor
