### ISSUE TITLE
[Master issue] Blackhole Infrastructure List

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#11910]
Master list for known/possibly known problems and future work
Infra
- [ ] #11919
- [ ] Enable other tests on BH CI
- [ ] #12483
- [ ] #12502
- [ ] #12188

Issues (list issues here)
- [ ]

**Comment by TT-billteng** [comment]
closing in favor of https://github.com/tenstorrent/tt-metal/milestone/11
