### ISSUE TITLE
[Bug Report] ttnn.remainder unary low PCC

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#11939]
**Describe the bug**
ttnn.remainder operation fails with low PCC when running with single input tensor and a scalar.

**To Reproduce**
1. Checkout branch amalbasaTT/remainder_unary-unit-test (soon to be merged to main)
2. Run unit test `test_unary_remainder.py ` using command:

```
pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_unary_remainder.py
```

**Expected behavior**
Test cases are created from the arguments generated for sweep tests. There are five test cases and all of them fail with an assertion error.

**Running sweeps**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps and check the results. To do this you should:

1. Run non working sweep by runing:
```
pytest tests/ttnn/python_api_testing/sweep_tests/run_sweep_test.py --input-path tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/ttnn_remainder_unary_test.yaml --input-method cli --cli-input result_remainder_unary
```
2. After the run is completed all test sweeps results should be available inside specified output directory.

**Comment by VirdhatchaniKN** [comment]
Hi @amalbasaTT , The test passes from main branch. Can we have a check on this and close the issue?

**Comment by amalbasaTT** [comment]
> Hi @amalbasaTT , The test passes from main branch. Can we have a check on this and close the issue?
It passes now, i will close an issue. Thanks!
