### ISSUE TITLE
Support for Conv2D with dims < 32 and dims % 32 != 0

### ISSUE THREAD

**Issue by sankarmanoj-tt** [tenstorrent/tt-metal#11955]
**Describe the bug**
No test cases for Conv2D where parameters like input_channels, output_channels are less than 32 or non-multiples of 32.
This leads to bugs in those scenarios.  

**To  Do**
1. Implement comprehensive test cases for these scenarios.
2. Fix all bugs related to this. 

**Expected behavior**
Conv2D works for any arbitrary dimension.

**Additional context**
#10110 
#10109

**Comment by esmalTT** [comment]
@sankarmanoj-tt We need this for UNet Shallow.  Our final layer is a pointwise convolution with some activation `(B*H*W, 16[32])` and weight `(1, 16, 1, 1)`, which crashes because the weight gets padded to a tile and then cannot be matmul'd with the activation because it's width is 16.
