### ISSUE TITLE
GH Workflow telemetry

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#12052]
Could be interesting to try this github action workflow.
https://github.com/catchpoint/workflow-telemetry-action

It should spit out runner telemetry over our runs and give us better insight on VM/BM utilization

**Comment by ttmchiou** [comment]
fyi @ayerofieiev-tt @tt-rkim @TT-billteng

**Comment by ttmchiou** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/10607719117
https://github.com/tenstorrent/tt-metal/actions/runs/10607755986

Example runs:
scroll down in the summary section

**Comment by tt-rkim** [comment]
This is great - it would output a LOT for smth like post commit, but I'm sure devs don't read too much into it unless they need to. Love it

**Comment by TT-billteng** [comment]
this is great! can we just add it to `prepare-metal-run` composite action and call it a day?
