### ISSUE TITLE
 [MCW] Refactor swin_s to use new Conv API on n150

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#12063]
Taking reference from [harini/ttnn_swin_s](https://github.com/tenstorrent/tt-metal/compare/main...harini/ttnn_swin_s), implement the model with new Conv API on n150.

Use preprocess_model_parameters instead of preprocess_model to load parameters.

**Comment by punithsekar** [comment]
The refactoring the swin_s model is in progress, [commit](https://github.com/tenstorrent/tt-metal/compare/main...punith/ttnn_swin_s_on_wh)


Completed mlp and patch_merging sub_module.[torch slice is used #8920 ]
Currently, working on ShiftedWindowAttention sub_module. The ShiftedWindowAttention sub_module which is shared in the reference commit [harini/ttnn_swin_s](https://github.com/tenstorrent/tt-metal/compare/main...harini/ttnn_swin_s) is not working in current main. Checking on it.

**Comment by punithsekar** [comment]
Swin_s whole model refactor is still in progress, [Commit](https://github.com/tenstorrent/tt-metal/compare/main...punith/ttnn_swin_s_on_wh).
I am attaching the perf sheet of one of the test_case of transformer block . Pcc of transformer block sub_module is > 0.99.
Many torch ops have been used like roll, 6D permute ,6D rehsape and some other places.
I am checking if we can eliminate torch ops wherever possible.
Closed a issue : [8926](https://github.com/tenstorrent/tt-metal/issues/8926) , Will close the issue [9011](https://github.com/tenstorrent/tt-metal/issues/9011) after checking.
Once the whole pipeline up after refactoring will concentrate on optimization.

**Comment by punithsekar** [comment]
Whole model is refactored, [commit](https://github.com/tenstorrent/tt-metal/compare/main...punith/ttnn_swin_s_on_wh). Whole model pcc>0.99,bs=1.
Some operations are in torch for those i have created issue maximum. Newly created issues: [12157](https://github.com/tenstorrent/tt-metal/issues/12157), [12154](https://github.com/tenstorrent/tt-metal/issues/12154), [12153](https://github.com/tenstorrent/tt-metal/issues/12153).
Closed issue : [8926](https://github.com/tenstorrent/tt-metal/issues/8926).
Attaching the perf sheet of swin_s_transformer_module for bs=1, for bs=8 getting OOM in conv.
ToDo: Optimize the model

[Uploading swin_s_transformer.csv…]()

**Comment by saichandax** [comment]
Closing this task, as the task to port the model to new Conv API is complete. Optimisation of the model is tracked on #12081
