### ISSUE TITLE
Need support for AdaptiveAvgPool2d

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#12158]
**Describe the bug**
Need support for AdaptiveAvgPool2d.

**Additional context**
Fallback_ops AdaptiveAvgPool2d is available.

To recreate the issue run the command:
`tests/ttnn/unit_tests/operations/test_avg_pool2d.py` in [commit](https://github.com/tenstorrent/tt-metal/compare/main...sabira/avg_pool2d_test) 

For input shape [1, 512, 7, 7] , Expected shape is [1, 512, 7, 7]
with the ttnn.global_avg_pool2d, the output shape is [1,512, 1, 1]
Need support for ttnn AdaptiveAvgPool2d or it expect ttnn global avg pool to return same shape as input

**Comment by punithsekar** [comment]
fyi @saichandax

**Comment by saichandax** [comment]
Not needed as of now in the VGG. Can re-open when needed.
