### ISSUE TITLE
MatmulMultiCoreMultiDRAMIn0MCastIn1MCast ND hanging on BH

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#12187]
https://github.com/tenstorrent/tt-metal/issues/11623 has been tracking ND hangs on BH CI. 

Ran for small number of iterations locally on IRD machines without seeing hang but increasing test iterations was able to reproduce the hang on IRD (I used yyz-bh-26 and saw hang after ~20 iterations)

Reducing the sub-block dimensions as (merged to main in https://github.com/tenstorrent/tt-metal/pull/12186) enables test to run for 1000 iterations (on yyz-bh-26). 

To run test with workaround: 
```
TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=CommonFixture.MatmulMultiCoreMultiDRAMIn0MCastIn1MCast --gtest_repeat=<N>
```

Without workaorund:
```
TT_METAL_DISABLE_BH_ND_WORKAROUND=1 TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=CommonFixture.MatmulMultiCoreMultiDRAMIn0MCastIn1MCast --gtest_repeat=<N>
```

**Comment by abhullar-tt** [comment]
Usually the hang is seen on a single core with a writer kernel being stuck waiting on data to be populated in its CB

Ran the test without the workaround to reduce subblocks of matmul after reducing the aiclk to 400 MHz (from 800 MHz using syseng script to set plls) and now all cores are hanging in the same spot. This points to the bug not being didt related

**Comment by bbradelTT** [comment]
> Usually the hang is seen on a single core with a writer kernel being stuck waiting on data to be populated in its CB
> 
> Ran the test without the workaround to reduce subblocks of matmul after reducing the aiclk to 400 MHz (from 800 MHz using syseng script to set plls) and now all cores are hanging in the same spot. This points to the bug not being didt related

@yugaoTT could you please take a look and see if there's something that is handling non-1 parameters incorrectly?

**Comment by bbradelTT** [comment]
There's a good chance this is related to https://github.com/tenstorrent/tt-metal/issues/12220 and the problematic change occurred between Aug. 21st 2024 and Sep. 4th 2024.

**Comment by bbradelTT** [comment]
This is due to https://github.com/tenstorrent/tt-metal/issues/11519 PR: https://github.com/tenstorrent/tt-metal/pull/11520

**Comment by abhullar-tt** [comment]
This runs 10k iterations on fast dispatch without the workaround, issue looks to be related to slow dispatch only, removing didt suspected label

**Comment by yugaoTT** [comment]
on BH cmd_buffer is known to have issues, need to turn on cmd_buffer_fifo. 
Instead of using `noc_cmd_buf_ready` and `cmd_buffer` for sending out mcast requests (as well as other read/write requests), 
use `cmd_buffer_fifo` and `CMD_BUF_AVAIL`

**Comment by bbradelTT** [comment]
@abhullar-tt Is there an issue tracking to fix the problems with the BH cmd_buffer or will they remain and cmd_buffer_fifo will always need to be on?

**Comment by abhullar-tt** [comment]
> @abhullar-tt Is there an issue tracking to fix the problems with the BH cmd_buffer or will they remain and cmd_buffer_fifo will always need to be on?

It is tracked in #5174 to verify that cmd buffers are functional on new BH hw
