### ISSUE TITLE
[Blackhole] Fix dest print for dest remap

### ISSUE THREAD

**Issue by rtawfik01** [tenstorrent/tt-metal#12234]
Currently, if `pack_untilize` function is used in Blackhole, these bits would have to be enabled:
```
    DEST_ACCESS_CFG_remap_addrs
    DEST_ACCESS_CFG_swizzle_32b
```

Once they are enabled, these bits cause the destination register to have a different remapping. This remapping does not affect LLKs or software use cases, but it does affect the debug prints from the destination register here:
`tt_metal/hw/inc/debug/dprint_tensix.h`

There should be a flag added to `dprint_tensix_dest_reg` to allow it to print the different remapping that occurs to be able to debug pack_untilize or any other feature in the future that uses the above bits.

@ttmtrajkovic @ncvetkovicTT @nvelickovicTT

**Comment by abhullar-tt** [comment]
FYI @tt-dma

**Comment by nvelickovicTT** [comment]
@Marco Merlini should have a script that does this, which could be a starting point.

**Comment by TT-Marco** [comment]
Just pasting what I sent over slack for posterity. I haven't double checked everything in here, but it should give an idea:

```
When you enable the swizzling mode, 32-bit data is stored in a different order

Instead of:
Dest    || Physical 
address || location
-------------------
0       || 0
4       || 4
8       || 8
12      || 12
16      || 16
20      || 20
24      || 24
28      || 28
4n+m    || 4n+m  (0 <= m <= 3)
o+32    || o+32  (0 <= o <= 31)

You have:
Dest    || Physical 
address || location, call this P(a)
-------------------
0       || 0
4       || 8
8       || 4
12      || 12
16      || 24
20      || 16
24      || 28
28      || 20
4n+m    || P(4n)+m  (0 <= m <= 3)
o+32    || P(o)+32  (0 <= o <= 31)

So for example, for dest address 53,
53/32 = 1 R 21
21    = 20 + 1
P(20) = 16
P(21) = P(20) + 1 = 17
P(53) = P(21) + 1*32 = 49

So that's swizzling

Remapping simply means to rotate bits [3:1] of the address to the right, and this is performed before swizzling. So,
R(53) = R(0b110101) = 0b110011 = 51
When they are both turned on, address A is stored in P(R(A))
Well, I hope what I've written here is accurate!!!
```

**Comment by TT-Marco** [comment]
More details because I just can't help myself: the address on the left-hand side is the _row_ address. When you are using a RISC to read dest over the memory, keep in mind that the LSBs of the RISC's address actually select the column, and the MSBs are the dest row address.

Swizzling does not apply in 32-bit mode, but remapping does. And of course, the RISC-dest bus has to be used correctly; see `ckernel_dest.h` for some helper functions and `ctest_risc_dest.cc` in the Tensix repo for an example

**Comment by miacim** [comment]
I cannot repro the issue. @nvelickovicTT, I will reassign issue back to you to find/create test that is exposing problem.

I had a chat with @rtawfik01, and I tried different tests. The only test with suspicious behavior was test_maxpool2d.py. I spent time debugging this and comparing the results between blackhole and wormhole_b0. The numbers in the destination (dest) are correct and match those on wormhole. However, there is some additional garbage in dest that is not zero and this should be investigated by llk team. Also on blackhole, dest output is printed 98 times, whereas on wormhole_b0, dest output is printed 196 times with the same code. First row on blackhole is exactly the same as on wormhole b0 for first 98 prints. So this test is not exposing the issue.
 
I was running following command 
```
TT_METAL_DPRINT_CORES=(0,0) pytest "tests/ttnn/unit_tests/operations/test_maxpool2d.py::test_run_max_pool[dtype=DataType.BFLOAT16-dilation=(1, 1)-stride=(2, 2)-padding=(0, 0)-kernel_size=(2, 2)-act_shape=[4, 64, 112, 112]-device_params={'l1_small_size': 24576}]"
```
and changed file ```ttnn/cpp/ttnn/operations/pool/maxpool/device/kernels/compute/max_pool_multi_core.cpp``` 
```cpp
  for (uint32_t c_i = 0; c_i < in_ntiles_c / in_nblocks_c; ++c_i) {
      reduce_tile_math(c_i,  num_faces_in_tile /* reduce 1 or 2 faces */);
  }
+dprint_tensix_dest_reg<true>(0);
```

**Comment by miacim** [comment]
per discussion with @ttmtrajkovic, moving issue back on me to work on unit test
