### ISSUE TITLE
Fix and upgrade standalone Python wheel test, package and release, and any other related wheel-dependent workflows to work with new `TT_FROM_PRECOMPILED`

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#12273]
Should probably have options in workflow dispatch and pass it into `eager-package.main`.

Related to https://github.com/tenstorrent/tt-metal/issues/12122

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by tt-rkim** [comment]
This work is blocked until docker is fixed again.

**Comment by tt-rkim** [comment]
Anyway, we had an issue here anyway.

Looks like the `build-wheel` job of `eager-package-main` when called from another workflow doesn't seem to listen to the `always()` trick to continue even if a dependent job didn't run.

The `${{ always() }}` trick may work since I didn't have the wrapper in last run.

**Comment by tt-rkim** [comment]
cc: @dimitri-tenstorrent btw, some pipelines like "package and release" broke because of the `from_compiled` changes. I have some work on branch to try to fix this, but it's not complete yet. there are some easy outs we could do to unblock people work on said pipelines like yourself

**Comment by dimitri-tenstorrent** [comment]
I am not blocked on that at the moment for the docs work. 

Let me know if you need help especially if I broke it :)

**Comment by tt-rkim** [comment]
@ayerofieiev-tt @skhorasganiTT @dimitri-tenstorrent 
All wheel-related workflows should be fixed now and I've kicked off another package and release run: https://github.com/tenstorrent/tt-metal/actions/runs/10817118236
