### ISSUE TITLE
TGG CI runners not displaying `tt-smi` info

### ISSUE THREAD

**Issue by sagarwalTT** [tenstorrent/tt-metal#12319]
Runners `g06cs01` and `g06cs02`, which are both TGG machines, don't seem to be printing out `tt-smi` info when a workflow on either of these machines is run. Workflows on other machines display `tt-smi` info under the header `Set up runner`, however this header isn't being shown on the TGG CI runners.

**Comment by tt-rkim** [comment]
@ttmchiou do they reset scripts not include this info?

**Comment by TT-billteng** [comment]
> @ttmchiou do they reset scripts not include this info?

doesn't seem like it when I looked

**Comment by ttmchiou** [comment]
some machines didn't have CI reset script installed or required reboot so fixed those in the machines.
Hugepage installation also required.

Used tt-system-tools with override /opt/tenstorrent/bin/hugepage-override.txt (set to 64)
to install hugepages

g06cs01 potential issue, filing ticket for investigation
https://github.com/tenstorrent/tt-metal/actions/runs/10798097592/job/29963069828
g06cs02  fixed and operational in CI
https://github.com/tenstorrent/tt-metal/actions/runs/10795235556/job/29962840167
