### ISSUE TITLE
Add `libsndfile` as a test dependency via CPM that the Python runtime can link to

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#12412]
Lots of nightly pipelines are failing on whisper tests which require `libsndfile` as a system dependency.

On CI, we should be able to get away with declaring `libsndfile` via CPM and directing its install to `build/lib`. https://github.com/libsndfile/libsndfile

We may want to gate creating this library behind a flag that is default on, but turn off during wheel builds. This may affect running the test with an installation via wheel if we don't package it, but that should be a pretty rare use case.

@TT-billteng says create a new `cmake/test_dependencies.cmake`

**Comment by vtangTT** [comment]
Where does it need to be linked? Or are we only using the headers?

**Comment by tt-rkim** [comment]
We're not linking to it nor using the headers.

One of the `whisper` tests in `ttnn` uses it, which means there's some third party python package that tries linking to it at runtime.

**Comment by vtangTT** [comment]
How would I validate this change?

**Comment by tt-rkim** [comment]
I believe you can target certain VMs which don't have `libsndfile` as a dependency installed, such as `tt-metal-ci-vm-105`: https://github.com/tenstorrent/tt-metal/actions/runs/10856672561/job/30132067051

You could probably a custom dispatch on your branch onto that VM with something like `pytest tests/ttnn/integration_tests/whisper/`. On main, that should fail with that error message (hopefully... haven't checked myself lolooollololol)

Let us know if you need help with labels. I'd probably just put `tt-metal-ci-vm-105` onto it as a label.

**Comment by vtangTT** [comment]
As discovered by @tt-aho , pip version < 20.3 will not pick up `soundfile` with its own packaged `libsndfile`

Fixed by @TT-billteng through https://github.com/tenstorrent/tt-metal/pull/12673, where pinning pip version to `21.2.4` picks up the version with packaged lib. 

Validated by observing whisper tests pass with pip @ `21.2.4` and failing with missing lib with pip @ the old `20.1.1` version
