### ISSUE TITLE
Unable to resolve the shard spec value error at nlp_create_qkv_heads_decode API

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#12428]
**Describe the bug**
On implementing Tensor Parallel Attention submodule, replaced `nlp_create_qkv_heads` API with `nlp_create_qkv_heads_decode` API for creating qkv heads in multi-device. Facing the following error at `nlp_create_qkv_heads_decode` API.
`RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_decode/device/nlp_create_qkv_heads_decode_device_operation.cpp:32: input_tensor.shard_spec().value().shape[1] == (this->num_q_heads + this->num_kv_heads * 2) * this->head_dim || input_tensor.shard_spec().value().shape[1] == 32`
Unable to change the shard_spec value of input tensor, and couldn't resolve the issue.

**To Reproduce**
1. Checkout to the branch: [harini/llama31_attention](https://github.com/tenstorrent/tt-metal/compare/harini/llama31_attention)
2. Run the command: `pytest models/demos/wormhole/llama31_8b/tests/test_llama_attention.py`

**Expected behavior**
Expected to resolve the issue.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: WH n300

**Comment by saichandax** [comment]
Closing this issue, as this is no more relevant to Llama3 on n300.
The implementation is already on main: #13160
