### ISSUE TITLE
Shape mismatch at rms_norm_post_all_gather

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#12427]
**Describe the bug**
While implementing Tensor Parallel TT Distributed RMS Norm Submodule, facing shape mismatch error at ttnn.rms_norm_post_all_gather API.
`E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/normalization/layernorm_distributed/device/layernorm_post_all_gather_op.cpp:42: stats.get_legacy_shape()[2] == a.get_legacy_shape()[2]`
Expected to have same shape for input and tt_stats. But, using all_gather API for tt_stats changes the shape of tt-stats. Hence the shape of input and tt_stats are not same, unable to find a way to get same shape.

**Note:** After rebasing latest main to the branch, facing the following error at rms_norm_pre_all_gather API:
`E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/tensor/types.cpp:172: normalized_index >= 0 and normalized_index < rank
E       info:
E       Index is out of bounds for the rank, should be between 0 and 2 however is 3`

**To Reproduce**
1. Checkout to branch: [harini/llama31_distributed_rmsnorm](https://github.com/tenstorrent/tt-metal/compare/harini/llama31_distributed_rmsnorm)
2. Run the command: `pytest models/demos/wormhole/llama31_8b/tests/test_llama_distributed_rms_norm.py`

**Expected behavior**
Expected to have same shape of input and tt_stats to proceed with implementation of module.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: WH n300

**Comment by saichandax** [comment]
Closing this issue as this is no more relevant to llama3 on n300
Llama3.1_8b is on main: #13160
