### ISSUE TITLE
ttnn.maxpool2d fails in VGG model

### ISSUE THREAD

**Issue by vigneshkeerthivasanx** [tenstorrent/tt-metal#12443]
**Describe the bug**
ttnn.maxpool2d fails to produce result for some test cases in e150 and n300 while working on VGG model.

**To Reproduce**

pick the test from the [commit](https://github.com/tenstorrent/tt-metal/compare/main...vignesh/ttnn_maxpool2d_unit_test_vgg)
Run pytest <path to file>

**Expected behavior**
As the above shared configuration works in pytorch, it is expected to run in ttnn aswell.

**Error**
1. For input shape [1, 256, 56, 56],

```
E       RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:141: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 1032763878400 B L1 buffer across 50 banks, where each bank needs to store 20655277568 B
```

2. For input shape [1, 512, 28, 28]

```
E       RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:141: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 4398027153408 B L1 buffer across 56 banks, where each bank needs to store 78536199168 B
```
2. For input shape [1, 512, 14, 14]
```
LOW PCC issue
PCC = 0.8859652206760608
```

**Comment by mywoodstock** [comment]
@vigneshkeerthivasanx The OOM error bug has been fixed in `main` (today), please rebase and try those two tests again, they pass for me.
Im now looking into the PCC error test case.

**Comment by mywoodstock** [comment]
The remaining PCC error is due to a kernel limitation in the width dimension. Opening this feature issue to support wide cases: #12544 . An update should be ready by tomorrow.

**Comment by mywoodstock** [comment]
@vigneshkeerthivasanx The support for wide channels has been merged to `main`. These tests all pass now.

**Comment by vigneshkeerthivasanx** [comment]
@mywoodstock All tests are passing in the VGG model with good PCC.
Thanks.

**Comment by saichandax** [comment]
Closing this issue, as it is resolved.
Thanks, @mywoodstock .
