### ISSUE TITLE
Add a barrier op that tries to terminate as close to the same time on each chip as possible

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#12516]
From parent issue:

The purpose of this issue is to implement an op that acts as a barrier within a performance profiling trace run. The ops should be written to complete on every chip at as close a time as possible so that there is minimal start skew across chips for the sequence of ops that follow. With high skew in starting time across chips, it is very difficult to reason about core performance issues in a handful of CCL ops.

- [ ] Port existing ring latency microbenchmark to be exposed as a standalone op
  - Don't enable with EDM yet
  - benchmark path: `tests/tt_metal/tt_metal/perf_microbenchmark/ethernet/test_ethernet_hop_latencies_no_edm.cpp`
- [ ] Update implementation to connect to EDM
- [ ] Optimize implementation to minimize barrier time

# Chip Start Skew Issue
With multi-chip alignment on profiler, we see quite massive skew between devices (atleast 17us). Is this within the anticipated vairation?

![image](https://github.com/user-attachments/assets/b4d091cb-a866-462b-a973-78012e859dd7)

When kicking off trace we see upwards of 55us delta between earliest and latest launch. This seems to loosely carry forth through future invocations of the eriscs (likely affecting reported numbers):

![image](https://github.com/user-attachments/assets/63ca79bf-2e98-4c84-842e-0d1f6e13f50d)

Once we get into the middle of the trace, we are looking at around a 12-14us start time skew between erisc kernels on different chips

![image](https://github.com/user-attachments/assets/4e98e89c-e370-4741-b19c-1331f1c91277)

**Comment by jvegaTT** [comment]
Barrier Op has been created and was pushed to the main branch
