### ISSUE TITLE
Bad PCCs in matmul.full.matmul_default_block_sharded n_size_32 sweeps

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-metal#12529]
After https://github.com/tenstorrent/tt-metal/pull/11520, the matmul.full.matmul_default_block_sharded n_size_32 sweeps stopped working properly.

Most of them hung. That was fixed as part of https://github.com/tenstorrent/tt-metal/issues/12220 with https://github.com/tenstorrent/tt-metal/pull/12462 that updates the matmul reader to not mcast when no destinations.

After that, there are a lot of PCC errors:
![image](https://github.com/user-attachments/assets/a2854236-2774-460a-908a-9c3e315dce89)

Repro steps should be:
```
python3 tests/sweep_framework/parameter_generator.py --module-name matmul.full.matmul_default_block_sharded # if needed
python tests/sweep_framework/runner.py --module-name matmul.full.matmul_default_block_sharded --vector-id ttVS4pEBwvAQT7Jm2dzu 
```

**Comment by bbradelTT** [comment]
Note: the vector ids have changed because of a code update. Therefore the vector ids in the screen shot can no longer be used.

**Comment by bbradelTT** [comment]
It turns out that what was done in

```
                            // multicast to every core in receiver grid
                            noc_async_write_multicast_loopback_src(
                                    local_read_addr,
                                    in0_multicast_data_addr,
                                    in0_block_size_bytes,
                                    in0_mcast_num_cores,
                                    false,
                                    false);
                        }
```
needs to happen even when in0_mcast_num_cores is 1

Therefore the change in https://github.com/tenstorrent/tt-metal/pull/12462 needs to be undone and whatever is causing the hang needs to be identified.

**Comment by TT-BrianLiu** [comment]
This fixes it: https://github.com/tenstorrent/tt-metal/pull/12796
We just need to use `noc_async_write` instead of `noc_async_write_multicast_loopback_src` (it hangs with linking set to True) for local CB copying. 

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/77707ad4-7eec-4173-991c-c781948b3e95">

**Comment by TT-BrianLiu** [comment]
Bad PCC was because we were using garbage data if we don't do the copy at all.
