### ISSUE TITLE
WH T3K - Hang Running FF1 and Sharded WL 

### ISSUE THREAD

**Issue by tcolacoTT** [tenstorrent/tt-metal#12530]
Branch: [ppopovic/rebased_didt_tests](https://github.com/tenstorrent/tt-metal/tree/ppopovic/rebased_didt_tests)

Testing with latest experimental FW 80.10.4.0

host: `yyz-debug-sjc-t3004`
Seeing Hang occur consistently on PCIe Device 2, ETH Coordinate (2,1)

Failure observed with following two configs:
Natural Clock/Voltage: 
WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/experimental/falcon_7b/tests/test_reproduce_hang_matmul.py -k "test_reproduce_matmul_2d_hang and ff1-hang and 8chips" 

Fixed 650AICLK/ 0.85V: WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest tests/didt/test_sharded_ff1.py -k "test_reproduce_matmul_2d_hang and 8chips" 

To fix clock and voltage :
ttp force-setup-plls --args ai=650 --mobo
ttp force-core-voltage --args voltage=0.85 --mobo

At failing point have seen:
- Mix of PCIe being accessible or down to the failing device
  - When PCIe was alive confirmed ARC heartbeat alive and moving forward over PCIe
  - When PCIe down connected JTAG to confirm same state of ARC
- No Thermal trips occurring, ARC alive

**Comment by ttmtrajkovic** [comment]
After diagnosing PGOOD problems and reworking boards, this is no longer happening.
