### ISSUE TITLE
ttnn.Conv1d with bias fails with "Index is out of bounds for the rank"  [GS] [WH]

### ISSUE THREAD

**Issue by kkeerthana0573** [tenstorrent/tt-metal#12557]
**Describe the bug**
ttnn.conv1d unit test cases fail with `Index is out of bounds for the rank, should be between 0 and 2 however is 3` when bias is True. 

On GS and WH(n300):
```
E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/tensor/types.cpp:172: normalized_index >= 0 and normalized_index < rank
E       info:
E       Index is out of bounds for the rank, should be between 0 and 2 however is 3
```

**To Reproduce**
1. Pick the test from the [commit](https://github.com/tenstorrent/tt-metal/compare/main...keerthana/squeezebert_conv1d_testcases).
2. Run `pytest tests/ttnn/unit_tests/operations/test_conv1d.py::test_squeezebert_conv1d`.

**Expected behavior**
Expected to pass the testcase with bias.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Devices: GS, WH(n300)

**Comment by saichandax** [comment]
cc: @boris-drazic , @jvasilje

**Comment by mywoodstock** [comment]
@saichandax @kkeerthana0573 On running the test on your branch, I get a different error:
```
E       RuntimeError: TT_ASSERT @ ../ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp:503: bias_tensor.value().get_shape().rank() == 4
```
Am I missing something?

**Comment by kkeerthana0573** [comment]
@mywoodstock, 
On running the test on my branch, I got the same error as reported. Please find the attached test log. 
[log.txt](https://github.com/user-attachments/files/17048591/log.txt)

Thank you.

**Comment by mywoodstock** [comment]
OK, so the bias shape was incorrect in the unit test. Please pick up this commit:
https://github.com/tenstorrent/tt-metal/pull/12846/commits/9b8eabb4b93c28bf84224e96005fbf588c0cf49b

LMK if it works fine for you now.

**Comment by kkeerthana0573** [comment]
@mywoodstock, 
Thanks for the fix. 
With the [https://github.com/tenstorrent/tt-metal/commit/9b8eabb4b93c28bf84224e96005fbf588c0cf49b](https://github.com/tenstorrent/tt-metal/commit/9b8eabb4b93c28bf84224e96005fbf588c0cf49b) commit, first test_case with `input_shape [8, 384, 768]` and `output_channels: 768` **passed**. While the rest of the cases failed with `Statically allocated circular buffers on core range [(x=0,y=0) - (x=11,y=7)] grow to {} B which is beyond max L1 size of {} B`. 

Please find the log attached for the above mentioned Statically allocated CB error. [log.txt](https://github.com/user-attachments/files/17050211/log.txt)

Thank you.
