### ISSUE TITLE
Investigate mismatch between mixtral README numbers and CI/dashboard numbers

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#12578]
Possible perf regression:
Mixtral:
README: 15.7
latest passing release (https://github.com/tenstorrent/tt-metal/actions/runs/10693502206): 13.6

**Comment by skhorasganiTT** [comment]
Assigning P0 per the request of @uaydonat

**Comment by mtairum** [comment]
The 15.7 t/s/u was an abnormal perf that lasted a few days. We weren't doing perf analysis on Mixtral at the time, so we never checked what might have caused the bump. 

But 13.6 t/s/u is in-inline with that the current perf should be, so I'll update the README file.

Keep in mind that after the Llama3.1-8B perf sprint we'll give some TLC to Mixtral, both CI-wise and perf-wise.

**Comment by mtairum** [comment]
Pushed README change here: https://github.com/tenstorrent/tt-metal/pull/12629

@uaydonat  Let me know if we should keep this open for later when we resume mixtral perf, or close it now and then we reopen when Mixtral is stable again and ready for perf improvements.
