### ISSUE TITLE
Llama3-70B README notes (customer drop)

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent/tt-metal#12605]
Few questions fro the user prespective, please:
- The 128K seq length option is not mentioned in the run options in the README. Will it be a 3rd option with batch 1? 
- Can we clarify which options are running under the performance demo (i.e. batch, seq length, profile or decode only…)?
- Why not running the prefill as the only option, why do we still need to run decode_only if prefill is performing well? 
- Can we remove the arguments with one option only, like llama version and the T3000 implementation?
- Add the method on how to set : host's CPU frequency governors are set to performance

**Comment by uaydonat** [comment]
> The 128K seq length option is not mentioned in the run options in the README. Will it be a 3rd option with batch 1?

Good point. @cglagovichTT let's add separate batch size and seq_length as options, the demo can assert that the selected values can fit in T3000, but the users should be able to set arbitrary batch size and seq length.

> Can we clarify which options are running under the performance demo (i.e. batch, seq length, profile or decode only…)?

This is not clear to me. All the listed option can be set. Are you asking what config gives 15 t/s/u? or which configs are tested internally?

> Why not running the prefill as the only option, why do we still need to run decode_only if prefill is performing well?

decode-only option is useful for debugging if the demo breaks. Same for for num_layers.

> Can we remove the arguments with one option only, like llama version and the T3000 implementation?

llama3 is not the only option. llama2 can also be selected. Same demo launched from different model folders with different options. (The README under llama2 folder shows the instructions to run llama2.) @cglagovichTT maybe we change text to this for better clarity.

`llama_version: [llama3, llama2]: Select llama3 model`

> Add the method on how to set : host's CPU frequency governors are set to performance

I do not know if this belongs in the model README. We should have a system README file for system configuration. @tt-rkim ?

**Comment by tt-rkim** [comment]
> Add the method on how to set : host's CPU frequency governors are set to performance
>
> I do not know if this belongs in the model README. We should have a system README file for system configuration. @tt-rkim ?

@uaydonat I believe this in particular does belong in models-type documentation, as the use case for CPU perf governor is only for models. However, we can expand the `INSTALLING.md` with additional information about models installation. We have some specific instructions for models in there, already. Let us know if you need guidance on adding this section.

**Comment by uaydonat** [comment]
> > Add the method on how to set : host's CPU frequency governors are set to performance
> > I do not know if this belongs in the model README. We should have a system README file for system configuration. @tt-rkim ?
> 
> @uaydonat I believe this in particular does belong in models-type documentation, as the use case for CPU perf governor is only for models. However, we can expand the `INSTALLING.md` with additional information about models installation. We have some specific instructions for models in there, already. Let us know if you need guidance on adding this section.

This is a system setting that is common to all models (not just llama) and any other experiment the user wants to bring up on our systems. It would make sense to mention it in INSTALLING.md.

For even better coverage, we can refer to the INSTALLING.md in model READMEs.

**Comment by jvasilje** [comment]
@uaydonat @cglagovichTT has this issue been resolved? readme updated? can we close this?

**Comment by cglagovichTT** [comment]
Just closed the PR. Please reopen if there are more requests on the Llama readme.

**Comment by mbahnasTT** [comment]
I like it, thanks! @cglagovichTT
