### ISSUE TITLE
Complete customer team trial installation of wheel after `patchelf` and related cleanup for metal wheel `v0.52.0-rc21`

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#12609]
Please refer to https://github.com/tenstorrent/tt-metal/releases/tag/v0.52.0-rc21

This is a release candidate. We generate these every night.

Please note:

- Not all models are guaranteed to be working. Please refer to the CI workflow linked in the release description to see what has been tested.
- We now no longer ask users set *neither* the `TT_METAL_HOME` nor the `ARCH_NAME` environment variables. *Do not set these*. This will ensure we trigger the wheel flow. We can put more verbose checks for this to ensure customers don't go down the right path. Note `PYTHONPATH` should still be set for models.
- Please ensure to clone the repo at the specified tag if you need the source code for models.
- Let us know if we should remove the part about models not working with source, if the wheel is more functional with models this time.

Let us know if we should put any of this in the installation instructions.

Let us know of any other specific feedback to take action on. Otherwise, we will consider there to be no action items on infra or metal team.

Let us know if you have any further questions.

cc: @TT-billteng

**Comment by dvartaniansTT** [comment]
@tt-rkim I confirm falcon7b model demo passes. and the WHL installation was smooth. but all models demos need to pass for an official WHL release as we see in the CI some model demos failed. 

The detailed instructions added to the issue description such as following the installation guide from the whl branch/tag ... the note regarding env variables setting, ... should be added to the installation instructions for the customers as well. cc: @mbahnasTT

**Comment by tt-rkim** [comment]
@uaydonat @skhorasganiTT Note that customer team is raising the issue of not all model demos passing on an official release.

The official position of the models team is it will NOT be a release-level goal to ensure that all models function for the same release candidate wheel, while at the same time advertising the latest and greatest performance numbers for all the models. The only guarantee the models team will deliver for the time being is that functioning individual models can be tied to specific release candidates (NOT non-release official releases). So, users on the front page will know which model works on which release candidate, but it won't necessarily be the same one for all models. @uaydonat can elaborate.

I have personally urged model team to treat breaking model demos as P0.

**Comment by tt-rkim** [comment]
Thank you for your feedback @dvartaniansTT . If you believe the instructions for wheel were sufficient, then we can close the instructions changes issue for the wheel as well.
