### ISSUE TITLE
ttnn.max_pool2d fails in convnet mnist model

### ISSUE THREAD

**Issue by vigneshkeerthivasanx** [tenstorrent/tt-metal#12642]
**Describe the bug**
ttnn.max_pool2d fails in convnet mnist model

**To Reproduce**
pick the test from [commit](https://github.com/tenstorrent/tt-metal/compare/vignesh/ttnn_maxpool_mnist_unit_test) 
Run pytest 

**Expected behavior**
As the above shared configuration works in pytorch, it is expected to run in ttnn aswell.

**Screenshots**
```
E       RuntimeError: TT_FATAL @ ../tt_metal/impl/buffers/buffer.cpp:38: valid_page_size
E       info:
E       For valid non-interleaved buffers page size 2156 must equal buffer size 107748. For interleaved-buffers page size should be divisible by buffer size
```

**Comment by vigneshkeerthivasanx** [comment]
CC: @boris-drazic @jvasilje

**Comment by mywoodstock** [comment]
@vigneshkeerthivasanx Looks like I need this file to run: `convnet_mnist.pt`. Where can I get it?

**Comment by vigneshkeerthivasanx** [comment]
@mywoodstock The `convnet_mnist.pt` file is available in weka in the following location
`/mnt/MLPerf/tt_dnn-models/ConvNetMNIST/convnet_mnist.pt`
