### ISSUE TITLE
ttnn.conv2d failing in unit test of vovnet model

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#12648]
**Describe the bug**
ttnn.conv2d is failing with `Statically allocated l1 buffer` issue in unit test

**To Reproduce**
1. Checkout [keerthanar/vovnet_unit_tests](https://github.com/tenstorrent/tt-metal/tree/keerthanar/vovnet_unit_tests)
2. Run `pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_vovnet_conv_issue`
3. The following error will occur,
`Statically allocated circular buffers on core range [(x=0,y=0) - (x=6,y=0)] grow to 1827680 B which is beyond max L1 size of 1499136 B`

**Please complete the following environment information:**
- WH (n150)

**Comment by dvartaniansTT** [comment]
@keerthana-r-mcw is this the only failing conv vairant? https://github.com/tenstorrent/tt-metal/blob/keerthanar/vovnet_unit_tests/tests/ttnn/unit_tests/operations/test_new_conv2d.py#L2056

please note on the issue description which convs are failing. 
also make a note that you have commented out the failing variant. for unit test purposes for the issue, I'd actually recommend commenting out passing ones and letting the developers/engineering team easily run the unit test for the failing case.

**Comment by keerthana-r-mcw** [comment]
Hi @dvartaniansTT , 
This [commit](https://github.com/tenstorrent/tt-metal/compare/main...keerthanar/vovnet_unit_tests) has three different tests where one has all passing convs (`test_conv_vovnet`), one has test case that throws `Statically allocated l1 buffer` (`test_vovnet_conv_issue`) and another has convs that pass with `split_conv` (`test_conv_vovnet_split`). 
Issue [test
](https://github.com/tenstorrent/tt-metal/blob/6b1253d32f5db2ca573936523a7c63451bf8e6e2/tests/ttnn/unit_tests/operations/test_new_conv2d.py#L2208)In the description, I attached the command line to run the test that has conv throwing `Statically allocated l1 buffer`,
`pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_vovnet_conv_issue`

**Comment by mywoodstock** [comment]
@keerthana-r-mcw Could you please give this another try with latest `main` -- I think it should be resolved.

**Comment by pavlejosipovic** [comment]
@keerthana-r-mcw @dvartaniansTT 
I run this test case on latest main 
https://github.com/tenstorrent/tt-metal/tree/pjosipovic/conv_vovnet-model
I had to tweak the failing conv to use auto_shard in order to pass as height sharding is not a good fit for that conv.
You can also explicitly use block sharding in this case if you prefer that.

If this is good enough for you can you pls close the issue?

**Comment by keerthana-r-mcw** [comment]
I'll check and let you know.

**Comment by keerthana-r-mcw** [comment]
Closing issue, since issue got resolved
