### ISSUE TITLE
ttnn.softmax returns zero valued tensor in convnet mnist model

### ISSUE THREAD

**Issue by vigneshkeerthivasanx** [tenstorrent/tt-metal#12664]
**Describe the bug**
ttnn.softmax returns zero valued tensor in convnet mnist model resulting in PCC = 0.0.

**To Reproduce**
Pick the test from [commit](https://github.com/tenstorrent/tt-metal/compare/vignesh/ttnn_softmax_convnet_mnist)
Run pytest 

**Expected behavior**
As the above shared configuration works in pytorch, it is expected to run in ttnn as well.

**Screenshots**
```
 ERROR    | models.utility_functions:comp_pcc:602 - One tensor is all zero
E       AssertionError: 0.0
```

**Comment by vigneshkeerthivasanx** [comment]
CC: @boris-drazic @jvasilje

**Comment by saichandax** [comment]
@vigneshkeerthivasanx , Can you check if the issue is still persistent?

**Comment by vigneshkeerthivasanx** [comment]
> [@vigneshkeerthivasanx](https://github.com/vigneshkeerthivasanx) , Can you check if the issue is still persistent?

I checked yesterday, and the issue persists in the model.

**Comment by saichandax** [comment]
@yugaoTT , Could you share any update on this issue, as it is a blocker for ConvNetMnist model?

cc: @boris-drazic

**Comment by yugaoTT** [comment]
can you please try ttnn_tensor = ttnn.softmax(ttnn_tensor, dim=-1, numeric_stable=True) ? 
we added a numeric_stable flag to make the computation more stable. Thanks

**Comment by vigneshkeerthivasanx** [comment]
The issue was resolved by using `numeric_stable=True` in `ttnn.softmax`. Thank you.
Hence closing the ticket.
