### ISSUE TITLE
Enabling async mode crashes UNet Shallow

### ISSUE THREAD

**Issue by esmalTT** [tenstorrent/tt-metal#12685]
### Summary

I am currently seeing a segmentation fault when enabling it on UNet. The model runs for about 4 or 5 iterations and then crashes consistently on upsample on the 6th. 

I haven't seen the issue with async enabled on single device, only on N300.

To reproduce - checkout b7d8a6a5d990d5d93fd47fa55d9b678a1dc2551c and run the following.

```sh
pytest -sv models/experimental/functional_unet/tests/test_unet_perf.py::test_unet_data_parallel_perf_e2e
```

Make sure you have `export WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml`.

**Comment by esmalTT** [comment]
@tt-asaigal has a solution for this. Apparently `std::set` is not thread-safe but it is used in `MemoryConfig`.

Just opening this for tracking puposes.

**Comment by TT-billteng** [comment]
If you see a lot more places where you need thread-safe data structures, consider using TBB more throughout the code base

**Comment by esmalTT** [comment]
Resolved 👍
