### ISSUE TITLE
Bert Split Support

### ISSUE THREAD

**Issue by tarafdarTT** [tenstorrent/tt-metal#12729]
I accidentally made the issue in the wrong project (pytorch2.0) , so I'm copying it here. 

Sprint on making sure all split configs are supported in Bert.

### aten.split.Tensor
|    | ATen Input Variations                                                    | Status   |
|---:|:-------------------------------------------------------------------------|:---------|
|  0 | Tensor<[1, 256, 2]> self = ?,<br>int<> split_size = 1,<br>int<> dim = -1 | Unknown  |

This is equivalent to TTNN split where we set splitting into two chunks on the last dim. Let's just make sure that works for this shape.

The split op currently only splits in two (@jaykru-tt is adding support for splitting N ways), on the last dim and its tilized.

As you see with this shape its not a friendly tiliizable shape, lets start with `Row-Major` support. 

You can have the split op under neath the hood use slice since slice is more flexible. 

Split into two equals = Slice first half, Slice second half. 

Sync with @sjameelTT on how to use the slice op 

CC: @ayerofieiev-tt

**Comment by jaykru-tt** [comment]
resolved by #12804.
