### ISSUE TITLE
Failed conv in Yolov7

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#12785]
**Describe the bug**
On unit testing the Conv2d ops of Yolov7, a Conv failed with the following error:
```
E       RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:143: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 819200 B L1_SMALL buffer across 50 banks, where each bank needs to store 16384 B
```

**To Reproduce**
1. Checkout to the branch [harini/yolov7_failing_convs](https://github.com/tenstorrent/tt-metal/compare/harini/yolov7_failing_convs)
2. Run the command: `pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_yolov7_failing_convs`

**Expected behavior**
Expected to pass the failing conv.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: WH n300

**Comment by dvartaniansTT** [comment]
@HariniMohan0102 why is use shallow conv variant set to False it the unit test? this is a 3 input channel conv. it is shallow.

**Comment by dvartaniansTT** [comment]
@HariniMohan0102 I se you listed N300, are you doing data parallel or using a single chip on N300?

**Comment by HariniMohan0102** [comment]
@dvartaniansTT Unit tests are done on n300 in single chip.

**Comment by shwetankTT** [comment]
@HariniMohan0102 I checked the issue at the mainline. The given test case passes if you set the --> {"act_block_h": 64}

**Comment by mywoodstock** [comment]
@HariniMohan0102 Please try the config @shwetankTT mentioned above and let us know if this can be closed.

**Comment by HariniMohan0102** [comment]
Sure, I'll test the config and update you.

**Comment by HariniMohan0102** [comment]
The test case passed by having "act_block_h": 64 in config override. 
Closing the issue, as it is resolved.
Thank you.
