### ISSUE TITLE
TTNN Matmul op doesn't support nd1 - nd2 product when d1 < d2

### ISSUE THREAD

**Issue by sdjordjevicTT** [tenstorrent/tt-metal#12828]
**Describe the bug**
TTNN Matmul op does not work when the rank of input_tensor_b is greater than the rank of input_tensor_a. According to the [public documentation](https://docs.tenstorrent.com/ttnn/latest/ttnn/ttnn/matmul.html), this kind of product is supported. I am consistently encountering an error when trying to execute this specific operation.

**To Reproduce**
```python
import ttnn
import torch

device = ttnn.open_device(0)

tensor_a = torch.rand(256, 2048)
tensor_b = torch.rand(7, 7, 2048, 256)

tensor_c = torch.matmul(tensor_a, tensor_b)

print(tensor_c.shape)


a_tt = ttnn.from_torch(tensor_a, layout=ttnn.TILE_LAYOUT, device=device)
b_tt = ttnn.from_torch(tensor_b, layout=ttnn.TILE_LAYOUT, device=device)

c_tt = ttnn.matmul(a_tt, b_tt)

ttnn.close_device(device)
```

Error once the above code is executed:
```
Always | FATAL    | When in1 rank greater than in0 rank front dimensions need to be 1
Traceback (most recent call last):
  File "/localdev/sdjordjevic/src/tt-metal/simple_test.py", line 17, in <module>
    c_tt = ttnn.matmul(a_tt, b_tt)
  File "/localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/decorators.py", line 326, in __call__
    return self.function(*function_args, **function_kwargs)
RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp:1273: input_shape_b[index] == 1
info:
When in1 rank greater than in0 rank front dimensions need to be 1
backtrace:
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0x36f8a8) [0x7ff12df7d8a8]
 --- ttnn::operations::matmul::Matmul::compute_output_shapes(std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&) const
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(_ZN2tt8tt_metal9operation29generic_create_output_tensorsIN4ttnn10operations6matmul6MatmulEEENS1_21program_output_helperIT_Xsr18has_create_programIS8_EE5valueEE4typeERKS8_RKNSt3__16vectorINS0_6TensorENSD_9allocatorISF_EEEENSD_8optionalINS0_8DataTypeEEENS0_6LayoutERKNSL_INS0_12MemoryConfigEEE+0x46) [0x7ff12e8afd66]
```

**Expected behavior**
The expected behavior is that this scenario should work as stated in the public documentation.

**Screenshots**
N/A

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Version of software: commit https://github.com/tenstorrent/tt-metal/commit/23b968f8cb5ae13b95d876d615599733903ce375

**Additional context**
N/A

**Comment by bbradelTT** [comment]
This is related to batching.

tensor_a has implied batching dimensions 1,1
tensor_b has batching dimensions 7,7

Those need to be the same. It's a limitation of how we rely on tensor_a to determine batching parameters.

```
tensor_a = torch.rand(256, 2048)
tensor_b = torch.rand(1, 1, 2048, 256)
```
should work

```
tensor_a = torch.rand(7,256, 2048)
tensor_b = torch.rand(1, 7, 2048, 256)
```
should work too.

In general, the batch dimensions of the tensors need to be aligned or tensor_b needs to have them be 1, to have meaningful results.

The documentation needs to be made more clear about how batching works.

**Comment by bbradelTT** [comment]
Updated doc string with this scenario.

Doc string updated via PR https://github.com/tenstorrent/tt-metal/pull/13071
