### ISSUE TITLE
[Bug Report] Slice op, documentation and functionality

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-metal#12826]
**Describe the bug**
Seems like the `slice` op is missing from [TT-NN API](https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api.html#operations) documentation, while it has references in the tt-metal source ([ref to the op](https://github.com/tenstorrent/tt-metal/blob/main/ttnn/cpp/ttnn/operations/data_movement/slice/slice.cpp)).

Core reason for using this op is certain casing for indexing (where stride is 1). Currently, we're relying on decomposing this type of op into a combination of matmuls and transposes. 

**Expected behavior**
Slice op is outlined and documented with other data movement ops.

**Screenshots**
<img width="288" alt="image" src="https://github.com/user-attachments/assets/66fb0cf3-3b6e-4abd-a971-401ff1173eb0">

**Comment by sjameelTT** [comment]
Should be in main now.
