### ISSUE TITLE
bert model calls squeeze on non-dim 0 tensor

### ISSUE THREAD

**Issue by kevinwuTT** [tenstorrent/tt-metal#12854]
[bert model](https://github.com/tenstorrent-metal/pytorch2.0_ttnn/blob/main/tests/test_bert.py) calls squeeze on the last dimension of a 3D tensor:

```
torch.ops.aten.squeeze(tensor, -1) # tensor.shape = torch.Size([1, 256, 1])
```

However, `ttnn.squeeze` only [supports dim 0 currently ](https://github.com/tenstorrent/tt-metal/blob/aaab87ae7a03bda838307a94940390494e205b4e/ttnn/ttnn/operations/core.py#L186)

**Comment by ayerofieiev-tt** [comment]
https://github.com/tenstorrent/tt-metal/pull/12734

**Comment by tarafdarTT** [comment]
@kevinwuTT just added it. There is another issue with reshape that certain shapes hit that I'm working on but squeeze can now squeeze on any dim.
