### ISSUE TITLE
WRCFG conflicting with MMIO writes.

### ISSUE THREAD

**Issue by amahmudTT** [tenstorrent/tt-metal#12855]
**Describe the bug**

From what is observed, WRCFG instructions in one thread can collide with MMIO writes in another. This was observed in issue #9370 , the call to ```reduce_revert_delta which eventually``` calls ```_llk_pack_reduce_mask_clear_``` by the packer executes some WRCFG instructions and if the unpacker during that time moves ahead and performs MMIO write instructions in the function ```_llk_unpack_AB_matmul_``` we observe that the stale value in SrcB is used by the unpacker leading to wrong results.  

We implemented a workaround by replacing WRCFG instructions with RMWICB instructions.  https://github.com/tenstorrent/tt-metal/pull/12832

**To Reproduce**

Branch : amahmud/colman_mod_sdpa

Command : ```pytest -svv tests/tt_eager/python_api_testing/unit_testing/misc/test_scaled_dot_product_attention.py::test_sdpa_nd_program_cache```

The SPDA problem is modified to make Q, K and V matrices all diagonal. The result should be the product of Q, K and V and diagonal too. But when run multiple times, for some calls to matmul_block which is supposed to multiply V with a block from the matrix QK actually multiplies with something that was supposed to be used in SrcB in a call to the function reduce_c. 

The constants are put in such a way that the result could only be derived by the mistake above 

```
   Q = torch.eye(s, d).expand(b, nh, s, d) * 5
   K = torch.eye(s, d).expand(b, nkv, s, d) * 7
   V = torch.eye(s, d).expand(b, nkv, s, d) * 9
   
   In the writer thread we create tiles with constant 3. 
   generate_reduce_scaler(cb_identity_scale_in, 0x40404040);
 ```
 
   The output should be a diagonal matrix with 316 in the diagonal. But for some blocks at the top we get 27, which is what we would get if we multiplied a tile from V with a tile containing 3 that is created in the writer and which we use in the function reduce_c. 
   In the matmul_block function after updating the address of SrcA and SrcB using MMIO, the first unpack instruction unpacks SrcB and this instruction gets the wrong address. 
   
   If you want to reproduce the issue on the main branch, revert workaround commit mentioned above but keep the UNPACR(tensix_sync()) function deleted which was another workaround. But It is not easy to understand what is happening by printing the results. in the main branch because the matrices contain random numbers.

**Expected behavior**
The result should be a diagonal matrix and reflect the multiplication of QKV.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Comment by amahmudTT** [comment]
Running the test in slow dispatch mode, i.e TT_METAL_SLOW_DISPATCH_MODE=1, also failed.

**Comment by ttmtrajkovic** [comment]
Adding @vtangTT to enable Versim

**Comment by amahmudTT** [comment]
The branch 

```amahmud/sdpa_reduced```  commit id ```bff71e90db7e56fbafe11de5cef65e7ec0af0ac7``` can now reproduce the issue deterministically. 

To do this we applied 

1. It required taking all the wait_fronts out of the loops for circular buffers which interact with DRAM. 
2. Added 55 (empirically derived depends on the changes mentioned below) number of unpacker nops at the start of matmul_blocks function, since removing the wait front will speed up the unpacker. 

The above two steps would have made it deterministic, but for some reason we seem to be having a non determinism which vary by 1-2 cycles. To prevent that 

3. 1000 nops were added for unpacker/math/packer threads before all the wait fronts.
4. The WRCFG instructions were copy pasted 3 times in the ```_llk_pack_reduce_mask_clear_``` called by ```reduce_revert_delta``` function. 

The bug is hit in two ways , once when the SrcB address is not updated in the first iteration of the q_iter loop, and the other in the second one. The above changes made the first one manifest and the test case checks against the buggy output. Running the test case should say it did not match with the expected result but did with the expected buggy output.

**Comment by amahmudTT** [comment]
Added c++ test case using only one tile. 

```
Branch: amahmud/sdpa_tiny 
Commit: fbaee350b9bfc794724d222f54f964255f515ddb
Command: TT_METAL_SLOW_DISPATCH_MODE=1 TT_NOP_INSERT=7 ./build_Release/test/tt_metal/test_sdpa_nd_bug 

Correct Output - diagonal_tile(316)
Result - diagonal_tile(45)  or diagonal_tile(0)  // Depends on the number of nops

Pseudocode:

Q = diagonal_tile(5)
K = diagonal_tile(7)
V = diagonal_tile(9)
cb_identity_scale  = tile_first_32(3)

QK = Q*K 
IM  = Q*K + cb_identity_scale
Out = QK * V
```

Result is either 0 * V or Q * V,   even though IM is correct. 
SrcB uses a stale buffer from the double buffering.

**Comment by amahmudTT** [comment]
Note:

Some similar code is also present for wormhole in functions 

```
_llk_pack_reduce_mask_config_
unpacker_wrapup
```

**Comment by amahmudTT** [comment]
Branch https://github.com/tenstorrent/tt-metal/tree/amahmud/sdpa_x1_ver 
Can run the test in simulator and also run its counterpart in python (needed to choose the number of nops needed).
When the cpp test test_sdpa_nd_bug is run on the simulator with 36/40 nops it fails. We copy pasted the code in ```_llk_pack_reduce_mask_clear_``` to allow for multiple points of failure. With 35 nops it does not fail. 

To run the problem follow the instructions here 
https://yyz-gitlab.local.tenstorrent.com/tenstorrent/tt-metal/-/blob/main/versim/README.md

The typical run command would look like 

```
NNG_SOCKET_NAME=deviceinit TT_METAL_SLOW_DISPATCH_MODE=1  TT_NOP_INSERT=35 ./test_sdpa_nd_bug &> sdpa_35_nop
```

Result for such runs is saved in the ```/proj_sw/user_dev/amahmud/sdpa_bug_simulations``` folder in the yyz* compute machines. Files like sdpa_*_nop contain the standard output and files starting with versim prefix contain the versim log. They can be matched by noting the number of nops mentioned in the files.

**Comment by amahmudTT** [comment]
VCD Dumps for 35 nops (ND not observed) and 36 nops (ND observed) introduced in the above mentioned test case.

[Uploading SDPA_VCD.zip…](https://github.com/tenstorrent/tt-metal/issues/12855)

**Comment by amahmudTT** [comment]
Same issue can be reproduced on blackhole. Just that for the above test case we need 54 nops. But on Wormhole depending on the number of nops in extreme rare cases I see an old buffer is introduced or a buffer with zeroes for SrcB, but on Blackhole I see with not = 55 a random pattern is introduced. (So does blackhole not clear L1 memory to zeroes ?)  And on Blackhole the problem seems to be more deterministic on hardware. Probably because how the threads are launched. For example on Wormhole for a certain number of nops I generally get 90% failures, but on blackhole it is more like 100% failures.

**Comment by amahmudTT** [comment]
The cause of the issue has been found and is explained here :
https://github.com/tenstorrent/tt-metal/issues/9370#issuecomment-2455455056

**Comment by amahmudTT** [comment]
Similar cases : 

```
/tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_unpack_tilize_api.h"   Function : llk_unpack_tilizeA_B

```

**Comment by amahmudTT** [comment]
Closing this issue. Further ND due to the same code pattern but in other files will be treated as separate issue/issues. 
[Unsafe code used for MMIO leading to potential race conditions. #14694](https://github.com/tenstorrent/tt-metal/issues/14694)
