### ISSUE TITLE
ttnn.slice doesn't support tensors of rank != 4

### ISSUE THREAD

**Issue by jaykru-tt** [tenstorrent/tt-metal#12860]
At least for host tensors (have not confirmed for device tensors) slice errors out on tensors of rank < 4 due to indexing into their shape at [3]. If slice can't be easily tweaked to support rank < 4 tensors, it should at least do an unsqueeze on the input followed by a squeeze on its output to avoid a confusing error for its consumers.

**Comment by jaykru-tt** [comment]
@sjameelTT we added support for sub-rank-4 tensors right? Can I close this? Otherwise, could you assign it to yourself?

**Comment by sjameelTT** [comment]
We have all rank support now for slice!
