### ISSUE TITLE
`reshape` doesn't work correctly in `TILE` layout

### ISSUE THREAD

**Issue by mtopalovicTT** [tenstorrent/tt-metal#12866]
**Describe the bug**
`Reshape` produces different results when tensor is in row vs tile layout.
In our example we will work on 4x4 tensor which has numbers from 0 to 15.
* If we reshape this tensor in row layout to `2x8` we get expected result i.e `[[0, 1 ... 6, 7], [8, 9 ... 14, 15]]`.
* If we reshape this tensor in tile layout to `2x8` and then convert to row layout `[[0, 1, 2, 3, 0, 0, 0, 0], [4, 5, 6 ,7, 0, 0, 0, 0]]`

From what we see `reshape` in `TILE` layout includes zeros from padded input tensor to output tensor. Example above is coded in below python script.

**To Reproduce**
```
import numpy as np
import ttnn

device_id = 0
device = ttnn.open_device(device_id=device_id)

ttnn.set_printoptions(profile="full")
t = ttnn.arange(0, 16, dtype=ttnn.int32)
t = ttnn.reshape(t, (4, 4))
print("Initial tensor")
print(t)

reshape_in_row = ttnn.reshape(t, (2, 8))
print("{ROW_MAJOR_LAYOUT} Initial tensor to 2x8 shape")
print(reshape_in_row)

tile_layout_t = ttnn.to_layout(t, ttnn.TILE_LAYOUT, device=device)
print("{TILE_LAYOUT} Initial tensor")
print(tile_layout_t)

tile_layout_t_after_reshape = ttnn.reshape(tile_layout_t, ttnn.Shape((2, 8), (32, 32)))
print("{TILE_LAYOUT} After reshape to 2x8 shape")
print(tile_layout_t_after_reshape)

tile_to_row_layout_t = ttnn.to_layout(tile_layout_t_after_reshape, ttnn.ROW_MAJOR_LAYOUT, device=device)
print("{ROW_MAJOR_LAYOUT} Tile layout reshaped tensor to row major")
print(tile_to_row_layout_t)

ttnn.close_device(device)
```

**Expected behavior**
We expect that reshape in tile and row layout works the same i.e if we take reshaped tensor in row layout it should look exactly the same as reshape in tile layout (after we convert tile reshape output to row major layout).

**Screenshots**
Input tensor.
<img width="808" alt="image" src="https://github.com/user-attachments/assets/3a45dbd7-c034-4fa4-9f90-076fa4abd860">
`reshape` on row major layout input tensor.
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/dc94db15-0c1e-47d3-be6a-65e0cff6a5d8">
`reshape` on tile major layout input tensor (result is converted to row major for simplicity).
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/4d79b38e-8ae1-47de-ba89-e1376dc63a2f">

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Version of software: 242308ee8f71b1e2b914c320ba6d6e24e15b72e4 (any version has this behaviour)

**Additional context**

**Comment by tt-mpantic** [comment]
Hi @tarafdarTT any updates on this one ?

**Comment by ntarafdar** [comment]
solved here:
https://github.com/tenstorrent/tt-metal/pull/13022
will merge soon

**Comment by nvukobratTT** [comment]
Hey guys, I'm just checking in to see if the change for this issue is ready to be merged? :))

**Comment by ntarafdar** [comment]
addressed in https://github.com/tenstorrent/tt-metal/pull/13022 and its merged
