### ISSUE TITLE
didt FF1 without GELU hang pcie dead

### ISSUE THREAD

**Issue by skrsmanovicTT** [tenstorrent/tt-metal#12888]
Based on FW80.10.4 bundle baseline didt testing [results](https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?gid=1118664107#gid=1118664107), this issue will be used to track debug activities related to specific test case failure type.

### Failure description and reproduce steps
**Test case:** FF1 without GELU
**Failure behavior:** test execution hangs, pcie is dead, warm reset(using tt-smi -r) fix the hang
**Affected systems/boards:**
bgd-lab-26 board 0
**Reproduce steps - running test:** WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/experimental/falcon_7b/tests/test_reproduce_hang_matmul.py -k "test_reproduce_matmul_2d_hang and ff1-hang and 2chips"
Note: Please note that numbef of test iterations need to be set using NUM_ITERATIONS variable inside test_reproduce_hang_matmul.py depending on system failure speed rate - for this use case failure is often seen around 100k iterations.
**Reproduce steps - running ttp capture of ARC data:** ttp didt_multichip --args out=ttp_data.csv,num_iters=300000
Note: ttp and safe mode is set up from [tt-experiment repo](https://yyz-gitlab.local.tenstorrent.com/tenstorrent/tt-experiment).

### Failure analysis
**Last lines of ttp log before hang:**
```
19940.29, 136.94, 167.00, 769.5,  47.81, 803.00,   0.82, c0de004d, 15ae9bd4, 0-0
19942.20,  17.82, 158.00, 864.0,  37.31, 788.00,   0.81, c0de0042, 15ae9c3e, 1-0
Failed to read from chip 1-0: Read 0xffffffff from ARC scratch[6]: you should reset the board.
Failed to read from chip 0-0: Read 0xffffffff from ARC scratch[6]: you should reset the board.
Saved data to ff1_no_gelu_board_0-0-0.csv
Saved data to ff1_no_gelu_board_0-1-0.csv
Data saved for all chips
Sampled data for all chips in 350.04 seconds
<PASSED> didt_multichip.py
```
**ttp capture left chip:**
![image](https://github.com/user-attachments/assets/e0aba9e8-95fb-42e4-af48-ad5e5df41f7b)
**ttp capture right chip:**
![image](https://github.com/user-attachments/assets/c34e65d5-f52b-4d0e-b6c3-1507abb9e059)
**TODO:** provide raw ttp results

**Note:** This failure is under investigation more debug results will be provided when finished.

**Comment by ttmtrajkovic** [comment]
No longer valid.
After PGOOD problems were diagnosed, we no longer see failures where pcie is not alive.
