### ISSUE TITLE
didt FF1 without GELU hang pcie alive

### ISSUE THREAD

**Issue by skrsmanovicTT** [tenstorrent/tt-metal#12887]
Based on FW80.10.4 bundle baseline didt testing [results](https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?gid=1118664107#gid=1118664107), this issue will be used to track debug activities related to specific test case failure type.

### Failure description and reproduce steps
**Test case**: FF1 without GELU
**Failure behavior**: test execution hangs, pcie is alive and device can be debugged, warm reset fix the hang
**Affected systems/boards:**
bgd-lab-t3002 board 3
**Reproduce steps - running test**: WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/experimental/falcon_7b/tests/test_reproduce_hang_matmul.py -k "test_reproduce_matmul_2d_hang and ff1-hang and 2chips"
Note: Please note that numbef of test iterations need to be set using NUM_ITERATIONS variable inside test_reproduce_hang_matmul.py depending on system failure speed rate - for this use case failure is often seen around 1M iterations.
**Reproduce steps - running ttp capture of ARC data**: ttp didt_multichip --args out=ttp_data.csv,num_iters=1800000
Note: ttp and safe mode is set up from [tt-experiment repo](https://yyz-gitlab.local.tenstorrent.com/tenstorrent/tt-experiment).

**Note:** This failure is under investigation more debug results will be provided when finished.

**Comment by skrsmanovicTT** [comment]
# Debug updates
**Test case:** FF1 without GELU
**Machine:** bgd-lab-t3002 board 3
**Failure behavior:** test execution hangs, pcie is alive and device can be debugged, warm reset fix the hang
**Branch:** skrsmanovic/didt_hang_l1_debug - latest didt branch with added debug postcodes in L1
**Reproduce steps - running test:** pytest tests/didt/test_ff1_matmul.py::test_ff1_matmul -k "without_gelu and 2chips" --iterations 1000000

## Debug infrastructure
**syseng repo:** https://yyz-gitlab.local.tenstorrent.com/tenstorrent/syseng
**syseng repo setup:**
```
cd syseng/src/t6ifc/t6py
./bin/venv-create 
source bin/venv-activate.sh
``` 
Commits https://github.com/tenstorrent/tt-metal/commit/24b67625bd85b0f734d76d62a7fe1b3c4747b8d0 and https://github.com/tenstorrent/tt-metal/commit/0b551cc1a638ec7211591c74b0e81edb565f16c4 are leaving some postcodes in L1 memory that can help us to navigate where kernel execution hangs. To read L1 after hang **read-noc** command from syseng repo will be used.
Debug postcodes will be left at address 0x15200(compute kernel) and 0x15240(data movement kernel) in L1 memory.
**read-noc** syntax:
```
read-noc --interface <pci_interface> --chip_x <X> --chip_y <Y> --x <x> --y <y> --num_words <num_words> --addr <addr>
<pci_interface> is pcie interface to which board is attached for example pci:0, pci:1, pci:2, pci:3....
<X> is x coordinate of chip in chip grid - can be observed from tt-smi command
<Y> is y coordinate of chip in chip grid - can be observed from tt-smi command
<x> is x coordinate of core inside chip (address of specific core in chip grid that we want to read from)
<y> is y coordinate of core inside chip (address of specific core in chip grid that we want to read from)
<num_words> is number of words (word is 4 bytes) to be read from memory
<addr> is L1 address to be read from
```

## Debug steps
Once test hangs first it is important to determine chip that is hang, for that purpose we can look at test output, last id that shows in test output is id of chip that hangs:
```
2024-09-24 13:08:18.897 | INFO     | tests.didt.matmul_test_base:run_matmul:167 - Start sync device id: 0
2024-09-24 13:08:18.899 | INFO     | tests.didt.matmul_test_base:run_matmul:169 - End sync device id: 0
2024-09-24 13:08:18.899 | INFO     | tests.didt.matmul_test_base:run_matmul:167 - Start sync device id: 1
2024-09-24 13:08:18.899 | INFO     | tests.didt.matmul_test_base:run_matmul:169 - End sync device id: 1
2024-09-24 13:08:18.899 | INFO     | tests.didt.matmul_test_base:run_matmul:199 - Iteration = 614015, done!
2024-09-24 13:08:18.899 | INFO     | tests.didt.matmul_test_base:run_matmul:167 - Start sync device id: 0
2024-09-24 13:08:18.901 | INFO     | tests.didt.matmul_test_base:run_matmul:169 - End sync device id: 0
2024-09-24 13:08:18.901 | INFO     | tests.didt.matmul_test_base:run_matmul:167 - Start sync device id: 1
``` 
Based on this log chip with id 1 hangs (right chip with coordinates 1, 0).
### Compute kernel analysis
Read out of postcodes in compute kernel:
```
[1930] skrsmanovic:bgd-lab-t3002-special-skrsmanovic-for-reservation-3924457 /proj_sw/user_dev/skrsmanovic/syseng/src/t6ifc/t6py > read-noc --addr 0x15200 --interface pci:3 --chip_x 1 --chip_y 0 --x 1 --y 1 --num_words 10
00: 0x00015200 => 0x99deda99
01: 0x00015204 => 0x01c1b811
02: 0x00015208 => 0x00000001
03: 0x0001520c => 0x00baba01
04: 0x00015210 => 0x08baba01
05: 0x00015214 => 0x00002036
06: 0x00015218 => 0x00000c00
07: 0x0001521c => 0x00002636
08: 0x00015220 => 0x000000cc
09: 0x00015224 => 0x00000080
```
Comparing last post code on address 0x1520c with modified compute kernel code it is clear that compute kernel stuck at: https://github.com/tenstorrent/tt-metal/blob/0b551cc1a638ec7211591c74b0e81edb565f16c4/tt_metal/hw/ckernels/wormhole_b0/metal/llk_io/llk_io_unpack.h#L50-L72 waiting for all tiles of operand 0 to be received.

### Data movement kernel analysis
When we are analyzing data movement kernel postcodes it is important to note how data movement is organized in case of test specific matmul operation (where data is stored, how it is multicasted 1d or 2d etc..). In case of this particular run it can be observed that all cores with x coordinate 8 are stuck with same postcode (other cores are passing this failing point):
```
[2014] skrsmanovic:bgd-lab-t3002-special-skrsmanovic-for-reservation-3924457 /proj_sw/user_dev/skrsmanovic/syseng/src/t6ifc/t6py > read-noc --addr 0x15240 --interface pci:3 --chip_x 1 --chip_y 0 --x 8 --y 1 --num_words 10
00: 0x00015240 => 0x00000024
01: 0x00015244 => 0x0001a360
02: 0x00015248 => 0x08baba01
03: 0x0001524c => 0x00018fe0
04: 0x00015250 => 0x00000008
05: 0x00015254 => 0x77cccc77
06: 0x00015258 => 0x77cccc77
07: 0x0001525c => 0x77cccc77
08: 0x00015260 => 0x77cccc77
09: 0x00015264 => 0x77cccc77
```
Looking at modified data movement kernel code:
https://github.com/tenstorrent/tt-metal/blob/0b551cc1a638ec7211591c74b0e81edb565f16c4/ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in0_sender_receiver_padding_block_sharded.cpp#L171-L187
it is clear that kernel is stuck waiting for all semaphores to atomically increment.

**Comment by pavlepopovic** [comment]
bgd-lab-t3001, board 0, same signature

**Comment by skrsmanovicTT** [comment]
bgd-lab-t3004 board 1 after rebase (branch: ppopovic/rebased_2) with FW80.10.4.1, same signature FF1 without GELU

**Comment by ttmtrajkovic** [comment]
After diagnosing PGOOD problems and reworking boards, this is no longer observed
