### ISSUE TITLE
Add Initial N300 CCL unit tests

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#12883]
We are missing (even basic) test coverage for CCLs on N300. Although our testing on t3000 should naturally have high overlap with n300, it can't ensure the basics don't regress (e.g. basic behaviour to run all all-gathers on n300 as line).

Ideally these tests can give us sanity-test level coverage in post commit and for that reason I think we can add a very small number of tests (2 per op) and leave it there. Over time we may swap these specific cases out for more complex ones but we should try to have atleast 1 or 2 in. 

This will also help catch accidental CCL related regressions in case someone unknowingly breaks something in CCL ops which as of now are only tested in frequent and nightly jobs.

I propose we start with these 2 test cases on n300:

## 1
interleaved
2 chips
1 link
shape (before fracture) [1, 1, 64, 16384]
dim=3
layout = ttnn.TILE_LAYOUT),

## 2
input_shape (per chip): [1, 1, 512, 2048],
shard shape: [128, 256]
Shard strategy: width
Core range:            ttnn.CoreRangeSet({ttnn.CoreRange(ttnn.CoreCoord(0, 0), ttnn.CoreCoord(7, 3))}),
2 chips
1 link
row major orientation

## Calling All Gather
When calling all-gather, we shouldn't distinguish between line or ring and should just call default `ttnn.all_gather`

## Test Location
I would like to put this under ttnn-unit tests as a new ttnn-group (currently the highest group number is `ttnn group 6`. Pending @tt-rkim's approval, we should make a new one: `ttnn ccl group`. This is specified in `.github/workflows/ttnn-post-commit.yaml`

**Comment by tt-rkim** [comment]
This is fine with me. Another job in ttnn. @TT-billteng you too?

Main thing is how long these would take. Do you already have some initial N300 tests?

**Comment by SeanNijjar** [comment]
> This is fine with me. Another job in ttnn. @TT-billteng you too?
> 
> Main thing is how long these would take. Do you already have some initial N300 tests?

I don't have exact runtimes yet (here's a PR we'll be able to get runtimes from when the tests are added to post-commit: https://github.com/tenstorrent/tt-metal/pull/12922).

However, I can't imagine it taking more than an extra minute (assuming the build artifacts are able to be loaded very quickly.

**Comment by SeanNijjar** [comment]
@tt-rkim Update on this. They way the TTNN tests are currently grouped, they will automatically pick up the new CCL tests (here's a run: https://github.com/tenstorrent/tt-metal/actions/runs/10955272562/job/30419809641). Based on the timestamps in the logs, it's only a few seconds of extra runtime. 

My preference would have been a separate TTNN CCL test group but it looks like at the moment that's going to be more annoying than its worth, given how the groups are currently split. So let's consider the topic of new test group concluded.

**Comment by tt-rkim** [comment]
Sounds good, you can close it if there's nothing else to do for now.

Once there's more, we can talk about splitting off things into another job
