### ISSUE TITLE
didt FF1 with GELU safe mode board unavailable

### ISSUE THREAD

**Issue by skrsmanovicTT** [tenstorrent/tt-metal#12884]
Based on FW80.10.4 bundle baseline didt testing [results](https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?gid=1118664107#gid=1118664107), this issue will be used to track debug activities related to specific test case failure type.
### Failure description and reproduce steps
**Test case**: FF1 with GELU
**Failure behavior**: test execution hangs, pcie is dead, tt-smi reset not possible, green (power good LED) is turned off - power cycle of system is required for further investigation
**Affected systems/boards:**
bgd-lab-t3001 board 0
bgd-lab-t3002 board 2
bgd-lab-t3003 board 3 (*Needs to be confirmed)
**Reproduce steps - entering safe mode**: ../tt-experiment/bin/force_voltage_aiclk --enable --aiclk 650 --voltage 850
**Reproduce steps - running test**: WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest tests/didt/test_sharded_ff1.py -k "test_reproduce_matmul_2d_hang and 2chips"
**Note**: Please note that numbef of iteration tests need to be set using NUM_ITERATIONS variable inside test_sharded_ff1.py depending on system failure speed rate - failing iteration can be found in baseline results.
**Reproduce steps - running ttp capture of ARC data**: ttp didt_multichip --args out=board0_ff1_with_gilu_safe_mode.csv,num_iters=1800000
**Note**: ttp and safe mode is set up from [tt-experiment repo](https://yyz-gitlab.local.tenstorrent.com/tenstorrent/tt-experiment).

### Failure analysis
**Last lines of test log before hang:**
```
2024-09-19 11:15:12.901 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:194 - End sync device id: 0
2024-09-19 11:15:12.901 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:184 - Start sync device id: 1
2024-09-19 11:15:12.901 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:194 - End sync device id: 1
2024-09-19 11:15:12.901 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:226 - Iteration = 298179
2024-09-19 11:15:12.901 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:184 - Start sync device id: 0
2024-09-19 11:15:12.904 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:194 - End sync device id: 0
2024-09-19 11:15:12.904 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:184 - Start sync device id: 1
2024-09-19 11:15:12.904 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:194 - End sync device id: 1
2024-09-19 11:15:12.904 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:226 - Iteration = 298180
2024-09-19 11:15:12.904 | INFO     | tests.didt.test_sharded_ff1:test_reproduce_matmul_2d_hang:184 - Start sync device id: 0
``` 
**Last lines of ttp log before hang:**
```
830432.30, 135.29, 166.00, 648.0,  57.62, 785.00,   0.81, c0de0042, 64d2e3, 1-0
830694.85, 151.06, 182.00, 648.0,  80.00, 788.00,   0.83, c0de004d, 64d7aa, 0-0
830697.43, 138.61, 166.00, 648.0,  57.62, 785.00,   0.83, c0de004d, 64d718, 1-0
830959.27, 147.42, 182.00, 648.0,  80.12, 788.00,   0.81, c0de0042, 64dbda, 0-0
830961.85,  45.64,  56.00, 648.0,  57.62, 785.00,   0.81, c0de004c, 64db47, 1-0
831223.77,  38.88,  48.00, 648.0,  80.31, 788.00,   0.81, c0de0042, 64e00c, 0-0
831226.37, 136.92, 168.00, 648.0,  57.62, 785.00,   0.81, c0de0042, 64df79, 1-0
Failed to read from chip 1-0: Read 0xffffffff from ARC scratch[6]: you should reset the board.
Failed to read from chip 0-0: Read 0xffffffff from ARC scratch[6]: you should reset the board.
Saved data to board0_ff1_with_gilu_safe_mode-0-0.csv
Saved data to board0_ff1_with_gilu_safe_mode-1-0.csv
Data saved for all chips
Sampled data for all chips in 1801.90 seconds
```
**ttp capture left chip:**
![board0_ff1_with_gilu_safe_mode-0-0](https://github.com/user-attachments/assets/593d51bd-9d9d-49f2-b61b-366f34a8ca27)
raw data: 
[board0_ff1_with_gilu_safe_mode-0-0.csv](https://github.com/user-attachments/files/17060433/board0_ff1_with_gilu_safe_mode-0-0.csv)

**ttp capture right chip:**
![board0_ff1_with_gilu_safe_mode-1-0](https://github.com/user-attachments/assets/2d1d33e0-d590-4b4f-9b15-5bbb76ad8ed8)
raw data: 
[board0_ff1_with_gilu_safe_mode-1-0.csv](https://github.com/user-attachments/files/17060478/board0_ff1_with_gilu_safe_mode-1-0.csv)
**TT-Health therm trip check command:** ../tt-experiment/bin/tt-heatlh --cli_all passive
**TT-Health therm trip results:** No new therm trip triggers, tt-helath log file: 
[09-19-2024_12:07:47_results.txt](https://github.com/user-attachments/files/17060728/09-19-2024_12.07.47_results.txt)

### Recovery steps
**Warm reset:** 
```
skrsmanovic:bgd-lab-t3001-special-skrsmanovic-for-reservation-3923680 /localdev/skrsmanovic/gitrepos/tt-experiment > tt-smireset 
	 Starting pci link reset on WH devices at pci indices: 0 
 Failed to recover WH chip, please reboot the system to reset the chip. Exiting...
```
**Cold reset:** Since power good LED (green LED) was off, power cycle of system was done and board is operational after that step.

**Comment by ttmtrajkovic** [comment]
After diagnosing PGOOD problems and reworking boards, this is no longer observed
Safe mode tested on many systems:
https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?pli=1&gid=341688123#gid=341688123
