### ISSUE TITLE
Tensor–tensor bitwise operators

### ISSUE THREAD

**Issue by jdh8** [tenstorrent/tt-metal#12907]
Currently, our bitwise operators support tensor&ndash;scalar operations, namely
- `ttnn.bitwise_and`
- `ttnn.bitwise_or`
- `ttnn.bitwise_xor`

Extending the second argument (RHS) from a scalar to a tensor unlocks lowering from `aten.bitwise_*.Tensor`.

**Comment by tt-rkim** [comment]
@ayerofieiev-tt is this an ops or infra issue? Sounds like ops?

**Comment by KalaivaniMCW** [comment]
Related to #13582

**Comment by umadevimcw** [comment]
@jdh8 This is already tracked here #13582.

Can we close this issue ?

**Comment by eyonland** [comment]
#13582 is now closed and should be resolved.
