### ISSUE TITLE
[Bug Report] Multiple wormhole cards cause a coredump

### ISSUE THREAD

**Issue by EternalPeace** [tenstorrent/tt-metal#12987]
**Describe the bug**
Multiple wormhole cards cause a coredump，
using the example test：
./build/programming_examples/loopback 

**To Reproduce**
insert multiple wormhole cards into the server。

1.git clone https://github.com/tenstorrent/tt-metal.git --recurse-submodules
2.cd tt-metal
3.git submodule foreach 'git lfs fetch --all && git lfs pull'
4.export ARCH_NAME=wormhole_b0
export TT_METAL_HOME=$(pwd)
export PYTHONPATH=$(pwd)
5.
./build_metal.sh
6../create_venv.sh
7.source python_env/bin/activate
8../build/programming_examples/loopback

**Expected behavior**

2024-09-22 10:17:07.388 | INFO     | SiliconDriver   - Detected 4 PCI devices : [0, 1, 2, 3]
2024-09-22 10:17:07.903 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.9.0 (Device 0)
2024-09-22 10:17:07.905 | INFO     | SiliconDriver   - Detected 4 PCI devices : [0, 1, 2, 3]
2024-09-22 10:17:07.911 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.9.0 (Device 1)
2024-09-22 10:17:07.912 | INFO     | SiliconDriver   - Detected 4 PCI devices : [0, 1, 2, 3]
2024-09-22 10:17:07.919 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.9.0 (Device 2)
2024-09-22 10:17:07.920 | INFO     | SiliconDriver   - Detected 4 PCI devices : [0, 1, 2, 3]
2024-09-22 10:17:07.930 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.9.0 (Device 3)
2024-09-22 10:17:07.931 | FATAL    | Always          - Unexpected ERISC Response Flags.
libc++abi: terminating due to uncaught exception of type std::runtime_error: Unexpected ERISC Response Flags.
backtrace:
 --- /root/zych/tt-metal/build_Release/lib/libdevice.so(+0x3de42) [0x7fd87ebdae42]
 --- tt_SiliconDevice::read_from_non_mmio_device(void*, tt::umd::cxy_pair, unsigned long, unsigned int)
 --- tt_SiliconDevice::read_from_device(void*, tt::umd::cxy_pair, unsigned long, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
 --- tt_SiliconDevice::verify_eth_fw()
 --- tt_SiliconDevice::start_device(tt_device_params const&)
 --- tt::Cluster::initialize_device_drivers()
 --- tt::Cluster::Cluster()
 --- tt::Cluster::instance()
 --- /root/zych/tt-metal/build_Release/tt_metal/libtt_metal.so(+0x13ca78) [0x7fd87ef90a78]
 --- /root/zych/tt-metal/build_Release/tt_metal/libtt_metal.so(+0x13c6a2) [0x7fd87ef906a2]
 --- /root/zych/tt-metal/build_Release/tt_metal/libtt_metal.so(+0x13c4de) [0x7fd87ef904de]
 --- tt::DevicePool::initialize(std::__1::vector<int, std::__1::allocator<int>>, unsigned char, unsigned long, unsigned long, tt::tt_metal::DispatchCoreType, std::__1::vector<unsigned int, std::__1::allocator<unsigned int>> const&)
 --- tt::tt_metal::CreateDevice(int, unsigned char, unsigned long, unsigned long, tt::tt_metal::DispatchCoreType, std::__1::vector<unsigned int, std::__1::allocator<unsigned int>> const&)
 --- ./build/programming_examples/loopback(+0x7aba) [0x556ad47b4aba]
 --- /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fd87e554083]
 --- ./build/programming_examples/loopback(+0x799e) [0x556ad47b499e]

Aborted (core dumped)

**Screenshots**
<img width="415" alt="image" src="https://github.com/user-attachments/assets/e83c9d85-ff81-4876-91d7-31128d010df5">

**Please complete the following environment information:**
commit:9091cb77dfbfb2fe141ccb79c887f5367c92d8d9
uname -a
Linux x3002 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
tt-flash flash --fw-tar fw_pack-80.10.0.0.fwbundle --force

**Additional context**
we don't want to isolate the device, we want to solve the problem.

**Comment by mbahnasTT** [comment]
please switch to v0.51.0, it's working there seamlessly without the need to isolate any cards.
<img width="952" alt="image" src="https://github.com/user-attachments/assets/548aa400-a8ff-48ad-b9b1-e82c3d24e068">

**Comment by mbahnasTT** [comment]
It's working good on the tag v52-rc31 as well.

**Comment by EternalPeace** [comment]
<img width="415" alt="image" src="https://github.com/user-attachments/assets/070e773e-6368-4c3f-88df-b87a75dfe3c1">

**Comment by EternalPeace** [comment]
> <img alt="image" width="415" src="https://private-user-images.githubusercontent.com/27431100/370224361-070e773e-6368-4c3f-88df-b87a75dfe3c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzA5ODYsIm5iZiI6MTcyNzE3MDY4NiwicGF0aCI6Ii8yNzQzMTEwMC8zNzAyMjQzNjEtMDcwZTc3M2UtNjM2OC00YzNmLTg4ZGYtYjg3YTc1ZGZlM2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA5MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MTYxZGViNmNjNWYxZTdmMGZiOThkNDBjNDRhMzg0N2Y0MTFlYzY2NzM5YmI1NDNiZDNhMjIzYzUyZWI4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UzP6Rk9uS8Mmj4FDk8cZLK3EQTPKaVC123yarNrFUmY">

Could it be an environment issue?
Could it be that there’s a problem with my hardware? How can I confirm if the hardware itself is functioning properly?
