### ISSUE TITLE
Track t3000 nightly regression

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#12986]
T3000 nightly has recently regressed. Issue tracks root causing the problem commit and resolving the issue. I suspect the issue is related to 4-chip reduce scatter tests where the 4 chosen chips do not form a ring and so error out when trying to identify receiver and sender chips.

Please reassign accordingly after problem commit has been identified.

**Comment by Aswinmcw** [comment]
Hi @cfjchu , after your PR (#12719), t3k nightly tests are failing due to device not connected issue, Can you look into it 
Failing pipeline (https://github.com/tenstorrent/tt-metal/actions/runs/10948889220)

**Comment by SeanNijjar** [comment]
Hey @cfjchu, I assume these (4chip) tests fail now because we don't by default specify the inner 4 chip ring. I'd l8ke some input from you about the best way to proceed so we can still have a4chip ring? Do we just need to invoke the APIs differently in order to get that ring?
