### ISSUE TITLE
Bringup llama3.1 8b on N300 to support 128k context length 

### ISSUE THREAD

**Issue by sraizada-tt** [tenstorrent/tt-metal#12991]

**Comment by yieldthought** [comment]
I modified `models/demos/llama3/demo/demo.py` to be able to read in arbitrary context from Gutenberg books and asked it to quote and analyse parts of the first context-length of Frankenstein. 11623 tokens of prompt already produces bad output.

**Comment by yieldthought** [comment]
16k sequence length in `test_llama_model_prefill.py` passes with PCC: 0.968

**Comment by sraizada-tt** [comment]
Can you double check if the prompt is formatted correctly with the chat headers?

**Comment by sraizada-tt** [comment]
Also - just to ensure nobody does redundant work- I found 32k and 64k give bad pcc only because of the SDPA accumulation error that Jack is working on fixing

**Comment by yieldthought** [comment]
> Can you double check if the prompt is formatted correctly with the chat headers?
Yeah it correctly used the instruct chat headers, I explicitly printed the prompt to check.

**Comment by sraizada-tt** [comment]
Hmm, previously I have seen good outputs even when prefill pcc is as low as 0.92
