### ISSUE TITLE
[GH Permissions] Need permission to push a branch and create PR

### ISSUE THREAD

**Issue by tt-vjovanovic** [tenstorrent/tt-metal#13038]
## What you are trying to do...

I want to add small script that will install tt-debuda for tt-metal developers. It will provide simple device debugging capabilities (reading/writing to L1, reading registers, etc.).

## Who needs permissions...

I need permissions for myself: @tt-vjovanovic. I'm already part of Tenstorrent organization...

**Comment by tt-rkim** [comment]
Done.

I recommend putting it in `scripts/` and putting a CODEOWNER for it.
