### ISSUE TITLE
Yolov4 shard concat fails with low pcc

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#13037]
**Describe the bug**
ttnn.concat with shard memory config in yolov4 fails with low pcc

**To Reproduce**
1. Checkout [keerthanar/yolov4_shard_conv_issue](https://github.com/tenstorrent/tt-metal/tree/keerthanar/yolov4_shard_conv_issue)
2. Run `pytest tests/ttnn/unit_tests/operations/test_shard_concat.py`
3. The test will fail with low `PCC = 0.9846032141739874`
 
Device - WH n150

https://github.com/tenstorrent/tt-metal/issues/12387

**Comment by dvartaniansTT** [comment]
@punithsekar is this still a valid issue? are we doing sharded concat in main now or still doing S2I ,... ?

**Comment by punithsekar** [comment]
We are doing sharded concat for some sub_modules in the main(DS1 to DS3). For remaining we are using S2I.
@keerthana-r-mcw , Can you add some points on this?

**Comment by keerthana-r-mcw** [comment]
@dvartaniansTT, this issue is created to follow up on this old issue https://github.com/tenstorrent/tt-metal/issues/12387.

**Comment by dvartaniansTT** [comment]
@keerthana-r-mcw , I dont get it. is this issue resolved now or not and why are we still using S2I in some yolov4 submodules for the concat op? cc: @punithsekar and @mbahnasTT

**Comment by keerthana-r-mcw** [comment]
We were getting low PCC if we used shard concat in some of YOLOV4's submodules; for those, we are still using S2I.

**Comment by keerthana-r-mcw** [comment]
Hi,
In the latest main, we tried to test the test and noticed that the inputs passed to the shard concat are in the interleaved memory config. So, I changed it to shard and checked. Now, we are getting 0.98 pcc.
@ntarafdar Can you please check the test once?
cc: @dvartaniansTT 
Thanks
