### ISSUE TITLE
[Bug Report] Program does not end after using Maxpool

### ISSUE THREAD

**Issue by athul-bos-semi** [tenstorrent/tt-metal#13034]
**Problem Description**
The program runs to completion, even goes through all the subsequent functions, but it does not stop running. 

**To Reproduce**
1. Use _ttnn.max_pool2d_new()_

**Expected Behavior**
The program closes device and stops running. 
If you got to this stage, use Ctrl+Z to end the program, then warm reset the card, else the new program also gets stuck in random places.

**Screenshots**
![Screenshot from 2024-09-24 09-54-20](https://github.com/user-attachments/assets/3472887a-07ab-4981-b028-5314b054bbd1)

**Environment Information:**
- OS: Metal Devcloud accessed through Ubuntu 22.04 client
- Version of software: TT-Metal v0.51.0

**Additional context**
The same code works smoothly if Maxpool is not used.

**Comment by dvartaniansTT** [comment]
@mywoodstock 

I tried to replicate this reported issues. 

built from v51. 
and copied files from [Athul's repo](https://github.com/athul-bos-semi/UNet_TTNN/tree/main) 
placed them under: tests/ttnn/integration_tests/vanilla_unet_bos/
ran: `python tests/ttnn/integration_tests/vanilla_unet_bos/test_unet.py` 
replaced this line in test_unet.py: `device = tt_lib.device.CreateDevice(2, l1_small_size=32768, num_hw_cqs=1)` with `device = tt_lib.device.CreateDevice(0, l1_small_size=32768, num_hw_cqs=1)` as my device id is 0: 

but was unable to reproduce the reported issue. instead I get a different error:

**Comment by athul-bos-semi** [comment]
I uploaded the new code using ttnn instead of tt-lib [here](https://github.com/athul-bos-semi/UNet_TTNN/tree/main), but it won't work with v0.51.0, because v51 does not have ttnn.reshard. This code, in v52, will go all the way to Upsample 3, but fails due to using too much memory. I am working on fixing this now.

**Comment by mbahnasTT** [comment]
@athul-bos-semi I'll close all the 3 issues you filed, assuming we passed them all, then you may file new ones based on the progress. Thanks!
