### ISSUE TITLE
blackhole machines ci is flaky

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#13076]
Noticed roughly around when new fw was flashed 
machines CI has been flaky ever since

**Comment by smehtaTT** [comment]
@bkeith-TT @ttmchiou @abhullar-tt  - please help update this with JIRA tickets / more info

**Comment by abhullar-tt** [comment]
The flakiness causes ND hangs on the machines after running tt-smi reset at the end of CI jobs. This is seen even after successful jobs. 

Related JIRA tickets:
https://tenstorrent.atlassian.net/browse/SYS-851
https://tenstorrent.atlassian.net/browse/SYS-953

**Comment by bkeith-TT** [comment]
Status 2024-11-04:
- SYS-851 is mostly fixed, but being held in review pending larger FW release
- SYS-953 seems assigned but not started

**Comment by ttmchiou** [comment]
Blackhole post-commit seems to be in a stable state after flashing to 80.12.0.0 fw.

There exists more up-to-date fw but devs and SysEng is currently taking a look.
https://github.com/tenstorrent/tt-metal/issues/14775

Successive Blackhole GREEN post-commit runs

https://github.com/tenstorrent/tt-metal/actions/runs/11693253538
https://github.com/tenstorrent/tt-metal/actions/runs/11694720296
https://github.com/tenstorrent/tt-metal/actions/runs/11693150103


In the meantime closing this issue as Blackhole post-commit seems to be in a stable state until fixes are introduced in newer fw
