### ISSUE TITLE
Low PCC on Matmul on WH when tweaking out_subblock_h

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent/tt-metal#13080]
**Describe the bug**
In the configs of FF2 and self_output matmuls of ViT model on WH, there is a low PCC issue:
- If `out_subblock_h == per_core_M == 7` then the PCC is low for the attention module
- If `out_subblock_h == 1` then PCC is passing the set threshold > 0.829

**To Reproduce**
1. Go to main branch
2. run as is `pytest  --disable-warnings  tests/ttnn/integration_tests/vit/test_ttnn_optimized_sharded_vit_wh.py` then PCC test is passing > 0.829
3. Modify `out_subblock_h=1` to be `out_subblock_h=7` in `models/experimental/functional_vit/tt/ttnn_optimized_sharded_vit_wh.py` at line 57 and/or line 77. These are the configs `self_output_matmul_program_config` and `ff2_matmul_program_config`
4. run again `pytest  --disable-warnings  tests/ttnn/integration_tests/vit/test_ttnn_optimized_sharded_vit_wh.py`  to observe the low PCC

**Expected behavior**

**Screenshots**
`FAILED tests/ttnn/integration_tests/vit/test_ttnn_optimized_sharded_vit_wh.py::test_vit[sequence_size=224-image_channels=3-image_size=224-batch_size=8-model_name=google/vit-base-patch16-224] - AssertionError: 0.14427797253910019`

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by bbradelTT** [comment]
@mbahnasTT [mbahnas/vit_wh](https://github.com/tenstorrent/tt-metal/tree/mbahnas/vit_wh) seems to no long exist. Could you please create it again?

**Comment by bbradelTT** [comment]
I recreated with
```
a=ttnn.from_torch(torch.ones([1,1,1024,256], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
b=ttnn.from_torch(torch.ones([1,1,256,512], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
program_config=ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
                compute_with_storage_grid_size=ttnn._ttnn.tensor.CoreCoord(4, 4),
                in0_block_w=1,
                out_subblock_h=2,
                out_subblock_w=4,
                per_core_M=8,
                per_core_N=4,
                transpose_mcast=False,
                fused_activation=None,
                fuse_batch=False,
                )
c = ttnn.matmul(a,b, program_config=program_config)
print(c)
```

To make testing easier, I switched to 8 instead of 7. That still resulted in incorrect output:
```
a=ttnn.from_torch(torch.ones([1,1,1024,256], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
b=ttnn.from_torch(torch.ones([1,1,256,512], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
program_config=ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
                compute_with_storage_grid_size=ttnn._ttnn.tensor.CoreCoord(4, 4),
                in0_block_w=1,
                out_subblock_h=8,
                out_subblock_w=4,
                per_core_M=8,
                per_core_N=4,
                transpose_mcast=False,
                fused_activation=None,
                fuse_batch=False,
                )
c = ttnn.matmul(a,b, program_config=program_config)
print(c)
```

Reducing the out subblock h/w to be within 8 when multiplied together removes the incorrect output:
```
a=ttnn.from_torch(torch.ones([1,1,1024,256], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
b=ttnn.from_torch(torch.ones([1,1,256,512], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
program_config=ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
                compute_with_storage_grid_size=ttnn._ttnn.tensor.CoreCoord(4, 4),
                in0_block_w=1,
                out_subblock_h=2,
                out_subblock_w=4,
                per_core_M=8,
                per_core_N=4,
                transpose_mcast=False,
                fused_activation=None,
                fuse_batch=False,
                )
c = ttnn.matmul(a,b, program_config=program_config)
print(c)
```

That is the requirement we have for internally generated matmul configs. We may need to enforce that for user supplied ones as well.

Looking into this further.

**Comment by bbradelTT** [comment]
I talked to @yugaoTT
He said that 8 is a hard limit because there are only 16 dest registers that can hold up to 16  32x32 tiles,
and we use half_sync mode, which means only 8 registers are available for each  matmul call.

I'll update the validate() call to check the limit of 8.
