### ISSUE TITLE
ttnn.Conv1d fails with L1 OOM issue for SqueezeBERT [WH]

### ISSUE THREAD

**Issue by kkeerthana0573** [tenstorrent/tt-metal#13093]
**Describe the bug**
ttnn.Conv1d fails with L1 OOM issue for SqueezeBERT. 

  On WH - n300:
  ```
  E       RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:143: tt::exception
  E       info:
  E       Out of Memory: Not enough space to allocate 192 B L1_SMALL buffer across 48 banks, where each bank needs to store 32 B
  ```

**To Reproduce**

1. Pick the test from the [commit](https://github.com/tenstorrent/tt-metal/compare/main...keerthana/squeezebert_ttnnconv1d_testcases).
2. Run `pytest tests/ttnn/unit_tests/operations/test_squeezebert_conv1d.py::test_squeezebert_attention`.

**Expected behavior**
Expected to pass the testcase.

**Please complete the following environment information:**
OS: [e.g. Ubuntu 20.04]
Devices: WH(n300)

**Comment by kkeerthana0573** [comment]
cc: @boris-drazic

**Comment by mywoodstock** [comment]
@kkeerthana0573 The test is missing device params for L1 small space. Please add this to the test:
```
@pytest.mark.parametrize("device_params", [{"l1_small_size": 16384}], indirect=True)
```
