### ISSUE TITLE
Add output memory configuration option for conv2d/maxpool2d

### ISSUE THREAD

**Issue by LPanosTT** [tenstorrent/tt-metal#13106]
As of now, Conv2d and Maxpool leave the output on L1. It would be beneficial for the MLIR team to have the option to model where the output ends up in the compiler. 

For now we'd want to use this feature to set the output to being on device DRAM, in the interleaved format. This will make bringup easier while we work on actually modelling sharding and memory/buffer types.

Looking to be able to define a `Conv2dConfig` like this:

```
conv_config = ttnn.Conv2dConfig()
conv_config.output_memory_space = ttnn.DRAM_MEMORY_CONFIG
conv_config.output_shard_spec = ttnn.INTERLEAVED
```

CC: @nvukobratTT

**Comment by mywoodstock** [comment]
@LPanosTT We can support this, but will require some major updates/additions to the kernels (e.g. we will need an explicit writer kernel to move data to DRAM).

**Comment by mywoodstock** [comment]
The plan is to use `sharded2interleaved` in the conv macro op based on the output memory config provided to the op.

**Comment by mywoodstock** [comment]
PR has landed in main
