### ISSUE TITLE
[Bug Report] Cannot reshape ROW_MAJOR tensor

### ISSUE THREAD

**Issue by LPanosTT** [tenstorrent/tt-metal#13120]
**Describe the bug**
Performing the following reshape on a ROW_MAJOR tensor yields an error:

- Reshape: (1, 224, 224, 3) --> (1, 1, 50176, 3)
- Error: `RuntimeError: TT_FATAL @ /localdev/lpanos/tt-metal/tt_metal/impl/buffers/buffer.cpp:41: page_size % sizeof(uint32_t) == 0`

If the tensor is TILE_LAYOUT instead we get this error, which seems to make sense:
`Unable to reshape a tensor in TILE_LAYOUT to non-tile height and width! Please convert the tensor to ROW_MAJOR_LAYOUT first.`

**To Reproduce**

Run the following test:
```
def test_reshape_broken(device):

    input = torch.randn(1, 224, 224, 3, dtype=torch.bfloat16)
    new_shape = (1, 1, 50176, 3)
    layout = ttnn.TILE_LAYOUT

    input_tensor = ttnn.from_torch(input, layout=layout, dtype=ttnn.bfloat16, device=device)

    ttnn_output = ttnn.reshape(input_tensor, new_shape)
```

**Expected behavior**
The reshape should execute.

**Additional context**
In order to accurately model the tensor shapes in a compiler, a reshape must be inserted on the output of `Conv2d` since most (if not all) frameworks' `Conv2d` ops output a tensor in the form `(N, H, W, C)`, ttnn outputs `(1, 1, N*H*W, C)`. This is blocking the first convolution in resnet50.

**Comment by mtopalovicTT** [comment]
@tarafdarTT Hi naif, are you familiar with this one? I also stepped onto it while trying out different tensor sizes.


cc @tt-mpantic @sdjordjevicTT

**Comment by mtopalovicTT** [comment]
@LPanosTT After some looking it seems that this constraint is well [documented](https://docs.tenstorrent.com/ttnn/latest/ttnn/tensor.html#ttnn-row-major-layout)

ttnn.Tensor uses a minimum of 4 bytes to store a row of the tensor in [ttnn.ROW_MAJOR_LAYOUT](https://docs.tenstorrent.com/ttnn/latest/ttnn/tensor.html#ttnn-row-major-layout) on the device. That means that the width of a tensor on the device must be a multiple of 4 / sizeof(dtype). The exact numbers are shown below:

**Comment by LPanosTT** [comment]
@mtopalovicTT that makes sense to me, it’s just that the page_size gets calculated to be 6, and I’m wondering if maybe there’s something wrong with that calculation, or if this on-device reshape is just impossible

**Comment by LPanosTT** [comment]
@mtopalovicTT so is the conclusion for this just that this reshape is impossible to do on device no matter the layout?

**Comment by mtopalovicTT** [comment]
@LPanosTT sorry I'm not following
per this:
> That means that the width of a tensor on the device must be a multiple of 4 / sizeof(dtype). The exact numbers are shown below:

In your case width is 3, and requirement for float16 is that width should be divisible by 2 if I understand this documentation properly.

**Comment by LPanosTT** [comment]
> In your case width is 3, and requirement for float16 is that width should be divisible by 2 if I understand this documentation properly.

Okay so it definitely will not work in row-major layout then. But it also won't work in tile layout. So, that would mean that this reshape cannot be done on device?

**Comment by mtopalovicTT** [comment]
To your questions I'm not sure :D We are currently pushing a uplift of metal in mlir which carries fixes for reshape after which we can test different scenarios. IIRC fix was that if some reshape couldn't be done on device due to constraint, reshape is pushed is done on cpu and then returned to device.

**Comment by ntarafdar** [comment]
this has been covered now with our generality reshape push
