### ISSUE TITLE
2D -> 1D Reshape fails with ttnn::Reshape, but works by directly calling tensor.reshape

### ISSUE THREAD

**Issue by jnie-TT** [tenstorrent/tt-metal#13159]
**Describe the bug**
`ttnn::Reshape` doesn't work when squeezing the last dim of a 2D row major device tensor - getting error `Unable to reshape given tensor!`. However, directly calling tensor.reshape works.

**To Reproduce**
This fails:
```
std::array<int32_t, 1> newShape = {32};
// Here tensor is a 32x1 row major single-device tensor
ttnn::reshape(tensor, newShape);
```
This works:
```
std::array<int32_t, 1> newShape = {32};
// Here tensor is a 32x1 row major single-device tensor
tensor.reshape(newShape);
```

cc: @AleksKnezevic @mrakitaTT

**Comment by ntarafdar** [comment]
solved here: https://github.com/tenstorrent/tt-metal/pull/13022
will merge soon

**Comment by AleksKnezevic** [comment]
Thanks for the quick fix @ntarafdar!!!

**Comment by ntarafdar** [comment]
merged in, I'm closing issue for now, feel free to re-open if main isn't still working for your case.
