### ISSUE TITLE
Conv in Model_K with Dilation>1 gives Unexpected output shape 

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#13170]
**Describe the bug**
On testing Model_k having Conv2d with dilation>1, the output shape is different from the expected output shape. Expected to have  same output shape of Torch Conv2 output and TTNN Conv2 output.

**_Note:_** Error is not reproducible. Comparing the printed output shapes of torch and ttnn convs.

**To Reproduce**
1. Checkout to the branch: [harini/failing_conv_dilation](https://github.com/tenstorrent/tt-metal/tree/harini/failing_conv_dilation)
2. Run the command `pytest tests/ttnn/unit_tests/operations/test_conv_dilation.py`

**Expected behavior**
Expected to get same output shapes of torch and ttnn conv2d ops when dilation>1. 

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: WH n150

**Comment by mywoodstock** [comment]
@sankarmanoj-tt assigning this to you. I did a quick check on the issue, it looks like there is some issue with the output shape of the tensor -- the shape calculated is all good, but the tesnor seems strange as it shows the unpadded output size larger than padded size (they should both be same in this case):
```
ttnn.Shape([1, 1, 14884[14400], 48[64]])
ttnn.Shape([1, 1, 13924[12800], 56[64]])
```
Could you please debug?

**Comment by HariniMohan0102** [comment]
The issue is resolved. I'm closing the issue.
Thank you.

**Comment by dvartaniansTT** [comment]
@HariniMohan0102 have you ran the model_k end to end and verified that dilation>1 works as expected in the end to end model?

**Comment by HariniMohan0102** [comment]
@dvartaniansTT I'll check in end to end model pipeline for dilation>1 and will let you know.
