### ISSUE TITLE
[Bug Report] ttnn.max - Unsupported dim 

### ISSUE THREAD

**Issue by chandrasekaranpradeep** [tenstorrent/tt-metal#13186]
**Describe the bug**
ttnn.max op throws `Unsupported dim` error while reducing along the `channel dimension` for 4d input and `batch dimension` for both 4d and 3d input. 

The `Unsupported dim` issue is only thrown when the negative  dimension(i.e -3 for 3d and -4 and -3 for 4d) is passed to ttnn.max dim argument. In ttnn.max op, when the positive dimension(i.e 0 for 3d and 0 and 1 for 4d) is passed to ttnn.max dim argument, it will go into `if (dim[0] == rank - 3) condition` or `else if (dim[0] == 0) condition` block in `ttnn/cpp/ttnn/operations/reduction/generic/generic_reductions.cpp`, which will transpose the batch/channel and height and then call the reduce_impl function again beacause the reduce are only supported in H and W but `if (dim[0] == rank - 3) condition` or `else if (dim[0] == 0) condition` block doesn't work for the negative dimension and negative to positive  dimension conversion are happening after this conditions.

For more context, here is the exact error message
```
E       RuntimeError: TT_THROW @ ../ttnn/cpp/ttnn/operations/reduction/generic/generic_reductions.cpp:250: tt::exception
E       info:
E       Unsupported dim
```

**To Reproduce**
Run the following test:
```
import pytest
import torch
import ttnn
from tests.ttnn.utils_for_testing import assert_with_pcc
from models.utility_functions import torch_random

@pytest.mark.parametrize("input_shape_and_dim", 
                         [
                             ((2, 32, 64, 64),-4),
                             ((2, 22, 37, 41),-4),
                             ((2, 32, 64, 64),-3),
                             ((2, 22, 37, 41),-3),
                             ((2, 32, 64),-3),
                             ((2, 22, 37),-3)
                         ])
def test_max_unsupported_dim(device, input_shape_and_dim):
    
    input_shape, max_dim = input_shape_and_dim
    
    torch_input_tensor = torch_random(input_shape, -100, 100, dtype=torch.bfloat16)
    torch_output_tensor, _ = torch.max(torch_input_tensor, dim=max_dim, keepdim=True)

    input_tensor = ttnn.from_torch(torch_input_tensor, layout=ttnn.TILE_LAYOUT, device=device)

    output_tensor = ttnn.max(input_tensor, dim=max_dim)
    output_tensor = ttnn.to_layout(output_tensor, ttnn.TILE_LAYOUT)
    output_tensor = ttnn.from_device(output_tensor)

    output_tensor = ttnn.to_torch(output_tensor)

    assert_with_pcc(torch_output_tensor, output_tensor)
```

**Expected behavior**
It reduces along the batch and channel dimension when the negative dimension are passed to ttnn.max dim argument.

**Comment by ayerofieiev-tt** [comment]
Hi! Thank you for the report. Makes sense. 
Moving to the owner.

**Comment by bbradelTT** [comment]
It looks like torch accepts up to a negative size:
```
torch.max(torch.ones([2,2,2,2]),-5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Dimension out of range (expected to be in range of [-4, 3], but got -5)
```

I'll look into adjusting the dims to map from negative to positive and let the rest of the code use positive dims.

**Comment by bbradelTT** [comment]
I will fix the unsupported dim issue.

Created https://github.com/tenstorrent/tt-metal/issues/14898 to deal with the failures that occur afterwards.
