### ISSUE TITLE
Llama3.1_8b Bringup

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#13213]
Model Card: [12942](https://github.com/tenstorrent/tt-metal/issues/12942)

Tensor Parallel Implementation of submodules:  
- MLP: [11803](https://github.com/tenstorrent/tt-metal/issues/11803)
- RMS Norm: [11804](https://github.com/tenstorrent/tt-metal/issues/11804) 
- Attention: [11805](https://github.com/tenstorrent/tt-metal/issues/11805) 
- Decoder: [11806](https://github.com/tenstorrent/tt-metal/issues/11806) 

PR: [12899](https://github.com/tenstorrent/tt-metal/pull/12899)
Cookbook: [Llama31_8b_TensorParallel.md](https://github.com/tenstorrent/tt-metal/blob/806fbbed015d314d36d3d730fffca4ff3e369634/models/demos/wormhole/llama31_8b/Llama31_8b_TensorParallel.md)

Issues:
- RMS Norm: [12427](https://github.com/tenstorrent/tt-metal/issues/12427)
- Attention: [12428](https://github.com/tenstorrent/tt-metal/issues/12428)
- Decoder: [12429](https://github.com/tenstorrent/tt-metal/issues/12429)

**Comment by mtairum** [comment]
N300 supported now in main. Check PR https://github.com/tenstorrent/tt-metal/pull/13160 for more details
