### ISSUE TITLE
Support clamping with min/max tensor

### ISSUE THREAD

**Issue by jerrysky3** [tenstorrent/tt-metal#13234]
The op `aten.clamp.Tensor` clamps an input tensor with min and max tensor. While there is `ttnn.clip` to clamp an input tensor with min and max float, it doesn't support tensors as min/max.
https://github.com/tenstorrent/tt-metal/blob/849b3e6d7b9caabcba2898de2381e2f08bcb44f7/ttnn/cpp/ttnn/operations/eltwise/unary/unary_composite.hpp#L105

Currently I couldn't find a corresponding op in `ttnn` for this operation. Therefore I feel like we need to either:

1. Extend the `ttnn.clip` to support min/max tensors
2. Break it down into some ops. E.g., Build masks with `ttnn.lt` and `ttnn.gt`, then use `ttnn.where` to select between the input tensor and min/max tensor.

Before going to 2., which is more complicated and might run slower, I'd like to know if 1. is possible?

**Comment by VirdhatchaniKN** [comment]
Issue addressed in PR https://github.com/tenstorrent/tt-metal/pull/14660

**Comment by VirdhatchaniKN** [comment]
Merged to main, Hence closing issue
