### ISSUE TITLE
Enhance build_metal.sh

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-metal#13258]
# Goals
- Remove redundant documentation that should be in README.md
- Add support for long options
- Add support for `--clean` to remove stale build artifacts
- Add support for `--release`, `--development`, `--debug` as aliases for Release, RelWithDebInfo, Debug build types
- Add support for custom install prefix
- Add support to optionally build tests

**Comment by mbezuljTT** [comment]
@blozano-tt ccache build appears to be broken after this change. is this something you can work on? 🙏
