### ISSUE TITLE
[Issue Report] 224x224 Convolution does not work for Stride 2

### ISSUE THREAD

**Issue by athul-bos-semi** [tenstorrent/tt-metal#13274]
**Describe the bug**
The convolution that works for an image of size 224x224 at stride 1 does not work for Stride 2. STride to causes the following error

**To Reproduce**
1. Download both files from [here](https://github.com/athul-bos-semi/RetinaNet_TTNN)

**Expected behavior**
```
Out of Memory: Not enough space to allocate 3211264 B L1 buffer across 1 banks, where each bank needs to store 3211264 B
```
If you replace the stride value to `[1,1]` in 93, the program works. 

**Screenshots**
![image](https://github.com/user-attachments/assets/cd0ee22e-71e8-4f8d-8905-723bdf033eaa)

**Please complete the following environment information:**
- OS: Metal Devcloud accessed through Ubuntu 22.04 client
- Device: Wormhole B0
- Version of software: TT-Metal v0.52.0

**Additional context**
The Bottleneck model in line 106 works fine. If you need to test it, just make sure to uncomment all values from line 14 to 24.

**Comment by pavlejosipovic** [comment]
Hi @athul-bos-semi this test case is not passing on main.
I've made a branch where I ported this test-case on latest code https://github.com/tenstorrent/tt-metal/tree/pjosipovic/13274
Commit that made a difference is 819d1341b78da0e95a09e7d5ecaacf48ad7aab09
Let me know if this resolve the issue for you.

**Comment by pavlejosipovic** [comment]
@athul-bos-semi can we close this issue?

**Comment by athul-bos-semi** [comment]
Yes, thank you
