### ISSUE TITLE
[Feature Request] Support model Qwen2-7B in the model demos

### ISSUE THREAD

**Issue by cthsieh** [tenstorrent/tt-metal#13277]
* Goal: Run model [Qwen2-7B](https://huggingface.co/Qwen/Qwen2-7B) on the TT Wormhole device.
* Changes: Add this directory `models/demos/wormhole/qwen2_7b`.

## Approach

We will leverage the existing implementation of [Mistral-7B](https://github.com/tenstorrent/tt-metal/tree/main/models/demos/wormhole/mistral7b), which has a similar architecture and has already been successfully deployed on the device.

By comparing the architectural differences between the two models, we identified the differences between Mistral-7B and Qwen2-7B, then will incrementally modify the implementation to support Qwen2-7B. The five major differences we found are:

1. Model configuration (tensor dimensions)
1. Bias of Q, K, and V projections
1. RoPE (Rotary Position Embeddings)
1. Tokenizer
1. Weight format

Each of these differences will be adjusted accordingly in the Qwen2-7B model implementation.

### Model Configuration

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-47a34ed8-7fff-bad6-1f00-e5fbbb2ecf8c"><div dir="ltr" style="margin-left:0pt;" align="left">
Parameters | Mistral-7B | Qwen2-7B
-- | -- | --
Number of layers | 32 | 28
Hidden size | 4096 | 3584
Number of attention heads | 32 | 28
Number of K, V heads | 8 | 4
Intermediate size of MLP | 14336 | 18944
Vocabulary size | 32000 | 152064

</div></b>

### Bias of Q, K, and V Projections

The following table shows the weight tensor names and their shapes, which comes from `state_dict` of both the models. You can find that Qwen2-7B has 3 additional bias tensors for Q, K, and V projections compared to Mistral-7B. 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-c911ab44-7fff-2508-d99c-68e1437dac3e"><div dir="ltr" style="margin-left:0pt;" align="left">
Mistral-7B weight name | Shape | Qwen2-7B weight name | Shape
-- | -- | -- | --
tok_embeddings.weight | [32000, 4096] | model.embed_tokens.weight | [152064, 3584]
norm.weight | [4096] | model.norm.weight | [3584]
output.weight | [32000, 4096] | lm_head.weight | [152064, 3584]
layers.0.attention_norm.weight | [4096] | model.layers.0.input_layernorm.weight | [3584]
layers.0.attention.wq.weight | [4096, 4096] | model.layers.0.self_attn.q_proj.weight | [3584, 3584]
N/A | N/A | model.layers.0.self_attn.q_proj.bias | [3584]
layers.0.attention.wk.weight | [1024, 4096] | model.layers.0.self_attn.k_proj.weight | [512, 3584]
N/A | N/A | model.layers.0.self_attn.k_proj.bias | [512]
layers.0.attention.wv.weight | [1024, 4096] | model.layers.0.self_attn.v_proj.weight | [512, 3584]
N/A | N/A | model.layers.0.self_attn.v_proj.bias | [512]
layers.0.attention.wo.weight | [4096, 4096] | model.layers.0.self_attn.o_proj.weight | [3584, 3584]
layers.0.feed_forward.w1.weight | [14336, 4096] | model.layers.0.mlp.gate_proj.weight | [18944, 3584]
layers.0.feed_forward.w2.weight | [4096, 14336] | model.layers.0.mlp.down_proj.weight | [3584, 18944]
layers.0.feed_forward.w3.weight | [14336, 4096] | model.layers.0.mlp.up_proj.weight | [18944, 3584]
layers.0.ffn_norm.weight | [4096] | model.layers.0.post_attention_layernorm.weight | [3584]

</div></b>

### RoPE

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-2f6c4d0e-7fff-7e6c-946a-e2b8a5b33c1a"><div dir="ltr" style="margin-left:0pt;" align="left">
  | Mistral-7B | Qwen2-7B
-- | -- | --
RoPE type | Standard RoPE | Dynamic RoPE

</div></b>

Dynamic RoPE is an advanced version of the standard Rotary Positional Embeddings (RoPE). It addresses the limitations of standard RoPE when dealing with variable-length sequences, particularly when models are required to handle both very short and very long contexts efficiently. 

Key differences:
* Standard RoPE:
  * In standard RoPE, the rotation angle (θ) is fixed and directly depends on the token position. The rotational transformation uses a predefined scaling (like fixed frequency parameters) across the sequence.
  * The embedding does not adapt dynamically, which can lead to issues when handling sequences much longer than those seen during training.
* Dynamic RoPE:
  * Dynamic RoPE introduces a dynamic scaling factor or adaptive rotation that adjusts based on the sequence length or other context-specific conditions.

### Tokenizer

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-16ed8355-7fff-73fa-eee1-21884a91390f"><div dir="ltr" style="margin-left:0pt;" align="left">
  | Mistral-7B | Qwen2-7B
-- | -- | --
Library | `sentencepiece` | `transformers`
Module | `SentencePieceProcessor` | `AutoTokenizer`

</div></b>

### Weight Format

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-1bc70060-7fff-af44-4db5-9e5f62b6d0bf"><div dir="ltr" style="margin-left:0pt;" align="left">
  | Mistral-7B | Qwen2-7B
-- | -- | --
Format | `.pt` | `.safetensors`

</div></b>

The safetensors format is a lightweight and secure format for storing tensors, developed to provide an alternative to PyTorch's .pt or .pth files. To load safetensors files, you should use the safetensors library.

**Comment by uaydonat** [comment]
fyi @cglagovichTT

**Comment by cglagovichTT** [comment]
Is it possible that dynamic ROPE can be supported by generating rotary embeddings on the host based on the sequence length? Would this allow you to use dynamic ROPE without changing any kernels?
