### ISSUE TITLE
Investigate mamba nightly single-card tests hanging after LLK change to remove race condition

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#13292]
https://github.com/tenstorrent/tt-metal/commit/71b359a05de81b70057d49187e7d8ac03d144997

last pass: https://github.com/tenstorrent/tt-metal/actions/runs/11080894657
next fail, which only has CI infra changes + @rdjogoTT 's commit: https://github.com/tenstorrent/tt-metal/actions/runs/11081600775

**Comment by tt-rkim** [comment]
Owner of this model is @esmalTT and @kpaigwar

**Comment by tt-rkim** [comment]
@rdjogoTT should we keep this open for your work, or do you have another issue you'd rather use to tie to your commit messages?

**Comment by rdjogoTT** [comment]
@tt-rkim closing this is fine
