### ISSUE TITLE
Fast Dispatch Nightly CI Problem for Llama 3.1 8B

### ISSUE THREAD

**Issue by caixunshiren** [tenstorrent/tt-metal#13294]
### Issue
When running the Nightly Fast Dispatch CI pipeline on PR https://github.com/tenstorrent/tt-metal/pull/13205, the following two test cases on decoder prefill always timeout for 300s:

```
FAILED tests/nightly/single_card/llama31_8b/models/demos/wormhole/llama31_8b/tests/test_llama_decoder_prefill.py::test_llama_decoder_inference[4096]
FAILED tests/nightly/single_card/llama31_8b/models/demos/wormhole/llama31_8b/tests/test_llama_decoder_prefill.py::test_llama_decoder_inference[128]
```

However, other pipelines that contains those test cases or bigger model level test cases has passed. Namely, the All Post Commit pipeline, Single Card Demo, and Single Card Perf has all passed. It is also worth noting that the pr did not change anything for the prefill version running on these test cases.

In addition, when running locally on single WH machines or T3K machines, these tests always pass and run way below the timeout limit. @mtairum also tried disable every tests in Nightly Fast Dispatch CI except for those two, and he consistently gets the later one timeout ([4096] passing, [128] timeout).

We suspect that these might be CI issues? @tt-rkim

**Comment by tt-rkim** [comment]
First, let's see if we can reproduce it on the CI system itself.

I have custom dispatched: https://github.com/tenstorrent/tt-metal/actions/runs/11112123500

And this happens for both N150 N300, and all the time?

**Comment by tt-rkim** [comment]
It's possible there is persistent state from previous tests

**Comment by caixunshiren** [comment]
Thanks Raymond. Yes. This happens for both N150 and N300, all the time.

**Comment by tt-rkim** [comment]
changed link, syntax error originally

**Comment by tt-rkim** [comment]
ah shit my bad - will kick off another one your branch. might as well https://github.com/tenstorrent/tt-metal/actions/runs/11113231491

**Comment by mtairum** [comment]
Adding some additional info.

It does look like that there is some bad state leftover that this particular test is picking upon.
When running just the isolated test (twice since it has two parameters) we see that the first run actually passes but the second fails:

```
PASSED tests/nightly/single_card/llama31_8b/models/demos/wormhole/llama31_8b/tests/test_llama_decoder_prefill.py::test_llama_decoder_inference[4096]
FAILED tests/nightly/single_card/llama31_8b/models/demos/wormhole/llama31_8b/tests/test_llama_decoder_prefill.py::test_llama_decoder_inference[128]
```

Pipeline here: https://github.com/tenstorrent/tt-metal/actions/runs/11110224223/job/30868080740

**Comment by tt-rkim** [comment]
Hmm - but if you run the isolated test file locally, it does not fail?

**Comment by mtairum** [comment]
Correct. Running locally, either isolated or in the test batch like in CI, it passes.

**Comment by tt-rkim** [comment]
Can you try on a cloud VM then?

**Comment by mtairum** [comment]
Tried on a cloud VM. Same issue. 

If I run the two tests one after the other the second gets Killed.
```
$ pytest tests/nightly/single_card/llama31_8b/models/demos/wormhole/llama31_8b/tests/test_llama_decoder_prefill.py
```

I noticed that if we reduce the max_batch_size to 1 the tests pass successfully, as seen in this pipeline: https://github.com/tenstorrent/tt-metal/actions/runs/11126752821/job/30918318682

I also fixed how we call the batch size but that didn't change the CI behaviour.

Further analysis shows that the process runs out of memory:
```
[975018.930671] Out of memory: Killed process 556325 (pytest) total-vm:45470180kB, anon-rss:39316460kB, file-rss:0kB, shmem-rss:20kB, UID:1000 pgtables:78988kB oom_score_adj:0
[975863.831145] Out of memory: Killed process 561813 (pytest) total-vm:47932756kB, anon-rss:39371620kB, file-rss:3160kB, shmem-rss:20kB, UID:1000 pgtables:79204kB oom_score_adj:0
[976505.052316] Out of memory: Killed process 567017 (pytest) total-vm:48130896kB, anon-rss:39412928kB, file-rss:3080kB, shmem-rss:20kB, UID:1000 pgtables:79280kB oom_score_adj:0
```

I tried forcing the garbage collector at the end and deleting the reference model, but no luck.

@tt-rkim any hints on why we see this on the VMs?

**Comment by tt-rkim** [comment]
thank you!!
