### ISSUE TITLE
Runtime error: valid_page_size issue with the maxpool configuration for Vanilla UNet.

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#13336]
**Describe the bug**
Experiencing a valid page_size issue in the maxpool operation for a configuration of Vanilla U-Net.

Configuration:- 
Input shape - [1, 256, 60, 80] (NCHW)
kernel_size= (2,2)
padding=(0, 0)
stride=(2, 2)
dilation=(1,1)

**To Reproduce**
1. Checkout to branch [punith/vanilla_unet_maxpool_issue](https://github.com/tenstorrent/tt-metal/compare/main...punith/vanilla_unet_maxpool_issue)
2. Run command, `pytest tests/ttnn/unit_tests/operations/test_maxpool2d.py::test_run_max_pool_vanilla_unet`

**Expected behavior**
It should pass without any issue.

**Screenshots**
```
E       RuntimeError: TT_FATAL @ ../tt_metal/impl/buffers/buffer.cpp:38: valid_page_size
E       info:
E       For valid non-interleaved buffers page size 40 must equal buffer size 2528. For interleaved-buffers page size should be divisible by buffer size
```

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Device: WH-n150

**Comment by punithsekar** [comment]
fyi @saichandax

**Comment by dvartaniansTT** [comment]
by rebasing to main, I was able to resolve this issue @punithsekar . 
I will close the issue now. cc: @mbahnasTT
