### ISSUE TITLE
Retire legacy script `build_with_profiler_opt.sh`

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-metal#13352]
We can now retire this from the repo:

https://github.com/tenstorrent/tt-metal/blob/main/scripts/build_scripts/build_with_profiler_opt.sh

It is only used in one workflow, and its usage can be replaced by either `build_metal.sh` or with direct CMake usage.

cc: @mo-tenstorrent

**Comment by blozano-tt** [comment]
> `build_metal.sh` is not building programming examples. `build_with_profiler_opt.sh` does.
> 
> Can we add building programming examples as an option too? `cmake --build build --target programming_examples`
> 
> `build_with_profiler_opt.sh` is referenced at multiple places in docs. Docs assume programming examples are built as well.

Good catch.

Is there no
‘add_subdirectory(programming_examples)’ anywhere?

I think it’s a good idea to add an option for that.

**Comment by mo-tenstorrent** [comment]
Searched `build_metal.sh` and didn't find anything.
