### ISSUE TITLE
[GH Permissions] A team of compiler engineers

### ISSUE THREAD

**Issue by jdh8** [tenstorrent/tt-metal#13383]
## What you are trying to do...
We are working on this project for miscellaneous improvements and to enable more conversions in [`pytorch2.0_ttnn`](https://github.com/tenstorrent/pytorch2.0_ttnn).  We have made a couple of pull requests and opened dozens of issues.  It would be great convenience to grant us writing permissions so that we can:

- Label issues and PRs
- Run CI tests to fix code proactively

## Who needs permissions...
@jerrysky3 and me

**Comment by ayerofieiev-tt** [comment]
Hi! Working on this. Will update you tomorrow.

**Comment by jdh8** [comment]
Closing this issue after both of us have joined the team
