### ISSUE TITLE
T3K Frequent Failing On Main (t3k ethernet tests)

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#13432]
The t3k frequent ethernet tests group recently started failing: https://github.com/tenstorrent/tt-metal/actions/runs/11158163501/job/31014420451

This issue tracks the resolution of this regression.

**Comment by SeanNijjar** [comment]
Reassigning to @cfjchu as he volunteered to fix this :)

**Comment by cfjchu** [comment]
merged into main
