### ISSUE TITLE
Add support to ttnn async for executing models in threads other than the main thread

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#13447]
This is required by vLLM (as a result of https://github.com/tenstorrent/vllm/issues/15) since it attempts to execute TT models in threads other than the main thread when serving.

**Comment by tt-asaigal** [comment]
Changes merged @ https://github.com/tenstorrent/tt-metal/commit/34f1b629f4d4356455ccbaf63f81bf9c8f4ae9f3 should allow you to call TTNN async APIs from a forked thread.

**Comment by skhorasganiTT** [comment]
vLLM async model execution works with your changes, thanks a lot Aditya
