### ISSUE TITLE
Monitor and tweak Nightly FD pgm dispatch perf requirements

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#13441]
We have an issue where due to instability on hosts, even if we loop kernels for pgm dispatch benchmarks on the device, we can still get large variance in perf measurements.

We should ideally be looping on the host-side multiple times to reduce variance and flakiness. This will cause problems locally for people running this test, as well.

**Comment by tt-rkim** [comment]
Example: https://github.com/tenstorrent/tt-metal/actions/runs/11165451201/job/31041549829

**Comment by pgkeller** [comment]
is this still an issue?

**Comment by aliuTT** [comment]
With John's latest golden results, this is probably not relevant. I had this issue open as a generic tag for github commits. Closing issue.
