### ISSUE TITLE
eltwise ops fail PCC when broadcasting [GS][WH]

### ISSUE THREAD

**Issue by kkeerthana0573** [tenstorrent/tt-metal#13464]
**Describe the bug**

1. ttnn.add fails with "Low Pcc" in Whisper model.

> Input shapes of tensor_a : [8, 1500 [1504], 512] and tensor_b : [1500 [1504], 512]

> **On GS(e150):**
  > `E       AssertionError: 0.20598982372530486`
> **On WH(n300):**
  > `E       AssertionError: 0.17328692806300294`

**To Reproduce**

1. Pick the test from the [commit](https://github.com/tenstorrent/tt-metal/compare/main...keerthana/whisper_add_testcase).
2. Run `pytest tests/ttnn/unit_tests/operations/test_add.py::test_whisper_add`.

**Expected behavior**
Expected to pass the test case.

**Please complete the following environment information:**

- OS: [e.g. Ubuntu 20.04]
- Devices: GS(e150), WH(n300)

**Comment by yieldthought** [comment]
I believe this is because broadcasting is not supported, we also see this bringing up llama 3.2 with the following test failing for all elementwise ops:

```
@pytest.mark.parametrize(
    "dtype",
    [
        ttnn.bfloat16,
    ],
    ids=[
        "bfloat16",
    ],
)
@pytest.mark.parametrize(
    "test_func_name, torch_func_name",
    [(ttnn.add, torch.add), (ttnn.sub, torch.sub), (ttnn.mul, torch.mul)],
)
def test_run_elt_binary_broadcast(dtype, test_func_name, torch_func_name, device):
    b, nh, s, d = 1, 8, 32, 128
    shape_a = (b, nh, s, d)
    shape_b = (b, 1, s, d)

    torch.manual_seed(10)

    mem_config = ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)

    in0 = torch.randn(shape_a).bfloat16().float()
    in1 = torch.randn(shape_b).bfloat16().float()
    in0_t = torch2tt_tensor(in0, device, tt_memory_config=mem_config, tt_dtype=dtype)
    in1_t = torch2tt_tensor(in1, device, tt_memory_config=mem_config, tt_dtype=dtype)

    out_t = test_func_name(in0_t, in1_t)
    out = tt2torch_tensor(out_t)

    passing, output = comp_pcc(out, torch_func_name(in0, in1), 0.9999)
    logger.info(output)
    assert passing
```

**Comment by yieldthought** [comment]
Suggest we rename the issue to "ttnn binary elementwise ops fail with bad pcc when broadcasting"

**Comment by eyonland** [comment]
This is related to #13643 in that we are not truly doing broadcasting properly.  We need kernel development on this effort.  Going to see where we can prioritize this work.

**Comment by KalaivaniMCW** [comment]
FYI @kkeerthana0573, 
tested the shapes mentioned in this issue on the latest main. 
<img width="1187" alt="image" src="https://github.com/user-attachments/assets/60552c73-46b3-4a8c-99eb-ddd7f9875e75">

**Comment by kkeerthana0573** [comment]
@KalaivaniMCW, 
Thanks for the workaround.

**Comment by KalaivaniMCW** [comment]
@kkeerthana0573 shall I close this issue ?

**Comment by kkeerthana0573** [comment]
@KalaivaniMCW, 
We proceeded with the workaround, so there’s no blocker now. However, the underlying broadcasting issue remains unresolved. This issue can be closed since it’s no longer blocking.

**Comment by KalaivaniMCW** [comment]
@kkeerthana0573 Yes https://github.com/tenstorrent/tt-metal/issues/13643 is still in progress and being tracked. 
Thanks.

**Comment by KalaivaniMCW** [comment]
Closed with workaround
https://github.com/tenstorrent/tt-metal/issues/13643 is still in progress
