### ISSUE TITLE
2CQ with Trace hangs on Galaxy

### ISSUE THREAD

**Issue by ubcheema** [tenstorrent/tt-metal#13482]
2CQ support has been enable on Galaxy.
When running tests that use 2CQs with trace I have observed hangs.

Passes: `pytest models/demos/t3000/resnet50/tests/test_perf_e2e_resnet50.py::test_perf_2cqs`

Hangs: `pytest models/demos/t3000/resnet50/tests/test_perf_e2e_resnet50.py::test_perf_trace_2cqs[wormhole_b0-True-16-True-0.0043-60-device_params0]`

TTNN 2 cq trace test also hangs: `pytest tests/ttnn/unit_tests/test_multi_device_trace.py`

All of these were tried on Galaxy machine.

**Comment by tt-asaigal** [comment]
Changes staged @ https://github.com/tenstorrent/tt-metal/pull/13484 should resolve the 2 CQ Trace hangs for TG. Also adding a test to regress on this feature.
