### ISSUE TITLE
Make MatmulMultiCoreReuseMultiCastDRAMShardedProgramConfig work with BH

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-metal#13487]
MatmulMultiCoreReuseMultiCastDRAMShardedProgramConfig assumes 12 DRAM banks.

However, BH has 8 DRAM banks.

Therefore, need to update the logic to handle 8 DRAM banks as well.

**Comment by yugaoTT** [comment]
closing as merged
