### ISSUE TITLE
[Bug] ttnn.conv fails with low pcc when changing shard_grid

### ISSUE THREAD

**Issue by bosGlee** [tenstorrent/tt-metal#13570]
Explanation

I'm trying to change 1d_systolic_convolution's shard grid.
What I expected is activation's size is small enough to run in GS, that should be run on WH with same shard_grid.

But I found that some parameters in conv2d is strongly connected with grid_size of chip, so it doesn't work. (pcc test fail)

For example, CoreGrid(0,0) and CoreGrid(7,3) works in WH. (Because it uses 0-7 grid for x)
But not work with GS because x.grid for GS is larger than 7.

My Guess : 

Inside device/multi_core_optimized_conv_sharded/optimized_conv_op_sharded_v2.cpp, 
there are mcast weights algorithms.
What I think is red box across cores. But if mcast contains blue block, pcc test might fail. 

![image](https://github.com/user-attachments/assets/0d3ce4e8-e07a-4b18-aea5-07c9879087e8)

**To Reproduce**
1. Go to /tt-metal/tests/ttnn/unit_tests/operations/test_new_conv2d.py::run_conv
2. Add override config options to run_conv . In this case, 248 and 246 use 24 cores but their shapes are different.
```
    if config_override and "num_cores_nhw" in config_override:
        if config_override["num_cores_nhw"] == 98:
            conv_config.core_grid = change_by_your_chip
            conv_config.override_sharding_config = True
            print("Setting num_cores_nhw to 98")
        elif config_override["num_cores_nhw"] == 248:
            conv_config.core_grid = ttnn.CoreRangeSet({ttnn.CoreRange((0, 0), (7, 2))})
            conv_config.override_sharding_config = True
            print("Setting num_cores_nhw to 24 with coregird (8,3)")
        elif config_override["num_cores_nhw"] == 246:
            conv_config.core_grid = ttnn.CoreRangeSet({ttnn.CoreRange((0, 0), (5, 3))})
            conv_config.override_sharding_config = True
            print("Setting num_cores_nhw to 24 with coregird (6,4)")
```
3. Make some 1d systolic convolutions and see errors
Such as 
```
        (1, 3, 32, 192, 192, 3, 3, 2, 2, 1, 1, 1, True, {"act_block_h": 32}, False),  """good"""
        (1, 3, 32, 192, 192, 3, 3, 2, 2, 1, 1, 1, True, {"act_block_h": 32,"num_cores_nhw" : 248}, False),  # assert True, but False in GS
        (1, 3, 32, 192, 192, 3, 3, 2, 2, 1, 1, 1, True, {"act_block_h": 32,"num_cores_nhw" : 246}, False),  # assert False GS and WH
```

**Screenshots**
![image](https://github.com/user-attachments/assets/cf7f9f91-61a0-48b0-9882-cbdebffe1456)
**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software  tt-metal v52

I think it needs an assert.

**Comment by jvasilje** [comment]
@mywoodstock @pavlejosipovic this is a P0 bug, identified by the customer team.

**Comment by mywoodstock** [comment]
@bosGlee WIth height sharding, the shards are assigned to the cores in row-major fashion (as correctly depicted in your image). We do not support a smaller sub-grid in this mode.
Could you please elaborate on your use case where one would need sub-grid with height sharding instead of full grid row major?

**Comment by bosGlee** [comment]
@mywoodstock 
Thanks for an answer.

I test how self-made model works when a number of compute cores are limited.
For example, if I use 20 cores, height_shard convolution's shard shape would be (0,0)-(1,8) || ((2,0)-(2,3)
But block_shard convolution's shard shape is (0,0)-(3,4), which causes data movement... 

It seems better to endure the data movement and use the current function.
Thanks!

P.S.  I see that matmul function uses dram sharding.
Are there any plans to implement DRAM-sharded convolution, where weights are fetched using DRAM-shard?

**Comment by mywoodstock** [comment]
@bosGlee OK!
And yes, we will have dram sharded convs, but first for act only, then we will look at weights.

**Comment by Spstars** [comment]
Yes, thanks for an answer.

**Comment by mbahnasTT** [comment]
@Spstars thanks!
