### ISSUE TITLE
Binary Bitwise ops

### ISSUE THREAD

**Issue by KalaivaniMCW** [tenstorrent/tt-metal#13582]
Op Requirement :
ElemwiseBinary/ELEMWISE_BINARY_BITWISEAND
ElemwiseBinary/ELEMWISE_BINARY_BITWISEOR
ElemwiseBinary/ELEMWISE_BINARY_BITWISEXOR

Unary bitwise ops were implemented https://github.com/tenstorrent/tt-metal/pull/9437 , https://github.com/tenstorrent/tt-metal/pull/9436  using their respective operators ( ~ , & , | )  But the same method cannot be used in binary.

ref: https://tenstorrent.slack.com/archives/C07NTNN3QSK/p1727452697738579

**Comment by amahmudTT** [comment]
@KalaivaniMCW this is needed for all the architectures right ?

**Comment by KalaivaniMCW** [comment]
> @KalaivaniMCW this is needed for all the architectures right ?

@amahmudTT at present, bitwise ops are supported for Wormhole and Blackhole, not Grayskull.

**Comment by rtawfik01** [comment]
@ttmtrajkovic fyi. They want to implement binary bitwise operations, which would require copying tiles from each SrcA & B into the dest. Values in SrcA would be bit operated on by values in SrcB.

**Comment by staylorTT** [comment]
@amahmudTT Do we have an update on this issue?

**Comment by rdjogoTT** [comment]
@staylorTT With the work on this issue: https://github.com/tenstorrent/tt-metal/issues/15122, we will add support for binary SFPU ops, which will enable us to implement bitwise binary ops as well. That issue should be closed this week, and we can start work on this soon after.

**Comment by rdjogoTT** [comment]
@KalaivaniMCW Can this be closed?

**Comment by KalaivaniMCW** [comment]
Merged to main
