### ISSUE TITLE
[Bug Report]   thread_local  cached_program_command_sequences is never cleaned

### ISSUE THREAD

**Issue by dmakoviichuk-tt** [tenstorrent/tt-metal#13588]
**Describe the bug**
Here is
`    thread_local static std::unordered_map<uint64_t, CachedProgramCommandSequence> cached_program_command_sequences;
`
in the command_queue.hpp  which is never cleaned up but populated.
As result it is a memory leak in the app especially when 
**To Reproduce**
Run anything without cache for some time. And print size of the cached_program_command_sequences, you can see it only grows.

**Expected behavior**
It should not have programs which are never going to be used.

**Additional context**
Overall using static or thread_local variables is 99% a wrong decision. It should be fixed by removing this map.
For example if it is thread_local it is probably belongs to the Device class.
It caused a lot of issues and couple days of debugging to find a memory leak.
It should be fixed ASAP.
cc @pgkeller

**Comment by tt-aho** [comment]
This is a known issue that was going to be addressed/moved with SubCoreMesh changes to be made local to an object so it can get cleared. Is this really a P0 that needs to be resolved immediately? What is the use case for users to run long running applications without program cache?

**Comment by tt-aho** [comment]
Had an offline sync with @dmakoviichuk-tt, there are some program cache bugs that was preventing its usage, which is why this issue was hit. I can split out the changes for this from the overall SubCoreMesh changes to allow this to be addressed earlier.

**Comment by tt-aho** [comment]
Should be addressed with [53b60f4](https://github.com/tenstorrent/tt-metal/commit/53b60f494e5e9540b7149aa5d6e924e4ac09f3df) which makes the mapping local to the program, so it'll get cleared when a program is destructed. Closing as this should be resolved, can reopen if issues still persist.
