### ISSUE TITLE
Dispatch_s Optimization: Coalesce CQ_DISPATCH_NOTIFY_SLAVE_GO_SIGNAL into CQ_DISPATCH_CMD_WAIT

### ISSUE THREAD

**Issue by tt-asaigal** [tenstorrent/tt-metal#13612]
The `Dispatch_d` -> `Dispatch_s` handshake consists of `Dispatch_d` updating a free running counter on `Dispatch_s` to notify it that its safe to send a go signal.

This handshake is done using the `CQ_DISPATCH_NOTIFY_SLAVE_GO_SIGNAL` command (`add_notify_dispatch_s_go_signal_cmd` in `device_commands.hpp`), which follows a write barrier on `Dispatch_d`. The write barrier is implemented using the `CQ_DISPATCH_CMD_WAIT` command, which ensures that the program config sent by `Dispatch_d` has been committed to worker L1. This ensures that the go signal sent by `Dispatch_s` corresponds to valid data in L1.

Given that Prefetcher can be a bottleneck and that the notification command should always follow a write barrier, we should coalesce these commands to decrease Prefetcher overhead caused by parsing and relaying separate commands. This can be done as follows:

1. Modify `CQDispatchWaitCmd` with an additional flag as follows:

```
struct CQDispatchWaitCmd {
    uint8_t barrier;          // if true, issue write barrier
    uint8_t notify_prefetch;  // if true, inc prefetch sem
    uint8_t clear_count;      // if true, reset count to 0
    uint8_t wait;             // if true, wait on count value below
-   uint8_t pad1;
+   uint8_t notify_dispatch_s; // if true, update the free running counter on dispatch_s   
    uint16_t pad2;
    uint32_t addr;            // address to read
    uint32_t count;           // wait while address is < count
} __attribute__((packed));
```

2. Pipe this flag to an argument in `add_dispatch_wait`:

```
void add_dispatch_wait(
        uint8_t barrier, uint32_t address, uint32_t count, uint8_t clear_count = 0, bool notify_prefetch = false, bool do_wait = true, uint8_t dispatcher_type = 0, bool notify_dispatch_s = false)
```

3. Modify the wait command sent to `Dispatch_d` before the `Dispatch_s` notification to have `notify_dispatch_s = true`

4. Modify the `process_wait()` function in `cq_dispatch.cpp` to check the `notify_dispatch_s` flag and execute `process_notify_dispatch_s_go_signal_cmd()` if its set.

5. Remove all references to the `CQ_DISPATCH_NOTIFY_SLAVE_GO_SIGNAL` command and ensure that its not sent to `Dispatch_d` from host.

**Comment by tt-asaigal** [comment]
fyi @pgkeller please reassign as you see fit

**Comment by arikTT** [comment]
@tt-asaigal I'm still learning the code, but I looked up the calls to `add_notify_dispatch_s_go_signal_cmd`, one of them is indeed happening after the wait, but there is another call in `EnqueueTraceCommand::process()` that isn't preceded with a wait command. Can we still safely remove all references to the command? Should I add a call to the new wait in there?

**Comment by pgkeller** [comment]
@tt-asaigal can you answer the above?

**Comment by tt-asaigal** [comment]
Previously synced with @arikTT offline. Please let me know if there are additional questions. Thanks

**Comment by pgkeller** [comment]
I'm going to augment this task: we are now using 5 flags in uint8s.  That's 5 loads from L1, presumably followed by uses, so 30 cycles which is getting expensive.  The new thing add: pack all the bools into 1 uint8 w/ 1 load, and use a mask to see if the bit is set.  This will reduce to 1 load and andimmediate which will be much faster (when we don't have wait)

**Comment by tt-asaigal** [comment]
> I'm going to augment this task: we are now using 5 flags in uint8s. That's 5 loads from L1, presumably followed by uses, so 30 cycles which is getting expensive. The new thing add: pack all the bools into 1 uint8 w/ 1 load, and use a mask to see if the bit is set. This will reduce to 1 load and andimmediate which will be much faster (when we don't have wait)

We should probably add an enum defining the flags in `cq_commands.hpp` for this:

```
enum WaitCmdFlags : uint8_t {
    CLEAR_COUNT = 0x1,
    BARRIER = 0x2,
    NOTIFY_PREFETCH = 0x4,
    WAIT = 0x8,
    NOTIFY_DISPATCH_S = 0x10,
}
```

The flags can be assembled in the `add_dispatch_wait` fn based on the arguments.

**Comment by arikTT** [comment]
After some further review and discussion, we decided to coalesce the wait into `CQ_DISPATCH_NOTIFY_SLAVE_GO_SIGNAL` instead of the other way as originally planned. This makes the logic simpler, and doesn't overload `wait` with more functionality.
