### ISSUE TITLE
ttnn.lgamma operation does not work bfloat8_b

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#13626]
ttnn.lgamma operation does not work when input tensor is bfloat8_b. Documentation does not mention that limitation.

Steps to reproduce

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/eltwise/unary/lgamma.py`. To run:

```
python3 tests/sweep_framework/runner.py --elastic cloud --module-name eltwise.unary.lgamma
```

Sweep is xfail.

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by mcw-anasuya** [comment]
Merged to main, hence closing this issue.
