### ISSUE TITLE
ttnn.max_pool2d fails in lenet model.

### ISSUE THREAD

**Issue by sabira-mcw** [tenstorrent/tt-metal#13624]
**Describe the bug**
ttnn.max_pool2d fails with shape (1, 6, 28, 28) in  NCHW format. 

"The test is skipped with "Current maxpool writer needs nchannels to be multiple of 16!"
>  E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/data_movement/sharded/interleaved_to_sharded/device/interleaved_to_sharded_op.cpp:23: (*this->output_mem_config.shard_spec).shape[1] * input_tensor.element_size() % hal.get_alignment(HalMemType::L1) == 0
> E       info:
> E       Shard page size must currently have L1 aligned page size
> 

**To Reproduce**
1. Pick the test from [Commit](https://github.com/tenstorrent/tt-metal/compare/main...sabira/max_pool_unit_test)
2. Run `pytest tests/ttnn/unit_tests/operations/test_maxpool.py::test_run_max_pool`

**Expected behavior**
Expected to pass the test case.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Devices: GS, WH

**Comment by saichandax** [comment]
@boris-drazic , this issue is blocker for Lenet model. Can we assign it to someone?

**Comment by mywoodstock** [comment]
@sabira-mcw @saichandax This is a limitation in the op that channels need to be 16 or multiple. To get around this, you will need to pad the channels dim to 16.

**Comment by sabira-mcw** [comment]
Closing this issue, as padding the channels to 16 resolved the problem.
