### ISSUE TITLE
[Bug Report] ttnn.concat - Tile padding along concatenated dim is not supported 

### ISSUE THREAD

**Issue by chandrasekaranpradeep** [tenstorrent/tt-metal#13667]
**Describe the bug**
The ttnn.concat op throws `Tile padding along concatenated dim (3) not supported for concat yet (tensor: 0)` error when the tuple of two input tensor of same shape (1, 32, 12, 50) are passed with concat dim = -1. The above error is thrown while validating the input tensor of the concat op in the `ttnn::operations::data_movement::ConcatDeviceOperation::validate` function.

For more context, here is the exact error message:
```
E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/data_movement/concat/device/concat_device_operation.cpp:43: !in_ref.get_shape().has_tile_padding(this->dim)
E       info:
E       Tile padding along concatenated dim (3) not supported for concat yet (tensor: 0).
```
**To Reproduce**
Run the following test:

```
import torch
import ttnn
from tests.ttnn.utils_for_testing import assert_with_pcc

def test_concat_rotary_embedding(device):
    concat_dim = 3
    torch_input_tensor_a = torch.rand((1, 32, 12, 50), dtype=torch.float32)
    torch_input_tensor_b = torch.rand((1, 32, 12, 50), dtype=torch.float32)
    torch_output_tensor = torch.concat([torch_input_tensor_a, torch_input_tensor_b], dim=concat_dim)

    input_tensor_a = ttnn.from_torch(torch_input_tensor_a, layout=ttnn.TILE_LAYOUT, device=device)
    input_tensor_b = ttnn.from_torch(torch_input_tensor_b, layout=ttnn.TILE_LAYOUT, device=device)

    output = ttnn.concat([input_tensor_a, input_tensor_b], dim=concat_dim)
    output = ttnn.to_torch(output)

    assert_with_pcc(torch_output_tensor, output, 0.9999)
```

**Comment by ntarafdar** [comment]
@jaykru-tt can you see if this has been covered by the concat merge you did ?

**Comment by jvasilje** [comment]
Did not hear back reason for P0 label. Setting to P1.

**Comment by jvasilje** [comment]
@ntarafdar let's update the Forge team on the status on this issue. :)

**Comment by ntarafdar** [comment]
This can be cherry-picked right now in Jay's branch. He is currently trying to push this in through CI and running into perf issues (allocater).  https://github.com/tenstorrent/tt-metal/pull/14306

Need to investigate if this is infra issue or issue in concat.


Let us know if cherry-picking will work in meantime, Jay will be back next Wednesday to push it in.
If not we can assign someone this in the mean time

**Comment by tt-mpantic** [comment]
Hi Naif, thanks for the update. At the moment we are consuming only metal main so we can't consume custom branch that you shared and we will wait for fix to land on main. I understand that it takes some time to get this in and it is fine, important part if that this is being worked on with priority. 
Assigning someone else at this point seems inefficient. Wednesday sounds fine.

**Comment by dgolubovicTT** [comment]
Any updates on this one? We are still blocked on Llama bringup due to this.

**Comment by ntarafdar** [comment]
@jaykru-tt is back to work on this. He has seen unexpected bugs related to perf tests of models due to concat allocating large tensors. His eta to get this fixed and in is tomorrow.

**Comment by ntarafdar** [comment]
just wanted to give context on this bug on the turn around time.

Concat allocates really big tensors and this shows up an unrelated bug due to allocation that @jaykru-tt should have a fix for.
Unfortunately it only shows up in a large e2e test that shows up in the SD tests that takes 1.5 hrs to run, even a smaller unit test doesn't recreate this with the same inputs to concat as  its dependent on previous op allocations. 

@jaykru-tt is working hard at this and we want to thank you for your patience.

**Comment by jaykru-tt** [comment]
Should be resolved by #14306. Let me know if you're still seeing problems! @dgolubovicTT @tt-mpantic

**Comment by dgolubovicTT** [comment]
After this fix we have problems with the same concat. Namely ttnn.concat gives output that is padded 
input1 shape: (1,1,12,50)
input2 shape: (1,1,12,50)
concat dim = -1
pytorch output: (1,1,12,100)
ttnn output: (1,1,32,128)

you can repro it with your ttnn test ust putting these shapes:

```
@pytest.mark.parametrize("height", [12])
@pytest.mark.parametrize("width", [50])
@pytest.mark.parametrize("dim", [-1])
@pytest.mark.parametrize("async_mode", [True, False], ids=["async_on", "async_off"])
def test_concat(device, height, width, dim, async_mode):
    device.enable_async(async_mode)
    torch_input_tensor_a = torch.rand((1, height, width), dtype=torch.bfloat16)
    torch_input_tensor_b = torch.rand((1, height, width), dtype=torch.bfloat16)
    torch_output_tensor = torch.concat([torch_input_tensor_a, torch_input_tensor_b], dim=dim)

    input_tensor_a = ttnn.from_torch(torch_input_tensor_a, layout=ttnn.TILE_LAYOUT, device=device)
    print(" shape of input: ", input_tensor_a.shape)
    input_tensor_b = ttnn.from_torch(torch_input_tensor_b, layout=ttnn.TILE_LAYOUT, device=device)
    print(" shape of input: ", input_tensor_b.shape)

    # if ttnn.has_tile_padding(input_tensor_a, dim=dim) or ttnn.has_tile_padding(input_tensor_b, dim=dim):
    #     pytest.skip("Cannot concat tensors with tile padding")

    output = ttnn.concat([input_tensor_a, input_tensor_b], dim=dim)
    print(" shape of output: ", output.shape)
    print(" shape of torch_output_tensor: ", torch_output_tensor.shape)
    output = ttnn.to_torch(output)

    assert_with_pcc(torch_output_tensor, output, 0.9999)
```

So this is still a blocker for Llama bringup, therefore it is again P0.
Can you please add some tests when you fix it just to know it works at least for these shapes.

**Comment by ntarafdar** [comment]
@jaykru-tt could you look at this.

**Comment by ntarafdar** [comment]
@dgolubovicTT spoke to @jaykru-tt , he is on it, I think early next week is when he can have it done since Thu/Fri is off

**Comment by jaykru-tt** [comment]
Should be resolved by https://github.com/tenstorrent/tt-metal/pull/15513 once merged. I've added the requested shapes to make sure we don't regress on this.

**Comment by dgolubovicTT** [comment]
I've cherry-picked your fix and it works. Closing this one for now
