### ISSUE TITLE
ttnn.i0_bw operation fails with low PCC

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#13676]
ttnn.i0_bw operation fails with low PCC

 * Steps to reproduce

On branch `ngrujic/unit-tests-1` (soon to be merged into main), there is unit test `tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_eltwise_i0_bw.py`, which can be run with:

```
pytest  tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_eltwise_i0_bw.py
```

Also, you can reproduce this error with sweep test `tests/sweep_framework/sweeps/eltwise/unary_backward/i0_bw/i0_bw.py`. To run:

```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.unary_backward.i0_bw.i0_bw
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.unary_backward.i0_bw.i0_bw
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by umadevimcw** [comment]
@nemanjagrujic Kindly provide the unit test code to debug this issue.

**Comment by nemanjagrujic** [comment]
Hello @umadevimcw, I updated instructions.

**Comment by KalaivaniMCW** [comment]
`ttnn.i0_bw` uses `ttnn.reciprocal(input)` in it's implementation. And we have an ongoing issue with the reciprocal op kernel #14672 especially when the input is in bfloat8_b.

**Comment by KalaivaniMCW** [comment]
PR #15325
