### ISSUE TITLE
ttnn.acosh_bw operation does not work with bfloat8_b tensors

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#13674]
ttnn.acosh_bw operation does not work when input tensor is bfloat8_b. Documentation does not mention that limitation.

Steps to reproduce

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/eltwise/unary_backward/acosh_bw.py`. To run:

```
python3 tests/sweep_framework/runner.py --elastic cloud --module-name eltwise.unary_backward.acosh_bw
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by mcw-anasuya** [comment]
Updated doc and sweep test and merged to main. Closing this issue.
