### ISSUE TITLE
ttnn.mul_bw unary inconsistent documentation regarding input tensors layout

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#13683]
ttnn.mul_bw unary doesn't support ROW_MAJOR layout despite what it says in the documentation. When one or both of the input tensors has ROW_MAJOR layout, the FATAL error "Inputs to eltwise binary must be tilized" is thrown.

**To Reproduce**
Sweep test for mul_bw is located in 'tests/sweep_framework/sweeps/eltwise/unary_backward/mul_bw/mul_bw.py'
1. Go to 'tests/sweep_framework/sweeps/eltwise/unary_backward/mul_bw/mul_bw.py'
2. Remove next lines of code from the invalidate_vector function:
```
    if test_vector["input_layout"] == ttnn.ROW_MAJOR_LAYOUT:
        return True, "Inputs to eltwise binary must be tilized"
```
3. Generate new parameter vectors and run the sweep test
```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.unary_backward.mul_bw.mul_bw
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.unary_backward.mul_bw.mul_bw 
```
5. See error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Expected behavior**
For vectors with `grad_layout` and `input_a_layout` being ROW_MAJOR_LAYOUT, test will fail with the message "inputs to eltwise binary must be tilized"

**Comment by KalaivaniMCW** [comment]
updated doc 
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/218332ee-08bd-47b9-a427-152d17a9504e">
