### ISSUE TITLE
Incomplete documentation for ttnn.normalize_global and ttnn.normalize_hw regarding input_tensor rank

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#13682]
ttnn.normalize_global and ttnn.normalize_hw operations don't support tensors with rank that is not 4.

### Steps to reproduce:

You can reproduce this error with sweep tests `/tests/sweep_framework/sweeps/eltwise/unary/normalize_global/normalize_global.py`, and  `/tests/sweep_framework/sweeps/eltwise/unary/normalize_hw/normalize_hw.py`. 

1) Inside the sweep files, replace the "input_shape" parameter with: 
```
        "input_shape": gen_shapes([1, 1, 32, 32], [6, 12, 256, 256], [1, 1, 32, 32], 8)
        + gen_shapes([1, 32, 32], [12, 256, 256], [1, 32, 32], 8)
        + gen_shapes([32, 32], [256, 256], [32, 32], 8),
```

To run:
```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.unary.normalize_global.normalize_global
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.unary.normalize_global.normalize_global
```

```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.unary.normalize_hw.normalize_hw
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.unary.normalize_hw.normalize_hw
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by mcw-anasuya** [comment]
Merged to main, hence closing this issue.
