### ISSUE TITLE
Enable allocation of new buffers with a warning to allow running decode with trace and prefill without trace

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#13690]
This is required by vLLM (https://github.com/tenstorrent/vllm/issues/14) since we need to interleave executions of a decode trace with prefill (not traced).

**Comment by tt-asaigal** [comment]
Merged to Metal main @ https://github.com/tenstorrent/tt-metal/commit/f0b2483529a55d1101eb142ae1c70eec5260ecf7
