### ISSUE TITLE
Test matmuls with better synchronization

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent/tt-metal#13692]
We believe that di/dt issues are more likely to appear if all cores start and end compute at the same time. We can explicitly synchronize cores to confirm this hypothesis. On LM head reading in1 blocks from DRAM adds a lot of inconsistency, so we need to synchronize cores using semaphores and see how it affects droops and hang repro rate.

**Comment by s-jovic** [comment]
Branch `sjovic/dram-sync-matmul1d` (based on `skrsmanovic/didt_scope_experiments`) has a commit that adds support for 2 different sync variants, used on matmul 1d and LM head example:
- variant 1: skip waiting for in1 data from DRAM - this variant synchronizes cores already since DRAM it is the only source of 'nondeterminism' in matmul 1d
- variant 2: synchronize cores using semaphores after they all receive current block of in1 data

**LM head experiment**

To check synchronization between cores for each block, I used `tests/didt/sync_analysis.py` script - it generates a heatmap showing how far are cores start times from the mean start time for each block.

With baseline case, block start times wrt the mean start time is between -40000 and 40000, although most of them are between -10000 and 10000. PMON captures show that minimal voltage goes down to 808mV, while nominal voltage is around 920mV.

**Variant 1** results in lower nominal and minimal voltage, nominal being around 860mV and minimal around 770mV. Repro rate is definitely not better (faster hang) than the baseline case, although I am not sure whether it is worse (slower hang).

**Variant 2** results in similar voltage behavior, with minimal voltage going a bit lower (804mV), however, repro rate is much better. 
- On board3 t3002, baseline case often hangs after 300k+ iterations, while synced version hangs under 25k iterations.
- On board0 t3005, baseline case often hangs after 75k+ iterations, while synced version hangs under 10k iterations.
- On board1 t3005, synced version hangs under 1500 iterations.


**Matmul stagger**

I am currently testing how all-block stagger impacts the synced version of LM head. Results so far are good, and t3002 and both t3005 passed 5million iterations without hang, but this was all done on fw 80.10.4.0, so I will repeat the tests tonight with 80.10.4.1 firmware and more boards.

**Comment by s-jovic** [comment]
Regarding FF1 matmul, this one is already synced pretty well, and since repro rate is much slower than LM head, I didn't focus on this example yet.

**Comment by s-jovic** [comment]
High-sync lm head matmul exposes same signature as the ones explained in [this issue](https://github.com/tenstorrent/tt-metal/issues/13091); basically on a random block in iterations, all cores move on to the next block, but 1 or 2 fail to increment the semaphore for in0 to continue to the next block.

**Comment by s-jovic** [comment]
`sjovic/dram-synced-matmul2d` has sync implemented for FF1 example as well. The max diff between blocks starting on all cores is ~50 cycles. Repro rate is much quicker on N300 (bgd-lab-t3002, board3), we get a hang in less than 20k iterations.

**Comment by s-jovic** [comment]
`sjovic/dram-synced-matmul2d` was updated with a fix for runtime arguments when program cache is turned on. Sync argument was updated instead of output buffer address. This is why we had hangs on some grid sizes (8x5, 8x6 and 8x7). The grid size experiment with high-sync matmuls need to be repeated, locally I saw hang with 8x7 as well, but 8x6 passed 500k iterations.

**Comment by ttmtrajkovic** [comment]
Marking as completed as support for this workload exists.
Experiments with this tests are logged.
