### ISSUE TITLE
[Bug Report] Code example on all gather

### ISSUE THREAD

**Issue by gfengTT** [tenstorrent/tt-metal#13693]
**Describe the bug**

In section 5.2.1 of programming mesh documentation

https://github.com/tenstorrent/tt-metal/blob/b8b6dcaa4e90f08a180fd216b56382d549b8642c/tech_reports/Programming%20Mesh%20of%20Devices/Programming%20Mesh%20of%20Devices%20with%20TT-NN.md?plain=1#L280

**Issues**

1. (minor) Variable name inconsistency, `torch_tensor` vs. `torch_input_tensor`
2. The all_gather op failed: `Device 4 is not connected to Device 6`

**Context**
The system topology was:
```
4 -- 0 -- 3 -- 7
|    |    |    |
5 -- 1 -- 2 -- 6
```
So after `mesh_device = ttnn.open_mesh_device(ttnn.MeshShape(2, 4))`, `mesh_device.get_device_ids()` returns `[4, 0, 3, 7, 5, 1, 2, 6]`.

Instead I tried:
```
physical_device_ids = ttnn.get_t3k_physical_device_ids_ring()
mesh_device = ttnn.open_mesh_device(ttnn.MeshShape(1, 8), physical_device_ids=physical_device_ids[:8])
```

This time `mesh_device.get_device_ids()` returns `[4, 0, 3, 7, 6, 2, 1, 5]`, and the op works as expected.

**Environment**
t3k lab machine
- OS: Ubuntu 22.04
- Commit: 49f764c3bc27a88d7ed34b15002b3ffdbc37e4a3

**Comment by gfengTT** [comment]
@SeanNijjar just reminded me that `mesh_device = ttnn.open_mesh_device(ttnn.MeshShape(2, 4), mesh_type=ttnn.MeshType.Ring)` also works

**Comment by cfjchu** [comment]
Yes, you should be using `mesh_type=ttnn.MeshType.Ring`. Thanks for the bug report. The fix is merged in.
