### ISSUE TITLE
View ops

### ISSUE THREAD

**Issue by afuller-TT** [tenstorrent/tt-metal#13720]
From the community:

> [View opearions are _expensive_ while most frameworks expects it to be free](https://discord.com/channels/863154240319258674/1177107133167321158/1293966833463988297)

**Comment by ayerofieiev-tt** [comment]
Setting to P1. It would be helpful to have a view op which clearly has a 0 cost.
The challenge is that due to tiling and padding it is not possible to call view in ttnn in all the same cases.

**Comment by ntarafdar** [comment]
@jvegaTT we have this and a few reshape related issues. I think they can all be tackled together. Let's discuss tomorrow!

**Comment by ntarafdar** [comment]
@ayerofieiev-tt @afuller-TT 
@jvegaTT is making an explicit view op which will be a subset of reset that we have. The view will match the expectation of there being a 0 cost.
