### ISSUE TITLE
Reduce load on TTNN consumers

### ISSUE THREAD

**Issue by afuller-TT** [tenstorrent/tt-metal#13724]
From the community:

> [No, I mean as a downstream user. My compilation time skyrockets when I start including TTNN component.](https://discord.com/channels/863154240319258674/1177107133167321158/1293968995401207848)

**Comment by ayerofieiev-tt** [comment]
Thank you, this is on the radar. I don't think we need a ticket to track this one. We are well aware of the impact of template-heavy include-poor TT-NN core's. We intend to iterate on it in Q1 2025
