### ISSUE TITLE
ttnn.cos_bw operation fails with low PCC on Grayskull

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#13739]
ttnn.cos_bw operation fails with low PCC on Grayskull. On WH operation works fine.

Steps to reproduce

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/eltwise/unary_backward/cos_bw.py`. To run:

```
python3 tests/sweep_framework/runner.py --elastic cloud --module-name eltwise.unary_backward.cos_bw
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by eyonland** [comment]
@nemanjagrujic , I'm closing this issue as I understand we will be focusing all efforts going forward on WH and BH work.
