### ISSUE TITLE
[Bug Report] Apparent misuse of template parameters in `SimpleShape`'s constructor

### ISSUE THREAD

**Issue by o2buzzle** [tenstorrent/tt-metal#13738]
**Describe the bug**
In `ttnn/cpp/ttnn/tensor/types.hpp`, `SimpleShape` has the following constructors:

https://github.com/tenstorrent/tt-metal/blob/db6cd142380aca02a43137de5c1a8007c54dd331/ttnn/cpp/ttnn/tensor/types.hpp#L35-L42

Specifically there is a template on the first constructor that is not being used at all for that constructor (maybe the intent was to use `const std::vector<T>& shape` as the input?). This causes `Candidate template ignored: couldn't infer template argument 'T'` if a uint32_t vector is passed as input to the constructor as intended.

**To Reproduce**
1. Attempt to construct a SimpleShape with `std::vector<uint32_t>` as the argument

**Expected behavior**
Creation of SimpleShape with a vector of sizes being allowed just like `ttnn::Shape`

**Screenshots**
SimpleShape with current `main` branch (error generated using clangd, `operation_attributes.output_shape` is of type `std::vector<uint32_t>` ):
![image](https://github.com/user-attachments/assets/dd637bb9-4ff0-449c-a74e-1e1fd241a4de)
Removing `template <typename T>` allows object construction as expected.

**Please complete the following environment information:**
- OS: Ubuntu 22.04.5
- `main` branch of tt-metal, latest commit as of writing (db6cd142380aca02a43137de5c1a8007c54dd331)

**Additional context**
None

**Comment by ayerofieiev-tt** [comment]
Hi! Thank you! Yes, I found the same issue yesterday.
You can open a fix or I will provide it later today. Let me know if you work on this.

**Comment by o2buzzle** [comment]
@ayerofieiev-tt Sorry for the late reply, it was weekend

Since it should be an one-line change (plus maybe some touch-ups like removing `std::move` from references), it shouldn't be too complicated. I'll draft a PR for it.
