### ISSUE TITLE
Get add_tile API support for int32 values 

### ISSUE THREAD

**Issue by sraizada-tt** [tenstorrent/tt-metal#13754]
int32 addition support is here: common/inc/sfpu/ckernel_sfpu_add_int32.h, we need wrappers to use this is an op

**Comment by rtawfik01** [comment]
@rdjogoTT @amahmudTT @ttmtrajkovic The above is needed for full int32 additions, currently the above kernel has been used and tested in buda, but it does not have llk_sfpu wrappers or any tests in tt-metal. The above is needed for wormhole_b0.

**Comment by rdjogoTT** [comment]
Added the API here: https://github.com/tenstorrent/tt-metal/blob/main/tt_metal/include/compute_kernel_api/add_int32_sfpu.h
