### ISSUE TITLE
[Feature Request] DPS version of logical_xor op

### ISSUE THREAD

**Issue by mmanzoorTT** [tenstorrent/tt-metal#13758]
TTNN lib provides DPS based op for `logical_and`, `logical_or`, and `logical_not`. However, `logical_xor` is implemented as non-DPS op. Can we convert `logical_xor` to DPS op as well to be consistent?

**Comment by sdjordjevicTT** [comment]
Hi @eyonland, we discovered this during our onboarding in the TT-MLIR compiler. Can you give us some feedback on whether this inconsistency in the logical_xor op is a limitation or just needs to be implemented from your side?

**Comment by eyonland** [comment]
We need to investigate this a bit more to be sure, but I don't see why we can't get this implemented for you.

**Comment by umadevimcw** [comment]
@mmanzoorTT @sdjordjevicTT Updated the logical XOR similar to other logical ops like AND, OR,  in this PR  #14340. Let us know if this meets your requirements

**Comment by umadevimcw** [comment]
@sdjordjevicTT @mmanzoorTT Merged the PR. Kindly check and let me know if we can close this issue.

**Comment by mmanzoorTT** [comment]
@umadevimcw Thanks a lot. I'll test it today and will comment. PR looks good overall.

**Comment by eyonland** [comment]
@mmanzoorTT , can we close this issue?

**Comment by umadevimcw** [comment]
Closing this issue as the PR is merged to main. Will reopen if needed

**Comment by mmanzoorTT** [comment]
@umadevimcw @eyonland @sdjordjevicTT I have implemented/tested DPS logical_xor op with https://github.com/tenstorrent/tt-mlir/pull/1141 (requiring https://github.com/tenstorrent/tt-mlir/pull/1119 for tt-metal uplift) and it is working as expected. thanks a lot
