### ISSUE TITLE
Support floating-point exponents for `ttnn.pow`

### ISSUE THREAD

**Issue by jdh8** [tenstorrent/tt-metal#13779]
As we found in tenstorrent/pytorch2.0_ttnn#211, `ttnn.pow` only supports integer exponents.  Even if we only need integral support (as [current statistics](https://github.com/tenstorrent/pytorch2.0_ttnn/blob/e02d661c19d76bb1c9cf56af146efa4e77f930c6/docs/operations/aten.pow.Tensor_Scalar.md) say), we can still optimize current implementation with [binary exponentiation](https://en.wikipedia.org/wiki/Exponentiation_by_squaring).
https://github.com/tenstorrent/tt-metal/blob/021137c47a58841b6dfe9233a70ea449177bae51/tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_power_iterative.h#L18-L26

**Comment by mouliraj-mcw** [comment]
Hi @jdh8
- The pow function with floating-point exponents is already implemented in the composite structure
I would like some clarification on the requirement here - is it to optimize the current ckernel for pow using binary exponentiation ?

cc: @eyonland
