### ISSUE TITLE
ttnn.xlogy_bw inconsistent documentation regarding input tensors dtypes

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#13775]
ttnn.xlogy_bw doesn't support bfloat8_b dtypes on input_tensor_a and input_tensor_b

**To Reproduce**
Sweep test for xlogy_bw is located in 'tests/sweep_framework/sweeps/eltwise/binary_backward/xlogy_bw/xlogy_bw.py'
1. Go to 'tests/sweep_framework/sweeps/eltwise/binary_backward/xlogy_bw/xlogy_bw.py'
2. Inside the invalidate_vector function, comment out next piece of code:
```
    if test_vector["input_a_dtype"] == ttnn.bfloat8_b or test_vector["input_b_dtype"] == ttnn.bfloat8_b:
        return True, "bfloat8_b is not supported for input tensors"
```
3. Generate new parameter vectors and run the sweep test
```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.binary_backward.xlogy_bw.xlogy_bw
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.binary_backward.xlogy_bw.xlogy_bw 
```
5. See error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Expected behavior**
For vectors with `input_tensor_a` or `input_tensor_b` having bfloat8_b dtype, test will fail with the message "Unsupported DataType ..."

**Comment by KalaivaniMCW** [comment]
Updated doc
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/2096736e-dbbe-49bb-a637-1607788a04e2">
