### ISSUE TITLE
Runtime Error: Statically allocated circular buffers issue in conv

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#13811]
**Describe the bug**
A convolution of configuration (batch_size, output_channels,input_channels, input_height, input_width, filter_height, filter_width, stride_h, stride_w, pad_h, pad_w, use_1d_systolic_array, config_override, use_shallow_conv_variant) = (1, 128, 256, 120, 160, 3, 3, 1, 1, 1, 1, True, {"act_block_h": 32}, False), which is passing in unit test([Link](https://github.com/tenstorrent/tt-metal/blob/main/tests/ttnn/unit_tests/operations/test_new_conv2d.py#L2070)) is failing in pipeline of one of the vanilla unet pipeline([punith/vanilla_unet_inference_opt](https://github.com/tenstorrent/tt-metal/compare/main...punith/vanilla_unet_inference_opt)) due to statically allocated circular buffers issue in dec3_1 convolution.

**To Reproduce**
1. Checkout to branch, [punith/vanilla_unet_inference_opt](https://github.com/tenstorrent/tt-metal/compare/main...punith/vanilla_unet_inference_opt) .
2.  Run command `pytest tests/ttnn/integration_tests/vanilla_unet/test_ttnn_unet.py`

**Expected behavior**
Execution of conv without any issue.

**Screenshots**
```
>       ttnn_output = ttnn_model(device, ttnn_input_tensor)

tests/ttnn/integration_tests/vanilla_unet/test_ttnn_unet.py:153: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
models/experimental/functional_vanilla_unet/ttnn/ttnn_unet.py:241: in __call__
    dec3 = self.dec3_1(device, dec3)
models/experimental/functional_vanilla_unet/ttnn/common.py:57: in __call__
    [output_tensor, _out_height, _out_width, self.weights, self.bias] = ttnn.conv2d(
ttnn/ttnn/decorators.py:329: in __call__
    return self.function(*function_args, **function_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @ttnn.register_python_operation(name="ttnn.conv2d")
    def conv2d(
        *,
        input_tensor: ttnn.Tensor,  # may or may not be sharded
        weight_tensor: ttnn.Tensor,
        device: ttnn.Device,
        in_channels: int,
        out_channels: int,
        batch_size: int,
        input_height: int,
        input_width: int,
        kernel_size: Union[int, Tuple[int, int]],
        stride: Union[int, Tuple[int, int]],
        padding: Union[int, Tuple[int, int]],
        dilation: Union[int, Tuple[int, int]] = (1, 1),
        groups: int = 1,
        bias_tensor: ttnn.Tensor = None,
        conv_config: Conv2dConfig = None,  # config overrides by user
        conv_op_cache={},  # basic conv object caching in python needed for intermediate refactoring. Not needed after full op refactoring in C++.
        debug=False,  # ignored
    ) -> Tuple[ttnn.Tensor, int, int, ttnn.Tensor, ttnn.Tensor]:
>       return ttnn._ttnn.operations.conv2d.conv2d(
            input_tensor=input_tensor,
            weight_tensor=weight_tensor,
            device=device,
            in_channels=in_channels,
            out_channels=out_channels,
            batch_size=batch_size,
            input_height=input_height,
            input_width=input_width,
            kernel_size=kernel_size,
            stride=stride,
            padding=padding,
            dilation=dilation,
            groups=groups,
            bias_tensor=bias_tensor,
            conv_config=conv_config,
        )
E       RuntimeError: TT_THROW @ ../tt_metal/impl/program/program.cpp:541: tt::exception
E       info:
E       Statically allocated circular buffers in program 53 clash with L1 buffers on core range [(x=0,y=0) - (x=7,y=7)]. L1 buffer allocated at 414976 and static circular buffer region ends at 804288

```

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Device : WH-n150

**Additional context**
The same configuration convolution is passing in another implementation of vanilla unet ([Link](https://github.com/tenstorrent/tt-metal/compare/main...punith/vanilla_unet_inference)).

**Comment by punithsekar** [comment]
fyi @saichandax

**Comment by shwetankTT** [comment]
@punithsekar I've rebased your branch to the mainline, but my findings should still be relevant. I noticed some allocated tensors which are no longer needed. After deallocation it should work.  ![Image](https://github.com/user-attachments/assets/37f94e20-2fff-42ce-8a47-f50d67360bde)

**Comment by shwetankTT** [comment]
@mywoodstock Can we close it?

**Comment by mywoodstock** [comment]
Thanks @shwetankTT.

@punithsekar Could you please confirm if this works now? If so, we can close this.

**Comment by punithsekar** [comment]
Sure @mywoodstock ,
I will check and let you know.
CC: @saichandax @dvartaniansTT

**Comment by punithsekar** [comment]
Since the tensors that were not deallocated were still being used later in the code, I moved them from L1 space to DRAM. This has resolved the issue with statically allocated buffers. If no other solution is available other than offloading the tensors to DRAM, we can consider this issue closed. @mywoodstock Once you acknowledge this we can close it.

Thank you!
CC: @dvartaniansTT

**Comment by punithsekar** [comment]
On a lighter note, I encountered an OOM issue in the first convolution on rebasing to the latest main. I resolved it by avoiding placing the input tensor on the device, as detailed in [this commit](https://github.com/tenstorrent/tt-metal/commit/414c62d5bcd3eb32a157b94837b53f35a2363233).
