### ISSUE TITLE
Can't build Metal with profiler

### ISSUE THREAD

**Issue by arikTT** [tenstorrent/tt-metal#13831]
**Describe the bug**
I'm trying to build Metal with the profiler enabled and getting build errors and failure. the exact error depends on the script used (either `build_with_profiler_opt.sh` or using `-p` for `build_metal.sh`).

**To Reproduce**
1. Reserve a Grayskull ird with the following image: ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-20.04-amd64:latest
2. Follow steps to set environment and clone the repo per the Metal installation instrcution.
3. use `./build_metal -p` to build with profiler

The build fails with the following output:
```
FAILED: tmp/tracy_stamp/tracy_capture_tools-build 
cd /proj_sw/user_dev/ayaacob/tt-metal/build_Release_tracy/tools/profiler/bin && cd /proj_sw/user_dev/ayaacob/tt-metal/tt_metal/third_party/tracy/capture/build/unix && CXX=g++ TRACY_NO_LTO=1 make -f /proj_sw/user_dev/ayaacob/tt-metal/tt_metal/third_party/tracy/capture/build/unix/Makefile && /usr/bin/cmake -E touch /proj_sw/user_dev/ayaacob/tt-metal/build_Release_tracy/tmp/tracy_stamp/tracy_capture_tools-build
make[1]: Entering directory '/proj_sw/user_dev/ayaacob/tt-metal/tt_metal/third_party/tracy/capture/build/unix'
make[1]: *** No rule to make target '/usr/include/capstone/m68k.h', needed by 'obj/release/o/o/o/../../../server/TracyWorker.o'.  Stop.
make[1]: Leaving directory '/proj_sw/user_dev/ayaacob/tt-metal/tt_metal/third_party/tracy/capture/build/unix'
make: *** [/proj_sw/user_dev/ayaacob/tt-metal/tt_metal/third_party/tracy/capture/build/unix/Makefile:7: release] Error 2
```

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- branch based on commit `4f9574dc9ad` on `master` from 10/14.

**Additional context**
Verified on clean build

**Comment by tt-rkim** [comment]
Per @blozano-tt ,

If you do

```
sudo apt-get install libcapstone-dev
```

Does it work?

**Comment by arikTT** [comment]
It says libcapastone-dev is already the newest (4.0.1+really+3.0.5-1build1). Isn't that the correct version?

**Comment by tt-rkim** [comment]
You don't have a `/usr/include/capstone/` in your container?

**Comment by arikTT** [comment]
I do have it, but there is no `m68k.h` file. Any place I can get the missing file(s)?

**Comment by tt-rkim** [comment]
OK wait - why is your build even looking for m68k... that seems like a very old architecture: https://en.wikipedia.org/wiki/Motorola_68000_series

I don't even have it on my development system:

```
(internal_python_env) rkim@e12cs07:~/tt-umd$ ls -hal /usr/include/capstone/
total 216K
drwxr-xr-x  2 root root 4.0K Jan 19  2024 .
drwxr-xr-x 68 root root  20K Sep 24 07:01 ..
-rw-r--r--  1 root root  28K Oct 18  2019 arm64.h
-rw-r--r--  1 root root  17K Oct 18  2019 arm.h
-rw-r--r--  1 root root  25K Oct 18  2019 capstone.h
-rw-r--r--  1 root root  16K Oct 18  2019 mips.h
-rw-r--r--  1 root root 3.2K Oct 18  2019 platform.h
-rw-r--r--  1 root root  22K Oct 18  2019 ppc.h
-rw-r--r--  1 root root  11K Oct 18  2019 sparc.h
-rw-r--r--  1 root root  14K Oct 18  2019 systemz.h
-rw-r--r--  1 root root  34K Oct 18  2019 x86.h
-rw-r--r--  1 root root 4.8K Oct 18  2019 xcore.h
```

@mo-tenstorrent any idea what's going on?

**Comment by mo-tenstorrent** [comment]
No idea, I am struggling to understand how the same docker image working on other instances is failing to build here. Wasn't that the entire point of docker?

**Comment by blozano-tt** [comment]
> No idea, I am struggling to understand how the same docker image working on other instances is failing to build here. Wasn't that the entire point of docker?

Yes, this is bizarre

**Comment by arikTT** [comment]
what is the best way of starting with a clean image? I just made a reservation on a different machine and see the same

**Comment by arikTT** [comment]
@mo-tenstorrent  @blozano-tt any ideas on how to start over with a clean image/container?

**Comment by tt-rkim** [comment]
have you tried release your current ird reservation and trying a new one?

**Comment by arikTT** [comment]
tried that, same results (even switched grom GS to WH)

**Comment by mo-tenstorrent** [comment]
@ttmchiou any idea what could be going on?

**Comment by tt-rkim** [comment]
It should only be building for native...

Per `tt_metal/third_party/tracy/common/unix-release.mk`:

`ARCH := $(shell uname -m)`

what does `uname -m` give you?

**Comment by tt-rkim** [comment]
what host is your container running on? are you able to see that? and do

```
git submodule status
git status
```

and send us the output

**Comment by arikTT** [comment]
tried on 2 machines, here is the output of `ird list`:
```
SELECTION ID         USER                 CLUSTER              PARTITION            MACHINE              TIME LEFT            CPU_IDS              MEMORY               BOARDS               JOB ID               SSH PORT             DEBUDA PORT          COMMENT
1                    ayaacob              tt_aus_colo          sw_interactive       aus-gs-08            2:50:42              -                    -                    -                    3016803              46099                51099                "ssh_port=46099,debuda_port=51099"
2                    ayaacob              tt_aus_colo          sw_interactive       aus-wh-20            4:06:12              -                    -                    -                    3016820              46099                51099                "ssh_port=46099,debuda_port=51099"
```
and git output:
```
ayaacob@aus-wh-20-special-ayaacob-for-reservation-3016820:/proj_sw/user_dev/ayaacob/tt-metal$ git submodule status
 7b11d073376b905b46edaa757f0bfde5c38a9636 models/demos/t3000/llama2_70b/reference/llama (heads/main)
 2ba5a2973915aa1c5afbf6f1524e87e0c43bc058 tt_metal/third_party/lfs (v0.2.26-9-g2ba5a29)
 b8f28551cc3a98ea9fbfc15c05b513c8f2d23e84 tt_metal/third_party/pybind11 (v2.10.2-22-gb8f28551)
 1aab81a8ddddf94702fad18efec0c1c163c96bab tt_metal/third_party/sfpi (remotes/origin/HEAD)
 7d9e85b6b2e9bf501021f857f2f3cbe43bc37c85 tt_metal/third_party/taskflow (v3.7.0)
 71d4c8d378b52af7da7012b9b595a61e9304f0bb tt_metal/third_party/tracy (v0.10-tt.0-11-g71d4c8d3)
 5b445850ee674118a99bda696e3c40f4941f3529 tt_metal/third_party/tt_llk_blackhole (heads/main-3-g5b44585)
 9cadb14bc905b84abb0e99e41ab83a612c4cd428 tt_metal/third_party/tt_llk_grayskull (remotes/origin/HEAD)
 56ec2f52c817053116058c7ca4ed22da11c236ae tt_metal/third_party/tt_llk_wormhole_b0 (remotes/origin/HEAD)
 f7b1ce0f6ed3101bdd4f1367145378a59996f07b tt_metal/third_party/umd (remotes/origin/jnie/dp_umd-40-gf7b1ce0)
ayaacob@aus-wh-20-special-ayaacob-for-reservation-3016820:/proj_sw/user_dev/ayaacob/tt-metal$ git status
On branch coalesce_cmd_wait_into_slave_go
Your branch is up to date with 'origin/coalesce_cmd_wait_into_slave_go'.

nothing to commit, working tree clean
```

**Comment by tt-rkim** [comment]
I've put this as P3.

Unfortunately, I won't have time to get back to this. If you've unblocked yourself, please close the issue or let us know if it keeps coming up

Please reach out to colleagues on your team to see how they set up similar flows. We don't see this with others using IRD.
