### ISSUE TITLE
Low PCC During Tensor Layout Conversion on Device in Lenet Model

### ISSUE THREAD

**Issue by sabira-mcw** [tenstorrent/tt-metal#13860]
**Describe the bug**
When converting the layout of a tensor on the device, the PCC drops.

**To Reproduce**

1. Pick the test from [Commit](https://github.com/tenstorrent/tt-metal/compare/main...sabira/test_layout)
2. Run pytest tests/ttnn/unit_tests/operations/test_layout.py::test_layout

**Expected behavior**
 The PCC  expected to be at a normal level during the tensor layout conversion process.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Devices: GS, WH

**Additional context**
This issue may affect overall performance and efficiency when working with tensor layouts. Further investigation might be needed to identify the underlying cause.

**Comment by saichandax** [comment]
We are not using this layout conversion in the Lenet Model.
If this issue persists in any other model, we can re-open or create new issue.

Closing this issue for now.
