### ISSUE TITLE
[Bug Report] Create Semaphore on Ethernet core does not initialize semaphore value

### ISSUE THREAD

**Issue by jvegaTT** [tenstorrent/tt-metal#13898]
**bug summary:**
Calling:
tt::tt_metal::CreateSemaphore(program, eth_sender_core, 0, CoreType::ETH);

Does not initialize the semaphore to a value of 0

**To Reproduce**
Code with error has been pushed to branch jvega/broken_semaphore
I created a semaphore in ttnn/cpp/ttnn/operations/ccl/barrier/device/host/barrier_full_worker_grid.cpp line 55 which is sent to the kernel code located at ttnn/cpp/ttnn/operations/ccl/barrier/device/kernels/barrier_sender_HPerf_LPrec.cpp and ttnn/cpp/ttnn/operations/ccl/barrier/device/kernels/barrier_receiver_HPerf_LPrec.cpp . The semaphore is in the memory of the ethernet device running barrier_sender_HPerf_LPrec.cpp
The receiver is made to spin for a long time to prevent it from influencing the test at line 149
The sender obtains the semaphore address at line 42 and prints it. The value received is a large garbage value.

You can run this code by first setting the variable:
export TT_METAL_DPRINT_CHIPS=0,1,2,3,4,5,6,7
export TT_METAL_DPRINT_ETH_CORES=all
and running
pytest tests/ttnn/unit_tests/test_barrier.py
This prints:
Sem value is currently1059471014

re-running gives us a different value and each of the chips prints a different value

**Expected behavior**
Should say Sem value is currently0, what it was initialized to

**Comment by tt-aho** [comment]
Hi @jvegaTT , I believe there might be a bug in the code and it is reading from the wrong address.

The return value of `CreateSemaphore` was changed a while ago from being an address to being an index/ID. In the kernel code to get the address we need to call `get_semaphore<type>(sem_id)` where `sem_id` is the value from CreateSemaphore and type should be `ProgrammableCoreType::ACTIVE_ETH`.

Would you be able to try this out and confirm if it works as expected with this change?

**Comment by jvegaTT** [comment]
As this is a non-issue so I am closing it
