### ISSUE TITLE
[Bug Report] `ttnn.reshape` output becomes `ROW_MAJOR` layout but input was `TILE` layout

### ISSUE THREAD

**Issue by kevinwuTT** [tenstorrent/tt-metal#13891]
**Describe the bug**
For certain input and output shapes, even when the input is `TILE` layout, the output of `ttnn.reshape` suddenly becomes `ROW_MAJOR` layout. One example is (1, 1445, 192) -> (1445, 192)

**To Reproduce**

```
torch_tensor = torch.rand((1, 1445, 192), dtype=torch.bfloat16)

with ttnn.manage_device(device_id=0) as device:  
    from_torch = ttnn.from_torch(torch_tensor, layout = ttnn.TILE_LAYOUT, dtype = ttnn.bfloat16, device = device)
    print(from_torch.layout)
    ttnn_reshape = ttnn.reshape(from_torch, (1445, 192))
    print(ttnn_reshape.layout)
```

**Other shapes with the same issue:
* (1, 256) -> (1, 1, 256)
* (16, 1, 32) -> (16, 1, 32) (same shape)
For some shapes there seems to be a pattern where the layout changes if H dim is 1. 

**Output:**
```
Layout.TILE
Layout.ROW_MAJOR
```

**Expected behavior**
The output of `ttnn.reshape` becomes `ROW_MAJOR`. This doesn't happen with shapes like (1, 32, 32) -> (32, 32) for instance.

**Please complete the following environment information:**
- OS: Ubuntu 20.04.6 LTS
- tag: v0.53.0-rc16

**Comment by ntarafdar** [comment]
closing as this was solved
