### ISSUE TITLE
softshrink_bw operation does not work bfloat8_b

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#13927]
softshrink_bw operation does not work when input tensor is bfloat8_b. Documentation does not mention that limitation.

Steps to reproduce

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/eltwise/unary_backward/softshrink_bw.py`. To run:

```
python3 tests/sweep_framework/runner.py --elastic cloud --module-name eltwise.unary_backward.softshrink_bw
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by KalaivaniMCW** [comment]
Documentation has been updated

**Comment by KalaivaniMCW** [comment]
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/4ba078d6-95f9-4f9c-ab5d-c003b529aaee">

**Comment by KalaivaniMCW** [comment]
FYI, bfloat8_b support will be added if #14346 is merged
