### ISSUE TITLE
ttnn.ldexp_bw operation does not work with row major layout

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#13928]
ttnn.ldexp_bw operation does not work when input tensor is in row major layout. Documentation states it should.

Steps to reproduce

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/eltwise/binary_backward/ldexp_bw.py`. To run:

```
python3 tests/sweep_framework/runner.py --elastic cloud --module-name eltwise.binary_backward.ldexp_bw
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by KalaivaniMCW** [comment]
Documentation has been updated
