### ISSUE TITLE
ttnn.ldexp_bw operation fails with low PCC

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#13929]
ttnn.ldexp_bw operation fails with low PCC (eg 0.98)

Steps to reproduce

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/eltwise/unary_backward/ldexp_bw.py`. To run:

```
python3 tests/sweep_framework/runner.py --elastic cloud --module-name eltwise.unary_backward.ldexp_bw
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by nemanjagrujic** [comment]
@umadevimcw Ok, just keep in mind that we need all relevant docs updated as well (exp, ldexp, ldexp_bw).

**Comment by umadevimcw** [comment]
Updated the document for ldexp and merged to main. Hence closing this issue
