### ISSUE TITLE
ttnn.logaddexp2_bw operation does not work with row major layout

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#13974]
ttnn.logaddexp2_bw operation does not work when input tensor is in row major layout. Documentation states it should.

Steps to reproduce

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/eltwise/binary_backward/logaddexp2_bw.py`. To run:

```
python3 tests/sweep_framework/runner.py --elastic cloud --module-name eltwise.binary_backward.logaddexp2_bw
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by KalaivaniMCW** [comment]
Updated doc 
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/51258c3d-e8b3-44c2-affd-66df986cee2c">

**Comment by KalaivaniMCW** [comment]
Currently, eltwise ops support TILE layout.
