### ISSUE TITLE
ttnn.mul_bw binary inconsistent documentation regarding the input tensors layout

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#13977]
ttnn.mul_bw binary doesn't support ROW_MAJOR layout despite what it says in the documentation. When any/all of the input tensors have ROW_MAJOR layout, the FATAL error "Inputs to eltwise binary must be tilized" is thrown.

**To Reproduce**
Sweep test for mul_bw is located in 'tests/sweep_framework/sweeps/eltwise/binary_backward/mul_bw/mul_bw.py'
1. Checkout branch amalbasaTT/backward_ops-sweeps-4
2. Go to 'tests/sweep_framework/sweeps/eltwise/binary_backward/mul_bw/mul_bw.py'
3. Remove next lines of code from the invalidate_vector function:
```
    if test_vector["input_layout"] == ttnn.ROW_MAJOR_LAYOUT:
        return True, "Inputs to eltwise binary must be tilized"
```
4. Generate new parameter vectors and run the sweep test
```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.binary_backward.mul_bw.mul_bw
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.binary_backward.mul_bw.mul_bw 
```
5. See error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Expected behavior**
For vectors with `input_layout` being ROW_MAJOR_LAYOUT, test will fail with the message "inputs to eltwise binary must be tilized"

**Comment by mcw-anasuya** [comment]
Closing this issue since document was updated in #14101 and merged to main.

<img width="1147" alt="Screenshot 2024-10-30 at 22 25 44" src="https://github.com/user-attachments/assets/09a81b33-390f-4181-bda5-3f7380bee62b">
