### ISSUE TITLE
ttnn.pow_bw reports "Unsupported DataType" error when using bfloat8_b on input_tensor_a and when the exponent is zero

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#13971]
**Describe the bug**
ttnn.pow_bw reports "Unsupported DataType" error when using bfloat8_b on input_tensor_a and when the exponent is zero. 

**To Reproduce**
Sweep test for pow_bw is located in 'tests/sweep_framework/sweeps/eltwise/unary_backward/pow_bw/pow_bw.py'
1. Go to 'tests/sweep_framework/sweeps/eltwise/unary_backward/pow_bw/pow_bw.py'
2. In "nightly" suite, set parameter "allow_exponent_zero" to [True]
3. Generate new parameter vectors and run the sweep test
```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.unary_backward.pow_bw.pow_bw
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.unary_backward.pow_bw.pow_bw --suite-name nightly
```
5. See the error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by mcw-anasuya** [comment]
This issue is fixed in #14336 and merged to main.
ttnn.pow_bw passes for both bfloat8_b and bfloat16 when exponent = 0. 
Hence closing this issue.
