### ISSUE TITLE
Reshape Op: use `TT_FATAL` in place of `TT_ASSERTS` + test padded shape instead of unpadded

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#14013]
For example, this condition: https://github.com/tenstorrent/tt-metal/blob/main/ttnn/cpp/ttnn/tensor/tensor_ops.cpp#L359-L363

Additionally, in the above, I believe it should be testing against padded new shape instead.

For a test that fails this assertion see:
```
tests/ttnn/unit_tests/operations/test_maxpool2d.py::test_run_max_pool[dtype=DataType.BFLOAT8_B-dilation=(1, 1)-stride=(2, 2)-padding=(0, 0)-kernel_size=(2, 2)-act_shape=[8, 16, 528, 80]-device_params={'l1_small_size': 24576}]
```
Note that the input width is 16, in bfloat8_b (so tiled, and hence padded).

**Comment by ntarafdar** [comment]
@mywoodstock I think you mentioned you were going to add this patch. Did you end up doing it?

**Comment by mywoodstock** [comment]
Hey, no I was using some local workaround for this, since I saw that the shape in that function was updated to SimpleShape which does not carry padding info.

**Comment by ntarafdar** [comment]
if there's a workaround I'm putting this as a P1 then

**Comment by jvegaTT** [comment]
With the changes to reshape, the above assert is no longer hit even if changing to TT_FATAL with the specified test. This I believe is due to the fact host-side reshape never happens anymore (it only runs on device) so that function is no longer called by reshape. Can the issue be closed?

**Comment by jvegaTT** [comment]
Closing this issue as no response was received in a week and we believe the issue to be solved.
