### ISSUE TITLE
[Bug Report] Moreh_adamw program is not properly cached

### ISSUE THREAD

**Issue by rfurko-tt** [tenstorrent/tt-metal#14010]
**Describe the bug**
While using `moreh_adamw` we saw that cache grows a little bit with every iteration. After review, we see that `steps` is cached inside program cache that triggers recreation of program for every new call. 

**To Reproduce**
* `enable_program_cache`
* Run `moreh_adamw` with same parameters except steps (1, 2, 3, 4, 5)
* Cache size grows 

**Expected behavior**
`steps` should not be part of caching mechanism

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Version of software: main

**Comment by mrshaw01** [comment]
@BuiChiTrung You should take a look and resolve this problem in the next PR scheduled for next week.
Ticket: MV-1089.

**Comment by o2buzzle** [comment]
@rfurko-tt Since `moreh_adam` and `moreh_adamw` shares this same issue I will PR to fix both of them

**Comment by mrshaw01** [comment]
@o2buzzle will resolve this issue. It seems like the problem could also appear in moreh_adam.

**Comment by rfurko-tt** [comment]
thank you @o2buzzle! Sounds reasonable!
