### ISSUE TITLE
EMBEDDING: misc/test_rotary_embedding.py::test_rotary_embedding_decode mismatching

### ISSUE THREAD

**Issue by ntarafdar** [tenstorrent/tt-metal#14063]
misc/test_rotary_embedding.py::test_rotary_embedding_decode fails due to mismatch in the results for decode tests involving bfp8_b . Investigatin showed that the results of the scalar multiplication are wrong, which lead to the final mismatch.

**Comment by arikTT** [comment]
Compute kernel is `rotary_embedding.cpp`. The first half of the rotated input is multiplied by -1, when I tested the result of that was wrong. There is only single scalar multiplication `mul_tiles_bcast_scalar(rotated_in_cb, scalar_cb, 0, 0, 0);`

**Comment by ntarafdar** [comment]
hey @amahmudTT I am not sure as I filed this based off @abhullar-tt master issue of BH bringup, initially thinking our team owned it but later finding out its not in our jurisdiction. 
I think just running the pytest `[misc/test_rotary_embedding.py::test_rotary_embedding_decode` (after re-enabling it) should recreate it.

**Comment by amahmudTT** [comment]
Managed to reduce  the test a lot. See branch https://github.com/tenstorrent/tt-metal/compare/main...amahmud/b14063

As can be seen it seems the ```tilize_init_short``` and ```tilize_uninit``` pair seem to be causing the issue. As can be seen in the test case and the comments. 

```
    binary_op_init_common(in_cb, scalar_cb, out_cb);

    /* We replace the TILIZE_ROWS function with just the init and uninit functions.
       Moreover, we replace the circular buffers with compatible data types, for the
       subsequent operations, still the issue appears. Thus the functions should be
       buggy and no amount of tensix sync helps, so this is not a race either.
    */

    //TILIZE_ROWS(untilized_sin_cb, untilized_sin_sync_cb, retilized_sin_cb, Wt);
    tilize_init_short(in_cb, Wt);
    tilize_uninit(in_cb);
    //tensix_sync();

    uint32_t in1_idx = 0;
    for (uint32_t i = 0; i < num_rows; ++i) {
        for (uint32_t j = 0; j < Wt; ++j) {
                reconfig_data_format(in_cb, scalar_cb);
                pack_reconfig_data_format(out_cb);
                cb_wait_front(in_cb, onetile);
                cb_reserve_back(out_cb, onetile);
                ACQ();
                mul_tiles_bcast_scalar_init_short();
                mul_tiles_bcast_scalar(in_cb, scalar_cb, 0, 0, 0);
                pack_tile(0, out_cb);
                REL();
                cb_push_back(out_cb, onetile);
                cb_pop_front(in_cb, onetile);
        }
    }


    /* This is a contrived issue, not related to the current bug. If we remove the tensix_sync(),
       the whole output data is corrupted, and only happens when the circular buffer data types
       are different from the previous operation. This one seems to be a race.
    */
    //tensix_sync();
    //binary_op_init_common(sin_cb, scalar_cb, untilized_sin_cb);
```

Moreover there is probably a race condition that I might have discovered while debugging this bug. This race is not present in this bug, but is worth exploring. See the comments at the bottom of the code snippet above. 

So far it seems this issue is the same as issue 1404.

**Comment by amahmudTT** [comment]
This PR fixes the reduced test case : https://github.com/tenstorrent/tt-metal/pull/15459
Need to test the big test with this and close this issue.

**Comment by amahmudTT** [comment]
Seems like there are two bugs in this test case, one race the other is the one mentioned above, which got fixed. The reduced test case now passes in the main branch but the original test case fails in certain scenarios and looks more like a race. Needs further investigation.

**Comment by amahmudTT** [comment]
```
 77     constexpr uint32_t untilized_sin_cb = get_compile_time_arg_val(14);
 78     constexpr uint32_t untilized_sin_sync_cb = get_compile_time_arg_val(15);
 79     constexpr uint32_t retilized_sin_cb = get_compile_time_arg_val(17);
 80     binary_op_init_common(sin_cb, untilized_sin_sync_cb, untilized_sin_cb);
 81     UNTILIZE_TILES(sin_cb, untilized_sin_cb, Wt);
 82     reconfig_data_format_srca(sin_cb, untilized_sin_cb);
 83     pack_reconfig_data_format(untilized_sin_cb, retilized_sin_cb);
 84     TILIZE_ROWS(untilized_sin_cb, untilized_sin_sync_cb, retilized_sin_cb, Wt);
 85     updated_sin_cb = retilized_sin_cb;
 86     uint32_t in1_idx = 0;
 87
 88     tensix_sync();
 89     UNPACK(print_full_tile(updated_sin_cb));
 90     tensix_sync();
 91
 92     for (uint32_t i = 0; i < num_rows; ++i) {
 93         for (uint32_t j = 0; j < Wt; ++j) {
 94             in1_idx = j;
 95             reconfig_data_format(in_cb, updated_sin_cb);
 96             pack_reconfig_data_format(retilized_sin_cb, out_cb);
 97             MUL_TILES(in_cb, updated_sin_cb, out_cb, onetile, in1_idx);
 98         }
 99     }
```

The output of the  ```UNPACK(print_full_tile(updated_sin_cb));``` , is different between the passing and failing test cases (where in_cb data type differs) although no code related to in_cb is executed, thus it indicates in the upper layers some data types / circular buffers are mixed up.

**Comment by amahmudTT** [comment]
Printing out the tiles looked different (in temrs of layout) when the format was bop_8 and float, but on further digging the bug was found to be in TileSlice code used for printing tiles. (https://github.com/tenstorrent/tt-metal/issues/15694) So this is not a NOC related issue as the input data comes in properly.

**Comment by amahmudTT** [comment]
Compared the assembly code of the two scenarios,   

Input Buffer type - float16 , Sine buffer type - float 16
Input Buffer type - bfp8 , Sine buffer type - bfp8

Since I do not use the input buffer at all, the assembly code of all the cores should be the same, but when I compare the assembly all of them match except the packer thread's code, and the difference is not just in jump instruction addresses but in loading of immediate values, which  indicates some config registers are written with different immediate values, now I need to find out which source code the assembly belongs to :D 

```
  461     603c:       45002637                lui     a2, 0x45002                                              |  461     603c:       45001637                lui     a2, 0x45001
  462     6040:       03960613                addi    a2, a2, 57 # 45002039 <__kernel_init_local_l1_base+0x44ff|  462     6040:       03960613                addi    a2, a2, 57 # 45001039 <__kernel_init_local_l1_base+0x44f
  463     6044:       00c7a023                sw      a2, 0(a5)                                                |  463     6044:       00c7a023                sw      a2, 0(a5)
  464     6048:       45040637                lui     a2, 0x45040                                              |  464     6048:       45020637                lui     a2, 0x45020
  465     604c:       03a60613                addi    a2, a2, 58 # 4504003a <__kernel_init_local_l1_base+0x4503|  465     604c:       03a60613                addi    a2, a2, 58 # 4502003a <__kernel_init_local_l1_base+0x450
  466     6050:       00c7a023                sw      a2, 0(a5)                                                |  466     6050:       00c7a023                sw      a2, 0(a5)
  467     6054:       45080637                lui     a2, 0x45080                                              |  467     6054:       45040637                lui     a2, 0x45040
  468     6058:       03b60613                addi    a2, a2, 59 # 4508003b <__kernel_init_local_l1_base+0x4507|  468     6058:       03b60613                addi    a2, a2, 59 # 4504003b <__kernel_init_local_l1_base+0x450
  469     605c:       00c7a023                sw      a2, 0(a5)                                                |  469     605c:       00c7a023                sw      a2, 0(a5)
```

**Comment by amahmudTT** [comment]
Found the bug, the difference in assembly was being produced by tilize_init_short and tilize_uninit, they had default argument for out_cb=16. 
That default argument was not passed by the programmer, that default argument was actually dependent on the input data type and not the value of the sine data type, as this was being read from the header files, there was no difference in the kernel source code but the assembly code. Fixing this fixes my test case. Need to test the original test and follow up with the bug discovered while creating a test case (does not affect our program)

**Comment by amahmudTT** [comment]
PR merged closing issue.
