### ISSUE TITLE
Tilize/Untilize: misc/test_untilize_test.py

### ISSUE THREAD

**Issue by ntarafdar** [tenstorrent/tt-metal#14061]
Shows up in blackhole, I think it's an alignment issue so if it is we can hold on it until the change is in.

**Comment by ntarafdar** [comment]
@https://github.com/tenstorrent/tt-metal/issues/14594

@jaykru-tt can you confirm that fixing the llk should fix this issue?

**Comment by jaykru-tt** [comment]
It's not totally clear to me but it's the most likely candidate. There might also be a problem in the writer, but it's hard to determine while the LLK is still producing junk data.
