### ISSUE TITLE
EMBEDDING: misc/test_rotary_embedding.py::test_rotary_embedding_decode_fp32 mismatching

### ISSUE THREAD

**Issue by ntarafdar** [tenstorrent/tt-metal#14064]
Decode tests are failing for fp32. The first 16 values of each row of the result are correct, but the next 16 values are wrong and lead to the failure.

**Comment by amahmudTT** [comment]
@ntarafdar  can you give me the command to reproduce this issue ? Or which test is failing exactly ?

**Comment by amahmudTT** [comment]
Borys's fix fixed this, but a relevant bug with much shared source code https://github.com/tenstorrent/tt-metal/issues/14063 , showed that there can be multiple bugs in the source code these two bugs are touching and sometimes they are passing by luck (a tile whose first row is used has other parts wrong). So I am planning to close these two bugs together, as closing this may reopening it even if a tiny change is made to the source code.

**Comment by amahmudTT** [comment]
This PR fixed this issue https://github.com/tenstorrent/tt-metal/pull/15459
