### ISSUE TITLE
Temporarily take tt-metal-ci-vm-112 out of CI Pool

### ISSUE THREAD

**Issue by tt-asaigal** [tenstorrent/tt-metal#14067]
This is needed for debug. Seems like an issue with recent changes is only reproducible on a set of CI machines including this.
Hanging suite on this machine: https://github.com/tenstorrent/tt-metal/actions/runs/11406333945/job/31740442870

**Comment by TT-billteng** [comment]
Is vm-112 still being used for this issue?
