### ISSUE TITLE
Bug in reading padded block shard tensors to host. 

### ISSUE THREAD

**Issue by sankarmanoj-tt** [tenstorrent/tt-metal#14081]
Padded Block Sharded Tensors are copied incorrectly to the host. 

Example:  A Tensor of Dimension (240, 256) block sharded across (8,4) cores. Each shard is of size (30,64), which gets padded to (32,64). 

When this tensor gets copied to the host, the padding value in each shard also gets copied. In the final tensor, (32,64) elements from the first shard gets copied to the host instead of (30,64), which pushes the data in the second shard to start from (32,0) instead of (30,0). 

Every subsequent shard gets pushed out, and the last shard is truncated.

**Comment by ntarafdar** [comment]
hey @sankarmanoj-tt can you provide a test with this failure?

**Comment by jvasilje** [comment]
@sankarmanoj-tt pls let the team know how to repro this. 

In the meantime, I'm closing the bug due to lack of an actionable description in the opened issue. @sankarmanoj-tt if you still have this problem, please re-open the issue with an actionable description. Thank you.
