### ISSUE TITLE
ttnn.tan low PCC

### ISSUE THREAD

**Issue by dveizovicTT** [tenstorrent/tt-metal#14086]
**Describe the bug**
ttnn.tan has low PCC for some inputs. For all failures PCC is around 0.993

**To Reproduce**
Checkout branch: dveizovic/sweeps-migration
Sweep test for tan is located in 'tests/sweep_framework/sweeps/eltwise/unary/tan/tan.py'
1. Go to 'tests/sweep_framework/sweeps/eltwise/unary_backward/rdiv_bw/rdiv_bw.py'
2. Generate new parameter vectors and run the sweep test
```
python3 tests/sweep_framework/parameter_generator.py --elastic cloud --module-name eltwise.unary.tan.tan
python3 tests/sweep_framework/runner.py --elastic cloud --module-name eltwise.unary.tan.tan --suite-name nightly
```
4. See the error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by eyonland** [comment]
I'm not finding the tests you mentioned above.  Are they on a different branch?

**Comment by mouliraj-mcw** [comment]
Hi @dveizovicTT ,

Currently, during testing, I did not observe any picture drops for this test.
Could you please verify and confirm so that we can proceed to close this ticket?
