### ISSUE TITLE
ttnn.polar low PCC on GS

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#14092]
**Describe the bug**
ttnn.polar has low PCC on GS machine

**To Reproduce**
Sweep test for polar is located in 'tests/sweep_framework/sweeps/eltwise/unary_complex/polar/polar.py'
1. Checkout branch amalbasaTT/complex_ops-sweeps (soon to be merged on main)
1. Go to 'tests/sweep_framework/sweeps/eltwise/unary_complex/polar/polar.py'
2. Make sure your are on a machine with Grayskull
3. Generate new parameter vectors and run the sweep test
```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.unary_complex.polar.polar
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.unary_complex.polar.polar
```
5. See the error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by VirdhatchaniKN** [comment]
Since the issue is specific to GS, Will close issue based on https://github.com/tenstorrent/tt-metal/issues/13739#issuecomment-2455186390
