### ISSUE TITLE
Support ROPE op for Llama in decode mode 

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent/tt-metal#14107]
Today, ROPE in decode mode is implemented as a matmul, where rot_mat is precomputed on host based on the sin/cos for each user's position_id.

What we want is for the `sin,cos: [max_seq_len=128k, head_dim=128]` matrices to exist on device. In decode mode, the top of the model should use `position_ids: [batch]` to select sin/cos values with a `ttnn.embedding` op.
Inside of attention, the `rotary_embedding_llama` op should be modified to accept decode-shaped `sin`, `cos`, and `x` inputs.

We can expect `x` to be of shape
```
xq: [1, batch, nh, dhead]
xk: [1, batch, nkv, dhead]
```
with reasonable values for those dims.

Decode mode ROPE should be no slower than 4µs, and accept x sharded by height (refer to Llama code for exactly how inputs will be formatted).

**Comment by avoraTT** [comment]
With the following PR:
- #14241 

Here's a breakdown of the perf for an iteration with `batch=32`, `n_heads=8`, `n_kv_heads=1` and `dhead=128` (which is the llama3 70b case):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/avora/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/avora/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">


OP CODE | DEVICE FW DURATION [ns] | DEVICE KERNEL DURATION [ns]
-- | -- | --
Embeddings | 2525 | 1724
Embeddings | 2489 | 1717
TilizeWithValPadding | 18141 | 17611
TilizeWithValPadding | 18227 | 17702
InterleavedToShardedDeviceOperation | 3075 | 2251
InterleavedToShardedDeviceOperation | 3170 | 2344
RotaryEmbeddingLlama | 4501 | 3820
RotaryEmbeddingLlama | 4485 | 3836



</body>

</html>
