### ISSUE TITLE
ttnn.max_bw low PCC

### ISSUE THREAD

**Issue by dveizovicTT** [tenstorrent/tt-metal#14136]
**Describe the bug**
ttnn.max_bw has low PCC for some inputs. For all failures PCC is around 0.998

**To Reproduce**
Checkout branch: dveizovic/binary-bw-ops-migration
Sweep test for tan is located in 'tests/sweep_framework/sweeps/eltwise/binary_backward/max_bw/max_bw.py'
1. Go to 'tests/sweep_framework/sweeps/eltwise/unary_backward/rdiv_bw/rdiv_bw.py'
2. Generate new parameter vectors and run the sweep test
```
python3 tests/sweep_framework/parameter_generator.py --elastic cloud --module-name eltwise.binary_backward.max_bw.max_bw
python3 tests/sweep_framework/runner.py --elastic cloud --module-name eltwise.binary_backward.max_bw.max_bw --suite-name nightly
```
4. See the error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by VirdhatchaniKN** [comment]
Hi @dveizovicTT ,
I ran the above mentioned sweep test and found that the test has also been written for ROW_MAJOR Layout and bfloat8_b datatype. But according to the documentation,
![Image](https://github.com/user-attachments/assets/6c25447d-9a97-4d84-8e52-af903449aad1)
`ttnn.max_bw` only supports bfloat16 with TILE Layout combination.
 
Updating the test with above changes passes the test
![Image](https://github.com/user-attachments/assets/d21ff089-4ec2-4429-8819-4c843b4ca896)

**Comment by VirdhatchaniKN** [comment]
From PR https://github.com/tenstorrent/tt-metal/pull/14133 , ![Image](https://github.com/user-attachments/assets/246292cc-b05f-480b-8abd-1464229f9aa9)
`final_test` suite is passing, Hence closing issue
