### ISSUE TITLE
Incomplete documentation: min_bw, max_bw

### ISSUE THREAD

**Issue by dveizovicTT** [tenstorrent/tt-metal#14137]
ttnn.min_bw and ttnn.max_bw are failing due to _**Unsupported data type!**_ when first tensor is blofat8.

This is not documented in official documentation for these two ops.

**Comment by KalaivaniMCW** [comment]
Updated doc 
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/af39d98b-0c63-47e2-ae31-7cb7a7391cb9">

<img width="992" alt="image" src="https://github.com/user-attachments/assets/cc8b568d-fd70-4efa-a94f-d0f574f08da9">
