### ISSUE TITLE
ttnn.polar_bw binary inconsistent documentation regarding the input tensors datatype

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#14144]
ttnn.polar_bw doesn't support bfloat8_b on input_tensor_a. Fatal error "Unsupported DataType" is thrown when input_tensor_a has bfloat8_b.

**To Reproduce (MAKE SURE YOU ARE ON A WORMHOLE MACHINE)**
Sweep test for polar_bw is located in 'tests/sweep_framework/sweeps/eltwise/unary_complex/polar_bw/polar_bw.py'
1. Checkout main branch
3. Go to 'tests/sweep_framework/sweeps/eltwise/unary_complex/polar_bw/polar_bw.py'
4. Remove next lines of code from the invalidate_vector function:
```
    if test_vector["input_a_dtype"] == ttnn.bfloat8_b:
        return True, "bfloat8_b is not supported on input_tensor_a"
```
5. Generate new parameter vectors and run the sweep test
```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.unary_complex.polar_bw.polar_bw
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.unary_complex.polar_bw.polar_bw 
```
6. See error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Expected behavior**
For vectors with `input_a_dtype` being bfloat8_b, test will fail with the message "Unsupported DataType".

**Comment by mouliraj-mcw** [comment]
Closing as completed
