### ISSUE TITLE
ViT e2e perf with trace_2cq hung on WH-N300

### ISSUE THREAD

**Issue by kkeerthana0573** [tenstorrent/tt-metal#14205]
**Describe the bug**
We are bringing up e2e performance test for Squeezebert and VGG models using trace_2cq,  following the setup used in [vit_ttnn_inference_perf_e2e_2cq_trace](https://github.com/tenstorrent/tt-metal/blob/main/models/demos/wormhole/vit/demo/demo_vit_ttnn_inference_perf_e2e_2cq_trace.py). However, the test for demo_vit_ttnn_inference_perf_e2e_2cq_trace appears to hang.  We waited for 25 minutes before terminating the test manually.

**To Reproduce**
1. Set `export WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml`.
2. Run ViT inference test using `pytest --disable-warnings  models/demos/wormhole/vit/demo/demo_vit_ttnn_inference_perf_e2e_2cq_trace.py`

**Expected behavior**
Expected to pass the test

Please complete the following environment information:
OS: [e.g. Ubuntu 20.04]
Devices: WH(n300)

**Comment by kkeerthana0573** [comment]
cc: @boris-drazic, @saichandax, @vigneshkeerthivasanx

**Comment by kkeerthana0573** [comment]
@mbahnasTT, 
We came across [AdvancedPerformanceOptimizationsForModels](https://github.com/tenstorrent/tt-metal/blob/main/tech_reports/AdvancedPerformanceOperationsForModels/AdvancedPerformanceOptimizationsForModels.md) while exploring about Trace and Command Queues. 
Could you please help us with any missing/additional information regarding [vit_ttnn_inference_perf_e2e_2cq_trace](https://github.com/tenstorrent/tt-metal/blob/main/models/demos/wormhole/vit/demo/demo_vit_ttnn_inference_perf_e2e_2cq_trace.py) and e2e perf trace_2cq?

**Comment by kkeerthana0573** [comment]
The `vit_ttnn_inference_perf_e2e_2cq_trace` test is currently on the main branch.

The following environment variables were set before running the test:

> export ARCH_NAME=wormhole_b0
> export TT_METAL_HOME=$(pwd)
> export PYTHONPATH=$(pwd)
> export WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml
> export TT_METAL_ENV=dev

A profiler build was then executed with these steps:

> ./build_metal.sh -p

The test was initiated with:

`pytest --disable-warnings models/demos/wormhole/vit/demo/demo_vit_ttnn_inference_perf_e2e_2cq_trace.py
`  as directed in the[ README.md](https://github.com/tenstorrent/tt-metal/blob/main/models/demos/wormhole/vit/README.md).

However, the test appears to hang during execution on n300.

**Comment by saichandax** [comment]
@mbahnasTT , closing this issue, as we are not refering to ViT for implementing trace+2cqs. We are refering to RN50 implementation.

This issue might be still persisting, however, we are not blocked by it. Re-open, if it needs to be tracked further.

Thank you.
