### ISSUE TITLE
Investigate why the GitHub `tt-metal-ci-vm-105` seems to not have killed its test before letting other jobs on

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#14225]
@blozano-tt 's workflow triggered on a run on vm-105: https://github.com/tenstorrent/tt-metal/actions/runs/11491670594/job/31984727604

that seems to have timed out

Then Aswin noticed that processes were still on the cards: https://github.com/tenstorrent/tt-metal/actions/runs/11492895955/job/31988153030

We don't kill the processes in the reset script, so the reset script would fail, and it would pick up another job, causing CI to fail in a death loop.

On the runner, I see

```
● actions.runner.tenstorrent-tt-metal.tt-metal-ci-vm-105.service - GitHub Actions Runner (tenstorrent-tt-metal.tt-metal-ci-vm-105)
     Loaded: loaded (/etc/systemd/system/actions.runner.tenstorrent-tt-metal.tt-metal-ci-vm-105.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-10-23 15:26:14 UTC; 23h ago
   Main PID: 1203 (runsvc.sh)
      Tasks: 56 (limit: 56657)
     Memory: 452.3M
     CGroup: /system.slice/actions.runner.tenstorrent-tt-metal.tt-metal-ci-vm-105.service
             ├─  1203 /bin/bash /home/ubuntu/actions-runner/runsvc.sh
             ├─  1369 ./externals/node16/bin/node ./bin/RunnerService.js
             ├─  1512 /home/ubuntu/actions-runner/bin/Runner.Listener run --startuptype service
             ├─696278 /home/ubuntu/actions-runner/externals.2.320.0/node20/bin/node /home/ubuntu/actions-runner/_work/_actions/catchpoint/workflow-telemetry-action/v2/dist/scw/index.js
             ├─696313 sudo /home/ubuntu/actions-runner/_work/_actions/catchpoint/workflow-telemetry-action/v2/dist/proc-tracer/proc_tracer_ubuntu-20 -f json -o /home/ubuntu/actions-runner/_work/_actions/catchpoint/workflow-telemetry-action/v2/d…
             ├─696331 /bin/bash ./tests/scripts/run_tests.sh --tt-arch grayskull --pipeline-type post_commit --dispatch-mode slow
             ├─696332 /bin/bash ./tests/scripts/run_pre_post_commit_regressions_slow_dispatch.sh
             ├─696333 /bin/bash ./tests/scripts/run_cpp_fd2_tests.sh
             ├─696334 ./build/test/tt_metal/perf_microbenchmark/dispatch/test_prefetcher -t 0 -i 5
             └─696335 /home/ubuntu/actions-runner/_work/_actions/catchpoint/workflow-telemetry-action/v2/dist/proc-tracer/proc_tracer_ubuntu-20 -f json -o /home/ubuntu/actions-runner/_work/_actions/catchpoint/workflow-telemetry-action/v2/dist/p…
```

that this process

```
ubuntu    696334 99.1  0.0 2393884 2892 ?        Rl   02:57 687:57 ./build/test/tt_metal/perf_microbenchmark/dispatch/test_prefetcher -t 0 -i 5
```

is still taking up the card.

Is the telemetry action doing this? cc: @ttmchiou 

Anyway, this is not high priority and seems like a rare bug. Rebooting the runner.

**Comment by tt-aho** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11506113457/job/32029317045
Hit a similar issue on vm-10

**Comment by tt-rkim** [comment]
These are both grayskull machines... how could this be happening...

**Comment by tt-rkim** [comment]
I'm taking a LOOOOOOONG vacation.

## So what the hell was happening?

We were seeing VMs actually have processes use the card during startup, such as pointed out by @tt-aho : https://github.com/tenstorrent/tt-metal/actions/runs/11506113457/job/32029317045

Tracing the history of jobs on bad VMs, such as the history of `tt-metal-ci-vm-123`, by looking at the `Worker` logs in `_diag` on the runner, we can eventually get back to the last job that didn't die this way during startup for a runner in this state: https://github.com/tenstorrent/tt-metal/actions/runs/11503999936/job/32023823559

The logs typically something like:

```
tests/ttnn/unit_tests/operations/test_moreh_norm.py::test_moreh_norm_backward[ttnn_dtype=DataType.BFLOAT16-keepdim=True-input_shape=[32, 32]-global_norm(dim=None)-p=2.0]                  Device | INFO     | Opening user mode device driver
2024-10-24 18:59:31.689 | INFO     | SiliconDriver   - Detected 1 PCI device : [0]
2024-10-24 18:59:31.730 | WARNING  | SiliconDriver   - init_detect_tt_device_numanodes(): Could not determine NumaNodeSet for TT device (physical_device_id: 0 pci_bus_id: 0000:07:00.0)
2024-10-24 18:59:31.730 | WARNING  | SiliconDriver   - Could not find NumaNodeSet for TT Device (physical_device_id: 0 pci_bus_id: 0000:07:00.0)
2024-10-24 18:59:31.731 | WARNING  | SiliconDriver   - bind_area_memory_nodeset(): Unable to determine TT Device to NumaNode mapping for physical_device_id: 0. Skipping membind.
2024-10-24 18:59:31.731 | WARNING  | SiliconDriver   - ---- ttSiliconDevice::init_hugepage: bind_area_to_memory_nodeset() failed (physical_device_id: 0 ch: 0). Hugepage allocation is not on NumaNode matching TT Device. Side-Effect is decreased Device->Host perf (Issue #893).
                  Metal | INFO     | Initializing device 0. Program cache is NOT enabled
                  Metal | INFO     | AI CLK for device 0 is:   1202 MHz
2024-10-24 18:59:43.815 | INFO     | tests.ttnn.unit_tests.operations.test_moreh_norm:run_moreh_norm_backward:231 - input_grad's Max ATOL Delta: 1.020126223564148, Max RTOL Delta: 84.22364807128906
FAILED                  Metal | INFO     | Closing device 0
2024-10-24 18:59:49.484 | INFO     | SiliconDriver   - Waiting for core (x=11,y=10) to recieve mem bar flag 170 in function
2024-10-24 18:59:49.484 | INFO     | SiliconDriver   - Waiting for core (x=9,y=11) to recieve mem bar flag 170 in function
2024-10-24 18:59:49.484 | INFO     | SiliconDriver   - Waiting for core (x=11,y=11) to recieve mem bar flag 170 in function
...
```

For whatever reason, UMD is not able to get past this check. It then continues to dump and dump gigabytes of logs to `INFO` level (THIS SHOULD BE DEBUG AHHH cc: @blozano-tt ). The check itself is in `tt-umd/device/tt_silicon_driver.cpp:set_membar_flag`. This never seems to pass for a device in this state.

However - we run the test in docker. The default driver is JSON logs, so it actually saves logs to device!!! cc: @dimitri-tenstorrent @ttmchiou . For example, the file `/var/lib/docker/containers/f03c947b341dcc988a0d4cfa3f999a20eb9b13b493199ed527c4dc2b13e5ca87/f03c947b341dcc988a0d4cfa3f999a20eb9b13b493199ed527c4dc2b13e5ca87-json.log` on `vm-123` was like 45GB big.

This means that some JSON file that stores the logs from the test container keeps growing in size. Eventually, it reaches 40GB+. This then causes the runner to run out of space, and the test dies. However, the runner is not able to `sudo kill -9` because there's no disk space at the end of a test, so the process becomes orphaned. This is why the next job still detects a process using the card.

I'm wondering what kind of instability we introduced recently for this membar flag thing.

**Comment by tt-rkim** [comment]
## What's next?

We need to investigate we started running into:

```
2024-10-24 18:59:49.484 | INFO     | SiliconDriver   - Waiting for core (x=11,y=10) to recieve mem bar flag 170 in function
2024-10-24 18:59:49.484 | INFO     | SiliconDriver   - Waiting for core (x=9,y=11) to recieve mem bar flag 170 in function
2024-10-24 18:59:49.484 | INFO     | SiliconDriver   - Waiting for core (x=11,y=11) to recieve mem bar flag 170 in function
...
```

upon close device.

@pgkeller @tt-aho Do you guys have any insight why this start happening on GS on close device?

**Comment by tt-rkim** [comment]
We're seeing it on WH too!!!!

https://github.com/tenstorrent/tt-metal/actions/runs/11510092733/job/32041509946

**Comment by tt-rkim** [comment]
Related to: https://github.com/tenstorrent/tt-metal/issues/14248

**Comment by tt-rkim** [comment]
This is still happening: https://github.com/tenstorrent/tt-metal/actions/runs/11640859174/job/32418852996

even with `--log-driver none` set...

I'm gonna try using another option to help out with rotation.

`--log-opt max-size=100m`

**Comment by tt-rkim** [comment]
Never mind - you can't use that with `none` log driver.

THIS IS SO JANK
