### ISSUE TITLE
Maxpool2D block sharding bug

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#14249]
Branch: `asarje/maxpool-block-bug`
Unit test: `tests/ttnn/unit_tests/operations/test_maxpool2d.py::test_run_max_pool_block_shard`
(Shape = [1, 512, 10, 10], kernel_size = (5,5), padding = (2, 2), stride = (1, 1))

The output PCC is bad -- output tensor seems to have some junk values mixed in.

**Comment by punithsekar** [comment]
@mywoodstock @wransom-TT, Not only the above mentioned configurations are making issues.
Even the following configurations also give a bad PCC,
(Shape = [1, 512, 10, 10], kernel_size = (9,9), padding = (4, 4), stride = (1, 1)) 
(Shape = [1, 512, 10, 10], kernel_size = (13,13), padding = (6, 6), stride = (1, 1))

**Comment by mywoodstock** [comment]
@punithsekar yes, they are all the same issue -- basically related to kernel sizes larger then 4x4. We are looking into this.

**Comment by punithsekar** [comment]
Thanks for the acknowledgment, Abhinav. Since you mentioned specific configurations, I’ve added them.
