### ISSUE TITLE
ttnn.sum operation does work when input tensor is rank 2 or 3

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#14285]
ttnn.sum operation does work when input tensor is rank 2 or 3, which is not covered in documentation.

We are getting:

```
Always | FATAL    | Tensor rank is not 4
TT_FATAL @ ../ttnn/cpp/ttnn/operations/data_movement/pad/pad.cpp:41: rank == 4
info:
```

* Steps to reproduce

Checkout main branch.

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/reduction/sum.py`. To run:

```
python3 tests/sweep_framework/runner.py --elastic cloud --module-name reduction.sum
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by bbradelTT** [comment]
@nemanjagrujic this should be fixed now, at least for most scenarios. Could you please test if your scenarios are covered, and either
- provide specific examples that you still need to work that aren't or
- close this issue?

**Comment by nemanjagrujic** [comment]
@bbradelTT  Seems to be working now
