### ISSUE TITLE
ttnn.remainder_bw binary inconsistent documentation regarding the supported architecture types

### ISSUE THREAD

**Issue by amalbasaTT** [tenstorrent/tt-metal#14293]
ttnn.remainder_bw binary doesn't support Grayskull architecture type. Fatal error "UnaryOpType '67' is not supported on Grayskull architecture" is thrown.
 
**To Reproduce**
Sweep test for remainder_bw is located in 'tests/sweep_framework/sweeps/eltwise/binary_backward/remainder_bw/remainder_bw.py'
1. Checkout branch amalbasaTT/backward_ops-sweeps-4 (soon to be merged to main)
2. Make sure you are on Grayskull machine
3. Go to 'tests/sweep_framework/sweeps/eltwise/binary_backward/remainder_bw/remainder_bw.py'
4. Remove `mesh_device_fixture` function
5. Generate new parameter vectors and run the sweep test
```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.binary_backward.remainder_bw.remainder_bw
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.binary_backward.remainder_bw.remainder_bw 
```
6. See error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Expected behavior**
Test cases will fail with message "UnaryOpType '67' is not supported on Grayskull architecture".

**Comment by mouliraj-mcw** [comment]
closing as completed. (https://github.com/tenstorrent/tt-metal/issues/14145)
