### ISSUE TITLE
repeat_interleave hang

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent/tt-metal#14310]
## Problem Description
I found that on commit https://github.com/tenstorrent/tt-metal/commit/d1a10ea9a9ec91d4730500bc86fa8c4bc398579f, the following test case consistently hangs. I have not been able to repro a hang on the parent commit.

I have also found that the hang does not repro if async runtime is disabled. Since `d1a10ea9a9` moved certain reshapes to host, it must be the case that in async mode the `tensor.cpu()` call is hanging. 

While I know this particular commit will be reverted, I think it is worthwhile to investigate anyways since the hang is unexpected and will show up again when `d1a10ea9a9` is reintroduced.

```
@pytest.mark.parametrize(
    "mesh_device",
    [
        (1, 2),
    ],
    indirect=True,
)
def test_repeat_interleave_hang(mesh_device, use_program_cache):
    mesh_device.enable_async(True)
    dtype = ttnn.bfloat16
    repeats = 4
    dim = 1
    

    for i in range(100000):
        logger.info(f"iteration {i}")
        input_tensor = ttnn.from_torch(torch.rand(1, 4, 6528, 128), layout=ttnn.TILE_LAYOUT, dtype=dtype, device=mesh_device, mesh_mapper=ttnn.ReplicateTensorToMesh(mesh_device))
            
        output = ttnn.repeat_interleave(input_tensor, 4, dim=1)
        pt_output = ttnn.to_torch(output, mesh_composer=ttnn.ConcatMeshToTensor(mesh_device, dim=0))
```

## Machine details
I reproed on `sjc-snva-t3010`, using a 1x2 mesh to run the test.

**Comment by cglagovichTT** [comment]
I created this as P1 since the problem commit has been reverted but I am leaning toward P0 because the commit uncovered an async runtime hang.

**Comment by tt-asaigal** [comment]
Hey @cglagovichTT please try the test with the commit staged on this PR: https://github.com/tenstorrent/tt-metal/pull/14322. 
The reshape changes ended up exposing a deadlock that the commit should resolve.

**Comment by cglagovichTT** [comment]
This fixed it! Thanks a ton for the quick solution!

**Comment by nttng207** [comment]
@tt-asaigal I just faced this issue (hanging when call tensor.cpu())
`b, c, h, w = tuple(self.image_encoder.features.layer2.output_shape)
image_features = ttnn.reshape(ttnn.to_layout(image_features, ttnn.ROW_MAJOR_LAYOUT), (b, h, w, c))
image_embd_layer2 = self.avgpool_img(image_features)`
`self.avgpool_img` is `fallback_ops.AdaptiveAvgPool2d`, the code hanging when executing `conversion_wrapper.py` (`convert_tt_tensor_to_pt_tensor`)
