### ISSUE TITLE
l1_banking_allocator.cpp needs MEM_MAILBOX_BASE

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-metal#14329]
https://github.com/tenstorrent/tt-metal/blob/ada4ad8a44d37d57833edfe80eea4a3cb9f03525/tt_metal/impl/allocator/l1_banking_allocator.cpp#L173

l1_banking_allocator.cpp needs MEM_MAILBOX_BASE

Should we put MEM_MAILBOX_BASE behind Hal?

**Comment by abhullar-tt** [comment]
I think it makes sense to put this under the HAL.
