### ISSUE TITLE
Need support for MultiheadAttention op

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#14337]
Describe the bug
Need support for MultiheadAttention layer for PETR model
Torch link: https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html
Model card: https://github.com/tenstorrent/tt-metal/issues/14296

Torch example:
```
multihead_attn = nn.MultiheadAttention(embed_dim, num_heads)
attn_output, attn_output_weights = multihead_attn(query, key, value)
```

device: WH N150

**Comment by dvartaniansTT** [comment]
@keerthana-r-mcw please add details and proper description to this issue, add torch examples ...

**Comment by keerthana-r-mcw** [comment]
@punithsekar FYR

**Comment by keerthana-r-mcw** [comment]
Closing this issue, since it's implemented
