### ISSUE TITLE
misc/test_softmax.py::test_softmax PCC failure with float32

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-metal#14348]
Command to run:
`pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py` (there are other tests, output shown below)

or
`pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax` just for this test.

```
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[True-bfloat16]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[False-bfloat16]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_with_program_cache[True]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_with_program_cache[False]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[True-bfloat16]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[True-bfloat8_b]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[False-bfloat16]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[False-bfloat8_b]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-no-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-no-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-no-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-no-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax[bfloat16-in0_DRAM]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax[bfloat8_b-in0_DRAM]
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[True-float] - AssertionError: FAILED: 0.7438545260666998
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[False-float] - AssertionError: FAILED: 0.7438815564487562
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-causal-64] - AssertionError: FAILED: 0.4560745921843578
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-causal-384] - AssertionError: FAILED: 0.29388434435907
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-no-causal-64] - AssertionError: FAILED: 0.4226715140500547
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-no-causal-384] - AssertionError: FAILED: 0.2886772491603555
```

**Comment by prajaramanTT** [comment]
@bbradelTT Can we close this ?

**Comment by ncvetkovicTT** [comment]
@prajaramanTT Please note that if you're basing this off of the previous comment, it in fact isn't correct, #14352 and this issue don't have the same common cause.

**Comment by bbradelTT** [comment]
@prajaramanTT we can't close this. We can only close these issues after all the relevant tests pass and we make the tests run again in pipelines (remove the skip for blackhole in the code).

**Comment by ncvetkovicTT** [comment]
Will check if all the tests pass after #15754 is merged

**Comment by ncvetkovicTT** [comment]
I have accidentally enabled all tests from ```test_softmax.py``` within PR #15754. I pulled the latest main and fortunately the tests pass, meaning that we can close this as well:
```
=========================================================================================================================================================================================================== short test summary info ============================================================================================================================================================================================================
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[True-bfloat16]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[True-float]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[False-bfloat16]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[False-float]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_with_program_cache[True]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_with_program_cache[False]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[True-bfloat16]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[True-bfloat8_b]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[False-bfloat16]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[False-bfloat8_b]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-no-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-no-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-no-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-no-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-no-causal-64]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-no-causal-384]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax[bfloat16-in0_DRAM]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax[bfloat8_b-in0_DRAM]
======================================================================================================================================================================================================= 24 passed, 24 warnings in 16.75s =======================================================================================================================================================================================================
```

**Comment by abhullar-tt** [comment]
> I have accidentally enabled all tests from `test_softmax.py` within PR [#15754](https://github.com/tenstorrent/tt-metal/pull/15754). I pulled the latest main and fortunately the tests pass, meaning that we can close this as well:
> 
> ```
> =========================================================================================================================================================================================================== short test summary info ============================================================================================================================================================================================================
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[True-bfloat16]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[True-float]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[False-bfloat16]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax[False-float]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_with_program_cache[True]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_with_program_cache[False]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[True-bfloat16]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[True-bfloat8_b]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[False-bfloat16]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_softmax_mix_precision[False-bfloat8_b]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.thatpy::test_scale_mask_softmax_inplace[float32-in0_DRAM-causal-64]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-causal-384]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-no-causal-64]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[float32-in0_DRAM-no-causal-384]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-causal-64]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-causal-384]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-no-causal-64]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat16-in0_DRAM-no-causal-384]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-causal-64]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-causal-384]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-no-causal-64]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax_inplace[bfloat8_b-in0_DRAM-no-causal-384]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax[bfloat16-in0_DRAM]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py::test_scale_mask_softmax[bfloat8_b-in0_DRAM]
> ======================================================================================================================================================================================================= 24 passed, 24 warnings in 16.75s =======================================================================================================================================================================================================
> ```

thats a nice accident :)
