### ISSUE TITLE
Transpose BH DRAM Alignment 

### ISSUE THREAD

**Issue by ntarafdar** [tenstorrent/tt-metal#14360]
CC: @abhullar-tt 

Transpose kernel needs to be aligned to BH Dram, seems to be hardcoded to 32B in the kernel for reading

**Comment by sjameelTT** [comment]
Is this the same as #12549?

**Comment by sjameelTT** [comment]
#14609 is blocking further investigation of transposes with W as tilize_block is not working
#13609 will fix the RM related kernels out of the box

**Comment by sjameelTT** [comment]
Blackhole transpose issues are now all accounted for; any other alignment is fixed by `abhullar/diff-aligns` and the WH transpose issues are LLK related.
