### ISSUE TITLE
[Bug Report] RuntimeArgsData::operator[] is not inlined but called very often.

### ISSUE THREAD

**Issue by dmakoviichuk-tt** [tenstorrent/tt-metal#14367]
**Describe the bug**
operator[] implementation is in the cpp and not inlined.
**To Reproduce**
Run any op.
**Expected behavior**
It should be inlined.

**Screenshots**
![Screenshot 2024-10-27 at 1 10 10 PM](https://github.com/user-attachments/assets/7fa0810a-29b3-4b22-9e8b-f5866b0d224a)

**Comment by dmakoviichuk-tt** [comment]
@blozano-tt ptal

**Comment by blozano-tt** [comment]
We can use this alternative approach to keep the operator[] inlined:

https://github.com/tenstorrent/tt-metal/pull/13956/files
