### ISSUE TITLE
[Perf] tt: :tt_metal::allocator::FreeList::deallocate is very slow for nanogpt training

### ISSUE THREAD

**Issue by dmakoviichuk-tt** [tenstorrent/tt-metal#14374]
**Describe the bug**
tt: :tt_metal::allocator::FreeList::deallocate takes  ~5% of the total host time during nanogpt training.

**To Reproduce**
Run nanogpt training.

**Expected behavior**
It should be faster.
**Screenshots**

**Comment by abhullar-tt** [comment]
Hey Denys, this is something that has come up before. I haven't had the chance to look into optimizing it but there definitely is  room for optimizations in trying to deduce where the block to free should be inserted back into the free list.

**Comment by dmakoviichuk-tt** [comment]
hi @abhullar-tt  I think current freelist allocator could be slightly optimized overall but algo will remain the same. Not sure if it help a lot.

**Comment by abhullar-tt** [comment]
> Member

We previously talked about exploring something like: http://www.gii.upv.es/tlsf/

**Comment by dmakoviichuk-tt** [comment]
@abhullar-tt  looks interesting.
But as a first step I think it is good to optimize existing one to make sure we don't add new issues.

**Comment by abhullar-tt** [comment]
> [@abhullar-tt](https://github.com/abhullar-tt) looks interesting. But as a first step I think it is good to optimize existing one to make sure we don't add new issues.

Yes definitely agree and know there is room to optimize existing implementation

**Comment by prajaramanTT** [comment]
@dmakoviichuk-tt Can you add priority to this ticket ?

**Comment by abhullar-tt** [comment]
@prajaramanTT Marty actually opened up a PR for allocator optimziation: https://github.com/tenstorrent/tt-metal/pull/15536

@dmakoviichuk-tt do you think you could test with this change?

**Comment by dmakoviichuk-tt** [comment]
@abhullar-tt  closing it for now. I don't see it in the profiler for my case. But might reopen in future.
