### ISSUE TITLE
asserts running CI

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#14382]
at minimum, sweeping test_prefetcher asserts in CI
check if anything else asserts
then enable asserts in CI so we don't break in the future

**Comment by pgkeller** [comment]
@nhuang-tt is this fixed?  If so, please close, thanks

**Comment by nhuang-tt** [comment]
It's fixed but the assertions don't run in CI because it's using Release build. To enable Debug / RelWIthDebIngo tests and builds in CI would need more capacity which seems to be constrained at the moment
