### ISSUE TITLE
Disassembler crashes while disassembling. 

### ISSUE THREAD

**Issue by amahmudTT** [tenstorrent/tt-metal#14398]
**Describe the bug**
Branch : https://github.com/tenstorrent/tt-metal/compare/main...amahmud/fp32_perf
Test case : tests/tt_metal/tt_metal/test_eltwise_add.cpp

This test case has empty reader and writer, it will compile and theoretically should work. But when we built the files and tried to disassemble the trisc0/1/2.elf files, it shows the disassembly but crashes in the end saying segmentation fault. So piping the output to a file is problematic. 

**To Reproduce**
1. Checkout the branch. 
2. Compile the C++ tests
3. Run the test test_eltwise_add , it should be in ```tt-metal/build_Release/test/tt_metal```
4. Try to disassemble the trisc.0/1/2 files which should be in a subfolder in ```tt-metal/built``` folder
My disassembly command was as follows : ```$tt_dir/tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-objdump -D -S -t -g -C```

The disassembler should crash with Segmentation Fault message.

**environment information:**
- OS: [e.g. Ubuntu 20.04]
- Wormhole_b0

**Additional context**
This test case is unique as the readers and writers are empty. I managed to get the assembly output to a file using linux script command. Hence the ^M

![Screenshot 2024-10-28 at 5 18 17 PM](https://github.com/user-attachments/assets/dc0df6fa-0236-4a1d-8a63-914c2333c1b6)

**Comment by nathan-TT** [comment]
Is there a reason you're using -D rather than -d (disassembling all sections, rather than just executable ones)

**Comment by amahmudTT** [comment]
> Is there a reason you're using -D rather than -d (disassembling all sections, rather than just executable ones)

No, I think it was a mistake in my part

**Comment by nathan-TT** [comment]
ok, use '-d' the crash is happening because the section (.comment) is not an integral number of instructions.  Here's a smaller reproducer:
```
	.text
        lui a0,0x12345
        addi a0,a0,0x678
	.byte 2 ;; delete to remove crash
```
```
tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-as -o asm.o asm.s
tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-objdump -d asm.o
```
(because this is .text it'll crash with -d)

**Comment by amahmudTT** [comment]
You meant crash with -D and not -d ?

**Comment by nathan-TT** [comment]
no, that shorter example is an oddly-sized executable section, which both -d and -D attempt to disassemble

**Comment by amahmudTT** [comment]
Ok, so is it still a bug then ? Or did I just use the wrong command ?

**Comment by nathan-TT** [comment]
it is still a bug, but won't normally affect things -- use -d and usually text sections are integral numbers of instructions

**Comment by amahmudTT** [comment]
ok

**Comment by nathan-TT** [comment]
I have a fix, which I'll fold into the next compiler release -- unless you need it sooner. (the next release should be in the next month)

**Comment by amahmudTT** [comment]
Thanks, I am not in any urgent need. I was able to dump the things I needed using the script command, (It had ^M) at the end of every line.

**Comment by pgkeller** [comment]
@nathan-TT did the fix mentioned above get released?

**Comment by nathan-TT** [comment]
> [@nathan-TT](https://github.com/nathan-TT) did the fix mentioned above get released?

oh, yes it will have been as a side-effect of the move off LFS
