### ISSUE TITLE
ttnn.add example shared in TTNN API documentation fails from main and from v0.52.0 tag 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#14448]
**Describe the bug**
Please see the code sample bellow which is borrowed from [TTNN API documentation examples](https://docs.tenstorrent.com/ttnn/latest/ttnn/ttnn/add.html#ttnn-add)

It errors out with: (also see the screen-shot attached)

                 `Always | FATAL    | Index is out of bounds for the rank, should be between 0 and 0 however is 18446744073709551615`

**To Reproduce**
1. build from v0.52.0
2. run the code bellow
3. See error

**Code**
`device_params = {"l1_small_size": 24576}
device = ttnn.open_device(device_id=0, **device_params)

print ("trying now =====")

tensor1 = ttnn.to_device(ttnn.from_torch(torch.tensor((1, 2), dtype=torch.bfloat16)), device)
tensor2 = ttnn.to_device(ttnn.from_torch(torch.tensor((0, 1), dtype=torch.bfloat16)), device)

output = ttnn.add(tensor1, tensor2)

print("tensor1 shape:", tensor1.shape)
print("tensor2 shape:", tensor2.shape)`

**Expected behavior**
examples on the documentation should run with no error or if additional parameters are needed to be set, it should be included in the documentation example. 

**Screenshots**
<img width="1727" alt="Screenshot 2024-10-29 at 2 15 48 PM" src="https://github.com/user-attachments/assets/84cbe7ee-8fdc-41e3-bf11-6c27585b74da">

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- [built from v0.52.0 tag](https://github.com/tenstorrent/tt-metal/releases/tag/v0.52.0)

**Additional context**
error is reported by community and customers. I also built from main and v0.52.0 and getting the same error on both builds.

**Comment by mcw-anasuya** [comment]
Example has been updated to create tensors of rank 2.

<img width="1164" alt="Screenshot 2024-10-30 at 22 16 09" src="https://github.com/user-attachments/assets/d0d4e06b-45e6-4916-93bf-c1256a531762">

Updated document has been merged to main. Closing this issue.
