### ISSUE TITLE
Semantic change in CreateSemaphore API is not documented

### ISSUE THREAD

**Issue by csehydrogen** [tenstorrent/tt-metal#14457]
In the past, CreateSemaphore directly returned L1 address of the semaphore allocated.
Now, CreateSemaphore returns ID (0, 1, 2, ...) and L1 address should be obtained via `get_semaphore`.
This behavior change is not yet reflected into documentation.

**Comment by tt-aho** [comment]
Hey @csehydrogen, thanks for flagging this. I've updated the relevant comments to reflect what the returned value is/should be used, we are now just waiting on having the published docs regenerated.

**Comment by bbeggsTT** [comment]
CreateSemaphore in the API list on the docs website: https://docs.tenstorrent.com/tt-metalium/latest/tt_metal/apis/host_apis/buffers/CreateSemaphore.html#createsemaphore

**Comment by bbeggsTT** [comment]
HPP file to be edited for changes here: https://github.com/tenstorrent/tt-metal/blob/main/tt_metal/host_api.hpp

**Comment by tt-aho** [comment]
> HPP file to be edited for changes here: https://github.com/tenstorrent/tt-metal/blob/main/tt_metal/host_api.hpp

@bbeggsTT the file has already been updated. The published docs need to be regenerated, which we currently only do when making new releases @tt-rkim

**Comment by tt-rkim** [comment]
This is correct.

Currently, we are not able to release on a regular cadence because the models tests (the demo models on the front page) are not in good shape.

I'm open to increasing the frequency of releases, despite these tests not passing.

**Comment by bbeggsTT** [comment]
@tt-rkim Can we close this issue since changes have been made or do we need to wait until the next release to close?

**Comment by tt-rkim** [comment]
We can most definitely close. We do need to wait for releases.
