### ISSUE TITLE
Remove usage of full_like/ones_like/zeros_like ops in eltwise composite where tensor-scalar support is available

### ISSUE THREAD

**Issue by KalaivaniMCW** [tenstorrent/tt-metal#14466]
In tt-eager, 
Some of the eltwise-binary ops did not have tensor-scalar support, so eltwise composite/backward ops that were implemented used full_like/ones_like/zeros_like to convert scalar to tensor and pass it for binary operations. 

- Since now we have [#14172 ](https://github.com/tenstorrent/tt-metal/pull/14172), we can modify our implementations in various eltwise ops

- [x] #14924
- [x] #14879
- [x] #14880
- [x] #14713
- [x] #14714
- [x] #14928
- [x] #14929
- [x] #14930

**Comment by umadevimcw** [comment]
All the PR merged to main. Hence closing
