### ISSUE TITLE
Investigate ttnn resnet performance on-device regressions from end of October 2024

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#14471]
There was a regression recently on on-device performance for ttnn resnet 50.

**Comment by tt-rkim** [comment]
@pavlejosipovic 

Hey, I think your changes may have caused regressions in other on-device perf models:

1 commit before yours: https://github.com/tenstorrent/tt-metal/actions/runs/11594806696
your commit: https://github.com/tenstorrent/tt-metal/actions/runs/11595503614

I am re-running a 3rd time to be sure, but this is what I'm seeing. It's regressions in diff models.

**Comment by tt-rkim** [comment]
This isn't definitive, but the failure is new.

I will re-run a couple of times.

**Comment by pavlejosipovic** [comment]
which models my change https://github.com/tenstorrent/tt-metal/commit/1a271b317f3e17106bb40b823c320a45673ebcd4 is just improving perf on reset on gs?

**Comment by tt-rkim** [comment]
Yes , so it is confusing... just running some stress tests to be sure
