### ISSUE TITLE
Remove cluttering PR messages about "deployment to environment" and explore other options for people to be able to find workflow runs for a given PR

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#14484]
@ayerofieiev-tt asked us to get rid of

![image](https://github.com/user-attachments/assets/ad07e1b1-7f33-4065-9c25-93e30a0f707f)

This should be a matter of getting rid of `environment:` key in our workflow files.

As for alternatives for people workflow runs for a PR, we could provide options such as:

- A comment command to list workflow runs for a branch as a comment
  - Con: can clutter PRs similarly and email people
- A local script that lists links on the command line given a branch
  - Con: not as convenient to click and see as on a browser
- A new CI/CD superset dashboard page for this purpose
  - Con: a little inconvenient for people to access, although it might be slightly nicer than the above script idea

cc: @tt-aho

**Comment by tt-rkim** [comment]
cc: @blozano-tt

**Comment by tt-rkim** [comment]
Last thing to do is to remove `environment: `

Will do by friday.

**Comment by blozano-tt** [comment]
@tt-rkim thank you for this!
