### ISSUE TITLE
reshape and add output dtype seems always bfloat16

### ISSUE THREAD

**Issue by swimdi** [tenstorrent/tt-metal#14493]
When I debug `XGLM` model test, has this error message
```
self = <OpOverload(op='aten.index_select', overload='default')>
args = (tensor([[ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.00....,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
             15., 16., 17., 18., 19., 20.], dtype=torch.bfloat16))
kwargs = {}

    def __call__(self, *args, **kwargs):
>       return self._op(*args, **(kwargs or {}))
E       RuntimeError: index_select(): Expected dtype int32 or int64 for index
```
The expected type should be int32 or int64, but got bfloat16

The 3rd input of index_select has these chain

```
aten::arange.start -> aten::unsqueeze -> aten::add.Tensor ->
aten::squeeze.dim -> aten::unsqueeze -> aten::view -> 3rd input of aten::index_select
```
`aten::unsqueeze` and ` aten::unsqueeze` both converted to `ttnn.reshape`, and I think `ttnn.reshape`'s output dtype will be bfloat16 whatever the input dtype is int32 or int64, and then cause the 3rd input of `aten::index_select` get dtype error

Also `ttnn.add` has same issue

so I block `aten::unsqueeze`, ` aten::unsqueeze` and `ttnn.add` of above input chain, then that error msg not shown

The reproduce step is
1. In `to_tt_guard.py`, replace
```
aten_unsqueeze_default_blocklist = [["Tensor<[19]> self = ?", "int dim = 0"]]
```
as 
```
aten_unsqueeze_default_blocklist = []
```

2.  `pytest tests/models/xglm/test_xglm.py`

After this issue is resolved, please also remove the related blocklist in `to_tt_guard.py`.

**Comment by ntarafdar** [comment]
@swimdi I'm assuming you fixed this with your PR linked here. Closing, please re-open if I'm wrong
