### ISSUE TITLE
Document Creation - Tutorial - Adding Two Integers

### ISSUE THREAD

**Issue by bbeggsTT** [tenstorrent/tt-metal#14499]
I am currently working on a tutorial for Adding Two Integers.

**Comment by bbeggsTT** [comment]
First review completed 10-30-2024.

This will be split into two tutorials:

1. Adding Two Integers in a Baby RISC-V
2. Adding Two Integers in the Compute Kernel

**Comment by zzigler-tt** [comment]
@bbeggsTT please add the issue # for the different tutorials within the comments.

**Comment by bbeggsTT** [comment]
Document is published in GitHub here: https://github.com/tenstorrent/tt-metal/blob/main/tech_reports/prog_examples/add_2_integers_in_riscv/Tutorial%20-%20Add%20Two%20Integers%20in%20a%20Baby%20RISC-V.md
