### ISSUE TITLE
[Bug Report] Programs enqueued immediately after traces are enqueued may corrupt the last command in the trace

### ISSUE THREAD

**Issue by jbaumanTT** [tenstorrent/tt-metal#14501]
**Describe the bug**

Programs enqueued immediately after traces are enqueued may corrupt the last command in the trace, because they might into part of the ringbuffer that's in use by the  running program.

**To Reproduce**
1. Run pytest tests/nightly/single_card/functional_unet/experimental/functional_unet/tests/test_unet_trace.py::test_unet_trace_2cq_same_io[2-1-32-device_params0] with the ringbuffer changes

The test will generally hang
**Expected behavior**
Test passes

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by davorchap** [comment]
Great catch!

Which Program does Unet enqueue after the trace run?

**Comment by pgkeller** [comment]
Commit 4422c93 is a decent fix, definitely good enough for now.  Longer term seems we could:
1) Record the RB state at the end of the trace
2) When playing a trace, set the RB state to match the "end of trace state"
3) Next program will just continue on
@tt-asaigal

**Comment by pgkeller** [comment]
fixed
