### ISSUE TITLE
[Bug Report] Builds successfully locally, but fails to build on CI/CD

### ISSUE THREAD

**Issue by mrshaw01** [tenstorrent/tt-metal#14505]
**Describe the bug**
https://github.com/tenstorrent/tt-metal/pull/13924
This PR builds successfully locally. However, when running all post-commit checks, it fails:
https://github.com/tenstorrent/tt-metal/actions/runs/11605026934/job/32315969659

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Please complete the following environment information:**
N/A

**Additional context**
N/A

**Comment by mrshaw01** [comment]
@o2buzzle

**Comment by o2buzzle** [comment]
#14504 should fix it. Please prioritize that

**Comment by mrshaw01** [comment]
Resolved at: https://github.com/tenstorrent/tt-metal/pull/14504
I'll close this issue.
