### ISSUE TITLE
fix sfpi-rel to not use LFS

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#14590]
build w/ a release tarball

**Comment by nathan-TT** [comment]
sfpi is now released via tarballs, tt-metal uses the new mechanism.

There is at least one other repo (budabackend) still uses the old mechanism

**Comment by tt-rkim** [comment]
@ubcheema @TTDRosen do we still house the erisc main in budabackend?

**Comment by nathan-TT** [comment]
Declaring victory, We can track the budabackend issue separately,
