### ISSUE TITLE
tt_cluster.hpp uses ARCH_NAME specific includes to gather L1 Address params

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-metal#14608]
Prerequisite: #14618 

https://github.com/tenstorrent/tt-metal/blob/1b5d19faa16efbb173cf044156d31bc58a881ceb/tt_metal/llrt/tt_cluster.hpp#L304-L314

These parameters are passed over to UMD at runtime, but code tries to initialize a struct at compile time.

Need to change tt_cluster.cpp to initialize the struct at runtime using Hal.

Some parameters may need to be added to Hal.

**Comment by blozano-tt** [comment]
@abhullar-tt @pgkeller looks like we need to add

FIRMWARE as a key to hal, but looks like each of the 5 process cores will have its own value? 

Also, ERIC_BARRIER_BASE is not currently considered by HAL.

Same with FW_VERSION_ADDR

Any guidance on this?

**Comment by abhullar-tt** [comment]
UMD only uses
```    
(uint32_t)MEM_L1_BARRIER, 
(uint32_t)eth_l1_mem::address_map::ERISC_BARRIER_BASE, 
(uint32_t)eth_l1_mem::address_map::FW_VERSION_ADDR
```

**Comment by abhullar-tt** [comment]
I think we should prune unused params, defines, etc before making changes to reflect existing state

**Comment by blozano-tt** [comment]
This issue is linked to:

https://github.com/tenstorrent/tt-umd/issues/244

**Comment by blozano-tt** [comment]
> UMD only uses
> 
> ```
> (uint32_t)MEM_L1_BARRIER, 
> (uint32_t)eth_l1_mem::address_map::ERISC_BARRIER_BASE, 
> (uint32_t)eth_l1_mem::address_map::FW_VERSION_ADDR
> ```

When I grep UMD code, I see the following fields getting used:

```
l1_address_params.trisc0_size
l1_address_params.trisc1_size
l1_address_params.trisc2_size
l1_address_params.trisc_base
l1_address_params.tensix_l1_barrier_base
l1_address_params.eth_l1_barrier_base
l1_address_params.fw_version_addr

**Comment by blozano-tt** [comment]
https://github.com/tenstorrent/tt-umd/pull/260

Pruning the params^
