### ISSUE TITLE
P100s hang when reading out of PCIe with new FW

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#14617]
After new FW was loading onto P100s reads from PCIe are hanging. Current suspicion is that it is due to  some shared logic for selecting where to load pcie fw. 

Marking as p0 because this impacts all Fast Dispatch traffic

**Comment by abhullar-tt** [comment]
This issue is expected on P150s because these use a different pcie noc endpoint than p100s but p100s should not have been impacted

**Comment by abhullar-tt** [comment]
@TTDRosen we got a FW drop to address this but it seems like it was not stable, do you know what the issue here is?

**Comment by abhullar-tt** [comment]
@ttmchiou have we updated to newer FW that does not hang P100s? If so I think that this issue can be closed

**Comment by ttmchiou** [comment]
We have P100s with 80.13.1.0 fw that does not hang the machines running on CI now.

Issue could be due to flashing or hardware issue in the past.
Lets close this issue for now?
