### ISSUE TITLE
New FW drop break ability to target eth cores on BH P100s

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#14613]
New eth FW and FW for tt-smi reset has broken our ability to target / load fw on eth cores. This is seen in p100s which do not have any active eth cores. 

This problem is showing up on p100s and p150s

CI machines are running this new FW and currently no tests can be run. 

Workaround in main: Push a patch to make it look like BH has no eth cores

**Comment by bingliTT** [comment]
Could you walk me through the sequence being used to load fw on the eth cores?

**Comment by abhullar-tt** [comment]
> Could you walk me through the sequence being used to load fw on the eth cores?

1. assert risc reset on all eth cores
2. host writes erisc FW binary to L1 
3. host program a jump to start addr of FW 
4. host issues l1 barrier to make sure steps 2 and 3 are completed 
5. eth cores get deasserted
6. host polls eth cores for done signal (supplied by eth FW)

This sequence has been working for the p100s and nothing has changed here with the new FW

**Comment by abhullar-tt** [comment]
Adding @TTDRosen for visibility

**Comment by abhullar-tt** [comment]
This issue was expected to be hit on ethernet cores with active links on P150s but is not expected on:
-  P100s or 
- eth cores on P150s without links


Looks like we are running into this in the unexpected cases because FW on these link-less cores is running an init sequence. Proposed solution from @bingliTT is for FW on these cores to skip straight to a heartbeat counter which shouldn't have any issues if Metal is using eth risc0

**Comment by abhullar-tt** [comment]
FYI @ttmchiou

**Comment by abhullar-tt** [comment]
Closing this because the current eth FW for idle eth cores will be uplifted to allow Metal using risc0 and risc1. 

Also have working support to program only risc1 of active eth cores on `abhullar/active-eth`
