### ISSUE TITLE
sanitize_noc_host.hpp uses ARCH_NAME specific include path

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-metal#14615]
https://github.com/tenstorrent/tt-metal/blob/3a1a1765e4daf7a23f42e0eb1a00fb8ace5372bd/tt_metal/impl/debug/sanitize_noc_host.hpp#L5-L6

Can we get the required parameters from Hal?

This header file provides the function: `tt::watcher_sanitize_host_noc_write()` to `tt_cluster.cpp`.

https://github.com/tenstorrent/tt-metal/blob/3a1a1765e4daf7a23f42e0eb1a00fb8ace5372bd/tt_metal/llrt/tt_cluster.cpp#L481

**Comment by blozano-tt** [comment]
@tt-dma what should we do here?

Put all these parameters behind Hal?
https://github.com/tenstorrent/tt-metal/blob/3a1a1765e4daf7a23f42e0eb1a00fb8ace5372bd/tt_metal/impl/debug/sanitize_noc_host.hpp#L15-L21

cc: @pgkeller

**Comment by pgkeller** [comment]
> [@tt-dma](https://github.com/tt-dma) what should we do here?
> 
> Put all these parameters behind Hal?
> 
> [tt-metal/tt_metal/impl/debug/sanitize_noc_host.hpp](https://github.com/tenstorrent/tt-metal/blob/3a1a1765e4daf7a23f42e0eb1a00fb8ace5372bd/tt_metal/impl/debug/sanitize_noc_host.hpp#L15-L21)
> 
> Lines 15 to 21 in [3a1a176](/tenstorrent/tt-metal/commit/3a1a1765e4daf7a23f42e0eb1a00fb8ace5372bd)
> 
>  // what's the size of the NOC<n> address space?  using 0x1000 for now 
>  #define DEBUG_VALID_REG_ADDR(a)                                                        \ 
>      (                                                                                  \ 
>       (((a) >= NOC_OVERLAY_START_ADDR) && ((a) < NOC_OVERLAY_START_ADDR + NOC_STREAM_REG_SPACE_SIZE * NOC_NUM_STREAMS)) || \ 
>       (((a) >= NOC0_REGS_START_ADDR) && ((a) < NOC0_REGS_START_ADDR + 0x1000)) || \ 
>       (((a) >= NOC1_REGS_START_ADDR) && ((a) < NOC1_REGS_START_ADDR + 0x1000)) || \ 
>       ((a) == RISCV_DEBUG_REG_SOFT_RESET_0)) 
> cc: [@pgkeller](https://github.com/pgkeller)

I think the whole functionality belongs behind the hal.  So watcher makes an "is_valid" call, parameters and code instanced behind the hal.
