### ISSUE TITLE
metal_soc_descriptor.cpp uses ARCH_NAME specific include path for dev_mem_map.h

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-metal#14623]
https://github.com/tenstorrent/tt-metal/blob/4924301fe768a35d1455dabd7b2660c5160009e9/tt_metal/common/metal_soc_descriptor.cpp#L12

`dev_mem_map.h` is ARCH_NAME specific and is brought in for `MEM_TRISC0_FIRMWARE_SIZE`.

This needs to be eliminated or moved behind hal or yaml.
https://github.com/tenstorrent/tt-metal/blob/97731c4e64db1306a751ddc467e6e1e65f1009f7/tt_metal/common/metal_soc_descriptor.cpp#L375

**Comment by blozano-tt** [comment]
@pgkeller could you please elaborate on your `TODO` comment here?

What yaml file should provide these params? Is that still a good forward plan?

https://github.com/tenstorrent/tt-metal/blob/97731c4e64db1306a751ddc467e6e1e65f1009f7/tt_metal/common/metal_soc_descriptor.cpp#L375

**Comment by pgkeller** [comment]
> [@pgkeller](https://github.com/pgkeller) could you please elaborate on your `TODO` comment here?
> 
> What yaml file should provide these params? Is that still a good forward plan?
> 
> [tt-metal/tt_metal/common/metal_soc_descriptor.cpp](https://github.com/tenstorrent/tt-metal/blob/97731c4e64db1306a751ddc467e6e1e65f1009f7/tt_metal/common/metal_soc_descriptor.cpp#L375)
> 
> Line 375 in [97731c4](/tenstorrent/tt-metal/commit/97731c4e64db1306a751ddc467e6e1e65f1009f7)
> 
>  this->trisc_sizes = {MEM_TRISC0_FIRMWARE_SIZE, MEM_TRISC1_FIRMWARE_SIZE, MEM_TRISC2_FIRMWARE_SIZE};  // TODO: Read trisc size from yaml

I don't think that comment is mine, though maybe...

At this point in time, trisc_sizes is legacy and should be removed.  From a grep, I only see it used in tt_versim_device under deprecated.

**Comment by blozano-tt** [comment]
> At this point in time, trisc_sizes is legacy and should be removed. From a grep, I only see it used in tt_versim_device under deprecated.

Thank you for highlighting this! Makes me happy.
