### ISSUE TITLE
tt-topology with multiple n300s failing

### ISSUE THREAD

**Issue by ionx-justyn** [tenstorrent/tt-metal#14625]
**Describe the bug**
I have four n300s on a Linux machine running in a Docker (Ubuntu 20.04). Prior to running `tt-topology -l linear -f linear_layout.png` I have no issues with `tt-smi` and can invoke various `tt-metal` tests, etc. Note that single n300 tests have no issues when running our `tt-metal` scripts using this Docker. 

The `tt-topology` command fails with the attached errors. I have to do a reboot to get the cards back online. 

**To Reproduce**
With 4x n300s connected via PCIe: 
1. `source` your Pyenv
2. Run `tt-topology -l linear -f linear_layout.png`
3. See error

**Expected behavior**
Output file for the linear_layout.png generated, updated coordinates in the `tt-smi`, and ability to target individual devices within `tt-metal` scripts. 

**Screenshots**
Prior to running `tt-topology`:
<img width="878" alt="pre_tt-smi" src="https://github.com/user-attachments/assets/cd52debd-7e95-4bd1-a79c-93a83b712c31">
`tt-smi -s` logs:
[tt_smi_logs_results.json](https://github.com/user-attachments/files/17608898/tt_smi_logs_results.json)
`tt-topology -ls` output: 
<img width="369" alt="pre_tt-topology_-ls" src="https://github.com/user-attachments/assets/8643579b-b555-4081-bc2f-af7c00af7fc6">
`lscpi` output prior to `tt-topology`: 
<img width="471" alt="pre_lscpi" src="https://github.com/user-attachments/assets/84517d54-716b-4266-a320-418a3d69805b">
`dmesg` output prior to `tt-topology`: 
<img width="244" alt="pre_dmesg" src="https://github.com/user-attachments/assets/929f1c86-1135-471c-8ba8-dd8d72393b82">
`dkms status` prior to `tt-topology`: 
<img width="473" alt="pre_dkms_status" src="https://github.com/user-attachments/assets/a000daa3-4c42-480d-9e23-e25b011e2709">
`tt-topology -l linear -f linear_layout.png` terminal output: 
<img width="840" alt="post_tt-topology-linear" src="https://github.com/user-attachments/assets/1a476a1d-c29e-4804-b2ca-14919d694d09">
`tt_topology_log` output: 
[tt_topology_logs_log.json](https://github.com/user-attachments/files/17608907/tt_topology_logs_log.json)
Post `tt-smi` output: 
<img width="882" alt="post_tt-smi" src="https://github.com/user-attachments/assets/00fc3893-0ed3-4a4d-ac56-a0dab99b1b31">

**Please complete the following environment information:**
- OS: Host system uses Ubuntu 22.04. Docker uses Ubuntu 20.04
- Version of software: 
    - tt-smi: 3.0.2
    - tt-topology: 1.1.5

**Additional context**
Just noting again that this is being run in a Docker due to host environment being restricted to Ubuntu 22.04, which hasn't been an issue with a single n300.

**Comment by dvartaniansTT** [comment]
@ionx-justyn , thanks for filing the detailed issue. 

We currently support single device or mesh topology for (data parallel or tensor parallel). What's your use case for the linear topology?

**Comment by ionx-justyn** [comment]
Hey @dvartaniansTT! I tried `mesh` as well, but ended up with the same problem. We do not necessarily need linear specifically. I'm just trying to get our basic script working with >1 n300. 

We dynamically target an n300, but our scripts are hanging after the `import ttnn` with more than one n300 on the mobo. From the `tt-smi` above you can see all four have the same coords. I'm not sure if the same coords is the problem here, though.

**Comment by mbahnasTT** [comment]
hi @ionx-justyn , the supported options are:
- Run on one n300, but in that case you need to isolate it in the docker container or disable 3 out of the 4 cards
`sudo docker run -it -d --name=mlir-container -v /home/ubuntu/.ssh:/root/.ssh -v /dev/hugepages-1G:/dev/hugepages-1G -v /home/ubuntu/code:/code --restart=unless-stopped --shm-size=4g --cap-add ALL --device /dev/tenstorrent/1:/dev/tenstorrent/0 ghcr.io/tenstorrent/tt-mlir/tt-mlir-ci-ubuntu-22-04:dt-e931311c5edde3f3df8df7b8bf42e9dd bash`

- OR, set the tt-ttopology as `mesh` and connect the cards with the T-Fly and QSFD cables as our standard LoudBox setup. In that case you can use the multi-card in data parallel or tensor parallel configuration.

Hopefully this is helpful.

**Comment by ionx-justyn** [comment]
Thank you @mbahnasTT! 

In our case, we have four n300s, so would we need something like the below for a single docker image to be limited to a single n300? 
```
--device /dev/tenstorrent/1:/dev/tenstorrent/0 \
--device /dev/tenstorrent/2:/dev/tenstorrent/0 \
--device /dev/tenstorrent/3:/dev/tenstorrent/0 \
```

**Comment by mbahnasTT** [comment]
@ionx-justyn yes correct, please confirm when it's working OK. Thanks!

**Comment by ionx-justyn** [comment]
Looking good now! We went the Docker approach, but we'll likely test out the Loudbox setup at some point. Thanks so much, @mbahnasTT and @dvartaniansTT!
