### ISSUE TITLE
Conv fails in OSA_Module if input tensor is in Row Major 

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#14646]
**Describe the bug**
In the OSA_Module of VovnetCP module of PETR model, a conv fails with L1 issue if the input to the conv is in Row major layout:
```
E       RuntimeError: TT_THROW @ ../tt_metal/impl/program/program.cpp:747: tt::exception
E       info:
E       Statically allocated circular buffers in program 31 clash with L1 buffers on core range [(x=0,y=0) - (x=7,y=5)]. L1 buffer allocated at 491520 and static circular buffer region ends at 508416
```
If the input is converted to Tile layout, conv passes but pcc drops from 0.99 to 0.0627.

**To Reproduce**
1. Checkout to the branch [harini/petr_vovnetcp_osa_conv](https://github.com/tenstorrent/tt-metal/tree/harini/petr_vovnetcp_osa_conv)
2. Run the command: `pytest /home/ubuntu/harini/tt-metal/tests/ttnn/integration_tests/petr/test_vovnetcp.py::test_vovnetcp_osa_module`

**Expected behavior**
Expected to resolve the issue and get 0.99 pcc for the conv.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: WH n150

**Comment by HariniMohan0102** [comment]
cc: @punithsekar

**Comment by sankarmanoj-tt** [comment]
@HariniMohan0102 Can you rebase this on origin/main? I'm unable to run this.

**Comment by punithsekar** [comment]
Hi @sankarmanoj-tt ,
I have tested the branch after rebasing it to latest main. Resolved the issues that were faced in the convolution.
The above-mentioned  Statically allocated circular buffers issue is occurring in the latest main.

So, We can close this issue.

CC: @saichandax @HariniMohan0102
