### ISSUE TITLE
Refactor dev_msgs.h to be independent of ARCH_NAME

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-metal#14643]
Per @pgkeller - dev_msgs.h is the contract between the host and the device, and it should not be separated.

However, it is currently a blocker in making our code base agnostic to compile time ARCH_NAME usage.

It requires some refactoring / cleanup to make use of Hal.

https://github.com/tenstorrent/tt-metal/blob/main/tt_metal/hw/inc/dev_msgs.h

This file makes ~14 files ARCH_NAME specific.
```
tt_metal/impl/program/program.hpp
tt_metal/impl/dispatch/command_queue.cpp
tt_metal/impl/device/device.hpp
tt_metal/impl/device/device.cpp
tt_metal/impl/debug/watcher_device_reader.hpp
tt_metal/impl/debug/watcher_server.cpp
tt_metal/llrt/tt_cluster.hpp
tt_metal/llrt/llrt.cpp
tt_metal/llrt/tt_cluster.cpp
tt_metal/llrt/llrt.hpp
tt_metal/tools/profiler/profiler.cpp
tt_metal/tools/profiler/tt_metal_profiler.cpp
tt_metal/tools/profiler/kernel_profiler.hpp
tt_metal/tt_metal.cpp
```

**Comment by blozano-tt** [comment]
@pgkeller @abhullar-tt 

I am struggling to untangle `core_config.h` inside of `dev_msgs.h`.
https://github.com/tenstorrent/tt-metal/blob/3f12bb9bf54a140a54fe95d240f354bdcd190546/tt_metal/hw/inc/dev_msgs.h#L13

We currently try to bring different versions of the file into the translation unit depending on `ARCH_NAME`:
https://github.com/tenstorrent/tt-metal/blob/main/tt_metal/hw/inc/grayskull/core_config.h
https://github.com/tenstorrent/tt-metal/blob/main/tt_metal/hw/inc/wormhole/core_config.h
https://github.com/tenstorrent/tt-metal/blob/main/tt_metal/hw/inc/blackhole/core_config.h

The file brings in enum types, constants, and structs that are used at `COMPILE_TIME`. 

For example:
https://github.com/tenstorrent/tt-metal/blob/3f12bb9bf54a140a54fe95d240f354bdcd190546/tt_metal/hw/inc/dev_msgs.h#L97-L98
https://github.com/tenstorrent/tt-metal/blob/3f12bb9bf54a140a54fe95d240f354bdcd190546/tt_metal/hw/inc/dev_msgs.h#L101
https://github.com/tenstorrent/tt-metal/blob/3f12bb9bf54a140a54fe95d240f354bdcd190546/tt_metal/hw/inc/dev_msgs.h#L275
https://github.com/tenstorrent/tt-metal/blob/3f12bb9bf54a140a54fe95d240f354bdcd190546/tt_metal/hw/inc/dev_msgs.h#L287

This is a problem Hal cannot currently solve, as Hal is a runtime concept.

Could you please take a stab at solving this when you have time?

cc: @bkeith-TT @TT-billteng

**Comment by pgkeller** [comment]
Yes, there is a lot of work to do.  Device side this is fine.  For host side presently we rely on using the "max" values across all arches and core types.  To unify the build we either need to stick w/ the max values (and preferably enforce w/ asserts) or move these messages behind the hal.  Short term easiest to use max, long term we likely want this all behind the hal.
