### ISSUE TITLE
Kernel test test_tx_rx has a compile error

### ISSUE THREAD

**Issue by nhuang-tt** [tenstorrent/tt-metal#14678]
**Describe the bug**
`test_tx_rx` has a kernel compilation error because it's missing some defines and compile args that are used by the Traffic Gen TX and RX.

**To Reproduce**
`TT_METAL_SLOW_DISPATCH_MODE=true ./build/test/tt_metal/perf_microbenchmark/routing/test_tx_rx`

**Expected behavior**
Test Passes

**Comment by pgkeller** [comment]
@nhuang-tt is this fixed?

**Comment by nhuang-tt** [comment]
Fixed
