### ISSUE TITLE
Remove ifdef ARCH_BLACKHOLE from llrt arrays

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#14689]
`processor_to_fw_base_addr` and `local_init_addr` assignment in llrt.cpp have ifdef `ARCH_BLACKHOLE` this can be removed by pulling this information from the HAL. 

This can potentially be cleaned up with https://github.com/tenstorrent/tt-metal/issues/11839

**Comment by blozano-tt** [comment]
Closed by #15150
