### ISSUE TITLE
Conv error when passing sharded input in Segformer

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent/tt-metal#14705]
**Describe the bug**
Conv error (possible number overflow) when passing a sharded input, while it passes with interleaved input

**To Reproduce**
1. Go to branch `mbahnas/segformer_wh_optim`
2. Run `pytest tests/ttnn/integration_tests/segformer/test_segformer_encoder.py`

**Expected behavior**
purest to Pass

**Screenshots**
![Image](https://github.com/user-attachments/assets/555521aa-953e-4bbc-84bc-62879591b1d8)

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by pavlejosipovic** [comment]
@mbahnasTT wanted to check if this is resolved against latest code but mbahnas/segformer_wh_optim doesn't seem to exist (or any branch with similar name)?

**Comment by pavlejosipovic** [comment]
I've tweaked the code of the test in order for it to pass with shared code-path
https://github.com/tenstorrent/tt-metal/tree/pjosipovic/segformer_wh_optim
This one is not conv related.

**Comment by mbahnasTT** [comment]
I confirm, thanks @pavlejosipovic
