### ISSUE TITLE
TTNN eltwise ops - Update Examples

### ISSUE THREAD

**Issue by mcw-anasuya** [tenstorrent/tt-metal#14797]
For all TTNN eltwise ops:
The tensor shapes provided in examples are inconsistent with the op.
Currently we support device operations for ranks > 2 for most of the ops as per doc. The current examples in the doc creates a 1D tensor.

- [x] #14982
- [x] #14983
- [x] #14984
- [x] #14985
- [x] #14986
- [x] #14987

**Comment by VirdhatchaniKN** [comment]
Closing issue as all PRs have been merged to main
