### ISSUE TITLE
GraphCapture doesn't throw an error for L1 overflow in NO_DISPATCH mode

### ISSUE THREAD

**Issue by derdeljanTT** [tenstorrent/tt-metal#14815]
**Describe the bug**
GraphCapture doesn't throw an error for L1 overflow in NO_DISPATCH mode

**To Reproduce**
E.g., the following block
```cpp
const auto input_tensor_a = ttnn::zeros(params.a_Shape, DataType::BFLOAT16, ttnn::TILE_LAYOUT, this->getDevice(), params.memory_config);
        const auto input_tensor_b = ttnn::zeros(params.b_Shape, DataType::BFLOAT16, ttnn::TILE_LAYOUT, this->getDevice(), params.memory_config);

        auto call = [&] {
            std::vector<tt::tt_metal::Tensor> res;
            for (int i = 0; i < 500; i++) {
                res.push_back(ttnn::add(
                    input_tensor_a,
                    input_tensor_b,
                    std::make_optional(DataType::BFLOAT16),
                    std::make_optional(ttnn::L1_MEMORY_CONFIG)));
            }

            return res;
        };

        ttnn::graph::GraphProcessor::begin_graph_capture(tt::tt_metal::IGraphProcessor::RunMode::NO_DISPATCH);
        {
            auto output = call();
        }
        auto json_trace = ttnn::graph::GraphProcessor::end_graph_capture();
```
will not throw in no dispatch mode but will throw in normal mode, as we run out of the L1 space.

**Expected behavior**
Pasted block of code should throw in either no dispatch mode or some new mode which does not dispatches kernels to the device but tracks memory allocations.

**Comment by mbezuljTT** [comment]
Original design intention was to disallow NO_DISPATCH graph captures to mess up allocator state. With that in mind, this is not a bug. We need to figure out right way to enable L1 overflow catching, but it requires more work on the allocator and graph capture. I've started #15262 to align and scope future work.
