### ISSUE TITLE
why are blank trisc kernels so big?

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#14826]
Working on kernel ring buffer code, found out that blank trisc kernels are not so blank.
I think it is memcpy or some such getting pulled in.
This issue is to figure out what is going on and fix.

**Comment by nathan-TT** [comment]
investigating ...

**Comment by nathan-TT** [comment]
436 bytes removed from startup code

**Comment by nathan-TT** [comment]
Resolved
