### ISSUE TITLE
Add support for groups in `ttnn.concat`

### ISSUE THREAD

**Issue by esmalTT** [tenstorrent/tt-metal#14830]

**Comment by esmalTT** [comment]
Completed in [4fc773a](https://github.com/tenstorrent/tt-metal/commit/4fc773ab18affaabe1bf6d66552acd4e73d636aa)

**Comment by mbezuljTT** [comment]
@esmalTT  

I'm getting local build break on `concat_program_factory.hpp `

> In file included from ../ttnn/cpp/ttnn/operations/data_movement/concat/device/concat_program_factory.cpp:5:
> ../ttnn/cpp/ttnn/operations/data_movement/concat/device/concat_program_factory.hpp:24:1: error: no member named 'operation' in namespace 'tt::tt_metal'; did you mean 'operations'?
>    24 | tt::tt_metal::operation::ProgramWithCallbacks s2s_rm_concat_two_tensors_multi_core(
>       | ^~~~~~~~~~~~~~~~~~~~~~~
>       | operations
> ../ttnn/cpp/ttnn/operations/data_movement/concat/device/concat_program_factory.hpp:11:17: note: 'operations' declared here
>    11 | namespace ttnn::operations::data_movement::detail {
>       |                 ^
> ../ttnn/cpp/ttnn/operations/data_movement/concat/device/concat_program_factory.hpp:24:26: error: no type named 'ProgramWithCallbacks' in namespace 'ttnn::operations'
>    24 | tt::tt_metal::operation::ProgramWithCallbacks s2s_rm_concat_two_tensors_multi_core(
>       | ~~~~~~~~~~~~~~~~~~~~~~~~~^

it's solves when I add #include `"ttnn/operation.hpp"` however, I dont understand why CI is passing and my local build is failing :/

my build command is 
`./build_metal.sh -b Debug -c --build-tests`

please advise, or let me know if I should PR that fix.
