### ISSUE TITLE
Out of Memory (OOM) error with ttnn.mul for shape [6, 16, 384, 384] on n300,e150

### ISSUE THREAD

**Issue by sabira-mcw** [tenstorrent/tt-metal#14840]
**Describe the bug**
Encountering  Out of Memory (OOM) issue when processing a tensor with the shape [6, 16, 384, 384] and a scalar value of 0.125. The error occurs during the matrix multiplication operation when the batch size exceeds 5.

```
E       RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:142: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 56623104 B L1 buffer across 56 banks, where each bank needs to store 1011712 B
E       backtrace:
```

**To Reproduce**
1. Pick the test from [commit](https://github.com/tenstorrent/tt-metal/compare/main...sabira/test_mul_bloom)
2. Run ```pytest tests/ttnn/unit_tests/operations/test_mul.py```

**Expected behavior**
The operation should run without encountering an Out of Memory (OOM) error for the given tensor shape and scalar value.

**Please complete the following environment information:**
    - OS: [e.g. Ubuntu 20.04]
    - Devices: GS, WH

**Comment by KalaivaniMCW** [comment]
Hi @sabira-mcw 
For the given input tensor size, it seems to exceed the L1 capacity. Is there any specific reason for using L1 memory here instead of DRAM ? 
the tests pass with DRAM memory config

![Image](https://github.com/user-attachments/assets/439b5f53-cde6-4239-a0e6-5e312d2b5663)

**Comment by eyonland** [comment]
@sabira-mcw, we do not currently support temporal sharding.  Given this works for DRAM I'd like to close this.  Please re-open if this is a blocker.
