### ISSUE TITLE
[Bug Report] ttnn.full input shape and `TILE_LAYOUT` compatibility

### ISSUE THREAD

**Issue by kevinwuTT** [tenstorrent/tt-metal#14871]
**Describe the bug**

If I have an input with a shape where the height dimension is not a multiple of 32, I get an error if I also pass in `TILE_LAYOUT`. However, if I split the operation to calling `ttnn.full` with `ROW_MAJOR_LAYOUT` and then tilize with `ttnn.to_layout` I get no errors.

**To Reproduce**

```
import ttnn

with ttnn.manage_device(device_id=0) as device:
    ttnn_full = ttnn.full((1, 256), layout = ttnn.TILE_LAYOUT, fill_value = 1.0, device = device)
```
```
RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/numpy/functions.hpp:70: shape[-2] % tt::constants::TILE_HEIGHT == 0
info:                                                
TILE layout requires height dimension to be multiple of 32    
```

However, if I have `ttnn.full` default to `ROW_MAJOR_LAYOUT` and call `ttnn.to_layout` to `TILE_LAYOUT` after, I do not get any errors.

```
import ttnn

with ttnn.manage_device(device_id=0) as device:
    ttnn_full = ttnn.full((1, 256), fill_value = 1.0, device = device)
    to_layout = ttnn.to_layout(ttnn_full, layout = ttnn.TILE_LAYOUT)
```

**Expected behavior**
Should `ttnn.full` alone support shapes like this with `TILE_LAYOUT`?

**Please complete the following environment information:**
- OS: Ubuntu 20.04 Grayskull
- Version of software (eg. commit): `tt-metal: tags/v0.53.0-rc35`

**Comment by ayerofieiev-tt** [comment]
I thought if it should be p0 or p1 and set as P0 because it seems like a regression which makes PyTorch CI non-functional.
Basically, we need help to look & address this asap.

**Comment by kevinwuTT** [comment]
I can no longer reproduce this error on `v0.53.0-rc39`. Will close this issue.

However, a different shape raises another issue: https://github.com/tenstorrent/tt-metal/issues/15030
