### ISSUE TITLE
Reading controller buffer in multi-device async runs is hanging

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent/tt-metal#14905]
First seen by @skhorasganiTT on llama on T3K and now seen by @djordje-tt on llama runs on TG dumping device profiler causes hangs. Looking deeper into the hang, it is showing that  reading the profiler control buffer through 
`read_hex_vec_from_core` hangs during its umd `read_block` child call.

Note that `read_dex_vec_from_core` is called for each core per device, what is being observed is multiple devices go through until usually one of the calls slows down by a lot and then the subsequent ones hang.

Also, even though this is a async run, dumps are run serially as they all need to obtain a syncing mutex. 

Repro steps:

1. Profiler build on `skhorasgani/llama_trace_perf_tracy`
2. (on AUS COLO) export LLAMA3_CKPT_DIR="/mnt/MLPerf/tt_dnn-models/llama-3/llama-3-70b-repacked/" && export LLAMA3_TOKENIZER_PATH="/mnt/MLPerf/tt_dnn-models/llama-3/tokenizer.model" && export LLAMA3_CACHE_PATH="/mnt/MLPerf/tt_dnn-models/llama-3/llama-data-cache/weights-cache-3/"
3. `TT_METAL_DEVICE_PROFILER=1 pytest models/demos/t3000/llama2_70b/tests/test_llama_perf_decode.py::test_Llama_perf_host[wormhole_b0-True-device_params0-gen128-llama3]`

Tracy file showing dump on device 6 hanging. [Dump6_Stuck.tracy.zip](https://github.com/user-attachments/files/17683499/Dump6_Stuck.tracy.zip)

GDB  trace showing thread 51 stuck on `read_block` while others are waiting
![Image](https://github.com/user-attachments/assets/465e5c29-7014-4369-b721-c49e7018f0e9)

**Comment by mo-tenstorrent** [comment]
Further double clicked on what is hanging, 

```
  42 void tt_SiliconDevice::wait_for_non_mmio_flush() {
  41     if(flush_non_mmio) {
  40         log_assert(arch_name != tt::ARCH::BLACKHOLE, "Non-MMIO flush not supported in Blackhole");
  39         std::string read_tlb = "LARGE_READ_TLB";
  38         auto chips_with_mmio = this->get_target_mmio_device_ids();
  37         for(auto chip_id : chips_with_mmio) {
  36             auto arch = get_soc_descriptor(chip_id).arch;
  35             if (arch == tt::ARCH::WORMHOLE || arch == tt::ARCH::WORMHOLE_B0) {
  34                 std::vector<std::uint32_t> erisc_txn_counters = std::vector<uint32_t>(2);
  33                 std::vector<std::uint32_t> erisc_q_ptrs = std::vector<uint32_t>(eth_interface_params.remote_update_ptr_size_bytes*2 / sizeof(uint32_t));
  32
  31                 //wait for all queues to be empty.
  30                 for (tt_cxy_pair &cxy : remote_transfer_ethernet_cores.at(chip_id)) {
  29                     auto timeout_seconds = std::chrono::seconds(10);
  28                     auto start = std::chrono::system_clock::now();
  27                     do {
  26                         if (std::chrono::system_clock::now() - start > timeout_seconds)
  25                         {
  24                             start =std::chrono::system_clock::now();
  23                             std::cout << "WHILE 1" << std::endl;
  22                         }
  21                         read_device_memory(erisc_q_ptrs.data(), cxy, eth_interface_params.request_cmd_queue_base + eth_interface_params.cmd_counters_size_bytes, eth_interface_params.remote_update_ptr_size_bytes*2, read_tlb);
  20                     } while (erisc_q_ptrs[0] != erisc_q_ptrs[4]);
  19                 }
  18                 //wait for all write responses to come back.
  17                 for (tt_cxy_pair &cxy : remote_transfer_ethernet_cores.at(chip_id)) {
  16                     auto timeout_seconds = std::chrono::seconds(10);
  15                     auto start = std::chrono::system_clock::now();
  14                     do {
  13                         if (std::chrono::system_clock::now() - start > timeout_seconds)
  12                         {
  11                             start =std::chrono::system_clock::now();
  10                             std::cout << "WHILE 2" << std::endl;
   9                         }
   8                         read_device_memory(erisc_txn_counters.data(), cxy, eth_interface_params.request_cmd_queue_base, 8, read_tlb);
   7                     } while (erisc_txn_counters[0] != erisc_txn_counters[1]);
   6                 }
   5             } else {
   4                 break;
   3             }
   2         }
   1         flush_non_mmio = false;
3112     }
```

Above code only printed WHILE1/2 every 3 min when only one `read_dex_vec_from_core` went through. 
This suggest that ERISC FW hanging is less likely and underlying memread is causing issues.

**Comment by jvasilje** [comment]
fyi @pgkeller

**Comment by mo-tenstorrent** [comment]
The issue is root caused

When CCL ops are used, erisc fw only context switches at very large timeout values so that CCL perf is not disturbed. This basically blocks UMD RW to make through with the remote chips or any chip that requires a ho in the network to make it to host. 

From a brief chat with @pgkeller,  the way to go is to do the small control buffer read for profiler through FD. That way we decouple ourselves from UMD on the profiler when in FD and also do not disturb any CCL settings

**Comment by mo-tenstorrent** [comment]
A workaround has been found and confirmed for this issue

Two things were going on here:

1. UMD transactions as part of Dump profiler device calls were slowed down to hang due to ccl ops taking hold of ERISCs. 
    As a workaround, precede device dump calls with device sync calls to make sure all ccl ops are finished.
    Full solution will be delivered by #15015   in short use FD based raw L1 reads instead of 
    UMD
2. IRD Weka storage is still slow for profiler generated artifacts.
     As a workaround, reserve you IRD with nvme /localdev and use it for profiler artifact storage. On the machine generate a artifact folder and use it to run tests or just point the default folder to localdev with symlink:

```
ird reserve --ports 8086:8086 --volumes /localdev/mmemarian:/localdev/mmemarian --docker-image [ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-20.04-amd64:latest](http://ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-20.04-amd64:latest) --timeout 8:0:0 wormhole_b0 --model x1_galaxy --num-pcie-chips 4 --machine aus-glx-06

sudo mkdir /localdev/mmemarian/test
sudo chmod 777 /localdev/mmemarian/test/

FAKE_DEVICE=TG python -m tracy -p -r -m -o /localdev/mmemarian/test/ "pytest models/demos/llama3/tests/test_llama_perf.py -k 128"

ln -s /localdev/mmemarian/test/ ./generated/```

Full solution for this issue will be coming with #15016

**Comment by djordje-tt** [comment]
Thanks for the quick resolution!!!
