### ISSUE TITLE
GS Profiler Ring buffer

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#14961]
GS Profiler throws an error on post-commit after introducing ring buffers.
Seems to only show up on GS

Sample runs
https://github.com/tenstorrent/tt-metal/actions/runs/11755558404/job/32750772480
https://github.com/tenstorrent/tt-metal/actions/runs/11787560400/job/32833315694

temporarily disabled in post-commit until resolved in this PR
https://github.com/tenstorrent/tt-metal/pull/14970

**Comment by mo-tenstorrent** [comment]
Marking p1 as it is only GS sync test that is affected. Potentially more tests that are non-GS can also be effected.

**Comment by bkeith-TT** [comment]
Marking P2 as this does not seem to be currently blocking, although we will still prioritize the fix.
