### ISSUE TITLE
Reinitialization of Tilize/Untilize Operations Fails When Changing # Out Tiles

### ISSUE THREAD

**Issue by wransom-TT** [tenstorrent/tt-metal#14973]
**Describe the bug**
When processing tensors with C dimensions that are larger than 8 but not multiples of 8 tiles, the resulting output is wrong.  This seems to be due to incomplete re-initialization of the tilize/untilize operations in the compute kernel since for instance if we have 12 tiles, we need to first process 8 tiles, then 4 tiles.

**To Reproduce**
1. checkout `wransom/TwelveTileBugRebase`
2. build the code `./build_metal.sh --debug`
3. run the max pool unit test `pytest tests/ttnn/unit_tests/operations/test_maxpool2d.py` which runs a simple test case on 1 core
4. the test should fail, but should also print register output from right after the reduce operation (see line 80 of `max_pool_multi_core.cpp`)

From here we need to set the stage a bit to understand the current debugging information.  Because we have 12 C tiles, `reduce_h_fused` in `max_pool_multi_core.cpp` will be called twice for each window position.  The first time it should process the first 8 tiles, the second time it should process the remaining 4 tiles.  (both C = 4 tiles and C = 16 tile cases work, but C = 12 does not).  Furthermore, we have HW=2x2, but a window size of 3x3.  Thus, our tensor is padded such that H_pad, W_pad = 4.  So, given our stride of 1x1 in a padded HW of 4x4 and a window size of 3x3, this results in 4 window positions.  So, we will see a total of 8 tiles printed to the console from the reduce output registers, 2 for each window position times 4 window positions.  In the branches default state it is set to print register data from tile 0 so, for the 12 tile test case we are working with, we will see all 8 printed tiles with a top row equal to "4" (the correct value).  If we change line 80 of `max_pool_multi_core.cpp` to print tile 4 instead, we will see every other tile printed with 0 as the top row.  This is what we should expect since we only have 12 tiles and are printing tile index 4, which on the second pass of `reduce_h_fused` exceeds the total of 12 tiles.

So all this seems to imply that the output of reduce is correct, and that the issue may lie in the untilize procedure.

Note in the branches default state, we are not reinitializing the tilize operation (we are only reinitializing the utilize operation (see lines 138, 144, 150, 156 of `max_pool_multi_core.cpp`.  Also note that the commented out calls to `tilizeA_B_reduce_init_short` on lines 138 and 150 reference a newly implemented, untested function which may not behave as intended.  Nonetheless it is expected that the tilize operation will need to be re-initialized as well, but the results are the same at least for this simple case whether these calls to tilize are used or not.

**Expected behavior**
With the updates in the referenced branch, a tensor with a 12 tile C dimensions should work.

**Please complete the following environment information:**
- This issue was encountered on a wormhole system

**Comment by rtawfik01** [comment]
@ttmtrajkovic This issue is about being able to use tilize + untilize combination for different number of tiles in one fused kernel. To recap:

1. Tilize + reduce + untilize for 4 tiles works standalone
2. Tilize + reduce + untilize for 8 tiles works standalone
3. Initializing tilize + reduce + untilize for 4 tiles, then re-initializing for 8 tiles does not work (or vice versa).

The above is a new addition for Wormhole B0, and I think we should isolate each of these ops into respective tests to check whether re-initialization in the same kernel can work, so that means:
1. Adding a Tilize unit test that does 4 tiles, then re-initializing to 8 tiles (or vice versa)
2. Adding a Untilize unit test that does 4 tiles, then re-initializing to 8 tiles (or vice versa)
3. Same thing for reduce for sanity

@rdjogoTT @amahmudTT fyi for wormhole kernels.

In the meantime @wransom-TT @mywoodstock , please make the smallest possible version of the test above, so that would be with single core, and only 12 tiles in the test (1 iteration), and please add the appropriate priority.

**Comment by wransom-TT** [comment]
@rtawfik01 the test in this branch is the smallest possible failing example.  I have set it to 1 core (this is done in the python test it's easy to miss see line 163 of `tests/ttnn/unit_tests/operations/test_maxpool2d.py),` 12 tiles, N = 1 and HW=2x2 (we don't see the issue with 2x1 or 1x1).

**Comment by rtawfik01** [comment]
@wransom-TT thanks for the smaller test, currently I don't have an ETA since most of the team has P0 bugs they are working on, I'll let you know once someone is available to look at this issue.

**Comment by mywoodstock** [comment]
@rtawfik01 Thanks! Please let us know when this will be visited -- meanwhile we will try to use workarounds.

**Comment by amahmudTT** [comment]
@wransom-TT I have started working on this bug, but regarding this paragraph. 

"Furthermore, we have 4 sticks since HW=2x2. So, we will see a total of 8 tiles printed to the console from the reduce output registers. In the branches default state it is set to print register data from tile 0 so, for the 12 tile test case we are working with, we will see all 8 printed tiles with a top row equal to "4" (the correct value). If we change line 80 of max_pool_multi_core.cpp to print tile 4 instead, we will see every other tile printed with 0 as the top row. This is what we should expect since we only have 12 tiles and are printing tile index 4, which on the second pass of reduce_h_fused exceeds the total of 12 tiles."

I understood this part : "In the branches default state it is set to print register data from tile 0 so, for the 12 tile test case we are working with, we will see all 8 printed tiles with a top row equal to "4" (the correct value)."

But for the next line I did not understand what you meant, coud you explain/rewrite what you meant here ?. By saying "This is what we should expect since we only have 12 tiles" do you mean that it is producing the wrong result and you are getting the wrong result ? And when you say " exceeds the total of 12 tiles." do you mean reaches the value of 12 ?

**Comment by wransom-TT** [comment]
@amahmudTT So I realized I kind of botched the explanation of why we will see 8 tiles outputted to the console.  This comes down to some confusing logic about the stride, padding and such.  I have re-worded this explanation in the original description.  But I don't think this was actually the source of your confusion.

So, what I meant when I say this:

"If we change line 80 of max_pool_multi_core.cpp to print tile 4 instead, we will see every other tile printed with 0 as the top row. This is what we should expect since we only have 12 tiles and are printing tile index 4, which on the second pass of reduce_h_fused exceeds the total of 12 tiles."

Is that if we are printing tile index 0, then for a given window position, we should see both tiles come out of reduce with the value populated, because we are printing tiles 0 and 8 out of 12.  However, if we print tile index 4 instead, then we are printing tiles 4 and 12 out of 12.  Since index 12 exceeds the max valid index of 11, the second tile which is printed should not have values populated, we should just see padding there.  The same would be true if we printed index 5.  In this case tiles 5 and 13 would be printed, and again since index 13 exceeds the max index of 11, we again would see valid values in the first tile, but just padding in the second.

Let me know if a call would be better to discuss this, it's pretty confusing, and thanks for taking this on!

**Comment by amahmudTT** [comment]
Thanks for the explanation, I will work further and then ping you :)

**Comment by amahmudTT** [comment]
I will try to run on a wormhole machine (when I get a free one), but funny thing is I tried to compile this branch on a blackhole machine, then got this error when trying to run your test case or another python test case.

```
info:
Device 0 init: failed to initialize FW! Try resetting the board.
backtrace:
```

I rebased with main then I got the same error, with the test case you provided or any other python test case. 

But if I just work on the main branch this issue does not appear.

**Comment by amahmudTT** [comment]
I will try to run on a wormhole machine, but funny thing is I tried to compile this branch on a blackhole machine, then got this error when trying to run your test case or another python test case.

```
info:
Device 0 init: failed to initialize FW! Try resetting the board.
backtrace:
```

I rebased with main then I got the same error, with the test case you provided or any other python test case. 

But if I just work on the main branch this issue does not appear.

**Comment by amahmudTT** [comment]
@wransom-TT will it be possible for you to reproduce this problem on the latest main branch. I tried rebasing but there is a lot of conflict on the relevant files and the current branch does not run any python test on blackhole, I would like to make sure the problem does not persist on blackhole too.

**Comment by wransom-TT** [comment]
@amahmudTT I have rebased my branch off main, so now instead of using `wransom/TwelveTileBug`, please use `wransom/TwelveTileBugRebase`.  A head's up though, Abhinav tells me there is an LLK issue on the current main for blackhole.  So it is likely the rebased version still will not run on blackhole.  Let me know if you need to get access to a wormhole machine to work on this.  It's a very high priority for my team so maybe we can help get you a WH reservation.  Thanks again, and let me know if you need anything!

**Comment by amahmudTT** [comment]
Thanks a lot !

**Comment by cmaryanTT** [comment]
@amahmudTT - any update on this issue?

**Comment by amahmudTT** [comment]
> [@amahmudTT](https://github.com/amahmudTT) - any update on this issue?

Working on it, have not found the bug yet.

**Comment by amahmudTT** [comment]
Since a timeline for the completion of this bug was requested. It will require longer than I initially anticipated. I will try to finish it by end of next week. 

The reader seems to be okay apart from one bug (fixing it does not fix the issue). 
@wransom-TT I assume in this line https://github.com/tenstorrent/tt-metal/blob/4e1d6ef68c6f1a4a1c6cc01477feb6b7675f823e/ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_max_pool_2d_multi_core_sharded_with_halo_wide.cpp#L66 , you meant 13th argument, with the intent of filling the whole page of the in_cb_id circular buffer with negative infinities ? 

The issue seems to be in the main kernel.

**Comment by amahmudTT** [comment]
We are encountering two issues with the bug. 

1.  In the compute kernel when we push back to the output circular buffer using 
```cb_push_back(out_cb_id, 1)```

We are always pusing a row of 256 elements, now for each stick we call this twice, resulting it having 384 correct elements and 128 garbage elements. It seems the function in python that converts the out_cb_id is supposed to assume that the output buffer given to it has contiguous valid memory. Thus we are seeing that a row has 384 valid elements but the next row of the output has 128 invalid elements. 


2. Somehow the output buffer always gets -inf as garbage data in the places where it is supposed to have garbage data. It runs 2 times for each stick (4 sticks in total).  First time it fills up 256 valid elements and pushes to the circular buffer, then next time it fills up 128 valid elements and 128 garbage elements (which by chance are negative infinities) and pushes it. But the weird thing is for the first three sticks this works totally fine, indicating this is NOT a problem related to initialization or reinitialization, but for the last stick it fills the circular buffer with negative infinities in both iterations. We need to know where these negative infinities are coming from, it is unlikely the packer will put them and even if it does then why in the last iteration ? 

We need to check is some other thread is accessing the output buffer at the same time and filling them with negative infinities or not. Since thes program does not have a writer kernel, and modifying the fill function calls in the reader kernel so that they do not write negative infinities does not fix the issue. It is hard to guess who is doing this.

**Comment by amahmudTT** [comment]
The first problem mentioned above is confirmed.  If we restart the accelerator, most of the negative infinities go away and they appear in the last iteration only. So when we print out the result of the rows pushed into the output buffer for the first stick, we have 

```
First phase 256 valid elements pushed 

4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4

Second phase 128 valid and 128 garbage data pushed. 

4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 -1.07264e-37 5.98965e+31 -6.40949e-30 -6.19245e+15 1.60938e+25 -407552 nan 1.00101e-38 8.98078e-36 1.17038e+11 -2.51992e-20 3104 10.125 -2.22822e+06 6.88214e-22 -8.81621e-39 0.000210762 4.23124e+24 1.11553e+32 -2.93874e-38 -486 -0.000946045 9.32813e+09 9.3533e+08 -6.70399e-39 9.65595e-06 -2.63402e+09 -6.4756e-10 -1.46984e+23 1.34688e+31 7.36673e+13 -6.89088e+25 5888 -1.0175e-11 -1.47656 4.93487e+23 5.30579e+08 1.46937e-39 4.99585e-38 1.03186e+20 -5.10371e-33 -2.20508e+27 2.02659e-23 0.730469 8.9407e-08 -1.4628e+26 -1.69482e-32 2.80471e+26 4.79792e+24 0.0786133 -2.22928e+17 -6.29425e-05 7.89751e+19 -1.11603e+21 85.5 56576 -0.0327148 4.00895e+31 -1.89247e+10 4.69903e+35 -1.33878e-08 5.92923e-19 7.22561e+31 -1.3894e-25 -3.72893e-11 4.31654e+21 -9.36918e+25 1.42609e-08 1.54215e+22 -2.63731e+19 8.48025e-29 -1.71408e-32 3.28166e-27 6.91114e-15 22.875 3.8188e+31 -1.35525e-17 -4.56369e+25 2.29019e+29 4.2612e+21 -83 -2.69992e-21 -4.86533e+20 1.83936e-08 7.48598e-23 1.45519e-10 -1.16552e-18 2.59194e+27 -0.824219 -2848 -4.94396e-17 -1.50452e-26 -1.81528e+33 -20 1.02751e-24 532480 -1.96875 -1.61716e-28 -2.14338e+37 8.37519e+10 4.0362e+33 1.70252e-31 -3.89227e+14 6.0559e+11 2.0383e-17 -110080 2.13056e-33 -0.00021553 -2.4783e+26 4.06371e-32 8.63974e-19 5.08038e-13 2.7926e-33 -1.47774e+15 -14.125 -7.07789e+06 2.99767e-28 3.90595e+07 4.9478e+14 -8.11296e+32 -0.648438 -0.890625 -1.72674e-23 2.3593e+07 1.84467e+20 1.04234e+15 1.30182e+16 438272

```

Now looking at the tensor output 

```
_________________
tensor([[[[ 4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00,
            4.0000e+00,  4.0000e+00,  4.0000e+00,  4.0000e+00],
          [-1.0726e-37,  5.9896e+31, -6.4095e-30, -6.1924e+15,  1.6094e+25,
           -4.0755e+05,         nan,  1.0010e-38,  8.9808e-36,  1.1704e+11,
           -2.5199e-20,  3.1040e+03,  1.0125e+01, -2.2282e+06,  6.8821e-22,
           -8.8162e-39,  2.1076e-04,  4.2312e+24,  1.1155e+32, -2.9387e-38,
           -4.8600e+02, -9.4604e-04,  9.3281e+09,  9.3533e+08, -6.7040e-39,
            9.6560e-06, -2.6340e+09, -6.4756e-10, -1.4698e+23,  1.3469e+31,
            7.3667e+13, -6.8909e+25,  5.8880e+03, -1.0175e-11, -1.4766e+00,
            4.9349e+23,  5.3058e+08,  1.4694e-39,  4.9959e-38,  1.0319e+20,
           -5.1037e-33, -2.2051e+27,  2.0266e-23,  7.3047e-01,  8.9407e-08,
           -1.4628e+26, -1.6948e-32,  2.8047e+26,  4.7979e+24,  7.8613e-02,
           -2.2293e+17, -6.2943e-05,  7.8975e+19, -1.1160e+21,  8.5500e+01,
            5.6576e+04, -3.2715e-02,  4.0089e+31, -1.8925e+10,  4.6990e+35,
           -1.3388e-08,  5.9292e-19,  7.2256e+31, -1.3894e-25, -3.7289e-11,
            4.3165e+21, -9.3692e+25,  1.4261e-08,  1.5421e+22, -2.6373e+19,
            8.4803e-29, -1.7141e-32,  3.2817e-27,  6.9111e-15,  2.2875e+01,
            3.8188e+31, -1.3553e-17, -4.5637e+25,  2.2902e+29,  4.2612e+21,
           -8.3000e+01, -2.6999e-21, -4.8653e+20,  1.8394e-08,  7.4860e-23,
            1.4552e-10, -1.1655e-18,  2.5919e+27, -8.2422e-01, -2.8480e+03,
           -4.9440e-17, -1.5045e-26, -1.8153e+33, -2.0000e+01,  1.0275e-24,
            5.3248e+05, -1.9688e+00, -1.6172e-28, -2.1434e+37,  8.3752e+10,
            4.0362e+33,  1.7025e-31, -3.8923e+14,  6.0559e+11,  2.0383e-17,
           -1.1008e+05,  2.1306e-33, -2.1553e-04, -2.4783e+26,  4.0637e-32,
            8.6397e-19,  5.0804e-13,  2.7926e-33, -1.4777e+15, -1.4125e+01,
           -7.0779e+06,  2.9977e-28,  3.9059e+07,  4.9478e+14, -8.1130e+32,
           -6.4844e-01, -8.9062e-01, -1.7267e-23,  2.3593e+07,  1.8447e+20,
            1.0423e+15,  1.3018e+16,  4.3827e+05,
```

We can see the 128 garbage elements for the first stick appear in the output at the front of the next stick.

**Comment by amahmudTT** [comment]
For the second issue, it seems to be a non-deterministic issue since with addition & removal of print statements it went away, but we can see the negative infinities are not introduced by the packer since they are there even before the packer is working for the last iteration, and nothing in the compute kernel writes to the output circular buffer but the packer, so it might be the thread handling this tensor or working as a writer kernel may be modifying it and causing the race condition. 

```
BEFORE OUTPUT PAGE denotes before the packer has written to the page, 
OUTPUT PAGE denotes after the packer has written into it. Indicating the ovverwriting with the negative infinities is done by some other thread.

******************
NumOutTiles : 8
BEFORE OUTPUT PAGE
-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
_________________
OUTPUT PAGE
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
_________________
******************
NumOutTiles : 4
BEFORE OUTPUT PAGE
-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
_________________
OUTPUT PAGE
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf

```

**Comment by amahmudTT** [comment]
The bug that overwrites the result with negative infinities is not actually a big issue, it is just that when we print out too much data the buffer for the debug print while using packer gets corrupted, as if I print the output using the unpacker thread I still get the expected result. That is 4 rows with 256 4s and 4 rows with 128 4s and garbage or negative infinities, even though the result form packer debug print says they were overwritten by negative infinities.

**Comment by mywoodstock** [comment]
@wransom-TT This can be closed?

**Comment by wransom-TT** [comment]
yes
