### ISSUE TITLE
DPS version of matmul in TTNN

### ISSUE THREAD

**Issue by azecevicTT** [tenstorrent/tt-metal#15038]
Is there a reason why matmul (and linear) aren't modeled as DPS ops in TTNN? We model them as DPS ops in TTNN MLIR dialect, is there a plan to make them DPS ops in the future or should we change them to non DPS to reflect TTNN state.

**Comment by sdjordjevicTT** [comment]
Hi @bbradelTT, we discovered this during our onboarding in the TT-MLIR compiler. Can you give us some feedback on whether this inconsistency in the matmul op is a limitation or just needs to be implemented from your side?

**Comment by bbradelTT** [comment]
@sdjordjevicTT sounds good. @asandhupatlaTT will work on it.

**Comment by sdjordjevicTT** [comment]
Great, thanks! Let's keep this issue open to track the progress.

**Comment by bbradelTT** [comment]
@asandhupatlaTT 
Please try to see if it makes it easier if we convert to compute_output_specs for `struct Matmul`.
See ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op.hpp for an example.

**Comment by bbradelTT** [comment]
@sdjordjevicTT @azecevicTT which TTNN ops are DPS ops already? Using those as guides will help speed up development.

**Comment by sdjordjevicTT** [comment]
All the ops that define the optional output tensor in their APIs should be DPS.

For example, you can take a look at element-wise ops API definition:
https://github.com/tenstorrent/tt-metal/blob/8901511f737c15d181629ce4de93fae4a11da3b8/ttnn/cpp/ttnn/operations/eltwise/binary/binary.hpp#L29C1-L29C69

Or take a look at the embedding op and its optional output tensor:
https://github.com/tenstorrent/tt-metal/blob/8901511f737c15d181629ce4de93fae4a11da3b8/ttnn/cpp/ttnn/operations/embedding/embedding.hpp#L26C1-L26C70

**Comment by asandhupatlaTT** [comment]
fixed at https://github.com/tenstorrent/tt-metal/pull/15285
