### ISSUE TITLE
ttnn.max_pool2d fails in unit test of squeezenet model

### ISSUE THREAD

**Issue by vguduruTT** [tenstorrent/tt-metal#15040]
**Describe the bug**
ttnn.max_pool2d is failing with Row size should be power of 2 issue in unit test

**To Reproduce**
1. Checkout to this branch : [venkatesh/ttnn_squeezenet_maxpool_unit_test_fail](https://github.com/tenstorrent/tt-metal/tree/venkatesh/ttnn_squeezenet_maxpool_unit_test_fail)
2. Run`pytest tests/ttnn/unit_tests/operations/test_maxpool2d.py::test_run_max_pool_squeeze_net_model`
3. 
Input shape of ttnn tensor - [1, 96, 109, 109](N,C,H,W)
The following error will occur,
```
            RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/pool/maxpool/device/max_pool2d_device_op.cpp:26: is_pow2
            E       info:
            E       Row size (nchannels * bytes = 192) should be power of 2 (false).
```

**Please complete the following environment information:**
OS:Ubuntu 20.04.6 LTS
Device: WH n300

**Comment by saichandax** [comment]
@vguduruTT , is this issue fixed?

**Comment by vguduruTT** [comment]
This works fine in unit tests with the latest main, but the PCC drops when it's introduced into the pipeline. Moreover, the drop in PCC persists even after removing the added MaxPool-specific input.- [Issue](https://github.com/tenstorrent/cloud/issues/3435)

**Comment by saichandax** [comment]
@vguduruTT , Please create issue for low pcc, and closing this issue.
