### ISSUE TITLE
[Bug Report] Use after move in run_operation.cpp

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#15073]
**Describe the bug**
This is a bug discovered by clang-analyzer following a long discussion on discord. In `run_operation.cpp`. The `operation` object is moved before calling `operation.compute_output_shapes()`. Causing a UB. I am not sure weather if it is causing any actual trouble now, but probably worth fixing.

Due to the nature of non-const functions. I am unable to fix myself as I lack the low level understanding of how this part of program works.

**To Reproduce**

In `ttnn/cpp/ttnn/run_operation.cpp`, line 372-374 and 437-437

![Image](https://github.com/user-attachments/assets/7e6f0979-0382-4386-b21b-eefc08c333fa)

![Image](https://github.com/user-attachments/assets/4552d37c-36c0-4024-8ecc-eb18bfcc5332)

**Expected behavior**
Should not trigger UB.

**Screenshots**

**Please complete the following environment information:**
- Commit: 3b8fb6c4766fb8767b859f5d9d94da1b6f7b8c95

**Additional context**

**Comment by ayerofieiev-tt** [comment]
Thank you! On it!

**Comment by jvasilje** [comment]
Thanks @ayerofieiev-tt ! <3

**Comment by ayerofieiev-tt** [comment]
Fixing this specific issue.

Then we should enable the clang-tidy check and fixing any issue that it surfaces.
https://github.com/tenstorrent/tt-metal/blob/008c50a744ab398526f12992f9f4902283f9215a/.clang-tidy#L28

CC @blozano-tt @afuller-TT

**Comment by marty1885** [comment]
Thanks for the quick patch! There shouldn't be any more as of now. I ran clang-analyzer over the entire codebase and this is the only use after move.

**Comment by marty1885** [comment]
Close as patch merged.
