### ISSUE TITLE
After picking up latest main avg_pool2d fails PCC in pytorch compiler

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/tt-metal#15129]
**Describe the bug**
This is a regression.
This test is failing in pytorch compiler with PCC error
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/main/tests/lowering/pool/test_avg_pool_2d.py

```
    def assert_with_pcc(expected_pytorch_result, actual_pytorch_result, pcc=0.999):
        assert list(expected_pytorch_result.shape) == list(
            actual_pytorch_result.shape
        ), f"list(expected_pytorch_result.shape)={list(expected_pytorch_result.shape)} vs list(actual_pytorch_result.shape)={list(actual_pytorch_result.shape)}"
        pcc_passed, pcc_message = comp_pcc(expected_pytorch_result, actual_pytorch_result, pcc)
>       assert pcc_passed, construct_pcc_assert_message(pcc_message, expected_pytorch_result, actual_pytorch_result)
E       AssertionError: 0.11032829709496224
```

The conversion is trivial:
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/main/torch_ttnn/passes/lowering/to_tt_pass.py#L355-L358

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software: possibly started to appear after rc41

**Comment by mywoodstock** [comment]
This particular test is covered in tt-metal, under `tests/ttnn/unit_tests/operations/test_global_avg_pool2d.py`. I checked the latest `main` fails with PCC error on this. Going to the CI -- I see this as passing 2 hours ago on `main` at commit `36d9c9de2daa64e2186d5d11505536f656af88d0`: https://github.com/tenstorrent/tt-metal/actions/runs/11897141178. When I check out `main` at this commit, its failing for me. So:
1. There is definitely a regression in `reduce` op (this global_avg_pool is a wrapper around reduce).
2. Something is VERY wrong with the CI -- how can it see passing when its been failing for a 3 days.

@bbradelTT could you please take a look at this 1. regression, since its the reduce op?

Not sure what needs to be done for 2.?

**Comment by bbradelTT** [comment]
@mywoodstock if someone broke all post commits in the last two hours they should fix it.

But this issue was created 3 days ago.

If you can provide me with a test that calls ttnn.reduce and fails with bad PCC, then I can take a quick look.

**Comment by bbradelTT** [comment]
From an earlier build, I couldn't recreate the failure:
```
================================================ short test summary info =================================================
PASSED tests/ttnn/unit_tests/operations/test_global_avg_pool2d.py::test_run_average_pool2d[dtype=DataType.BFLOAT16-resnet50_unpadded]
PASSED tests/ttnn/unit_tests/operations/test_global_avg_pool2d.py::test_run_average_pool2d[dtype=DataType.BFLOAT16-tile_divisible]
```

**Comment by mywoodstock** [comment]
I agree @bbradelTT . This is very strange as when i checkout the commit from the last full run on `main` on CI, it fails for me but the pipelines says it passed.

**Comment by bbradelTT** [comment]
Then this really doesn't sound like a regression in the reduce op.

**Comment by ayerofieiev-tt** [comment]
@mywoodstock @bbradelTT can you push this to resolution?

**Comment by mywoodstock** [comment]
@ayerofieiev-tt we need someone to do a git bisect to identify the commit/commits that broke this and revert it.

**Comment by bbradelTT** [comment]
@ayerofieiev-tt @mywoodstock I don't have an example that shows reduce failing on tt-metal for this specific issue.
Once that is provided, I can take a look.

If the commit was a fix for a P0 we might not want to, and might want to figure out what's wrong first.

**Comment by mywoodstock** [comment]
@bbradelTT The above test on average_pool is the example. Average pool here is simply a wrapper over the reduce op.

**Comment by bbradelTT** [comment]
The problem is I run that test locally and get
```
PASSED tests/ttnn/unit_tests/operations/test_global_avg_pool2d.py::test_run_average_pool2d[dtype=DataType.BFLOAT16-resnet50_unpadded]
```

**Comment by mywoodstock** [comment]
> The problem is I run that test locally and get
> 
> ```
> PASSED tests/ttnn/unit_tests/operations/test_global_avg_pool2d.py::test_run_average_pool2d[dtype=DataType.BFLOAT16-resnet50_unpadded]
> ```

Is this on latest main? It fails for me.

**Comment by bbradelTT** [comment]
Not latest main. But this issue was filed many days ago.

**Comment by bbradelTT** [comment]
I tested with latest main on WH and the avg pool2d tests pass for me:
```
================================================ short test summary info =================================================
PASSED tests/ttnn/unit_tests/operations/test_global_avg_pool2d.py::test_run_average_pool2d[dtype=DataType.BFLOAT16-resnet50_unpadded]
PASSED tests/ttnn/unit_tests/operations/test_global_avg_pool2d.py::test_run_average_pool2d[dtype=DataType.BFLOAT16-tile_divisible]
============================================= 2 passed, 2 warnings in 5.24s ==============================================
```

@ayerofieiev-tt can you please try again with latest main, and if it still doesn't work, provide a tt-metal side test that fails on tt-metal?

**Comment by ayerofieiev-tt** [comment]
Lets close for now
