### ISSUE TITLE
Add support for binary SFPU OPs

### ISSUE THREAD

**Issue by ttmtrajkovic** [tenstorrent/tt-metal#15122]
Need to add support for binary SFPU OPs that will accept 2 input tiles and produce one output.
both input tiles need to reside in DEST, thus effective size of subblock will be reduced by 2 for these ops.

@rdjogoTT to add more details as the work progresses
Currently gating other LLK and OP issues: 
- https://github.com/tenstorrent/tt-metal/issues/13857
- https://github.com/tenstorrent/tt-metal/issues/13754
- https://github.com/tenstorrent/tt-metal/issues/13582
- https://github.com/tenstorrent/tt-metal/issues/13445
- https://github.com/tenstorrent/tt-metal/issues/10034

Milos

**Comment by rdjogoTT** [comment]
Update can be found at: https://github.com/tenstorrent/tt-metal/issues/13857#issuecomment-2487009826
Basically, LLK level Binary SFPU OP support has been added for WH with APIs for basic OPs working (Add, Sub, Mul), and Pow is still in progress.

**Comment by rdjogoTT** [comment]
Update here: https://github.com/tenstorrent/tt-metal/issues/13857#issuecomment-2501279109
-> Pow PCC >0.99998 for non-negative base values, working on handling special cases where base is negative or base/power are NaN or Inf.

**Comment by rdjogoTT** [comment]
All LLK APIs have been added into main.
