### ISSUE TITLE
Unit test fails if tensor shape is not tile multiple

### ISSUE THREAD

**Issue by kmitrovicTT** [tenstorrent/tt-metal#15131]
**Describe the bug**

Running `tests/ttnn/unit_tests/operations/eltwise/test_binary_composite.py::test_binary_remainder_ttnn` with shape `(1, 1, 3, 3)` fails with 

```
Unsupported shape for tensor conversion from row-major to tile layout. The tensor shape height and width must be a multiple of tile height (32) and width (32), but the provided shape is Shape([1, 1, 3, 3]).
```

I am aware there is an ongoing effort to support shapes not divisible by tile size. If this is a duplicate, please link the original one. This one is raised to keep track in TT-Forge, because it popped up during testing.

**To Reproduce**

```
pytest -svv tests/ttnn/unit_tests/operations/eltwise/test_binary_composite.py::test_binary_remainder_ttnn
```

**Comment by KalaivaniMCW** [comment]
Hi @kmitrovicTT, 
 The utility functions used in this test are specific to TILE shaped inputs. 
For non-TILE shapes i.e. for inputs that need padding you can try this instead, 

```
@pytest.mark.parametrize(
    "shapes",
    [
        [[1, 1, 3, 3], [1, 1, 3, 3]],
    ],
)
@skip_for_grayskull("Unsupported for Grayskull")
def test_shape_remainder(device, shapes):
    torch.manual_seed(0)
    high = 10
    low = -10

    torch_input_tensor_a = torch.rand(shapes[0], dtype=torch.bfloat16) * (high - low) + low

    high = 9
    low = -9
    torch_input_tensor_b = torch.rand(shapes[1], dtype=torch.bfloat16) * (high - low) + low

    golden_function = ttnn.get_golden_function(ttnn.remainder)
    torch_output_tensor = golden_function(torch_input_tensor_a, torch_input_tensor_b)

    input_tensor_a = ttnn.from_torch(
        torch_input_tensor_a, layout=ttnn.TILE_LAYOUT, device=device, memory_config=ttnn.DRAM_MEMORY_CONFIG
    )
    input_tensor_b = ttnn.from_torch(
        torch_input_tensor_b, layout=ttnn.TILE_LAYOUT, device=device, memory_config=ttnn.DRAM_MEMORY_CONFIG
    )

    output_tensor = ttnn.remainder(input_tensor_a, input_tensor_b, memory_config=ttnn.DRAM_MEMORY_CONFIG)
    output_tensor = ttnn.to_torch(output_tensor)

    assert ttnn.pearson_correlation_coefficient(torch_output_tensor, output_tensor) >= 0.999

```

**Comment by kmitrovicTT** [comment]
Hey @KalaivaniMCW . Thanks for response!

Good thing you told me to try that. I copy-pasted your code and now I am getting 

```
When preallocted output tensor is used, Unary operation requires its shape to match the computed shape. Computed shape: SimpleShape([1, 1, 3, 3]), Shape in preallocated output tensor: ttnn.Shape([1, 1, 3[32], 3[32]])
```

which is the exact same error causing the `jax` [issue](https://github.com/tenstorrent/tt-xla/issues/70) which lead me to raise this issue in metal. I was wondering why the messages were not the same.

**Comment by KalaivaniMCW** [comment]
Hi @kmitrovicTT 
is it still failing on latest main? [It should be working fine now after this]( https://github.com/tenstorrent/tt-metal/blob/b8f6d12b38e79fed481b8a0ccf8cff2bebee6c0d/tests/ttnn/unit_tests/operations/eltwise/test_binary_composite.py#L498-L522)

**Comment by KalaivaniMCW** [comment]
Hi @kmitrovicTT 
Did the test work? If so, shall I close this issue ?

**Comment by KalaivaniMCW** [comment]
Will close this issue, as test is passing on main. reopen if necessary
