### ISSUE TITLE
Fix single-card e2e perf regressions and nightly FD for end of week of Nov 11, 2024

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#15144]
## What we know

- Beginning around Nov 8 (end of week of Nov 4), we started seeing non-deterministic hangs in GS perf pipelines and mamba in nightly FD
  - This seems to start at: https://github.com/tenstorrent/tt-metal/actions/runs/11748738312. Now, attempt 1 was all good, but re-running it all seems to cause hangs and I don't think it's bad-board related.
  - LKG seems to be: https://github.com/tenstorrent/tt-metal/actions/runs/11746299514
- Beginning around Nov 12 during working hours in India, we started seeing deterministic errors in ttnn code, causing trisc0 build errors in ttnn integration tests in GS in nightly FD and what seems to be seg faults in single-card e2e perf GS:
  - https://github.com/tenstorrent/tt-metal/actions/runs/11747156496 seems to be be LKG for FD nightly ![Image](https://github.com/user-attachments/assets/168506c2-6fdc-46bb-8c94-c9d7a773fa96)
  - https://github.com/tenstorrent/tt-metal/actions/runs/11748740177 we start seeing some very frequent mamba hangs
  - https://github.com/tenstorrent/tt-metal/actions/runs/11794900477 seems to be before some suspect ttnn changes, but after ring buffer changes
  - https://github.com/tenstorrent/tt-metal/actions/runs/11796802875 seems to after suspect ttnn changes
- Beginning around Nov 15 morning time in Toronto, we see yolov4 fail on N150 and N300
  - LKG: https://github.com/tenstorrent/tt-metal/actions/runs/11857595953
  - Failure starts: https://github.com/tenstorrent/tt-metal/actions/runs/11859450777
  - I suspect it's https://github.com/tenstorrent/tt-metal/commit/79ff70b0e115ac50e70a72391dde3c4a4a6fab7f

## What I'm suspicious of

- https://github.com/tenstorrent/tt-metal/commit/274f58a0c88d0e6926fe626fe4679f7ba778ec89 (suspect ttnn changes) seems to have caused some seg faults in e2e perf and failures in ttnn integration tests in nightly FD: ![Image](https://github.com/user-attachments/assets/b8238069-e49c-4376-95ae-f279d12c0e10)
  - Confirmed locally: This causes seg faults in a ttnn integration test for bert, and likely in model perf for GS as well
- https://github.com/tenstorrent/tt-metal/commit/d9df440d6256cf6e6e42b8b9de71ffc03fa60181 seems to have caused non-deterministic hangs in mamba on nightly FD and in e2e perf regressions
  - A couple commits after: https://github.com/tenstorrent/tt-metal/actions/runs/11872276397 hangs, although doesn't seg fault. I originally used this branch to check if ttnn integration tests were broken because of https://github.com/tenstorrent/tt-metal/commit/274f58a0c88d0e6926fe626fe4679f7ba778ec89, and it seems like it is: https://github.com/tenstorrent/tt-metal/actions/runs/11800976058
- https://github.com/tenstorrent/tt-metal/commit/79ff70b0e115ac50e70a72391dde3c4a4a6fab7f seems to have caused trace region to increase in size for yolov4

## What I'm doing

- Ran 4 invocations of single card e2e perf on `rkim/0-check-device-perf-pipes-pgkeller` which is "1 commit" before jbauman's ring buffer changes (with an extra commit in-between that includes clang changes from King Fuller) to stress test model perf
- Ran 4 invocations of single card e2e perf on `rkim/0-check-device-perf-pipes` which is on jbauman's ring buffer changes
- A couple re-runs AFTER jbauman's ring buffer: https://github.com/tenstorrent/tt-metal/actions/runs/11794897286 to check non-det-ness
- Ran a couple invocations of nightly FD on a commit before jbauman's ring buffer changes: https://github.com/tenstorrent/tt-metal/actions/runs/11789131288
- Ran a couple invocations of nightly FD on a commit before suspect ttnn changes, but after jbauman changes: https://github.com/tenstorrent/tt-metal/actions/runs/11800976058
- Ran a couple invocations nightly FD on a commit before suspect ttnn changes, but after jbauman changes (different commit from above): https://github.com/tenstorrent/tt-metal/actions/runs/11794900477
- Ran 3 invocations of FD nightly on main without @KalaivaniMCW 's changes on branch [rkim/15144-no-kalaviani](https://github.com/tenstorrent/tt-metal/tree/refs/heads/rkim/15144-no-kalaviani) - I expect we see all tests except mamba and yolov4 pass unless there were more regressions introduced during that time
  - Result: Minus intermittent failures, looks like ttnn integration tests pass, with errors in mamba and yolov4 (expected): https://github.com/tenstorrent/tt-metal/actions/runs/11882892352
- Ran single-card e2e on branch [rkim/15144-no-kalaviani](https://github.com/tenstorrent/tt-metal/tree/refs/heads/rkim/15144-no-kalaviani): https://github.com/tenstorrent/tt-metal/actions/runs/11886648244 - I expect this to either pass (unlikely) or hang (more likely) because of jbaumans' ring buffer changes.
- Custom test dispatch of mamba on N150 right before ring buffer changes from @jbaumanTT : https://github.com/tenstorrent/tt-metal/actions/runs/11882644591
  - Result: passed!
- Will bisect locally for yolov4 error: I suspect 79ff70b0e115ac50e70a72391dde3c4a4a6fab7f
  - Looks like it's a small trace region error, along with a `0xffffffff please reset` ... unfortunate. Testing fix: https://github.com/tenstorrent/tt-metal/actions/runs/11886623375 - UPDATE: Looks like that did it!

**Comment by tt-rkim** [comment]
cc: @TT-billteng @pgkeller @KalaivaniMCW @eyonland @jbaumanTT 

FYI - I think some ttnn changes and the ring buffer changes have caused more issues than we realize. Will post updates.

@pavlejosipovic has also noticed.

**Comment by tt-rkim** [comment]
Looks like yolov4 is the last deterministic failure that was introduced: https://github.com/tenstorrent/tt-metal/actions/runs/11882892352

Trace region error. Testing with more trace region: https://github.com/tenstorrent/tt-metal/actions/runs/11886623375

**Comment by tt-rkim** [comment]
Looks like that did it! Merging

**Comment by tt-rkim** [comment]
Merged revert of @KalaivaniMCW (cc @eyonland ) changes

**Comment by blozano-tt** [comment]
Impressive Debug

**Comment by tt-rkim** [comment]
After splitting the mamba test cases into 6 (WTF) groups, I found that some tests seem to just need a pcc threshold change, which I will do on main: https://github.com/tenstorrent/tt-metal/actions/runs/11996766311/job/33441680637

Others die with scary `FW unable to init` errors: https://github.com/tenstorrent/tt-metal/actions/runs/11996766311/job/33441680637#step:9:436

Will be testing out specific cases that seem to fail:

https://github.com/tenstorrent/tt-metal/actions/runs/12002871749
https://github.com/tenstorrent/tt-metal/actions/runs/12002876802
https://github.com/tenstorrent/tt-metal/actions/runs/12002882887
