### ISSUE TITLE
[Feature Request] Support for system queries on MeshDevice

### ISSUE THREAD

**Issue by cfjchu** [tenstorrent/tt-metal#15141]
@marty1885 has requested query-able APIs for the following:

`MeshDevice:: get_memory_allocation_statistics`,
`MeshDevice:: get_num_dram_channels`

> To be specific, I need get_memory_allocation_statistics in MeshDevice. GGML needs to know the memory currently used and how much is in total it have. Also get_num_dram_channels since allocation stats is per-channel and I need to know the size is bytes

**Comment by marty1885** [comment]
For context. The only reason I bring up `get_memory_allocation_statistics` and `get_num_dram_channels` is because that's the API Device provides. I just need the total and free memory in bytes. I'm perfectly happy with alternative solutions as long as the information if query-able somehow.
