### ISSUE TITLE
ttnn.upsample inconsistent interface

### ISSUE THREAD

**Issue by azecevicTT** [tenstorrent/tt-metal#15158]
`ttnn.upsample` scale_factor parameter is inconsistent with both [TF](https://www.tensorflow.org/api_docs/python/tf/keras/layers/UpSampling2D) and [Torch](https://pytorch.org/docs/stable/generated/torch.nn.Upsample.html). If we are only supporting 2D upsampling (which is also case with TF) it only makes sense that scale_factor is int for uniform scaling or (int, int) for scaling factors of H and W respectively. Will scale factors for N and C ever make sense, because I can't see a use case for them in upsampling. Regardless of that, (int, int) case should always be scale factors for H and W, current situation where it's interpreted as factors for W and C (where C is only asserted to equal 1) is totally counter-intuitive.

Also citing documentation `scale_factor (int or tt::tt_metal::Array2D or tt::tt_metal::Array3D or tt::tt_metal::Array4D) – multiplier for spatial size. Has to match input size if it is a tuple.`, sentence `Has to match input size if it is a tuple.` looks out of place.

FYI @sdjordjevicTT @nvukobratTT

**Comment by sdjordjevicTT** [comment]
@prajaramanTT @nkpatel-tt @mywoodstock do you have any update regarding this issue? We want to support this op in the TT-MLIR compiler, hence we are seeking some updates regarding this.

**Comment by nkpatel-tt** [comment]
@sdjordjevicTT  I will start looking into it now.

**Comment by sdjordjevicTT** [comment]
Thank you, @nkpatel-tt. If you need any assistance or further clarification, please feel free to contact us.
