### ISSUE TITLE
Improve parallelisation strategy for conv2d

### ISSUE THREAD

**Issue by pavlejosipovic** [tenstorrent/tt-metal#15171]
Conv2d determines number of work items along height and width dim and than tries to map to an array of tensix cores in 1d or 2d depending on the sharding strategy selected. In case this number of work items is a primer number or close to the prime number, conv2d will map one core or  a handful  of cores. 
In addition to poor performance in these cases, this leads to out-of-memory issues since conv2d can use small number of cores to store the sharded tensors, and single core gets to process large chunk of work.

To improve on this we need to pad number of work items so that we can distribute the the workload in an effective way over the grid of tensix cores.

**Comment by kmabeeTT** [comment]
Hi @pavlejosipovic  - We hit compile [error](https://github.com/tenstorrent/tt-mlir/actions/runs/12063102177/job/33637775016#step:9:2385) in tt-mlir after uplifting to latest tt-metal that includes this change because new field `enable_channels_padding` on `determine_parallel_config()` was added but we don't set it.   What is guidance for setting this field?  FYI @LPanosTT

**Comment by pavlejosipovic** [comment]
> Hi [@pavlejosipovic](https://github.com/pavlejosipovic) - We hit compile [error](https://github.com/tenstorrent/tt-mlir/actions/runs/12063102177/job/33637775016#step:9:2385) in tt-mlir after uplifting to latest tt-metal that includes this change because new field `enable_channels_padding` on `determine_parallel_config()` was added but we don't set it. What is guidance for setting this field? FYI [@LPanosTT](https://github.com/LPanosTT)

For conv ops  it should be set to true, and for max_pool it should be set to false.
Hopefully, we will enable this feature for max_pool as well, and get auto-sharing support as well so you won't have to use this function.
