### ISSUE TITLE
[Bug Report] dprint buffer has unexpected data in it

### ISSUE THREAD

**Issue by nhuang-tt** [tenstorrent/tt-metal#15178]
**Describe the bug**
Unexpected data is seen when DPRINT is enabled for Chip 0, 1 on Wormhole N300.

**To Reproduce**

Run any test that will use Chip 0 and 1 and enable DPRINT on both chips. DPRINT statements are not required in the kernel to reproduce this issue.

```
export TT_METAL_DPRINT_CORES=all
export TT_METAL_DPRINT_ETH_CORES=all
./build/test/tt_metal/perf_microbenchmark/routing/test_vc_uni_tunnel
```

An exception will be thrown saying "Unexpected debug print type code" or something like 1 bytes expected but 0 bytes in the DPRINT buffer.

There will be an exception 2 times, and on the 3rd try the test will pass.

And there are no issues if DPRINT is enabled only on Chip 1 (`TT_METAL_DPRINT_CHIPS=1`).

**Expected behavior**
Prints are shown in the console.

**Screenshots**
```
��                 Always | FATAL    | Unexpected debug print type code
libc++abi: terminating due to uncaught exception of type std::runtime_error: TT_THROW @ /localdev/nhuang/tt-metal/tt_metal/impl/debug/dprint_server.cpp:956: tt::exception
info:
Unexpected debug print type code
```

**Please complete the following environment information:**
- Debug and Release build are seeing the same issue

- N300

- Git commit is at top of the main branch - 36d9c9de2daa64e2186d5d11505536f656af88d0

**Additional context**
The DPRINT buffer address is at `tt::tt_metal::HalL1MemAddrType::DPRINT`. No test cases use that address as far as I know.

**Comment by pgkeller** [comment]
fyi: @tt-dma I heard from somewhere else that dprint from remote chip hangs under stress, good to look into this.  may be able to reproduce by just of dprints from remote chip?

**Comment by nhuang-tt** [comment]
I'm also seeing DPRINT Enabled on Device 0 twice. I'm not sure if that's expected.

```
                 Device | INFO     | Opening user mode device driver
  Detecting chips (found 2)
2024-11-19 07:27:03.894 | INFO     | SiliconDriver   - Detected 1 PCI device : [4]
2024-11-19 07:27:03.964 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.9.0 (Device 0)
2024-11-19 07:27:03.965 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.9.0 (Device 1)
                  Metal | INFO     | Initializing device 0. Program cache is NOT enabled
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
                 Always | WARNING  | Dispatch Core Type = CoreType::WORKER
                  Metal | INFO     | DPRINT enabled on device 0, all worker cores.
                  Metal | INFO     | DPRINT enabled on device 0, all ethernet cores.
                  Metal | INFO     | DPRINT Server attached device 0
                  Metal | INFO     | Initializing device 1. Program cache is NOT enabled
                  Metal | INFO     | AI CLK for device 1 is:   1000 MHz
                 Always | WARNING  | Dispatch Core Type = CoreType::WORKER
                  Metal | INFO     | DPRINT enabled on device 0, all worker cores.
                  Metal | INFO     | DPRINT enabled on device 0, all ethernet cores.
                  Metal | INFO     | DPRINT Server attached device 0
                 Always | WARNING  | Dispatch Core Type = CoreType::WORKER
```
