### ISSUE TITLE
Using sharded config with specific setup leads to segfault

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#15247]
Using sharded config with specific setup on WH with eltwise unary ops leads to segfault. This is setup which leads to segfault:

```
input_shape [1, 1, 25088, 2] 
DataType.BFLOAT16 
Layout.ROW_MAJOR 
ShardStrategy.BLOCK 
ShardOrientation.COL_MAJOR 
tensor_hw_as_shard_shape True
```

or 

```
input_shape [1, 8704, 4],
ttnn.bfloat16,
ttnn.ROW_MAJOR_LAYOUT,
ttnn.ShardStrategy.BLOCK,
ttnn.ShardOrientation.COL_MAJOR,
tensor_hw_as_shard_shape True,
```

* Steps to reproduce

Checkout ngrujic/unit-tests-1branch (soon to be merged into main). There are two unit tests (with two different ops) which can showcase this problem:

```
pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_eltwise_isfinite_sharded_segfault.py
pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_eltwise_exp_sharded_segfault.py
pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_eltwise_isposinf_sharded_segfault.py
```

**Comment by umadevimcw** [comment]
@nemanjagrujic  When i tried to exceute the sample code in from you commit I am getting following error. Here col 2, hence I have changed the orientation from COL_MAJOR to ROW_MAJOR 

![Image](https://github.com/user-attachments/assets/cd39e093-83de-4da4-9ae2-2b43f0c59a4f)


After changing the orientation I am getting following error (OOM)

![Image](https://github.com/user-attachments/assets/50d7051c-3402-444d-b2e6-885d7c94f4cc)

**Comment by nemanjagrujic** [comment]
@umadevimcw OK, Ill check...

**Comment by umadevimcw** [comment]
@nemanjagrujic if `tensor_hw_as_shard_shape` is true the col should be multiple of 16,  i got this error when I use (1, 1, 20480 , 2)

![Image](https://github.com/user-attachments/assets/4b8c7d37-58f6-4e7e-8972-eae7c26e36af)


if we go futher like 1,1, 20480, 32 -> OOM error

**Comment by nemanjagrujic** [comment]
@umadevimcw These asserts were added after I created ticket and unit tests. So earlier we have been observing segfault in these cases. I'll check a bit more to see if this ticked is invalid now, or needs to be changed.

**Comment by umadevimcw** [comment]
@nemanjagrujic Is this valid or can we close this issue?

**Comment by nemanjagrujic** [comment]
The code has changed so we are not observing this bug anymore.
