### ISSUE TITLE
[Feature Request] Support Grayskull as 1x1 mesh devices

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#15297]
**Is your feature request related to a problem? Please describe.**

Possibly related to #15296

I'm working on migrating my GGML backend to use `MeshDevice` instead of `ttnn::Device` as the first step to support multi WH chips. However this change breaks Grayskull compatibility completely as TTNN refuses to create a MeshDevice with a single GS chip in it. GS is currently is most popular devices among FOSS users, this severely reduces the people capable of running the software and contribute in the future.

Due to a warning message during initialization. I am not sure if it's actually TTNN refusing to make 1x1 GS mesh, or failing to recognize the board leading to the error. It is a problem that needs to be solve nevertheless.

Running the following program results in error:

```c++
#include <cstddef>
#include <ttnn/core.hpp>
#include <ttnn/distributed/api.hpp>

#include <vector>
#include <iostream>

int main()
{
    auto& sys = tt::tt_metal::distributed::SystemMesh::instance();
    auto mesh = ttnn::distributed::open_mesh_device({1, 1}, DEFAULT_L1_SMALL_SIZE, DEFAULT_TRACE_REGION_SIZE, 1, tt::tt_metal::DispatchCoreType::WORKER);


    std::cout << sys.get_shape().first << "x" << sys.get_shape().second << std::endl;
}
```

Output:

```
                 Device | INFO     | Opening user mode device driver
  Detecting chips (found 1)                                                                                                            
2024-11-21 07:47:15.053 | WARNING  | SiliconDriver   - Unknown board type for chip 0. This might happen because chip is running old firmware. Defaulting to DEFAULT
2024-11-21 07:47:15.062 | INFO     | SiliconDriver   - Detected 1 PCI device : [0]
2024-11-21 07:47:15.062 | WARNING  | SiliconDriver   - Unknown board type for chip 0. This might happen because chip is running old firmware. Defaulting to DEFAULT
                 Always | FATAL    | Unsupported number of devices: 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ /home/marty/Documents/not-my-projects/tt-metal/tt_metal/distributed/mesh_device.cpp:64: system_mesh_to_shape.contains(system_num_devices)
info:
Unsupported number of devices: 0
backtrace:
 --- tt::tt_metal::distributed::SystemMesh::get_system_mesh_shape(unsigned long)
 --- tt::tt_metal::distributed::SystemMesh::initialize()
 --- tt::tt_metal::distributed::SystemMesh::instance()
 --- ./ttnn-hello(+0xed3f) [0x5614e04dbd3f]
 --- /usr/lib/libc.so.6(+0x25e08) [0x7ce56d634e08]
 --- /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7ce56d634ecc]
 --- ./ttnn-hello(+0xd915) [0x5614e04da915]

[1]    3706 IOT instruction (core dumped)  ./ttnn-hello
```

**Describe the solution you'd like**
Even though GS does not support networking. It should be allowed to be made into an 1x1 device.

**Describe alternatives you've considered**

**Additional context**
* OS: Arch Linux
* Commit: 75868aad6a85f5a4dea37d5c849fe3be6a42e2e4
* Card: Grayskull e75

**Comment by kmabeeTT** [comment]
Thanks for ticket! Some folks in tt-mlir reported this today too, I bisected to commit 58063dbf6c from Nov13 as the culprit, and @abhullar-tt is going to make a fix.

**Comment by abhullar-tt** [comment]
PR https://github.com/tenstorrent/tt-metal/pull/15475 should address this, please let me know if this does not solve your issue

**Comment by marty1885** [comment]
@abhullar-tt Thanks for the PR! Just tested and it works now, I'll close the issue once the PR is merged. Have a nice thanksgiving soon!

**Comment by marty1885** [comment]
Closing as the PR has been merged. Thanks all.
