### ISSUE TITLE
Hardware counters are not incrementing for writes using dynamic noc in test_remote_cb_sync_matmul

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#15339]
If I insert a write barrier before the sem inc in `tests/tt_metal/tt_metal/perf_microbenchmark/common/kernels/writer_l1.cpp::remote_cb_push_back_and_write_pages` for the noc used by `noc_async_write_one_packet`, I see it hang in the barrier.

Polling the HW counters for both nocs show they are zero for some reason meaning it never incremented, even though the test properly completes and has correct output without the write barrier.

Need to figure out what the cause is.

**Comment by yugaoTT** [comment]
close as this is resolved by using local L1 scratch counters
