### ISSUE TITLE
[Bug Report] Frequent freezes during training

### ISSUE THREAD

**Issue by rfurko-tt** [tenstorrent/tt-metal#15349]
**Describe the bug**
Running training with GPT-2S results in frequent freezes after ~300k samples. 
Training restart also requires `tt-smi -r 0`
Switch blocking from false to true removes the issue: `tt::tt_metal::EnqueueProgram(queue, program, false);`

**To Reproduce**
1. Branch: rfurko/kahan_summation
2. Run tt-train/nano-gpt example 
3. Wait for 500-2000 steps 
4. Freeze 

**Expected behavior**
No freezes and crashes

**Screenshots**
One thread callstack here: 
![Image](https://github.com/user-attachments/assets/03edcb07-a15d-40ea-9fe0-26353c75fefc)
All other threads callstack:
![Image](https://github.com/user-attachments/assets/eee22300-e9b6-407b-8b87-639e2e7d4959)

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Version of software: rfurko/kahan_summation

**Comment by dmakoviichuk-tt** [comment]
@davorchap we are not convinced that it is related to the di/dt. My expectation didt would happen anyway if we have blocking EnqueueProgram.So this is pretty annoying issue.
@tt-asaigal  feel free to ping Roman if you need any help to reproduce this issue.

**Comment by rfurko-tt** [comment]
In the shared branch we forced matmul to use sublocks (1, 1) to minimize possibility di/dt. It didn't change frequency of freezes.

**Comment by tt-asaigal** [comment]
I took a look at the branch, and its fairly out of sync with latest main. A fairly non-deterministic hang was exposed by [this](https://github.com/tenstorrent/tt-metal/commit/d9df440d6256cf6e6e42b8b9de71ffc03fa60181) commit pushed on Nov 8, for which a workaround went in yesterday.
The branch has the hanging commit but not the workaround. Would it be possible to rebase on latest main and try the workload again?

**Comment by dmakoviichuk-tt** [comment]
@tt-asaigal could you show a link to the workaround?

**Comment by tt-asaigal** [comment]
please try cherry-picking these 2 in order:
https://github.com/tenstorrent/tt-metal/commit/9fff3ce65b2ade277db3ff8474c32ee294cbfb7e
https://github.com/tenstorrent/tt-metal/commit/30364957fe888854bda3ae43a00b1867f7c2291c

**Comment by rfurko-tt** [comment]
I've rebased to latest main and can confirm that freezing is not an issue now. Thanks @tt-asaigal!
