### ISSUE TITLE
ttnn.reshape fails with low PCC when reshaping to a 2D tensor from 4D in data parallel setup

### ISSUE THREAD

**Issue by vigneshkeerthivasanx** [tenstorrent/tt-metal#15456]
**Describe the bug**
Reshaping a tensor from 4D to 2D in a data parallel setup with ttnn.reshape results in low PCC. where PCC  =  ~0.000422

**To Reproduce**

1. pick the test from [Commit](https://github.com/tenstorrent/tt-metal/compare/main...vignesh/test_reshape_mesh_device)
2. Run `pytest tests/ttnn/unit_tests/operations/test_reshape_mesh.py`

**Expected behavior**
ttnn.reshape is expected to reshape the 4D tensor to 2D tensor with good PCC.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Comment by saichandax** [comment]
Same as #15422. Closing this as duplicate.
