### ISSUE TITLE
Installing.md needs to be streamlined

### ISSUE THREAD

**Issue by dimitri-tenstorrent** [tenstorrent/tt-metal#15499]
In Step 4, the numbered list is conflated with Option Headings. There should be a stricter hierarchical relationship between the headings and steps.

Please note Steps 1..4 in non-heading style within `Step 4. Install and start using TT-NN and TT-Metalium!`
![Image](https://github.com/user-attachments/assets/240476fd-3560-473c-8edc-d243372e4347)

These steps are also continued in a confusing way in Options 1 and Option 2. Please see the screenshot below.
![Image](https://github.com/user-attachments/assets/a31658b0-cca0-4f7d-a90b-07ff4ffc1fa9)

**Comment by dimitri-tenstorrent** [comment]
@bbeggsTT The screenshots are from the branch dimitri/12496_release_images which is not yet in main but the same problem exists on main.

**Comment by bbeggsTT** [comment]
Problems:
- The numbered list should not continue from the Step 4 in to Option 2.
- Options should be on a different hierarchical level.
