### ISSUE TITLE
Remove test_llama_perf

### ISSUE THREAD

**Issue by yieldthought** [tenstorrent/tt-metal#15539]
**Proposal: remove `models/demos/llama3/tests/test_llama_perf`**

e2e performance is measured from `demo.py`, `test_llama_perf` doesn't measure prefill, doesn't use tracing, device perf can be measured from the demo directly, it no longer has a compelling reason to exist and be maintained.

**Comment by mtairum** [comment]
This was shipped with the latest Llama3 text feature complete PR.
