### ISSUE TITLE
[Bug Report] Allocator is unusably slow under high memory pressure

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#15535]
**Describe the bug**
The current device memory allocator is quite show in my GGML backend under heavy load. This is because some TTNN operators and some of my GGML implementations will allocate DRAM address to store temporary data. Leading to a lot of small gaps in the DRAM space. Causing large allocations needing to walk the entire free list to get to the free space at the end of the linked list.

**To Reproduce**
This bug is not reproducible within the tt-metal repository nor there is a simple way to replicate it.

**Expected behavior**
Allocation should not get overly slow under heavy memory pressure

**Screenshots**

**Please complete the following environment information:**
- OS: Arch Linux
- Commit: aac41a3eaa44b12bb302135befbdd38b3ac7511a

**Additional context**

**Comment by abhullar-tt** [comment]
Marty actually opened a PR for this but there are some post commit failures that need to be debugged before the PR can be merged. Marty wasn't able to run all the failing tests locally so I will take a look at some of those as well, wasn't able to get to it earlier this week but I can prioritize this for early next week.

**Comment by zzigler-tt** [comment]
Hi @abhullar-tt , checking in to see the progress of this bug, TY!

**Comment by marty1885** [comment]
Closing as PR merged
