### ISSUE TITLE
ttnn.selu - LOW PCC (~0.19)

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#15548]
ttnn.selu op exhibits low PCC (~0.19). Provided unit test gives multiple configurations where we observe problem. Some of them are:

```
        [(3, 2, 192, 32)],
        [ttnn.bfloat16],
        [ttnn.TILE_LAYOUT],
        [ttnn.DRAM_MEMORY_CONFIG],
        ttnn.L1_MEMORY_CONFIG,
        6861134,
```
and
```

        [(12, 224, 224)],
        [ttnn.bfloat8_b],
        [ttnn.TILE_LAYOUT],
        [ttnn.DRAM_MEMORY_CONFIG],
        ttnn.L1_MEMORY_CONFIG,
        6411147,

```

Provided unit test shows more configurations where the problem can be observed.

 * Steps to reproduce
Checkout 
```
npetrovic/selu-sweep 
```
branch (soon to be merged into main). You can run unit test which can showcase this problem with this command:

```
pytest /home/ubuntu/tt-metal/tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_selu.py
```

**Comment by umadevimcw** [comment]
@npetrovic-tenstorrent Merged the fix into main
