### ISSUE TITLE
Expand sweeps tests for reduce ops

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-metal#15549]
Need to create sweeps that vary across inputs.
- all combinations of dims
- tensors input shapes of 1,  multiples of 32, and other even and odd numbers
- different tensor ranks
- data types
- L1 vs DRAM

Sweeps directory:
tests/sweep_framework/sweeps/reduction

Reduce ops:
sum, mean, max, min, std, var, argmax, topk, moe, prod

Steps:
1. identify what is already there
2. make a plan for what needs to be filled in
3. update the code based on the plan

**Comment by asandhupatlaTT** [comment]
Merged a PR to add new test cases for reduction

**Comment by asandhupatlaTT** [comment]
fixed at https://github.com/tenstorrent/tt-metal/pull/15804
