### ISSUE TITLE
[CCL] MeshShape in MeshDevice should be allowed to change its shape after open MeshDevide

### ISSUE THREAD

**Issue by wooseokTT** [tenstorrent/tt-metal#15601]
Currently in TT mlir runtime, once we open mesh device using the number of device ids in a uniform way, for example 1x8 mesh shape for t3k, we cannot change it to 2x4, 4x2, or 8x1. It only allows to create sub-mesh, which is really subset of 1x8 including 1x1, 1x2, 1x4, or 1x8. 

This issue tracks the ability to dynamically reshape the mesh  configuration at runtime after it is opened in any shape.

**Comment by omilyutin-tt** [comment]
What is the use case that calls for dynamic re-shaping?

**Comment by wooseokTT** [comment]
> What is the use case that calls for dynamic re-shaping?

Each graph may open mesh device in different config at runtime. So, we open mesh device in a uniform way {1, num_of_device_ids()}, and later trying to reshape the mesh shape with the particular shape that the graph wants it to be. This is the summary of our intention AFAIK.
