### ISSUE TITLE
Create a Kahan summation algorithm kernel for reduce sum

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-metal#15656]
The naive algorithm for reducing sums (used in sum, mean, and other ops) has inaccurcies.

A tree add algorithm improved the accuracy, but not sufficiently to have PCC above 0.99 for larger inputs. Therefore need to implement a new kernel algorithm that uses the Kahan summation algorithm.

See
https://en.wikipedia.org/wiki/Kahan_summation_algorithm

Difficulty will be in that we work on tiles instead of incrementally one element at a time.

**Comment by davorchap** [comment]
Kahan summation is required even if we accumulate into FP32 in DST / L1 ?

@ttmtrajkovic and @rtawfik01  what do you guys think?

**Comment by ttmtrajkovic** [comment]
@bbradelTT,
in addition to fp32 summation question, what is the distribution on your input data and what is the input precision?
Are data fully random or from real model?

I am not sure if chasing extra "9's" from pcc is the right trigger to go on an implement a more complex summation scheme.

**Comment by bbradelTT** [comment]
@ttmtrajkovic the issue filed, #13621, uses random data `torch_input_tensor = torch.rand(input_shape, dtype=torch.float32)`

I implemented a tree add algorithm that moves the PCC above 0.9 for dimensions above what's required, and with fp32_dest_acc_en I get to 0.988 for the specific dimensions asked.

If that should be sufficient, once that is merged, I can push back harder about verifying with real data.

**Comment by bbradelTT** [comment]
I recompiled and got better PCC. I think it'll be sufficient.

Thanks for the accumulate into FP32 suggestion @davorchap 

Closing.
