### ISSUE TITLE
[Cloud Support] Request to provision new VM

### ISSUE THREAD

**Issue by kevinwuTT** [tenstorrent/tt-metal#15672]
I was using `tt-metal-dev-artem-e150-1`, IP: `172.27.45.211`, but the VM is hanging whenever I try to use TTNN.
More info: https://github.com/tenstorrent/cloud/issues/3488

It is being looked into at the moment. @ayerofieiev-tt asked me to request a backup VM to use in the meantime.

**Comment by tt-rkim** [comment]
Looks like @ayerofieiev-tt made it in the meantime, since it was late yesterday

tt-metal-dev-kevinwu-wh-1

were you able to get access?

cc: @ayerofieiev-tt

**Comment by kevinwuTT** [comment]
Sorry for the late reply. Yes, I have access to this VM now and TTNN programs are working as expected.
