### ISSUE TITLE
[LLama3] Seqlen 128k for Llama3.2 1B and 3B - Reproduce on reference GPU

### ISSUE THREAD

**Issue by mtairum** [tenstorrent/tt-metal#15737]
For the 2 smallest llama3 models, 1B and 3B, we see bad output when prefill seqlen is very large, i..e > 64K.

We've debug extensively and cannot find a reason why this happens for these 2 small models, when it works fine for 8B up to 70B models.

Our best guess is that due to the small size of these models, long context lengths become very sensitive to accuracy.

## TODO
- Test the reference 1B / 3B model on CPU or GPU, using the same prompt  and look at the output. If the reference is also weak, we can close this issue.  Otherwise we'll revisit this.

**Comment by yieldthought** [comment]
![Image](https://github.com/user-attachments/assets/e1c0e810-89cb-4b9b-a0a9-af64ca48aa78)
[ref.log](https://github.com/user-attachments/files/18041787/ref.log)

1B reference model loses accuracy sharply after around 80k tokens

**Comment by yieldthought** [comment]
![Image](https://github.com/user-attachments/assets/6beea158-7328-47f3-b62f-b85428f7adbc)
3B follows a similar pattern

**Comment by yieldthought** [comment]
We're using the 3.1 reference codebase which hard-codes a scaling factor of 8, but 3.2 (as seen in hf below) actually uses 32:
![Image](https://github.com/user-attachments/assets/e03f39e6-a04a-475e-8623-9f7c27bf978a)
![Image](https://github.com/user-attachments/assets/22ec82f4-3e1f-4f3f-a210-45fb0fa6bf02)

**Comment by yieldthought** [comment]
The official Meta Llama 3 repo uses a scale_factor of 8 for all the models, including 3.2:
https://github.com/meta-llama/llama-models/blob/fc1e70e7970bdf599a924f6fd06cedb6e3819224/models/llama3/reference_impl/model.py#L47

**Comment by yieldthought** [comment]
The Meta Llama 3 huggingface repo config.json was updated from 8 to 32 a couple of weeks after release:
https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct/commit/c4219cc9e642e492fd0219283fa3c674804bb8ed
![Image](https://github.com/user-attachments/assets/76db48ce-51e9-4672-b743-eb8d63e5a947)

It appears this was a bugfix and they did not update their own official GitHub repository.

**Comment by yieldthought** [comment]
[Notified the Meta repo](https://github.com/meta-llama/llama-models/issues/241) so they can fix this on their end too.

**Comment by mtairum** [comment]
Merged in PR https://github.com/tenstorrent/tt-metal/pull/15909

Thanks @yieldthought
