### ISSUE TITLE
[TT-Train][Bug] ttnn::experimental::all_reduce crashes

### ISSUE THREAD

**Issue by dmakoviichuk-tt** [tenstorrent/tt-metal#15789]
**Describe the bug**

```
TEST_F(N300UtilsTest, TestXTensorReplicateAllReduce) {
    auto* device = &ttml::autograd::ctx().get_device();
    auto mesh_shape = device->shape();


    // optimized branch
    xt::xarray<float> test_data = xt::arange(64 * 64 * 4) / 100.F;
    xt::xarray<float> xtensor = test_data.reshape({2, 2, 64, 64});
    // non optimized branch
    //xt::xarray<float> test_data = xt::arange(32 * 32 * 1) / 100.F;
    //xt::xarray<float> xtensor = test_data.reshape({1, 1, 32, 32});

    ttml::core::XTensorToMeshVariant<float> replicate_composer = ttml::core::ReplicateXTensorToMesh<float>(mesh_shape);
    auto tensor = ttml::core::from_xtensor(xtensor, device, replicate_composer);

    auto sum_tensor = ttnn::experimental::all_reduce(tensor, ttnn::operations::reduction::ReduceType::Sum);
    ttml::core::MeshToXTensorVariant<float> identity_composer = ttml::core::VectorMeshToXTensor<float>(mesh_shape);

    auto xtensors_back = ttml::core::to_xtensor(sum_tensor, identity_composer);
    auto reduced_tensor = xtensor + xtensor;

    EXPECT_TRUE(xt::allclose(reduced_tensor, xtensors_back[0]));
    EXPECT_TRUE(xt::allclose(reduced_tensor, xtensors_back[1]));
}
```
Crash message is: `[ctest] C++ exception with description "vector" thrown in the test body.`

**To Reproduce**
go to the PR: https://github.com/tenstorrent/tt-metal/pull/15637
And run the TEST_F(N300UtilsTest, TestXTensorReplicateAllReduce).

**Expected behavior**
If the issue in our side (wrong setup or something else) all_reduce should return actionable message. Not just exception from the stl.
If the issue is inside of the all_reduce it should be fixed.
**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**
It is blocking us from the multi device support. I set P0.
cc @davorchap

**Comment by davorchap** [comment]
fyi @omilyutin-tt , sync with @SeanNijjar , is the error in MeshDevice infra or in the CCL OP?

**Comment by SeanNijjar** [comment]
Update: I've got a fix for the crash. The test now runs to completion but does **not** pass. It fails all-close but I think this is inevitable given the tiny `atol` in `allclose` and the (relatively) massive numbers we are converting fp32 -> fp16, accumulating, converting fp16 -> fp32 (visually the numbers are similar). 

However, this hasn't been confirmed by comparing against a single chip batch-sum or feeding the individual numbers through an fp16 addition and comparing to fp32. That being said I'll consider this issue solved on branch. Will open PR and get it merged asap.

**Comment by SeanNijjar** [comment]
fix has been merged. Reassigning to @dmakoviichuk-tt for fix confirmation.

**Comment by dmakoviichuk-tt** [comment]
Done!
