### ISSUE TITLE
[Bug Report] Build failure of latest `main` on GCC-14 in UMD

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#15811]
**Describe the bug**
The following error is produced when building the latest commit of tt-metal on GCC 14.

```
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/umd/device/api/umd/device/tt_core_coordinates.h:37:6: warning: elaborated-type-specifier for a scoped enum must not use the ‘class’ keyword
   37 | enum class CoordSystem : std::uint8_t {
      | ~~~~ ^~~~~
      |      -----
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/umd/device/api/umd/device/tt_core_coordinates.h:37:12: error: use of enum ‘CoordSystem’ without previous declaration
   37 | enum class CoordSystem : std::uint8_t {
      |            ^~~~~~~~~~~
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/umd/device/api/umd/device/tt_core_coordinates.h:37:24: error: expected unqualified-id before ‘:’ token
   37 | enum class CoordSystem : std::uint8_t {
      |                        ^
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/umd/device/api/umd/device/tt_core_coordinates.h:49:74: error: ‘CoordSystem’ does not name a type
   49 |     CoreCoord(const size_t x, const size_t y, const CoreType type, const CoordSystem coord_system) :
      |                                                                          ^~~~~~~~~~~
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/umd/device/api/umd/device/tt_core_coordinates.h:53:5: error: ‘CoordSystem’ does not name a type
   53 |     CoordSystem coord_system;
      |     ^~~~~~~~~~~
```

**To Reproduce**
1. Checkout 8ee1f823ccc6680fd4ba5aa9004487692da1c545
2. Configure with `cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_PROGRAMMING_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX=`pwd` -G Ninja -DCMAKE_CXX_FLAGS="" -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-g -O3"`
3. Build with Ninja
4. Observe the error

**Expected behavior**
Should build correctly

**Screenshots**

**Please complete the following environment information:**
- OS: Arch Linux
- Commit: 8ee1f823ccc6680fd4ba5aa9004487692da1c545

**Additional context**

**Comment by ayerofieiev-tt** [comment]
CC @joelsmithTT @blozano-tt

**Comment by marty1885** [comment]
i made a fix in UMD is made into a PR. If TT decided to merge it, please make a PR in tt-metal to update UMD. It's faster for TT to merge the change instead of me making a PR.

**Comment by joelsmithTT** [comment]
Reopening, still needs corresponding Metal PR.

**Comment by marty1885** [comment]
Close as the patch is now in main
