### ISSUE TITLE
1x1 MeshDevice isn't properly supported for all apis

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#15833]
The following snippet will hit an assertion in `copy_host_to_device_tensor` with a 1x1 MeshDevice if built in debug mode or a bad variant access in release, but not with MeshDevices that use more than 1 device.

```
    num_devices = device.get_num_devices() if isinstance(device, ttnn.MeshDevice) else 1
    x = torch.randn(num_devices, 1, 64, 64, dtype=torch.bfloat16)
    xt = ttnn.from_torch(
        x,
        dtype=ttnn.bfloat16,
        layout=ttnn.TILE_LAYOUT,
        device=device,
        memory_config=ttnn.L1_MEMORY_CONFIG,
        mesh_mapper=inputs_mesh_mapper,
        sub_device_ids=[ttnn.SubDeviceId(0)],
    )

    xt_host = ttnn.from_torch(
        x,
        dtype=ttnn.bfloat16,
        layout=ttnn.TILE_LAYOUT,
        mesh_mapper=inputs_mesh_mapper,
        sub_device_ids=[ttnn.SubDeviceId(1)],
    )

    ttnn.copy_host_to_device_tensor(xt_host, xt)
```

Assertion is: `RuntimeError: TT_ASSERT @ /localdev/aho/tt-metal/ttnn/cpp/ttnn/tensor/tensor.cpp:922: std::holds_alternative<OwnedStorage>(async_safe_tensor.get_storage())`

This is because the device tensor is created as a StorageType::Device tensor even though a MeshDevice was passed in because the infra automatically converts tensors with a single worker to a single device tensor.
However, the host tensor created here is created as a StorageType::MULTI_DEVICE_HOST tensor, which leads to the incorrect behaviour since the infra sees a single device tensor, so it expects the host tensor to be Borrowed or Owned, not MultiDeviceHost.

**Comment by omilyutin-tt** [comment]
Taking a look

**Comment by omilyutin-tt** [comment]
Confirmed that with https://github.com/tenstorrent/tt-metal/pull/15845 fixes the issue. We would need to look at a bunch of other APIs to generalize multi-buffer host storage. Tracking that in #15840.

**Comment by omilyutin-tt** [comment]
https://github.com/tenstorrent/tt-metal/pull/15845 was merged, tracking further work #15840.

@tt-aho / @SeanNijjar  - can you confirm the tests cases that were commented out now work?

**Comment by tt-aho** [comment]
Confirmed this seems to pass locally for me now. Will try on ci. Thanks!

**Comment by tt-aho** [comment]
Also passing on ci for my test case, closing the issue.
