### ISSUE TITLE
0 Cost View operation

### ISSUE THREAD

**Issue by jvegaTT** [tenstorrent/tt-metal#15863]
To have an extra 0-cost view operation to exist which unlike reshape will assert out if an 0 cost view is not possible

This is desired by the models teams as they can be certain that if this function works then a 0 cost view happened which is necessary for proper de-allocation.

**Comment by jvegaTT** [comment]
Feature has been pushed in

**Comment by nsorabaTT** [comment]
Hi @jvegaTT I see the cpp side has two overloads for view, but the second flavor `tensor_reshape(tensor, logical_shape, padded_shape)` does not see a binding for the python side.
I am looking to designate a tensor as a padded view, let me know if there is a way to do this.
