### ISSUE TITLE
[Bug Report] Dead link on TT-NN doc

### ISSUE THREAD

**Issue by dsklavos** [tenstorrent/tt-metal#15971]
**Describe the bug**
There's a dead link in the publicly facing TT-NN docs: https://docs.tenstorrent.com/ttnn/latest/ttnn/get_started.html

The "ResNet" link in section 2 leads to a GitHub with a 404.

**Comment by tt-rkim** [comment]
This is fixed on main.

This will be pushed on next run of docs pipeline for production docs site. Might be a while.
