### ISSUE TITLE
[Bug Report] magic_enum in headers causing hacks needed by outside consumers

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#16036]
**Describe the bug**
After updating tt-metal this morning. I find myself unable to consume the new library from GGML. The `magic_enum` library found by CMake from system requries include path `magic_enum/magic_enum.hpp` instead of `magic_enum.hpp` used by tt-metal. Leading to the following error.

For context, I'm using magic_enum provided by the system instead of CPM.

```
In file included from /home/marty/Documents/tt/tt-metal/tt_metal/common/core_coord.hpp:16,
                 from /home/marty/Documents/tt/tt-metal/tt_metal/common/metal_soc_descriptor.h:8,
                 from /home/marty/Documents/tt/tt-metal/tt_metal/llrt/tt_cluster.hpp:11,
                 from /home/marty/Documents/tt/tt-metal/tt_metal/impl/kernels/kernel_types.hpp:9,
                 from /home/marty/Documents/tt/tt-metal/tt_metal/impl/program/program.hpp:10,
                 from /home/marty/Documents/tt/tt-metal/tt_metal/host_api.hpp:11,
                 from /home/marty/Documents/llama.cpp/ggml/src/ggml-metalium/metalium-pch.hpp:14,
                 from /home/marty/Documents/llama.cpp/build/ggml/src/ggml-metalium/CMakeFiles/ggml-metalium.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/marty/Documents/tt/tt-metal/tt_metal/tt_stl/reflection.hpp:27:10: fatal error: magic_enum.hpp: No such file or directory
   27 | #include <magic_enum.hpp>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

The following hack is need to get it working in GGML. 

```cmake
find_package(magic_enum REQUIRED)
get_target_property(MAGIC_ENUM_INCLUDE_DIRS magic_enum::magic_enum INTERFACE_INCLUDE_DIRECTORIES)
foreach(dir ${MAGIC_ENUM_INCLUDE_DIRS})
    target_include_directories(ggml-metalium PRIVATE ${dir}/magic_enum)
endforeach()
```

~~A PR will be submitted shortly to address this problem.~~  I'm convinced I can't fix it alone.

**To Reproduce**
* Build tt-metal and setup environment variables
* Get commit `0c4bc7a568598629cb82c9b1184545ef65fe32d2` of marty1885/llama.cpp (metalium-support)
* Configure with `cmake .. -DCMAKE_CXX_COMPILER=g++-13 -DCMAKE_C_COMPILER=gcc-13 -DGGML_METALIUM=ON`
*  Build with `make`
* See error

**Expected behavior**
Able to consume tt-metal as library without hacks

**Screenshots**

**Please complete the following environment information:**
- OS: Arch Linux
- commit: c33b67ef25b913920228031be8b90f0d48cf1ea0

**Additional context**

**Comment by ayerofieiev-tt** [comment]
@blozano-tt ptal

**Comment by ayerofieiev-tt** [comment]
https://github.com/tenstorrent/tt-metal/blob/c33b67ef25b913920228031be8b90f0d48cf1ea0/dependencies/CMakeLists.txt#L75

Not sure if this works, but I assume we can do something like
```
CPMAddPackage(
    NAME magic_enum
    GITHUB_REPOSITORY Neargye/magic_enum
    GIT_TAG v0.9.6
)

if (magic_enum_ADDED)
    target_include_directories(magic_enum INTERFACE "${magic_enum_SOURCE_DIR}/include")
endif()
```

**Comment by marty1885** [comment]
@ayerofieiev-tt Yes that would work. But I need to avoid use of CPM else it's going to be a big pain and potentially deal breaker when eventually upstrteaming the backend.

**Comment by blozano-tt** [comment]
@marty1885 @afuller-TT @tt-rkim @ayerofieiev-tt 

Can we just change our C++ sources to do

include <magic_enum/magic_enum.hpp>

Given Marty’s issue and what I see in the opensource magic enum repo, that looks like the intended usage.

**Comment by ayerofieiev-tt** [comment]
Aligned. I just thought that for us to change from current include to the one Marty asks, we first have to change target include directories to allow it.

**Comment by marty1885** [comment]
> Can we just change our C++ sources to do

> include <magic_enum/magic_enum.hpp>

I tried but the change @ayerofieiev-tt suggested seems to also be needed. Otherwise the headers can't be found while building tt-metal itself.

**Comment by afuller-TT** [comment]
We are currently pulling in v0.9.6 of `magic_enum`.  Said version is inconsistent w.r.t. the include scoping for source builds (the way CPM does things) vs. installed builds (the way `find_package` consumes it).  https://github.com/Neargye/magic_enum/blob/v0.9.6/CMakeLists.txt#L36-L44

Fortunately v0.9.7 seems to fix this inconsistency: https://github.com/Neargye/magic_enum/blob/v0.9.7/CMakeLists.txt#L47-L50  I'll bump the version and put up a PR.
