### ISSUE TITLE
[Llama3] Demo hanging when after many decode iterations (>1k) with batch_size = 32

### ISSUE THREAD

**Issue by mtairum** [tenstorrent/tt-metal#16052]
**Describe the bug**
During profile measurement, I found that if batch_size is set to 32 in the Llama3 model family demo and the decode generation last for many iterations, it can lead to a hang.

I've seen this on 1B/3B/8B, so it's safe to assume that it affects the whole family of models.
This was previously undetected because the prompts we are using in the demo typically reach the end of the generation at around 300~500 tokens (hit a EoS token, as expected).
While debugging longer generation, I removed the EoS stop point, which led me to this issue.

**Update**

After debugging the issue seems to be with the default page attention settings: `{"page_block_size": 64, "page_max_num_blocks": 2048}`

This setting is tuned to the typical demo run, which generates up to 200 tokens.

If we increase the paged params it works.

**Comment by mtairum** [comment]
FIY @uaydonat @cglagovich @sraizada-tt

**Comment by cglagovichTT** [comment]
This could be a PGOOD hang, as debugged in this issue https://github.com/tenstorrent/tt-metal/issues/15090

**Comment by mtairum** [comment]
Hang seems to be deterministic:

- Hangs on iteration 879, for 8B on N150 with config:
```
(  # Batch-32 run (Throughput) - 32 users, small prompt
            "models/demos/llama3/demo/input_data_questions_prefill_128.json",  # input_prompts
            True,  # instruct mode
            1,  # repeat_batches
            8192,  # max_seq_len
            32,  # batch_size
            4096,  # max_generated_tokens
            True,  # paged_attention
            {"page_block_size": 32, "page_max_num_blocks": 1024},  # page_params  # TODO This will be serviced by vLLM
            {"temperature": 0, "top_p": 0.08},  # sampling_params (argmax)
        ),
```

- Hangs on 1401, for 8B on N300 with config:
```
        (  # Batch-32 run (Throughput) - 32 users, small prompt
            "models/demos/llama3/demo/input_data_questions_prefill_128.json",  # input_prompts
            True,  # instruct mode
            1,  # repeat_batches
            4096,  # max_seq_len
            32,  # batch_size
            2000,  # max_generated_tokens
            True,  # paged_attention
            {"page_block_size": 32, "page_max_num_blocks": 1024},  # page_params  # TODO This will be serviced by vLLM
            {"temperature": 0, "top_p": 0.08},  # sampling_params (argmax)
        ),
```

**Comment by mtairum** [comment]
The problem is with paged attention (updated the description).

On 8B-N300 with the following settings, it hangs on iteration 1912.
```
        (  # Batch-32 run (Throughput) - 32 users, small prompt
            "models/demos/llama3/demo/input_data_questions_prefill_128.json",  # input_prompts
            True,  # instruct mode
            1,  # repeat_batches
            4096,  # max_seq_len
            32,  # batch_size
            2000,  # max_generated_tokens
            True,  # paged_attention
            {"page_block_size": 32, "page_max_num_blocks": 2048},  # page_params  # TODO This will be serviced by vLLM
            {"temperature": 0, "top_p": 0.08},  # sampling_params (argmax)
        ),
```

But if we update the paged attention config it passes:
```
            {"page_block_size": 64, "page_max_num_blocks": 2048},  # page_params  # TODO This will be serviced by vLLM
```
