### ISSUE TITLE
[Bug Report] Reduce ops support reducing across more than 2 dims, but only if dims are not specified

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-metal#16118]
**Describe the bug**
Reduce ops support reducing across all dims, but only if dims are not specified. If you explicitly specify reduce dims and put all dims in there, it wont work for 3D+ tensors.

When no dims are specified [this](https://github.com/tenstorrent/tt-metal/blob/main/ttnn/cpp/ttnn/operations/reduction/generic/generic_reductions.cpp#L102) code path is hit.

 When dims are specified [this ](https://github.com/tenstorrent/tt-metal/blob/main/ttnn/cpp/ttnn/operations/reduction/generic/generic_reductions.cpp#L130)code path is hit and it only supports reductions across 1 or 2 dims.

**To Reproduce**
Try reducing 3D tensor across all dims, explicitely specifying `dims=[0, 1, 2]`.

**Expected behavior**
It should be checked if `dims.size() == tensor.rank()` and allowed to reduce across all dims, like it is allowed when `!dim_arg.has_value()`.

**Comment by bbradelTT** [comment]
Please test for None, [], and [0,...] (all dims)

**Comment by bbradelTT** [comment]
There will be subsequent work to handle more combinations https://github.com/tenstorrent/tt-metal/issues/16233

**Comment by bbradelTT** [comment]
I added dim=[] to https://github.com/tenstorrent/tt-metal/issues/16233 then.

**Comment by asandhupatlaTT** [comment]
fixed at https://github.com/tenstorrent/tt-metal/pull/16236
