### ISSUE TITLE
ttnn.to_layout for layout = TILE and input tensor rank > 4 hangs when the extra dimensions are not 1

### ISSUE THREAD

**Issue by sjameelTT** [tenstorrent/tt-metal#16141]
It hangs at the moment.

To reproduce run the following test on main:

```
@pytest.mark.parametrize(
    "config",
    [
        [[3, 1370, 1, 1, 1280], ttnn.ROW_MAJOR_LAYOUT],  # hang
        [[3, 50, 1, 1, 768], ttnn.ROW_MAJOR_LAYOUT],  # hang
        [[3, 50, 1, 1, 1024], ttnn.ROW_MAJOR_LAYOUT],  # hang
        [[3, 197, 1, 1, 768], ttnn.ROW_MAJOR_LAYOUT],  # hang
        [[3, 197, 1, 1, 1024], ttnn.ROW_MAJOR_LAYOUT],  # hang
    ],
)
@pytest.mark.parametrize("memory_config", [ttnn.DRAM_MEMORY_CONFIG])
def test_to_layout_hangs(config, memory_config, device):
    torch.manual_seed(2005)
    torch_input = torch.randn(config[0], dtype=torch.bfloat16)

    tt_input = ttnn.from_torch(
        torch_input, dtype=ttnn.DataType.BFLOAT16, layout=config[1], device=device, memory_config=memory_config
    )
    tt_output = ttnn.to_layout(tt_input, ttnn.TILE_LAYOUT)
    tt_output = ttnn.to_torch(tt_output)

    assert_with_pcc(torch_input, tt_output, 0.9999)
```

**Comment by kmabeeTT** [comment]
Thanks for ticket and deubg here - Here is another test... used to fatal assert (preferred) and now hangs (for us in tt-forge) after this tt-metal change from Dec17 : b80a975f1d - would be great to have fatal asserts back please.

```
import torch
import ttnn

with ttnn.manage_device(0) as device:
    x = torch.rand(2, 2, 7, 7, 384)

    x = ttnn.from_torch(x, dtype=ttnn.float32)
    x = ttnn.to_device(x, device, memory_config=ttnn.DRAM_MEMORY_CONFIG)
    x = ttnn.to_layout(x, ttnn.TILE_LAYOUT)

    res = ttnn.transpose(x, -4, -3)

    res = ttnn.to_torch(res)
    print(res)
```

**Comment by sjameelTT** [comment]
@nardoTT make sure it works for Kyle's case as well

**Comment by kmabeeTT** [comment]
Hello @nardoTT / @sjameelTT when I grab this fix to add asserts to avoid hang, I am now hitting this assert now in a previously passing tt-forge-fe llama ops test, and when I check the PR I see comment from @sjameelTT saying "Delete this" - was it resolved prematurely and should have been removed instead of modified?

```
2024-12-20T00:42:19.7316430Z E       RuntimeError: TT_FATAL @ /__w/tt-forge-fe/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/core/work_split/work_split_tilize.hpp:189: logical_shape.rank() >= 2
2024-12-20T00:42:19.7316519Z E       info:
2024-12-20T00:42:19.7316731Z E       Only tensors >=2D, tensors are supported. Shape: SimpleShape([32])
```
![Image](https://github.com/user-attachments/assets/a5569fc3-9053-4f8c-b0c9-bb853154d6e1)

**Comment by sjameelTT** [comment]
> Hello [@nardoTT](https://github.com/nardoTT) / [@sjameelTT](https://github.com/sjameelTT) when I grab this fix to add asserts to avoid hang, I am now hitting this assert now in a previously passing tt-forge-fe llama ops test, and when I check the PR I see comment from [@sjameelTT](https://github.com/sjameelTT) saying "Delete this" - was it resolved prematurely and should have been removed instead of modified?
> 
> ```
> 2024-12-20T00:42:19.7316430Z E       RuntimeError: TT_FATAL @ /__w/tt-forge-fe/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/core/work_split/work_split_tilize.hpp:189: logical_shape.rank() >= 2
> 2024-12-20T00:42:19.7316519Z E       info:
> 2024-12-20T00:42:19.7316731Z E       Only tensors >=2D, tensors are supported. Shape: SimpleShape([32])
> ```
> 
> ![Image](https://github.com/user-attachments/assets/a5569fc3-9053-4f8c-b0c9-bb853154d6e1)

1D tiles are not supported.

closing this issue as past the fatal, it's a normal feature request tracked by this: https://github.com/tenstorrent/tt-metal/issues/16188
