### ISSUE TITLE
ttnn.conv2d fails with statically allocated circular buffer issue

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#16267]
**Describe the bug**
ttnn.conv2d is failing with `Statically allocated circular buffers` in the unit test of SDXL_Turbo model for the resolution 1024x1024 when memory config is set to `ttnn.L1_MEMORY_CONFIG`
**To Reproduce**
1. Checkout [keerthanar/sdxl_turbo_unit_test](https://github.com/tenstorrent/tt-metal/tree/keerthanar/sdxl_turbo_unit_test)
2. Run the following command,
`pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_conv_sdxl_turbo_1024x1024_l1_failing_case`
3. The test will fail with the following error will occur,
`RuntimeError: TT_THROW @ ../tt_metal/impl/program/program.cpp:839: tt::exception
E       info:
E       Statically allocated circular buffers in program 23 clash with L1 buffers on core range [(x=0,y=0) - (x=7,y=6)]. L1 buffer allocated at 265216 and static circular buffer region ends at 356448`

**Please complete the following environment information:**
WH (n150)

**Comment by pavlejosipovic** [comment]
@keerthana-r-mcw One way to work around this is to set deallocate_activation and reallocate_halo_output to True
I've tested that out and pushed code here.
https://github.com/tenstorrent/tt-metal/tree/pjosipovic/sdxi_turbo_unit_test

**Comment by keerthana-r-mcw** [comment]
@pavlejosipovic test got passed. Thanks
