### ISSUE TITLE
FW release package to prevent FETs burn on N300 / N150

### ISSUE THREAD

**Issue by ttmtrajkovic** [tenstorrent/tt-metal#16287]
Paste release details on FW release 80.13.2.103.

Results for testing are here:
N300: https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?pli=1&gid=2094403948#gid=2094403948
N150: https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?pli=1&gid=2145444062#gid=2145444062

**Comment by tcolacoTT** [comment]
80.13.2.103 Debug package with latest VR setting.
Package is uploaded to ticket https://tenstorrent.atlassian.net/browse/SYS-887

Use tt-flash update using the firmware bundle

**Comment by ttmtrajkovic** [comment]
Thanks @tcolacoTT.

FYI @ihamer-tt, @pavlepopovic, @rdjogoTT
