### ISSUE TITLE
infra: implement linters for pre-commit

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#188]
We want linters that 

- Don't disturb our workflow too much
- Can run fixes automagically on changes/commits (probably through `pre-commit` infra)
- Can be installed as part of `python_env/dev` or pre-installed with ansible provision scripts

For the kinds of linters we may want now,

- `black` for Python
- `isort` for Python

For the kinds of linters that we may want but need to do a little more investigating,

- `clang-tidy3.9`
  - Seems like a good option with auto `-fix` command, but I read reports that it may be destructive/breaking to code. I may also be totally lying here and there is no magic `-fix` option, so if you know more than me about the C++ linting ecosystem (and you probably do), please comment
- `flake8`
  - May be destructive to workflow as there is no easy "autofix" option

For Python specifically, I believe we should hold off on static type checkers. They're a bit too much overhead right now, and it may be difficult to setup. Ex. Not all libraries have type stubs that are useful/correct

**Comment by blozano-tt** [comment]
@tt-rkim I support this cause.

Is this really still an open issue?

I think we have pre-commit files right?

**Comment by tt-rkim** [comment]
I think we can close to reduce the number of open issues, and we can open further issues to either expand the  file scope of current linters or add more.

BTW, @esmalTT graciously has a PR open for C++ linting: https://github.com/tenstorrent/tt-metal/pull/5412/files

we just have too much stuff on our plate to properly merge it + it's not super high priority. I'm sure the C++ people would love it though.
