### ISSUE TITLE
Bcast scalar improvement by constructing scalar tile in kernel

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#1945]
Removes need from users to preconstruct scalar tile. We'd just write 1 single value into a CB.

Would also help some other ops like the binop_tied_to_unary and other composite ops, so that they aren't creating/sending tile to device each run.

**Comment by davorchap** [comment]
@tt-aho is still outstanding ?

**Comment by tt-aho** [comment]
Support added in 7c65c017a2d42ebfa805f767ed4ba7c9ac9a28a2
