### ISSUE TITLE
Not a fan of having physical coordinates for an API that is in tt metal. Tt metal should ideally only take as input virtual coordinates and then transform them to physical internally.

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#1980]
Not a fan of having physical coordinates for an API that is in tt metal. Tt metal should ideally only take as input virtual coordinates and then transform them to physical internally.

_Originally posted by @DrJessop in https://github.com/tenstorrent-metal/tt-metal/pull/1859#discussion_r1281172956_

**Comment by pgkeller** [comment]
I think this is done-ish, or at least the base part is (using virtual coordinates).  @tt-asaigal

**Comment by tt-asaigal** [comment]
Virtual + Logical -> Physical is not exposed to the user. We have APIs to derive virtual from logical and vice versa. These are mostly required by TT Metal users to create programs and set RTAs/CTAs.
I think this should be done.
