### ISSUE TITLE
Remainder binary op

### ISSUE THREAD

**Issue by umadevimcw** [tenstorrent/tt-metal#2153]
Op Ref: 
ElemwiseBinary/ELEMWISE_BINARY_REMAINDER https://pytorch.org/docs/stable/generated/torch.remainder.html#torch.remainder
Arch: GS, WHB0
Kind: Math
Type: BF16

**Comment by davorchap** [comment]
> On hold due to dependencies on floor operation.

Is this still outstanding ?

**Comment by umadevimcw** [comment]
Its on hold due to floor op dependency

**Comment by umadevimcw** [comment]
Implemented in composite structure and merged to main
