### ISSUE TITLE
Update the tile registers and math->pack sync compute APIs in the docs

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#250]
Explain in docs how new `tile_regs_` `aquire/commit/wait/release` work.

* The new API term for DST is *tile registers*, this is because they aren't used just a "DST - destination", for SFPU they are used as SRC/DST, and there will be other OPs were we directly compute on DST, such `add_tile_to_dst`
* Tile regs are used a double buffer synchronization between math and pack
* Acquire gives you space of **half of tile regs**: 8 tiles of fp16 in GS/WH, 4 tiles of FP32 in WH-only 
* Do math on it, and then commit to signal pack, which does work and releases
* Provide a couple of simple examples

Refer to case: https://github.com/tenstorrent-metal/tt-metal/issues/2854

**Comment by davorchap** [comment]
upon review it's not there? perhaps got dropped from the docs

**Comment by mywoodstock** [comment]
> upon review it's not there? perhaps got dropped from the docs

Hmm, strange. Now sure why these got dropped. The docs are there in the code still.

**Comment by davorchap** [comment]
Also, please split out tile regs sync into their on section , currently in Compute APIs global list (https://tenstorrent-metal.github.io/tt-metal/latest/tt_metal/apis/kernel_apis/compute/compute.html)

**Comment by davorchap** [comment]
> Also, please split out tile regs sync into their on section , currently in Compute APIs global list (https://tenstorrent-metal.github.io/tt-metal/latest/tt_metal/apis/kernel_apis/compute/compute.html)

old APIs (acquire/release_dst) should also go to this section , we should say these are the old APIs , will be deprecated
