### ISSUE TITLE
Remove the ability for user to manage Device handle directly

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#2593]
This will involve replacing `CreateDevice`, `InitiailizeDevice`, and `CloseDevice`, with `GetDevice`. Upon first invocation of `GetDevice`, Device objects are created, and can only be destroyed when process dies

**Comment by aliuTT** [comment]
Something related to this that will become more apparent with Galaxy workloads: `create-ethernet-map` takes a long time to call. The script is a barrier between multichip machines booting up + ethernet training and SW workloads. It is now called everytime `tt_cluster` is initialized, but as long as ethernet links do not drop during SW testing, we can create the yaml file once after boot up and query a static file somewhere to skip this script for separate SW workloads.

**Comment by davorchap** [comment]
@TT-billteng can we close?
