### ISSUE TITLE
Extend Split op to support more than 2 partitions

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent/tt-metal#2634]
The current state of the TT Metal split operation allows for the partitioning of tensors into two equal parts, (partition = 2).

The request is to extend this capability to enable the TT Metal split operation to divide tensors into more than two parts (partition > 2). 

We have a use-case where the tensor needs to be split into 3 parts. But, `tt_lib.tensor.split_last_dim_two_chunks_tiled` can only split the tensor into 2 parts.

**Comment by davorchap** [comment]
@tarafdarTT and @yan-zaretskiy please review for the TM roadmap
