### ISSUE TITLE
Add a model status page, on a per model basis on the Sphinx docs

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#2740]
list of models working, description of their "working" stage (end-to-end demo or pcc-only, etc..)

instructions for how run the model / test.

**Comment by jvasilje** [comment]
@tt-rkim why is this on the metal board???

**Comment by tt-rkim** [comment]
@jvasilje Was a mistake - probably wanted to pick global dashboard and picked the wrong one because they both start with "Metal".
