### ISSUE TITLE
Separate python env from build folder

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#2873]
This is creating issues for using artifacts in CI pipeline as the 2GB python env and really slows down the artifact creation process ( zip/tar -> upload -> download -> unzip/untar) and this is the primary blocker for solving #2128.

We can make python env creation a separate, incremental step in CI as @tt-rkim has mentioned that the python env doesn't change often so CI should breeze through this step most of the time.

**Comment by tt-rkim** [comment]
@TT-billteng Would you agree that this is probably something that'll make separating artifacts from running silicon tests much easier? I think since the runners are locally hosted, pip will cache most python deps.

we could probably then just tell the runner to build the python environment before running tests, but that should be quite quick as most things are cached, except of course our Python package.

**Comment by TT-billteng** [comment]
> @TT-billteng Would you agree that this is probably something that'll make separating artifacts from running silicon tests much easier? I think since the runners are locally hosted, pip will cache most python deps.
> 
> we could probably then just tell the runner to build the python environment before running tests, but that should be quite quick as most things are cached, except of course our Python package.

Yes definitely, I'm thinking we can drop in build artifact which contains the lib files into `build` of a CI silicon runner, and then trigger an incremental `pip install`, which is cached locally.

**Comment by tt-rkim** [comment]
The only headache would be making sure

- we capture all python_env related make commands, including preserving ones hidden behind `TT_METAL_ENV_IS_DEV`
- One of the following:
  - ensure the separation is abstracted away from devs / it is clearly communication
  - this separation is clearly documented with commands to generate the dev python_env
- For the base environment (without extra metal crap that we install it), we can use some caching system. We already have this for free as it's a self-hosted runner, or we have to use `actions/setup-python`.

I've written some notes about potential things to watch for when working on build artifacts eventually in this comment: https://github.com/tenstorrent-metal/tt-metal/issues/5873#issuecomment-1973365067

**Comment by TT-billteng** [comment]
this is now done in the new CMake flow, thanks @vtangTT !
