### ISSUE TITLE
ttl.tensor.recip operation breaks with low PCC [Grayskull]

### ISSUE THREAD

**Issue by JelenaTosicJtosic** [tenstorrent/tt-metal#2898]
**Describe the bug**
**ttl.tensor.recip** operation breaks with low PCC error in some test cases. 

**To Reproduce**
1. Checkout `main` branch
2. Run unit test `test_eltwise_recip.py` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_recip.py`

**Expected behavior**
There are four test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_recip.py` and they all are expected to fail with low PCC error. 
For example, one of the tests is expected to fail with this result: 
`Max ATOL Delta: inf, Max RTOL Delta: inf, PCC: 1.0926756631169207e-06`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttl.tensor.recip and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_eltwise_recip_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `eltwise_recip_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Find on ARA**
1. Navigate to `http://172.27.44.162:8080/op_test_sweeps`
2. Select `pytorch_eltwise_recip_test` for the test sweep name and date interval to consists of 2023-09-21 09:22

**Comment by ruthreshx** [comment]
Hi @JelenaTosicJtosic,
Below, PR will resolve the Recip Issue.
PR Link: https://github.com/tenstorrent-metal/tt-metal/pull/4485

**Comment by boris-drazic** [comment]
Hi @banekg,
can you check if recip issue is resolved?

**Comment by banekg** [comment]
Hi @boris-drazic ,

I checked ruthresh/fix_rdiv branch (rebased with main) and `recip` operation still fails with low PCC value, on both, GS and WH.

**Comment by VirdhatchaniKN** [comment]
Hi @JelenaTosicJtosic , @jliangTT , @nemanjagrujic , @banekg 
Fix provided in branch [Aswinmcw/fix_recip](https://github.com/tenstorrent-metal/tt-metal/pull/7000) works .
<img width="1305" alt="Screenshot 2024-04-04 at 5 00 01 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/138196495/7f52c780-eae2-458a-9b61-beb8fac529d1">

**Comment by nemanjagrujic** [comment]
@VirdhatchaniKN  Tested, tests pass now (both unit and sweep). I will close the ticket once pull request is merged.

**Comment by npetrovic-tenstorrent** [comment]
> The unit test does not pass on latest main. Please check @VirdhatchaniKN. However, the sweeps appear to be passing without any problem.



> The unit test does not pass on latest main. Please check @VirdhatchaniKN. However, the sweeps appear to be passing without any problem.

Just to emphasise: It fails on Grayskull.

**Comment by VirdhatchaniKN** [comment]
Hi @npetrovic-tenstorrent 
We ran the test on GS and the test cases passed.

- Branch : [Aswinmcw/fix_recip](https://github.com/tenstorrent-metal/tt-metal/pull/7000)
- Test File : `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_recip.py`
<img width="1159" alt="Screenshot 2024-05-21 at 12 07 19 PM" src="https://github.com/tenstorrent/tt-metal/assets/138196495/17034bae-1ffe-47d0-aaa1-b880fec098ff">

- Test File : `tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_eltwise_unary.py`
<img width="1284" alt="Screenshot 2024-05-21 at 12 08 49 PM" src="https://github.com/tenstorrent/tt-metal/assets/138196495/46ad1f6d-4785-49c9-a39a-f717fd07b8d4">

We also ran the same on WH_B0, and the test cases passed.
Can you please share the test file that fails?

**Comment by npetrovic-tenstorrent** [comment]
> Hi @npetrovic-tenstorrent We ran the test on GS and the test cases passed.
> 
> * Branch : [Aswinmcw/fix_recip](https://github.com/tenstorrent-metal/tt-metal/pull/7000)
> * Test File : `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_recip.py`
> 
> <img alt="Screenshot 2024-05-21 at 12 07 19 PM" width="1159" src="https://private-user-images.githubusercontent.com/138196495/332310936-17034bae-1ffe-47d0-aaa1-b880fec098ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM4MTcsIm5iZiI6MTcxNjM2MzUxNywicGF0aCI6Ii8xMzgxOTY0OTUvMzMyMzEwOTM2LTE3MDM0YmFlLTFmZmUtNDdkMC1hYWExLWI4ODBmZWMwOThmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNzM4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDg3MDJhMTg4MzE2YzkxZmZkMzcxM2Y5NTQ5M2M4MzA0ZTNmYjU4OGY3MTllODgyYTk0NDk1MzAzMDRjOTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUX5WqTidBd2di4x6xx0kuLXLsyTtYg_F7s7aN4_FuA">
> * Test File : `tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_eltwise_unary.py`
> 
> <img alt="Screenshot 2024-05-21 at 12 08 49 PM" width="1284" src="https://private-user-images.githubusercontent.com/138196495/332311001-46ad1f6d-4785-49c9-a39a-f717fd07b8d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM4MTcsIm5iZiI6MTcxNjM2MzUxNywicGF0aCI6Ii8xMzgxOTY0OTUvMzMyMzExMDAxLTQ2YWQxZjZkLTQ3ODUtNDljOS1hMzlhLWY3MTdmZDA3YjhkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNzM4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmNkZTM2YTNhZTE2MDk4ZDI4ZWI0ZTYxMDQ2YzM5ZTlkMjk3ZGYxODk1YzBkNGU3ODMwMjJkMmY5MjgxZGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qkpJC5tvZjsdcDhtoPwCZFRdT8aPuVAaY5850MJ_ypk">
> We also ran the same on WH_B0, and the test cases passed. Can you please share the test file that fails?

I have carefully followed your instructions and got it passing as well. Issue can be closed and fix merged.
![Uploading 6FFA319E-E2AD-44F9-846B-A1C41F548A25.jpeg…]()

**Comment by npetrovic-tenstorrent** [comment]
Seems to be working now.

**Comment by npetrovic-tenstorrent** [comment]
The tests are passing
![6FFA319E-E2AD-44F9-846B-A1C41F548A25](https://github.com/tenstorrent/tt-metal/assets/109360062/95f4876a-e11d-4781-b5a0-7d4a43d51552)

**Comment by Aswinmcw** [comment]
> Seems to be working now.

Thanks for checking @npetrovic-tenstorrent , but the fix cannot be merged for now due to perf issues 
[Conversation Link](https://github.com/tenstorrent/tt-metal/pull/7000#issuecomment-2058653394)
