### ISSUE TITLE
Extend Reshape op to support Row_major Layout

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent/tt-metal#2925]
The current state of the TT Metal reshape operation allows for the reshaping of tensors only when the tensor is in the TILE Layout.

The request is to extend this capability to enable the TT Metal reshape operation to function even when the tensor is in a Row major layout.

We have a use case where the tensor needs to be reshaped. But,` tt_lib.tensor.reshape` can function only when the tensor is in the TILE layout.

**Comment by mtairum** [comment]
Closing this issue as stale since many updates were made since then for reshape op.
Also both Mistral and Mixtral bringup has been integrated on main without this issue.
