### ISSUE TITLE
Verify that static constructors work on the device

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent/tt-metal#312]
Would be convenient to be able to do arbitrary init for any statically constructed object once at kernel load, without having to edit 3 different firmware loaders. Also for external kernel writers this will be very convenient and most likely will be expected to work.

Last time i tried it, it didn't work. Perhaps it's a similar issue to constants on BRISC (some linker map problem possibly).

**Comment by pgkeller** [comment]
closing (we don't plan to support constructors in the near future, static variables should all be initialized properly)
