### ISSUE TITLE
conv op clean-up

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#3165]
remove unused compute / reader / writer kernels in conv ops:
- conv_op.cpp
- optimized_conv_op.cpp

**Comment by nsmithtt** [comment]
@tapspatel, does this overlap with some of the cleanup work you've done?

**Comment by tapspatel** [comment]
yes, Ive made all these changes, issue: https://github.com/tenstorrent-metal/tt-metal/issues/6664. Ill close that one and keep this for tracking as its the same issue

**Comment by tapspatel** [comment]
Conv op cleanup being discussed and items being created in the background. Will open a new issue tracking the kernel code clean up. Closing this one.
