### ISSUE TITLE
tt_lib.tensor.rpow fails with low PCC [Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#3283]
`ttl.tensor.rpow` operation breaks with low PCC error in some test cases 

**To Reproduce**

Checkout `main` branch
Run unit test `test_eltwise_rpow.py` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_eltwise_rpow.py `
Expected behavior

There are test cases presented in the unit `test_eltwise_rpow.py` and most of them are expected to fail with low PCC error.

For example, one of the tests is expected to fail with this result:
 Max ATOL Delta: nan, Max RTOL Delta: nan, PCC: 0.5864728012702187, PCC check failed

**Getting Additional info for the operation under test and its behavior**

To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttl.tensor.ne and check the results. To do this you should:

Follow the Getting Started page to setup the repo, environment variables and python-env
Activate `source build/python_env/bin/activate`
Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_eltwise_rpow_test -o ./result-sweeps`
After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find eltwise_rpow_sweep.csv which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique data_seed field.

**Comment by davorchap** [comment]
@npetrovic-tenstorrent is this still outstanding?

**Comment by bharane-abb** [comment]
> @npetrovic-tenstorrent is this still outstanding?

We have discussed the issue in the following GS ticket
https://github.com/tenstorrent/tt-metal/issues/3309

**Comment by npetrovic-tenstorrent** [comment]
The particular unit test seems still to fail. 
![B8A5C9ED-3D6B-41AA-932B-F22C2F8B2871](https://github.com/tenstorrent/tt-metal/assets/109360062/e69d65d7-8d30-4da9-947c-1b604dbac1e2)
However, based in the discussion @bharane-ab  mentions, it seems that this issue might be closed as not relevant anymore after reducing its range from [-100, 100 ] to [-10, 10] as in case of similar ops.

**Comment by npetrovic-tenstorrent** [comment]
> > @npetrovic-tenstorrent is this still outstanding?
> 
> We have discussed the issue in the following GS ticket #3309

Should documentation mention the value limitation as well ?
