### ISSUE TITLE
tt_lib.tensor.rpow fails with low PCC [Grayskull] [Doc]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#3309]
**Describe the bug**

**ttl.tensor.rpow** operation breaks with low PCC error in some test cases 

**To Reproduce**

Checkout `main` branch
Run unit test **test_eltwise_rpow.py** using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_rpow.py` 
Expected behavior

There are test cases presented in the unit test `test_eltwise_rpow.py` and most of them are expected to fail with low PCC error.

For example, one of the tests is expected to fail with this result:
`Max ATOL Delta: nan, Max RTOL Delta: nan, PCC: 0.9267387350542515, PCC check failed`

**Getting Additional info for the operation under test and its behavior**

To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttl.tensor.ne and check the results. To do this you should:

Follow the Getting Started page to setup the repo, environment variables and python-env
Activate source `build/python_env/bin/activate`
Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_eltwise_rpow_test.yaml -o ./result-sweeps`
After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find **eltwise_rpow_sweep.csv** which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique data_seed field.

**Comment by bharane-ab** [comment]
As Rpow is computed using multiple functions like logarithm, broadcasting, and exponentiation so  it is supported for various range based on the factor(base) value.



![Image](https://github.com/tenstorrent-metal/tt-metal/assets/138196316/92150fc9-ea62-45d8-ae17-b81c7b67787c)

**Comment by npetrovic-tenstorrent** [comment]
It still seems to exhibit low PCC in range [-100, 100]

**Comment by npetrovic-tenstorrent** [comment]
> Hi @jliangTT @eyonland @tt-aho @npetrovic-tenstorrent
> 
> As mentioned [here](https://github.com/tenstorrent-metal/tt-metal/issues/3309#issuecomment-1869941863), Rpow is computed using the `log`, `mul` and `exp` operations. To support a range from -100 to 85, the base value should be 2. So for different base value the input range will be different.
> 
> Kindly give your suggestion on this.

These limitations should be clearly stated in documentation.

**Comment by npetrovic-tenstorrent** [comment]
> As Rpow is computed using multiple functions like logarithm, broadcasting, and exponentiation so it is supported for various range based on the factor(base) value.
> 
> ![Image](https://private-user-images.githubusercontent.com/138196316/292958492-92150fc9-ea62-45d8-ae17-b81c7b67787c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTgwMjQsIm5iZiI6MTcxNjI5NzcyNCwicGF0aCI6Ii8xMzgxOTYzMTYvMjkyOTU4NDkyLTkyMTUwZmM5LWVhNjItNDVkOC1hZTE3LWI4MWM3YjY3Nzg3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxMzIyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDgyMTBjODQzNjdiNjIxNmQxNDhlZmFlMzJlNDYxNTNmOTdlYmI3NjA0YTg0OTI0MjAzMjcxZTBmMGFhYmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nFRLrkd8NB8gahTDGt_Bh1eqefsnrhBcNLKvSu3AgfQ)

Some form of these info should be added to the documentation, so users would be aware of its usage limitations.

**Comment by KalaivaniMCW** [comment]
Will revisit this task and update it after migration task

**Comment by ruthreshx** [comment]
Hi @npetrovic-tenstorrent ,
Surewe we will add the documentation along with the usage limitations.

**Comment by mcw-anasuya** [comment]
Rpow supports an input range upto 25.
<img width="1454" alt="Screenshot 2024-10-25 at 16 43 22" src="https://github.com/user-attachments/assets/7ca9de3e-2124-43ec-9c89-e0b8e5129eed">

**Comment by eyonland** [comment]
Please confirm this issue on WH and then update the documentation as mentioned above.

**Comment by mcw-anasuya** [comment]
Checked in WH, the input range supports upto 28. 
<img width="1446" alt="Screenshot 2024-10-30 at 20 45 51" src="https://github.com/user-attachments/assets/bcb0be03-75b5-4fd5-bd82-466b97fa7324">

**Comment by mcw-anasuya** [comment]
The PCC is 0.99 for input range up to 28, which is good for WH. So I'm closing this issue.
