### ISSUE TITLE
Break kernel build dependency on device/cleanup generated header files

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#3381]
Presently, the noc to bank and watcher header files are generated for every kernel for every device.  The noc to bank headers are now (recently) only included in the firmware and the watcher files are debug only so hardly justify requiring kernel recompilation for every device.  Instead, the watcher data could be generated by brisc.cc when the watcher is enabled and used by all the processors.  This would slow down the watcher, but better that than a recompile.  In addition, these files are over-generated (every kernel rather than per device).   Proposal:

1) Create a built/<device>/include/firmware directory, add it to the firmware include path in the build
2) Generate the noc/bank header into that directory (rename that file to bank_to_noc_gen.h ?).  Only generate the firmware side of the ifdef
3) Split the kernel portion of the ifdef in that file out into its own file under src/ckernels - that piece is static and doesn't need to be generated, bank_to_noc.h
4) Instead of generating a header for the watcher, create "well known addresses" w/ that data (mailboxes in dev_msgs.h).  Note that presently DISPATCH_CORE_X/Y are defined in that file, that will have to move, perhaps pass it into brisc.cc as -D defines in the build
5) The host will initialize those mailboxes w/ direct writes at device init time (directly from the watcher code, perhaps)
6) Replace the macros in the watcher header that check the validity of noc info to functions that read the valid ranges/values from the mailboxes.  A hard piece of this is if any of the data is dynamically sized - the mailbox will need to be big enough to handle full size
7) Optionally, the build needs to be cleaned up in general, split all the code to generate files out to its own file, generate.cpp in the build directory

**Comment by jliangTT** [comment]
With galaxy, this will reduce the number of times of kerne needing to be built from 32 times to 1 time.

**Comment by pgkeller** [comment]
fyi @tt-asaigal

**Comment by pgkeller** [comment]
Done, see #12844
