### ISSUE TITLE
Extend watcher w/ stack high water mark

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#3469]
On the device side, in each of the 5 firmware fns, when watcher is enabled:
 - dirty stack emmory w/ a pattern (eg, BABABABA) say 3/4 of the way through the stack depth before a kernel is run
 - after the kernel is run find the point at which the dirty pattern has been overwritten
 - report this back to the watcher by writing the result to a debug mailbox (see dev_msgs.h)

On the host side:
 - update the watcher to read the stack high water mark
 - if it has been updated, dump it out w/ the per-core report
 - maybe this should be behind an env var, TT_METAL_WATCHER_STACK.  Not sure

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent/tt-metal/pull/11105 implements this
