### ISSUE TITLE
Add CI machine for E75 coverage

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#3484]
Related to #3007 

After changes from @abhullar-tt , we want to add E75 coverage.

Unfortunately, this likely means no model coverage at all because we have no Weka connection on the corporate network. This is the only location of our single E75 card for the team. Models currently require TT internal cloud network connection to Weka.

cc: @chekangliang

**Comment by davorchap** [comment]
@tt-rkim do we recieve an E75 in the cloud?

**Comment by tt-rkim** [comment]
@davorchap Yes, it's on the to do list to integrate into CI.

**Comment by TT-billteng** [comment]
are we still doing this? Haven't heard anything about E75 recently

**Comment by jliangTT** [comment]
let me take an action on this but moving it to P3 for now. I want to check in a few things.

**Comment by TT-billteng** [comment]
Don't think we're doing this anymore
