### ISSUE TITLE
ttl.tensor.recip operation breaks with low PCC [Wormhole] [Doc]

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#3561]
**ttl.tensor.recip** operation breaks with low PCC error in some test cases. 

**To Reproduce**
1. Checkout `main` branch
2. Run unit test `test_eltwise_recip.py` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_recip.py`
[Same path as for grayskull test]

**Expected behavior**
There are four test cases presented in the unit test `test_eltwise_recip.py` and they all are expected to fail with low PCC error. 
For example, one of the tests is expected to fail with this result: 
`Max ATOL Delta: inf, Max RTOL Delta: inf, PCC: 1.0926756631169207e-06`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttl.tensor.recip and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_eltwise_recip_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `eltwise_recip_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by VirdhatchaniKN** [comment]
Hi @nemanjagrujic , @jliangTT 
Fix provided in branch [Aswinmcw/fix_recip](https://github.com/tenstorrent-metal/tt-metal/pull/7000) works .

<img width="1304" alt="Screenshot 2024-04-04 at 5 23 14 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/138196495/fe73e6b3-5b1c-462a-93fc-188a1e41cd38">

**Comment by nemanjagrujic** [comment]
@VirdhatchaniKN  Tested, tests pass now (both unit and sweep). I will close the ticket once pull request is merged.

**Comment by ruthreshx** [comment]
From the latest main, I'm facing the **valid_page_size** issue, currently debugging the same

**Comment by ruthreshx** [comment]
Hi @eyonland , @nemanjagrujic ,
The failure is related to range issues, that will be udpated during the doc task.
Thank you

**Comment by mcw-anasuya** [comment]
All four test cases fail with the expected message.
<img width="1642" alt="Screenshot 2024-10-25 at 16 11 31" src="https://github.com/user-attachments/assets/f79f3208-abda-4248-9bf2-453e474c0a88">
Hence closing

**Comment by nemanjagrujic** [comment]
@mcw-anasuya Just to double check. It is expected that 3rd case fails with:

```
PCC check failed
```

?
