### ISSUE TITLE
Complex Tensors Bugs

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent/tt-metal#3666]
GS

- [x] #3617
- [x] #3607
- [x] #3557
- [x] #3554
- [x] #3553
- [x] #3559
- [x] #3560
- [x] #3562

WH

- [x] #3614
- [x] #3613
- [x] #3616
- [x] #3611
- [x] #3610
- [x] #3609
- [x] #3608

tensor conversion 
- [] #3682

**Comment by umadevimcw** [comment]
@boris-drazic @muthutt For WHB0 Logical core bound error is not yet resolved. Is there any way to pass the x,y position of core for kernel? Except this rest of the low PCC issue are done

**Comment by davorchap** [comment]
@umadevimcw can this be closed, anything outstanding ?

**Comment by umadevimcw** [comment]
Can be closed.
