### ISSUE TITLE
Share program ID with erisc/brisc main loop through launch message

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent/tt-metal#3764]
In order to know the order of kernels that have been profiled, launch message can be loaded with unique ID. This ID can be stored as part of device profiling data and be cross referenced with host data during postprocessing.

**Comment by mo-tenstorrent** [comment]
Due to various levels of caching at the program and dispatch levels, cores do not see the unique id that was set by the host at runtime.

Program ID is not unique when programming caching is on and on top of that dispatcher will not push non-unique programs to device DRAM, i.e. program ID is not a good candidate for this ID. 

Another mechanism unrelated to the caching mechanism is needed to relay this ID to cores at every OP run.

**Comment by davorchap** [comment]
@mo-tenstorrent this is done?

**Comment by mo-tenstorrent** [comment]
No
