### ISSUE TITLE
Move op sweeps to pytest

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#382]
# To dos

- [x] Create pytest wrapper test file which calls sweeps
- [ ] #397
- [ ] Uplift shape/case generation code to create dynamic `pytest.mark.parametrize` cases using `pytest_generate_tests` fixture
- [x] Reset seeds for torch, numpy, and random in conftest for reproducibility

- [x] Add script to CI ops/dnn commits
- [ ] Update current ops sweeps with current list

- [ ] Document procedure to add ops and enforce usage

**Comment by TT-billteng** [comment]
Closing in favor of TTNN's new OP sweep infra which isn't pytest based
