### ISSUE TITLE
Investigate CONFIG=release for release pipelines

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#3852]
@pgkeller changed the build to use `lto`. This will get rid of certain asserts, but we should do so for release builds.

**Comment by tt-rkim** [comment]
We now regress on release, but tests don't work yet.

Lowering to P2

**Comment by TT-billteng** [comment]
@vtangTT give this a shot when you are done with CMake

**Comment by vtangTT** [comment]
this is fixed and run as default on CI now
