### ISSUE TITLE
Add Src and Dst ethernet routers

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#3951]
Assume no user specified eth data movement kernels specified

**Comment by aliuTT** [comment]
Pasting from a chat: this is the overall structure of the app FW:
```
while (1) {
- tunnel FD
- if user wants to run kernel
  - run_kernel()
  - in any while loop in kernel
     - tunnel FD
  -done_kernel()
- tunnel FD
}
```

**Comment by aliuTT** [comment]
Configuring devices to only do fd tunneling between chips assoc with same mmio device (cluster concept)

**Comment by aliuTT** [comment]
Going to close this issue, the rest of eth tunneling is tracked elsewhere
