### ISSUE TITLE
Unable to broadcast with add

### ISSUE THREAD

**Issue by arakhmati** [tenstorrent/tt-metal#4005]
Only W and H dimensions can be broadcasted during an add operation.  We need to support the other dimensions as well.

```
@pytest.mark.parametrize("h", [32])
@pytest.mark.parametrize("w", [2 * 32])
@pytest.mark.parametrize("scalar", [0.42])
def test_add_broadcasts(device, h, w, scalar):
    torch_a = torch.rand((1, 1, h, w), dtype=torch.bfloat16)
    torch_b = torch.rand((5, 64, h, w), dtype=torch.bfloat16)
    torch_output = torch.add(torch_a, torch_b)

    a = ttnn.from_torch(torch_a)
    a = ttnn.to_device(a, device)
    b = ttnn.from_torch(torch_b)
    b = ttnn.to_device(b, device)
    tt_output = ttnn.add(a, b)
    tt_output = ttnn.to_layout(tt_output, ttnn.ROW_MAJOR_LAYOUT)
    tt_output = ttnn.from_device(tt_output)
    tt_output = ttnn.to_torch(tt_output)

    assert_with_pcc(torch_output, tt_output, 0.9999)

```

**Comment by eyonland** [comment]
This issue will be partially solved with ttnn.repeat given that this op supports interleaved tensors.   However because ttnn.repeat does not work for sharded tensors we cannot close this issue.

**Comment by ayerofieiev-tt** [comment]
see the thread mentioned above.

Need to enable
```
ttnn.eq(
    ttnn.Tensor(<buffer is not allocated>, shape=Shape([1, 1, 2048, 2048]), dtype=DataType::BFLOAT16, layout=Layout::TILE), 
    ttnn.Tensor(<buffer is not allocated>, shape=Shape([1, 1, 1[32], 1[32]]), dtype=DataType::BFLOAT16, layout=Layout::TILE))
```

**Comment by tarafdarTT** [comment]
I think this is closer to an eltwise-binary op @eyonland

**Comment by eyonland** [comment]
Would it be better to close this ticket and instead create a new one specifically asking for ttnn.repeat to work with sharded tensors?

**Comment by eyonland** [comment]
I see this was upgraded to P0.  As mentioned, this support requires a ttnn.repeat to support sharding in this current implementation.

**Comment by ntarafdar** [comment]
This example highlighted above is in interleaved. 
Could someone provide the specific shading specification.

**Comment by ntarafdar** [comment]
I think I can add some auto formatting to interleaved such that we can always parse the input (for that it won't matter what sharing specification the input is in)
For native support it would be helpful to have the sharing spec.

I will have a PR up for formatting to interleaved soon.

**Comment by ntarafdar** [comment]
I'm closing this issue and going to follow in a different issue specifically adding sharding to repeat.
