### ISSUE TITLE
investigate: using const unexpectedly drops perf by 10%

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#4048]
This issue was found in bbe, not metal.  However, it shows up in common code.  From 10K feet, adding const to some volatile pointers dropped perf significantly.  Filed for tracking.

diff --git a/src/ckernels/wormhole_b0/buda/common/src/ckernel.cc b/src/ckernels/wormhole_b0/buda/common/src/ckernel.cc
index cc16bee398..299d321c6b 100644
--- a/src/ckernels/wormhole_b0/buda/common/src/ckernel.cc
+++ b/src/ckernels/wormhole_b0/buda/common/src/ckernel.cc
@@ -16,10 +16,10 @@ namespace ckernel
 
 enum class ttRiscCores : std::uint32_t { Unpack = 0, Math = 1, Pack = 2, Brisc = 3, Nrisc = 4};
 
-volatile uint tt_reg_ptr *reg_base = reinterpret_cast<volatile uint *>(0xFFB10000);
-volatile uint tt_reg_ptr *pc_buf_base = reinterpret_cast<volatile uint *>(PC_BUF_BASE);
-volatile uint tt_reg_ptr *regfile = reinterpret_cast<volatile uint *>(REGFILE_BASE);
-volatile uint tt_reg_ptr *instrn_buffer = reinterpret_cast<volatile uint *>(INSTRN_BUF_BASE);
+volatile uint tt_reg_ptr *const reg_base = reinterpret_cast<volatile uint *>(0xFFB10000);
+volatile uint tt_reg_ptr *const pc_buf_base = reinterpret_cast<volatile uint *>(PC_BUF_BASE);
+volatile uint tt_reg_ptr *const regfile = reinterpret_cast<volatile uint *>(REGFILE_BASE);
+volatile uint tt_reg_ptr *const instrn_buffer = reinterpret_cast<volatile uint *>(INSTRN_BUF_BASE);
 volatile uint tt_reg_ptr *mailbox_base[4] = {
     reinterpret_cast<volatile uint tt_reg_ptr *>(TENSIX_MAILBOX0_BASE), reinterpret_cast<volatile uint tt_reg_ptr *>(TENSIX_MAILBOX1_BASE),
     reinterpret_cast<volatile uint tt_reg_ptr *>(TENSIX_MAILBOX2_BASE), reinterpret_cast<volatile uint tt_reg_ptr *>(TENSIX_MAILBOX3_BASE)
diff --git a/src/ckernels/wormhole_b0/common/inc/ckernel.h b/src/ckernels/wormhole_b0/common/inc/ckernel.h
index 65dee87e2b..295ad3d9e3 100644
--- a/src/ckernels/wormhole_b0/common/inc/ckernel.h
+++ b/src/ckernels/wormhole_b0/common/inc/ckernel.h
@@ -81,10 +81,10 @@ constexpr uint RESET_VAL = 0;
 constexpr uint KERNEL_IN_PROGRESS = 15;
 constexpr uint KERNEL_COMPLETE = 1;
 
-extern volatile uint tt_reg_ptr *reg_base;
-extern volatile uint tt_reg_ptr *pc_buf_base;
-extern volatile uint tt_reg_ptr *regfile;
-extern volatile uint tt_reg_ptr *instrn_buffer;
+extern volatile uint tt_reg_ptr *const reg_base;
+extern volatile uint tt_reg_ptr *const pc_buf_base;
+extern volatile uint tt_reg_ptr *const regfile;
+extern volatile uint tt_reg_ptr *const instrn_buffer;
 extern volatile uint tt_reg_ptr *mailbox_base[4];
 extern volatile uint tt_reg_ptr *dbg_event_scratch;
 extern volatile uint tt_reg_ptr *trisc_l1_mailbox;

**Comment by nathan-TT** [comment]
as a general observation the widespread use of `volatile` is ick.  My suspicion is these are really atomics and/or controlled by a mutex with acquire/release semantics.
for this case, I wonder  if a simple memory load of the pointer variable has become a resynthesis of the pointer value. GCC 12 looks to be better at that -- modelling the hi/lo parts in the RTL, rather than punting to the assembler.

**Comment by pgkeller** [comment]
closing as I don't think there is much expected return from trying to investigate this further
