### ISSUE TITLE
Allow WH devices on multiple N300's to be connected in a ring topology

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#4145]
* Need to ensure that all ethernet  links train
* Both TFly and QSFP connections 
* Need this for 2x/3x/4x N300's systems

A requirement to deliver LLMs on T3000 and Dirtbox systems.

**Comment by pgkeller** [comment]
@davor is this still relevant?

**Comment by davorchap** [comment]
this is done
