### ISSUE TITLE
[Cloud Support] Request to set up 2x VM for Partner Developer 

### ISSUE THREAD

**Issue by chekangliang** [tenstorrent/tt-metal#4160]
## Problem/Purpose

Please help to set up 2x VM cloud instance for new developers (MCW). Their development focus will be in model bring up so it would require baseline developer tool chains. Let me know if there are any info I need to provide. 

## Environment information

Such as, if applicable:

- BM/VM/Container
- TT Silicon information (ex. E150 hang issue)

**Comment by tt-rkim** [comment]
Is this still needed @chekangliang or did we resolve already?

**Comment by chekangliang** [comment]
Yes it is still needed
