### ISSUE TITLE
Enable C++20

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#4252]
@eyonland @arakhmati and myself can see big benefits with adapting C++20. This can be a contained rollout as we can compile a subset of our code with C++20, and the rest still on C++17. (See https://stackoverflow.com/questions/46746878/is-it-safe-to-link-c17-c14-and-c11-objects/49119902#49119902). 

However, we need to migrate to at least GCC 10 as many required [features](https://gcc.gnu.org/projects/cxx-status.html) are only present in the newer versions. Luckily, Ubuntu 20.04 has a GCC 10 [package](https://packages.ubuntu.com/search?keywords=gcc-10). This won't be a problem if/when we migrate to conda as I've already used conda's GCC 12 package.

**Comment by TT-billteng** [comment]
Should try using [clang](https://github.com/tenstorrent-metal/tt-metal/pull/5114#issuecomment-1925907302) instead of upgrading to gcc 12

**Comment by TT-billteng** [comment]
clang vs gcc [perf](https://www.phoronix.com/review/gcc-clang-eoy2023) seems to be equal these days

**Comment by cfjchu** [comment]
fyi @arakhmati

**Comment by ttmchiou** [comment]
Needs the following branch to fix build issues with tt-metal codebase after compiling with clang-17 on C++17 standards
https://github.com/tenstorrent-metal/tt-metal/pull/6408

**Comment by ttmchiou** [comment]
Blocked by the resulting failures in when using clang to compile tt-metal. 
Using different optimization levels (O0-O3 
https://github.com/tenstorrent-metal/tt-metal/issues/6927
https://github.com/tenstorrent-metal/tt-metal/issues/6926
https://github.com/tenstorrent-metal/tt-metal/issues/6925
