### ISSUE TITLE
Investigate use of nanobind as a replacement of pybind11

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#4258]
https://github.com/wjakob/nanobind

> More concretely, [benchmarks](https://nanobind.readthedocs.io/en/latest/benchmark.html) show up to ~4× faster compile time, ~5× smaller binaries, and ~10× lower runtime overheads compared to pybind11.

I believe some of our issues related to binary size and compilation speed are due to use of pybind11. Let's investigate use of nanobind, as I hope chatGPT/some other LLM can do an auto conversion for us. I believe it's ok to have nanobind and pybind11 live side by side for situations where nanobind won't work. From a dependency standpoint, both are very lightweight.

Decision making process should be driven by [bloaty](https://github.com/google/bloaty) or something similar

**Comment by tt-rkim** [comment]
@TT-billteng Should we put this back on the board? This could be a great perf benefit that's independent of both Python version upgrade AND compiler upgrade

**Comment by TT-billteng** [comment]
worth a shot, I have another issue looking into removing useless includes

**Comment by tt-rkim** [comment]
@arakhmati why you close?

**Comment by tt-rkim** [comment]
Definitely not shortly. I believe it was a candidate for a bounty.

**Comment by Shubhamsaboo** [comment]
@ThisIsFineTM this is indeed a bounty now 💰 

Happy to assign this to you @ThisIsFineTM.

Be sure that you read over the [BOUNTY TERMS](https://docs.tenstorrent.com/bounty_terms.html), as you agree to all of them by picking up this issue.

If we haven't received any communication from you in a two week period, we will re-assign the issue, and you will no longer be eligible for completion of this bounty.

If you have any questions feel free to ping me here on this issue! Look forward to seeing your submission.

**Comment by ThisIsFineTM** [comment]
There's a decision we need to make before I dive right in:

Do we have 1 switch to change binding engines where its all-or-nothing, or do we break things up to be more piecemeal for a smoother transition. I can appreciate both methods, but since I'm adding this to your codebase as a 3rd party, I would appreciate some weigh-in so we can be on the same page with expectations.

### All or nothing:
#### Pros
* More straight forward from a code/cmake organization point of view
* Minimal interference with existing code and active development
* Potentially faster turnaround for total completion
* Don't have to spend as much time working around the strong coupling within the pybind code.
#### Cons
* It either works or it doesn't
* Risk of making edge cases more difficult to troubleshoot
* More time in code review required to get the capability due to the amount of changes all at once

### Piecemeal:
#### Pros:
* Faster to get individual submodules into the review/testing pipeline
* Edge cases can be deferred in favor of getting other more straight-forward parts working
#### Cons
* Need to break up the existing submodule heirarchy into individual modules since pybind and nanobind modules are not compatible. eg. ttnn.core -> ttnn_core
  * Going to need to validate that refactor as an additional step.
  * The strong coupling will make that more complicated.
  * Could work around the interface change by adding some glue code on the python side to remap to the original structure.
* Will have more potential interference with the active development going on in the pybind tree (which was as recent as yesterday)
* All things equal, it will be longer to implement to completion and will more likely require a time extension.

**Comment by afuller-TT** [comment]
Long term we don't want two implementations.  It would be a maintenance burden and we're not going to ship two variants.  Besides one of the goals is to have faster builds, not extra things to build.

So ultimately it's all-or-nothing.

Getting there I leave it to your discretion.  If suitable, we can have a CMake option where we flip A vs B.  That might be useful if you want to have some incremental PRs and then a final 'cutover' later.  But if code needs to get reorganized, that may be too much extra work.

FWIW TT-NN is a prime candidate for some CMake TLC.  I won't be getting to that for several weeks yet.  But if you choose to do some of that to make bindings easier, that would be welcome bonus.

**Comment by ThisIsFineTM** [comment]
Works for me. I'll start with the all-or-nothing approach and will refactor as needed. I may end up going to the piecemeal approach if all-or-nothing proves to have more blockers.

**Comment by blozano-tt** [comment]
@ThisIsFineTM super excited for this! I am rooting for you!

**Comment by ThisIsFineTM** [comment]
No pressure 😅

**Comment by ThisIsFineTM** [comment]
Brief status update-

* I mirrored the `*_pybind` files into `*_nanobind`
* Hooked up nanobind to cmake
* There's a little over 300 files
* I've converted about half of the files so far
* Had several cases where there were only hpp files, so I created the relevant cpp files and hooked them up in cmake
* Have a few cases that I deferred until the more straight forward work has been exhausted
* At my current pace, I'll probably want an additional week for testing / validation, since its...a lot. 
* I've been putting in some other smaller PRs on the side as I've come across things that are outside the scope of the bounty.

**Comment by blozano-tt** [comment]
Thanks for your force of will.

I’m wondering, (300 files sounds like a lot).

Are there schemes that could be adopted to reduce the pybind11 boiler plate?

For instance macros or template functions?

**Comment by ThisIsFineTM** [comment]
@blozano-tt 

If you want to see the list:
```sh
$ find ./ttnn -name "*pybind*"  | grep -E ".(hpp|cpp)$" | wc -l
311
```

The bindings are broken up into two distinct categories: individual class bindings and module bindings.

The individual class bindings expose things such as the constructors, class member functions, dunder implementations, and implicit conversions. 

The module bindings actually group those into the python module structure. 

Digging around, I did find this, which does have some automation: https://github.com/pthom/litgen

The issue I had was that there are some bits of the binding functionality that are custom, so I went with the semi-manual approach because I didn't want to have the generated bindings to break userspace (and to learn more about the codebase in general). My goal is to have this effort be a drop-in replacement for users of the python bindings.

**Comment by ThisIsFineTM** [comment]
Status update:
Not including the initial mirroring of the `*pybind*` -> `*nanobind*` and hooking up cmake:

```sh
$ git rev-list 06cbaff33d..HEAD | wc -l
153
$ git diff --shortstat 06cbaff33d
282 files changed, 5168 insertions(+), 4298 deletions(-)
```
31 targets to go according to ninja. Mostly out of low-hanging-fruit and debugging some issues in the files that glue everything together.

**Comment by blozano-tt** [comment]
There was a major PR that landed this week with like 8,000 lines changed.

Are you staying reasonably close to main?

**Comment by ayerofieiev-tt** [comment]
@ThisIsFineTM Great progress!

**Caution!** 
Please make sure to align any 3rdparty lib or any significant changes to the binding approach (e.g any kind of automation).
We all desire both C++ and Py APIs to be the best, docs to be the best, effort to add/maintain bindings to be the best. There are other efforts that are in progress or in drafting stage that might impact the decision. So I want to make sure we don't make decisions without the full context.

**Comment by ThisIsFineTM** [comment]
The way I have everything structured right now is I left the pybind code untouched and the nanobind code exists along side in distinct files.

In cmake, I added flags for `USE_PYBIND` and `USE_NANOBIND`, which will enable builds using either backend. The nanobind hooks are all adjacent to the pybind hooks. 

With how fast the repo evolves, I felt it prudent to keep this work as separate as possible from files other people are touching in main. This does make it a little extra work to make sure the bindings stay in sync with any development going on in the pybind code, but the reduced risk from not stepping on people's toes or holding up other development is worth it imo.

@blozano-tt I am holding off on syncing with main until I can get the nanobindings to build without error (getting close!). I've been documenting the individual file/module changes in the commit history and whether or not the nanobind port was straight forward or required some special attention. That way when I rebase I can have the per-file conversion guide right there to streamline the process. Having the foundation of a known good working set of bindings eliminates the question of "did I screw up the bindings or did something get updated?".

**Comment by blozano-tt** [comment]
> One of the things I've noticed is that most of the binding files are split up into hpp/cpp, but there are several that are header-only that don't need to be. I've been spinning up the cpp files where appropriate and cleaning up the includes as I've been going along. Hopefully it helps alleviate the build bottleneck with the bindings.

You honestly deserve a statue in the TT parking lot.

**Comment by ThisIsFineTM** [comment]
> You honestly deserve a statue in the TT parking lot.

I'll settle for a mini printed in PLA+ hiding in the background of random dev-day photos a la "where's waldo".

**Comment by ThisIsFineTM** [comment]
Status update:

* The low-hanging-fruit has been picked clean.
* Ended up adding a pretty sizable chunk of cpp files for the bindings that didn't have them before.
* Down to single-digit remaining build targets (assuming fixing the current errors doesn't uncover more).
* Debugging some really nasty template errors (> 300 lines of error spew for 1 file, for example, but I do have the error reporting depth turned up)
* Nanobind doesn't implement `def_buffer` and instead uses `ndarray` with a bit of a different setup. `tensor` has a lot of buffer code so its going to take some work.

**Comment by blozano-tt** [comment]
I did the work you are doing in the past on a much much smaller library, and I recall nanobind had first class support for torch tensors using ndarray.

I’m hopeful once you get through the hard part, things are cleaner than ever.

Thank you again for your help!

**Comment by ThisIsFineTM** [comment]
@blozano-tt It does have first class support for it, which is rather nice, but it also opens the door to having to figure out how much of the more manually implemented buffer code can be removed in favor of the built-in. How much of that to refactor is a bit of an open question.

For convenience (framework type is the section immediately below device type):
https://nanobind.readthedocs.io/en/latest/api_extra.html#device-type

nanobind also has support for `bind_vector`, which lets python and C++ share the underlying data more directly. I came across some comments in the code a few days ago about someone wanting to make certain interfaces faster, so those are good candidates for `bind_vector`. However, I feel that those types of enhancements are a bit outside the scope of the current effort. I want to get these last errors ironed out, sync with main, and get the nanobindings in the hands of people to actually exercise the new code. We can work on iterative improvements to the binding code as we transition away from pybind.

**Comment by ThisIsFineTM** [comment]
@blozano-tt I took a look at the new additions to `main` and  there wasn't much that needed deconflicting. There are just a few new files that had binding targets added, so I went ahead and just did the rebase and put these on the stack:
```
set(TTNN_SRC_PYBIND

    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/ttnn/operations/conv/conv1d/conv1d_pybind.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/ttnn/operations/data_movement/pad/pad_pybind.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/ttnn/operations/data_movement/reshape_on_device/reshape_pybind.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/ttnn/operations/data_movement/stack/stack_pybind.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/ttnn/operations/experimental/bcast_to/bcast_to_pybind.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/ttnn/operations/experimental/reduction/cumsum/cumsum_pybind.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/cpp/ttnn/operations/experimental/transformer/all_reduce_create_qkv_heads/all_reduce_create_qkv_heads_pybind.cpp
```

**Comment by tt-dma** [comment]
Hello, just a heads up I have a PR going in soon to remove some pybinds: https://github.com/tenstorrent/tt-metal/pull/21344. We're fully switching over from IDevice/Device -> MeshDevice, so the single-device pybinds are going away.

**Comment by ThisIsFineTM** [comment]
With how much active development is going on in the binding code, I have some thoughts on the integration strategy that I would like input on. Sorry for the wall of text!
 
**Issue 1**: I had some minor structural refactors- splitting the remaining monolithic hpp binding files into hpp/cpp, cleaning up includes, forward declarations, some extern template, and fixing some linker edge cases. These are currently the least straight forward to sync.

**Proposed Solution**: Create a separate PR where I make the structural updates in the pybind11 code so the nanobind is easier to keep synced. I already have a "shortlist" for those items so it shouldn't take *too* long. (Status: Complete #21633 #22292)

**Issue 2**: Currently I have a flag that can switch the build targets between pybind and nanobind, but this is currently implemented in discrete co-located blocks. This makes it very manual to make sure any new files / build targets are taken into account. However, I kept the names and file locations consistent, only swapping pybind for nanobind in the names/paths (with 1 notable exception). 

**Proposed Solution**: Refactor the cmake targets to be in the style of `filebase_${PY_BINDING}.cpp`,
with the binding backend flag setting the `${PY_BINDING}` cmake variable. This makes it so any new changes on the pybind build targets will automatically generate error messages in nanobind-mode that can make addressing discrepancies more streamlined. (Its not a bug, its a feature!)
(Status: Complete #21386 #21394)

**Issue 3**: The core pybind11 code lives in `ttnn/cpp/pybind11` of which `ttnn/cpp` is in the include path. The pybind11 third-party library uses `pybind11/<header>`. This makes the first party pybind include path ambiguous with the third party include path. `#include "pybind11/types.hpp"` got me more times then I'd like to admit.

**Proposed Solution**: Refactor the `cpp/pybind11` directory to `cpp/ttnn-pybind` to remove the ambiguity. I've already been using `cpp/ttnn-nanobind` in my branch and it has made things more clear. Added bonus is the cmake targets fall nicely into `cpp/ttnn-${PY_BINDING}`.
(Status: Complete #21498 #21504)

Each of these can be their own PR, and as long as the nanobind cmake codepaths are specifically opt-in, shouldn't break CI or userspace. It also makes people aware of the nanobind implementation more broadly, which should help with the transition. Order of time/difficulty is 1>2>3, and the nanobind code itself isn't required to implement these changes.

**Comment by ayerofieiev-tt** [comment]
Issue 3 - your proposed solution is good. 
Keeping in mind that pybind11 should be removed once nanobind proves working and giving same or better performance.

**Comment by ayerofieiev-tt** [comment]
Issue 1 - aligned, good thinking. Thank you

**Comment by ThisIsFineTM** [comment]
> Issue 3 - your proposed solution is good. Keeping in mind that pybind11 should be removed once nanobind proves working and giving same or better performance.

@ayerofieiev-tt That is the end goal, yes, but given how much traffic the binding code is getting, putting in the extra work to make sure the transition is as smooth as possible for everyone else is worth it.

**Comment by ThisIsFineTM** [comment]
Current plan of execution:
Going to wait for #21344 to get merged before putting in the next stage PRs. David's PR touches a lot of files so I don't want to do anything that will cause it unnecessary delay.

**Comment by ThisIsFineTM** [comment]
Status update: Nearing completion of the pybind sync / ttnn cleanup. Trying to get some related PRs merged before submitting that one.

**Comment by ThisIsFineTM** [comment]
There's a lot of moving parts in ttnn right now making rebasing onto the latest main a bit of a slog, so I'm going to stage that rollout as well.

**Comment by ThisIsFineTM** [comment]
@Shubhamsaboo The pybind side of things keeps moving rapidly and it is a bit of a cat-and-mouse game at this point. Can we consider a snapshot for merging the bounty?

**Comment by Shubhamsaboo** [comment]
Hey @ThisIsFineTM. 

@afuller-TT will help you with what's needed. Conceptually I am fine with what you are suggesting.

**Comment by ThisIsFineTM** [comment]
Good news, everyone! Nanobind builds and links with/without tracy and unity builds! This is a side by side comparison of the resulting library size using clang 20, release build, LTO, with tracy. 
```
nanobind: 23M  _ttnn.so

pybind:   49M  _ttnn.so
```

**Comment by blozano-tt** [comment]
> Good news, everyone! Nanobind builds and links with/without tracy and unity builds! This is a side by side comparison of the resulting library size using clang 20, release build, LTO, with tracy.
> 
> ```
> nanobind: 23M  _ttnn.so
> 
> pybind:   49M  _ttnn.so
> ```

Oh wow!!! This should help the wheel size!!!! @warthog9 check out this amazing external contrib!

**Comment by nsextonTT** [comment]
Closing. PR is merged and live. https://github.com/tenstorrent/tt-metal/pull/34447

@marty1885 Now its official :)
