### ISSUE TITLE
Investigate use of a per-test timeout 

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#4259]
Lately I've noticed that our post commit time is getting longer and longer. I believe some suites have a hard cutoff time of 1.5h and rather than keep changing a per suite cut off time, we can add a per-test timeout as a way to isolate hangs. This would be especially beneficial for our stress test runs since if a test actually hangs, we would be terminating much earlier than the 24h time limit, thus freeing up resources. 

We should investigate cutting down post-commit time in a separate issue, but we should consider using plugins like [pytest-timeout](https://pypi.org/project/pytest-timeout/ ).

**Comment by tt-rkim** [comment]
@TT-billteng are you tagging your commits with `pytest-timeout` with this? Could you do so pls?

**Comment by TT-billteng** [comment]
pytest timeout limit set to 10 minutes and in main currently

should investigate if this is possible for GTest

**Comment by TT-billteng** [comment]
Can't seem to find a generally accepted way to introduce a timeout threshold for each test with GTest

But CTest seems to provide a [way](https://stackoverflow.com/questions/45009595/how-to-overwrite-ctest-default-timeout-1500-in-cmakelists-txt) to do so.

**Comment by TT-billteng** [comment]
CI runs don't seem to respect the 10 minute pytest timeout for some reason :|

https://github.com/tenstorrent-metal/tt-metal/actions/runs/7481539629/job/20363314196

**Comment by tt-rkim** [comment]
@TT-billteng 
hmm... I see this

```
timeout: 600.0s
timeout method: signal
timeout func_only: False
```

Is it possible it can't signal the test out with `SIGINT`? Or whatever it is?
And it doesn't log that? Not sure... I feel like `pytest-timeout` would flip the heck out if it couldn't signal kill a test but I'm unsure.

What do you thyink

**Comment by TT-billteng** [comment]
I was able to get it working locally on my machine, just not sure why CI doesn't respect the timeout :|

**Comment by tt-rkim** [comment]
Did it work locally when a device-side hang was going on?

**Comment by TT-billteng** [comment]
hmmmm not sure

**Comment by TT-billteng** [comment]
but I would think it should because it should be timing the user-side process

**Comment by tt-rkim** [comment]
My theory is that it's a device-side hang that doesn't respect `SIGALRM`.

I may sound crazy, but I've seen this multiple times before. Ctrl+C doesn't do anything when trying to exit such a process.

`pytest-timeout` does support a `timeout_method=thread` option, but that comes at the cost of putting all tests into a separate thread. Not sure if logging will work in the first place, but we also will be masking a shit-ton of host-side problems by doing that.

What do you think?

**Comment by TT-billteng** [comment]
I think you're right, I'm trying to narrow down this BERT hang and tried using the `timeout` parameter; nothing happened and `Ctrl+C` doesn't work either

**Comment by tt-rkim** [comment]
If you do `sudo cat /proc/<PID>/stack` after checking for PID with something like `ps aux | grep metal`, you'll be able to see if it's hanging on device by checking if the last call is called something like "exit user mode loop", something like that

I find that if that happens, it guarantees signals can't really kill the process.

I'm not sure why this is. I think the usual case is it gets stuck in trying to read hex from the device via UMD. If we want timeouts to work for device-side hangs during pytest, I think we either have to bite the nasty bullet of moving everything into separate process, or add debug timeout infra to firmware for hangs. I think they may have something similar on Buda.

**Comment by TT-billteng** [comment]
Closing as this does work if it's not specific types of device-side hangs
