### ISSUE TITLE
uplift matmul kernel examples to new utilize and eliminate the extra data conversion

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent/tt-metal#4260]
Tasks on the 4 matmul kernel examples:
- Use new utilize() in #3219 and eliminate the extra data conversion uint32_t <> bfloat16 in vector gen, golden, and pcc check functions
- Add device profiler code
- Add some KPRINT examples in read/compute/write kernels

**Comment by rbartonTT** [comment]
Next steps:
- Update documentation to reflect bfloat16 changes to singlecore and multicore examples
- Add profiler to observe execution from one optimized version to another
- Add DPRINT commands to the 3 device kernels
- Add documentation to multicore_reuse and multicore_reuse_mcast examples
