### ISSUE TITLE
ttl.tensor.rmsnorm results in a mismatch

### ISSUE THREAD

**Issue by arakhmati** [tenstorrent/tt-metal#4327]
When running rmsnorm in t5, there is a PCC mismatch

**Comment by arakhmati** [comment]
> @arakhmati - can you add reproduction steps here ? if not tensor at least datatype and shapes are useful

Will do. Unfortunately it only fails in a bigger test

**Comment by arakhmati** [comment]
This is no longer an issue. rms_norm works perfectly fine in `t5`. Not sure if it somehow got fixed or maybe it was never the problem

**Comment by arakhmati** [comment]
This is still an issue. As seen by failures of t5 in the pipelines

**Comment by tt-aho** [comment]
@arakhmati can you retry on latest main if this is still an issue?

**Comment by arakhmati** [comment]
> @arakhmati can you retry on latest main if this is still an issue?

Will do

**Comment by jliangTT** [comment]
this issue has grown quite stale. Is this there an opportunity for a downgrade here or just closing if we don't plan on action on this any time soon?

**Comment by tt-aho** [comment]
If there is a unit test to repro, I can take a look.

**Comment by umadevimcw** [comment]
@tt-aho Are you looking at this issue?

**Comment by VirdhatchaniKN** [comment]
Hi @arakhmati ,
In test file `tests/ttnn/integration_tests/t5/test_ttnn_optimized_functional_t5.py` ,I noticed that different PCC values are provided for each test - [RMSNORM PCC.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14694318/RMSNORM.PCC.pdf)
The assertion error reported for the 7 failing test cases slightly varies in PCC when compared with the expected PCC. Would like to know If there is any specific reason for setting up PCC for each test

**Comment by jliangTT** [comment]
I am going to downgrade this to P2 to align with the javelin priority. T5 is super important but yeah javelin is keeping the really busy. I want to make this change to avoid priority inversion. 

Feel free to undo this @arakhmati if you feel differently.
