### ISSUE TITLE
Untilize sweep test does not work for multicore (last shape)

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#4332]
test: 
`tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_untilize.py::test_untilize_test[untilize_args0-input_shapes2]`

This needs to be fixed for multicore, and then change the default untilize to use multicore once this is fixed.

**Comment by mywoodstock** [comment]
cc: @TT-BrianLiu

**Comment by jliangTT** [comment]
this issue has grown pretty stale. Does it still apply?

**Comment by TT-BrianLiu** [comment]
@mywoodstock Is this test still broken?

**Comment by mywoodstock** [comment]
@TT-BrianLiu Yes, it still fails.

**Comment by jliangTT** [comment]
Does this need to be P1 critical? No one has complained about it since december? That tells me it shouldn't be p1.

**Comment by jliangTT** [comment]
The similar single core untilize is also showing up in ViT #6812 - we should also understand this as well.

**Comment by TT-BrianLiu** [comment]
On Grayskull, this test cant run cause it runs out of L1. Couple of things I have noticed with untilize:
- Single-core and multi-core both take full width per core. Single-core version properly figures out how much of the width to buffer, while multi-core naively double buffers on the full width. That's causing this test to run out of memory. 
- If each core gets the full width and at least tile HEIGHT, I would expect multi-core to just work as well.

What's needed to enable multi-core by default is:
- defining some shapes to test before we call it working. So far, I haven't seen a case fail on Grayskull multi-core.
- clean up `multi_core` and `pack_untilize` flags. We should just use the both as True and fix what's not working. It seems like it's just a matter of getting `pack_untilize` to work with longer widths.

**Comment by davorchap** [comment]
> * clean up `multi_core` and `pack_untilize` flags. We should just use the both as True and fix what's not working. It seems like it's just a matter of getting `pack_untilize` to work with longer widths.

Yes! Multi-core / pack-untilize flags as default behavior, and we can then deprecate the flags.

**Comment by TT-BrianLiu** [comment]
@mywoodstock I also tried the "failing" shape on wormhole. It runs out of L1 there as well. Are you sure there is a PCC issue? Or is it just a matter of cleaning up logic between single-core and multi-core?

**Comment by mywoodstock** [comment]
Oh sorry i did not enable multicore :) Yes, I also get L1 error now.
I do remember earlier it used to be PCC error.

**Comment by mywoodstock** [comment]
Also, I don't know which model uses/needs this particular shape :-/

**Comment by TT-BrianLiu** [comment]
Closing this issue now. The shape isn't bugged
