### ISSUE TITLE
Reduce noise from ResNet50 perf reports

### ISSUE THREAD

**Issue by farbabi** [tenstorrent/tt-metal#4357]
resnet50's performance shows significant noise for all batch sizes; this makes it impossible to accurately track performance improvements and regressions.

Hypothetically, calculating inference time from the 3rd run would be less noisy. @pgkeller: "The idea on using the 3rd run is that run 1 is dominated by compile.  Run 1 will likely kick lots of stuff out of cache and perhaps cause the main app to page out.  Run 2 gives the main app a chance to page in and warm the cache.  Run 3 may be clean(er). "

@davorchap

**Comment by farbabi** [comment]
It was found that the first few iterations include more noise compared to iterations > 4. For example for batch = 16:
<img width="1240" alt="Screen Shot 2023-12-14 at 5 16 24 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109362734/be294c43-490b-43d3-a3a6-dd0864b7abb5">

Moving forward, the average inference time of iterations 5-10 will be considered as model's inference time.

**Comment by mywoodstock** [comment]
stale. closing
