### ISSUE TITLE
Do not convert uint8 -> uint32 in python script as part of compilation

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent/tt-metal#4358]
~I think as a short term improvement to build speed, would be worthwhile to re-write hex8tohex32.py to be a cpp file.~

Remove the conversion of hex8 -> hex 32, just send the 8-bit data directly to device (UMD now has void pointer APIs)

**Comment by pgkeller** [comment]
Better: we don't need to do the conversion to 32 bit at all, just read the 8 bit directly.  A little more difficult would be to parse the .elf file (wonder if there is an open source solution we could use)

**Comment by DrJessop** [comment]
Agreed, but the naive approach would be an obvious improvement regardless.

**Comment by DrJessop** [comment]
Good point, let me update issue.

**Comment by pgkeller** [comment]
closing as this is done, though will open an issue later to parse the elf file directly
