### ISSUE TITLE
Refactor llrt/device/build

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#4363]
llrt sits below the device, this causes issues w/ things such as watcher (which sits in llrt presently)
device and build should sit at the lowest level of the SW hierarchy, likely as peers to the current llrt code (most of which is migrating away over time)

This issue is to track final resolution/refactor once the direction is fully known...

**Comment by tt-dma** [comment]
Should also enable the dprint hanging test/check for slow dispatch once these changes are in. See https://github.com/tenstorrent-metal/tt-metal/pull/4326#discussion_r1430610736 for details on why it's currently disabled for now.

**Comment by pgkeller** [comment]
fixed the main issues, and changed though on the hierarchy, closing.
