### ISSUE TITLE
Investigate and resolve GitHub-reported vulnerabilities

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#4382]
Dependabot is a dependency + vulnerability checker that GitHub runs for us on public repos.

It's found some, with some critical ones.

Though we're not serving sensitive data so it's not as bad as running a web service with such vulnerabilities, we should investigate and resolve.

I'm labelling this as P1 as it is definitely needed, but not urgent.

cc: @TT-billteng @tt-aho @chekangliang @jvasilje @davorchap

**Comment by tt-rkim** [comment]
From what I can tell, I'm fairly certain we can just bump versioned dependencies, then test on CI, then merge.

**Comment by TT-billteng** [comment]
fixed https://github.com/tenstorrent/tt-metal/commit/aa059925407012e45c4a228b52d87e64ddf0b1ec
