### ISSUE TITLE
[slow vs fast dispatch requirement for C++ Integration Tests] 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#4417]
**Describe the bug**
some C++ integration tests in tt-metal on this path: tt-metal/build/test/tt_metal fail after running "make tests" with an error: 
"This suite can only be run with TT_METAL_SLOW_DISPATCH_MODE set
backtrace ..."

The error can be avoided by exporting the env variable TT_METAL_SLOW_DISPATCH_MODE. However, other tests will fail if with this variable set to 1. 

**To Reproduce**
1. from the path:  "tt-metal/build/test/tt_metal "
2. run "make tests"
3. you will see the error

**Expected behavior**
suggesting to update documentation to inform user of the env variable requirements for different tests and also a short description of why this is needed per test. the details can be added somewhere in the shared screen shot of the documentation. 

**Screenshots**
![image](https://github.com/tenstorrent-metal/tt-metal/assets/132954887/af2dad7e-a752-45a0-9e6c-53f07ce67355)

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]

**Comment by tt-rkim** [comment]
Thank you for filing @dvartaniansTT 

Also please do not assign @muthutt - he is working on ops and wrote this piece of documentation as a courtesy to our team, but does not directly work on the C++ integration tests for metal runtime.

There is not actually a bug here, but rather a communication issue.

The key problem is: Certain tests can only be run in slow dispatch. Certain other tests can only be fast dispatch. There is only a subset of tests that can be run in both.

What do you think about the following solution: We will add more wording to clarify this and to tell users to be careful. We will refer them to places in the code where they can read more to see which test can be run with which dispatch mode. I would rule anything like making a table that we have to update in documentation telling which test can be run with what. I believe users are able to read code themselves when it comes to this kind of testing.

**Comment by dvartaniansTT** [comment]
@tt-rkim Thanks for the prompt response! sure! Moving forward I will assign issues to you if i'm not sure and always feel free to reassign to the relevant person if its not you. I agree with the solution as long as an external user is aware of the requirements. I still think would be nice to point them to a description of the slow vs fast dispatch modes (might be a link/pointer to another place in documentation where this is already explained ...) as users for the most part start running demos and tests before they have developed a full understanding of the SW stack. In fact, they hope to gain as much insights as possible by running the tests and demos.
