### ISSUE TITLE
Investigate non-deterministic hang with >1 hugepage on frequent pipeline Falcon WH on slow dispatch

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#4425]
We found this issue with Falcon on SD on frequent when trying to upgrade machines to use more than 1 HP per MMIO on WH. This is to enable @abhullar-tt + @DrJessop changes on multiple queues.

I initially thought that 2 HP per mmio (N300) were good for the model runner WH BM. This runner is N300. I'm specifically looking at whether multiple HP is ok for the frequent model pipelines.

Here are the runs. You can see we ran them quite a few times without incident. Ignore the failure and cancellations in each - those are other things

FD: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7225522273
SD: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7225521424/job/19761169441I n

What we were seeing before were hangs on the falcon test in the frequent pipeline on SD with 4HP per MMIO. Which is weird because this shouldn't touch SD.

Falcon seemed to not hang as of yesterday on SD, as shown by above links.
However, today I wake up and I see a falcon SD hang on this machine running on main: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7256117029/attempts/1

The original run (check attempt 1) on 4 HP per MMIO WH:
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7225521424/job/19761169441

Ultimately, we decided to file this issue for the frequent pipeline with P2 and merge the cq per device + hugepage infra changes.

cc: @boris-drazic @farbabi @jvasilje @davorchap @abhullar-tt

**Comment by tt-rkim** [comment]
The full test in here: tests/scripts/run_models.sh
in slow dispatch mode. you could prob just pluck the command at line 67
a more recent example since logs are gone for the original ones:
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7578214629/job/20640433405

cc: @vtangTT I sent this to you in private on slack

**Comment by vtangTT** [comment]
Update: ran 100 interations of 
```pytest models/demos/falcon7b/tests/test_falcon_end_to_end.py::test_FalconCausalLM_end_to_end_with_program_cache[BFLOAT16-L1-falcon_7b-layers_32-prefill_seq128]``` 
and encountered no hangs. Not sure if we want to close this issue or if I should run some with the whole test to see if I can recreate.

**Comment by tt-rkim** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7706989651/job/21003434040

`models/demos/falcon7b/tests/test_falcon_end_to_end.py::test_FalconCausalLM_end_to_end_with_program_cache[BFLOAT16-L1-falcon_7b-layers_32-prefill_seq128]` still fails here with a hang 9 hours ago.

I believe you're right and we'll have to start looping over the models script. @farbabi was not able to reproduce this way, so perhaps we can loop with the slow dispatch unit tests with python api unit tests.

Try first looping the unit tests line in `tests/scripts/run_pre_post_commit_regressions_slow_dispatch.sh:25` with just that falcon test **together** and see where that gets us

**Comment by vtangTT** [comment]
I was able to observe a timeout on the 2nd iteration of running 
```python tests/scripts/run_tt_metal.py --dispatch-mode slow``` 
followed by 
```pytest models/demos/falcon7b/tests/test_falcon_end_to_end.py::test_FalconCausalLM_end_to_end_with_program_cache[BFLOAT16-L1-falcon_7b-layers_32-prefill_seq128]```

**Comment by tt-rkim** [comment]
Hurray, we can observe this easily.

We'll need to fix before further LLM work can start, probably.

cc: @tt-aho @TT-BrianLiu @boris-drazic

**Comment by jvasilje** [comment]
@tt-rkim is this resolved?

**Comment by tt-rkim** [comment]
@jvasilje Nope - still under investigation. If we can't find anyone to assign this full time to for investigation, we'll have to move it to P2. Which may be not desirable because it's Falcon.

**Comment by vtangTT** [comment]
assigning to @jliangTT per his request for further triage

**Comment by pgkeller** [comment]
is this issue still present?
