### ISSUE TITLE
Cleanup conv and matmul configs and api

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#4440]
All the config generation should be automated with heuristics.

**Comment by mywoodstock** [comment]
@shwetankTT ok to close this?

**Comment by shwetankTT** [comment]
Matmul config clean up is still pending.

**Comment by tt-nshanker** [comment]
Conv config cleanup addressed by https://github.com/tenstorrent/tt-metal/issues/7083
