### ISSUE TITLE
Productize Model Analyzer

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#4475]
Prototype here: https://github.com/tenstorrent-metal/tt-metal/tree/main/tt_eager/model_analyzer

* Ideal cycles / math utilization / BW utilization should be reported in the profiler report for each, so that we don't have to use a separate tool.  
* each OP should provide a cycle model -- the cycle model for a number of OPs is already in the prototype, it can just be ported over

**Comment by davorchap** [comment]
fyi @arakhmati @eyonland , as we progress on ttnn we should discuss the productization of model analyzer

**Comment by arakhmati** [comment]
> fyi @arakhmati @eyonland , as we progress on ttnn we should discuss the productization of model analyzer 

Sounds good

**Comment by xanderchin** [comment]
Functionality was merged into op reports.
