### ISSUE TITLE
Introduce two types of kernel run-time args: 1) common across cores, 2) unique to core

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#4476]
There are real uses cases where a kernel has a large number of run-time arguments, up to 256.
Most of these arguments are common to all the cores on which the kernel runs. 

By explicitly specifying which args are common we can optimize dispatch:
* the total size of run-time args to send via PCIe/ETH are smaller, since same common args can be sent for a CoreRange once (vs replicated for each core in the core range).
* dispatcher core can use multi-cast to send common args to CoreRange

The API can be made that first C_N args for a kernel are common, and then next U_N are unique to each core in the CoreRange. C_N / U_N are specific to each kernel. 

Alternatively, we could auto-detect which common args across cores, could be costly to do this at run-time for every launch, but it could work well with MetalGraph.
However, given that CT args are already setup with CoreRanges, as well as CB Configs, it would make sense to keep RT args consistent with other APIs and make them CoreRage based.

**Comment by davorchap** [comment]
fyi @DrJessop , @abhullar-tt , @xanderchin

**Comment by davorchap** [comment]
the feature to speed-up dispatch of kernels w/ lots of run-time args, fyi @razorback3 and @pcjung08

**Comment by razorback3** [comment]
Just a question.
Is it planned as a feature of fast dispatch 2.0? or after that?

**Comment by jliangTT** [comment]
This is separate from fast dispatch 2.0 and will probably happen after since this is a performance feature. 

c.c. @davorchap and @jvasilje to confirm

**Comment by davorchap** [comment]
@kmabeeTT this has been implemented, we can close?

**Comment by kmabeeTT** [comment]
> @kmabeeTT this has been implemented, we can close?

This got implemented in FD2.0 recently by someone you mean? I was looking at it as my first task for FD1.0 long time ago before being asked to switch to Events feature but not touched it since then.

**Comment by kmabeeTT** [comment]
Had some offline discussions. Packed-Write cmd (that this should use, feature multicast capability) is implemented, but SetRuntimeArgs for FD2 is not yet, so will keep this open until this following is solved.  

1. Define API usage (how to use SetRuntimeArgs or if new flavor required) - discussion happening here now.
2. Implementation for FD2.0 using PackedWrite
3. New Unit Tests showing how it works.
4. Update some ops or tests as needed as example.

**Comment by pgkeller** [comment]
seems this is done?

**Comment by tt-aho** [comment]
Think so, closing.
