### ISSUE TITLE
ResNet50 Inference Time Drops after Consecutive Runs

### ISSUE THREAD

**Issue by farbabi** [tenstorrent/tt-metal#4526]
Resnet50 inference time is dropping after consecutive runs (also see https://github.com/tenstorrent-metal/tt-metal/issues/4525). The drop is obvious on BM, not much on VM. Persistent kernel caching and program cache were tested; no difference.
On BM, batch 20 was tested, 5 runs, each 10 iterations:
<img width="1062" alt="Screen Shot 2024-01-02 at 5 13 17 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109362734/60b30752-049e-4b63-ba02-970ddb995da8">

_______________
On VM, batch 20:
<img width="877" alt="Screen Shot 2024-01-02 at 8 03 51 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109362734/5a4ff80f-529a-4058-b89a-d3e0a6f4466c">

**Comment by mo-tenstorrent** [comment]
This is interesting ! @farbabi could you provide the command to reproduce the setup.

**Comment by farbabi** [comment]
> This is interesting ! @farbabi could you provide the command to reproduce the setup.

@mo-tenstorrent you can use my branch: `farbabi/resnet_perf_bug`

**Comment by mo-tenstorrent** [comment]
Hmm, I can't reproduce the same results. What I see is random fluctuation. 

I did the two following runs, second run is a fresh build after a `git clean -dfx`

<img width="1507" alt="Screenshot 2024-01-03 at 1 47 31 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109363418/6dcd1ae3-4803-4f68-b3ad-5570a983eb3f">

<img width="1309" alt="Screenshot 2024-01-03 at 1 55 20 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109363418/3f6dc1af-88c0-4c90-8f5c-390929843a46">

The runs are on your branch using the following command:

`pytest models/demos/resnet/tests/test_perf_resnet.py::test_perf_bare_metal`

**Comment by farbabi** [comment]
<img width="900" alt="Screen Shot 2024-02-08 at 2 35 49 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109362734/8cbb25be-08be-45ef-933a-947f028c69d3">

**Comment by pgkeller** [comment]
this is an old issue, is this stale?  can we close?

**Comment by pgkeller** [comment]
assume this is stale, closing
