### ISSUE TITLE
Move dispatch message to host memory instead of caching in DRAM

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent/tt-metal#4548]
Currently, the dev message is sent to DRAM. However, now with multi-cq, we will have to tell the workers which dispatch core sent the message, which can vary. Therefore, this info cannot be cached anymore.

**Comment by jliangTT** [comment]
- Gating to dynamic memory map, with FD 1.0 this result in significant perf regression; with FD 2.0, it won't happen so should align to FD 2.0 work.

**Comment by pgkeller** [comment]
done w/ fd2
