### ISSUE TITLE
Debugging features and tips for SFPI code implementation

### ISSUE THREAD

**Issue by dongjin-na** [tenstorrent/tt-metal#4625]
As far as I know, there is an emulator and logging feature for SFPI.
However, it seems both features are not opened yet.
Are there any good tips for debugging SFPI code? Or is there a way to use the features I mentioned?

- Emulation section in https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/dependencies/llk.html
  But, there's no main.cc file in tt-metal repo.

- FWLOG macro in LLK but it seems there's no implementation.
```
// ckernel_sfpu.h
template <bool APPROXIMATION_MODE, int ITERATIONS>
inline void _calculate_dropout_(const int iterations, uint prob, uint scale)
{
    // SFPU microcode

    FWLOG1("calculate_dropout() -- prob:%x", prob);
    FWLOG1("calculate_dropout() -- scale:%x", scale);
```
```
// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
//
// SPDX-License-Identifier: Apache-2.0

#define FWASSERT(s, p)
#define FWLOG0(...) (void)sizeof(__VA_ARGS__)
#define FWLOG1(...) (void)sizeof(__VA_ARGS__)
#define FWLOG2(...) (void)sizeof(__VA_ARGS__)

```

Target : WH_B0

**Comment by razorback3** [comment]
https://github.com/tenstorrent-metal/tt-metal/blob/main/tt_metal/hw/inc/tt_log.h
I also found this file which contains defining a macro (_TT_LLK_DUMP_) that looks like printing something in LLK-level.
Need more info about it.
