### ISSUE TITLE
Test-sweeps profiler doesn't work

### ISSUE THREAD

**Issue by banekg** [tenstorrent/tt-metal#4655]
When the following command is started: 

`python tt_metal/tools/profiler/profile_this.py -c "python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/ttnn_eltwise_add_test.yaml -o ~/tt-metal/ttnn-result-sweeps/ttnn_eltwise_add_profiler" -o ~/tt-metal/ttnn-result-sweeps/ttnn_eltwise_add_profiler`

an error will appear and `profile` subdirectory will not be created:

<img width="1270" alt="Screenshot 2024-01-09 at 16 20 40" src="https://github.com/tenstorrent-metal/tt-metal/assets/102523164/e7ec2819-17d5-45e5-98c2-6fc0eabddedc">

**Note:** For some operations profiler works. Please try this operation:

`python tt_metal/tools/profiler/profile_this.py -c "python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/ttnn_eltwise_sub_test.yaml -o ~/tt-metal/ttnn-result-sweeps/ttnn_eltwise_add_profiler" -o ~/tt-metal/ttnn-result-sweeps/ttnn_eltwise_sub_profiler`

**Comment by mo-tenstorrent** [comment]
Can you confirm if this is still an issue with the latest on main?
