### ISSUE TITLE
Use RTE for host conversion to block floats: FP32/FP16 -> bfp8/4 

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#4657]
check that round-to-even (RTE) is used, so that we're not biasing downwards/upwards in round to nearest scheme. 

depends on #4659

**Comment by davorchap** [comment]
@tt-asaigal has implemented and validated in BBE, it's great!

**Comment by tt-aho** [comment]
We should already be doing RTE for bfp8, we haven't ported bfp4 conversion yet

**Comment by davorchap** [comment]
> We should already be doing RTE for bfp8, we haven't ported bfp4 conversion yet

Ok, let's keep this case until we have bfp4 working + RTE. 
Based on Partha's results bfp4+RTE works for Falcon 7B, so could be really good for Falcon 40B , Mixtral, LLama2-70B

**Comment by tt-aho** [comment]
Would this be duplicate/similar to the original issue #2980?

**Comment by davorchap** [comment]
> Would this be duplicate/similar to the original issue #2980?

True, I close the old one and let's track here.
