### ISSUE TITLE
Blackhole support in Metal (single-chip)

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#4678]
key dependencies

- syseng/driver tools that support BH
- UMD that supports BH
- LLKs that support BH: #4900 

work on metal side
- [x] #8102
- FW support for NCRISC needs to change (no IRAM like in GS/WH)

**Comment by jliangTT** [comment]
Detailed work being enumeated at #5174

**Comment by pgkeller** [comment]
@abhullar-tt is this a dupe (can we close)?

**Comment by abhullar-tt** [comment]
> @abhullar-tt is this a dupe (can we close)?

yeah I think this is a stale / dupe issue, closing
