### ISSUE TITLE
test_resnet50_untilize_with_halo_and_conv_v2 sproadically failing with watcher enabled in stress test pipeline

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#4687]
We recently enabled watcher on stress test (24h of post commit in a loop) pipelines and got several consecutive runs to pass (last one being most recent):

https://github.com/tenstorrent-metal/tt-metal/actions/runs/7430070758
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7441497962
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7456505379

However, stress test on GS started failing here:

https://github.com/tenstorrent-metal/tt-metal/actions/runs/7470195336

Around this time, CI on other pipelines were also experiencing issues, so this may be a regression issue.

Passing commit: https://github.com/tenstorrent-metal/tt-metal/commit/828ccd648e3bccc20f8a60877a7ed62210ae1a1b
Failing commit: https://github.com/tenstorrent-metal/tt-metal/commit/0dd85e4e9d33ff8f945598be4b6263596be3558b

```
2024-01-11T09:07:34.1246428Z FAILED tests/tt_eager/python_api_testing/unit_testing/test_resnet50_untilize_with_halo_and_conv_v2.py::test_resnet50_conv[LoFi-activations_BFLOAT8_B-weights_BFLOAT16-64-16-115-115-4-4-1-1-0-0-batch_20] - AssertionError: Output should be identical to old conv!
2024-01-11T09:07:34.1246548Z assert False
```

I have been able to repro this locally on a VM by running the stress test locally
@pgkeller @mywoodstock

**Comment by mywoodstock** [comment]
cc: @TT-BrianLiu

**Comment by TT-billteng** [comment]
Stress testing failed again on same test for GS https://github.com/tenstorrent-metal/tt-metal/actions/runs/7483006866/job/20367564268

**Comment by jliangTT** [comment]
Is this still failing @TT-billteng?

**Comment by ttmchiou** [comment]
Seeing hanging issues on same test here on N150 machines
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8262747162/job/22602917413

**Comment by jliangTT** [comment]
triaging this into the kernel op bucket now that we have that process.
