### ISSUE TITLE
tt_lib eltwise_logaddexp fails with low PCC when at least one operand BFLOAT8_B [Grayskull and Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#4711]
Logical eltwise operations `tt_lib.tensor.eltwsie_loagaddexp` operation fails with low PCC

**To Reproduce**
Checkout `npetrovic/float8-unit-tests` branch that will be soon merged into main. Run unit test 

`tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_bfloat8_eltwise_logaddexp.py`  

With command
```
tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_bfloat8_eltwise_logaddexp.py
```

**Expected behavior**
There are three test cases expected to fail with low PCC error.

For example, one of the tests is expected to fail with this result:
```
Max ATOL Delta: inf, Max RTOL Delta: nan, PCC: 0.0, PCC check failed
```

**Getting Details**
You can get more combinations tested using test sweep: `tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/pytorch_eltwise_logaddexp_test.yaml` 

Result will be saved in `./result-sweeps` folder

**Comment by npetrovic-tenstorrent** [comment]
Still failing due to low PCC

**Comment by umadevimcw** [comment]
@npetrovic-tenstorrent Same as https://github.com/tenstorrent-metal/tt-metal/issues/6392#issuecomment-2036703272

**Comment by umadevimcw** [comment]
Please find the updates here https://github.com/tenstorrent/tt-metal/pull/8054#issuecomment-2149565705
