### ISSUE TITLE
Have device system memory addresses be relative to their allocated hugepages

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent/tt-metal#4757]
Currently, the device system memory addresses are relative to the system memory base. This results in two problems:
1. Debuggability in multi-device tests will be very difficult since you now need to account for which hugepage a device is given to read from/write to, and manually subtract the offsets during your debug.
2. The fact that different devices can access another device's hugepages is worrisome. We can potentially corrupt another hugepage, or read something that we shouldn't have.

We need to brainstorm what we may need from either of/both of UMD and kernel land MMIO read/write API changes to find a way to interact with relative addresses.

**Comment by abhullar-tt** [comment]
For context this came up because we wanted to keep host and device command queue rd/wr pointers in sync. This was achieved by accounting for absolute offset in the pointers but this results in host having to update pointers to be relative to a specific hugepage
