### ISSUE TITLE
Add repeat_interleave

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#4761]
**Is your feature request related to a problem? Please describe.**
We need to be able to use repeate_interleave in the ttnn api to build stable diffusion models

**Describe the solution you'd like**
I need a fallback up to torch from ttnn for now and need subsequent work to actually implement this in ttnn properly

**Describe alternatives you've considered**
Converting to torch manually with unnecessary code.

**Additional context**
Please follow the description as defined [https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html)

```
tensor_2d = torch.tensor([[1, 2], [3, 4]])
result = torch.repeat_interleave(tensor_2d, 2, dim=0)
print(result)
# Result :
# tensor([[1, 2],
#         [1, 2],
#         [3, 4],
#         [3, 4]])
```

**Comment by jliangTT** [comment]
@arakhmati , this one is done right as we have provided the fall back for Boris.
