### ISSUE TITLE
Create new queue restart command which resets a command queue without putting a dispatch core into reset

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent/tt-metal#4815]
This new reset command will allow us to safely restart a command queue. This can be very useful for debug in case we believe we have any pointer issues, and will be used by trace to reset the command queue and write a custom issue/completion size.

**Comment by davorchap** [comment]
@pgkeller is there an equivalent / needed in FD2?

**Comment by pgkeller** [comment]
> @pgkeller is there an equivalent / needed in FD2?

this is potentially a good idea, self assigned.  basically we'd pass a command "reset" to prefetch and dispatch after a stall and they'd reset.  I'll self assign.  The other thing is that I hope FD2 is simple enough we don't have these issues too often...
