### ISSUE TITLE
MHA Tutorial Fails on WH for seq_len = 384

### ISSUE THREAD

**Issue by kevinmiTT11** [tenstorrent/tt-metal#4859]
**Describe the bug**
seq_len = 384 is handled in the code differently in ttnn/transformer.py:114
```
if input_tensor.shape == (batch_size, 384, 1024 * 3) and 7 <= batch_size <= 9 and kv_input_tensor is None:
        query_key_value = ttl.operations.primary.transformers.split_query_key_value_and_split_heads(
            ttl_input_tensor,
            ttl_input_tensor.device().compute_with_storage_grid_size(),
            memory_config,
        )
```
In multi_core_split_query_key_value_and_split_heads.cpp:56,
```
    // Parallelize ashape[2] (384 / 32 = 12 tiles) across columns
    // Parallelize ashape[0] (B) across rows
    uint32_t num_cores_x = ashape[2] / TILE_HEIGHT;
    uint32_t num_cores_y = ashape[0];
    TT_ASSERT(num_cores_x <= compute_with_storage_grid_size.x);
    TT_ASSERT(num_cores_y <= compute_with_storage_grid_size.y); 
```
num_cores_x is set to be parallelized for GS, and raises assert errors for WH  

Changing to a seq_len of less than 384 would make the tutorial work but longer seq_len has L1 memory allocations issues which overlaps with the circular buffers

**To Reproduce**
Use a wormhole_b0 device and run all previous cells until cell 14 in the notebook at ttnn/tutorial/003.ipynb

Change num_cores_x to be 8 to see this error.

**Expected behavior**
`An error occurred: TT_ASSERT @ tt_eager/tt_dnn/op_library/transformer_tms/multi_core_split_query_key_value_and_split_heads/multi_core_split_query_key_value_and_split_heads.cpp:58: num_cores_x <= compute_with_storage_grid_size.x`

**Comment by jliangTT** [comment]
@tt-rkim , how do we triage tutorial failure? The one we shipped with the OSS doc push?  Any idea?

**Comment by tt-rkim** [comment]
@jliangTT 
I think for the tutorials, we can assign ownership to the various teams.

1. Install and build - me
2. Falcon7B - models team (@boris-drazic + @farbabi )
3. ttnn MHA 1 - ttnn (@arakhmati )
4. ttnn MHA 2 - ttnn
5. matrix multiplication kernels - me + Metal team

And have them triage the failures.

For this specific bug, @kevinmiTT11 have you tried using a Grayskull accelerator?

Note that WH B0 is not a fully supported architecture. All of our features do not yet support Wormhole, as stated in the README.

We would likely update our tutorials to work with both architectures once ttnn has parity with WH.

**Comment by kevinmiTT11** [comment]
@tt-rkim I have not tried using a Grayskull to test but i think they would support it since its related to compute grid size.
