### ISSUE TITLE
dotproduct_tile compute API

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#4903]
* llk_unpack_AB + llk_reduce_tile(avg) could be modified to enable dot-product, both SRCA and SRCB tiles need to provided for every output. llk_reduce uses Tensix dot-product under the hood, and the constant is loaded to SRCB, just need to make sure that a new tile  loaded for every tile in SRCA.  

* this feature is needed for Depthwise convolutions (MobileNet V1 / V2)

**Comment by mbahnasTT** [comment]
MobileNetV2 Depthwise variants:
(0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (0): Conv2d(96, 96, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=96, bias=False)
          (0): Conv2d(144, 144, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=144, bias=False)
          (0): Conv2d(144, 144, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=144, bias=False)
          (0): Conv2d(192, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=192, bias=False)
          (0): Conv2d(192, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=192, bias=False)
          (0): Conv2d(192, 192, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=192, bias=False)
          (0): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=384, bias=False)
          (0): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=384, bias=False)
          (0): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=384, bias=False)
          (0): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=384, bias=False)
          (0): Conv2d(576, 576, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=576, bias=False)
          (0): Conv2d(576, 576, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=576, bias=False)
          (0): Conv2d(576, 576, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=576, bias=False)
          (0): Conv2d(960, 960, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=960, bias=False)
          (0): Conv2d(960, 960, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=960, bias=False)
          (0): Conv2d(960, 960, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=960, bias=False)

**Comment by mbahnasTT** [comment]
(32, 32, 112, 112, 3, 3, 1, 1, 1, 1, True)
(96, 96, 112, 112, 3, 3, 2, 2, 1, 1, True)
(144, 144, 56, 56, 3, 3, 1, 1, 1, 1, True)
(144, 144, 56, 56, 3, 3, 2, 2, 1, 1, True)
(192, 192, 28, 28, 3, 3, 1, 1, 1, 1, True)
(192, 192, 28, 28, 3, 3, 1, 1, 1, 1, True)
(192, 192, 28, 28, 3, 3, 2, 2, 1, 1, True)
(384, 384, 14, 14, 3, 3, 1, 1, 1, 1, True)
(384, 384, 14, 14, 3, 3, 1, 1, 1, 1, True)
(384, 384, 14, 14, 3, 3, 1, 1, 1, 1, True)
(384, 384, 14, 14, 3, 3, 1, 1, 1, 1, True)
(576, 576, 14, 14, 3, 3, 1, 1, 1, 1, True)
(576, 576, 14, 14, 3, 3, 1, 1, 1, 1, True)
(576, 576, 14, 14, 3, 3, 2, 2, 1, 1, True)
(960, 960, 7, 7, 3, 3, 1, 1, 1, 1, True)
(960, 960, 7, 7, 3, 3, 1, 1, 1, 1, True)
(960, 960, 7, 7, 3, 3, 1, 1, 1, 1, True)

**Comment by uaydonat** [comment]
we are tracking this for mamba prefill as well...

**Comment by rdjogoTT** [comment]
Support has been merged with https://github.com/tenstorrent/tt-metal/pull/7780. There is an example compute kernel in tt_eager/tt_dnn/op_library/dot_product/kernels/compute/dot_product_multi_core.cpp based heavily on the max pool kernel.

The implementation uses unpack_tilizeA_B like maxpool, with a matmul to compute the dot product, and a new pack_untilize.

 Input tiles to SrcB are expected to already be transposed (so that rows of SrcB dot product with cols of SrcA).
