### ISSUE TITLE
`CompileProgram` perf optimizations

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#4959]

**Comment by abhullar-tt** [comment]
During resnet perf optimization the op/program hash was uplifted from using strings but kernel compilation hash is still using string hash. 

relevant test for compile program: tests/tt_metal/tt_metal/test_compile_program.cpp

**Comment by DrJessop** [comment]
This should definitely speed up compilation
https://github.com/tenstorrent-metal/tt-metal/issues/4358

**Comment by TT-billteng** [comment]
fixed by @vtangTT
