### ISSUE TITLE
ttnn.matmul fails with Runtime Error for valid inputs

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent/tt-metal#5059]
**Describe the bug**
Encountering a runtime error when performing a matmul operation on tensors with shapes [1, 16, 77 + 19, 40 + 24] and [1, 16, 38 + 26, 72 + 24]. The original shapes of the input tensors are (1, 16, 77, 40) and (1, 16, 38, 72). After converting the tensors to tile layout, their shapes become [1, 16, 77 + 19, 40 + 24] and [1, 16, 38 + 26, 72 + 24]  which are valid inputs for matmul. However, using these tile-layout tensors in the matmul operation results in a runtime error."

**To Reproduce**
Run the following unit test to reproduce the error
```

def test_unit_test(device):
    tensor_a = torch.randn([1, 16, 77, 40])
    tensor_b = torch.randn([1, 16, 38, 72])    

    tensor_a = ttnn.from_torch(tensor_a, dtype=ttnn.bfloat16)
    tensor_a = ttnn.to_layout(tensor_a, ttnn.TILE_LAYOUT)
    tensor_a = ttnn.to_device(tensor_a,device)
    

    tensor_b = ttnn.from_torch(tensor_b, dtype=ttnn.bfloat16)
    tensor_b = ttnn.to_layout(tensor_b, ttnn.TILE_LAYOUT)
    tensor_b = ttnn.to_device(tensor_b,device)

    result = ttnn.matmul(tensor_a, tensor_b)

```

**Screenshots**
Error log:
```
        if width_a != height_b:
>           raise RuntimeError("The width of the first tensor must be equal to the height of the second tensor")
E           RuntimeError: The width of the first tensor must be equal to the height of the second tensor

ttnn/ttnn/operations/matmul.py:199: RuntimeError
======================================================= short test summary info =======================================================
FAILED tests/ttnn/integration_tests/stable_diffusion/test_matmul2.py::test_unit_test - RuntimeError: The width of the first tensor must be equal to the height of the second tensor

```

**Comment by TT-BrianLiu** [comment]
What are the shapes that matmul sees after padding?

**Comment by Sudharsan-V** [comment]
Initial input shapes: [1, 16, 77, 40] and [1, 16, 38, 72]
After changing it to TILE LAYOUT: [1, 16, 77 + 19, 40 + 24] and [1, 16, 38 + 26, 72 + 24]

Note: We are not explicitly using a pad here when the layout is changed to TILE, the tensors are padded implicitly, and the shape changes.

**Comment by TT-BrianLiu** [comment]
@eyonland @arakhmati Can you comment on this? For `ttnn.matmul`, are users expected to pad to appropriate shapes or does it support padded up shapes when we convert to ttnn tensors? My guess is the shapes are padded up so we can have them as TILE layout on device, but the actual shape under the hood is still the original shape.

**Comment by bbradelTT** [comment]
@Sudharsan-V 
The initial input is invalid. Specifically the inner dimension needs to match between the two tensors:
Initial input shapes: [1, 16, 77, 40] and [1, 16, 38, 72]

40 != 38
The initial input shapes need to be either [1, 16, 77, 38] and [1, 16, 38, 72] or [1, 16, 77, 40] and [1, 16, 40, 72].

**Comment by Sudharsan-V** [comment]
@bbradelTT
I agree that the initial input shapes are invalid. However, after converting the inputs to the TILE layout, the shapes become [1, 16, 77 + 19, 40 + 24] and [1, 16, 38 + 26, 72 + 24]. Since (40 + 24) equals (28 + 26), the shapes are valid, correct?

Please correct me if I am wrong, but it appears that during the conversion from ROW_MAJOR to TILE_LAYOUT, some elements are added to the last two axes(if required). These elements seem to facilitate storing the tensor in TILE_LAYOUT on the device but do not actually participate in the execution.

**Comment by bbradelTT** [comment]
> @bbradelTT I agree that the initial input shapes are invalid. However, after converting the inputs to the TILE layout, the shapes become [1, 16, 77 + 19, 40 + 24] and [1, 16, 38 + 26, 72 + 24]. Since (40 + 24) equals (28 + 26), the shapes are valid, correct?
> 
> Please correct me if I am wrong, but it appears that during the conversion from ROW_MAJOR to TILE_LAYOUT, some elements are added to the last two axes(if required). These elements seem to facilitate storing the tensor in TILE_LAYOUT on the device but do not actually participate in the execution.

The underlying shapes do not become [1, 16, 77 + 19, 40 + 24] and [1, 16, 38 + 26, 72 + 24]. The underlying shapes are still [1, 16, 77, 40] and [1, 16, 38, 72].

You are correct that the tensor is layed out in memory to align at 32 element boundaries for storage purposes. Hence, the notation [1, 16, 77[96], 40[64]] and [1, 16, 38[64], 72[96]].

However, matmul requires the underlying shapes to match.

**Comment by Sudharsan-V** [comment]
@bbradelTT , Thanks for the clarification.
We can close this issue now.

**Comment by bbradelTT** [comment]
Great. Thanks.
