### ISSUE TITLE
yolo v4 conv ops bringup

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#5079]
**Describe the bug**

1. Some conv variants with **groups=1** for yolov4 are failing. (12 failed, 113 passed) on resolution 480x640! 

2. Please note, we also need to add support for groups>1 for 46 of the convs in YOLOv4.  (46 failed) [add support for groups>1](https://github.com/tenstorrent-metal/tt-metal/blob/dvartanians/yolov4/ttnn/ttnn/operations/conv2d.py#L80)

Please **prioritize** enabling groups>1 as the failing groups==1 tests are passing on lower resolution 240x320! [groups>1 separate issue: 6580](https://github.com/tenstorrent-metal/tt-metal/issues/6580)
We eventually need to go as high as 960x 1280 resolution. But to expedite bringup process we can start with the lower-resolutions.

**To Reproduce**
from [dvartanians/yolov4](https://github.com/tenstorrent-metal/tt-metal/tree/dvartanians/yolov4) run: `pytest tests/ttnn/unit_tests/operations/test_conv2d.py::test_yolov4_conv`

I also have a separate test for the groups > 1 convs for whenever we add support for it. you may run: `pytest tests/ttnn/unit_tests/operations/test_conv2d.py::test_yolov4_conv_groups_larger_than_one`

**Expected behavior**

1. figure out the sharding configs or other parameters that would pass the failing conv tests for groups=1.
2. figure out the optimal sharding configs that pass for the convs ideally we would like all convs to pass with block sharding or atleast minimal reshards in between the convs. 
3. add support for groups>1 convs. 
4. make all convs with groups>1 pass.
5. make them pass with the most optimal configs.  

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- [dvartanians/yolov4](https://github.com/tenstorrent-metal/tt-metal/tree/dvartanians/yolov4) commit: 50c10d20d2210eb9592117fd92158b5370238595 

**Additional context**
customer feature!

**Comment by jliangTT** [comment]
Assigning to @nsmithtt to triage - putting this as p2 while we discuss the priority of these items offline.

**Comment by dvartaniansTT** [comment]
I understand there are several asks in this one. I will make a separate issue for convs with groups > 1 and link it to this one.

**Comment by jliangTT** [comment]
@nsmithtt , should this land in the conv generality bucket?

**Comment by mywoodstock** [comment]
@dvartaniansTT are these still relevant? perhaps makes sense to try out with the latest conv version?

**Comment by saichandax** [comment]
@mywoodstock , we'll look on this and let you know if this is still relevant. Some of the issues have been addressed as we already ported to new Conv API.
We will check the relevance and close in the next week.
Thanks.

**Comment by mywoodstock** [comment]
@saichandax Any update on this one?

**Comment by mywoodstock** [comment]
I believe this can be closed? @dvartaniansTT

**Comment by dvartaniansTT** [comment]
@mywoodstock let me have a final check with MCW and will update here. thanks for your patience on this

**Comment by punithsekar** [comment]
@dvartaniansTT, the version of yolov4 which we use reference, https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/master/models.py, doesn't need group>1 need. Our input resolution of yolov4 was 320x320. For that resolution, the model works fine and we have merged it into the main. Once you acknowledge this comment we can close this issue Dalar.

CC: @saichandax
