### ISSUE TITLE
Update UNRESERVED_BASE to be right after the NCRISC/BRISC args

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#51]
`constexpr static std::uint32_t UNRESERVED_BASE = 200 * 1024; // Start of unreserved space
`

we should check for CBs and L1 Buffers.
Currently it check only for L1Buffers

**Comment by davorchap** [comment]
@abhullar-tt and @pgkeller we can close this one?

**Comment by pgkeller** [comment]
not sure of the current state.  the memory map work is not finished, ideally this would be a floating value based on the map and not a fixed value "at some distance" from the last address.  I'd leave it open to be investigated

**Comment by pgkeller** [comment]
closing - is irrelevant w/ new memory map that is unfolding
