### ISSUE TITLE
Update existing sharded ops to either assert or verify/work with passed in sharded memconfig

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#5101]
Since shardspec is a part of memconfig now, most ops are just asserting the memory layout (ie. height, width, block sharding) are the same/expected between input/outputs etc.

They currently ignore any potentially passed in shard spec, which is not ideal since users would expect their passed in scheme to be used.

Should either add asserts for no specified shard spec, or update existing ops to verify/use the passed in scheme.

**Comment by TT-BrianLiu** [comment]
I think we should review what happens when user pass in shard spec with sharded memconfig in general. Let's open issue later.
