### ISSUE TITLE
Outstanding sharding work for LLMs

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#5133]
- [ ] Integrate sharded Unpad/Slice
- [x] #4641  
    * LayerNorm -> Reshard -> MM 
    * MM -> Reshard -> CreateHeads
- [ ] Sharded AllGather
    * Is it easier to optimize the current interleaved AllGather or the sharded AllGather?

**Comment by tt-aho** [comment]
Closing since these can/are tracked in separate issues.
