### ISSUE TITLE
TTNN linear with or without bias output is the same

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#5237]
**Describe the bug**
The output of TTNN linear op is the same with or without bias. 

**To Reproduce**
1. Go to [dvartanians/ttnn_ops_issues](https://github.com/tenstorrent-metal/tt-metal/tree/dvartanians/ttnn_ops_issues)
2. from metal root directory run "python tests/ttnn/quick_tests/test_linear.py"
4. We expect output_1 and output_2 to be different but they are the same. 

**Expected behavior**
Adding a bias to the linear should change the output

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software: commit 8316cf1e8c54c982c5fcaa9be073d28de00f33a7

**Comment by dvartaniansTT** [comment]
@TT-BrianLiu I see this issue is assigned to you. Have you had a chance to look at it? cc: @mbahnasTT

**Comment by TT-BrianLiu** [comment]
i will take a look

**Comment by mbahnasTT** [comment]
Thanks @TT-BrianLiu !
