### ISSUE TITLE
ttnn.linear does not support core grids equal to 1  

### ISSUE THREAD

**Issue by djordje-tt** [tenstorrent/tt-metal#5274]
**Describe the bug**
ttnn.linear fails when either or both of its arguments are equal to 1. 
Assert error `mcast_in0 is not implemented yet.`

**To Reproduce**
1. Go to https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/converting_torch_model_to_ttnn.html
2. Reproduce run for optimized model (step 3)
3. `pytest -s ttnn_optimized_functional_bert.py::test_bert_intermediate[sequence_size=384-batch_size=1-model_name=phiyodr/bert-large-finetuned-squad2]`

**Expected behavior**
Expected passed test with output of ttnn.Linear

**Observed behavior**
```
RuntimeError: TT_ASSERT @ tt_eager/tt_dnn/op_library/bmm/multi_core_reuse_mcast_2d_optimized/bmm_op_multi_core_reuse_mcast_2d_optimized.cpp:964: false
E               info:
E               mcast_in0 is not implemented yet.
```
Full output log here: [output_error.log](https://github.com/tenstorrent-metal/tt-metal/files/14227314/output_error.log)

- OS: Ubuntu 20.04.6 LTS
- Device: Grayskull

**Comment by bbradelTT** [comment]
@djordje-tt the files for steps to reproduce seem to not exist anymore, and we made changes recently that will have already fixed this issue.

Could you please
- provide new steps to reproduce or
- check that the issue does not occur again?

**Comment by bbradelTT** [comment]
@djordje-tt I think this works now. Example code below. Could you please confirm?

Then I can close this issue.

```
import torch
import ttnn
import time
device_id = 0
device = ttnn.open_device(device_id=device_id)
a=ttnn.from_torch(25*torch.ones([1,1,32,32], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
b=ttnn.from_torch(125*torch.ones([1,1,32,32], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
c = ttnn.matmul(a,b)
d = ttnn.linear(a,b)
ttnn.close_device(device)
```

using
```
a=ttnn.from_torch(torch.ones([1], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
b=ttnn.from_torch(torch.ones([1], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
```
or
```
a=ttnn.from_torch(torch.ones([1,1], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
b=ttnn.from_torch(torch.ones([1,1], dtype=torch.bfloat16), layout=ttnn.TILE_LAYOUT, device=device)
```
also works.

**Comment by bbradelTT** [comment]
I'll close this for now. @djordje-tt please re-open with reproduction steps if this is still an issue.

**Comment by djordje-tt** [comment]
Hey, @bbradelTT sorry for late reply. I was on vacation. I agree with closing issue if you verified it's not an issue anymore!
