### ISSUE TITLE
Switch to performance cpu freq governor (benchmarks unpredictable due to ondemand governor)

### ISSUE THREAD

**Issue by olofj** [tenstorrent/tt-metal#5281]
Per discussion on Slack today, the performance benchmarks aren't showing up very predictably, and there were reports of performance getting better if the CPU is first made busy. It's a typical behavior when the `ondemand` cpufreq governor is in place, since CPU frequency will be lowered when the system goes idle, and not jump up immediately when the load comes back.

For benchmarking, this is obviously undesireable. But it's also not ideal to just always run the machine flat out (heat and power consumption being the obvious factors, but fan noise, etc, comes into play too).

I just posted the following on the group chat we had:

Ok, so it seems like the best package to use for this is probably cpupower-gui (on Ubuntu). So, apt-get install cpupower-gui.
That brings you a couple of commands. To get back to baseline after a change/run:

```
sudo cpupower set -g ondemand
```
To set performance governor:
```
sudo cpupower set -g performance
```

Since they need sudo, you might need/want to setup a passwordless single-command sudo rule for the CI user, since I hope your CI doesn't run as root.

I'm wondering if it makes sense to run those changes outside of the main benchmark/CI script. I.e. to do it in the surrounding CI / github workflow instead.

@tt-rkim, I'm guessing wrapping the call of run_tests.sh here with the above cpupower commands would be a likely thing to do: https://github.com/tenstorrent-metal/tt-metal/blob/d97c054e3079749e25a3e5d8109889067452a610/.github/workflows/perf-device-models.yaml#L42

**Comment by davorchap** [comment]
Amazing, thanks @olofj

**Comment by tt-rkim** [comment]
@tt-aho Should we first try this out on device perf pipeline machine? wdu think

**Comment by olofj** [comment]
Per slack discussion, since the perf benchmarks are run on a consistent set of machines, the simplest and easiest change would be to keep those persistently on the performance governor. I was of the impression that the problem was more widespread, and for the general solution we'll want something that bumps governor before the benchmark is ran, then drops it back down.

**Comment by olofj** [comment]
(For system-wide setup, there are system config files to set the defaults. CHeck the docs for cpupower-gui, there might even be existing ansible roles).

Internally we install cpufreq-utils and set it through there, but it seems to be an older package and cpupower is newer. I'll send you a link to those ansible roles, Raymond

**Comment by tt-rkim** [comment]
Will incorporate ansible role to use in our internal workflows.
Default should be `ondemand` - not `performance`

cc: @tenstorrent-metal/dev-ops-infra

**Comment by tt-rkim** [comment]
@TT-billteng this is also a todo for the any current and future perf machines for models

**Comment by tt-rkim** [comment]
@TT-billteng @tapspatel @jliangTT
An old issue, but still important. This will give more consistency and a big perf bump to our E2E pipeline.

We should make use of buda dev infra's playbook. @ttmchiou 

We should do this after the FD2 merge in order to minimize noise for them for now.

The plan will probably be someone will have to take the joy of running tests on it after changing the cpu governor and seeing what the new numbers are.

**Comment by davorchap** [comment]
Elevating to P0.

FD2 has been merged, and the team will now focus on end2end performance across the board, and noisy and low perf benchmarking will impede the team progress. 

Also, On Llama3-70B "ondemand" is 2x slower than "performance", so in addition to very large noise, we're seeing big perf difference.

**Comment by TT-billteng** [comment]
Machines that run multi-chip and single chip perf pipelines have been updated with cpu freq governor
