### ISSUE TITLE
Enforce code style described in `.clang-format` during CI pipelines

### ISSUE THREAD

**Issue by esmalTT** [tenstorrent/tt-metal#5301]
# Summary

Enforcing a common C++ code style across the entire `tt-metal` repository will [improve code readability](https://abseil.io/resources/swe-book/html/ch08.html) which should improve development velocity in the long term. Secondarily, this can also improve the external perception of `tt-metal` in the OSS community since enforcing common code style is considered an industry best practice. 

Currently, there is a style guide formalized as a `.clang-format` configuration file, but it is not enforced by any automated or manual process.

See the initial discussion on Slack [here](https://tenstorrent.slack.com/archives/C03N2GED3PS/p1707670509723669).

# Possible Solution

Our solution has the following requirements:

- It should avoid disrupting ongoing development with a large PR that reformats all of the C++ in the repository at once
- It should make sure future changes conform to the `.clang-format` style guide

To accomplish this I propose a script that can be run in CI or locally. This script would wrap running `clang-format` across the code repository,  targeting either all source files within the repository or only those modified (when comparing to the master branch using something like `git diff --name-only $(git merge-base origin/master HEAD)`), with an option to automatically fix formatting issues if specified. 

The usage would be something like:

```sh
./lint-clang-format.sh [-m <diff|all>] [-f]
```

- `-m <diff|all>`: Select mode to run formatter over all files (all) or just modified ones (diff).
- `-f`: If present, the script will attempt to fix all issues automatically.

Once this script is in the repository and confirmed to be working properly, we would need to do the following:

1. Add `clang-format` to IRD containers, and CI environment. 
2. Add a pipeline stage that should run on every branch that invokes the script above to check if modified code complies with style guide

The main advantage to this solution is it can be gradually rolled out, without disrupting day-to-day development. Over time the repository will become more and more consistent. The downside is that code formatting changes may be noisy for reviewers, and some files that are very rarely (or never!) changed will never become reformatted.

Here's a prototype of the script described above: [esmal/lint-clang-format](https://github.com/tenstorrent-metal/tt-metal/blob/esmal/lint-clang-format/scripts/lint_clang_format.sh)

**Comment by razorback3** [comment]
Is this working right now?
I see that there are many files in the main branch that are not following pre-defined clang-format style.

Or, may be we could add clang-format to run in pre-commit hook.
(cc. @mrshaw01, @o2buzzle )

**Comment by o2buzzle** [comment]
I hope I am not necroposting here, but the easiest and most straight-forward solution is to use this hook with pre-commit: https://github.com/pre-commit/mirrors-clang-format

**Comment by zzigler-tt** [comment]
@esmalTT Can we place this bug in the appropriate dashboard with a set priority and team labelling?

**Comment by ayerofieiev-tt** [comment]
@bkeith-TT

**Comment by esmalTT** [comment]
Closing since this has been addressed
