### ISSUE TITLE
Allocate CQ buffers in the non-default direction

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent/tt-metal#5358]
Currently, when we allocate program buffers, we just grow in the default DRAM buffer direction. This is not good, since we are sharing space with tensors and we can get holes between buffers.

Ideally, we'd want to grow our program/trace buffers from the other direction to ensure that they are contiguous/no holes. This would require exposing an extra param that specifies from which direction we want to grow the buffer.

**Comment by abhullar-tt** [comment]
@tt-aho @davorchap  this would address the issue with the move op in dram if we allocate program binary buffers / trace buffers top down in dram

**Comment by abhullar-tt** [comment]
yeah that case can still be hit
