### ISSUE TITLE
Remove hf_modeling_falcon.py

### ISSUE THREAD

**Issue by cfjchu** [tenstorrent/tt-metal#5386]
After merging in https://github.com/tenstorrent-metal/tt-metal/pull/5360, we should have Falcon models in the transformers package accessible. Just adding a cleanup task to purge `models/demos/falcon7b/reference/hf_modeling_falcon.py` and  instead reference Falcon classes directly through transformers lib.

fyi @skhorasganiTT

**Comment by tt-aho** [comment]
I saw the transformers update was reverted in https://github.com/tenstorrent-metal/tt-metal/commit/d38a22c3cf53f8824f676f18b7fd428b921a24a9.

Are we still trying to switch to newer version with falcon?

**Comment by tt-aho** [comment]
This branch updates Falcon40B to use Falcon from latest Transformers. This also updates to latest PT but no regression testing has been done on the branch so far to see if this breaks anything.
@TT-BrianLiu do you want to update Falcon7B on this branch, test and merge?
https://github.com/tenstorrent-metal/tt-metal/tree/aho/falcon-40b-transformers-uplift

**Comment by cfjchu** [comment]
fyi @skhorasganiTT
