### ISSUE TITLE
Add perf_file for functional Stable Diffusion model

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent/tt-metal#5408]
Add test_perf_mistral file for functional_stable_diffusion and profile the inference and compile time for the model.

**Comment by vigneshkeerthivasanx** [comment]
perf_file for  functional Stable Diffusion model is completed.
Commit: [Link](https://github.com/tenstorrent-metal/tt-metal/compare/vignesh/stable_diffusion_ttnn_test_perf)

**Comment by vigneshkeerthivasanx** [comment]
PR is updated with test_perf for 512x512.

With conv_on_device and without any optimization

- Compile time: 127.29490804672241
- Inference time: 166.16328954696655
- Samples per second: 0.006018176474036084


With text_embedding and pre-process parameters outside the loop and conv_on_device

- Compile time: 113.44756436347961
- Inference time: 169.08252477645874
- Samples per second: 0.005914271751750122


In the current PR the pre-processing is happening in inside the loop as we need to make changes in the sub-modules which is using using conv weights.

**Comment by vigneshkeerthivasanx** [comment]
- The PR has been updated by adding the **test_performance.py** file for stable_diffusion model in `tests/scripts/run_performance.sh`.
- We are skipping this test on WH as we are facing hang issue while testing.

**Comment by vigneshkeerthivasanx** [comment]
The PR has been updated with the test_performance file which currently uses `models/experimental/functional_stable_diffusion/tt2.` along with all the scheduler functions being used in ttnn

**Comment by Sudharsan-V** [comment]
The performance file for the ttnn stable diffusion model has been updated to include the on-device scheduler. Now, the entire denoising loop takes place on the device.
Corresponding PR: https://github.com/tenstorrent-metal/tt-metal/pull/5477

Performance number with on-device scheduler:
```
Compile time: 100.23629236221313
Inference time: 58.65621852874756
```
Performance number with torch scheduler
```
Compile time: 101.0598566532135
Inference time: 63.51971173286438
```

**Comment by Sudharsan-V** [comment]
PR [#5477](https://github.com/tenstorrent/tt-metal/pull/5477) is closed.
SD is merged with main.
Hence closing this ticket.
