### ISSUE TITLE
[Minor Bug] log_trace implementation inconsistency

### ISSUE THREAD

**Issue by tooniz** [tenstorrent/tt-metal#5413]
**Describe the bug**
log_trace is a function in debug build, but it's a macro in release build

```
#ifdef DEBUG
template <typename... Args>
static void log_trace_(LogType type, std::string const& src_info, char const* fmt, Args&&... args) {
    Logger::get().log_level_type(Logger::Level::Trace, type, fmt, src_info, std::forward<Args>(args)...);
}
...
#else
#define log_trace(...) ((void)0)
#endif
```

**To Reproduce**
That can set up a bad user experience when people type the following code
```
tt::log_trace(tt::LogAlways, "Hello Metal!");
```
It compiles fine except for CONFIG=release, `tt::` scope no longer makes sense since macros are global and you hit a compile error

**Expected behavior**
I suggest moving to macros for all logging functions. 

For functions arguments expressions need to be evaluated at the call site, and then internally discarded when runtime check on verbosity deems the message needs to be filtered out. _Performance is still bad when you specify LOGGER_LEVEL=NONE since argument expression eval takes time._

For macros, arguments as passed into it verbatim, the runtime check on verbosity occurs first before the argument expression are evaluated. _Performance is better when you properly specify LOGGER_LEVEL=NONE_

Another minor perf note: we only compile out log_trace under CONFIG=release, we should be using this more instead of log_debug unless we compile out log_debug as well.

**Comment by tooniz** [comment]
Filing under Bill and David since they are responsible for dev infra and debug, feel free to re-assign.

This is low priority

**Comment by pgkeller** [comment]
pretty sure this is no longer an issue (since we build release and have trace logging)
