### ISSUE TITLE
Allow RuntimeArgs to be multicasted to device instead of unicast for CoreRange

### ISSUE THREAD

**Issue by kmabeeTT** [tenstorrent/tt-metal#5484]
From talking to @pgkeller  last week, there is desire to "optimize runtime args", specifically:

1. Allow tests/modules to specify common runtime args sets that apply to multiple cores
2. use noc multicast instead of unicast for the common set of runtime args when writing to eth/tensix cores, to reduce latency

There is also task/goal to have models updated to use this, but that is kind of separate from the funcionality here, and can be done after.

From host API perspective bullet-1 is already ~solved since `SetRuntimeArgs()` already has a variant that takes `CoreRange` and `CoreRangeSet` (compared to basic `CoreCoord` version, ie called per core) alongside a vector of runtime args.  Under the hood it is not ideal, since they are treated the same way as `CoreCoord` version (for loop to blast out calls to `Kernel::set_runtime_args()` per core), but bullet 2 will address that.

For bullet-2, I looked into code last week during ramp up, and see that for Fast Dispatch we have a bunch of transfer pages for host->device data already setup via `ConstructProgramDeviceMap()` at compile time, for unicast and multicast flavors of pages (including runtime args, unicast only), so I made some changes here that basically do the following:

- propagate the `CoreRange` down to the call of `Kernel::set_runtime_args()` and lower code, and treat that as a "runtime args group" for potential multicasting.
- When a `CoreRange` is given and destination is`WORKER` core type (not `ETH`), setup a noc-multicast, otherwise setup a noc-unicast like before.  Update a few maps to have unicast and multicast flavors for runtime args, like is already done for go-signals, etc.
-  Tiny change in FD dispatch kernel to be aware of 2 flavors of runtime args `DeviceCommand::TransferType::RUNTIME_ARGS_MULTICAST` and `DeviceCommand::TransferType::RUNTIME_ARGS_UNICAST` 

With these changes, it seems to "just work" (some functional tests passing, perf improvements seen), although I have some FIXMEs, and issue about how to handle case when `SetRuntimeArgs()` is called multiple times for the same CoreRange, which seems like something that would have been supported before.

Some data going from previous unicast to new multicast in this microbenchmarking test after updating it:

```
     - Reduces dispatch time from test_pgm_dispatch.cpp from:

        36.9us -> 9.6us (64 cores, 128 rt args to 3 procs)
        24.6us -> 8.8us (64 cores, 128 rt args to 3 procs)
        13.5us -> 8.8us (64 cores, 32  rt args to 3 procs)
        12.7us -> 8.5us (64 cores, 1   rt args to 3 procs)
```

Let me know if I missed something here.  Don't have a design spec since this was relatively simple, and the host API is not changing (was already made).  FYI @DrJessop

**Comment by pgkeller** [comment]
stale, closing (can open new if/when)
