### ISSUE TITLE
Investigate hangs on fast dispatch ethernet unit tests

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#5595]
Reported by @TT-billteng 

We're seeing this non-deterministic issue where the EthKernelsDirectRingGatherAllChips test just hangs like this

https://github.com/tenstorrent-metal/tt-metal/actions/runs/8010264348/job/21890233060

and it's not immediately clear what's going on. It's likely because we're not upgrading to the latest open source tt-smi with new updates for ethernet reset.

We'll be looking into upgrading the runners today or early next week.

cc: @aliuTT @tapspatel

**Comment by TT-billteng** [comment]
Haven't seen it recently, but should keep an eye if this one shows up again

**Comment by tt-rkim** [comment]
Same, and hopefully new SMI helps out with this

**Comment by TT-billteng** [comment]
seems to be fixed, re-open if needed
