### ISSUE TITLE
Stable Diffusion e2e WH

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-metal#5606]
FYI @AleksKnezevic

**Comment by AleksKnezevic** [comment]
@boris-drazic what's the current status of SD on WH?

**Comment by boris-drazic** [comment]
@AleksKnezevic single iteration of UNet is giving good PCC (0.99) on WH and MCW is running multiple iterations to see images produced on WH. So far they seem to look good.

**Comment by boris-drazic** [comment]
No, this is with fallback convs. We need to collect numbers for convs on device.

**Comment by tapspatel** [comment]
closing issue as completed per @AleksKnezevic
