### ISSUE TITLE
Possible Sharding Hang on WH

### ISSUE THREAD

**Issue by ntarafdar** [tenstorrent/tt-metal#5636]
Not sure about the resolution on https://github.com/tenstorrent-metal/tt-metal/issues/4392

in test_sharded.py there are several sharding tests that are disabled for WH labelling this issue as the reason. 
With us getting a sprint on getting more models working in WH, its possible that we see this issue show up.

Want to investigate this sharding hang specifically in WH (even in single chip, has nothing to do with multi-chip workloads). 

Will take feedback on whether this should be P1 or P2 (since we are not sure yet if it will show up in key models)

CC: @eyonland

**Comment by jliangTT** [comment]
Agree this should be P1 if it is a hang in WH. But i cannot make out who to triage this to. Please ask in the slack channel: [#tt-metal-kernel-dev](https://tenstorrent.slack.com/archives/C06LM4T7JDP), or #tt-metal-issue-triage to identify owner. (c.c. me is okay)

**Comment by jvasilje** [comment]
9 month old bug.

**Comment by ntarafdar** [comment]
sorry forgot to close, these tests are no longer skipped and is not an issue anymore
