### ISSUE TITLE
Falcon40B end-to-end demo on T3000 4/8 chips

### ISSUE THREAD

**Issue by TT-BrianLiu** [tenstorrent/tt-metal#5639]
TODOs:

Part 1: Decode
- [x] Switch matmuls to use fp32 and L1 accum (also update PCCs for all unit/model tests)
- [x] Remove masking of last token in attention mask (doesn't really affect PCC or performance, but it's good to fix)
- [x] Add placeholder for model config for 4 chips (eventually support 8 chips)
- [x] Demo script with prefill on host + decode on device

Part 2: Prefill
- [x] Update fill cache op to support sharded input, multiple kv heads. Need to update interleaved to split work along width so logic is simpler for sharded input. This follows what update cache for decode does. (Attention)
- [x] Update MLP and MLP tests for prefill
- [x] Update decoder and tests for prefill
- [x] Update model and tests for prefill
- [x] Update causal_lm and tests for prefill
- [x] Update end-to-end test for prefill
- [x] Update perf script for prefill. Reporting `promts_per_s_per_user` instead of tokens.

Found some issues related to sharding for HEIGHT > 32, so this blocks bringing up prefill with seq_len > 32. Need to debug and revisit:
- [ ] Try out prefill with 8 chips
- [ ] Debug issues with sharded APIs for shard height > 32
- [ ] Update `nlp_create_qvk_heads` to suppport HEIGHT > 32 for sharded inputs. This wasn't needed because prefill only supports up to `seq_len` 32 for now.

**Comment by jliangTT** [comment]
this one seems to be on the model side. will remove it from the kernel board for now.
