### ISSUE TITLE
Backwars ops for Pow

### ISSUE THREAD

**Issue by umadevimcw** [tenstorrent/tt-metal#5642]

**Comment by KalaivaniMCW** [comment]
binary power operation of two tensors _pow(input, exponent)_ is not currently not supported, exponent is expected to be either int or float only. But it is required for the grad calculation. 
grad_input = grad * exponent * input**(exponent - 1)
grad_exponent = (grad * input**exponent) * torch.log(input)

**Comment by umadevimcw** [comment]
Closing based on discussion decided to use pow module with tensor input and float/int exponent
