### ISSUE TITLE
[TM op] Requesting Q transpose and pad op

### ISSUE THREAD

**Issue by cglagovich** [tenstorrent/tt-metal#5709]
This issue describes the new split_heads op which the models team is requesting.

Given the current state of things:
```python
(
    q_heads,  # [seqlen, n_local_heads, bsz, head_dim]
    k_heads,  # [seqlen, n_local_kv_heads, bsz, head_dim]
    v_heads,  # [seqlen, n_local_kv_heads, bsz, head_dim]
) = tt_lib.tensor.nlp_create_qkv_heads(
    fused_query_key_value[i], # [seqlen, 1, bsz, head_dim*total_num_heads]
    num_heads=self.n_local_heads,
    num_kv_heads=self.n_local_kv_heads,
    transpose_k_heads=False,
    output_mem_config=self.model_config["CREATE_QKV_HEADS_OUTPUT_MEMCFG"],
)
```

We want a new op which splits heads but outputs Q with dims (1,2) transposed, so the new shape should be `[seqlen, bsz, n_local_heads, head_dim]`. `n_local_heads` will usually not be divisible by `TILE_DIM`, so this op will have to pad to tile size as it transposes. 

The Q output should be 
- height sharded such that `bsz` is sharded across cores
- tilized
- bfloat16_b

 
Here is an example of the pad/transpose pattern using supported ops.
```python
q = tt_lib.tensor.pad(q, [1, N_HEADS_PADDED, BATCH, HEAD_DIM], [0, 0, 0, 0], 0.0)

q = tt_lib.tensor.transpose(q, -2, -3)

q = tt_lib.tensor.interleaved_to_sharded(
    q,
    sharded_mem_config=q_mem_config,
)
```

### Example input sizes
```python
fused_qkv: [1, 1, 32, 1280] # Width sharded on 8 cores
```

We need our new `nlp_create_qkv_heads` to execute on an input of this size in about `10 us`. 

# TODO
- [ ] Define specs for the inverse concat_heads op

**Comment by cglagovich** [comment]
@uaydonat @TT-BrianLiu @tarafdarTT

**Comment by uaydonat** [comment]
Does not seem critical for perf, TM ops are only a few percentages of the overall device perf, lowering priority.

**Comment by cglagovichTT** [comment]
We implemented this ourselves - closing
