### ISSUE TITLE
Re-work split reader implementation to read activations in parallel

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-metal#5713]
Re-work split reader implementation to read activations in parallel into the same CB. This will prevent this hard constraint - (act_block_h / out_subblock_h) % 2 == 0. Currently, activations are split at the subblock granularity and activations are split into 2 CBs. The compute waits and pops from 2 cbs which is not necessary.

**Comment by tt-nshanker** [comment]
![image](https://github.com/tenstorrent-metal/tt-metal/assets/109384087/4284f18e-8ea0-4b6c-8a42-a563d7909c63)

**Comment by mywoodstock** [comment]
@yugaoTT with the uneven reading, this constraint is no longer there `(act_block_h / out_subblock_h) % 2 == 0`, right?

**Comment by yugaoTT** [comment]
yes that's right

**Comment by mywoodstock** [comment]
cool. Closing this then.
