### ISSUE TITLE
Investigate Resnet Perf Drop

### ISSUE THREAD

**Issue by tarafdarTT** [tenstorrent/tt-metal#5728]
After: https://github.com/tenstorrent-metal/tt-metal/pull/5613

There was a drop in resnet perf for batch 20, where the threshold was increased from 0.015 to 0.0185, there are sometimes fails within noise now.

The previous PR is mostly unrelated to resnet except for the few lines related to the formation of the buffer mappings.
Previously this was incorrect where the logic would not work for certain sizes (width and height of tensor shapes were mixed up, and is assuming all shards to have the same size).

Code in main prior to this change, is functionally incorrect but due to limited testing on shard sizes this was not caught. 

This assumption was fixed and tests in resharding exposed issues with the logic. 

This performance drop should be explored.

CC: @tt-nshanker , @mywoodstock @TT-billteng @tt-rkim

**Comment by mywoodstock** [comment]
@tarafdarTT I believe this is no longer valid? If so can you please close?
