### ISSUE TITLE
TTNN RN50 on GS: Improve perf to be on par with TTLIB RN50

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#5730]
RN50 with TTNN runs e2e when tensors are in DRAM.
This effort is to make everything run with sharded using the same parallel config as much as possible, and get the performance at par with the TTLIB resnet50.

old stuff:

With fully sharded tensors, Downsample fails with L1 fitting issue. There seems to be fragmented memory. Using `reallocate`/`sharded_move` does not help.
Moving output of conv before downsample to DRAM bypasses the issue for now.

Branch: `asarje/shwetankTT/resnet`
Test: `pytest tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet.py::test_resnet`

**Comment by jvasilje** [comment]
so far @mywoodstock has ResNet50 fps = 1000. 
This reallocate is the blocker for improving perf. 
help?

**Comment by eyonland** [comment]
My take on this issue is that need to track the allocations of the tensors on the device and keep their offsets as the model is running.  With this information it will become obvious where we need to reallocate/deallocate.   At the moment folks are having to guess at where this needs to be done.  Can we flip this bug to a feature request and get this going on the next sprint?

**Comment by eyonland** [comment]
@abhullar-tt , is it possible to easily track the allocations and deallocations here?

**Comment by abhullar-tt** [comment]
we have `tt_lib.device.EnableMemoryReports()` that generates reports of mem allocation in `.reports/tt_metal dir` 

three reports get generated:
- program_memory_usage_summary
- program_l1_usage_summary
- program_detailed_memory_usage

L1 usage summary would probably be helpful here

**Comment by eyonland** [comment]
I'll try and enable that and take a look.   

Also,
Is there an easy way to hook into the allocation and deallocation and throw an exception when something happens.  I think this would only be applicable as a debugging mechanism.   I was imagining using something like this class below and then you just hook into the calls that are happening...


```
class AllocatorTracker {
   private:
    std::map<size_t, size_t> allocations;

   public:
    void allocate(size_t offset, size_t length) {
        if (length == 0) {
            throw std::runtime_error("Cannot allocate zero length.");
        }
        auto it = allocations.lower_bound(offset);
        if (it != allocations.begin()) {
            auto prevIt = std::prev(it);
            size_t prevEnd = prevIt->first + prevIt->second;
            if (prevEnd > offset) {
                throw std::runtime_error("Allocation overlaps with an existing allocation.");
            }
        }
        if (it != allocations.end() && offset + length > it->first) {
            throw std::runtime_error("Allocation overlaps with an existing allocation.");
        }
        allocations[offset] = length;
        // std::cout << "Allocated " << length << " units at offset " << offset << std::endl;
    }
    void deallocate(size_t offset) {
        auto it = allocations.find(offset);
        if (it == allocations.end()) {
            throw std::runtime_error("No allocation found at the specified offset.");
        }
        // std::cout << "Deallocated " << it->second << " units from offset " << offset << std::endl;
        allocations.erase(it);
    }
    void printAllocations() const {
        std::cout << "Current Allocations (offset: length):" << std::endl;
        for (const auto &alloc : allocations) {
            std::cout << alloc.first << ": " << alloc.second << std::endl;
        }
    }
} track_allocations;
```

**Comment by abhullar-tt** [comment]
there are already checks to ensure that allocations don't overlap and it will throw if it hits OOM

**Comment by jvasilje** [comment]
@mywoodstock this is a P0, appears it's just sitting :) 
are you working on fixing it, or someone else?
is it no longer blocking? should we re-prioritize?

**Comment by mywoodstock** [comment]
yes im actively working on it

**Comment by mywoodstock** [comment]
There are several issues encountered to get the full model working seamlessly with the sharding configs, @tt-nshanker , @nsmithtt and i are actively working on resolving the short comings with ttnn.

**Comment by mywoodstock** [comment]
Replacing this issue with the actual bigger issue: https://github.com/tenstorrent-metal/tt-metal/issues/6035.

**Comment by tt-nshanker** [comment]
> Replacing this issue with the actual bigger issue: #6035.

Issue #6035 is for cleaning up TTNN API. Not critical to functionality.

**Comment by mywoodstock** [comment]
yeah, we are doing workarounds to bypass preprocessor

**Comment by tt-nshanker** [comment]
> yeah, we are doing workarounds to bypass preprocessor

Should we have another issue to represent model changes to bypass preprocessor

**Comment by mywoodstock** [comment]
> Should we have another issue to represent model changes to bypass preprocessor

I'll just use this issue for that - will update name etc

**Comment by eyonland** [comment]
I
Glad to here that we have a workaround.  Given the workaround, I think we can bump this down to a P1.

**Comment by mywoodstock** [comment]
checkpointing: TTNN is at 60% of TTLIB now.

**Comment by mywoodstock** [comment]
this checkpoint is now in `main`

**Comment by eyonland** [comment]
@mywoodstock, based on our conversation, the last remaining items are:

1. There are L1 clash with batch 16 and 20, so need to go through op by op and move tensors around to make space
2. The last part of the graph is using l1 interleaved, and needs to be resharded to use width sharding like in ttlib version
3. Upload to demos folder

**Comment by mywoodstock** [comment]
This was already achieved. Closing.
