### ISSUE TITLE
watcher: remove dependency on runtime generated header file

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#5783]
This is a child project of #3381.

Currently a header file is generated w/ all the noc info for use by the watcher (to determine valid noc coords).  This header is harvesting dependent which means, eg, on galaxy we have to build kernels 32 times for 32 different chips.  Instead, watcher could use runtime information stored in mailboxes to remove this dependency.

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent/tt-metal/pull/12686 has this fix for this
