### ISSUE TITLE
[Metal Trace Phase1] Implement trace replay mechanism

### ISSUE THREAD

**Issue by tooniz** [tenstorrent/tt-metal#5831]
EnqueTrace emits a new command type that should be decoded by the prefetch core

The command needs to contain the trace buffer location in DRAM, trigger the load of interleaved pages from DRAM and assemble into a single buffer in prefetcher L1, then sent to the dispatch core as normal

**Comment by kmabeeTT** [comment]
This is done and implemented, marking closed.
