### ISSUE TITLE
Vanilla UNet variant CARVANA which has trained weights runs into errors on TTNN at the fourth downsample block 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#5856]
**Describe the bug**
We are adding 2 variants of vanilla UNet to run on device via TTNN. The trained weights are available for these two variants. Hence, we can use them to demo our UNet development on TTNN and also have a more reliable PCC check. 

This issue is regarding the [CARVANA variant](https://github.com/milesial/Pytorch-UNet)

**To Reproduce**
1. Go to [my branch at](https://github.com/tenstorrent-metal/tt-metal/commit/e21b73a32f355aaa18973b8b6a1914e94ecf4f16)
2. run `python tests/ttnn/integration_tests/unet/test_ttnn_functional_CARVANA_CONVENTIONAL_unet_maxpoolFallback.py`
3. See error
`...
RuntimeError: TT_FATAL @ tt_eager/tt_dnn/op_library/untilize/untilize_with_halo_op_v2.cpp:570: ncores_nhw_ == shard_spec.grid.num_cores()
info:
ncores_nhw ({}) != shard_spec.grid.num_cores ({})
...`

**Expected behavior**
runs with no error

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- [software version: commit](https://github.com/tenstorrent-metal/tt-metal/commit/e21b73a32f355aaa18973b8b6a1914e94ecf4f16)

**Comment by davorchap** [comment]
@dvartaniansTT please provide the shape of the failing OP, as disucssed with @mbahnasTT this could be fixed once we have width sharding for Convs.
