### ISSUE TITLE
[Future] pytest `/unit_testing/test_untilize_with_halo_v2.py` fails and hangs if only open/close device once for the whole session

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent/tt-metal#5867]
**Describe the bug**
In the future, we are looking to transition to only opening/closing device once per session. This would reduce post-commit time by ~5-10 mins. 

Theoretically, device shouldn't need to get closed between tests, but the cleanup done during device close flushes any leftovers from previous test, giving more stable results right now. 

`pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_v2.py` will fail for any parameterization and then hang. When run with watcher, it'll eventually throw: `ncrisc using noc1 tried to accesss core (11,10)` error 

**To Reproduce**
1. Only open device once for each test session: go to `conftest.py` and change `device_init_destroy` fixture to have scope `session`
2. run `TT_METAL_WATCHER=10 TT_METAL_WATCHER_APPEND=1 TT_METAL_WATCHER_DUMP_ALL=1 pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_v2.py`
3. observe failure

**Comment by vtangTT** [comment]
related to #4957 and #4960

**Comment by TT-billteng** [comment]
need to find an owner, who usually touches this file? @vtangTT

**Comment by vtangTT** [comment]
> need to find an owner, who usually touches this file? @vtangTT

looks like Abhinav, Nitika or Brian

**Comment by vtangTT** [comment]
Update: on most recent main, watcher is no longer throwing the ncrisc error, however looks like the failures for all configs will still happen deterministically

**Comment by TT-billteng** [comment]
seems like we aren't close to doing this anymore, though the overhead of opening and closing device has gone down drastically
