### ISSUE TITLE
Increase stack size for trisc0/1, currently 256 bytes

### ISSUE THREAD

**Issue by coffeeandcheesecake** [tenstorrent/tt-metal#588]
The constants are defined in trisc0.ld, trisc1.ld. The challenge is to know if there are any undesired side effects to just increasing these.

Current stack size is only 256 bytes on trisc0, trisc1 and that is not sufficient for say debug printing tiles. Also overwriting the stack causes (very) painful debugging issues.

**Comment by jliangTT** [comment]
infra needs to exist first.

**Comment by pgkeller** [comment]
closing, have data now and this isn't needed
