### ISSUE TITLE
WH ND hang in `test_falcon_matmuls_and_bmms_with_mixed_precision.py::test_falcon_matmul`

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#5882]
1) Install pytest repeat in environment with `pip install pytest-repeat`

2) `pytest --count=100 $TT_METAL_HOME/models/demos/falcon7b/tests/unit_tests/test_falcon_matmuls_and_bmms_with_mixed_precision.py -k "seq_len_128 and in0_BFLOAT16-in1_BFLOAT8_B-out_BFLOAT16-weights_DRAM"`

This has been observed in [CI](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8106936719/job/22157660197) and reproduced locally on a VM

**Comment by TT-billteng** [comment]
another hang https://github.com/tenstorrent-metal/tt-metal/actions/runs/8114687860/job/22180903685

**Comment by s-jovic** [comment]
Hey @TT-billteng, thanks for removing the test from the CI.

**Comment by s-jovic** [comment]
Test is not run on the CI currently, and we don't need it as the functions it tests are not used in Falcon7b. Closing the issue.
