### ISSUE TITLE
TopK op for MoE

### ISSUE THREAD

**Issue by yieldthought** [tenstorrent/tt-metal#5906]
To match the torch op:
TopK -> weights (of top k), indices (of top k): (32, 8) -> (32, 8), (32, 1)

Context for Mixtral (internal only): https://tenstorrent.sharepoint.com/:p:/s/Jasmina/EUZv5VSt7IBKj5cI05eBSOsBeVSAt9S_k3B6FCfzyT5RdQ?e=zkg8rF 

Open to better ideas for how to map the MoE branching operation than the torch approach, but this is our opening suggestion.

**Comment by yieldthought** [comment]
We will also need this for end-to-end performance, to avoid bringing tokens back to the host and pushing them back to the device each step.

**Comment by tarafdarTT** [comment]
@jliangTT FYI this is on my plate too. I can have a look at this as well but it'd be helpful if we can get more hands on TMs

**Comment by ttmtrajkovic** [comment]
Adding link to GH issue tracking LLK changes:
https://github.com/tenstorrent-metal/tt-metal/issues/5063

@tarafdarTT, whenever you're ready @rdjogoTT can help you with more detail and spec of the API. The compute kernel for BUDA already exists and it works, so it shouldn't take a while to just replicate this in metal.

Milos

**Comment by rdjogoTT** [comment]
@sraizada-tt @tarafdarTT @yieldthought 

FYI, for TopK with K=2 & N=32, we don't support K=2 directly. Rather we can use a higher K value and ignore/mask out the datums past the top 2.
After performance analysis, the fastest approach would be to use K=32 and ignore the extra datums. If needed, the extra datums can also be masked with an eltwise op after TopK.

**Comment by tarafdarTT** [comment]
> @sraizada-tt @tarafdarTT @yieldthought
> 
> FYI, for TopK with K=2 & N=32, we don't support K=2 directly. Rather we can use a higher K value and ignore/mask out the datums past the top 2. After performance analysis, the fastest approach would be to use K=32 and ignore the extra datums. If needed, the extra datums can also be masked with an eltwise op after TopK.

Awesome, do we need the k=64 case? I know you impelemented it but it sounded more complex.

**Comment by rdjogoTT** [comment]
> > @sraizada-tt @tarafdarTT @yieldthought
> > FYI, for TopK with K=2 & N=32, we don't support K=2 directly. Rather we can use a higher K value and ignore/mask out the datums past the top 2. After performance analysis, the fastest approach would be to use K=32 and ignore the extra datums. If needed, the extra datums can also be masked with an eltwise op after TopK.
> 
> Awesome, do we need the k=64 case? I know you impelemented it but it sounded more complex.

I believe that one of the falcon models will require TopK with K=64 (@cglagovichTT please confirm). The implementation is slightly more complex in terms of which tiles to load into DEST, but other than that the API calls work the same as for smaller values. Also, I'm happy to help with this case and others.

**Comment by cglagovichTT** [comment]
If LLM demos are limited to K=32 in the short term I don't think that's a problem. Longer term, we would probably want to provide optionality for higher Ks such as K=64, but I don't believe this is a blocker for demos. @yieldthought to add his thoughts as well.

**Comment by tarafdarTT** [comment]
@yieldthought @sraizada-tt hey guys I am working on this right now. Do you mind giving me the following parameters? I wanna make sure that out of the box I have a realistic case that is useful to you. 

1) Tensor shape ? [batch , channel, num rows, num columns]. 

From what I know is that the num columns supported are 32, 64, 128, 256, 512, 1024, 2048, 4096 in hardware with @rdjogoTT's kernel but we can pad to the next highest number we have.

2) The K we are interested in. We are golden if it's less than or equal to 32, a little less golden if it's bigger than 32 and less than 64 and will need to rearchitect if it's bigger than 64.

I'll try to have something by Wednesday/Thursdsay .

**Comment by sraizada-tt** [comment]
@tarafdarTT  For the top-k in the middle of MoE:
1. Tensor is [1, seqlen, batch, num_experts] = [1, 1, 32, 8]
2. K = 2 
3. Don't need sharing support on either input or output for this

**Comment by yieldthought** [comment]
Stuti could you also share the dims for the end-of-network use case?

**Comment by sraizada-tt** [comment]
For end-of-network use case:
1. Tensor is [1, seqlen, batch, vocab_size] = [1, 1, 32, 32000]
2. K really is a sampling choice here - can go from 1 to 80. Initially having it work for 1 to 32 should be okay. 
3. Don't need sharing support on either input or output for this

**Comment by uaydonat** [comment]
fyi, topk only appears at the end of token generation for other models, so it is less performance critical. 

On mixtral, topk is used in MoE at every layer, hence, it is performance critical.

**Comment by tarafdarTT** [comment]
adding @sjameelTT here, he is starting the implementation as I have a lot on my plate ATM. He will take the lead on this in the meantime but I'll be following along :)

**Comment by sjameelTT** [comment]
> For end-of-network use case:
> 
> 1. Tensor is [1, seqlen, batch, vocab_size] = [1, 1, 32, 32000]
> 2. K really is a sampling choice here - can go from 1 to 80. Initially having it work for 1 to 32 should be okay.
> 3. Don't need sharing support on either input or output for this

Hi Stuti, what data types are needed here?

**Comment by sraizada-tt** [comment]
@sjameelTT bfloat16 and bfloat8

**Comment by jliangTT** [comment]
@sjameelTT , what is the status for this?

**Comment by sjameelTT** [comment]
Started a single core implementation, on my branch sjameel/topk. Working on fixing bugs right now.

**Comment by jliangTT** [comment]
do we have an ETA yet?

**Comment by sjameelTT** [comment]
Aiming for end of next week.

**Comment by sjameelTT** [comment]
Blocked by constraints for CBs - we can't have two different data formats/types for either intermediate or output buffers. Since the indices and values are uint16 and bfloatX respectively these constraints need to be relaxed

**Comment by jliangTT** [comment]
@rtawfik01 / @rdjogoTT , any input on this? Is the next step to relax the decision on the constraint? Or we need to think about other options? If the decision is to relax the constraint, what would be the scope to ensure that we are doing it safely?

**Comment by rdjogoTT** [comment]
> @rtawfik01 / @rdjogoTT , any input on this? Is the next step to relax the decision on the constraint? Or we need to think about other options? If the decision is to relax the constraint, what would be the scope to ensure that we are doing it safely?

I believe relaxing the constraint is the next step, this is how it was handled in Buda.

**Comment by jliangTT** [comment]
What needs to be done? any code change from LLK side? Or is it a simple agreement with op writer so they can move on being unblocked?

**Comment by rdjogoTT** [comment]
No changes from LLK are needed, just an agreement.

**Comment by jliangTT** [comment]
@sjameelTT , can this be unblocked from your side?

**Comment by sjameelTT** [comment]
We can relax this constraint. It may take me some time to refactor this since I'm unfamiliar with this part of the codebase.

**Comment by sjameelTT** [comment]
Is there any hardware limitation that these were motivated by?

**Comment by sjameelTT** [comment]
All the packer and unpacker configuration functions touch this so I think this may need a spec discussion

**Comment by rdjogoTT** [comment]
No hardware limitation, it just used to be necessary when we used to allow only 1 type of output, and the intermediates needed to math as well. This is no longer the case.

**Comment by sjameelTT** [comment]
I have the values working with the simplest case (1, 1, 32, 64). Indices are waiting on the intermediate buffer changes. Will extend the values to other dimensions in the mean time.

**Comment by sjameelTT** [comment]
Indices and values are working now. Just need to clean up the code.

**Comment by uaydonat** [comment]
@mtairum @sraizada-tt can we close this?

**Comment by sraizada-tt** [comment]
Yes
