### ISSUE TITLE
Lower concurrent number of GitHub-hosted runner jobs like builds and releasing if we start hitting the 60 job limit

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#5976]
We could use the concurrent options to limit the number of GitHub-hosted runner jobs going on in these build / packaging jobs if we're starting to hit the 60 limit for our org.

cc: @TT-billteng @ttmchiou

**Comment by TT-billteng** [comment]
think we're aware of the limit now and actively managing load properly, especially with how many dedicated builders we have now
