### ISSUE TITLE
DPRINT asserts hardcoded L1 address check causing dprint failure on WH_B0

### ISSUE THREAD

**Issue by yugaoTT** [tenstorrent/tt-metal#5980]
is the CB is allocated above 1024 * 1024 or below 120*1024, the dprint failed with an error BAD TILE POINTER count=0.

**Comment by tt-dma** [comment]
Could you provide an example that reproduces this bug? So we can check if the bounds need updating or if there's a bug in the DPRINT addressing

**Comment by yugaoTT** [comment]
yes, 
branch `yugao/moreh-u-benchmark`
make build 
make tests
run `./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 32 --n 32 --k 64 --dtype 1 --fidel 0 --block 1  --num-tests 1 --fast-dispatch --bypass-check --one-core 1 --num-blocks 1`

**Comment by tt-dma** [comment]
Are there additional defines that are needed to run this test? I'm getting: 
```
(python_env) davidma@e04cs04:~/tt-metal$ ./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 32 --n 32 --k 64 --dtype 1 --fidel 0 --block 1  --num-tests 1 --fast-dispatch --bypass-check --one-core 1 --num-blocks 1
Remaining test_args:
        --dtype
        1
        --num-blocks
        1
                   Test | ERROR    | Command line arguments found exception
                 Always | ERROR    | In the slow dispatch mode, device profiler is used to measure the performance. Build the Metal library and test code with 'ENABLE_PROFILER=1'
                   Test | ERROR    | TT_ASSERT @ tests/tt_metal/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm.cpp:199: false
backtrace:
 --- /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f6b9839e083]
 --- ./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm(+0xa0ae) [0x55a4ed47f0ae]

                   Test | ERROR    | System error message: Success
                   Test | ERROR    | Test Failed
```

Seems it needs either profiler enabled or a certain dispatch mode?

**Comment by yugaoTT** [comment]
Which branch are you working on?

David Ma ***@***.***>于2024年3月4日 周一17:10写道：

**Comment by yugaoTT** [comment]
Hmm, maybe try make build ENABLE_PROFILER=1, then make tests
ENABLE_PROFILER=1. and commit should be at
https://github.com/tenstorrent-metal/tt-metal/commit/e7d6eaf0bc72aa03e1c85c84d7b655927ed73b8a

David Ma ***@***.***>于2024年3月4日 周一17:37写道：

**Comment by tt-dma** [comment]
I'm running on an n300 BM, and I'm able to run your test after checking out that commit (no extra env vars). I see a bunch of prints and then this error:
```
index: 2046 1 1
index: 2047 1 1
                   Test | ERROR    | validation single core failed
                  Metal | INFO     | Closing device 0
                 Always | INFO     | CSV_MICROBENCHMARK:title:test_compute_mm
                 Always | INFO     | CSV_INPUT:M:32:N:32:K:64:fast-dispatch:true
```
This looks separate from the DPRINT error that would be tripped by those bounds?

**Comment by yugaoTT** [comment]
Right, this is not related to dprint.

David Ma ***@***.***>于2024年3月4日 周一17:53写道：

**Comment by tt-dma** [comment]
Any idea on how I can reproduce the dprint issue that is filed here then?

**Comment by yugaoTT** [comment]
please enable the printing on core 0,0. `export TT_METAL_DPRINT_CORES="(0,0)"`, the DPRINT is in file `tests/tt_metal/tt_metal/perf_microbenchmark/1_compute_mm/kernels/bmm_large_block_zm_fused_bias_activation_block.cpp`, at line 115
