### ISSUE TITLE
Create API to evict a trace

### ISSUE THREAD

**Issue by tooniz** [tenstorrent/tt-metal#6020]
When a Trace is instantiated onto a CQ, it combines the traced commands into a flat buffer and commits that into device DRAM and caches it there.

The lifetime of the trace cannot be inferred, hence the trace buffer that is in DRAM is effectively cached until explicitly told to be evicted by the user.

We need a dedicated API for that to evict the trace out of DRAM by id, there won't actually be any device side operations we just need to destroy the host side trace buffer which will then trigger the deallocate call.

**Comment by tooniz** [comment]
Marking P2, probably not blocking for single workload tests, where by ending the test we deallocate all buffers and free up DRAM. This will be relevant when we need to actually run multiple workloads back to back and need to free up DRAM stored traces

fyi @davorchap

**Comment by kmabeeTT** [comment]
Tony made a commit on Apr1 which added metal API `ReleaseTrace()` API and a test `TraceInstanceManagement` added.  

Currently this type of API is not exposed at tt_eager level - open question if it should be.

**Comment by kmabeeTT** [comment]
I went ahead and exposed the API at python level in spirit of this ticket that users should have ability to control trace lifetime, marking closed.
