### ISSUE TITLE
Sending a to b, then b to a hangs in rare cases

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent/tt-metal#6083]
E.g.:

![Image](https://github.com/tenstorrent-metal/tt-metal/assets/130597713/6c7ea071-5658-4777-b996-9b3a71aef62b)

Temp fix to only test one direction on main.

**Comment by prajaramanTT** [comment]
@aliuTT Is this still an issue ?

**Comment by aliuTT** [comment]
No, closing.
