### ISSUE TITLE
Three CommonFixture tests fail on fast dispatch R chip

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#6097]
To reproduce, check out origin/dma/5661_enable_tests (should be merged soon): `./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=*CommonFixture*`

Should see `CommonFixture.DRAMLoopbackSingleCore`, `CommonFixture.Flatten`, and `CommonFixture.MatmulLargeBlock` failing, or at least on my n300 BM these three tests fail. Not familiar with these tests, so could be that failure is expected, will need to check that first.

**Comment by abhullar-tt** [comment]
these were failing with FD1.x? Is this still an issue in FD2.0?

**Comment by tt-dma** [comment]
Two of these tests are passing on my N300, `CommonFixture.Flatten` is disabled due to https://github.com/tenstorrent/tt-metal/issues/7380. Seems like this issue is not present anymore
