### ISSUE TITLE
Pushing BFP8 tensors to device is twice as slow as BF16

### ISSUE THREAD

**Issue by mikevin920** [tenstorrent/tt-metal#6101]
**Describe the bug**
We need to push attn_mask to device every token and its in bfp8 to save memory, we found that the calling torch2tt_tensor to DRAM interleaved is twice as slow for bfp8 tensors than bf16 tensors of the same size. 

**To Reproduce**
1. checkout this [branch](https://github.com/tenstorrent-metal/tt-metal/tree/model-team/llama2-sprint):
2. Take a look at this [test file](https://github.com/tenstorrent-metal/tt-metal/blob/model-team/llama2-sprint/models/demos/llama2_70b/tests/unit_tests/test_BFP8_to_device.py) that creates two tensors in diffrent data format and profiles the time for torch2tt_tensor
3. run this command after building tt-metal :`pytest -svv  models/demos/llama2_70b/tests/unit_tests/test_BFP8_to_device.py::test_bfp8_to_device[32-1]`
4. observe results shown by the profiler

**Expected behavior**
For tensor of size (32, 1, 32, 512)
```
pushing_attn_mask_to_DRAM_bf16: 0.017s
pushing_attn_mask_to_DRAM_bf8: 0.034s
```

**Comment by mikevin920** [comment]
@cglagovich @caixunshiren

**Comment by eyonland** [comment]
Hi @ttmtrajkovic , is this something you could look at?

**Comment by ttmtrajkovic** [comment]
This is more of a runtime performance problem, adding @tooniz.
The comment with regards to BFP8 in general is that it depends on the implementation of the host tilization as it requires calculating the common exponent for every 16 numbers and subsequent alignment. Number of bytes that are transferred is halved, but SW tilization gets more complicated.
Tony should have more details about the speed of tilization

**Comment by eyonland** [comment]
Hey @tooniz , is this something y'all could look into?

**Comment by jliangTT** [comment]
@mikevin920, how much bottleneck this is to the current model? Want to gauge if P2 is the right priority . @uaydonat

**Comment by mikevin920** [comment]
@jliangTT we arent looking at end to end performance very closely right now so P2 should be good?

**Comment by jliangTT** [comment]
@mikevin920 , is this issue becoming more of the bottleneck more recently? want to see if priority needs to be updated.

**Comment by jliangTT** [comment]
how much can we stand to gain e2e for this? This is for LLama right?

**Comment by kevinmiTT11** [comment]
potential 2x speed up of pushing attn_mask to device which happens every decode step. If we can take a look at uint32 as well, then pushing new tokens would also get a speed up

**Comment by uaydonat** [comment]
On falcon7b, @skhorasganiTT switched to using device tilize for attention_mask and the overhead was significantly reduced. Did you guys try that? @kevinmiTT11

**Comment by kevinmiTT11** [comment]
We will include that in our next merge to main. Should be able to speed up e2e time by a lot.

**Comment by tooniz** [comment]
You guys should either tilize on device or refer to Buda backend's implementaion of a fast tilizer using CPU instrinsics, eg. AVX to do BFP8 tilization -- a naive implemention on host is going to be very very slow

**Comment by pgkeller** [comment]
found this old issue, @kevinmiTT11  is this still a problem or was it address per Tony's comment above?  thanks

**Comment by skhorasganiTT** [comment]
This is no longer an issue for llama as we now tilize on device. Also the problem was specific to the [torch2tt_tensor](https://github.com/tenstorrent/tt-metal/blob/main/models/utility_functions.py#L172) model utility function which converts layout before sending to device (this function is used in older tests and should be deprecated). Since there is no runtime issue we can close this.
