### ISSUE TITLE
Sharding options for SD MHA

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent/tt-metal#6154]
We need to come up with a shard spec to allow us to do stable diffusion multi head attention performantly. The graph segment looks like this:

![image](https://github.com/tenstorrent-metal/tt-metal/assets/19839011/ea690c43-488f-49ff-9a92-87a441d2cce2)

Ideally we could have the matmul -> softmax -> matmul run without needing reshard. The first MM output is {2,8,4096,4096} so it will be time sharded along the head dim (i.e. it will executed as a (2, 1, 4096, 4096) calculation at one time and the results will be stitched together at the end. 

The following are the various shapes that we need shard specs for:
![image](https://github.com/tenstorrent-metal/tt-metal/assets/19839011/ee6e857d-72b9-4a93-8edc-5a92034226d7)

Can this be done with our current matmuls or do we need something else?

**Comment by TT-BrianLiu** [comment]
The first matmul is a 2D systolic matmul that needs to be uplifted to support taking in sharded inputs with:
- `in0` height sharded along column
- `in1` width sharded along row

Then, your output would be block sharded. For the second mm, if you want to leave sharding as is (ie. block sharded) and use the same 2D systolic matmul, it should work as long as value is in interleaved (check with L1 interleaved and see if perf is good enough).

**Comment by AleksKnezevic** [comment]
sounds good. Value is not too big, so hopefully it's not a big deal, thanks. We can use this issue for the updates needed to MM.

**Comment by pavlejosipovic** [comment]
I'm looking into this.

**Comment by pavlejosipovic** [comment]
Branch with working prototype is here [pjosipovic/2d_matmul_in0_height_in1_width_sharded](https://github.com/tenstorrent-metal/tt-metal/tree/pjosipovic/2d_matmul_in0_height_in1_width_sharded)

**Comment by TT-BrianLiu** [comment]
Nice! Put up a PR?

**Comment by pavlejosipovic** [comment]
My changes are in main, I'll leave it @AleksKnezevic  to close this issue if this improvement ends up helping with his use-case

**Comment by TT-BrianLiu** [comment]
@AleksKnezevic Block sharded output + single col/row HEIGHT/WIDTH sharded in0/in1 should work now. This is for the first qk matmul. Give it a try and if it works, close the issue?

**Comment by bbradelTT** [comment]
@AleksKnezevic can this issue be closed?

**Comment by AleksKnezevic** [comment]
Yes.
