### ISSUE TITLE
ViT patch Embeddings fallback warning message and need for optimization (new TM)

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent/tt-metal#6161]
**Describe the bug**
vit_patch_embeddings module includes 6 TM steps of permute and reshape and processing on a tensor with rank 6.
I had to modify few asserts to enable tensors with rank 6. the current error message:
```
 ttnn.reshape: falling back to torch due to reshape(): incompatible function arguments. The following argument types are supported:
    1. (tensor: tt_lib.tensor.Tensor, shape: ttnn._ttnn.types.Shape) -> tt_lib.tensor.Tensor
    2. (tensor: tt_lib.tensor.Tensor, shape: List[int[1]]) -> tt_lib.tensor.Tensor
2024-03-11 15:42:11.641 | WARNING  | ttnn.decorators:call_wrapper:232 - ttnn.reshape: falling back to torch due to reshape(): incompatible function arguments. The following argument types are supported:
    1. (tensor: tt_lib.tensor.Tensor, shape: ttnn._ttnn.types.Shape) -> tt_lib.tensor.Tensor
    2. (tensor: tt_lib.tensor.Tensor, shape: List[int[1]]) -> tt_lib.tensor.Tensor
                 Always | FATAL    | Unable to reshape given tensor!
2024-03-11 15:42:11.653 | WARNING  | ttnn.decorators:call_wrapper:232 - ttnn.reshape: falling back to torch due to TT_THROW @ ttnn/cpp/ttnn/operations/core.hpp:82: tt::exception
info:
Unable to reshape given tensor!
                 Always | FATAL    | Unable to reshape given tensor!
2024-03-11 15:42:13.010 | WARNING  | ttnn.decorators:call_wrapper:232 - ttnn.reshape: falling back to torch due to TT_THROW @ ttnn/cpp/ttnn/operations/core.hpp:82: tt::exception
info:
Unable to reshape given tensor!
```

**To Reproduce**
1. https://github.com/tenstorrent-metal/tt-metal/blob/mbahnas/ttnn_vit_classify/tests/ttnn/integration_tests/vit/test_ttnn_optimized_vit.py::test_vit_patch_embeddings
2. https://github.com/tenstorrent-metal/tt-metal/blob/mbahnas/ttnn_vit_classify/tests/ttnn/integration_tests/vit/test_ttnn_optimized_vit_highres.py::test_vit_patch_embeddings

**Expected behavior**
Running the test with no error message and getting a PCC=0.999
current: PCC: 0.998255238968629

**Screenshots**
   ```
    pixel_values = ttnn.to_layout(pixel_values, layout=ttnn.ROW_MAJOR_LAYOUT)
    pixel_values = ttnn.reshape(pixel_values, (batch_size, img_c, img_h, patch_count, patch_size))
    pixel_values = ttnn.reshape(pixel_values, (batch_size, img_c, patch_count, patch_size, patch_count, patch_size))
    pixel_values = ttnn.permute(pixel_values, (0, 1, 2, 4, 3, 5))
    pixel_values = ttnn.reshape(pixel_values, (batch_size, img_c, patch_count_sq, patch_size_sq))
    pixel_values = ttnn.permute(pixel_values, (0, 2, 1, 3))
    pixel_values = ttnn.reshape(pixel_values, (batch_size, patch_count_sq, patch_size_sq_trpl))
    pixel_values = ttnn.to_layout(pixel_values, dtype=ttnn.bfloat8_b, layout=ttnn.TILE_LAYOUT)
```

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by jliangTT** [comment]
@arakhmati, is this a kernel writer issue or a ttnn infra issue?

**Comment by jliangTT** [comment]
c.c. @eyonland as well.

**Comment by arakhmati** [comment]
@jliangTT @mbahnasTT the message means that we weren't able to run the reshape on the device. And as you can see, the next message is:
```
2024-03-11 15:42:13.010 | WARNING  | ttnn.decorators:call_wrapper:232 - ttnn.reshape: falling back to torch due to TT_THROW @ ttnn/cpp/ttnn/operations/core.hpp:82: tt::exception
info:
Unable to reshape given tensor!
```

So, it is a feature of `ttnn` to use the torch fallback (when one is available and ttnn operation fails to run)

**Comment by arakhmati** [comment]
Also, I ran the test. It looks like we need a custom Data Movement operation to transform the input instead of calling reshapes and permutes. And the PCC difference can be explained due to `float32` and `bfloat8_b` differences

**Comment by jliangTT** [comment]
adding @tarafdarTT on this. Can you take a look if this falls on your plate?

**Comment by jliangTT** [comment]
@arakhmati , based on your feedback, what needs to be done here? (sorry i don't have a good feel of next step, that is why i am pulling in @tarafdarTT  to comment as well)

**Comment by tarafdarTT** [comment]
Given @arakhmati's comment of us requiring a data movement operation to transform the input instead of doing a reshape, this will fall on my plate.

I will need to sync with him to figure out what that data movement operation will entail though.

**Comment by jliangTT** [comment]
thanks @tarafdarTT for this. let me know if you have bandwidth to support this with other request from the javelin team.

**Comment by tarafdarTT** [comment]
np @jliangTT , at the moment I'm a little low on bandwidth. I might have some time next week so it depends on the urgency. 
I think @yan-zaretskiy who's also on TMs is ooo until Tuesday as well. 
Would we be able to pull someone else in for this specific issue in the meantime. I think @tt-aho is also familiar with embeddings and TMs. (he may also be low on bandwidth as well though)

**Comment by jliangTT** [comment]
please prioritize the javelin stuff first and come back to this as soon as you can wrap up. what is the t-shirt size on this? is this something with the short turnaround time?

**Comment by tarafdarTT** [comment]
sure thing, I was just spooked by the customer bug and P1 priority on this.

**Comment by tarafdarTT** [comment]
regarding turn around time, I am not sure exactly, I will need to sync with @arakhmati or @mbahnasTT to figure out what they need from the data movement kernel.

**Comment by mbahnasTT** [comment]
To clarify it more, this is the full code snippet of the needed OP, as well as a carton to illustrate the objective.
P.S., I'll update the code to support non-square images.
```
pixel_values = ttnn.to_layout(pixel_values, layout=ttnn.ROW_MAJOR_LAYOUT)
 pixel_values = ttnn.reshape(pixel_values, (batch_size, img_c, img_h, patch_count, patch_size))
 pixel_values = ttnn.reshape(pixel_values, (batch_size, img_c, patch_count, patch_size, patch_count, patch_size))
 pixel_values = ttnn.permute(pixel_values, (0, 1, 2, 4, 3, 5))
 pixel_values = ttnn.reshape(pixel_values, (batch_size, img_c, patch_count_sq, patch_size_sq))
 pixel_values = ttnn.permute(pixel_values, (0, 2, 1, 3))
 pixel_values = ttnn.reshape(pixel_values, (batch_size, patch_count_sq, patch_size_sq_trpl))
 pixel_values = ttnn.to_layout(pixel_values, dtype=ttnn.bfloat8_b, layout=ttnn.TILE_LAYOUT) 
```

https://tenstorrent.slack.com/archives/C065NUB85K3/p1706056896959419

![image](https://github.com/tenstorrent-metal/tt-metal/assets/116673264/b33fd84d-2ce1-4617-8115-76aacd823673)

**Comment by tarafdarTT** [comment]
thanks @mbahnasTT , I'll try to digest this a bit. Find me in the office today, I might not have time to work on it, but since I'm in town let's make sure I understand the op so I can give @jliangTT an estimate.

**Comment by mbahnasTT** [comment]
Updated info, the ViT full model = embeddings + encoder
The encoder only e2e runtime (on 224x224 b=8) is 425 FPS  [optimized-L1-interleaved]
The full model e2e runtime is 16 FPS
So, we can quantify the impact of the embedding runtime

**Comment by tarafdarTT** [comment]
updating some information here that we spoke about on slack, posting here for completion.
file to look at: tests/ttnn/unit_tests/operations/test_embedding.py
this has your examples:
here we have a 2D vector input, (batch_size, sentence_size)  with weights that are 2D as well of vocabulary_size, hidden_embedding_dim size
the output should be (sentence_size, hidden_embeding_dim_size)
for you i think the 2D rectangle thats a single batch, should get flattened onto what we refer to as a sentence.
if you can flatten the batch into a sentence, you should be able to use the embedding op

Flatten with reshape:
original shape [batch , x, y] -> [batch, x*y]

**Comment by mbahnasTT** [comment]
Solved by using `tt_lib.tensor.fold` Thanks @yan-zaretskiy and @tarafdarTT 
```

# on cpu
    pixel_values = torch.permute(torch_pixel_values, (0, 2, 3, 1))
    pixel_values = torch.nn.functional.pad(pixel_values, (0,1,0,0,0,0,0,0))
# on device
    pixel_values = ttnn.from_torch(pixel_values, dtype=ttnn.bfloat16, layout=ttnn.ROW_MAJOR_LAYOUT, device=device)
    batch_size, img_h, img_w, img_c = pixel_values.shape # permuted input NHWC
    patch_size = 16
    patch_count = img_h // patch_size  # 14
    patch_size_sq_trpl = int(patch_size * patch_size * 3)  # 768
    patch_count_all = int(patch_count * patch_count)  # 196
    stride_h = patch_size
    stride_w = 1
    pixel_values = ttnn.reshape(pixel_values, (batch_size, img_h, img_w // patch_size, 4 * patch_size))
    pixel_values = ttl.tensor.fold(pixel_values, stride_h, stride_w)
    pixel_values = ttnn.to_layout(pixel_values, layout=ttnn.TILE_LAYOUT)
```
