### ISSUE TITLE
Ignore binary files generated in models/demos runs

### ISSUE THREAD

**Issue by djordje-tt** [tenstorrent/tt-metal#6189]
**Is your feature request related to a problem? Please describe.**
Whenever model is downloaded from hugging face, hundreds of binary files are generated and it's hard to keep track of changed files

**Describe the solution you'd like**
Add *.bin in .gitignore file
** Describe alternatives you've considered**
Alternative is to add locally and not push change but I highly doubt it's nice approach.

**Comment by tt-rkim** [comment]
Does huggingface download to `HF_CACHE`? Why is this necessary?

**Comment by djordje-tt** [comment]
This is already added to .gitignore in the meantime from another issue. So I am closing this one.
