### ISSUE TITLE
Fully Asynchronous Execution (from TT-Lib)

### ISSUE THREAD

**Issue by tt-asaigal** [tenstorrent/tt-metal#6217]
### High Level Goal
Support asynchronous execution at the TT-Lib/TTNN level by making the following calls non-blocking:

| Python Call     | TT-Lib Function(s) |
| -------------- | ------------------ |
| `device_tensor = host_tensor.to_device()`       |   `tensor_impl::to_device()`    |
|  `tensor = generic_operation(tensor)` |   `run_device_operation()` and `run_host_operation()`  |
| `host_tensor = device_tensor.cpu()`  and `host_tensor = device_tensor.cpu_sharded()`| `tensor_impl::to_host()` and `tensor_impl::to_host_sharded()`|

### Proposal
A single worker thread will be spawned for each device. This can be done in the `Device` constructor.

**Interface Between Main and Worker Threads**

A similar approach to the `CommandQueue` in TT-Metal can be used here. For each call we want to support asynchronously, a generic lambda implementation, encapsulating the data, can be pushed to a lock-free-queue. A worker thread will be responsible for processing each command/function pushed to the queue.

For prototyping purposes, `Taskflow` APIs can be used, with an Executor/Thread Pool per device.

**Object Ownership**

The following objects are owned by the worker threads (i.e. these objects will only be queried or modified through the workers):

1. Allocator (1 per device): Does not have to be made thread safe, since each thread has its own. Each device has its own allocator at in the Metal layer today.
2. Program Cache (1 per device): No concerns about worse cache performance or thread-safety here, since the program keys contain the device ID. **This object is currently global**. We need to make this per device (add this to the TT-Lib `device` class by extending the base `device` class exported by Metal), and instantiate it when `CreateDevices` is called at the TT-Lib level.
3. Kernel Cache: This is on disk and is a function of device-id, which automatically makes it per device and thread-safe. No changes should be required here.

**Tensor Lifetimes and Ownership**

The main thread currently manages all tensors and each function listed in the table above passes tensors by reference. This is problematic in async mode, since tensor metadata and memory can be preemptively deallocated by the main thread.

We have two approaches to deal with this:

_Approach 1: Tensor Handles (Preferred)_ 

Create a wrapper around the tensor class and allow shared ownership of the underlying tensor object.

```
class TensorHandle {
     public: 
         TensorHandle(Tensor& tensor_to_track, std::optional<MemoryConfig> mem_cfg) {
              tensor_to_track_ = std::make_shared<Tensor>(tensor_to_track);
              if (mem_cfg.has_value()) on_device_mem_cfg = std::make_shared<MemoryConfig>(mem_cfg);
         };
         std::shared_ptr<Tensor> get_tensor() { return tensor_to_track_; }
         std::shared_ptr<Tensor> get_mem_cfg() { return on_device_mem_cfg; }
     private:
          std::shared_ptr<Tensor> tensor_to_track_;
          std:shared_ptr<MemoryConfig> on_device_mem_cfg;
}
```
This class can be exported through `tt_lib.Tensor` (we can eventually migrate to this). With this approach, the Python API will interface only with handles and not Tensor objects themselves. The objects can be asynchronously used and modified by the worker.

Example:

```
ttl_tensor_handle.to(device) // Python Call on a TensorHandle
```
The above operation would call the following functions (instead of `Tensor::to()`):

```
// Call Stack:

TensorHandle TensorHandle::to(Device *target_device) {
      return to_device(this->get_tensor(), target_device, this->get_mem_cfg());
}

TensorHandle to_device(std::shared_ptr<Tensor> host_tensor, Device* target_device, std::shared_ptr<MemoryConfig> mem_config) {
     // Send the tensor, device and all associated metadata to be picked up by the worker and sent to device
     // device_tensor_md = host_tensor_md and device_tensor points to a device buffer containing host data
     TensorHandle device_tensor_handle;
     issue_tensor_write_through_worker(host_tensor, device_tensor_handle, target_device, mem_config);
     return device_tensor;
}
```

A similar approach can be used for all other APIs. 

This is likely the "correct" approach here, since we explicitly pass around handles and can have any tensor field accessed by the worker.

**Drawback: Significant Overhaul of TT-Lib code** 

All APIs (including Ops) need to use handles now. 

This:  `interleaved_to_sharded(const Tensor &input_tensor,...)` becomes this: `interleaved_to_sharded(const TensorHandle &input_tensor,...)`, so that `run_device_operation` can be called with shared tensor ownership and passed to the worker.

Additionally, this object will need to be uplifted to the Python APIs for full integration.

_Approach 2: Copy Tensor Data/Metadata by Value When Interfacing with Worker (Messy and Slow)_

The alternative to using shared pointers and handles is to pass data between threads by value. This adds overhead to the function calls and does not seem maintainable.

Example:

```
// Use existing APIs and eventually call to_device, which does additional data copies:
Tensor to_device(const Tensor& host_tensor, Device* target_device, const MemoryConfig& memory_config) {
      Tensor worker_tensor = host_tensor;
      MemoryConfig worker_mem_config = memory_config;
      Tensor device_tensor;
     issue_tensor_write_through_worker(host_tensor, device_tensor, target_device, mem_config);
     return device_tensor;
}
```
This approach can be extended to all other APIs with minimal changes to the function signatures.

**Comment by tt-asaigal** [comment]
fyi @tooniz @davorchap @kmabeeTT @arakhmati

**Comment by arakhmati** [comment]
I don't think we need a tensor handle class. Tensor is already a wrapper around storage. Which basically makes a tensor class a handle to the storage. And storage uses shared ptrs. Can we not just use the shared ptrs from the storage class? And keep the tensor as is. It would keep things simpler

**Comment by tt-asaigal** [comment]
> I don't think we need a tensor handle class. Tensor is already a wrapper around storage. Which basically makes a tensor class a handle to the storage. And storage uses shared ptrs. Can we not just use the shared ptrs from the storage class? And keep the tensor as is. It would keep things simpler

Thanks for the feedback Akhmed. My understanding is that the storage object is extracted from the tensor and can use shared ptrs to store buffer objects. The storage is then used when calling Metal APIs, such as `EnqueueWriteBuffer.` 

Having the worker share ownership of just the storage would not be enough, when it needs access to all tensor fields, including metadata. 

For example: When the worker thread calls `run_device_operation`,  it needs the entire tensor, to access/compute values such as shape, dtype, volume, etc.

A similar logic applies to the Host -> Device write path, where we can have the worker thread calling `to_device` which also needs access to tensor attributes other than storage.

We previously made the storage attribute use shared ptrs, since the workers operated at the metal level, with all other tensor fields accessed only by the main thread. This is no longer the case, since workers would exist at the TT-Lib level for this implementation.

**Comment by davorchap** [comment]
> > I don't think we need a tensor handle class. Tensor is already a wrapper around storage. Which basically makes a tensor class a handle to the storage. And storage uses shared ptrs. Can we not just use the shared ptrs from the storage class? And keep the tensor as is. It would keep things simpler
> 
> 
> 
> Thanks for the feedback Akhmed. My understanding is that the storage object is extracted from the tensor and can use shared ptrs to store buffer objects. The storage is then used when calling Metal APIs, such as `EnqueueWriteBuffer.` 
> 
> 
> 
> Having the worker share ownership of just the storage would not be enough, when it needs access to all tensor fields, including metadata. 
> 
> 
> 
> For example: When the worker thread calls `run_device_operation`,  it needs the entire tensor, to access/compute values such as shape, dtype, volume, etc.
> 
> 
> 
> A similar logic applies to the Host -> Device write path, where we can have the worker thread calling `to_device` which also needs access to tensor attributes other than storage.
> 
> 
> 
> We previously made the storage attribute use shared ptrs, since the workers operated at the metal level, with all other tensor fields accessed only by the main thread. This is no longer the case, since workers would exist at the TT-Lib level for this implementation.

As Aditya suggested, worker thread should owns all of tensor attributes , in fact it seems should probably own the whole thing, and the main thread just has a handle via which it can run accessors.

Architecturally this is headed is a direction of client/server design pattern, worker threads are "tensor servers" and the "main thread" (really a thin client thread) has thin accessors to request tensor data/metadata from the tensor servers.

**Comment by tooniz** [comment]
@tt-asaigal 
> This: interleaved_to_sharded(const Tensor &input_tensor,...) becomes this: interleaved_to_sharded(const TensorHandle &input_tensor,...), so that run_device_operation can be called with shared tensor ownership and passed to the worker.

@arakhmati 
> And keep the tensor as is. It would keep things simpler

Why do we need an explicit TensorHandle class, if we make all users of Tensor use shared_ptr<Tensor> instead, and internally do the same for private members (storage_, shape_, etc) if needed. Does that not get us the best of both worlds?

Any interface to Tensor that now need to become async should no longer accept any references, only either shared_ptr or by-val. You still have the same options originally proposed by Aditya with a shared_ptr<Tensor>

```
// ORIGINAL
inline Tensor to_device(
    const Tensor& tensor,
    Device* target_device,
    const MemoryConfig& memory_config,
    std::optional<std::reference_wrapper<CommandQueue>> queue);
```

becomes 1 or 2 versions

```
// NEW all shared_ptrs
inline shared_ptr<Tensor> to_device(
    shared_ptr<Tensor> tensor,  // shared_ptr
    Device* target_device,
    shared_ptr<MemoryConfig> memory_config,   // shared_ptr
    std::optional<std::reference_wrapper<CommandQueue>> queue);

// NEW some val
inline shared_ptr<Tensor> to_device(
    shared_ptr<Tensor> tensor,   // shared_ptr
    Device* target_device,
    const MemoryConfig memory_config,  // val
    std::optional<std::reference_wrapper<CommandQueue>> queue);
```

Note: target_device and queue lifetimes are not protected either, let's assume user manages those properly for now.

**Comment by tt-asaigal** [comment]
@tooniz and I had an offline discussion based on his comment above. Using `shared_ptr<Tensor> ` for all async functions is also feasible, and may be better, since we're not introducing additional objects/types that the user needs to worry about.

We would do this by exposing only tensor `shared_ptr` at the python level:

`auto pyTensor = py::class_<Tensor, std::shared_ptr<Tensor>>(m_tensor, "Tensor", R"doc(...`

This way, workers can jointly own the tensor.

The main challenge here is that all internal functions in the tensor class use the following mechanics:

```
Tensor Tensor::to(Device *target_device, const MemoryConfig &mem_config) const {
    // Dereference this here and pass tensor by ref -> doesn't matter if we use shared_ptr, since refcount does not get 
    // incremented
    return tensor_impl::to_device_wrapper(*this, target_device, mem_config);
}
```

To get around this, we would have to use `std::enable_shared_from_this` as a base class for `Tensor` and pass `shared_from_this()` to internal functions instead of `this`. The lower level APIs would remain identical to the previous tensor handle approach and would still accept `shared_ptr<Tensor>`.

Code overhaul would still be the same, since ops would now need to accept `shared_ptr<Tensor>`.

@arakhmati wanted to get your thoughts on this, since you implemented most of the existing functionality here.

**Comment by arakhmati** [comment]
I fundamentally don't understand why Approach 2 is considered messy and slow.

To me it's the opposite:
- It requires less code changes.
- Copying the tensor is cheap. We do it all the time. And the underlying buffer is never copied when a copy of Tensor class is made because the storage is always a ptr

But I think I am missing something.
Will the shape, data type and layout of the tensor be set asynchronously now?

**Comment by tt-asaigal** [comment]
> I fundamentally don't understand why Approach 2 is considered messy and slow.
> 
> To me it's the opposite:
> 
> * It requires less code changes.
> * Copying the tensor is cheap. We do it all the time. And the underlying buffer is never copied when a copy of Tensor class is made because the storage is always a ptr
> 
> But I think I am missing something. Will the shape, data type and layout of the tensor be set asynchronously now?

You're right, copying the tensor is cheap due to data itself not being copied, so I guess we shouldn't worry about overhead here. 

The tensor metadata/attributes can be set asynchronously. Example: on the `run_device_operation` path, the workers will generate output tensors and set metadata using `create_output_tensors`, in which case these values will be updated asynchronously and we need to pass a tensor ptr all the way up to the python wrapper.

**Comment by tooniz** [comment]
Yeah I was never that concerned with copying the tensor metadata, you just need shared_ptr to help manage the life-time. Specifically output tensors is the more interesting one, you'd want to allocate it before the contents are actually filled by the worker thread, however if the main thread that has the Tensor goes out of scope, it still needs to be kept alive hence the shared_ptr<Tensor>.

**Comment by arakhmati** [comment]
I understand now. I didn't realize all attributes are set asynchronously. Everything makes sense now

And now I also agree that the first approach is better

**Comment by tooniz** [comment]
@tt-asaigal Had an idea where you have copies of Tensor but all internal fields are shared_ptr<T> so they're all shared under the hood, that minimizes the API changes. Do you see any problems with that approach?

**Comment by tt-asaigal** [comment]
> @tt-asaigal Had an idea where you have copies of Tensor but all internal fields are shared_ptr so they're all shared under the hood, that minimizes the API changes. Do you see any problems with that approach?

Under this implementation, we'd pass tensors by value to all functions, so we're not worried about preemptive deallocation of metadata in the main thread. The use of shared ptrs will facilitate:
1. Storage not being preemptively deallocated (worker increments ref count and holds on to owned/device storage/buffer)
2. Modifications to tensor metadata making it up to the main thread, since each copy of the tensor would point to the same metadata in host memory.

**Comment by arakhmati** [comment]
I don't think we should use shared pointers for every attribute.

@eyonland and I have one more proposal. What about using `std::promise<Tensor>`? It seems like it fits this use case perfectly

**Comment by tt-asaigal** [comment]
> I don't think we should use shared pointers for every attribute.
> 
> @eyonland and I have one more proposal. What about using `std::promise<Tensor>`? It seems like it fits this use case perfectly

Is the suggestion to use `std::promise<Tensor>` when returning args from the worker to the main thread? It won't make sense to use this when passing tensors from main to worker, since we can't guarantee joint ownership this way + we don't have an associated future here. 

The only bonus of using a promise here seems to be that we'd automatically know when data is ready by calling `promised_tensor.get_future()`.

Is my understanding here correct?

**Comment by arakhmati** [comment]
I think we should jump on a zoom call and discuss the options by looking at the code

**Comment by davorchap** [comment]
Another aspects to consider -- the client thread API should look the same even if the tensor is on a different server. Same APIs but also for multi-server/multi-Galaxy scale.

**Comment by eyonland** [comment]
@tt-asaigal and @tooniz , is it possible to include some sort of tracing that would run without impacting performance and still give the ability to see that operation that was last being run on the device.   See  #6362  for refefrence.

**Comment by tt-asaigal** [comment]
> @tt-asaigal and @tooniz , is it possible to include some sort of tracing that would run without impacting performance and still give the ability to see that operation that was last being run on the device. See #6362 for reference. I'm for the currently active op for a device to simply be tracked and easily recovered during an exception or a hang. Not full trace capability.

Yeah I think we should be able to do something like this. I'm working on the async implementation now and we'll have a worker queue per device. Similarly we can have an op vector/data structure per device that gets appended to each time we call `run_device_operation`. In the case of an exception in a specific thread, we can report the ops that ran so far on the device along with the error.

**Comment by tt-asaigal** [comment]
Hey everyone, I've pushed an initial implementation for fully asynchronous execution to [asaigal/tt_lib_async_mode](https://github.com/tenstorrent-metal/tt-metal/tree/asaigal/tt_lib_async_mode).

E2E tests that I ran pass with this implementation (I tested the entire attention matmul suite that covers multiple different ops and basic C++ op tests).

I'd appreciate some feedback on a few design decisions I've made here:
1. The worker queue and worker thread are per device. I've added these objects to the device class and a top level function can push to the queue through the device handle. This allows us to scale across multiple devices.
2. Only host <--> device paths go through the worker thread, since we need a device handle. This means that any tensor operations running purely on host will be synchronously executed, since the tensors they use are device agnostic.

```
Example: 
# Create host tensor
tt_input_tensor_host =  ttl.tensor.Tensor(input_tensor_a, in0_dtype)

# Host -> Host operation run synchronously
tt_input_tensor_host_tilized = tt_input_tensor_host.to(ttl.tensor.Layout.TILE)

# Host -> Device operation run asynchronously
device_tensor = tt_input_tensor_host_tilized.to(device, interleaved_mem_config)

# Send Workload from host -> device run asynchronously
device_tensor = ttl.tensor.interleaved_to_sharded(device_tensor, ...)

# Blocking Device -> Host operation, goes through worker but is synchronous
read_back = device_tensor.cpu()
```

3. The current implementation tries to make the main thread as lightweight as possible, by placing any computation required for an Op on the worker. This means that:

```
Tensor group_attn_matmul(Tensor& input_a, Tensor& input_b) {
      auto params = COMPUTE_SHARD_AND_KERNEL_PARAMETERS();
      return operation::run(GroupAttnMatmul(params), {input_a, input_b});
}
```

becomes:

```
Tensor group_attn_matmul(Tensor& input_a, Tensor& input_b) {
      // Create tensor handle to be populated later by worker
      Tensor output_tensor;

      // Push op creation and enqueue to worker
      input_tensor_a.device()->push_work([input_tensor_a, input_tensor_b, output_tensor] () mutable {
               auto params = COMPUTE_SHARD_AND_KERNEL_PARAMETERS();
               auto local_tensor = operation::run(GroupAttnMatmul(params), {input_a, input_b});
               // Asynchronously populate the output sent to the main thread
               populate_output_tensor(output_tensor, local_tensor);
      });
      return output_tensor;
}
```

This gives us a clear separation between the main and worker threads, where the worker owns the creation of all ops. This also allows for more parallelization of work. The main drawback here is that we'll need to update the top-level calls for all ops to use the worker thread.

Please lmk your thoughts. In the meantime, I'll make my changes BW compatible and make tensor accessors spin until the tensor is populated.

**Comment by tt-asaigal** [comment]
Support added and under active testing.
