### ISSUE TITLE
Investigate ttnn / tt_lib Python bindings not re-building when an underlying C++ file is changed

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#6314]
Reported by @TT-BrianLiu  - he's seeing that for an already built metal, further changes to `ttnn/cpp/ttnn/operations/matmul.hpp` and then invoking `make build` does not result in changes being picked up

**Comment by TT-billteng** [comment]
we've switched to CMake, hopefully this is less of an issue now
