### ISSUE TITLE
watcher error with `test_moreh_groupnorm`

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#6319]
Happens on GS or WH

`TT_METAL_WATCHER=60 pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_groupnorm.py::test_moreh_groupnorm`

`TT_METAL_WATCHER=60 pytest 
tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_groupnorm.py::test_moreh_groupnorm_backward`

**Comment by jliangTT** [comment]
@razorback3 , do you mind help getting someone assigned to work on this?

**Comment by razorback3** [comment]
@seunghwan100 Would you take a look?

**Comment by razorback3** [comment]
@jliangTT

**Comment by razorback3** [comment]
@jliangTT 
One of our team's engineer says this problem might be related to #5868 and guesses that same reason with #5868.
Why don't we wait for #5868 to be resolved and then look this up again later?

**Comment by jliangTT** [comment]
being debugged in #5868
