### ISSUE TITLE
Demo for Bloom

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent/tt-metal#6343]
Update the bloom demo to be compatible with the ttnn_functional_bloom model.

**Comment by Sudharsan-V** [comment]
The demo for bloom_causal_lm is completed.
corresponding PR: [#6488](https://github.com/tenstorrent-metal/tt-metal/pull/6488)

The demo for bloom_QA is in progress.

**Comment by kkeerthana0573** [comment]
Demo for bloom_qa :

Dataset used for BloomForQuestionAnswering - SQuAD
Metrics used: 
- With ttnn_functional_bloom :
Exact Score - 0.0
F1 Score - 2.0357872506696952
- With ttnn_optimized_functional_bloom :
Exact Match - 0.0
F1 Score - 2.5764411027568923

Here are the results when ttnn_optimized_functional_bloom is used:

> Question: What discipline did Winkelmann create?
> Answer:  did Winkelmann create?Johann Joachim Winckelmann was a German art historian and archaeologist. He was a pioneering Hellenist who first articulated

> Question: What is the process in which neutrophils move towards the site of inflammation called?
> Answer:  the process in which neutrophils move towards the site of inflammation called?Neutrophils and macrophages are phagocytes

Corresponding commit - [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...keerthana/functional_bloom_qa_demo)

**Comment by saichandax** [comment]
Updates are in the doc [here](https://docs.google.com/document/d/17Ctd_mBPrvlEPEQtxqSluyVVjw-XmlwGiZv0H_3DchQ/edit)

**Comment by jayasuryamaganuru** [comment]
Commit for single bloom_block analysis using allclose metric -  [link](https://github.com/tenstorrent-metal/tt-metal/compare/jayasurya/bloom_block_analysis)

**Comment by boris-drazic** [comment]
Looking at all close results, atol_delta seems to be very large compared to the range of data values.
For instance `post_attention_layernorm` has absolute difference between ttnn and PyTorch of 5.31 while values are in range -4.65 to 4.77.
Can you take a look at actual tensor values and what is the magnitude of them? Do these large differences make sense?
Is there only a few values that are very different and the rest are a good match?
For `self_attention.query_key_value` and `post_attention_layernorm`, can you add to spreadsheet input and output tensors for each and matching tensors from PyTorch so we can plot and comapre them value by value.
(It is probably enough to just put values for one selection of last two dims, i.e., [1, 1, :, :]).

**Comment by jayasuryamaganuru** [comment]
The observations, plots are recorded in the sheet - [link](https://docs.google.com/spreadsheets/d/1KP_q_qCQsnIMZZMMKMdEatItdX9tH-CZXX9FZJftAls/edit?usp=sharing)

**Comment by jayasuryamaganuru** [comment]
Bloom block opwise analysis can be done with this commit - [link](https://github.com/tenstorrent-metal/tt-metal/commit/2180cb21ef07a678923abe65e237ed2c54114149)

Real inputs are fed to bloom block , and the results are updated in the 
allclose analyis  [sheet](https://docs.google.com/spreadsheets/d/1aw2NGBVNBRA1KCeIoeKddobPr356Nl-mLYjRyBdWSYo/edit#gid=1086984055) 

Scatterplots, histograms with better details are updated in [plots doc](https://docs.google.com/document/d/1KZ6mUQMkWWJQUhVQ1_OkohaU1wMNt5o46tkOgEP8PBk/edit)

**Comment by jayasuryamaganuru** [comment]
From allclose results, plots these things caught the attention,

1.

**Comment by jayasuryamaganuru** [comment]
The observations from the above data / plots:

1. Divergence from torch result started from self_attention.query_key_value which is the output of Linear layer, debugging this pcc drop , arrived at the custom preprocessor where original weights are reshaped, sliced, concatenated. since these processed weights arrangement differ from torch weights, I believe it's the reason for drop in PCC.

2. In the next intermediate outputs,  self_attention.attention_probs, self_attention.context_matmul, self_attention..context_layer, though the PCC ~ 0.999. scatterplots, distribution historgram shows the intermediate tensors for torch and ttnn differ greatly.

**Comment by Sudharsan-V** [comment]
The pcc for the bloom_QA model is improved. The following changes improved the pcc of the model

- Replace the method compute_attention_probes in pytorch
- Fused linear in the bloom mlp is broken to individual ttnn ops.

These changes helps to improve the pcc.
PFA the results in the [bloom_QA_real_inputs](https://docs.google.com/spreadsheets/d/1aw2NGBVNBRA1KCeIoeKddobPr356Nl-mLYjRyBdWSYo/edit#gid=610992017)
Corresponding: [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...punith/bloom_debug)

**Comment by punithsekar** [comment]
Created demo file for functional bloom qa model.
Corresponding PR #7293

**Comment by jayasuryamaganuru** [comment]
PR for updated README.md file of functional bloom model for question answering - #7411

**Comment by jayasuryamaganuru** [comment]
Results of bloom QA model for the following cases are updated in the [sheet](https://docs.google.com/spreadsheets/d/1ZmEkZ0Rs8muHBHhe2apmM_1SuDDbLc9gJPZLpey40VU/edit?usp=sharing)

1.  bfloat8 (main branch)
2. bfloat16 ([commit](https://github.com/tenstorrent/tt-metal/compare/main...punith/bloom_qa_with_different_dtype))
3. bfloat16 + ttnn linear replace with matmul, add ([commit](https://github.com/tenstorrent/tt-metal/commit/d24288bf95a647963ba2047d02fa021322f9bdc2)

**Comment by Sudharsan-V** [comment]
Bloom Demo is merged with main.
Corresponding PRs [#8391](https://github.com/tenstorrent/tt-metal/pull/8391), [#8431](https://github.com/tenstorrent/tt-metal/pull/8431)
Hence closing this issue/ticket.
