### ISSUE TITLE
Some ttnn operations are missing memory_config parameter

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#6350]
Most ttnn operations are having `memory_config: ttnn.MemoryConfig = ttnn.DRAM_MEMORY_CONFIG` parameter. For example:

https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/ttnn/signbit.html

But some operations are missing it. Like:

```
permute
reshape
rmsnorm
repeat_interleave
global_avg_pool2d
split
```

**Comment by jliangTT** [comment]
do we know the complete list so we can assign each kernel developer to add?

**Comment by nemanjagrujic** [comment]
@jliangTT The complete list is in the ticket to best of our knowledge.

**Comment by Aswinmcw** [comment]
Closing as memory config parameter is not needed for these ops
