### ISSUE TITLE
Add ability to tag enqueued commands so that we can report what exactly finished

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent/tt-metal#6362]
Currently there is no way to find out exactly which programs finished. A possible solution is to add some form of tag when you enqueue, and when the completion thread finishes said event, it can report the tag that was submitted.

Example:
```
Tag tag("ProgramName");
EnqueueProgram(cq, program, /* blocking */ false, tag);
```
When completion thread finishes this program, it can report the tag "ProgramName".

In run_operation.cpp, we can call 
```
EnqueueProgram(..., /* DeviceOperation */ operation.get_type_name());
```

**Comment by jliangTT** [comment]
@tooniz to triage.
