### ISSUE TITLE
Metal tests for Sharded Read Writes in Dispatch

### ISSUE THREAD

**Issue by tarafdarTT** [tenstorrent/tt-metal#6419]

**Comment by jliangTT** [comment]
lmk if i triaged to the rigth board.

**Comment by davorchap** [comment]
To be done as part of FD2

**Comment by davorchap** [comment]
@tt-aho we have gtests now, should we close?

**Comment by tt-aho** [comment]
I'm going to leave it open for now as I need to add >64k page sized tests for sharding once we add support. Will also do some cleanup/reorg of the test cases
