### ISSUE TITLE
Llama2 70B Prefill MLP 

### ISSUE THREAD

**Issue by caixunshiren** [tenstorrent/tt-metal#6423]
Tracking Llama2 70B Prefill MLP here. 

Goal: 32 users, 128 sequence length MLP performant prefill

Tasks:
- Prefill MLP test cases
- Prefill MLP functionality
- Prefill MLP Perf

FYI @cglagovich @mikevin920

**Comment by caixunshiren** [comment]
Added MLP functionality and rebased to main. Adding a merge request rn

**Comment by caixunshiren** [comment]
The Prefill MLP has PCC of 0.988 and is waiting on #6556 to resolve the compatibility of ttlib.ops.primary.matmul to support fp32 accumulate so that PCC can get even higher.

**Comment by caixunshiren** [comment]
Latest commit exposed that #6556 can be worked around with custom program config, but it also shows that fp32 accurate is too big to fit into L1

**Comment by uaydonat** [comment]
@cglagovichTT close?
