### ISSUE TITLE
[Bug Report] Uninitialized memory written to cq_sysmem

### ISSUE THREAD

**Issue by joelsmithTT** [tenstorrent/tt-metal#6428]
**Describe the bug**
The data array in `DeviceCommand::packet_` is not initialized.  This can result in unexpected data being written to sysmem when `SystemMemoryManager::cq_write` is called.

**To Reproduce**
1. Optional: Modify UMD to zero hugepage memory after it is mapped into the application address space.
2. Build and run the `programming_examples/loopback`.
3. Examine the contents of a hugepage after the `loopback` program is finished.  Examples below.  Exact behavior may differ system to system.

**Expected behavior**
Did not expect to see logging messages from the application in sysmem.

**Screenshots**
The message is [from a log statement in the application](https://github.com/tenstorrent-metal/tt-metal/blob/7a79c3163707cd08bbd59edc02388d27b8653bd0/tt_metal/common/bfloat16.hpp#L136).
```
$ hexdump -C /dev/hugepages-1G/tenstorrent -s 0x00003710 -n 64
00003710  f4 01 00 00 00 00 00 00  43 72 65 61 74 65 64 20  |........Created |
00003720  61 20 72 61 6e 64 6f 6d  20 76 65 63 74 6f 72 20  |a random vector |
00003730  6f 66 20 73 69 7a 65 20  32 35 36 30 30 7c 20 00  |of size 25600| .|
00003740  f8 5f 37 ff c4 7f 00 00  60 96 e4 f0 ff 7f 00 00  |._7.....`.......|
00003750
```
This message is from a print statement I enabled in UMD:
```
$ hexdump -C /dev/hugepages-1G/tenstorrent -s 0x00002b20 -n 128
00002b20  20 41 d7 d8 86 55 00 00  2d 2d 2d 2d 20 74 74 53  | A...U..---- ttS|
00002b30  69 6c 69 63 6f 6e 44 65  76 69 63 65 3a 3a 69 6e  |iliconDevice::in|
00002b40  69 74 5f 68 75 67 65 70  61 67 65 3a 20 70 68 79  |it_hugepage: phy|
00002b50  73 69 63 61 6c 5f 64 65  76 69 63 65 5f 69 64 3a  |sical_device_id:|
00002b60  20 30 20 63 68 3a 20 30  20 6d 61 70 70 69 6e 67  | 0 ch: 0 mapping|
00002b70  5f 73 69 7a 65 3a 20 31  30 37 33 37 34 31 38 32  |_size: 107374182|
00002b80  34 20 70 68 79 73 69 63  61 6c 20 61 64 64 72 65  |4 physical addre|
00002b90  73 73 20 30 78 66 63 30  30 30 30 30 30 30 0a 00  |ss 0xfc0000000..|
```

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Version of software: 926415b3ee4d417d4e28cb7a677fb2b29d608409
- Grayskull

**Additional context**
This is probably innocuous but it can be fixed by initializing the aforementioned array:
```
diff --git a/tt_metal/impl/dispatch/device_command.hpp b/tt_metal/impl/dispatch/device_command.hpp
index e94cadaf6..f4858be8d 100644
--- a/tt_metal/impl/dispatch/device_command.hpp
+++ b/tt_metal/impl/dispatch/device_command.hpp
@@ -215,7 +215,7 @@ class DeviceCommand {

     struct packet_ {
         CommandHeader header;
-        std::array<uint32_t, DeviceCommand::NUM_ENTRIES_IN_DEVICE_COMMAND - DeviceCommand::NUM_ENTRIES_IN_COMMAND_HEADER> data;
+        std::array<uint32_t, DeviceCommand::NUM_ENTRIES_IN_DEVICE_COMMAND - DeviceCommand::NUM_ENTRIES_IN_COMMAND_HEADER> data{};
     };

     packet_ packet;
```

**Comment by jliangTT** [comment]
triage this to the top of the funnel. @joelsmithTT , how critical is this?

**Comment by joelsmithTT** [comment]
I doubt it is causing any problems if nothing is actually reading that memory, but it is undefined behavior and it did cause me a bit of confusion.  I can open a pull request.

**Comment by jliangTT** [comment]
CQ sounds like a runtime thing. I will put it in the runtime board while you investigate.

**Comment by davorchap** [comment]
Thanks @joelsmithTT . Placing under FD2 board as well, to be reviewed is this is an issue in FD2.

**Comment by pgkeller** [comment]
adding Almeet as she is working on host code

**Comment by tooniz** [comment]
This made life difficult for me for metal trace debug, so I put in a fix to zero init the commands written to device.

It's merged to fd-2/main, https://github.com/tenstorrent/tt-metal/pull/7634
```
Commands leave may padding and reserved fields uninitialized, leading to non-deterministic data seen in the issue queue. This should not create functional issues if host and dispatcher/prefetcher correctly populate and consume valid fields.

However having un-initialized invalid fields leads to a bad time for debugging, and serializing the CQ to trace buffer or to disk also results in different binaries.

This change will introduce zero init by default, it can be disabled using TT_METAL_ZERO_INIT_DISABLE=1 for stress testing in nightly/random regressions.
```
