### ISSUE TITLE
Backward operations support

### ISSUE THREAD

**Issue by umadevimcw** [tenstorrent/tt-metal#6443]
Add backward operations support for following ops

- [x] #3900 
- [x] #4858 
- [x] #6285 
- [x] #6063 
- [x] #6132 
- [x] #6055 
- [x] #6061 
- [x] #5646 
- [x] #5511 
- [x] #5510 
- [x] #5679 
- [x] #5474 
- [x] #5822 
- [x] #5825 
- [x] #6004 
- [x] #3893 
- [x] #3896 
- [x] #4338 
- [x] #4338 
- [x] #6055 
- [x] #6061 
- [x] #6062 
- [x] #6107 
- [x] #6132 
- [x] #6133 
- [x] #6155 
- [x] #6236 
- [x] #6234 
- [x] #6226 
- [x] #6121 
- [x] #6120 
- [x] #6119 
- [x] #6057 
- [x] #6056 
- [x] #6007 
- [x] #6005 
- [x] #5954 
- [x] #5951 
- [x] #5894 
- [x] #5879 
- [x] #5811 
- [x] #5810 
- [x] #5761 
- [x] #5751 
- [x] #5682 
- [x] #5645 
- [x] #5643 
- [x] #4996 
- [x] #3894 
- [x] #4338 
- [x] #4341 
- [x] #4377 
- [x] #5520 
- [x] #5840 
- [x] #5885 
- [x] #5947 
- [x] #5961 
- [x] #6001 
- [x] #4289 
- [x] #6066 
- [x] #6136 
- [x] #6123 
- [x] #6117 
- [x] #4998 
- [x] #5687 
- [x] #5824 
- [x] #5825 
- [x] #5888 
- [x] #5889 
- [x] #5890 
- [x] #5989 
- [x] #6116 
- [x] #6146 
- [x] #6284 
- [x] #6493 
- [x] #6382 
- [x] #6383 
- [x] #6405 
- [x] #6533
- [x] #6534 
- [x] #6536 
- [x] #6598 
- [x] #6589 
- [ ] #6583 
- [x] #5813 
- [x] #6816 
- [x] #6827 
- [x] #6903 
- [x] #6911 
- [x] #6931
- [x] #6943
- [x] #7229 
- [x] #7192 
- [x] #7188

**Comment by umadevimcw** [comment]
@eyonland Created primary issue for output arguments task. If this is the expectation we can follow this for the rest of the tasks as well

**Comment by jliangTT** [comment]
already subscribed. will take myself off the owner.

**Comment by Aswinmcw** [comment]
Hi @eyonland @razorback3 , while implementing div_no_nan backward op, we need some clarifications on the requirements for this op, we have opened a [PR](https://github.com/tenstorrent-metal/tt-metal/pull/6290) for this, can you please check the current implementation of the div_no_nan op then give us the suggestions to be modified?

**Comment by VirdhatchaniKN** [comment]
Hi @eyonland , @razorback3 ,
The below list of ops have no gradient available. We have updated the same in the sheet

1. ElemwiseBinary/ELEMWISE_BINARY_GCD 
2. ElemwiseBinary/ELEMWISE_BINARY_HEAVISIDE
3. ElemwiseUnary/ELEMWISE_UNARY_HEAVISIDE   
4. ElemwiseBinary/ELEMWISE_BINARY_LCM 
5. ElemwiseUnary/ELEMWISE_UNARY_SIGNBIT 
6. ElemwiseBinary/ELEMWISE_BINARY_LOGICALANDI 
7. ElemwiseBinary/ELEMWISE_BINARY_LOGICALAND 
8. ElemwiseBinary/ELEMWISE_BINARY_LOGICALOR 
9. ElemwiseBinary/ELEMWISE_BINARY_LOGICALORI 
10. ElemwiseBinary/ELEMWISE_BINARY_LOGICALXOR 
11. ElemwiseBinary/ELEMWISE_BINARY_LOGICALXORI 
12. ElemwiseUnary/ELEMWISE_UNARY_LOGICALNOT 
13. ElemwiseUnary/ELEMWISE_UNARY_LOGICALNOTI 
14. ElemwiseUnary/ELEMWISE_UNARY_BITWISEAND 
15. ElemwiseUnary/ELEMWISE_UNARY_BITWISENOT 
16. ElemwiseUnary/ELEMWISE_UNARY_BITWISEOR 
17. ElemwiseUnary/ELEMWISE_UNARY_BITWISEXOR 
18. ElemwiseBinary/ELEMWISE_BINARY_BITWISEAND 
19. ElemwiseBinary/ELEMWISE_BINARY_BITWISEOR 
20. ElemwiseBinary/ELEMWISE_BINARY_BITWISEXOR 
21. ElemwiseUnary/ELEMWISE_UNARY_ISFINITE 
22. ElemwiseUnary/ELEMWISE_UNARY_ISINF 
23. ElemwiseUnary/ELEMWISE_UNARY_ISNAN 
24. ElemwiseBinary/ELEMWISE_BINARY_ISCLOSE 
25. ElemwiseBinary/ELEMWISE_BINARY_ISCLOSENAN
26. ElemwiseUnary/ELEMWISE_UNARY_ISNEGINF 
27. ElemwiseUnary/ELEMWISE_UNARY_ISPOSINF 
28. ElemwiseUnary/ELEMWISE_UNARY_ISREAL 
29. ElemwiseUnary/ELEMWISE_UNARY_LEFT_SHIFT 
30. ElemwiseBinary/ELEMWISE_BINARY_LEFT_SHIFT 
31. ElemwiseUnary/ELEMWISE_UNARY_RIGHT_SHIFT 
32. ElemwiseBinary/ELEMWISE_BINARY_RIGHT_SHIFT 
33. ElemwiseBinary/ELEMWISE_BINARY_NEXTAFTER 

<img width="1235" alt="Screenshot 2024-03-18 at 5 30 50 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/138196495/39dfa0c6-f614-4467-9d40-66e6427f9b8d">

**Comment by VirdhatchaniKN** [comment]
Hi @eyonland  , @razorback3  ,
The below list of ops have no gradient available. We have updated the same in the sheet

1. ElemwiseBinary/ELEMWISE_BINARY_GCD
2. ElemwiseBinary/ELEMWISE_BINARY_HEAVISIDE
3. ElemwiseUnary/ELEMWISE_UNARY_HEAVISIDE
4. ElemwiseBinary/ELEMWISE_BINARY_LCM
5. ElemwiseUnary/ELEMWISE_UNARY_SIGNBIT
6. ElemwiseBinary/ELEMWISE_BINARY_LOGICALANDI
7. ElemwiseBinary/ELEMWISE_BINARY_LOGICALAND
8. ElemwiseBinary/ELEMWISE_BINARY_LOGICALOR
9. ElemwiseBinary/ELEMWISE_BINARY_LOGICALORI
10. ElemwiseBinary/ELEMWISE_BINARY_LOGICALXOR
11. ElemwiseBinary/ELEMWISE_BINARY_LOGICALXORI
12. ElemwiseUnary/ELEMWISE_UNARY_LOGICALNOT
13. ElemwiseUnary/ELEMWISE_UNARY_LOGICALNOTI
14. ElemwiseUnary/ELEMWISE_UNARY_BITWISEAND
15. ElemwiseUnary/ELEMWISE_UNARY_BITWISENOT
16. ElemwiseUnary/ELEMWISE_UNARY_BITWISEOR
17. ElemwiseUnary/ELEMWISE_UNARY_BITWISEXOR
18. ElemwiseBinary/ELEMWISE_BINARY_BITWISEAND
19. ElemwiseBinary/ELEMWISE_BINARY_BITWISEOR
20. ElemwiseBinary/ELEMWISE_BINARY_BITWISEXOR
21. ElemwiseUnary/ELEMWISE_UNARY_ISFINITE
22. ElemwiseUnary/ELEMWISE_UNARY_ISINF
23. ElemwiseUnary/ELEMWISE_UNARY_ISNAN
24. ElemwiseBinary/ELEMWISE_BINARY_ISCLOSE
25. ElemwiseBinary/ELEMWISE_BINARY_ISCLOSENAN
26. ElemwiseUnary/ELEMWISE_UNARY_ISNEGINF
27. ElemwiseUnary/ELEMWISE_UNARY_ISPOSINF
28. ElemwiseUnary/ELEMWISE_UNARY_ISREAL
29. ElemwiseUnary/ELEMWISE_UNARY_LEFT_SHIFT
30. ElemwiseBinary/ELEMWISE_BINARY_LEFT_SHIFT
31. ElemwiseUnary/ELEMWISE_UNARY_RIGHT_SHIFT
32. ElemwiseBinary/ELEMWISE_BINARY_RIGHT_SHIFT
33. ElemwiseBinary/ELEMWISE_BINARY_NEXTAFTER

<img width="1234" alt="Screenshot 2024-03-18 at 5 43 02 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/138196495/dddeb41f-a773-459a-99f5-5bea1ff6697a">

**Comment by jliangTT** [comment]
> Hi @eyonland , @razorback3 , The below list of ops have no gradient available. We have updated the same in the sheet
> 
> 1. ElemwiseBinary/ELEMWISE_BINARY_GCD
> 2. ElemwiseBinary/ELEMWISE_BINARY_HEAVISIDE
> 3. ElemwiseUnary/ELEMWISE_UNARY_HEAVISIDE
> 4. ElemwiseBinary/ELEMWISE_BINARY_LCM
> 5. ElemwiseUnary/ELEMWISE_UNARY_SIGNBIT
> 6. ElemwiseBinary/ELEMWISE_BINARY_LOGICALANDI
> 7. ElemwiseBinary/ELEMWISE_BINARY_LOGICALAND
> 8. ElemwiseBinary/ELEMWISE_BINARY_LOGICALOR
> 9. ElemwiseBinary/ELEMWISE_BINARY_LOGICALORI
> 10. ElemwiseBinary/ELEMWISE_BINARY_LOGICALXOR
> 11. ElemwiseBinary/ELEMWISE_BINARY_LOGICALXORI
> 12. ElemwiseUnary/ELEMWISE_UNARY_LOGICALNOT
> 13. ElemwiseUnary/ELEMWISE_UNARY_LOGICALNOTI
> 14. ElemwiseUnary/ELEMWISE_UNARY_BITWISEAND
> 15. ElemwiseUnary/ELEMWISE_UNARY_BITWISENOT
> 16. ElemwiseUnary/ELEMWISE_UNARY_BITWISEOR
> 17. ElemwiseUnary/ELEMWISE_UNARY_BITWISEXOR
> 18. ElemwiseBinary/ELEMWISE_BINARY_BITWISEAND
> 19. ElemwiseBinary/ELEMWISE_BINARY_BITWISEOR
> 20. ElemwiseBinary/ELEMWISE_BINARY_BITWISEXOR
> 21. ElemwiseUnary/ELEMWISE_UNARY_ISFINITE
> 22. ElemwiseUnary/ELEMWISE_UNARY_ISINF
> 23. ElemwiseUnary/ELEMWISE_UNARY_ISNAN
> 24. ElemwiseBinary/ELEMWISE_BINARY_ISCLOSE
> 25. ElemwiseBinary/ELEMWISE_BINARY_ISCLOSENAN
> 26. ElemwiseUnary/ELEMWISE_UNARY_ISNEGINF
> 27. ElemwiseUnary/ELEMWISE_UNARY_ISPOSINF
> 28. ElemwiseUnary/ELEMWISE_UNARY_ISREAL
> 29. ElemwiseUnary/ELEMWISE_UNARY_LEFT_SHIFT
> 30. ElemwiseBinary/ELEMWISE_BINARY_LEFT_SHIFT
> 31. ElemwiseUnary/ELEMWISE_UNARY_RIGHT_SHIFT
> 32. ElemwiseBinary/ELEMWISE_BINARY_RIGHT_SHIFT
> 33. ElemwiseBinary/ELEMWISE_BINARY_NEXTAFTER
> 
> <img alt="Screenshot 2024-03-18 at 5 46 15 PM" width="1241" src="https://private-user-images.githubusercontent.com/138196495/313674147-349f67b2-ee8c-4d03-88ac-75cf39e03c08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzU2NDksIm5iZiI6MTcxMDc3NTM0OSwicGF0aCI6Ii8xMzgxOTY0OTUvMzEzNjc0MTQ3LTM0OWY2N2IyLWVlOGMtNGQwMy04OGFjLTc1Y2YzOWUwM2MwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxNTIyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGU0YTc4MjI1OTY2YjJjMzRjNjAxYzhhNTdkOGIyNTA3YWRlZDNlYjAzM2E4MzQ1YmVjZjBlNDRiYjJjODY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UicDPK8NrGOsgNjTnHn416QG6aTbpCIdb77S6Mn_BkU">

@razorback3 , please comment on the limitation and how it affects the compiler.

**Comment by razorback3** [comment]
> @razorback3 , please comment on the limitation and how it affects the compiler.

@hschoi4448 is taking a look on this issue. He will soon leave the feedback.

**Comment by Aswinmcw** [comment]
Hi @razorback3 , for implementing backward op for bitmask version of relu, we need some clarification on the requirement of the op, can you share any reference for it if you have? as relu gives output of max(0,x), does it have any bitmask version?

**Comment by razorback3** [comment]
> Hi @razorback3 , for implementing backward op for bitmask version of relu, we need some clarification on the requirement of the op, can you share any reference for it if you have? as relu gives output of max(0,x), does it have any bitmask version?

Would you check the below document?
https://docs.google.com/document/d/1eVCEF0mU7KtczbnaRz7u4XJlwFhKc1DLUC9cNC07byI/edit?usp=sharing
Feel free to ask me if you are not familiar enough with the above document.

**Comment by Aswinmcw** [comment]
> > Hi @razorback3 , for implementing backward op for bitmask version of relu, we need some clarification on the requirement of the op, can you share any reference for it if you have? as relu gives output of max(0,x), does it have any bitmask version?
> 
> Would you check the below document? https://docs.google.com/document/d/1eVCEF0mU7KtczbnaRz7u4XJlwFhKc1DLUC9cNC07byI/edit?usp=sharing Feel free to ask me if you are not familiar enough with the above document.

@razorback3 Thanks for sharing the doc, but it is not accessible from my side, can you please check it and share it with me?

**Comment by Aswinmcw** [comment]
> > > > Hi @razorback3 , for implementing backward op for bitmask version of relu, we need some clarification on the requirement of the op, can you share any reference for it if you have? as relu gives output of max(0,x), does it have any bitmask version?
> > > 
> > > 
> > > Would you check the below document? https://docs.google.com/document/d/1eVCEF0mU7KtczbnaRz7u4XJlwFhKc1DLUC9cNC07byI/edit?usp=sharing Feel free to ask me if you are not familiar enough with the above document.
> > 
> > 
> > @razorback3 Thanks for sharing the doc, but it is not accessible from my side, can you please check it and share it with me?
> 
> Would you tell me your tenstorrent email address?

Sure here it is,
azayasankaran@tenstorrent.com
udselvaraj@tenstorrent.com

**Comment by razorback3** [comment]
Please check :)

**Comment by Aswinmcw** [comment]
> Please check :)

Got it thanks

**Comment by razorback3** [comment]
@jliangTT Seems like @Aswinmcw do not have access permission to the entire shared drive of Moreh-TT.
I gave him a permission to the above mentioned doc only for right now.

**Comment by hschoi4448** [comment]
> Hi @eyonland , @razorback3 , The below list of ops have no gradient available. We have updated the same in the sheet
> @razorback3 , please comment on the limitation and how it affects the compiler.

The ops in the list appear to be ops for which backward does not exist in PyTorch.
For ops in PyTorch where backward does not exist, there is no problem even if backward is not implemented in TT.

**Comment by razorback3** [comment]
We found 2 issues in the current backward implementation:
- https://github.com/tenstorrent-metal/tt-metal/issues/6533
- https://github.com/tenstorrent-metal/tt-metal/issues/6534

**Comment by umadevimcw** [comment]
@razorback3 Will look into this and push the fix.

**Comment by umadevimcw** [comment]
@hschoi4448 @razorback3 Please find PR #6542 with the fixes for above ops

**Comment by KalaivaniMCW** [comment]
Hi @eyonland , @razorback3, 
The below list of backward support for complex ops are implemented for Type 1 complex tensor as of now ( yet to be implemented for type 2 complex tensor )
- conj
- imag
- real
- complex add
- complex sub
- complex mul
- complex recip

**Comment by KalaivaniMCW** [comment]
**Regarding sin_bw and cos_bw:**
- sin_bw and cos_bw use the forward op cos() and sin() respectively which have a range of 0 to 2*pi.
- In torch, for values beyond 2*pi, the result from (input % 2*pi) is used for cos() and sin() operation.
- In TT, there is no support for % operator or floor. 
For such cases, what could be done? 
-should we have an assert statement mentioning about the input range?

**Comment by eyonland** [comment]
Closing given all tasks completed.
