### ISSUE TITLE
Unet: e2e investigation

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-metal#6465]
We need to investigate why host perf is so slow, limiting us to 27 fps.  Some notes:

- Use Tracy for initial debug
    - Ignore the first couple “frames” in tracy since those are warmup where we should be hitting compile
```bash
python tests/ttnn/integration_tests/unet/test_ttnn_shallow_unet.py --loop 10
```
 - Program cache is disabled by default #6180, we need to enable it
   - When I tried enabling it crashed in upsample program update somewhere, so that’s a bug that’ll likely need to be fixed (feel free to debug or file a P1)

**Comment by smehtaTT** [comment]
Closing as discussed in 9/4 meeting
