### ISSUE TITLE
Enable simpler installation and installation into system Python

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#6576]
This likely means:

- Getting the wheel working and verifying its packages exist in any environment, system or virtual
- Combining the `setup.py`
- Ensuring that editable install still works

#6482 related to this

cc: @eyonland @arakhmati @TT-billteng

**Comment by tt-rkim** [comment]
A couple of high-level directives for future wheel:

- move `tt_eager` into `ttnn/experimental` or something similar
- combine python bindings of `tt_lib` and `ttnn` so we have one SO
- remove any forced rpath / `patchelf` changes during `__init__.py` setup of installed wheel environment

**Comment by TT-billteng** [comment]
@tt-rkim says the wheel works!
