### ISSUE TITLE
`CommandQueueMultiDeviceFixture.Eth*` tests hang

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#6616]
This is non-deterministic and may only hang on some machines

https://github.com/tenstorrent-metal/tt-metal/actions/runs/8363470635/job/22900315144

**Comment by vtangTT** [comment]
On N300 bm any one of `CommandQueueMultiDeviceFixture.Eth*` tests will ND hang the board

`sudo reboot` and/or `tt-smi-metal -r 0` before or after seems to leave the board in a bad state and these eth tests will hang

Can reliably reproduce by: 

1. `sudo reboot`
2. run `build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=CommandQueueMultiDeviceFixture.Eth* --gtest_repeat=-1` 
3. observe hang, usually on one of the first three tests: 
`EthKernelsDirectSendAllConnectedChips`
`EthKernelsSendDramBufferAllConnectedChips`
`EthKernelsSendInterleavedBufferAllConnectedChips`

Can also observe this hang without reboot: 

1. `tt-smi-metal -r 0`
2. run `build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=CommandQueueMultiDeviceFixture.Eth*` a couple of times
3. will eventually hang 

CC: @TT-billteng @ttmchiou @tt-rkim

**Comment by vtangTT** [comment]
assigning to @jliangTT  per his request for further triage

**Comment by jliangTT** [comment]
Reviewed this today and this is one of the issue we can test against the new FD2.0 branch once it is ready.

**Comment by davorchap** [comment]
@aliuTT these tests are passing with FD2, can we close?

**Comment by aliuTT** [comment]
Yes, closing
