### ISSUE TITLE
vm-20 resets during pip dependency fetch

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#6634]
vm-20 has been misbehaving, this isn't first time:

https://github.com/tenstorrent-metal/tt-metal/actions/runs/8371308956/job/22920110565

**Comment by TT-billteng** [comment]
another run https://github.com/tenstorrent-metal/tt-metal/actions/runs/8371308956/job/22920110565

**Comment by tt-rkim** [comment]
@TT-billteng  - same link posted twice, do you have a diff link?

**Comment by TT-billteng** [comment]
oops, I did see it somewhere but can't find the link 😓

**Comment by TT-billteng** [comment]
@ttmchiou has re-made VM, hope it works

**Comment by TT-billteng** [comment]
vm-20 is doing good now
