### ISSUE TITLE
[Bug Report] Falcon40b sharded prefill demo giving non-meaningful output for max_seq_len 128

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent/tt-metal#6651]
**Describe the bug**
Falcon40b prefill demo giving non-meaningful output for max_seq_len 128

**To Reproduce**
pytest --disable-warnings -q -s --input-method=cli --cli-input="What is the capital of Serbia?"  models/demos/falcon40b/demo/demo.py

**Additional context**
The output of the prefill is good, seems that the device is left in a bad state after prefill on device. To show this, on branch `sjovic/falcon40b-demo-with-reset`, running the same command with `reset_devices` set to True in the demo, gives good output. The flag means that after prefill, kv cache is loaded to torch and host memory, devices are closed and opened again, and the kv cache is put to the device again.

Other things tried:
- just deallocating all buffers or outputs of the prefill on device, without closing the devices - still results in an issue
- dumping memory layout
- other max_seq_len than 128 don't work as well (64 and 160 for example)
- watcher didn't report any issue with memory access neither on decode nor prefill
- DEBUG build still results in issues

Pending to try:
- Moving most of the ops to interleaved mode
- Deallocating explicitly even the tensors that are reassigned (and thus should be removed with garbage collector)

**Comment by s-jovic** [comment]
cc @TT-BrianLiu @aliuTT @tarafdarTT @johanna-rock-tt since I created a separate issue

**Comment by s-jovic** [comment]
To make seq len 2048 work without nd output and hangs, dues to the same issue, all 1d/2d matmuls were set to use subblock h/w 1 - both mlp matmuls, both attention matmuls and lm head matmul.

**Comment by johanna-rock-tt** [comment]
Can we close this issue?

**Comment by s-jovic** [comment]
Yeah, we can close it now.
