### ISSUE TITLE
TestPrintInvalidCore and DeviceInitializeAndTeardown tests hanging on N300

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent/tt-metal#6659]
`DPrintErrorChecking.TestPrintInvalidCore` hangs when run locally on N300 bm on most recent main `a9b969b`

Will hang if run the entire fd gtest suite, and also when run individually, but in a different way

When run entire suite it seems to hang right after attaching:
<img width="1301" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/157417475/276dc6e3-3ed5-4b84-9be9-24774a56baed">

When run individually, it'll hang when closing device: 
<img width="1308" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/157417475/a42d3d1c-98fc-4a04-83d1-3ed1144251f9">

The above two behaviours were observed on N300 bm

As per slack convo, `DPrintFixture.TestPrintFromAllHarts` has hung multiple times on N300 CI:
![image](https://github.com/tenstorrent-metal/tt-metal/assets/157417475/82f389b4-59b4-4e7a-8d53-39d4f72ed052)

CC: @ttmchiou @TT-billteng @tt-rkim @tt-dma 

related to #6647

**Comment by ttmchiou** [comment]
![image](https://github.com/tenstorrent-metal/tt-metal/assets/156848643/ab2b5eff-4d07-46f6-b72b-2a5639ba9443)

I believe also happens on 1000Mhz units.

**Comment by tt-dma** [comment]
I found two tests failing on main: TestPrintInvalidCore and DeviceInitializeAndTeardown. Both cause hangs on n300 BM, and both tests involve creating a Device and then destroying it without running any kernels. I've bisected and the commit that breaks it is https://github.com/tenstorrent-metal/tt-metal/commit/ec29ca7de

**Comment by vtangTT** [comment]
i've noticed that when running `DeviceInitializeAndTeardown` on N300 BM, it'll hang and then `tt-smi-metal` won't be able to show status of the board

`tt-smi-metal -r 0` will still be able to reset the board successfully

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent-metal/tt-metal/pull/6708 has a workaround for this, Allan will investigate what the cause is

**Comment by jliangTT** [comment]
With the workaround, let's make it a p2 given all the other actvitiies.

**Comment by pgkeller** [comment]
@aliuTT @tt-dma I assume this workaround is still in place?  Any idea why and how to fix?

**Comment by aliuTT** [comment]
Just to recall, I believe the workaround was removing this zero vector: 
```
 /* TODO: removing this section of code fixes the n300 hangs, what's the proper fix?
        std::vector<uint32_t> zero_vec_below_command_q_base(
            (eth_l1_mem::address_map::COMMAND_Q_BASE - eth_l1_mem::address_map::FIRMWARE_BASE) / sizeof(uint32_t), 0);
        llrt::write_hex_vec_to_core(
            this->id(), physical_core, zero_vec_below_command_q_base, eth_l1_mem::address_map::FIRMWARE_BASE);
        */
```

Likely that there is some UMD section in this address range. Will check with Umair.

**Comment by aliuTT** [comment]
```
Base FW:
0x0 - 0x903F: Firmware text and data sections.
0x11000 - 0x17FFF: Layer 3 Routing network queues
```

Confirmed that `COMMAND_Q_BASE` which starts at 0x11000 to `FIRMWARE_BASE` should never be zeroed. This section of code can be deleted. I'll put up a cleanup PR.
