### ISSUE TITLE
ttnn.nextafter breaks when first parameter is not BFLOAT16 [Grayskull and Wormhole] 

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#6684]
**ttnn.nextafter** operation fails in cases when the first argument is not BFLOAT16: TT_FATAL @ tt_eager/tt_dnn/op_library/bcast/bcast_op.cpp:90: input_tensor_a.get_dtype() == input_tensor_b.get_dtype()

**To Reproduce**
Checkout `main`  branch and run unit test `test_nextafter.py ` (or others) using this command pattern:

```
pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_nextafter.py
```

**Expected behavior**
There are three test cases presented in the unit test - the first one passes, the others fail `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_nextafter.py` and they are expected to fail with error "TT_FATAL @ tt_eager/tt_dnn/op_library/bcast/bcast_op.cpp:90: input_tensor_a.get_dtype() == input_tensor_b.get_dtype()"

```
TT_FATAL @ tt_eager/tt_dnn/op_library/bcast/bcast_op.cpp:90: input_tensor_a.get_dtype() == input_tensor_b.get_dtype()
```

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweep test:

```
tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_nextafter_test.yaml
```

To do this you should:

1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_nextafter_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by Aswinmcw** [comment]
Hi @npetrovic-tenstorrent , the above mentioned test file `pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_nextafter.py` is passing in main, Can we close this issue?

**Comment by umadevimcw** [comment]
Closing this issue as it passes in main
