### ISSUE TITLE
Metal device init and close triggers ARC 0xffffffff error on Galaxy

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent/tt-metal#6693]
Reproable on `aus-glx-08`:

- `git checkout aliu/galaxy-fd2`

- `TT_METAL_GALAXY_CHIPS=0,4 ./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter="CommandQueueSingleCardFixture.WriteOneTileToDramBank0"` (passes a few times, but triggers ARC 0xffffffff on third run consistently)

**Comment by ubcheema** [comment]
galaxy/main is able to run on galaxy systems.
Device open/close works. 
I have verified running single chip tests on mmio device and first Galaxy remote device.
