### ISSUE TITLE
Extend update_cache OP to update the KV cache for multiple users at individual positions

### ISSUE THREAD

**Issue by johanna-rock-tt** [tenstorrent/tt-metal#6733]
**Describe the feature**
Currently the` tt_lib.tensor.update_cache` OP takes the newly produced K and V values and updates the cache for all users at a specific position (kvlen), so one column of the kvcache is updated. The position to be updated is currently the same for all users.
What we need: Update the kv cache at different positions per user, to enable decoding within one batch with independent prompt lengths per user.

**Proposed usage for the OP**

`tt_lib.tensor.update_cache(cache, value, kv_update_positions)`

where `cache` ist the kv_cache tensor for K or V for a specific layer, `value` is the new K or V to be updated into the layer's kv cache, and `kv_update_positions` is a list of indices with `len(kv_update_positions)` matching the number of users (=32) containing the indices in S to write the new k/v cache values `into.`

**Comment by johanna-rock-tt** [comment]
FYI: @miacim @cglagovichTT @djordje-tt

**Comment by TT-BrianLiu** [comment]
Please file under one of the global project boards. Otherwise, no one is going to look at it :)

**Comment by jliangTT** [comment]
hey @johanna-rock-tt , for KV cache we have been considered it as a tensor manipulation op which uses "op_cat: TM" label. You just need to label it and it will get auto-assigned. thanks!

**Comment by jliangTT** [comment]
Also i have been asking people to use label P1_critical + bug or feature, instead of using P1_feature_needed and P1_bug. If you can, please help make our life easier.

**Comment by johanna-rock-tt** [comment]
Sorry about that, will do!

**Comment by TT-BrianLiu** [comment]
If we pad up each prompt to be same length and use appropriate masks with varying prompt length per user during decode, that should work as well? We need varying prompt length for attention mask anyways.

**Comment by cglagovich** [comment]
After you're done with prefill, you want to run decode where each token has a different length KV cache. You want to fill each cache at the right position for each user

**Comment by johanna-rock-tt** [comment]
I think what Brian is proposing is to left pad the kvcache of the prompts after prefill and use approprite attention masks (mask out the padded part to the left entirely). Is that what you're saying @TT-BrianLiu?
I think this would work if we'd run prefill 32 times and then decode until all users are done and then start fresh. But this would not allow us to swap in new users as soon as one is done in decode etc. Right? So for a demo not ideal.

**Comment by TT-BrianLiu** [comment]
Actually nvm, i think it would make more sense to do it separately for each user. You would have to mask out the padded prompts, don't mask the new cache, then mask out the rest, which is weird.

**Comment by cglagovichTT** [comment]
Safe to close this issue now that #10050 is merged?
