### ISSUE TITLE
watcher should be more specific about noc failures

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#6738]
On core (x=6,y=1): ncrisc using noc0 tried to accesss core (00,01) L1[addr=0x400974f0,len=16]

This error line doesn't say why the transaction is bad.  Experts can figure it out, but would be great to know that the problem was an alignment violation, say:
 On core (x=6,y=1): ncrisc using noc0 tried to accesss core (00,01) L1[addr=0x400974f0,len=16] (bad address alignment)
 On core (x=6,y=1): ncrisc using noc0 tried to accesss core (00,01) L1[addr=0x80000000,len=16] (address overflow)
 On core (x=6,y=1): ncrisc using noc0 tried to accesss core (00,01) L1[addr=0x0000000,len=0] (zero length transaction)
(etc)

**Comment by tt-dma** [comment]
@tt-dma Make sure new version specifies read/write instead of "access"

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent/tt-metal/pull/13029 implements this
