### ISSUE TITLE
Overlapping Memory Map for Runtime 

### ISSUE THREAD

**Issue by kkwong10** [tenstorrent/tt-metal#677]
@pgkeller 
We have addresses hardcoded in: `tt-metal/tt_metal/hostdevcommon/common_runtime_address_map.h` for args/debug prints/debugger
```cpp
// TODO: these could be moved to even lower addresses -- 5 RISC-V hexes combined don't need 100 KB
constexpr static std::uint32_t RUNTIME_CONFIG_BASE = 100 * 1024;
constexpr static std::uint32_t BRISC_L1_ARG_BASE = 101 * 1024;
constexpr static std::uint32_t BRISC_L1_RESULT_BASE = 102 * 1024;
constexpr static std::uint32_t NCRISC_L1_ARG_BASE = 103 * 1024;
constexpr static std::uint32_t NCRISC_L1_RESULT_BASE = 104 * 1024;
```

Which overlap with the actual TRISC2 regions.  It seems like we are OK for now because of holes in our memory map, but we should ensure that this file is relative to the defines we set so there is no hazardous overlaps

**Comment by pgkeller** [comment]
this is slowly getting cleaned up under other issues, closing
