### ISSUE TITLE
PCC error/`allclose` mismatch with `repeat_interleave`

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#6791]
device: WHB0
branch: `asarje/ri-test`
test that fails: `pytest tests/ttnn/unit_tests/operations/test_repeat_interleave.py::test_f2`

The expected PCC here is `1.0`, but get less than that on WH.
GS works correctly.

**Comment by jliangTT** [comment]
assigning to P2 for now but this was spotted during feature enablement here #6516

**Comment by jliangTT** [comment]
closing it as repeat interleave implementation and design will be done in #7600. And this is less relevant
