### ISSUE TITLE
ttnn.permute() on device

### ISSUE THREAD

**Issue by kpaigwar** [tenstorrent/tt-metal#6799]
### Description
We are seeing permute OP is falling back on host. We require its on-device support for better performance.

### Requirement
```
input_tensor = ttnn.from_torch(
            torch.rand(1, 32, 5120, 1),
            layout=ttnn.TILE_LAYOUT,
            device=self.device,
            memory_config=ttnn.L1_MEMORY_CONFIG,
            dtype=ttnn.bfloat16,
        )
output_tensor = ttnn.permute(input_tensor, (0, 3, 1, 2))
```

**Comment by kpaigwar** [comment]
fyi @aguhaTT

**Comment by jvasilje** [comment]
can you run this as 2 transposes back to back. 1) XY, 2) YW?

**Comment by aguhaTT** [comment]
we will try that.

**Comment by kpaigwar** [comment]
Our input is of shape (1, 1, b, n) where b,n=32
If we break down permute(0, 2, 3, 1) as
1) transpose(2, 1)     `# 1, 1, b, n -> 1, b, 1, n ` 
2) transpose(3, 2)   ` # 1, b, 1, n -> 1, b, n, 1`

The second transpose is falling back to host because I think transposing unary dimension makes it ROW_MAJOR which is not supported on device.

Here you can see the device and layouts after each transpose

```
#C0 StorageType: StorageType.DEVICE, Layout: Layout.TILE                                                                                                                                      
tt_lib.tensor.transpose(C0, 2, 1, output_mem_config=ttnn.L1_MEMORY_CONFIG)  # 1, 1, b, n -> 1, b, 1, n                                                                          
#C1 StorageType: StorageType.DEVICE, Layout: Layout.ROW_MAJOR
                                                                                                                                 
tt_lib.tensor.transpose(C1, -2, -1, output_mem_config=ttnn.L1_MEMORY_CONFIG)  # 1, b, 1, n -> 1, b, n, 1                                                                                     
#C1 StorageType: StorageType.OWNED, Layout: Layout.ROW_MAJOR
```
I think to make it work we might have to pad the unary dimension.

**Comment by kpaigwar** [comment]
I verified that ttnn.permute is functional on device for tensors with shapes divisible by TILE_WIDTH. However, in our case, the tensors have TILE Padding and ttnn.permute() converts them to ROW_MAJOR_LAYOUT which fallbacks to host as filed in issue #7020.

https://github.com/tenstorrent-metal/tt-metal/blob/8e10df949182744f291895c70dc4832442da127c/ttnn/ttnn/operations/data_movement.py#L229

This issue can be handled at ttnn level

**Comment by jliangTT** [comment]
@kpaigwar , want to clarify on the re-assign to ttnn team. Was there an offline conversation to put this in the ttnn team queue?

**Comment by kpaigwar** [comment]
> @kpaigwar , want to clarify on the re-assign to ttnn team. Was there an offline conversation to put this in the ttnn team queue?

No, there wasn't an offline conversation. This seems to work on Device when the shapes are TILE WIDTH. But fallbacks on host with how padding is handled in ttnn.

**Comment by jliangTT** [comment]
sounds good. @eyonland, i am leaving this in your queue to triage. thanks.

**Comment by esmalTT** [comment]
We have come up with a workaround (https://github.com/tenstorrent/tt-metal/pull/7804, https://github.com/tenstorrent/tt-metal/pull/7668) and no longer require this feature.

Closing.
