### ISSUE TITLE
Cleanup and remove any FD2 branch-specific hacks before merging to main

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#6801]

**Comment by tt-rkim** [comment]
This includes changes to:

- infra and CI files
- build-specific hacks
- CODEOWNERS
- README etc.

**Comment by tt-rkim** [comment]
@jliangTT Tagging this with P2 and infra-ci labels as they're relevant, although FD2 project is owning project.

**Comment by davorchap** [comment]
FD2 has been merged
