### ISSUE TITLE
split_query_key_value_and_split_heads mismatches when used with block sharded tensors

### ISSUE THREAD

**Issue by arakhmati** [tenstorrent/tt-metal#6805]
Branch: `main`
Command to reproduce: `pytest tests/ttnn/unit_tests/operations/test_transformer.py::test_sharded_split_query_key_value_and_split_heads[input_dtype=DataType.BFLOAT8_B-head_size=64-num_heads=12-sequence_size=224-batch_size=8]`

**Comment by xanderchin** [comment]
Also seeing low pcc issue in `ttnn_optimized_sharded_bert`. Input is also block sharded.

**Comment by jliangTT** [comment]
@sjameelTT , want to confirm that you are working on this one and it is in progress?

**Comment by sjameelTT** [comment]
> @sjameelTT , want to confirm that you are working on this one and it is in progress?

Yeah, all my changes are on my local repo right now though. I am still getting familiar with all the APIs and codebase.

**Comment by jvasilje** [comment]
@sjameelTT what's the ETA on this fix?

**Comment by sjameelTT** [comment]
I'm hoping I'll be able to finish all the cases by next week since I'm doing a refactor and creating two new APIs.

**Comment by sjameelTT** [comment]
Does this have a deadline? I can try to speed things up. I am taking Wednesday off for Eid.

**Comment by jvasilje** [comment]
you should take Wed off for Eid. :-) 

yes, we want to enable model demos asap. 
this OP is blocking for a model that Mohamed is working on. @mbahnasTT can you connect with @sjameelTT and discuss how to get unblocked on this.

**Comment by jvasilje** [comment]
im raising this to a P0. 
@sjameelTT please update once every 2hrs on progress. 
@jliangTT fyi - pls help track.

**Comment by TT-BrianLiu** [comment]
PR with new op: https://github.com/tenstorrent-metal/tt-metal/pull/7323

This should work for `num_heads=12` on Grayskull. For `num_heads=8`, each core gets multiple groups of heads and requires additional support. I am looking into it right now.

**Comment by jliangTT** [comment]
closed after cloising loop with @xanderchin

**Comment by jliangTT** [comment]
Any update here? @sjameelTT

**Comment by jliangTT** [comment]
The golden function needs change for the sharded implementation (optimized_bert use the sharded implementation). No more blocker for this issue. But the golden function <> sharded implementation incompatibility needs to be addressed. file an issue.
