### ISSUE TITLE
ViT sharded: optimize the patch and position embeddings

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent/tt-metal#6812]
**Describe the bug**
comparing L1-interleaved and Sharded Perf, with objective of further optimization on sharded.
Investigation points:
  - Improve Matmul utilization 
  - Not all OPs are benefiting from sharded on the same level

**To Reproduce**
1. Go to 'branch' mbahnas/vit_ttnn_sharded/
2. './tt_metal/tools/profiler/profile_this.py -n vit_sharded -c "pytest tests/ttnn/integration_tests/vit/test_performance_deviceOPs.py::test_performance_vit_encoder"`

**Expected behavior**

**Screenshots**
<img width="1265" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/116673264/1b5a6aa5-2d3d-4bbb-9f5e-4fd4ea3e7dce">

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by jliangTT** [comment]
I don't actually know how to triage this - we don't really have a model team owning this ViT (is it CNN?) assigning to jasmina to see check.

**Comment by mbahnasTT** [comment]
@jliangTT It's a transformer based, so very close to BERT. I believe Akhmed or Naif can have a look.

**Comment by jliangTT** [comment]
Naif is super slammed. let's see @arakhmati has an input. got any pointer that you can help mohammed investigate the perf?

**Comment by mbahnasTT** [comment]
Let me try @arakhmati 's new tool and put a report out of that, and/or I can have a working session with Akhmed on it, if he has 15 mins

**Comment by arakhmati** [comment]
> Let me try @arakhmati 's new tool and put a report out of that, and/or I can have a working session with Akhmed on it, if he has 15 mins

@mo-tenstorrent let me know. We can zoom whenever tomorrow

**Comment by jliangTT** [comment]
i think he meant @mbahnasTT

**Comment by mbahnasTT** [comment]
I had a review with @arakhmati on the utilization numbers, and I understood that I need to increase my batch size (or use less number of cores) to demonstrate higher utilization on low resolution. Another path that I'll switch to the high resolution b=1 to demonstrate the utilization.

**Comment by mbahnasTT** [comment]
@yan-zaretskiy @tarafdarTT 

I added a unit test for the embedding optimization and fallback: Fold->Matmul->Concat->Add

- branch: `https://github.com/tenstorrent-metal/tt-metal/compare/mbahnas/vit_ttnn_sharded_v2`
- PCC unit test: pytest tests/ttnn/integration_tests/vit/test_ttnn_optimized_sharded_vit.py::test_vit_embeddings
- generating the perf sheet: `./tt_metal/tools/profiler/profile_this.py -n vit_EMBEDDINGS -c "pytest tests/ttnn/integration_tests/vit/test_performance_deviceOPs_ttnn_optim_sharded_vit.py::test_performance_vit_embeddings"`
![Uploading Screenshot 2024-04-04 at 10.21.20 AM.png…]()

**Comment by mbahnasTT** [comment]
concat is concatenating `cls-tokens` from the model weight, with tensor shape [1,768] to the image processed tensor [196,768]

**Comment by mbahnasTT** [comment]
code snippet:
```

   fold_h_padded = (batch_size * img_h * patch_count_all) + 224
    fold_w_padded = (4 * patch_size * patch_size) + 128

    # pixel_values = ttnn.reshape(pixel_values, (batch_size, img_h, img_w // patch_size, 4 * patch_size))
    folded_pixel_values = ttnn.experimental.tensor.fold(pixel_values, stride_h, stride_w)  # 1568, 1024
    ttnn.deallocate(pixel_values)
    x = ttnn.reallocate(folded_pixel_values)
    folded_pixel_values = ttnn.to_layout(x, layout=ttnn.TILE_LAYOUT, dtype=ttnn.bfloat8_b)

patch_embedding_output = ttnn.linear(
        folded_pixel_values,
        parameters.projection.weight,
        bias=parameters.projection.bias,
        memory_config=ttnn.L1_MEMORY_CONFIG,
        dtype=ttnn.bfloat8_b,
        core_grid=ttnn.CoreGrid(y=8, x=12),
        # program_config=config.program_configs["embedding_matmul_program_config"],
    )
    # ttnn.deallocate(pixel_values)

    patch_embedding_output = ttnn.to_layout(patch_embedding_output, layout=ttnn.ROW_MAJOR_LAYOUT)
    patch_embedding_output = ttnn.reshape(patch_embedding_output, (batch_size, patch_count_all, patch_size_sq_trpl))

    embedding_output = ttnn.concat((cls_token, patch_embedding_output), dim=1)

    embedding_output = ttnn.add(
        embedding_output, position_embeddings, memory_config=ttnn.L1_MEMORY_CONFIG, dtype=ttnn.bfloat8_b
    )
    embedding_output = ttnn.to_layout(embedding_output, layout=ttnn.TILE_LAYOUT)
```

**Comment by tarafdarTT** [comment]
Concat is working with no fallback.
@mbahnasTT could you comment on the status , just want to track the perf stuff you are seeing right now.

**Comment by tarafdarTT** [comment]
@mbahnasTT can I close this issue?
