### ISSUE TITLE
CB code needs a separate barrier for atomics

### ISSUE THREAD

**Issue by imatosevic** [tenstorrent/tt-metal#6814]
In the present implementation of circular buffers with semaphores, NOC atomics are used to update semaphores. 

However, the code assumes that the write barrier call (`noc_async_write_barrier`) acts as a barrier for both writes and atomics. This is incorrect, since in NOC there are separate request/response counters for reads, writes, and atomics respectively, so code that makes this assumption may lead to race conditions. 

In order to have a functional barrier for atomics, we need to add a separate counter for outstanding atomic transactions, and also issue atomics as non-posted (i.e., set `NOC_CMD_RESP_MARKED` flag in `NOC_CTRL` register). 

One complication is that non-posted NOC atomics require a return address in L1 for the response value. (Atomic increment returns the pre-increment value.) So if we're discarding the response value, we nevertheless need to provide a scratch location in L1. (Otherwise, if this address is not set, the response may corrupt a random L1 location.) 

To avoid performance degradation for write barriers in sequences that don't use atomics, we should provide a separate `noc_async_atomic_barrier` call, and identify all places in the code where it's needed. 

One place where we are presently aware of the problem is when a local semaphore is updated with a NOC loopback atomic sequence. In this case, there may be a race condition with subsequent code from the same RISC that reads the updated semaphore value. (This code may race ahead of the outstanding atomic transaction and read a stale value.)  

The bug was found by code inspection. There are no known tests that reproduce it. However, it should be considered when looking at non-deterministic failures in sequences that use atomics.

**Comment by jliangTT** [comment]
Has this been addressed? @imatosevic ? looks like there has been some activity in past few week.

**Comment by imatosevic** [comment]
@jliangTT - The fix has been merged into the fast dispatch 2 main branch (fd-2/main) in MR #6885. We need to decide if we should integrate it into main directly (MR #6814) or defer it until fd2-2/main is integrated. 

There are presently no known issues in the main branch where the fix is needed, so it's unclear what's the better way to proceed. We'll discuss this in the next FD2 meeting and update the ticket with the decision.

**Comment by imatosevic** [comment]
I discussed this with @pgkeller, and we decided not to pursue a direct integration of the fix into main. It will be integrated as part of the upcoming fd-2/main integration.
