### ISSUE TITLE
need a stand alone watcher dump tool

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#6830]
This is a feature request for a tool that could run standalone, connect to a hung device and dump the watcher state even if watcher was not enabled.  Notes:
1) The state will be minimal, but could include the kernel IDs from the launch message
2) The state that is there can be validated (eg, L1[0] corruption)

Presumably, this would just be a normal program that connects to the device, launches watcher, and does a dump.  We have to be careful though that device init doesn't trash the state we care about by launching a kernel or zeroing memory.

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent/tt-metal/pull/8239 implements this, we'll file another issue to improve the tool for host side
