### ISSUE TITLE
Yolov4- variant with trained weights failing convs unit tests

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#6851]
**Describe the bug**
Using [this YOLOv4 implementation ](https://github.com/Tianxiaomo/pytorch-YOLOv4). I extracted all conv variants and added a unit test for them.

Some variants are currently failing on GS. 

**To Reproduce**
1. Go to [my branch: dvartanians/yolov4](https://github.com/tenstorrent-metal/tt-metal/tree/dvartanians/yolov4)
2. run: `pytest tests/ttnn/unit_tests/operations/test_conv2d.py::test_yolov4_REPO_320_320`
3. 3 failing cases (out of 37)
4. See error when running the unit test. but here is a short snippet of the error: 
`tests.ttnn.unit_tests.operations.test_conv2d:run_conv:169 - list(expected_pytorch_result.shape)=[1, 256, 10, 10] vs list(actual_pytorch_result.shape)=[1, 255, 10, 10]`
The error happens at `check_with_pcc_without_tensor_printout` function. 

**Expected behavior**
Expecting all variants to pass in order to implment YOLOv4 via TTNN end to end.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (current commit: 7060853ea690db1a3aba2229cf0da04d0d6af4d7)

**Additional context**

- Customer feature 
- Please note, it would be ideal if all convs could run with the same sharding strategy (block sharding) however, I could not get all of them to pass as such. Therefore, had to make some of them pass with height sharding. These would be a follow up issue for perf. As first step we can focus on getting all convs to run on device.

**Comment by jliangTT** [comment]
assigning to the customer board to triage. Looks like this one misses our last week's prioritization due to not having the rigth tag.

**Comment by jliangTT** [comment]
Bumping in to P0 to focus on burning down customer's issue (Jim's request)

**Comment by nsmithtt** [comment]
Fixed w/ https://github.com/tenstorrent/tt-metal/pull/8281
