### ISSUE TITLE
Using launch message for ethernet kernels causes hangs on T3000

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#6860]
Steps to reproduce:
- On T3000 machine
- In `test_pause.cpp`, see comments and re-enable running on ethernet cores
- Run `./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=*WatcherPause`
- Result is that the test hangs, it should finish in only a few seconds.

Observations:
- This test passes (running on eth cores) if I go to the commit right before https://github.com/tenstorrent-metal/tt-metal/commit/ec29ca7de, fails when I run on this commit
- This issue happens on `WatcherPause` and `WatcherWaypoints`, but not any other watcher-on-eth-core tests. These two tests run kernels on tensix + eth cores int eh same `Program`, while the others don't, could be related.

If applications are using tensix + ethernet kernels in the same `Program` then they can run into this. Perhaps this issue goes away in FD2.0 though

**Comment by jliangTT** [comment]
This mechanism might change following FD2.0. Need to debug after FD2.0 is ready.

**Comment by davorchap** [comment]
@tt-dma and @aliuTT this is resolved w/ FD2 ?

**Comment by aliuTT** [comment]
Based on description, looks like this is a go signal problem. Probably resolved in FD2. @tt-dma, can you rerun and confirm?

**Comment by tt-dma** [comment]
Checking here: https://github.com/tenstorrent/tt-metal/actions/runs/9011705151/job/24759745487

**Comment by tt-dma** [comment]
Fixed with FD2, and also this test was somehow disabled on two separate levels... https://github.com/tenstorrent/tt-metal/pull/8307
