### ISSUE TITLE
[Feature Request] mul_tiles between a CB and a DST

### ISSUE THREAD

**Issue by yan-zaretskiy** [tenstorrent/tt-metal#6916]
I'd like to use the compute API similar to the existing `mul_tiles`, but which takes a DST register as the second argument, e.g.

```
void ckernel::mul_tiles_dst(uint32_t icb0, uint32_t itile0, uint32_t idst_in, uint32_t idst_out)
```

**Comment by ttmtrajkovic** [comment]
This would require to introduce into the compute API move from DST to SRC, which is supported in LLKs but missing compute API.
@yan-zaretskiy, what's the priority of this and is this a feature to increase perf or there's a functional gater?

I think this could be addressed either mid-next week or the following week. Please help prioritize.

**Comment by rtawfik01** [comment]
Hi @yan-zaretskiy I am going to expose the api and also add tests for it here: https://github.com/tenstorrent/tt-metal/pull/8582.
The difference is the api will look like this:
```
template<
EltwiseBinaryType eltwise_binary_type = ELWADD,
EltwiseBinaryReuseDestType binary_reuse_dest = EltwiseBinaryReuseDestType::NONE>
ALWI void binary_dest_reuse_tiles( uint32_t in_cb_id, uint32_t in_tile_index, uint32_t dst_tile_index)
```

where `dst_tile_index` is both the dst tile index that will be loaded back to the source register, and the output tile index for the result of the binary operation of source register A & B, aka its "in-place"

Let me know if this works for you, you can look at the PR above to see an example of a test for it and how to use it.

**Comment by rtawfik01** [comment]
Merged here: https://github.com/tenstorrent/tt-metal/pull/8727. @yan-zaretskiy let me know if there is any issues

**Comment by esmalTT** [comment]
Closing since it appears to be completed. @yan-zaretskiy feel free to re-open if there are issues.
