### ISSUE TITLE
clang-17 build test_print_tensor fails

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#6925]
Switching to using clang-17 to compile tt-metal repository has made some changes.

test_print_tensor.py fails for testPrint on E150 Grayskull tests when building with -O0

Install clang-17
compile on tt-metal branch mchiou/4252-enable-c++20-install-clang-17
run ttnn tests
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8474740104/job/23221781875

**Comment by jliangTT** [comment]
Bumping to P1 as -O0 is an important debugging feature for us

**Comment by eyonland** [comment]
Build with C++20 is passing.  Checking to see if this is still an issue.

**Comment by eyonland** [comment]
@vtangTT and @arakhmati fixed this issue.  Thank you both!
