### ISSUE TITLE
clang-17 build issue - SingleCoreSfpuCompute Test failure

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#6926]
build  with tt-metal compiled with clang-17
compilation of tt-metal and tests are successful but tests run in post commit fail

on Slow dispatch and Fast Dispatch
SingleCoreSfpuCompute tests fail deterministically
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8474740104/job/23221777305

**Comment by TT-billteng** [comment]
is this test still in test suite @ttmchiou ?
