### ISSUE TITLE
clang-17 build - MultiCoreSfpuCompute/MultiCoreSingleCardSfpuParameterizedApproxFixture test Failure

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#6927]
Using clang-17 compiled libs of tt-metal and tests
MultiCoreSfpuCompute/MultiCoreSingleCardSfpuParameterizedApproxFixture.AllCoreMultiTileSfpuApproxCompute test suites deterministically fail on fast dispatch for GS/WH archs

https://github.com/tenstorrent-metal/tt-metal/actions/runs/8474740104/job/23221780957

**Comment by TT-billteng** [comment]
is this test still in the testing suite @ttmchiou ?

**Comment by ttmchiou** [comment]
test is still in testing suite similar to #6926 
closing as tests are passing in current post-commit now
