### ISSUE TITLE
Faster softplus needed

### ISSUE THREAD

**Issue by aguhaTT** [tenstorrent/tt-metal#6938]
Currently, we are getting `0.1 ms` for softplus. We need something around `0.01 ms`. Maybe fusing is needed. It would be helpful if it supported sharded mode as well. 

**To Reproduce**
we are using `ttnn.softplus(delta_t, parameter1=1.0, parameter2=20.0, memory_config=ttnn.L1_MEMORY_CONFIG)`
where `delta_t` is of datatype `ttnn.bfloat16` and of shape `1,1,32,5120`

@kpaigwar @esmalTT

**Comment by jliangTT** [comment]
@yugaoTT or @eyonland , is this a ttnn thing or an op-writer thing? (triage question)..

**Comment by yugaoTT** [comment]
looks like softplus is a implemented using a bunch od unary ops connected together. Might need a new implementation to fuse all ops into one kernel

**Comment by jliangTT** [comment]
ok. let me put this into the fused queue since new implementation needs to be planned.
