### ISSUE TITLE
faster repeat needed

### ISSUE THREAD

**Issue by aguhaTT** [tenstorrent/tt-metal#6939]
`repeat` currently takes `0.46 ms` because it is implemented on a singe core. We have a budget of around `0.01ms`. Also, it does not currently support sharding.

**To Reproduce**
`ttnn.repeat(B, ttnn.Shape([1, 1, 1, 5120], [1, 1, 32, 5120]))`
where `B` is of datatype `ttnn.bfloat16` and shape `1,1,32,32`

if sharding can be supported, input `B` will be `ttnn.L1_MEMORY_CONFIG` while output will have the memory config:
```
ttnn.create_sharded_memory_config(
        shape=(1, 1, 32, 163840),
        core_grid=ttnn.CoreGrid(y=4, x=8),
        strategy=ttnn.ShardStrategy.WIDTH
    )
```

@kpaigwar @esmalTT

**Comment by jliangTT** [comment]
@tarafdarTT , putting on your queue to triage. assume it is on the back log until other things clear up.

**Comment by jliangTT** [comment]
Summary from a brainstorm with @davorchap @yan-zaretskiy @aguhaTT @kpaigwar @uaydonat: (doing my best to describe)
- repeat interleave (though running on device) is still slow and need a tile-base solution. Discussed on how to do that. 
- this affects mamba decode therefore is very improtant. 
- brainstorm on dedicatd repeat logic to use sharding/l1 to speed things up.

Next step: 
- should prototype the idea that first get it into tiles and extract left-most column & estimate latency.
- check with LLK team to see if feature support.

**Comment by jliangTT** [comment]
With #7600 closed, does this issue still apply?

**Comment by apalaguha** [comment]
No we do not need it for mamba anymore.

**Comment by aguhaTT** [comment]
No we do not need it for mamba anymore.

**Comment by esmalTT** [comment]
@jliangTT Should we close this? We no longer need it for Mamba.

**Comment by kpaigwar** [comment]
Yeah let's close this
