### ISSUE TITLE
Update raw pointer usage in tt-metal host APIs

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#698]
- [x] Kernel args
- [x] Kernels
- [x] Circular Buffers
- [x] Semaphores
- [x] Program
- [ ] Device

Replace with const ref/refs or smart pointers when needed

Passing criteria: all existing tests and models should run and pass

**Comment by davorchap** [comment]
@TT-billteng and @abhullar-tt can we close this one?
