### ISSUE TITLE
fuse mish activation into conv in TTNN

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#6986]
**Is your feature request related to a problem? Please describe.**
need to enable fusing of "mish" activation into conv similar to "relu" as in [here](https://github.com/tenstorrent-metal/tt-metal/blob/dvartanians/yolov4/tests/ttnn/integration_tests/yolov4/test_ttnn_yolov4_DownSample1.py#L37)

**Describe the solution you'd like**
enable `ttnn_module_args.c1["activation"] = "mish"  # Fuse mish with conv1` in TTNN

**Additional context**
Developing in GS e150
branch [dvartanians/yolov4](https://github.com/tenstorrent-metal/tt-metal/blob/dvartanians/yolov4/models/experimental/functional_yolov4/tt/ttnn_yolov4.py)

**Comment by nsmithtt** [comment]
@dvartaniansTT why does mish need to be fused?  We can just run it as an eltwise following the conv.  Relu is special because we have specialized HW for it.

**Comment by nsmithtt** [comment]
Closing, no plans to fuse mish, it can be run as an eltwise op.
