### ISSUE TITLE
[Stub/workaround] Add vector-addition example

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#6993]
This PR is created to work around the commit message needs imposed by the pre-commit hook. See the discord messages for detail. ([link](https://discord.com/channels/863154240319258674/1177146871051984966/1222289800803909673))

```
marty1885
 — 
03/26/2024 9:03 PM
Hi, took me a while. I wrote an heavily annotated vector addition program in Metalium. Hope it helps people understand how Tenstorrent hardware works and what are the components.
https://github.com/marty1885/ttVecAdd
 — 
03/27/2024 5:03 AM
@marty1885 this is amazing! Would you be ok contributing this example directly to the TT-Metalium repo? I'm sure this would be very helpful for people exploring the framework
Shubham Saboo
 — 
03/27/2024 5:08 AM
Great work @marty1885. If you can plesae add this example to TT-Metalium repo, we would love to promote it from our social channels.
```

**Comment by jliangTT** [comment]
@marty1885 , this is really great and thanks for working with us to merge the examples in and help contributing to our documentation. We will do our best to get to it as soon as we can but given the PR review queue, we are a little backed up and hope to get to it in a couple of weeks. thanks for your patience. 

c.c. @tt-rkim

**Comment by marty1885** [comment]
Closing as it it merfed
