### ISSUE TITLE
Add Padding to reshard

### ISSUE THREAD

**Issue by ntarafdar** [tenstorrent/tt-metal#7040]
Interleaved to sharded and then sharded to interleaved adds padding for tensors not aligned to 16B, reshard currently does not do that. Required for SD

CC: @mtatsumiTT @AleksKnezevic @davorchap

**Comment by tarafdarTT** [comment]
CC: @jliangTT

**Comment by tarafdarTT** [comment]
addressed in here: https://github.com/tenstorrent/tt-metal/pull/8279

**Comment by tarafdarTT** [comment]
Reopening because commit that addressed this was reverted
