### ISSUE TITLE
ttnn.std and  ttnn.var operations failed with low PCC value error [Grayskull and Wormhole]

### ISSUE THREAD

**Issue by banekg** [tenstorrent/tt-metal#7052]
**Describe the bug**
**ttnn.std** and **ttnn.var** operations break with "low PCC value" error in some test cases. 

**To Reproduce**
1. Checkout `barsic/model-preprocessing` branch. To be merged into `main` soon.
2. Run unit tests `test_std.py` and `test_var.py` using these commands:
`pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_std.py`
`pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_var.py`
3. NOTE: the same calls should be used for the **Wormhole**, to avoid duplicating files.

**Expected behavior**
There is a test case presented in the unit test `tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_std.py` and it is expected to fail with _low PCC value_ error.

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttnn.std and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_std_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `std_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by Aswinmcw** [comment]
@banekg @jliangTT, this issue is due to reduce operation

**Comment by KalaivaniMCW** [comment]
will be revisited after TTNN migration

**Comment by VirdhatchaniKN** [comment]
Hi @banekg 

- std works fine and the test passes.
- Fix for variance : #7963
