### ISSUE TITLE
Documentation is lacking a Pull Request Runbook

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-metal#7091]
Given the importance of making sure main is clean, it would be good to have a runbook for creating and merging Pull Requests

It would be good to cover the following in detail:
- creating the initial Pull Request (PR)
- specifying which tests to run based on the type of PR (e.g. different requirements for doc updates only vs core functionality updates)
- checking that your commit will be good once merged
- merging commits
- what to do if the commit will not be good
- merging into main
- verifying after the merge that everything is good
- what to do if something went wrong afterwards, and 
- best practices around reverts

Initial draft:

The tt-metal repository has a single main branch, with pull requests being merged in via rebase.

For a pull request, you will need to deal with a local branch and an origin branch.

The local branch should be on your VM, and you should interact with it through the command line or Visual Studio. The following uses the command line.
The origin branch is on Github and you should use the Github UI to interact with the branch.

1. Create the initial Pull Request (PR)

You need to have an issue. Either someone creates one and assigns it to you, or you need to create an issue. For example issue 123.

2. Create a branch on a VM. Include the user, the issue number, and optionally a description of the change. `/` and `-` are used as separators between user and issue number. And `-` and `_` between issue number and description. E.g.

```
git checkout -b user-123
git checkout -b user/123
git checkout -b user-123_rename_method_x
git checkout -b user/123-add-x-unit-test
```

3. Save your changes

Edit the files that you want, making sure relevant unit tests pass. Then add them in. E.g.

```
git add abc.py
git add -A
```

You can restore files if you need to get the original. E.g.

```
git restore abc.py
git restore '*'
git restore --staged abc.py # if the file was already added
```

Once you are satisfied that everything works, create a commit. The message needs to specify the issue number, with a pound sign and a colon, and the description should describe the change itself, and cannot be generic and refer to something else, such as saying that you are addressing reviewer feedback.

```
git commit -m"#123: rename method x"
```

Note: each commit should work. That is, everything compiles properly on the architecture used by your VM, you can run relevant code on the card, and relevant unit tests pass.

You can use `git log` to see the sequence of commits in the branch. That allows you to see where your branch is relative to main, and can help you figure out how the commits are structured, before and after commits and rebases.

4. Save the commit to origin and create a pull request

You will need to push the change to origin. The command will provide a url that you should use to create pull request. This should be done the first time you push a change. After that you may need to set upstream to be able to push changes in the future. E.g.

```
git push origin user-123:user-123
git branch --set-upstream-to=origin/user-123 user-123
```

Note: you may be able to push and set the upstream at the same time, but that assumes that you haven't rebased, which is probably not the case. The command would be something like

```
git push origin --set-upstream origin user-123
```

If that doesn't work, you should use `branch --set-upstream-to`.

Once you have a pull request, in the UI you can run actions against the branch. Go to Actions (https://github.com/tenstorrent/tt-metal/actions) and run the workflows that you want against your branch. At the very least, you should run All post-commit tests.

You can make more changes, commit them, and then if everything is set up and you don't need to rebase, then you can just do

```
git push
```

Occasionally, and for the final set of tests before the final commit, you should rebase your branch.

5. Rebase your branch

Your branch needs to be kept up to date with main via rebase. You should rebase your local branch, and then once everything looks good, push the change. You should not rebase your origin branch. That way, if anything goes wrong, you can use origin to restore your branch to a good state.

You should first make sure main is up to date:

```
git checkout main
git fetch origin # if you want to be extra safe
git pull --rebase --prune # accidentally make changes on local main, prune shows what got deleted
```

Then you can 

```
git checkout user-123
git rebase main
```

This will apply one commit at a time. Each commit is in order. If your branch has two commits, then the first one is applied, then the second one is applied.

If there are no conflicts, everything will complete successfully. Then you can push the changes to origin. This is done through a forced push to save the rebase information:

```
git push -f
```

If there is any conflict with the commits being processed, you will need to edit the files to fix the problem. Information should be printed about what to do. It's probably a good idea not to skip commits.

Don't be surprised if changes from a subsequent commit are not there in the first commit. For example, if you are editing the files to fix up the first of two commits, the files will not have the edits of the second commit. When editing files, only fix up the conflicts listed. Do not change anything else.

If you do change anything else, then `git rebase --continue` will complain and you will probably have to restart.

Look for `HEAD`. The conflict will look something like:

```
<<<< HEAD
Some other edits
====
Your edits
>>>> Your branch
```

Update the file to have a single piece of working code and remove the commit info. Make sure everything compiles and all the tests pass. Then you can continue with the rebase.

```
git rebase --continue
```

If something is wrong enough that you want to abort the rebase and undo all the changes, then you can start over. Do

```
git rebase --abort # go to before the rebase
```

If your local is in a bad state, you may also want to start from scratch on your local by pulling from origin, reflogging, or checking out a specific commit via its hash:

```
git pull --rebase # will undo changes
git reflog
git checkout <hash>
```

If none of those work you can also try:
```
git reset --hard origin/<BRANCH>
```

Note: If you are getting errors you may need to update the origin info via `git branch --set-upstream-to`. 

If everything goes well with all the updates. Then you can update origin:

```
git push -f
```

Note: It's okay to have a few commits, as long as each one works on its own. If you do want to combine commits you would want to run something like:

```
git rebase -i HEAD~10 # the number indicates how many commits you want to look at - here 10 commits
```

The latest one is at the bottom. You can use fixup or squash. Usually you want to use fixup (indicated by f) since that discards the message. Then edit the messages appropriately.

6. Merge to main

You will probably need to iterate several times in terms of pushing changes and rebasing your branch.

Once you have all of your changes working locally, your pull request (PR) approved, and all the workflows that you want passing after a final rebase, It is time to merge in your branch into main. This should be done in the Github UI.

Go to your PR and press the "Merge with rebase" button.

After that you can delete your branch in the UI.

**Comment by tt-rkim** [comment]
@jliangTT

@bbradelTT raised this as a gap in our onboarding infra. I've classified as a P3, but let me know if you think differently and we should get on this quicker.

**Comment by jliangTT** [comment]
p3 priority seems okay. i feel like dev should be empowered to improve documentation themselves too. i know @bbradelTT is doing some write-up and can pitch in. maybe it is a matter of poniting to Borys the right way to make the update? just 2c.

**Comment by tt-rkim** [comment]
Yes, @bbradelTT if you have anything to contributing to a written doc from your first couple weeks, please let us know

**Comment by bbradelTT** [comment]
@tt-rkim I don't have anything concrete yet. I'll update this thread when I do.

**Comment by bbradelTT** [comment]
@tt-rkim I updated the first comment / description to have a draft of what I'd like written. Any suggestions about where to save the text?

@arakhmati showed me what to do, I merged in some code, and did rebase a few times. The draft is based on that experience.
