### ISSUE TITLE
[Metal Trace] Add logic to automatically figure out the trace buffer page size

### ISSUE THREAD

**Issue by tooniz** [tenstorrent/tt-metal#7110]
We will want to empirically tune the number to start, to find out what the page sizes are for optimal NOC transfer and DRAM access for a given architecture.

Then we should turn those results into a min and a max threshold, to give us some flexibility since using a fixed number may result in DRAM wastage.

The final goal: Calculate the page size for interleaved buffer that
- is a power - of - 2 number (prefetch constraint),
- AND is evenly distributed across the banks (start_page = 0)
- AND falls inside min and max size constraints (optimal noc util),

fyi @pgkeller

**Comment by jliangTT** [comment]
hey @tooniz , the label shows it is p2 but in the project board it is p0. Can you clarify the priority?
