### ISSUE TITLE
ttnn.arange operation fails with "valid page size" error [Grayskull and Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#7145]
**Describe the bug**
**ttnn.arange** operation breaks with "RuntimeError: TT_FATAL @ tt_metal/impl/buffers/buffer.cpp:31: valid_page_size" error in some test cases. 

**To Reproduce**
1. Checkout `main` branch
2. Run unit test `test_arange.py` using this command:
`pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_arange.py`

**Expected behavior**
There is a test case presented in the unit test `tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_arange.py` and are expected to fail with VALID PAGE SIZE error

For example, the test is expected to fail with this error message: 
```
RuntimeError: TT_FATAL @ tt_metal/impl/buffers/buffer.cpp:31: valid_page_size
```

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttnn.geglu and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_arange_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `arange_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by Aswinmcw** [comment]
@jliangTT @npetrovic-tenstorrent , This arange op can contain both even and odd number of tensor elements, for tensor that needs to be created in the device should be even elements like [1,1,1,32] but some cases like [1,1,1,31] contains odd number of elements causing this error.
The implementation works correctly and only during tensor creation, this error occurs

**Comment by Aswinmcw** [comment]
Hi @npetrovic-tenstorrent , fix for this issue has been merged to main. Kindly check and close this issue. PR [Link](https://github.com/tenstorrent/tt-metal/pull/8238)

**Comment by Aswinmcw** [comment]
Hi @npetrovic-tenstorrent , fix for this issue has been merged to main. Kindly check and close the issue
[PR Link](https://github.com/tenstorrent/tt-metal/pull/8238)

**Comment by npetrovic-tenstorrent** [comment]
> Hi @npetrovic-tenstorrent , fix for this issue has been merged to main. Kindly check and close the issue [PR Link](https://github.com/tenstorrent/tt-metal/pull/8238)

Seems to be working now. I close the issue.
