### ISSUE TITLE
Mixtral8x7b T3000 hang

### ISSUE THREAD

**Issue by sraizada-tt** [tenstorrent/tt-metal#7165]
Mixtral8x7b demo on T3000 hangs at the 1st or 2nd iteration. Tried:

1. running on `bliu/issue-6472` branch (ref issue: [6472](https://github.com/tenstorrent-metal/tt-metal/issues/6472))  -- doesn't help
2. running with this commit from the all-gather hang issue: [b989c269a64c6d40a7523a94f3c4ba16b1eefd20](https://github.com/tenstorrent-metal/tt-metal/commit/b989c269a64c6d40a7523a94f3c4ba16b1eefd20) (ref issue: [6388](https://github.com/tenstorrent-metal/tt-metal/issues/6388))  -- doesn't help
3. setting core grid size to (y=4, x=8) -- hangs after 7 iterations instead of the 1st or 2nd but still hangs (this hang also hangs the t3000 reset, requires reboot to get the machine back)
4. running with watcher : After the first iteration run crashes with this:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Read 0xffffffff from ARC scratch[6]: auto-reset succeeded.
Fatal Python error: Aborted
```
On branch `mixtral8x7b-wh`:
`pytest models/demos/mixtral8x7b/demo/demo.py`

**Comment by sraizada-tt** [comment]
Running with the all-gathers commented out, we get a hang at iteration 16. Re-running the same, we get a hang at iteration 27. This is with core_grid 4x8. 

all-gather issue: https://github.com/tenstorrent-metal/tt-metal/issues/6388

**Comment by sraizada-tt** [comment]
More information: when we run the attention layer in loops and the MoE layer in loops - they don't hang, but when we run the decoder (which consists of 1 attention layer ands one MoE layer) in loops- it hangs after 7 iterations.

**Comment by sraizada-tt** [comment]
MoE layer when run in loops hangs for device_id=2 but doesn't hang for device_id=0, 1, 3, 4, 5, 6, 7. Unit test for reproducing: https://github.com/tenstorrent-metal/tt-metal/blob/mixtral8x7b-wh/models/demos/mixtral8x7b/tests/test_moe.py

**Comment by uaydonat** [comment]
I think we have a workaround for this? @sraizada-tt

**Comment by sraizada-tt** [comment]
works if matmul core_grid is set to (7, 6) -- decreases perf though

**Comment by uaydonat** [comment]
@sraizada-tt  we have been asked to try the Watcher and do the initial triaging for this hang. Does it look like a dispatcher hang or some other core is hanging? in which case FD2.0 will probably not fix the hang.

**Comment by uaydonat** [comment]
@sraizada-tt can we retry without the work-around on latest main (incl FD2) to see if this hang is still happening?

**Comment by sraizada-tt** [comment]
we get a segfault where we used to get a hang - workaround with (6, 7) grid still works

**Comment by uaydonat** [comment]
Can you file an issue for the seg fault (how to replicate it) and file it to jason (cc me)?

The runtime team is making a push to fix all the hangs/seg faults with FD2 so we do not need to use workarounds.

**Comment by davorchap** [comment]
> we get a segfault where we used to get a hang - workaround with (6, 7) grid still works

Where is the segfault, can you paste the error and repro instructions?

**Comment by sraizada-tt** [comment]
added new issue: https://github.com/tenstorrent/tt-metal/issues/8289 with error and reproduction instructions

**Comment by uaydonat** [comment]
new issue filed, closing this one.
