### ISSUE TITLE
Fast SFPU kernel for Exp 

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#7208]
* SFPU Exp is a critical function in Softmax and contributes 75%  of exec time.
* Softmax is the slowest OP in Stable Difffusion, BERT, and a significant contributor in LLM pre-fill (they're similar to BERT).

We need a faster Exp, here are the notes from a recent discussion:
* if we switch to Stable Softmax, then we can get rid of comparisons, branches in the SFPU kernel such as: 
```cpp
v_if (val >= 89) {
                vFloat val_inf = std::numeric_limits<float>::infinity();
                dst_reg[0] = val_inf;
            }
```
* Switching to Stable Softmax would also require changes to the Softmax compute kernel
* using SFPU assembly directly in the SFPU kernel

fyi @cglagovich @AleksKnezevic 

@ttmtrajkovic and @gilani let's sync on who can take this on.

**Comment by ttmtrajkovic** [comment]
The boundary checks could be guarded by templates to give the programmer an option to have softmax approximating function without checks and remove this:
```
v_if (val>=89){
                vFloat val_inf = std::numeric_limits<float>::infinity();
                dst_reg[0] = val_inf;
```

the negative check must still exist as we don't know the value of the max(x_i) and how much negative the number could get.

I am not sure I understand the next two bullet points:
>Switching to Stable Softmax would also require changes to the Softmax compute kernel
>using SFPU assembly directly in the SFPU kernel

Stable softmax should mean that we insert few extra ops in the graph: max(x) and x - max(x) so no impact on sfpu kernel.

milos

**Comment by davorchap** [comment]
fyi @yugaoTT

**Comment by yugaoTT** [comment]
I tested w/ and w/o the condition check in the exp SFPU, with a sharded softmax test of input shape of (8,8,768,384), and input data type of bfp8_b. 
The condition check is very slow compared to removing the condition:

w/ condition:
387211 ns

w/o condition:
230851 ns

there's about 150K overhead 
there's about 150K overhead

**Comment by pavlejosipovic** [comment]
@pavlepopovic  tried to use this variant of exp on falcon7b profile and have up on it as ppc dropped. right?

**Comment by ttmtrajkovic** [comment]
@yugaoTT,

Could you share the code used for your experiment? The number you pasted makes sense. 

@pavlejosipovic, 
I think this option can be used only on stable softmax, do you know if that was the case with @pavlepopovic ?

**Comment by pavlepopovic** [comment]
> @yugaoTT,
> 
> Could you share the code used for your experiment? The number you pasted makes sense.
> 
> @pavlejosipovic, I think this option can be used only on stable softmax, do you know if that was the case with @pavlepopovic ?

I wasnt using stable softmax

**Comment by yugaoTT** [comment]
@ttmtrajkovic I only commented out the condition check in my code, there is no stable softmax implemented so far. 
the test I run to get the result is: 
tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax_sharded.py::test_softmax

**Comment by ttmtrajkovic** [comment]
Ok, I can make this parametrizable so any op developer can use itOn Apr 10, 2024, at 19:40, Yu Gao ***@***.***> wrote:﻿
@ttmtrajkovic I only commented out the condition check in my code, there is no stable softmax implemented so far.
the test I run to get the result is:
tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax_sharded.py::test_softmax

**Comment by pavlepopovic** [comment]
I was able locally to test softmax_in_place() function that's using stable softmax.
Kernel needs to be modified to do a reduce max, followed by a sub_tiles_bcast(), and then perform the exponent call without `v_if (val >= 89)`.
Initial results show that kernel time of softmax op dropped from ~430k NS to ~380k NS following these improvements.
Modifying fused scale mask softmax is the next thing to experiment with.

**Comment by davorchap** [comment]
@ttmtrajkovic @yugaoTT @pavlepopovic Stan mentioned that Miles is working on a new version of an SFPU EXP that is super fast. I'll ping you on slack.

**Comment by ttmtrajkovic** [comment]
hey @davorchap,
Yes, I was helping Miles to setup his repo and test the code on exp tests. Stay tuned for results :).

**Comment by rtawfik01** [comment]
Fast exp has been merged here: https://github.com/tenstorrent/tt-metal/pull/7693
