### ISSUE TITLE
[Metal Trace] Skip tracing of EWB for program binaries

### ISSUE THREAD

**Issue by tooniz** [tenstorrent/tt-metal#7343]
**Describe the bug**
By default trace will record all commands written to the issue queue. 

However that records the WriteBuffer command for program binaries, making the trace buffer big and also making the trace replay slow

We should let the binary WB commands fallthrough and get dropped into the issue queue while recording other commands into the trace so we get binary caching in DRAM

**Comment by davorchap** [comment]
@tt-aho I think the cleaner solution is in user-space:
* not trace the initial iteration of model where EWB for binaries are expected
* we need to enforce that while capturing the trace all of Program cache lookups are hits , trace won't worked w/ non-cached binaries
* thus, if user tries to trace the initial iteration it will error out
* this also forces the user to make sure that all OPs are program cachable

**Comment by davorchap** [comment]
> I am not sure if there is more work to do here, or if the commit made Apr12 " [#7343](https://github.com/tenstorrent/tt-metal/issues/7343): Restore binary caching within a trace via forced commands" solves this...

@tt-aho and @kmabeeTT 
I don't think trace should silently drop any commands, for any command that we don't support tracing for , we should error out.
No tracing support for:
* EWB
* ERB
* un-cached EPs

**Comment by tt-aho** [comment]
Related to this. If we remove support for un-cached EPs, then we can remove the `trace_ctx->owned_buffer_pool` entirely since we were using it to pin program buffers (and tensor buffers which we also plan to remove) when we weren't running with program cache.

**Comment by tt-aho** [comment]
I've updated tracing to only support cached EPs. We longer support tracing record events (programs don't record an event anyways in non-blocking mode) and tracing shouldn't be used when host interaction is required anyways. They would need to be separate traces
