### ISSUE TITLE
Optimize Generation of Buffer Page mappings

### ISSUE THREAD

**Issue by tarafdarTT** [tenstorrent/tt-metal#7401]
Currently the page mappings are being formed in the constructor of device buffer. This is sub-optimal because 1) this is done at runtime 2) not all buffers even need the mappings.

This recently came up with a regression in Bert and ViT perf (which is why I'm labelling this as a p0. @jliangTT )

We only need the mappings when writing directly to a sharded buffer, reading back directly from a sharded buffer and the creation of the program in reshard. For most on device ops we can bypass this.

**Comment by tarafdarTT** [comment]
FYI: @davorchap @mo-tenstorrent

**Comment by tarafdarTT** [comment]
its been addressed in this PR: https://github.com/tenstorrent-metal/tt-metal/pull/7402
Waiting for approvals and then can merge

**Comment by jliangTT** [comment]
is this completed? I recall that you have fixed this one already right?

**Comment by tarafdarTT** [comment]
ah ya , sorry forgot to mark as completed. It's been merged.
