### ISSUE TITLE
ttnn.softplus operation failed with low PCC value error [Grayskull and Wormhole]

### ISSUE THREAD

**Issue by banekg** [tenstorrent/tt-metal#7404]
**Describe the bug**
**ttnn.softplus** operations break with "low PCC value" error on Grayskull in one test case. 

**To Reproduce**
1. Checkout `barsic/ttnn-param-fix-1` branch. To be merged into `main` soon.
2. Run unit test `test_eltwise_softplus_inf.py` using this command:
`pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_softplus_inf.py`

**Expected behavior**
There is a test case presented in the unit test `tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_softplus_inf.py` and it is expected to fail with _PCC: 0.0 value_ error.

The problem lies in the tensor comparison function which cannot handle the following case:

`PyTorch: tensor([[inf, inf, inf, inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf, inf, inf, inf, inf]])`

`TT: TorchTensor([[2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38,
              2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38],
             [2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38,
              2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38],
             [2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38,
              2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38],
             [2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38,
              2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38],
             [2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38,
              2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38],
             [2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38,
              2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38],
             [2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38,
              2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38],
             [2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38,
              2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38],
             [2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38,
              2.3660e+38, 2.3660e+38, 2.3660e+38, 2.3660e+38]],
            dtype=torch.bfloat16)`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttnn.std and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_softplus_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `eltwise_softplus_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by eyonland** [comment]
We need to verify that this passes for WH.

**Comment by KalaivaniMCW** [comment]
Ran `tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_softplus_inf.py` in **Wormhole N150 machine** and the test passed
 ![Image](https://github.com/user-attachments/assets/793fe73a-186d-4eab-a999-a86c8e50297f)
![Image](https://github.com/user-attachments/assets/2c59c6cc-79f6-40ee-9805-762a509afed3)
![Image](https://github.com/user-attachments/assets/7af0309f-700f-449e-b73a-c1316bc70184)

**Comment by KalaivaniMCW** [comment]
And Softplus is not supported in GS - refer [comment](https://github.com/tenstorrent/tt-metal/issues/9877#issuecomment-2243953309)
