### ISSUE TITLE
Hang in cb_wait_front When Using Various Formats in Kernel

### ISSUE THREAD

**Issue by dongjin-na** [tenstorrent/tt-metal#7406]
**Describe the bug**

When I try to use Uint32 for SFPU and bfloat16 for FPU in kernels, `cb_wait_front` in the writer kernel hangs. 
Please let me know if I missed something or wrote the code incorrectly.
This hang occurs under the following conditions; I've created a simple example:

### CB data format
```
CB::c_in0 = DataFormat::UInt32
CB::c_intermed0 = DataFormat::UInt32
CB::c_in1 = DataFormat::Float16_b
CB::c_out0 = DataFormat::Float16_b
```
### Compute kernel creation
- fp32_dest_acc_en is true

### compute kernel
- It just copies bfloat16 tile from c_in1 to dst register and then pack it to c_out0.
```
namespace NAMESPACE {
void MAIN {

    // uint32
    constexpr auto cb_in0{tt::CB::c_in0};
    constexpr auto cb_intermed0{tt::CB::c_intermed0};

    // bfloat16
    constexpr auto cb_in1{tt::CB::c_in1};
    constexpr auto cb_out0{tt::CB::c_out0};

    unary_op_init_common(cb_in1, cb_out0);
    // copy cb_in1 (bfloat16) to dst0
    unpack_reconfig_data_format_srca(cb_in1);
    tile_regs_acquire();
    cb_wait_front(cb_in1, 1);
    copy_tile_to_dst_init_short(cb_in1);
    copy_tile(cb_in1, 0, 0);
    tile_regs_commit();

    // pack dst0 to cb_out0 (bfloat16)
    PACK((  pack_reconfig_data_format(cb_out0) ));
    tile_regs_wait();
    cb_reserve_back(cb_out0, 1);
    pack_tile(0, cb_out0);
    cb_push_back(cb_out0, 1);
    tile_regs_release();

    PACK(DPRINT << "pack tile to cb_out0(bfloat16) is done" << ENDL());

}
} 
```

### writer kernel
```
        DPRINT << "writer before cb_wait_fronat(cb_id_out0)" << ENDL();
        cb_wait_front(cb_id_out0, onetile); // hanging
        DPRINT << "writer after cb_wait_fronat(cb_id_out0)" << ENDL();
        l1_read_addr = get_read_ptr(cb_id_out0);
        noc_async_write_tile(write_tile_id, dram_output_addrg, l1_read_addr);
        noc_async_write_barrier();
        cb_pop_front(cb_id_out0, onetile);
```

**To Reproduce**
Test code is in `origin/sfpu_uint32` branch.
```
pytest ./tests/tt_eager/python_api_testing/unit_testing/misc/test_sfpu.py::test_copy_tiles
```

**Comment by razorback3** [comment]
@jliangTT Would you assign anyone who can handle this bug? It is related to the dropout implementation. Maybe @ttmtrajkovic is the right person?

**Comment by ttmtrajkovic** [comment]
@dongjin-na, @razorback3,
The problem with this test is not a hang in the compute kernel but earlier, possibly in the dispatcher. I will dig some more in case I find something, otherwise, someone from metal-runtime should take a look.

**Comment by jliangTT** [comment]
ok. queuing to runtime queue to take a look.

**Comment by davorchap** [comment]
@dongjin-na does the compute kernel finish? 
does this get ` PACK(DPRINT << "pack tile to cb_out0(bfloat16) is done" << ENDL());` printed out from compute?

**Comment by dongjin-na** [comment]
> @dongjin-na does the compute kernel finish?
> does this get  PACK(DPRINT << "pack tile to cb_out0(bfloat16) is done" << ENDL()); printed out from compute?

- Yes. Here's the log output with DPRINT.
```
reader cb in0 data_format : 24
reader cb in0 tile bytes : 4096
reader input_addr 4128
reader num_tiles 1
reader start_id 0
pack tile to cb_out0(bfloat16) is done    // <---------- log from compute kernel.
writer cb out0 data_format : 5
writer cb out0 tile bytes : 2048
writer output_addr 8224
writer num_tiles 1
writer start_id 0
reader cb in1 data_format : 5
reader cb in1 tile bytes : 2048
reader in1 addr 8224
readeer done
writer before cb_wait_fronat(cb_id_out0)
```

- This test case uses a single Tensix core.

**Comment by ttmtrajkovic** [comment]
I looked at this a few weeks ago and there was no pack print or any debug print  that I’ve placed at the start of the kernel.Adding Reem to take a look when she has a chance, in case I missed anything.On May 2, 2024, at 14:58, Dongjin Na ***@***.***> wrote:﻿

@dongjin-na does the compute kernel finish?
does this get  PACK(DPRINT << "pack tile to cb_out0(bfloat16) is done" << ENDL()); printed out from compute?


Yes. Here's the log output with DPRINT.

reader cb in0 data_format : 24
reader cb in0 tile bytes : 4096
reader input_addr 4128
reader num_tiles 1
reader start_id 0
pack tile to cb_out0(bfloat16) is done    // <---------- log from compute kernel.
writer cb out0 data_format : 5
writer cb out0 tile bytes : 2048
writer output_addr 8224
writer num_tiles 1
writer start_id 0
reader cb in1 data_format : 5
reader cb in1 tile bytes : 2048
reader in1 addr 8224
readeer done
writer before cb_wait_fronat(cb_id_out0)


This test case uses a single Tensix core.

**Comment by ttmtrajkovic** [comment]
+ @rtawfik01 

hi Reem,
Could you please take a look when you get a chance.

milos

**Comment by rtawfik01** [comment]
Hi, there was missing operand ids that needed to be passed down to the LLK calls; otherwise, they were using the data formats from operand 0 (uint32 data format) by default while the function was supposed to work on operand 1 (bfloat16 data format). Now the test no longer hangs. The fixes are here: #8169 and #8179.

Please rebase your branch, and let me know if you have any other issues.

**Comment by dongjin-na** [comment]
@rtawfik01, I've checked the test example after rebase, and it no longer hangs, as you said.
I will let you know if the issue has been resolved in the dropout op implementation code base. (I'm currently working on something else, so I'll check it out as soon as it's finished.)

**Comment by davorchap** [comment]
@dongjin-na is this resolved?

**Comment by dongjin-na** [comment]
@davorchap , I plan to continue implementing dropout next week.  Is it okay to close the issue after checking to see if there are any kernel issues during the implementation process?  The work is expected to be completed within next week.

**Comment by dongjin-na** [comment]
The compute kernel for dropout works well. I appreciate your help. I'll close this issue.
