### ISSUE TITLE
Change CreateSemaphore API to return a semaphore ID

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#7426]
The current API poses 2 problems:
1) Exposing an address prevents the runtime from moving semaphore locations (needed for FD2.1)
2) Create complexity in runtime implementation and test code (eg test_prefetcher) trying to track both addresses and semaphore counts per core

(note: original plan was to rename this atomic counter, changed plan to just fix the address issues)

**Comment by davorchap** [comment]
as part of this change, rename to AtomicCounter to better reflect the underlying mechanism

**Comment by davorchap** [comment]
Moving to P1 , so that we can transition the OPs that use Semaphores (small subset) to the new API and have them ready

**Comment by aliuTT** [comment]
WIP branch with the API change to return semaphore ID: https://github.com/tenstorrent/tt-metal/pull/10468. 

@pgkeller @tt-aho, can you guys take a look, make sure this is the right direction? @TT-BrianLiu has been volunteered to help fix all the matmul kernels that uses semaphore address.

**Comment by aliuTT** [comment]
Changes in main.
