### ISSUE TITLE
[Bug Report] SFPI is different from what is expected

### ISSUE THREAD

**Issue by maychair** [tenstorrent/tt-metal#7455]
**Describe the bug**
I am trying to customize the SFPI function, for example, floating-point addition. However, the execution result of the function I implemented is different from what is expected.

**To Reproduce**
Here is my testing code:
```
inline void sfpu_custom_func() {
    // use dst_reg[1] as output
    // dst_reg[0] = 1.0f; //working
    // dst_reg[0] = dst_reg[0] + 1.0f; // working
    // dst_reg[0] = dst_reg[1]; // not working
    // dst_reg[0] = dst_reg[1] + 1; // not working
    dst_reg[0] = dst_reg[0] + dst_reg[1]; // not working

    // use dst_reg[1] as output
    // dst_reg[1] = 1.0f; // not working
    // dst_reg[1] = dst_reg[1] + 1.0f; // not working
}

namespace NAMESPACE {
void MAIN {
    uint32_t n_tiles = get_arg_val<uint32_t>(0);
    constexpr uint32_t dst_reg0 = 0;
    constexpr uint32_t dst_reg1 = 1;
    constexpr uint32_t output_dst_index = 0;

    binary_op_init_common(tt::CB::c_in0, tt::CB::c_in1, tt::CB::c_out0);

    for(uint32_t i = 0; i < n_tiles; i++) {
        acquire_dst(tt::DstMode::Full);
        cb_wait_front(tt::CB::c_in0, 1);
        cb_wait_front(tt::CB::c_in1, 1);

        UNPACK(( llk_unpack_AB_init<BroadcastType::NONE>(tt::CB::c_in0, tt::CB::c_in1) ));        
        UNPACK(( llk_unpack_AB(tt::CB::c_in0, tt::CB::c_in1, 0, 0)  ));

        MATH(( llk_math_eltwise_unary_datacopy_init<A2D, BroadcastType::NONE, DST_ACCUM_MODE>(false, false, tt::CB::c_in0) ));
        MATH(( llk_math_eltwise_unary_datacopy<A2D, BroadcastType::NONE, DST_ACCUM_MODE, UnpackToDestEn>(dst_reg0)));
        MATH(( llk_math_eltwise_unary_datacopy_init<B2D, BroadcastType::NONE, DST_ACCUM_MODE>(false, false, tt::CB::c_in1) ));
        MATH(( llk_math_eltwise_unary_datacopy<B2D, BroadcastType::NONE, DST_ACCUM_MODE, UnpackToDestEn>(dst_reg1)));

        MATH(llk_math_eltwise_unary_sfpu_0_param<APPROX>
                        (sfpu_custom_func,
                        sfpu_custom_func,
                        output_dst_index, VectorMode::RC);)

        cb_reserve_back(tt::CB::c_out0, 1);

        // copy data from dst to cb
        pack_tile(output_dst_index, tt::CB::c_out0);

        cb_push_back(tt::CB::c_out0, 1);
        cb_pop_front(tt::CB::c_in0, 1);
        cb_pop_front(tt::CB::c_in1, 1);
        release_dst(tt::DstMode::Half);
    }
}
}
```

**Expected behavior**
I want to copy srca to dst0, srcb to dst1, then perform floating-point addition using SFPI, and save the result in dst0. However, the copy is good and the result is very strange.
Printing dst1 directly shows normal results, and performing multiplication and addition separately using dst0 also yields normal results. However, when I use dst1 for operations, the results become strange.
**Screenshots**
 Here
is log:
```
(.venv) ➜  tt-metal git:(d96a89aeb) ✗ ./build/programming_examples/eltwise_sfpu
                  Metal | INFO     | Initializing device 0
                 Device | INFO     | Opening user mode device driver
2024-04-15 16:23:55.950 | INFO     | SiliconDriver   - Detected 1 PCI device : {0}
                  Metal | INFO     | AI CLK for device 0 is:   1300 MHz
                  Verif | INFO     | Created a random vector of size 32768
                  Verif | INFO     | Created a random vector of size 32768
input:
0.95017 0.228754 0.184809 0.559551 0.790026 0.00605003 0.692366 0.389153 
input:
0.516586 0.125242 0.152585 0.142815 0.348134 0.692358 0.338373 0.391108 
output:
1.20507 0.260248 0.494625 1.41601 1.60349 0.244383 1.36131 1.0332 
```

**Please complete the following environment information:**
- OS: [Ubuntu 22.04]
- Version of software (tt-metal d96a89aeb)

**Comment by maychair** [comment]
The hardware is grayskull e75.

**Comment by jliangTT** [comment]
Hey thanks for submitting this issue. 

It looks like the program is making use of our internal api(s). We do have user-facing API to provide low level programmability to our Grayskull hardware in the Metalium stack. The Metal API are more thought through for usability. See our doc [here](https://tenstorrent.github.io/tt-metal/latest/tt-metalium/).

If there are specific question, feel free to reach out to @mbahnasTT or @milank94, or ask here in order. Thanks.

**Comment by maychair** [comment]
Hey, thanks for replying.
I have read the API of the low-level kernel and would like to customize an SFPU kernel and I'm a bit confused. 
@jliangTT @mbahnasTT  Here are my questions:
1. Does Grayskull support customizing SFPU kernels using the SFPI interface?
2. Are there any examples available for reference (customizing SFPU kernels using SFPI)?
3. Is there any issue with using SFPI to implement addition dst_reg[0] = dst_reg[0] + dst_reg[1];? Why is the result different from what I expected?

**Comment by jliangTT** [comment]
> 1. Does Grayskull support customizing SFPU kernels using the SFPI interface? 

Yes, GS supports SFPI interface invoked from metalium host API that is user facing. Not direct invocation from user. 

> 2. Are there any examples available for reference (customizing SFPU kernels using SFPI)? 

@pgkeller , @tt-rkim, do you know of an example with metal program using SFPU kernel 

> 3. Is there any issue with using SFPI to implement addition dst_reg[0] = dst_reg[0] + dst_reg[1];? Why is the result different from what I expected? 

@rtawfik01 , do you mind comment on this?

**Comment by tt-rkim** [comment]
> Are there any examples available for reference (customizing SFPU kernels using SFPI)?

To my knowledge, there are no example kernels in metal where we directly use SFPI. Everything we use goes through either the available NOC or dataflow APIs.

Our current interface into SFPI right now is through the LLKs, which are different submodule repos. For example: https://github.com/tenstorrent/tt-llk-gs/blob/main/common/inc/ckernel_sfpi.h

**Comment by tt-rkim** [comment]
I did a search for certain keywords like `dst_reg` in `tt_metal/` and `tt_eager/` , where all of our kernels should be in metal.

It returned nothing.

**Comment by maychair** [comment]
It was indeed an issue with operation sizes and indexs. I tweaked my code, and now I can get the addition and multiplication results correctly. Thanks for your replies @jliangTT @tt-rkim @rtawfik01 , it helps a lot. Below is the correctly functioning SFPU kernel for reference:
```
template <bool APPROXIMATION_MODE, int ITERATIONS = 4>
inline void sfpu_custom_func()
{
    for (int d = 0; d < ITERATIONS; d++)
    {
        vFloat a = dst_reg[0];   // srcA
        vFloat b = dst_reg[16]; // srcB
        dst_reg[0] = a + b;
        dst_reg++;
    }
}
```
About customizing SFPU kernels, any additional notes are greatly appreciated.
