### ISSUE TITLE
[Bug Report] github.io broken link due to org repo migration

### ISSUE THREAD

**Issue by jliangTT** [tenstorrent/tt-metal#7471]
**Describe the bug**

FIX: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn 
FIX: https://tenstorrent-metal.github.io/tt-metal/latest/tt-metalium

works: https://tenstorrent.github.io/tt-metal/latest/ttnn 
works: https://tenstorrent.github.io/tt-metal/latest/tt-metalium

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by tt-rkim** [comment]
Done, reopen if new issues pop up pls
