### ISSUE TITLE
FD2: read back completion event order issue

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#7473]
Running on GS:
    build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch -s 1024 -a 128 -x 11 -y 8

Or on WH:
    build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch -w 5000 -s 1024 -x 7 -y 6 -S 4 -c 32 -a 128

Results in:
    Always | FATAL    | Event Order Issue: expected to read back completion signal for event 6 but got 0!

**Comment by pgkeller** [comment]
I ran:
    build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch -w 5000 -s 2048 -x 7 -y 6 -S 4 -c 32 -a 128
(changed the bin size up to 2K)
and got a hang in dispatcher process_wait (waiting for responses from workers).  I was going to file a separate issue on this, but after 3 more runs I got the "completion signal for event" issue above and not a hang.  Unclear if these are 2 manifestations of the same issue or separate issues.  Not filing this separate until the above is root caused

**Comment by aliuTT** [comment]
Event order is not out of order, but rather in this case, `event id = 6` value does not make it to the prefetcher (and therefore dispatcher) for the enqueue_record_event call. I commented out the assert and test does pass, so it's likely that there may be some host bug, and unlikely that it's a dispatch issue. I'm currently running on a N300/T3000 with this repro command:
```
build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch -w 2270 -x 7 -y 6 -a 128
```
`-w 2269` passes.

**Comment by aliuTT** [comment]
I'm going to dump the EnqueueProgram command vector for the passing and failing case, see if for some reason that specific number of warmup iteration is causing a corruption there.

**Comment by aliuTT** [comment]
Fix is in main.
