### ISSUE TITLE
FD2 watcher error in test_pgm_dispatch

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#7475]
Running on GS:
    build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch -s 256 -x 11 -y 8
Results in:
    Always | WARNING  | Device 0, Worker Core (x=0,y=9)[physical (x=1,y=11)]: ncrisc using noc0 tried to access Tensix core w/ physical coords (x=6,y=9) L1[addr=0x00019800,len=0]

Or running on WH:
    build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch -s 256 -n -t -x 7 -y 6 -S 4
Results in:
    Always | WARNING  | Device 0, Worker Core (x=0,y=7)[physical (x=1,y=9)]: ncrisc using noc0 tried to access Tensix core w/ physical coords (x=7,y=7) L1[addr=0x00018800,len=0]

(0 length transactions getting flagged)

**Comment by abhullar-tt** [comment]
TODO: add host side assert for this

**Comment by aliuTT** [comment]
Fixed on main
