### ISSUE TITLE
Improve documentation for ttnn glu, reglu, and geglu operations

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#7487]
For ttnn.glu, ttnn.reglu and ttnn.geglu operations have two limitations:

1. Last dimension of input tensor should be divisible by 64, 
2. dim parameter must reference last dimension (-1). In pytorch dim does not have to be -1.

Those limitations are not covered in documentation:

https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/ttnn/glu.html
https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/ttnn/reglu.html
https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/ttnn/geglu.html

Please improve documentation to reflect code.

Here are tickets which described those problems as bug which are now closed: https://github.com/tenstorrent/tt-metal/issues/6537, https://github.com/tenstorrent/tt-metal/issues/6687, https://github.com/tenstorrent/tt-metal/issues/6677

**Comment by mcw-anasuya** [comment]
Documentation updated and merged to main. Hence closing.
