### ISSUE TITLE
Stabilize night and perf pipelines for FD2 merge

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#7502]
@jliangTT @davorchap to track today's work on stabilizing CI for FD2 merge.

**Comment by tt-rkim** [comment]
Still working on this.

- @tt-rkim  Isolating ttnn to its own separate pipeline in nightly
- @arakhmati to fix some t5 errors
- @tt-rkim to triage remaining ttnn failures
- @tt-rkim to work on reverts to autoformat by @tt-asaigal to get falcon up and running again in perf pipeline

**Comment by TT-billteng** [comment]
we have stabiliized nightly and perf pipelines in preparation for FD2 merge
