### ISSUE TITLE
ttnn.matmul

### ISSUE THREAD

**Issue by jliangTT** [tenstorrent/tt-metal#7512]
tt::tt_metal::Matmul struct is removed, cleaning up the C++ code, making future changes easier to make.

**Comment by jliangTT** [comment]
This would required a sign-off between @bbradelTT , @arakhmati , and @TT-BrianLiu

**Comment by bbradelTT** [comment]
I checked with @arakhmati
Reshape and in-op validation for matmul are already in C++.
What would be needed is reshape moved to program cache and code clean up.
