### ISSUE TITLE
ttnn.transformer.split_query_key_value_and_split_heads

### ISSUE THREAD

**Issue by jliangTT** [tenstorrent/tt-metal#7519]

**Comment by sjameelTT** [comment]
for the block sharded implementation it's just the transpose functionality which I have on the below change. Made my own ticket for it though, apologies for that, can relabel it under this. Works on all my wormhole tests locally right now.

https://github.com/tenstorrent/tt-metal/tree/sjameel/create_qkv_heads_transpose

**Comment by TT-BrianLiu** [comment]
This is more so to track porting this op into c++?

**Comment by sjameelTT** [comment]
> This is more so to track porting this op into c++?

isn't downloading as much logic as possible into the ttlib API calls the way we plan on doing it or do we want to reimplement things from scratch?
