### ISSUE TITLE
`models/experimental/stable_diffusion/tests/` failures - GS only

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent/tt-metal#7536]
These SD tests are GS only run in the Nightly FD suite, currently failing with the same signature:

> launch_with_autoformat must be used if output tensor for op can be placed on host.
> 
> RuntimeError: TT_ASSERT @ tt_eager/tt_dnn/op_library/run_operation.cpp:713: outputs.at(i).tensor_attributes->dynamic_storage

`pytest models/experimental/stable_diffusion/tests/test_cross_attn_down_block.py -k test_run_cross_attn_down_block_real_input_inference`

`pytest models/experimental/stable_diffusion/tests/test_cross_attn_up_block.py -k test_run_cross_attn_up_block_real_input_inference`

`pytest models/experimental/stable_diffusion/tests/test_unet_mid_block.py -k test_run_unet_mid_block_real_input_inference`

`pytest models/experimental/stable_diffusion/tests -k test_unbatched_stable_diffusion`

Skipping on CI until fixed

CC: @tt-rkim @TT-billteng

**Comment by vtangTT** [comment]
CC: @jliangTT

**Comment by jliangTT** [comment]
I think most of the development of stable_diffusion is on WH. @AleksKnezevic @boris-drazic , is this GS current p2?

**Comment by AleksKnezevic** [comment]
Yes, that's correct. We're only targeting wormhole at this time.

**Comment by mywoodstock** [comment]
Do we need this? I believe we are not going to support SD on grayskull. cc: @esmalTT

**Comment by tt-rkim** [comment]
If not, we can close, but we should update any README documentation at project root + models for this right?

**Comment by esmalTT** [comment]
I don't think any of the docs refer to SD on GS. Think we're good to close this 👍

**Comment by tt-rkim** [comment]
Thanks guys, re-open if issues
