### ISSUE TITLE
Stable Diffusion error on FD2

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#7537]
On N300:
`WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest tests/ttnn/integration_tests/stable_diffusion/test_unet_2d_condition_model.py::test_unet_2d_condition_model_512x512[batch_size=2-in_channels=4-input_height=64-input_width=64]`

Result is an out of bounds error that tracks back to dispatch code, this test passes on main but fails on fd-2/main. See https://github.com/tenstorrent/tt-metal/actions/runs/8713514940/job/23902066530

**Comment by abhullar-tt** [comment]
This passes on branch that has support for running FD out of eth :)
