### ISSUE TITLE
`models/experimental/mamba/tests/` failures - WH only

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent/tt-metal#7551]
These mamba tests on failing for nightly fd CI: 

`models/experimental/mamba/tests/test_full_model.py`
`models/experimental/mamba/tests/test_demo.py`

Going to skip on CI

CC: @TT-billteng @tt-rkim

**Comment by tt-rkim** [comment]
Raising this as P1 for models team. @jliangTT 
Hopefully @kpaigwar 's new PR fixes this. We found this while fixing nightly models pipeline.

**Comment by vtangTT** [comment]
CC: @jliangTT

**Comment by kpaigwar** [comment]
Yes the proposed PR will fix this. I am testing all the changes locally before I ask for review

**Comment by kpaigwar** [comment]
They are fixed in the main. Forgot to close the issue.
