### ISSUE TITLE
Create new pipeline / augment existing FD post-commit to account for `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml` for FD2 tests

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#7555]
@abhullar-tt requested that we enable the FD2 team to run fast dispatch tests with this environment variable so they can run with ethernet cores.

Some requirements are:

- fast dispatch suite with env var `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml`
- It's ok if this only applies to WH X2
- They will likely be running this often

Somet things to ask are:

- How often do you want to run just with this env var?
- Are you okay if you still have to go through the regular post-commit pipeline flow where you have to run everything?

cc: @TT-billteng

**Comment by tt-rkim** [comment]
@abhullar-tt 
Should we make the ethernet core descriptor the default now, or?

**Comment by abhullar-tt** [comment]
> @abhullar-tt Should we make the ethernet core descriptor the default now, or?

No, we don't have full watcher / dprint support for FD out of ethernet and there are still some tests that are failing. We would want parity before making it the default. Just need some level of regression testing in the interim since there is none now

**Comment by tt-rkim** [comment]
this project is done
