### ISSUE TITLE
[llama] E2E potential issues

### ISSUE THREAD

**Issue by kevinmiTT11** [tenstorrent/tt-metal#7558]
profiled using this command `python -m tracy -m pytest -svv models/experimental/llama2_70b/tests/test_llama_perf_decode.py::test_Llama_perf_host[quick]`

- [ ] Gap between tt_lib ops when using lambda in program configs (lru cache? precompute model config before foward call)

**Comment by uaydonat** [comment]
@cglagovichTT is this still relevant?

**Comment by cglagovichTT** [comment]
Not relevant, we have better issues to track e2e now
