### ISSUE TITLE
Stable Diffusion nd hang on N150 CI

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#7573]
See N150 CI run https://github.com/tenstorrent/tt-metal/actions/runs/8730537394/job/23961062075, doesn't happen every time

**Comment by aliuTT** [comment]
Trying locally on an N300 after `e46e280b2010666bf0c61b05e8eb23d40e521b7d`, so far passing

**Comment by aliuTT** [comment]
This test is removed on main: https://github.com/tenstorrent/tt-metal/commit/89064484416057025717fc08bd1ad2435ba68668

David to check what happened, but otherwise I'll lower priority to P1. Seems like it's not gating merge.

**Comment by tt-dma** [comment]
Test removed on main due to this same issue, so this isn't an FD issue, closing
