### ISSUE TITLE
Deprecate `WH_ARCH_YAML` env var and make dispatch out of eth cores default for WH

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#7606]
Functionality depends on:

- [x] #7573 
- [x] #7480 
- [x] #7603 
- [x] #5973

**Comment by davorchap** [comment]
Let's decide on Monday on this. Nick mentioned the model team wants 8x8 as the default grid, in which case we deprecate this and make 8x8 the default.

**Comment by pgkeller** [comment]
can this be closed?

**Comment by abhullar-tt** [comment]
> can this be closed?

we deprecated the env var but I don't think we want to make eth dispatch default for now, closing for now and will re-open another issue if it needs to be made default
