### ISSUE TITLE
Attempt to run 8x8 grid test results in hang

### ISSUE THREAD

**Issue by imatosevic** [tenstorrent/tt-metal#7613]
A test of the FD2 packetized path that uses many cores across 8 rows and 8 columns was observed to hang on some WHB0 systems. For example, the hang was observed in this regression:
https://github.com/tenstorrent/tt-metal/actions/runs/8707961154/job/23884693545#step:8:2561

After the test was changed to use only 6 rows, it passes. 

I also tested with the following change from @abhullar-tt, which adds a check in case a kernel is run on a storage-only core:
9a8e29edcdb5e404283c8996525d99a6ce5d05b7

With this change, the test reports the error: "Cannot program core (x=7,y=7). It is reserved for storage and no compute", so that seems to be the problem. 

As long as we have the storage-only core restriction, we should have a check like the above to avoid hangs.

**Comment by abhullar-tt** [comment]
> upgrading as we should fix this for metal release 1.0

I have a branch with a fix for this, was just forgotten about. Ill rebase and merge
