### ISSUE TITLE
Investigate ttnn perf t5-small regression

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#7619]
https://github.com/tenstorrent/tt-metal/actions/runs/8742619140/job/23991319245

`AssertionError: Some model(s) Inference Time (sec) are too slow, see above for details on slow models: [('ttnn_google/flan-t5-small_ ', 6.4949, 4.0), ('ttnn_phiyodr/bert-large-finetuned-squad2_ ', 46.7346, 32.0), ('ttnn_t5-small_ ', 4.6138, 3.0)]`

Might just be a simple bisect.

Ignoring for now.

@TT-billteng @jliangTT @vtangTT

**Comment by TT-billteng** [comment]
I assume we got over this
