### ISSUE TITLE
Reshard has very low perf in RN50

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#7623]
Branch: `main` (4875899c6748d979ec54a4c6cbae0705beb14902)
Test: `pytest tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet50.py::test_resnet_50[batch_size=20-act_dtype=DataType.BFLOAT8_B-weight_dtype=DataType.BFLOAT8_B-math_fidelity=MathFidelity.LoFi]`

There are few reshards in RN50, see below. One of them takes almost 450K ns!
<img width="1909" alt="Screenshot 2024-04-18 at 14 17 56" src="https://github.com/tenstorrent/tt-metal/assets/704486/38080bbf-be6d-4454-95f9-20b73e0b4e7a">

Here are their input/output shapes:
<img width="1387" alt="Screenshot 2024-04-18 at 14 34 46" src="https://github.com/tenstorrent/tt-metal/assets/704486/1dea1569-ccef-414d-af25-4d7598d96dc8">
<img width="1342" alt="Screenshot 2024-04-18 at 14 34 59" src="https://github.com/tenstorrent/tt-metal/assets/704486/8c9a6c84-c8ac-4bb2-8ecf-290e45657dca">

Breakdown of all ops with categories:
<img width="1330" alt="Screenshot 2024-04-18 at 16 20 18" src="https://github.com/tenstorrent/tt-metal/assets/704486/392fb61b-8d87-4195-9901-eecdae1a203f">

**Comment by jliangTT** [comment]
@davorchap instructed that we make this a p0 because stable diffusion and resnet is low performant because of it. Will spin up a message to prioritize this against other P0.

**Comment by tarafdarTT** [comment]
@mywoodstock can you comment with a branch and how to run.

**Comment by mywoodstock** [comment]
@tarafdarTT updated the description with these details.

**Comment by tarafdarTT** [comment]
@jliangTT @davorchap @mywoodstock , I'm lowering this to P1. The major update has been merged. I think a little bit more low hanging fruit is available that I will work on today (I don't have other P0s at the moment, but I have other P1s) , because this op is everywhere. I'll see what more perf I can squeeze out today.
