### ISSUE TITLE
Tilize/Untilize TMs should use multicore as default

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#7625]
dependent: https://github.com/tenstorrent/tt-metal/issues/4332

- [x] Tilize
- [x] Untilize
- [x] TilizeWithValPadding
- [x] UntilizeWithUnpadding

**Comment by TT-BrianLiu** [comment]
Going to flip tilize and untilize to multicore default first.

**Comment by TT-BrianLiu** [comment]
`TilizeWithValPadding` and `UntilizeWithUnpadding` needs review. Right now, only sharded is multi-core. Not sure why interleaved is single core
