### ISSUE TITLE
Matmul default configs 

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#7627]
WH
* L1 accum = true (bfloat16) 
* Pick sharding scheme based on shape: tall, wide, square
   - if Block sharding them use RM (transpose_mcast=false)
* max sub-block size we can fit to half-dst
* fidelity default = LoFi

**Comment by davorchap** [comment]
@acejkov @yugaoTT @TT-BrianLiu need your input on the best defaults

**Comment by davorchap** [comment]
fyi @mywoodstock

**Comment by yugaoTT** [comment]
There is also in0_block_w, that can be smaller than the shard block width, but need to try out for each matmul individually

**Comment by acejkov** [comment]
To add on top of what Davor mentioned: 
Max in0_block_w which is block accumulation dim 
Max input block size that fits into L1 to reduce number of wait/pop calls

Output sub-block dim is critical to enable re-use in src registers.

**Comment by bbradelTT** [comment]
fidelity is LoFi if a program config or user grid is specified. Otherwise it's HiFi2. That was to maintain existing behaviour for models.

max subblock, as specified in SUBBLOCK_HW_CHOICES, is 8 tiles or less which fits to half-dst

there is code that chooses the uOP and transpose_mcast based on dimensions

**Comment by bbradelTT** [comment]
Talked to @TT-BrianLiu and @yugaoTT 

L1 accum does not change max subblock size (it's still 8). Therefore the current behaviour should be okay.

Therefore all four items are currently covered.

@davorchap any other concerns?

If not, I'll close this issue.

**Comment by davorchap** [comment]
> Talked to @TT-BrianLiu and @yugaoTT 
> 
> 
> 
> L1 accum does not change max subblock size (it's still 8). Therefore the current behaviour should be okay.
> 
> 
> 
> Therefore all four items are currently covered.
> 
> 
> 
> @davorchap any other concerns?
> 
> 
> 
> If not, I'll close this issue.
> 
> 

Do we auto-pick a sharding scheme ?

**Comment by bbradelTT** [comment]
> Do we auto-pick a sharding scheme ?

Yes. If output mem config is sharded then we choose the sharding scheme based on the program config that is used and various values (M, N, per core M/N, transpose mcast, etc.). If output mem config is not sharded then just call `operation::generic_create_output_tensors(*this, input_tensors, this->output_dtype, Layout::TILE, this->output_mem_config)`

See [create_output_tensors](https://github.com/tenstorrent/tt-metal/blob/main/ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp#L1078) for details.

**Comment by bbradelTT** [comment]
I think everything in this issue is covered. Closing.
