### ISSUE TITLE
Conv default configs

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#7628]
WH

- [x] L1 accum = true (bfloat16)
- [x] max sub-block size we can fit to half-dst
- [x] fidelity default = LoFi
- [ ] sharding scheme manual for now: 
- [ ]       - need to add width sharding
- [ ]       - later on Pick sharding scheme based on shape: tall, wide, square
- [x] #7848

**Comment by mywoodstock** [comment]
The configs are all set for WH. Sharding selection is still manual. Closing this.
