### ISSUE TITLE
`add_unary`, `sub_unary` and `mul_unary` don't propagate the memory config to the underlying op

### ISSUE THREAD

**Issue by arakhmati** [tenstorrent/tt-metal#7637]
Even though `add_unary`, `sub_unary` and `mul_unary` have memory config as an argument, they do not propagate to the underlying op. It effectively gets ignored. New `ttnn::operation::binary::Binary` operation had to updated to have the same bug for now in order to make the models work

**Comment by TT-BrianLiu** [comment]
Fixed with: https://github.com/tenstorrent/tt-metal/pull/9939
