### ISSUE TITLE
Some ttnn operations failed for BFLOAT8_B type [Grayskull and Wormhole]

### ISSUE THREAD

**Issue by banekg** [tenstorrent/tt-metal#7644]
**Describe the bug**

Some **ttnn** operations failed when BFLOAT8_B is used as a data type. The operations which are failing are:

- ttnn.softplus
- ttnn.softshrink
- ttnn.softsign
- ttnn.polygamma
- ttnn.threshold
- ttnn.rad2deg
- ttnn.isclose

**To Reproduce**
1. Checkout `main` branch.
2. Run unit test `test_eltwise_softplus.py` using this command:
`pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_softplus.py`

**Expected behavior**
There is a test case presented in the unit test `tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_softplus.py` and it is expected to fail with 
`TT_FATAL @ tt_eager/tt_dnn/op_library/bcast/bcast_op.cpp:92: input_tensor_a.get_dtype() == input_tensor_b.get_dtype()` error.

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttnn.std and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_softplus_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `eltwise_softplus_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by jliangTT** [comment]
@umadevimcw , let me know if these are all eltwise. Or we need to break up the list.

**Comment by umadevimcw** [comment]
@jliangTT @banekg all the above ops depends on `mk_tiled_scalar` and the logic has only BFLOAT16 type
```
template <typename T>
Tensor mk_tiled_scalar(T value) {
    assert(std::is_scalar<T>::value && "T should be scalar");
    std::array<unsigned int, 4> shape = {1, 1, TILE_HEIGHT, TILE_WIDTH};
    std::vector<bfloat16> buffer_vec(TILE_HW, bfloat16(0));
    buffer_vec[0] = bfloat16(value);
    auto buffer = owned_buffer::create(std::move(buffer_vec));
    Tensor scalar = Tensor(OwnedStorage{buffer}, shape, DataType::BFLOAT16, Layout::TILE);
    return scalar;
}

```
Hence all the above ops throws error for `bfloat8_b` datatype.

**Comment by umadevimcw** [comment]
@jliangTT Even when i tried to add the support to mk_tiled_scalar to support bf8 I am getting following error

```
In file included from tt_eager/tt_dnn/op_library/complex/complex_ops.hpp:7,
                 from tt_eager/tt_dnn/op_library/complex/complex_ops.cpp:5:
tt_eager/tt_dnn/op_library/composite/composite_ops.hpp: In function ‘tt::tt_metal::Tensor tt::tt_metal::mk_tiled_scalar(T, tt::tt_metal::DataType)’:
tt_eager/tt_dnn/op_library/composite/composite_ops.hpp:54:45: error: could not convert ‘buffer’ from ‘tt::tt_metal::owned_buffer::Buffer<bfloat8_b>’ to ‘tt::tt_metal::OwnedBuffer’ {aka ‘std::variant<tt::tt_metal::owned_buffer::Buffer<short unsigned int>, tt::tt_metal::owned_buffer::Buffer<int>, tt::tt_metal::owned_buffer::Buffer<unsigned int>, tt::tt_metal::owned_buffer::Buffer<float>, tt::tt_metal::owned_buffer::Buffer<bfloat16> >’}
   54 |         Tensor scalar = Tensor(OwnedStorage{buffer}, shape, DataType::BFLOAT8_B, Layout::TILE);
      |                                             ^~~~~~
      |                                             |
      |                                             tt::tt_metal::owned_buffer::Buffer<bfloat8_b>
In file included from tt_eager/tt_dnn/op_library/eltwise_unary/eltwise_unary_op.cpp:11:
tt_eager/tt_dnn/op_library/composite/composite_ops.hpp: In function ‘tt::tt_metal::Tensor tt::tt_metal::mk_tiled_scalar(T, tt::tt_metal::DataType)’:
tt_eager/tt_dnn/op_library/composite/composite_ops.hpp:54:45: error: could not convert ‘buffer’ from ‘tt::tt_metal::owned_buffer::Buffer<bfloat8_b>’ to ‘tt::tt_metal::OwnedBuffer’ {aka ‘std::variant<tt::tt_metal::owned_buffer::Buffer<short unsigned int>, tt::tt_metal::owned_buffer::Buffer<int>, tt::tt_metal::owned_buffer::Buffer<unsigned int>, tt::tt_metal::owned_buffer::Buffer<float>, tt::tt_metal::owned_buffer::Buffer<bfloat16> >’}
   54 |         Tensor scalar = Tensor(OwnedStorage{buffer}, shape, DataType::BFLOAT8_B, Layout::TILE);
      |                                             ^~~~~~
      |                                             |
      |                                             tt::tt_metal::owned_buffer::Buffer<bfloat8_b>
In file included from tt_eager/tt_dnn/op_library/backward/backward_ops.cpp:5:
tt_eager/tt_dnn/op_library/composite/composite_ops.hpp: In function ‘tt::tt_metal::Tensor tt::tt_metal::mk_tiled_scalar(T, tt::tt_metal::DataType)’:
```


Updated logic is
```

template <typename T>
Tensor mk_tiled_scalar(T value, DataType dtype) {
    assert(std::is_scalar<T>::value && "T should be scalar");
    std::array<unsigned int, 4> shape = {1, 1, TILE_HEIGHT, TILE_WIDTH};
    if(dtype == DataType::BFLOAT8_B)
    {
        std::vector<bfloat8_b> buffer_vec(TILE_HW, bfloat8_b(0));
        buffer_vec[0] = bfloat8_b(value);
        auto buffer = owned_buffer::create(std::move(buffer_vec));
        Tensor scalar = Tensor(OwnedStorage{buffer}, shape, DataType::BFLOAT8_B, Layout::TILE);
        return scalar;
    }
    else
    {
        std::vector<bfloat16> buffer_vec(TILE_HW, bfloat16(0));
        buffer_vec[0] = bfloat16(value);
        auto buffer = owned_buffer::create(std::move(buffer_vec));
        Tensor scalar = Tensor(OwnedStorage{buffer}, shape, DataType::BFLOAT16, Layout::TILE);
        return scalar;
    }

}
```

@jliangTT @tt-aho

**Comment by banekg** [comment]
The documentation does not specify that the BFLOAT8_B type is not supported.

Please check the following links:

- https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/ttnn/polygamma.html
- https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/ttnn/softplus.html
- ...

**Comment by umadevimcw** [comment]
@banekg We can update the document. 

@tt-aho Any comments on this issue and observations https://github.com/tenstorrent/tt-metal/issues/7644#issuecomment-2076466100

https://github.com/tenstorrent/tt-metal/issues/7644#issuecomment-2076585120

**Comment by tt-aho** [comment]
bfp8 is stored as an owned u32 buffer.

You can create the initial vector as float and then create the bfp8 tensor similar to below

```
auto output_packed_data = pack_fp32_vec_as_bfp8_tiles(output_float_data, /*row_major_input=*/false, /*is_exp_a=*/false);
    auto output_uint32_buffer = owned_buffer::create<uint32_t>(std::move(output_packed_data));
    return Tensor(std::move(OwnedStorage{std::move(output_uint32_buffer)}), float_tensor.get_legacy_shape(), DataType::BFLOAT8_B, tensor.get_layout());
```

**Comment by umadevimcw** [comment]
@banekg Please test above ops with this PR https://github.com/tenstorrent/tt-metal/pull/8485

**Comment by umadevimcw** [comment]
> bfp8 is stored as an owned u32 buffer.
> 
> You can create the initial vector as float and then create the bfp8 tensor similar to below
> 
> ```
> auto output_packed_data = pack_fp32_vec_as_bfp8_tiles(output_float_data, /*row_major_input=*/false, /*is_exp_a=*/false);
>     auto output_uint32_buffer = owned_buffer::create<uint32_t>(std::move(output_packed_data));
>     return Tensor(std::move(OwnedStorage{std::move(output_uint32_buffer)}), float_tensor.get_legacy_shape(), DataType::BFLOAT8_B, tensor.get_layout());
> ```

Thanks @tt-aho It works.

**Comment by umadevimcw** [comment]
@banekg and @tt-aho @eyonland Kindly review this PR https://github.com/tenstorrent/tt-metal/pull/8485

@banekg Please test these test cases in the above PR (branch : umadevimcw/ttnn_bf8_tests)

**Comment by nemanjagrujic** [comment]
> @banekg and @tt-aho @eyonland Kindly review this PR #8485
> 
> @banekg Please test these test cases in the above PR (branch : umadevimcw/ttnn_bf8_tests)

Hello @umadevimcw, @banekg is not in TT anymore. I will take this and checkout. You can also ping @npetrovic-tenstorrent for instead of @banekg.

**Comment by umadevimcw** [comment]
@nemanjagrujic sure thanks for the info

**Comment by umadevimcw** [comment]
Closing this issue as fixes are merged to main
