### ISSUE TITLE
ttnn.mean operation failed with low PCC [Wormhole]

### ISSUE THREAD

**Issue by banekg** [tenstorrent/tt-metal#7645]
**Describe the bug**
**ttnn.mean** operation breaks with "low PCC value" error in some test cases. 

**To Reproduce**
1. Checkout `main` branch.
2. Run unit test `test_mean.py` by using this command:
`pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_mean.py`

**Expected behavior**
There is a test case presented in the unit test `tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_mean.py` and it is expected to fail with _low PCC value_ error.

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttnn.std and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/ttnn_mean_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `mean_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by KalaivaniMCW** [comment]
![Screenshot 2024-04-30 at 7 34 54 PM](https://github.com/tenstorrent/tt-metal/assets/156762498/25e5bdc1-7c17-40f2-95e9-b7e5952cf2f2)
