### ISSUE TITLE
Hang when using enable_persistent_kernel_cache

### ISSUE THREAD

**Issue by mtairum** [tenstorrent/tt-metal#7651]
On recent main commits (Last one tested: `77ba946`) we are seeing hangs on the mistral7b demo code when using `enable_persistent_kernel_cache` in conjunction with `program_cache`.

The hang disappears if we disable `program_cache` or the `persistent_kernel_cache`, but both on it hangs.

This is currently impacting mistral7b performance, going from around 11 tok/s/u to around 8 tok/s/u end-to-end.

**Comment by davorchap** [comment]
@mtairum program cache should be sufficient to get the target end2end performance. 
Persistent kernel cache only saves kernel binary compile time, which happens only during the first past of the model.
First couple of model iterations should be discounted for performance measurements anyway , during which kernel binaries are compiled and program cache is constructed.

**Comment by jliangTT** [comment]
@arakhmati , this failed w/ program cache. Are you the right person to debug this?

**Comment by jliangTT** [comment]
leave it un-prioritize for now. Is this the highest order performance issue we should look at?

**Comment by uaydonat** [comment]
Do we have a fix for this? @mtairum

**Comment by mtairum** [comment]
No, no fix yet.

**Comment by jliangTT** [comment]
Can we identify the op that we are hanging on? And the visualizer can also yield a hash for that the program hash on? 

@eyonland, can you share the documentation?

**Comment by mtairum** [comment]
I've tested both in release and debug mode, no hangs anymore. closing this issue.
