### ISSUE TITLE
Investigate "Cannot mix single and multi-device tensors when calling launch op!" in ttnn_falcon7b multi-chip nightly tests

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#7664]
Skipping for now

**Comment by tt-rkim** [comment]
cc: @jliangTT 
This is the test that we needed to disable for @kevinmiTT11

**Comment by tt-asaigal** [comment]
Hey I think this should be fixed with changes staged here: https://github.com/tenstorrent/tt-metal/pull/7689.

**Comment by arakhmati** [comment]
This is fixed on `main`
