### ISSUE TITLE
Disable zero initialization of commands by default

### ISSUE THREAD

**Issue by tooniz** [tenstorrent/tt-metal#7671]
For https://github.com/tenstorrent/tt-metal/issues/6428

We've enabled zero initialization of commands by default, with an user opt-out of `TT_METAL_ZERO_INIT_DISABLE=1`. That makes bringup and debug easier for FD2.

Once it's stable and ready for production, we should flip the switch to default uninitialized for performance and more stress testing

The right way to flip the switch should be turning the following in device_command.cpp into a compile time flag:
```
bool DeviceCommand::zero_init_disable = tt::parse_env<bool>("TT_METAL_ZERO_INIT_DISABLE", false);
```

something like the following so at the place of use we can do `if constexpr (!zero_init_disable)` and it'll have no runtime cost
```
`ifdef DEBUG
constexpr bool DeviceCommand::zero_init_disable = false;
`else
constexpr bool DeviceCommand::zero_init_disable = true;
`endif
```

**Comment by abhullar-tt** [comment]
We moved away from using `TT_METAL_ZERO_INIT_DISABLE`. This doesn't seem relevant anymore
