### ISSUE TITLE
Investigate non-deterministic hang on all gather test in multi-chip unit tests

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#7705]
https://github.com/tenstorrent/tt-metal/actions/runs/8762147802/job/24049539678

We've been the seeing the all-gather test fail ND recently. This is the example:

`tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py::test_all_gather_on_t3000_post_commit_looping[100-mem_config0-input_dtype0-4-2-input_shape3-3-layout3]`

however I don't think it may be limited to this.

cc: @tt-asaigal @tapspatel @TT-billteng @tt-snijjar

**Comment by SeanNijjar** [comment]
Reducing the loop count doesn't help at all here. The all gather gets stuck during dispatch of the first loop iteration, for the problem config.

**Comment by tt-rkim** [comment]
Skipping the test on main: https://github.com/tenstorrent/tt-metal/pull/7715

**Comment by tt-rkim** [comment]
Skipping all all gather, more hangs: 

https://github.com/tenstorrent/tt-metal/actions/runs/8795617131/job/24136986192
https://github.com/tenstorrent/tt-metal/actions/runs/8797746666/job/24143313725

in multi chip unit tests
