### ISSUE TITLE
TTNN exp-alike ops - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#7709]
For the following TTNN exp-alike ops:
- exp, exp2, expm1

The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, its seems that some of them support BFLOAT8_B, while only exp seems to support ROW_MAJOR. All the others only support TILE layout.

**Comment by Aswinmcw** [comment]
Will revisit this task and update it after migration task

**Comment by VirdhatchaniKN** [comment]
Fix provided : #7879

**Comment by umadevimcw** [comment]
Closing this as already merged to main
