### ISSUE TITLE
Fix f12cs02 build artifact errors exposed when using the Python API

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#7710]
You'll see this weird issue with 

https://github.com/tenstorrent/tt-metal/actions/runs/8773192610
https://github.com/tenstorrent/tt-metal/actions/runs/8775147721

I'm personally 99.9% sure it's because `LD_LIBRARY_PATH` isn't set / `rpath` doesn't point to `/home/ubuntu/.../build/lib`.

Either

- changing usernames of T3ks in cloud to `ubuntu`, or
- setting `LD_LIBRARY_PATH` in all our pipelines that use `build-artifact`

**Comment by tt-rkim** [comment]
@TT-billteng What's your opinion on how we should set this? I'm leaning towards `LD_LIBRARY_PATH` for tests as we're doing this in post-commit, but we should also ideally make our runners uniform

There is some weirdness you can get by setting hardcoded `rpath`s as well

**Comment by TT-billteng** [comment]
I don't like using `LD_LIBRARY_PATH` because it's yet another environment variable we need to modify. This one is more loaded because it's well known and others may use it.

**Comment by tt-rkim** [comment]
Sounds good, for current and future binary releases such as through conda channels, we'll need to strip out the `rpath` or use the artifacts from the pure build pipeline, otherwise people can't use them anyway unless they make a `/home/ubuntu/.../build/...` on their machines

Fix here is to change usernames of the machines.

I've taken the two new T3Ks out of service for now

**Comment by tt-rkim** [comment]
Closing because `ubuntu` user set on all machines. Thanks @TT-billteng
