### ISSUE TITLE
TTNN hard*-alike ops - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#7711]
For the following TTNN hard-* ops:
- ttnn.hardshrink
- ttnn.hardsigmoid
- ttnn.hardswish
- ttnn.hardtanh

The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). 

In practice, its seems that they do support BFLOAT8_B to some extent. 
The sweeps seem to be running with BFLOAT8_B, but immediately get stuck afterwards.
It needs to be clearly defined in documentation whether they support this data type or no.

**Comment by umadevimcw** [comment]
Will revisit this task and update it after migration task

**Comment by mcw-anasuya** [comment]
Merged to main. Hence closing this issue.
