### ISSUE TITLE
Deadlock when compiling programs in async mode

### ISSUE THREAD

**Issue by jnie-TT** [tenstorrent/tt-metal#7722]
**Issue**

Program compile is parallelized over kernels, and further parallelized when building compute kernels using taskflow. Since the number of threads forked is uncontrolled, there is a risk of deadlocking with excessive parallelization - dependencies between jobs cannot be resolved because the number of threads surpasses the limit. This deadlock scenario often occurs in async mode when there are multiple devices due to more parallelization introduced in the previous layer, but this can happen in single-threaded mode as well if we have enough kernels/compile jobs such that the multithreaded work exceeds the limit.

**Current Solution**

To avoid this, when running in async mode, we don't spawn new threads for compile. Instead, we execute the work/function on the current thread directly. 

**Proposal**

Move away from task flow, and introduce a custom thread pool API that book keeps a pool of threads, as well as the maximum thread limit. If a job to be executed was created by a thread in the pool, and the current number of busy threads hits the thread limit, then execute the work on that thread directly instead of assigning a new thread to do it. 

This helps fix the deadlock by limiting the amount of parallelism. Furthermore, since there are no dependencies between tasks, this eliminates unneeded overhead of taskflow dependency management. Lastly, this adds more configurability on our end, where we can experiment with cpu affinity, thread amount/tasks etc.

**Comment by tt-asaigal** [comment]
cc @TT-billteng we wanted to get your thoughts on implementing a custom thread pool class in Metal for more control and to bypass the deadlock @jnie-TT mentioned above.

This could be a first step towards improving the compile process.
