### ISSUE TITLE
Maxpool Config Support Needed for YoloV4

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#7746]
Maxpool variant in YoloV4 Neck Sub-Module fails ,

```
 "act_shape, kernel_size, padding, stride",
    [
        ((1, 512, 10, 10), (5, 5), (2, 2), (1, 1)),  # Pcc drop ~0.74
         ((1, 512, 10, 10), (9, 9), (4, 4), (1, 1)), #hang issue
        ((1, 512, 10, 10), (13, 13), (6, 6), (1, 1)),  # statical buffer issue
    ],
```
To run the unit test, Use the following steps:

- Checkout to [ankit/maxpool_unittest_error](https://github.com/tenstorrent/tt-metal/tree/ankit/maxpool_unittest_error) branch.
- Run pytest tests/ttnn/unit_tests/operations/test_max_pool2d.py::test_run_max_pool_yolov4

Note: The second configuration is commented in unit test as it hangs. To test it please uncomment the line.

**Comment by ankitmcw** [comment]
Op report: 
[ops_perf_results_yolov4_maxpool_2024_04_23_08_57_22.csv](https://github.com/tenstorrent/tt-metal/files/15074207/ops_perf_results_yolov4_maxpool_2024_04_23_08_57_22.csv)

**Comment by punithsekar** [comment]
Currently we face the following issues,

```
 "act_shape, kernel_size, padding, stride",
    [
        ((1, 512, 10, 10), (5, 5), (2, 2), (1, 1)),  # Pcc drop ~0.74
         ((1, 512, 10, 10), (9, 9), (4, 4), (1, 1)), #hang issue
        ((1, 512, 10, 10), (13, 13), (6, 6), (1, 1)),  # statical buffer issue
    ],
```
To run the unit test, Use the following steps:

- Checkout to ankit/maxpool_unittest_error branch.
- Run `pytest tests/ttnn/unit_tests/operations/test_max_pool2d.py::test_run_max_pool_yolov4`

Note: The second configuration is commented in unit test as it hangs. To test it please uncomment the line.

**Comment by mywoodstock** [comment]
this is done.
