### ISSUE TITLE
Kernels are not running properly on Idle Erisc cores (active or inactive)

### ISSUE THREAD

**Issue by kmabeeTT** [tenstorrent/tt-metal#7771]
Two ~related issues with `eth_mode=Idle` erisc cores.

1. When issuing kernel to "active" erisc cores  `device->get_active_ethernet_cores(true)` configured with `eth_mode=IDLE` (for testing purposes mainly) tests run to completion but simply don't execute the user kernel in FD2 (I see they are running okay in slow-dispatch mode with equivalent test hacked up). 

2. When issuing kernel to "inactive" erisc cores `device->get_inactive_ethernet_cores()`, test hangs for reasons unknown.

Will update this with simple test cmd for each of above case shortly, along with assertion (discussed in meeting) pointing to this issue to denote that the path is currently buggy/unsupported.

FYI @aliuTT / @ubcheema

**Comment by kmabeeTT** [comment]
Planning to add this assert into a branch inside `Program::populate_dispatch_data()` that already worked on ETH cores:

```
                 Always | FATAL    | Kernel increment_runtime_arg is on Idle Eth core, not yet supported. Issue #7771.
unknown file: Failure
C++ exception with description "TT_ASSERT @ tt_metal/impl/program/program.cpp:766: std::get<EthernetConfig>(kernel->config()).eth_mode != Eth::IDLE
```

My tests for each of above case will be merged soon too, will update this comment.

**Comment by kmabeeTT** [comment]
A couple follow ups to previous comment

1. Merged tests at c6fc5e0f2 last night to fd-2/main, disabled

2. I had to abandon that assert idea for now in `Program::populate_dispatch_data()` when I merged the tests last night since it fired in CI ([log](https://github.com/tenstorrent/tt-metal/actions/runs/8807139931/job/24180973360#step:8:2547)) for FD on idle-eth cores (`WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml`) when loading `cq_prefetch` kernel.  Allan told me now it should go somewhere in `commany_queue.cpp` so it's applied to FD2 path only and not SD.  Will have to revisit this.

3. The "active idle" test case 1 from previous comment was hanging for me before merge and I didn't know why at the time, so I kept it disabled. Just realized now that it will hang if run on it's own, but it will pass if it's run after sibling test (not mentioned before) that runs same workload with active eth core not configured to be idle, and having `TT_METAL_CLEAR_L1=0` defined. So, my conclusion is something in `eth_mode=IDLE` run is looking in the wrong place and using something (go signal?) from previous running test with `eth_mode!=IDLE`.   My guess is same bug is affective case-2 (inactive idle test, hangs) too and it could be that some code is not sensitive to `eth_mode=IDLE` but should be. 
 FYTI @aliuTT .
 
 In case it's helpful, passing active eth core test to run first is this (then case-1 above will not hang):

```
export TT_METAL_CLEAR_L1=0
./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter="CommandQueueSingleCardFixture.IncrementRuntimeArgsSanitySingleCoreDataMovementErisc" |& tee erisc_active_cores_passing.log
```

(Sorry if this is all confusing, lmk if any questions).

**Comment by tt-dma** [comment]
See also, some FD-on-idle-eth tests disabled due to this issue, tagged with `#7771`

**Comment by pgkeller** [comment]
I think this can be closed as several tests work fine at this point w/ dispatch to active/idle eth (FD to idle isn't supported yet, but the infra is there to do so).

@aliuTT One question I have is: why does the kernel API require specifying both a core and whether the core is active or idle since the core will imply active/idle? Dispatching to an active core w/ the flag "idle" should be an error (or just precluded in the API).

**Comment by tt-dma** [comment]
Is there an existing issue filed for FD-to-idle-eth? I checked the tests that are disabled due to this issue and they're all FD-specific.

**Comment by pgkeller** [comment]
No, no issue yet, unclear if it is useful (if idle eth is going to remain internal for FD)

**Comment by tt-dma** [comment]
Ok, will close this issue and update the comments mentioning it to instead mention that FD-on-idle-eth isn't supported
