### ISSUE TITLE
TTNN trigonometric hyperbolic ops - wrong types info in documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#7792]
For the following TTN trigonometric hyperbolic ops:
- sinh, cosh, asinh, acosh, atan, atanh 

The documentation is complete, but seems wrong/inconsistent. 
It does mention supported data types (BFLOAT16/BFLOAT8_B) and supported layouts (ROW_MAJOR/TILE). 
In practice, its seems that BFLOAT8_B is not supported.

**Comment by Aswinmcw** [comment]
Will revisit this task and update it after migration task

**Comment by mcw-anasuya** [comment]
Merged to main. Hence closing this issue.
