### ISSUE TITLE
We need a fast numerically equivalent softmax op

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#7813]
As explained https://tenstorrent.slack.com/archives/C065NUB85K3/p1713866838068869
the ttnn.softmax will conditionally use the moreh_softmax https://github.com/tenstorrent/tt-metal/blob/main/ttnn/ttnn/operations/others.py#L171 when the tensor requires padding.  This was done to maintain numerical accuracy.  The issue is that this operation does not properly cache the operations so there is a significant impact to performance.   We would like for a numerically accurate implementation to also exist that is highly performant.

**Comment by eyonland** [comment]
@yugaoTT , per our discussion, a version of softmax that uses the CBs to handle the mask sounds like the right approach here.

**Comment by eyonland** [comment]
@yieldthought, you might be interested in this.

**Comment by yugaoTT** [comment]
I have the support for interleaved version now, do we need it for sharded as well?

**Comment by yugaoTT** [comment]
merged, closing issue
