### ISSUE TITLE
Perf CI parity for FD-2

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#7816]
See CI perf pipeline, main is green: https://github.com/tenstorrent/tt-metal/actions/runs/8827091120

- GS: `models/demos/resnet/tests/test_perf_resnet.py::test_perf_bare_metal`, four different resnet tests, inference too slow
    - `ResNet50-20_ : Inference Time (sec): 0.0578, Expected Inference Time (sec): 0.04`
    - `resnet50_ 224x224_batchsize16 : Inference Time (sec): 0.0517, Expected Inference Time (sec): 0.015`
    - `resnet50_ 224x224_batchsize20 : Inference Time (sec): 0.0558, Expected Inference Time (sec): 0.0185`
    - `resnet50_batch_size16_ 224x224_batchsize16 : Inference Time (sec): 0.047, Expected Inference Time (sec): 0.015`
    -  `resnet50_batch_size20_ 224x224_batchsize20 : Inference Time (sec): 0.0511, Expected Inference Time (sec): 0.0185`
    
- N300: `models/demos/mamba/tests/test_mamba_perf.py::test_mamba_e2e_perf[32-10-11.0-0.75]`, compile time too slow
    - `Compile Time (sec):  13.37, Expected Compile Time (sec): 11.00`
  
- N300: `models/experimental/functional_stable_diffusion/tests/test_perf_stable_diffusion.py::test_stable_diffusion_perf[1-2-image_size0-3600-1.8]`, inference too slow
   - `Inference Time (sec):  1.8703, Expected Inference Time (sec):  1.8000`

**Comment by abhullar-tt** [comment]
weird that compile time changed, is `test_mamba_perf.py` compile time threshold flaky on main?

**Comment by abhullar-tt** [comment]
@pgkeller maybe increasing the cmddat_q size could help bridge some of these gaps

**Comment by tt-dma** [comment]
> weird that compile time changed, is `test_mamba_perf.py` compile time threshold flaky on main?

Happens consistently here (3/3 runs), haven't see that step fail when monitoring main for the last couple weeks

**Comment by abhullar-tt** [comment]
Same models are less than expected perf when running with increased fetch q (4K entries), cmddat queue (128K -> 256K) and prefetch size (64K -> 128K) 

https://github.com/tenstorrent/tt-metal/actions/runs/8838161835

from branch `abhullar/fetch-cmddat-sizes`

@davorchap @pgkeller
