### ISSUE TITLE
Explore sending slack notifications when a pipeline fails

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#7817]
https://github.com/slackapi/slack-github-action

**Comment by dimitri-tenstorrent** [comment]
@TT-billteng Which pipelines should we report to the channel? 

- All commits for main
- nightlies


Should we set up a new channel or re-use an existing one? 
tt-metal-pipline-status for new or just report to tt-metal-infra when pipelines break?
@tt-rkim I saw that you quarter back the failures to other teams sometimes. What are your preferences?

**Comment by TT-billteng** [comment]
> @TT-billteng Which pipelines should we report to the channel?
> 
> * All commits for main
> * nightlies
> 
> Should we set up a new channel or re-use an existing one? tt-metal-pipline-status for new or just report to tt-metal-infra when pipelines break? @tt-rkim I saw that you quarter back the failures to other teams sometimes. What are your preferences?

I'm thinking we report all pinned pipelines at least and few other important scheduled ones

**Comment by dimitri-tenstorrent** [comment]
Created a Slack app and requested permissions to create webhooks 
https://api.slack.com/apps/A072VTK2XK2

**Comment by dimitri-tenstorrent** [comment]
@olofj Do you mind allowing the app above to be have webhooks? Thank you!

**Comment by dimitri-tenstorrent** [comment]
@TT-billteng I have spoken to @tt-rkim and we decided to add the first set of notifications to the Nightly Model Performance Workflow.

I will create a notification that will tag Raymond on slack for now. The notification will look similar to 
<img width="1101" alt="Screenshot 2024-05-09 at 11 15 18 AM" src="https://github.com/tenstorrent/tt-metal/assets/119051828/ee69bd1f-d0cb-4efe-8c33-94729c99c559">

Additionally, and this will be covered in the follow up issue #8304 we would like to:
- Create a set of owners when the tests fail so we notify the correct person
- Parse the output and identify which tests fail
- Direct users to the exact error message (or even paste it in Slack with the error)

**Comment by dimitri-tenstorrent** [comment]
This is wrapped up. We need to extend this to more pipelines but that is likely a separate issue.

**Comment by tt-rkim** [comment]
Thank you @dimitri-tenstorrent
