### ISSUE TITLE
Tensor deallocate unusably slow (0.5ms per call)

### ISSUE THREAD

**Issue by yieldthought** [tenstorrent/tt-metal#7821]
Mistral attention (branch: mistral-fast-attention d3b355a6a6e19827517deb5fdb3a91c03f079ea6) has very slow tensor deallocate calls.

To reproduce on the above checkout:

`pytest models/demos/mistral7b/tests/test_mistral_attention.py`

```
...
Test | INFO     | Small tensor algorithm selected
22 deallocate calls took: 11.575 ms
2024-04-25 07:59:42.615 | INFO     | models.demos.mistral7b.tests.test_mistral_attention:test_mistral_attention_inference:105 - (False, 'Max ATOL Delta: 0.0017914026975631714, Max RTOL Delta: 683.31884765625')
...
```

This is produced by the following code in `models/demos/mistral7b/tt/mistral_attention_fast.py` which has been modified in this commit to put all the deallocates together at the end of the attention forward pass and time them at the host:

```
start = time()
xqkv_fused.deallocate()
k_heads_1KBD.deallocate()
k_heads_1KBD_rot.deallocate()
v_heads_1KBD.deallocate()
keys_BKPD.deallocate()
keys_1B_P_8D.deallocate()
keys_1B_8D_P_preshard.deallocate()
values_BKPD.deallocate()
q_heads_1QBD.deallocate()
q_heads_1BQD.deallocate()
q_heads_1B_Q_8D_preshard.deallocate()
keys_1B_8D_P.deallocate()
q_heads_1B_Q_8D.deallocate()
attn_1BQP.deallocate()
attn_1BQP_presoftmax.deallocate()
values_1B_P_8D.deallocate()
attn_output_1BQD.deallocate()
attn_output_1QBD.deallocate()
attn_output_1B_Q_8D.deallocate()
attn_output_1BQD.deallocate()
attn_output_1QBD.deallocate()
attn_output_11BH.deallocate()
duration = time() - start
print(f"22 deallocate calls took: {duration * 1e3:.3f} ms")
```

Interestingly if I just time deallocation of 1000 single tile tensors I get 1.6us per tensor which is much more expected; I don't know what is causing this particular combination or configuration of tensors to be so very slow but it is the overwhelming majority of e2e time for this module.

**Comment by arakhmati** [comment]
I can't run the test because `model_args.consolidated_weights_path` doesn't exist on my machine. I tried modifying it locally but couldn't get it to work. Can you please make it work in the case when `model_args.consolidated_weights_path` doesn't exist?

And I am trying to reproduce this in a smaller test and as you mentioned it runs fast. I will try running some other models and see if this issue shows up elsewhere

**Comment by yieldthought** [comment]
@arakhmati The paths are correct for CI bt not for dev clusters on aus and yyz - these are found in /proj_sw/ and you can update the default path with this patch:
[proj_sw_weights.patch](https://github.com/tenstorrent/tt-metal/files/15200070/proj_sw_weights.patch)

**Comment by yieldthought** [comment]
That's over a minute (not a second!) in deallocate calls:
<img width="1154" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/946653/50ba4f90-6c40-4f6b-a7f2-ed12a213301f">

**Comment by arakhmati** [comment]
Looking at this, it's not clear to me what causes the issue.
But my top guesses are:
- because we call `deallocate` so many times 
- because `find_block` inside of `FreeList::deallocate` is slow in this particular scenario. Upon inspecting it, it looks like `find_block` uses an `O(N)` algorithm to find the block by traversing a linked list.

@abhullar-tt is it possible that this slow down is caused by `find_block`? Is there an easy way we can isolate the issue? Maybe a unit test that we could use to allocate at random addresses and then deallocate them?

@mo-tenstorrent can you help us profile it further to get the bottom of this slow down?

**Comment by davorchap** [comment]
> Looking at this, it's not clear to me what causes the issue.
> 
> But my top guesses are:
> 
> - because we call `deallocate` so many times 
> 
> - because `find_block` inside of `FreeList::deallocate` is slow in this particular scenario. Upon inspecting it, it looks like `find_block` uses an `O(N)` algorithm to find the block by traversing a linked list.
> 
> 
> 
> @abhullar-tt is it possible that this slow down is caused by `find_block`? Is there an easy way we can isolate the issue? Maybe a unit test that we could use to allocate at random addresses and then deallocate them?
> 
> 
> 
> @mo-tenstorrent can you help us profile it further to get the bottom of this slow down?
> 
> 

@yieldthought 
Are these tensors are in DRAM?

This many tensors wouldn't fit into L1 , so I presume DRAM.

My guess is that DRAM gets fragmented with lots of free blocks and the N in O(N) grew a lot.

I think doing some profiling within the find_block to see how many free blocks and what N is.

If fragmentation is indeed the problem, would be good to know why it happened?

@arakhmati can we visualize DRAM in the same way as L1? it would be great to have it, the issue may be obvious from the diagram.

**Comment by arakhmati** [comment]
@davorchap yes, we definitely can. Although, I need to update the visualizer to work with multi-device

**Comment by abhullar-tt** [comment]
> Looking at this, it's not clear to me what causes the issue. But my top guesses are:
> 
> * because we call `deallocate` so many times
> * because `find_block` inside of `FreeList::deallocate` is slow in this particular scenario. Upon inspecting it, it looks like `find_block` uses an `O(N)` algorithm to find the block by traversing a linked list.
> 
> @abhullar-tt is it possible that this slow down is caused by `find_block`? Is there an easy way we can isolate the issue? Maybe a unit test that we could use to allocate at random addresses and then deallocate them?

We don’t have a randomized stress test for this but it wouldn’t be difficult to create one. Both allocate and deallocate have O(n) components. @davorchap we were considering updating mem allocator algo to [TLSF](http://www.gii.upv.es/tlsf/). if we don’t go down this route the allocator can keep some extra metadata that would replace find_block

> 
> @mo-tenstorrent can you help us profile it further to get the bottom of this slow down?

**Comment by yieldthought** [comment]
Using a `shared_ptr` for FreeList isn't great:
- Iterating through it (for those lovely long linear-time searches) copies the object N times, causing 2N _atomic_ reference count updates.
- Atomic reads and writes are slow.
- I haven't reasoned through a counterexample but I doubt the whole list is thread-safe even with shared_ptr because there's still nothing to stop another thread modifying the list while you're traversing it and it seems pretty likely you could get into a bad place like this.

The `yieldthought/faster-deallocate` branch replaces `shared_ptr` with boost's `local_shared_ptr` which keeps the reference counting semantics to avoid carefully rewriting to manually manage memory, but removes the atomics. This makes the list very definitely thread-unsafe instead of only probably thread-unsafe. So I also protected the public methods with a mutex, which is probably what we want if we want this to be thread-safe in the first place.

If the intention was never for this to be thread-safe we should remove the mutex and save a bit of performance. It'd be really great if the docstrings for Metalium classes noted which of them were/were not supposed to be thread-safe.
