### ISSUE TITLE
Falcon 7b prefill CI coverage

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent/tt-metal#7823]
Current CI coverage for Falcon 7b prefill:
- `test_perf_falcon.py` is ran as a part of [model perf regression pipeline](https://github.com/tenstorrent/tt-metal/blob/main/tests/scripts/run_performance.sh#L39); PCC is checked here but the threshold is 0.89 so it's not very useful
- some unit tests as a part of [post commit fd/sd tests ](https://github.com/tenstorrent/tt-metal/blob/main/tests/scripts/run_python_model_tests.sh#L53) - very low coverage, some matmuls are not even used in the model

`test_perf_falcon.py` seems like a good test to discover hangs and perf regression, but we need to add one for 2k seq len as well, and proper e2e PCC tests for both 128 and 2k seq len.

**Comment by s-jovic** [comment]
Added e2e test for 128 seq len and proper PCC check in https://github.com/tenstorrent/tt-metal/pull/8218.

To add (after optimized prefill version is enabled):

- [ ] 2k seq len e2e PCC test
- [ ] 2k seq len perf test

**Comment by s-jovic** [comment]
Added e2e and perf tests here: https://github.com/tenstorrent/tt-metal/commit/4fc1bb496fad50b1ee8c4bbdb4ab0be631d19dc7.

**Comment by uaydonat** [comment]
can we close this?

**Comment by pavlejosipovic** [comment]
I'll leave this for @s-jovic to check when she is back from vacation, I don't think we have proper 2k e2e tests yet.

**Comment by s-jovic** [comment]
T3000 and single-chip model perf e2e tests also check PCC so no need to add separate e2e test actually. Closing the issue.
