### ISSUE TITLE
[Metal Trace] Support for dynamic memory alloc/dealloc of intermediate tensors

### ISSUE THREAD

**Issue by tooniz** [tenstorrent/tt-metal#7832]
An intermediate tensor is defined as Tensor produced AND consumed by hidden layers. Other tensors are considered IO type, since they're either input to the graph or output of the graph

Metal Trace is able to model the graph but it requires IO buffers to remain static.

Filing this issue to identify tt_eager Tensors as 2 types -- input/output vs. intermediate so only IO to the graph have lifetime extended and intermediate types are released during the trace exeuction

**Comment by tooniz** [comment]
WIP tzhou/trace-greedy-buffers, only assign globally allocated buffer for non-intermediates

Could use some review @arakhmati @kmabeeTT

**Comment by kmabeeTT** [comment]
I tried RN50 with Trace last week, but it fails badly during capture with 2 different errors, opened #8065 and #8066 , suspected to be related to this and requiring this or similar fix.  Did try the fix from this bug, and it didn't solve either error though, so needs exploring.

**Comment by tt-aho** [comment]
This is resolved on branch to be merged
