### ISSUE TITLE
[Metal Trace] Eager Tensor support for reusing existing storage for new activations

### ISSUE THREAD

**Issue by tooniz** [tenstorrent/tt-metal#7833]
Common usage pattern today for every inference request is to recreate a new Tensor and send it to device

Pattern 1
```
ttact = ttl.tensor.Tensor(act, ttl.tensor.DataType.BFLOAT16)
ttact = ttact.to(device)
```

Pattern 2
```
in0 = torch.randn(in0_shape).bfloat16().float()
in0_t = torch2tt_tensor(
            in0, device, tt_memory_config=interleaved_mem_config_DRAM, tt_dtype=ttl.tensor.DataType.BFLOAT8_B
        )
# where torch2tt_tensor performs Pattern 1
```

However this reallocates memory, which could put each iteration's input Tensor anywhere in DRAM. That breaks tracing since we'd want static addresses.

We need a way to allocate a Tensor once but keep reusing its storage for each successive inference request itereation's activation data

**Comment by tt-aho** [comment]
This is done on branch to be merged
