### ISSUE TITLE
Add support for non-4D tensor in moreh_linear and moreh_linear_backawrd OP

### ISSUE THREAD

**Issue by dongjin-na** [tenstorrent/tt-metal#7838]
Is your feature request related to a problem? Please describe.
Currently, these OPs only support 4D shape tensors.
We need to remove this constraint to handle non-4D tensors.

**Comment by jliangTT** [comment]
is there any workaround for this @dongjin-na ?

**Comment by dongjin-na** [comment]
I'm working on it.
There are already other ops that have completed that non-4D tensor support.
- https://github.com/tenstorrent/tt-metal/pull/7745
- https://github.com/tenstorrent/tt-metal/pull/7742
