### ISSUE TITLE
Fix an issue that prevents tensors from getting dealocated

### ISSUE THREAD

**Issue by arakhmati** [tenstorrent/tt-metal#7869]
Re-enable `reshape_outputs_of_split_query_key_value_and_split_heads` in `ttnn/cpp/ttnn/operations/transformer.hpp` for the case of nlp_create_qkv_heads_falcon7b  once the issue is fixed

**Comment by tt-asaigal** [comment]
Worked with @arakhmati to resolve the OOM issue seen due to certain tensors not getting deallocated in async mode. Reshapes are now enabled for the `nlp_create_qkv_heads_falcon7b ` operation on main.

**Comment by jliangTT** [comment]
closing per review with @arakhmati
