### ISSUE TITLE
tt_cluster::write_reg calls wait for non_mmio_flush on mmio chip

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#7883]
Found looking at FD2 perf, removing that call has a measurable (~5%) gain w/ the current rate that we write.

Also, these paths shouldn't be doing a map lookup every time to see if the flush is needed.  That info could be cached in the device as a flag and passed through the API

**Comment by tt-aho** [comment]
We've switched back to using static tlbs instead of write_reg. Can we close this issue? Or file the removal of flush on umd?

**Comment by pgkeller** [comment]
closing.  this issue still persists, but should be addressed under a broader cleanup effort of umd/cluster/etc.
