### ISSUE TITLE
DevicePool: for managing active devices across stack

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent/tt-metal#7887]
Tracking TODOs and possible issues.

https://github.com/tenstorrent/tt-metal/pull/7839

Notes from meeting with Joseph and Almeet:
- Possibly remove `num_hw_cqs` and `l1_bank_remap` from device constructor
- Merge DevicePool and DeviceMesh
- Add APIs to get certain topologies (Mesh, Linear, Ring etc.)

**Comment by pgkeller** [comment]
moving this to P1 as we keep bumping into bugs that this would resolve

**Comment by aliuTT** [comment]
Picking up this work now, I'll start with the following items:
- rename DeviceMesh to DevicePool, and move it to tt_metal namespace.
- make it static and use it in the multi device command queue initialization
- add an API to return a ring for TTNN multi device APIs

**Comment by aliuTT** [comment]
fyi @abhullar-tt @cfjchu

**Comment by cfjchu** [comment]
> * make it static and use it in the multi device command queue initialization

what do you mean by this bullet?

**Comment by aliuTT** [comment]
We need a global DevicePool for command queue initialization. So I'm thinking of making DevicePool something like this:
```
const DevicePool& DevicePool::instance(
    std::vector<chip_id_t> device_ids, const uint8_t num_hw_cqs, const std::vector<uint32_t>& l1_bank_remap) {
    static DevicePool device_pool(device_ids, num_hw_cqs, l1_bank_remap);
    device_pool.l1_bank_remap = l1_bank_remap;
    return device_pool;
}

DevicePool::DevicePool(
    std::vector<chip_id_t> device_ids, const uint8_t num_hw_cqs, const std::vector<uint32_t>& l1_bank_remap) {
    ZoneScoped;
    for (const auto& device_id : device_ids) {
        const auto& mmio_device_id = tt::Cluster::instance().get_associated_mmio_device(device_id);
        for (const auto& mmio_controlled_device_id :
             tt::Cluster::instance().get_devices_controlled_by_mmio_device(mmio_device_id)) {
            if (this->active_devices.find(mmio_controlled_device_id) == this->active_devices.end()) {
                auto dev = new Device(mmio_controlled_device_id, num_hw_cqs, l1_bank_remap);
                this->active_devices.insert({mmio_controlled_device_id, dev});

                detail::InitDeviceProfiler(dev);
            }
        }
    }
    tt::Cluster::instance().set_internal_routing_info_for_ethernet_cores(true);
}

Device* DevicePool::get_active_device(chip_id_t device_id) const {
    TT_ASSERT(
        this->active_devices.find(device_id) != this->active_devices.end(),
        "DevicePool does not contain active device {}",
        device_id);
    auto dev = this->active_devices.at(device_id);
    if (not dev->is_initialized()) {
        dev->initialize(this->l1_bank_remap);
    }
    return dev;
}
```
So that TTNN and runtime backend can call `tt::DevicePool::instance({0}).get_active_device(0)` to get device 0. I'll tweak the APIs to make it more usable, but this is the gist of it

**Comment by aliuTT** [comment]
Giving an update, still working on changes. Majority of feature for merging global device managers is done. Trying to delete some redundant code and smoothing out CI: https://github.com/tenstorrent/tt-metal/actions/runs/9195121154/job/25290455521

**Comment by aliuTT** [comment]
Open issues:
- #8936 
-
