### ISSUE TITLE
Multi-CQ + doubling cmddatQ and max prefetch size for tensix dispatch bug in writing large buffer

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#7892]
Branch `abhullar/fetch-cmddat-sizes` increases number of fetchQ entries and doubles cmddatQ and max prefetch size for dispatch out of tensix. 

It seems like increasing max prefetch size from 64K to 128K causes failure in 1GB EWB/ERB multi-CQ test:
```
[ RUN      ] MultiCommandQueueSingleDeviceFixture.TestIssueMultipleReadWriteCommandsForOneBuffer
                  Metal | INFO     | Initializing device 0. Program cache is NOT enabled
                  Metal | INFO     | AI CLK for device 0 is:   1202 MHz
                 Always | FATAL    | Event Order Issue: expected to read back completion signal for event 1 but got 234882048!
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_ASSERT @ tt_metal/impl/dispatch/command_queue.cpp:1502: event_completed == read_descriptor.event_id
```

with watcher enabled we hit assert of seeing invalid command in the prefetcher
```
              LLRuntime | INFO     | Watcher checking device 0
                 Always | WARNING  | Watcher stopped the device due to tripped assert, see watcher log for more details
                 Always | WARNING  | Device 0 worker core(x= 1,y= 9) phys(x= 2,y=11): ncrisc tripped an assert on line 874. Current kernel: tt_metal/impl/dispatch/kernels/cq_prefetch.cpp. Note that file name reporting is not yet implemented, and the reported line number for the assert may be from a different file.
                 Always | INFO     | Last waypoint:  NTW,!CMD,   W,   W,   W 
                 Always | INFO     | While running kernels:
                 Always | INFO     |  brisc : blank
                 Always | INFO     |  ncrisc: tt_metal/impl/dispatch/kernels/cq_prefetch.cpp
                 Always | INFO     |  triscs: blank
                 Always | FATAL    | Watcher detected tripped assert and stopped device.
```

cmd to repro: `TT_METAL_WATCHER=120 TT_METAL_NUM_HW_CQS=2 ./build/test/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue --gtest_filter=MultiCommandQueueSingleDeviceFixture.TestIssueMultipleReadWriteCommandsForOneBuffe`

**Comment by abhullar-tt** [comment]
This branch had three changes:

1. increase num fetchQ entries to 4K (from 128)
2. double cmddatQ size (128K to 256K)
3. increase max fetch size (64K to 128K)

combination of these three was causing the issue above. reverting either 1 or 3 is a workaround for the issue. 

reverting 3 yielded lower perf numbers on the model perf pipeline than reverting 1 so I went with workaround of merging 2 and 3 to fd-2/main. 

changes 2 and 3 yield better perf than what was first reported in #7816. 

Model perf pipeline for reduced num fetchQ entries: https://github.com/tenstorrent/tt-metal/actions/runs/8862959986

Model perf pipeline for reducing fetch size: https://github.com/tenstorrent/tt-metal/actions/runs/8862972357

**Comment by pgkeller** [comment]
Closing as this is understood.  We need to be careful going forward of the relative sizes of these and/or need to put in explicit wrap handling
