### ISSUE TITLE
Add N150 and T3000 CI Pipelines for full model demos

### ISSUE THREAD

**Issue by uaydonat** [tenstorrent/tt-metal#7896]
We currently do not run the full model demos in CI, which is a gap in our coverage.

You can see the list of the demos that are functional on our github page.

https://github.com/tenstorrent/tt-metal?tab=readme-ov-file#wormhole-wh-models

For a simple batch=32 input prompt, these demos would probably run for 10-15 minutes. So, maybe we want to create a once-a-day pipeline.

We need verify both accuracy and performance for these. The demos already print tokens/second/user metric. We should just grep that from output and verify. We do not want to add any CI related logging/testing since the demos are meant to be external and clean. We will need to add to demos some kinda check to verify correctness (perplexity per token?).

**Comment by uaydonat** [comment]
fyi @tapspatel

**Comment by uaydonat** [comment]
@tapspatel I know you are busy but it would be good to take a look at this when you have the chance. If it is just a matter of adding a once-a-day pipeline config, we can fill the tests in.

**Comment by uaydonat** [comment]
There does not seem to be a big difference between multi-device-build-and-unit-tests-frequent.yaml and multi-device-build-and-unit-tests.yaml

One runs every 3 hours, the other every 4 hours. 
Maybe we move all tests to the latter, and the former runs once a day (i.e. nightly as the name implies) so we can add demos to it?

**Comment by tapspatel** [comment]
taking a look now

**Comment by tapspatel** [comment]
https://github.com/tenstorrent/tt-metal/pull/8262

I added the new end of end demos pipeline. I also changed the frequency of the unit tests and frequent tests

unit: every 3 hours
frequent: every 8 hours
performance: every day at 6am
end-end-demos: every day at 12am

**Comment by tapspatel** [comment]
Merged into main: 6984d928162553e6e6b0717e1df4945a603f0ab6
Closing issue
