### ISSUE TITLE
CommonFixture.MatmulMultiCoreMultiDRAM hangs on device 1 on N300

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#7910]
- Remove the `break` in `tests/tt_metal/tt_metal/unit_tests_common/compute/matmul/test_matmul_multi_core_X_dram.cpp:505`
- `./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=CommonFixture.MatmulMultiCoreMultiDRAM`
- Result is a hang: https://github.com/tenstorrent/tt-metal/actions/runs/8854442333/job/24317672563

**Comment by tt-dma** [comment]
`CommonFixture.MatmulMultiTile` also appears to hang in a similar manner

**Comment by aliuTT** [comment]
merged, and test re-enabled
