### ISSUE TITLE
`CommandQueueFixture.TestEventsEventsQueryBasic` failing on e150 vm

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent/tt-metal#7911]
First noticed on stress test pipeline: https://github.com/tenstorrent/tt-metal/actions/runs/8810852687

Can be reproduced on main by looping that one test ~100-200 times. Bisect shows that the test has been failing since being added at this commit: 06828e32f [here](https://github.com/tenstorrent/tt-metal/commit/06828e32f0583392a99de71fb56128ee5af3ceff#diff-097539bc727a291abd7744c3f00a1e4942f6b1208add319569d8ff795482d2fcR209)

Failure signature.:
![image](https://github.com/tenstorrent/tt-metal/assets/157417475/f87a008a-ca71-4eba-bfac-c447e178c34a)

CC: @TT-billteng @kmabeeTT

**Comment by kmabeeTT** [comment]
Thanks for heads up, very surprised this simple test could actually fail,
will take a look !

**Comment by TT-billteng** [comment]
Can we disable until we get this resolved?

**Comment by kmabeeTT** [comment]
Sorry for delay, just took a look and reproduced, then spotted test issue which explains this. Will fix very shortly in main and resolve.

**Comment by kmabeeTT** [comment]
Fixed at b15f79b3c in main, marking closed.  Dumb oversight in haste to whip together this test. Wasn't properly blocking on host before calling EventQuery() function so definitely would give ND results, sorry about that!. Needed to call Finish() or EventSynchronize(), so changed test to use both methods, on earlier events for more coverage.
