### ISSUE TITLE
CommandQueueSingleCardFixture.Sending131072Pages hangs on T3000

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#7922]
See: https://github.com/tenstorrent/tt-metal/actions/runs/8854458333, test hangs on T3000. Need to re-enable test tagged with #7922

**Comment by tt-dma** [comment]
`CommandQueueSingleCardFixture.TestNon32BAlignedPageSizeForDram`, `CommandQueueSingleCardFixture.TestWrapHostHugepageOnEnqueueReadBuffer`, `CommandQueueSingleCardFixture.TestIssueMultipleReadWriteCommandsForOneBuffer`, and potentially more tests appear to be hanging in a similar manner

**Comment by tt-dma** [comment]
After latest changes the first test at least is still failing: https://github.com/tenstorrent/tt-metal/actions/runs/8917922933/job/24491729958

**Comment by ubcheema** [comment]
All tests pass on fd-2/main @ 78a893fc42424e17f0c6ec7954f78904953866b2

**Comment by ubcheema** [comment]
please confirm and close.

**Comment by aliuTT** [comment]
Try again on main, it should be passing now.
