### ISSUE TITLE
models/demos/ttnn_falcon7b/tests/multi_chip/test_falcon_causallm.py::test_falcon_causal_lm[wormhole_b0-True-True-20-2-BFLOAT16-DRAM-falcon_7b-layers_1-prefill_seq128_batch32] Segfault/double free on T3000

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#7925]
See https://github.com/tenstorrent/tt-metal/actions/runs/8870324980/job/24353544159#step:7:4723 

Same test also segfaults: models/demos/ttnn_falcon7b/tests/multi_chip/test_falcon_causallm.py::test_falcon_causal_lm[wormhole_b0-True-True-20-2-BFLOAT16-DRAM-falcon_7b-layers_1-prefill_seq128_batch32]

**Comment by pgkeller** [comment]
maybe related to a tracing issuing in main

**Comment by tt-dma** [comment]
Appears fixed: https://github.com/tenstorrent/tt-metal/actions/runs/8930806280/job/24531646616

Will wait to see the full run before closing

**Comment by tt-dma** [comment]
Fixed per Umair/Allan/Paul's recent changes: https://github.com/tenstorrent/tt-metal/actions/runs/8930806280
