### ISSUE TITLE
[Bug Report] Invalid power_tile output

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#7928]
**Describe the bug**

The output of the code, which computes `power(1, 1)`, varies depending on whether the code is placed inside or outside a for loop that runs only once.

I discovered that the behavior of power_tile is abnormal during debugging.
So I have modified `moreh_norm` op and the kernel to take input values, compute power, and output the result.

kernel : https://github.com/tenstorrent/tt-metal/blob/hyungsuk/debug_power/tt_eager/tt_dnn/op_library/moreh_norm/moreh_norm_h/kernels/moreh_norm_h_kernel.cpp

```C++
    DPRINT_PACK( DPRINT << "EXECUTE POWER \n";)

    // The following code produces the correct output.
    ACQ();
    cb_wait_front(cb_x, onetile);
    cb_reserve_back(cb_y, onetile);

    // copy
    copy_tile_init();
    copy_tile(cb_x, 0, dst0);

    // power
    power_tile_init();
    power_tile(dst0, p);

    pack_tile(dst0, cb_y);

    cb_push_back(cb_y, onetile);

    cb_pop_front(cb_x, onetile);
    REL();


    DPRINT_PACK(DPRINT << "num_cols_per_core " << num_cols_per_core << "\n"; )
    DPRINT_PACK(DPRINT << "Ht " << Ht << "\n"; )
    // This loop only runs once.
    for (uint32_t col_idx = 0; col_idx < num_cols_per_core; ++col_idx) {
        // This loop only runs once.
        for (uint32_t row_idx = 0; row_idx < Ht; ++row_idx) {
            DPRINT_PACK( DPRINT << "EXECUTE POWER \n";)
            // The following code is identical to the above but produces incorrect output.
            // ACQ();
            // cb_wait_front(cb_x, onetile);
            // cb_reserve_back(cb_y, onetile);

            // // copy
            // copy_tile_init();
            // copy_tile(cb_x, 0, dst0);

            // // power
            // power_tile_init();
            // power_tile(dst0, p);

            // pack_tile(dst0, cb_y);

            // cb_push_back(cb_y, onetile);

            // cb_pop_front(cb_x, onetile);
            // REL();
        }
    }
```

In the code above, there are two identical pieces of code for computing power.
If that code is executed outside the for loop, it produces the correct output.
```Python
cpu_x  tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
cpu_tensor tensor([[[[1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]]]], dtype=torch.bfloat16)
```
However, if this code is executed within a for loop that runs only once, it produces incorrect output.
```Python
cpu_x  tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
cpu_tensor tensor([[[[1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 1., 0., 1., 0., 1., 0.], # <---- Values generated for unknown reasons.
          [0., 1., 0., 1., 0., 1., 0.],
          [0., 1., 0., 1., 0., 1., 0.]]]], dtype=torch.bfloat16)
```

The output reveals that there are values generated for unknown reasons.
These values are subsequently added in the operation where `reduce_h` is executed, resulting in incorrect output.
ex) norm

**To Reproduce**
1. Go to debug branch https://github.com/tenstorrent/tt-metal/tree/hyungsuk/debug_power
2. Run `pytest ./tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_norm.py `
3. See DPRINT output
```Python
cpu_x  tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

cpu_tensor tensor([[[[1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 1., 0., 1., 0., 1., 0.],  # <---- Values generated for unknown reasons.
          [0., 1., 0., 1., 0., 1., 0.],           
          [0., 1., 0., 1., 0., 1., 0.]]]], dtype=torch.bfloat16)
```

**Expected behavior**

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit 5f32bf75a74679c46b69f5a9ef8c87057155e731)
- Arch: wormhole_b0

**Additional context**

**Comment by amahmudTT** [comment]
I am looking into the issue and will be looking at the difference in generated assembly between the two cases and if the padded data passed to the device from host is cleared up properly. Does this issue needs to be reprioritized, since there is a workaround ?

**Comment by amahmudTT** [comment]
The branch is very outdated compare to main (folder structure/ function changes) would it be possible to reproduce @hschoi4448  the issue on an updated branch. Thanks.

**Comment by amahmudTT** [comment]
> The branch is very outdated compare to main (folder structure/ function changes) and I am finding it hard to build the branch, would it be possible for you , @hschoi4448, to reproduce the issue on an updated branch. Thanks.

@hschoi4448 never mind, I was able to rebase with main and reproduce the issue.

**Comment by amahmudTT** [comment]
The data that is going into the hardware in the math kernel is correct. But still the output is wrong. 

Input tile printed within kernel
<img width="416" alt="Screenshot 2024-08-15 at 8 03 45 PM" src="https://github.com/user-attachments/assets/12c04fce-e007-45ac-87e8-46268b2c49bd">

Output tile in python
<img width="937" alt="Screenshot 2024-08-15 at 8 09 34 PM" src="https://github.com/user-attachments/assets/b484eced-8d22-40cf-ac8f-b439f37acf84">

**Comment by amahmudTT** [comment]
Assembly files

Loop based version giving incorrect result 
[power_loop_bug_asm.txt](https://github.com/user-attachments/files/16638808/power_loop_bug_asm.txt)

NO-loop version giving correct result
[power_no_loop_correct.txt](https://github.com/user-attachments/files/16638815/power_no_loop_correct.txt)

**Comment by amahmudTT** [comment]
The bug is caused by the compiler not issuing `SFPNOP` instructions after `SFPMUL` in more than half of the cases when it inlines and unrolls the loop in the power_tile function in the loop that runs only once. The assembly generated for power_tile function itself is correct and has `SFPNOPs` issued whenever they are needed. It is when it is inlined we see this issue. If we remove the loop, the `SFPNOP` instruction is always issued. Forcing an `SFPNOP` by `TTI_SFPNOP` in the function calculate_power_iterative in 
`tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_power_iterative.h` also makes the test pass. 

Assembly files:

Without loop  (gives correct result and has `SFPNOP` after every `SFPMUL`)
[power_no_loop_correct.txt](https://github.com/user-attachments/files/16641527/power_no_loop_correct.txt)

With loop (does not have `SFPNOP` after 5 instances of `SFPMUL`)
[power_loop_bug_asm.txt](https://github.com/user-attachments/files/16641535/power_loop_bug_asm.txt)

As can be seen in a part of the inlined version of power_tile :

```
    7834:	00ee0863          	beq	t3, a4, 7844 <kernel_launch()+0x38c>
    7838:	18006402          	sfpmul	L0, L0, L1, L9, 0
    783c:	00170713          	addi	a4, a4, 1
    7840:	ff5ff06f          	j	7834 <kernel_launch()+0x37c>
    7844:	c8030001          	sfpstore	0, L0, 0, 3
```

This is the inner loop inside power_tile function missing a required `SFPNOP` which could be temporarily fixed by forcing a `NOP` using `TTI_SFPNOP`:

```
template <bool APPROXIMATION_MODE,int ITERATIONS = 8>
inline void calculate_power_iterative(const uint exponent)
{
    #pragma GCC unroll 8
    for (int d = 0; d < 8; d++)
    {
        vFloat in = dst_reg[0];
        vFloat result = 1.0f;
        for (uint i = 0; i < exponent; i++) {
            result *= in;
            // TTI_SFPNOP;
        }
            dst_reg[0]=result;
        dst_reg++;
    }
}

```

**Comment by amahmudTT** [comment]
Issue created for SFPI compiler : https://github.com/tenstorrent/sfpi/issues/13

**Comment by amahmudTT** [comment]
PR to fix this issue in compiler merged https://github.com/tenstorrent/sfpi-gcc/pull/1#issuecomment-2317822374

**Comment by amahmudTT** [comment]
@hschoi4448 could you sync your problem to main and retry it ? Thanks.

**Comment by hschoi4448** [comment]
I have confirmed that the correct value is being output in `power_tile`.
