### ISSUE TITLE
Deterministic hang of SD device-perf test on WHB0

### ISSUE THREAD

**Issue by mtatsumiTT** [tenstorrent/tt-metal#7934]
The SD device-perf test has been hanging since 2 days ago. After bisecting, it seems the deterministic hang started from [this commit](https://github.com/tenstorrent/tt-metal/commit/4c98e1973f791480177228e12426cd89e536cbad)

passing log (`ace1e53`): https://github.com/tenstorrent/tt-metal/actions/runs/8880638315
hanging log (`4c98e19`): https://github.com/tenstorrent/tt-metal/actions/runs/8864319766 

To repro the hang locally, please try:
```bash
pytest models/experimental/functional_stable_diffusion/tests -m models_device_performance_bare_metal
```

fyi @AleksKnezevic

**Comment by AleksKnezevic** [comment]
@tarafdarTT if you're testing locally, SD is broken on main as of `f0700725d822c9da2662b43421a0edff892e7c04`. You can cherry-pick `369b17eb24dee27283559ef7d91016030727a87e` to resolve. I'll merge it in as soon as I have PR review.

**Comment by tarafdarTT** [comment]
Breaking commits have been reverted on main
