### ISSUE TITLE
models.demos.falcon7b.tests.test_perf_falcon:run_test_FalconCausalLM_end_to_end hangs on N300

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#7947]
See https://github.com/tenstorrent/tt-metal/actions/runs/8881164154/job/24383082348

**Comment by pgkeller** [comment]
@tt-dma could not reproduce locally, but fails in CI twice

**Comment by tt-dma** [comment]
Running again after Umair's recent fixes: https://github.com/tenstorrent/tt-metal/actions/runs/8917934561

**Comment by tt-dma** [comment]
Running again after latest fixes: https://github.com/tenstorrent/tt-metal/actions/runs/8930813188

**Comment by tt-dma** [comment]
Looks fixed on fd-2/main: https://github.com/tenstorrent/tt-metal/actions/runs/8930813188/job/24531821481
