### ISSUE TITLE
TTNN log/exp-alike ops - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#7955]
For the following TTNN logexp-alike ops:
- logaddexp, logaddexp2, ldexp

The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, its seems that they fully support BFLOAT16. 
When it comes to BFLOAT8_B, they fail with LOW PCC for some cases, but still they are executed and even pass. 
ROW_MAJOR layout seems not supported by any of these ops, while TILE is supported.

**Comment by VirdhatchaniKN** [comment]
Will revisit after Migration task - https://github.com/tenstorrent/tt-metal/issues/7711#issuecomment-2245229879

**Comment by mouliraj-mcw** [comment]
closing as completed
