### ISSUE TITLE
TTNN ternary addc-alike ops incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#7956]
For the following TTNN ternary-addc* alike ops:
- addcmul, addcdiv

The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, its seems that they support BFLOAT16 only and TILE layout.

**Comment by KalaivaniMCW** [comment]
will be revisited after TTNN migration
