### ISSUE TITLE
TTNN tensor creation ops - zeros, zeros_like, empty - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#7957]
For the following TTNN tensor creation ops:
- zeros, empty
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). 

For op:
- zeros_like 
BFLOAT8_B is listed but seems not supported in practice.

**Comment by jliangTT** [comment]
@eyonland , need your help to triage. Who own the tensor creation methods?

**Comment by eyonland** [comment]
@npetrovic-tenstorrent , do you create a pytest already for this?

**Comment by eyonland** [comment]
@jliangTT , ttnn team can take the work after the migration.   Can we downgrade to a P2 ?

**Comment by KalaivaniMCW** [comment]
Merged #14104
