### ISSUE TITLE
Falcon40b prefill hang on CI

### ISSUE THREAD

**Issue by johanna-rock-tt** [tenstorrent/tt-metal#7960]
**Describe the bug**
Some falcon 40b prefill tests hang non-deterministically on CI.

What we know so far:
- April 26th the issue was already in main
- Many of the tests pass also after April 26th, so it's not clear when the issue was introduced
- Hang rate so far observed: ~1/10 tests CI runs, give that we have 4 prefill falcon40b tests that would make it hang ~ 1/40 tests

**To Reproduce**
WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/demos/falcon40b/tests/ci/test_falcon_end_to_end_t3000_prefill.py::test_FalconCausalLM_prefill_end_to_end_t3000_ci[BFLOAT8_B-DRAM-falcon_40b-layers_1-prefill_seq2048]

**Comment by johanna-rock-tt** [comment]
One of the ci runs that fail:
https://github.com/tenstorrent/tt-metal/actions/runs/8874039071/job/24360804934#logs

**Comment by johanna-rock-tt** [comment]
Seems to be fixed after running with the new FW at 1GHz. Closing for now until we observe this behaviour again.

**Comment by uaydonat** [comment]
@johanna-rock-tt is this hanging with FD2 on main?

**Comment by johanna-rock-tt** [comment]
This was passing 2/2 but I need to confirm by running more loops.

**Comment by johanna-rock-tt** [comment]
Ran this again in the CI pipeline, all 1 layer tests pass now: https://github.com/tenstorrent/tt-metal/actions/runs/8986502626/job/24682765136

So I'd say that one is fixed.
