### ISSUE TITLE
TTNN logical binary ops - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#7961]
For the following TTNN tensor binary logical ops:
- and, or, xor

The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE).

However, it seems that these ops actually support both BFLOAT16 and BFLOAT8_B in practice with TILE layout in both cases.

**Comment by KalaivaniMCW** [comment]
Will revisit this task and update it after migration task

**Comment by mcw-anasuya** [comment]
Merged to main, hence closing this issue
