### ISSUE TITLE
ND behavior with `test_scaled_dot_product_attention.py`

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#7994]
Seeing this test fail on both N150 and N300:

https://github.com/tenstorrent/tt-metal/actions/runs/8902134133/job/24447782333
https://github.com/tenstorrent/tt-metal/actions/runs/8885562726/job/24397601439
https://github.com/tenstorrent/tt-metal/actions/runs/8889116545/job/24406991042

I haven't been able to repro successfully on my on dev machine yet.

**Comment by TT-billteng** [comment]
@cglagovichTT please re-assign if you aren't the right person to investigate, thanks :)

**Comment by TT-billteng** [comment]
another failed run https://github.com/tenstorrent/tt-metal/actions/runs/8904505690/job/24453963816

**Comment by TT-billteng** [comment]
seems to be fail whether clock is 800mhz or 1Ghz

**Comment by cglagovichTT** [comment]
I'll take a look, thanks for reproing

**Comment by cglagovichTT** [comment]
It's fine to disable until it's resolved

**Comment by cglagovichTT** [comment]
When you ran 100 times locally, is there a specific test which fails consistently or does it vary?

**Comment by cglagovichTT** [comment]
These seem to be the problem. Reproed on aus-glx-01 N150 at 800 MHz
```
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_scaled_dot_product_attention.py::test_sdpa_tt_with_program_cache[1-8-1-2048-128-k256-q128-bfp8-65-100] - assert False
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_scaled_dot_product_attention.py::test_sdpa_tt_with_program_cache[1-16-1-2048-64-k128-q128-bf16-23-100] - assert False
```

**Comment by TT-billteng** [comment]
I've seen the error mostly in `test_sdpa_tt_with_program_cache`, is it ok to disable the whole test?

**Comment by cglagovichTT** [comment]
yes please disable

**Comment by cglagovichTT** [comment]
My tests passed CI, but eager unit tests 3 on N300 failed https://github.com/tenstorrent/tt-metal/actions/runs/8914556845/job/24482620568

**Comment by cglagovichTT** [comment]
All green after rerunning the failing test (which my code doesn't touch)

**Comment by cglagovichTT** [comment]
my tests were in eager test group 4 which is passing. 
Locally this passed as well
```
pip install pytest-repeat
pytest --count=100 tests/tt_eager/python_api_testing/unit_testing/misc/test_scaled_dot_product_attention.py::test_sdpa_tt_with_program_cache -v 
```

**Comment by cglagovichTT** [comment]
PR https://github.com/tenstorrent/tt-metal/pull/8061
