### ISSUE TITLE
TTNN sub and mul ops - incomplete/inconsistent documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#7996]
For the following TTNN tensor binary logical ops:
- sub, mul
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE).

However, it seems that these ops actually support BFLOAT8_B in practice and do not support ROW_MAJOR.

**Comment by KalaivaniMCW** [comment]
Will revisit this task and update it after migration task

**Comment by mcw-anasuya** [comment]
Merged to main, hence closing
