### ISSUE TITLE
Stable Diffusion hang on N300

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#8008]
See: https://github.com/tenstorrent/tt-metal/actions/runs/8891052064/job/24434609036

models/experimental/functional_stable_diffusion/tests/test_perf_stable_diffusion.py::test_stable_diffusion_perf[1-2-image_size0-3600-1.8]

Couldn't repro locally on my BM

Running again on main to check: https://github.com/tenstorrent/tt-metal/actions/runs/8912592000

**Comment by tt-dma** [comment]
Seems like it might be fixed: https://github.com/tenstorrent/tt-metal/actions/runs/8912592000/job/24476595705

TODO @tt-dma run a few more times to make sure

**Comment by tt-dma** [comment]
Seems ND, happened 1/4 times here: https://github.com/tenstorrent/tt-metal/actions/runs/8912592000

Possibly we just never hit this before/it's not FD-related? Need to run in a loop but I can't repro on my BM

**Comment by tt-aho** [comment]
I was also trying to repro on an N300 vm and coudn't repro locally.

@tt-rkim you mentioned SD perf test also hangs on main? Is that hang ND?

**Comment by tt-rkim** [comment]
Hey guys, https://github.com/tenstorrent/tt-metal/issues/7560
is a relevant issue. Different version of stable diffusion but could be related

@mtatsumiTT @AleksKnezevic should we disable the old stable diffusion test and move it to a deprecated folder?

**Comment by AleksKnezevic** [comment]
Which test do you want to disable? 

There is an ND hang on VM, it doesn't show up on BM AFAIK. We have a workaround for the VM hang, but it's non-performant. It's just there so we have CI coverage in the mean time. The BMs should run the performant test.

**Comment by tt-aho** [comment]
I see, so there aren't any expected issues for the SD perf test on main. We'll try and dig into what the issue is on fd2 then.

**Comment by tt-rkim** [comment]
My bad - I think I got confused.

Last known good for perf pipeline is https://github.com/tenstorrent/tt-metal/commit/3649042c681d295b7f2dbfd81ab14aaeb9d4c86b before the sharding changes. We reverted the sharding changes, but then small allocator changes got added which put it back to red, so we didn't get another green after reverting.  Looks like various things have been causing hangs

**Comment by tt-aho** [comment]
fd2 is currently rebased off of 5c5c4b6fd031be4e14c5b78a439fa38f897efbb1 so this should be a good commit then?

**Comment by tt-dma** [comment]
It's failing nondeterministically on the main commit FD2 branch is based off of:
https://github.com/tenstorrent/tt-metal/actions/runs/8919624703/job/24496256918 - PASS
https://github.com/tenstorrent/tt-metal/actions/runs/8919625259/job/24496276745 - FAIL
https://github.com/tenstorrent/tt-metal/actions/runs/8919625805/job/24496370520 - FAIL
https://github.com/tenstorrent/tt-metal/actions/runs/8919626667/job/24496372453 - FAIL

Failure signature is the same as we're seeing on FD2 tip (hang with last printed output being the same). I think we can call this not an FD2 bug and just rerun if it happens when testing FD2

**Comment by tt-dma** [comment]
Going to close this for now since it's likely not an FD2 issue, let me know if we want to re-open
