### ISSUE TITLE
[Bug Report] dprint_tensix_dest_reg on Grayskull

### ISSUE THREAD

**Issue by rdjogoTT** [tenstorrent/tt-metal#8009]
**Describe the bug**
dprint_tensix_dest_reg does not work properly on Grayskull.
It prints the first 8 columns of each face correctly, then repeats these for the last 8 columns (rather than printing the values actually in those columns).

Example:
correct output for line 1 of a face:
a b c d e f g h I j k l m n o p

current output for line 1 of a face:
a b c d e f g h a b c d e f g h

**To Reproduce**
1. Go to 'tt-metal/tt_eager/tt_dnn/op_library/pool/kernels/compute/max_pool_multi_core.cpp' and add 'dprint_tensix_dest_reg();' before 'tile_regs_wait();' on line 78. Also include '#include "tt_metal/hw/inc/debug/dprint_tensix.h"'.
2. Run 'TT_METAL_DPRINT_CORES=0,0 pytest -svv tests/ttnn/unit_tests/operations/test_max_pool2d.py' maxpool test
4. See error in printed Dst outputs.
Note: occurs when running other tests as well, this is just one example.

**Expected behavior**
I expect that the debug print should print the last 8 columns of each Dst face, rather than repeating the first 8 in their place.

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- On main

**Comment by ihamer-tt** [comment]
Waiting on repo permissions. This is the fix:
```
diff --git a/common/inc/ckernel_debug.h b/common/inc/ckernel_debug.h
index efae256..c6f1237 100644
--- a/common/inc/ckernel_debug.h
+++ b/common/inc/ckernel_debug.h
@@ -211,6 +211,7 @@ inline void dbg_get_array_row(const uint32_t array_id, const uint32_t row_addr,
     dbg_bus_cntl.f.en = 1;
 
     for (uint32_t i=0; i<8; i++) {
+       dbg_bus_cntl.f.sig_sel = i >> 2;
        dbg_bus_cntl.f.rd_sel = i<<1; // Sel 16-bit
        reg_write(RISCV_DEBUG_REG_DBG_BUS_CNTL_REG, dbg_bus_cntl.val);
        wait (5); // Wait for value to get stable

```

**Comment by rdjogoTT** [comment]
> Waiting on repo permissions. This is the fix:
> 
> ```
> diff --git a/common/inc/ckernel_debug.h b/common/inc/ckernel_debug.h
> index efae256..c6f1237 100644
> --- a/common/inc/ckernel_debug.h
> +++ b/common/inc/ckernel_debug.h
> @@ -211,6 +211,7 @@ inline void dbg_get_array_row(const uint32_t array_id, const uint32_t row_addr,
>      dbg_bus_cntl.f.en = 1;
>  
>      for (uint32_t i=0; i<8; i++) {
> +       dbg_bus_cntl.f.sig_sel = i >> 2;
>         dbg_bus_cntl.f.rd_sel = i<<1; // Sel 16-bit
>         reg_write(RISCV_DEBUG_REG_DBG_BUS_CNTL_REG, dbg_bus_cntl.val);
>         wait (5); // Wait for value to get stable
> ```

This fix was implemented and tested in: https://github.com/tenstorrent/tt-metal/pull/8317
