### ISSUE TITLE
`build_metal.sh` cleanup

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#8027]
I think this script is too doing much and may become a "black box" if we keep adding to it.
We should have this script only be responsible for creating the environment.
User would then either do `pip install` themselves or invoke `cmake`

_Originally posted by @TT-billteng in https://github.com/tenstorrent/tt-metal/pull/7601#discussion_r1586880998_

**Comment by vtangTT** [comment]
python_env creation moved into `create_venv.sh` https://github.com/tenstorrent/tt-metal/pull/8522
