### ISSUE TITLE
Yolov4 concat falls back to host 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#8034]
**Is your feature request related to a problem? Please describe.**
The concat ops are falling back to host [in yolov4 end to end implementation](https://github.com/tenstorrent/tt-metal/pull/8011)

**Describe the solution you'd like**
run all ops on device including the concats. The perf excel sheet is attached for reference. 

**Additional context**
running on GS - e150. 
command to run: pytest tests/ttnn/integration_tests/yolov4/test_ttnn_yolov4.py
[ops_perf_results_yolov4End2End_2024_05_01_21_43_28.csv](https://github.com/tenstorrent/tt-metal/files/15183119/ops_perf_results_yolov4End2End_2024_05_01_21_43_28.csv)

**Comment by saichandax** [comment]
In the current YoloV4 implementation with new Conv API (#10068), we don't have concat falling back to host.
Can we close this issue? @dvartaniansTT
