### ISSUE TITLE
Metal EnqueueTrace (ExecBuf) cmd should trigger Prefetcher Stall (don't fetch next cmd to cmddat_q)

### ISSUE THREAD

**Issue by kmabeeTT** [tenstorrent/tt-metal#8062]
Today..

- Currently Prefetcher (`cq_prefech.cpp: fetch_q_get_cmds()`) has ability to fetch one command ahead from prefetch_q to write into cmddat_q.   
- However, this is a problem when a Trace replay (via `CQ_PREFETCH_CMD_EXEC_BUF`) is issued because it is "hijacking" (ie. re-using) the cmddat_q via `process_relay_inline_exec_buf_cmd()` for reading of paged "Trace Buffer" commands from "Trace Buffer in DRAM" directly to cmddat_q.
- This may cause subsequent cmds fetched from "issue q" by fetch_q_get_cmds() to have their data overwritten when the previous cmd `CQ_PREFETCH_CMD_EXEC_BUF` writes it's Trace Buffer cmds to the same place.

Proposal (from @pgkeller )

1. Create a "prefetch stall" feature/flag on fetch_q entry (use MSB as a flag) to tell Prefetcher to stall prefetching ahead.
2. Have host set this flag when generating ExecBuf cmd.
3. In fetch_q_get_cmds() when reading fetch-q entries, must mask off the MSB when decoding fetch_size, and store it in a global state, say `prefetch_stall_state`
4. Have `prefetch_stall_state` take on 3 states:  NOT_STALLED(0) -> STALL_NEXT(1) do next fetch then stall -> STALLED (2) do not fetch anymore
5. Early exit `fetch_q_get_cmds()` if STALLED. 
6. At the end of `read_from_pcie()` (reads from issue-q to cmddat_q) shift `prefetch_stall_state` once to the left.  Remains 0, 1->2.
7. At the end of ExecBuf handling via `process_relay_inline_exec_buf_cmd()` return to `prefetcher_stall_state=NOT_STALLED`

Thoughts from me (found during implementation):

1. If we're going to early-exit `fetch_q_get_cmds()` when STALLED, then read-barrier/sync will be missing (handled in this function), so consider removing early-exit to allow other logic (except new fetches via `read_from_pcie()` ) to execute.  Or keep the early exit, but add code to  `read_from_pcie()` to ensure cmd we are staling on is barriered on and returned.

I have changes made for this last few days when we thought it was the cause of the #7793 hang (it wasn't), will cleanup and put up a PR.

**Comment by kmabeeTT** [comment]
PR for this is here:

https://github.com/tenstorrent/tt-metal/pull/8160

**Comment by davorchap** [comment]
@kmabeeTT has this been fixed and merged?

**Comment by kmabeeTT** [comment]
> [@kmabeeTT](https://github.com/kmabeeTT) has this been fixed and merged?

Not yet, some chat in the linked PR, been working on the feedback, and CI clean, but one more test failure talked about in PR that I hit today, and haven't found the fix for yet.

Priority feels about right, it's not the cause of any known test failures right now, but we should fix it. Leave it with me for a bit longer.
