### ISSUE TITLE
Trace RN50 - Assert: "Statically allocated circular buffers in program 4 clash with L1 buffers on core range"

### ISSUE THREAD

**Issue by kmabeeTT** [tenstorrent/tt-metal#8065]
Hitting this when updating RN50 to use "Trace" feature., looks like L1 usage is increasing when in trace mode, which might make sense.

```

git checkout kmabee/rn50_trace_issue_8065

pytest "models/demos/resnet/tests/test_perf_resnet.py::test_perf_bare_metal[20-0.0135-25-32768]" |& tee resnet.log


                 Always | FATAL    | Statically allocated circular buffers in program 4 clash with L1 buffers on core range [(x=0,y=0) - (x=11,y=7)]. L1 buffer allocated at 267584 and static circular buffer region ends at 435136
```

Needs some debug and figuring out what is happening and what to do.

I heard from Abhinav that this is not the latest resnet version and folks are using "a ttnn version" lately.

**Comment by kmabeeTT** [comment]
As experiment, disabling the change to extend IO and intermediate lifetime during capture does work around this error and sibling #8066, namely commenting out this line in `HWCommandQueue::enqueue_program()`:

```
this->trace_ctx->owned_buffer_pool.insert(this->trace_ctx->owned_buffer_pool.end(), program.owned_buffer_pool.begin(), program.owned_buffer_pool.end());
```

Proper fix not yet clear, should be something along the lines of what #7832 is proposing (but the WIP change there at https://github.com/tenstorrent/tt-metal/commit/f0ed014334059d8198aa5f1172e9962540a00ebb didn't solve this yet).

**Comment by davorchap** [comment]
closing as this is not an  issue anymore, fyi @tt-aho
