### ISSUE TITLE
CommandQueueSingleCardFixture.ShardedBufferReadWrites shows incorrect output

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#8077]
` TT_METAL_ENABLE_REMOTE_CHIP=1 ./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter="CommandQueueSingleCardFixture.ShardedBufferReadWrites`

**Comment by tt-dma** [comment]
`ShardedBufferLargeReadWrites` also appears to show the same issue

**Comment by ubcheema** [comment]
PR created with fix: https://github.com/tenstorrent/tt-metal/pull/8134

**Comment by ubcheema** [comment]
fix pushed to fd-2/main
