### ISSUE TITLE
Top level end-to-end performance infra checklist

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent/tt-metal#8085]
**Baseline perf:**

1. Use "performance" cpu freq governor: https://github.com/tenstorrent/tt-metal/issues/5281
   - at the minimum on perf regression machines & developer BMs, but if we ran it on all CI it may speed up all pipelines
3. Fix Release build on CI: https://github.com/tenstorrent/tt-metal/issues/4255
4. Pick optimal compiler (GCC vs Clang): https://github.com/tenstorrent/tt-metal/issues/8460

**Improving python -> C++ interface:**

1. Upgrade to Python 11: https://github.com/tenstorrent/tt-metal/issues/7451
2. #4258 

CC: @TT-billteng @davorchap @tt-rkim

**Comment by TT-billteng** [comment]
closing as I own the remaining issue
