### ISSUE TITLE
Investigate CMake support for UMD

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent/tt-metal#8129]
Would make `tt_metal` CMake build a lot cleaner

**Comment by joelsmithTT** [comment]
Looks like https://github.com/tenstorrent/tt-metal/pull/9383 added this.

**Comment by TT-billteng** [comment]
@vtangTT think we can close this?

**Comment by vtangTT** [comment]
Yes, we have CMake support in UMD now. Closing.
