### ISSUE TITLE
TTNN log-alike ops incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8142]
For the following TTNN tensor log-alike ops:
- log2, log10, log1p, log_sigmoid

The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE).

However, it seems that these ops actually support BFLOAT16 with TILE layout. ROW_MAJOR is not supported.
However, some of them do execute with BFLOAT8_B (low PCC on GS in some cases):
- log2, log_sigmoid, log10

Log_sigmoid seems to pass with BFLOAT8_B on both GS and WH.
Log1p - seems that a BFLOAT8_B not supported.

**Comment by VirdhatchaniKN** [comment]
Fix for `log_sigmoid` provided in PR #8050 
Fix for `log2`, `log10`, `log1p` provided in PR #7827

**Comment by VirdhatchaniKN** [comment]
Will revisit after Migration task - https://github.com/tenstorrent/tt-metal/issues/7711#issuecomment-2245229879

**Comment by mcw-anasuya** [comment]
Doc updated and merged to main, hence closing this issue.
