### ISSUE TITLE
Mamba Demo ND hang on nightly

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#8146]
https://github.com/tenstorrent/tt-metal/actions/runs/8952210492/job/24589377588

This happens with/without fd2 changes and seems ND, sometimes ci can pass

**Comment by tt-aho** [comment]
Maybe not specific to mamba and maybe something else in the pipeline is causing issues?
I see SD random hang before without fd2 merge after disabling mamba (this runs before mamba) https://github.com/tenstorrent/tt-metal/actions/runs/8960407033/job/24606920317
I see mistral random hange with fd2 changes after disabling mamba (this runs after mamba) https://github.com/tenstorrent/tt-metal/actions/runs/8959824908/job/24605745360

**Comment by uaydonat** [comment]
fyi @esmalTT

**Comment by tt-aho** [comment]
I also confirmed after removing mamba it's not always the same mistral test that hangs, and that it hangs without fd2 changes. Will spin a separate issue for it but could be related.

**Comment by uaydonat** [comment]
do these tests hang locally? It may make sense to run them 20+ times in a loop to get reasonable status.

**Comment by tt-aho** [comment]
I haven't tried locally. I am currently looking for/triaging issues related to FD2, and this happens without fd2 so didn't look into it further.

**Comment by uaydonat** [comment]
thanks @tt-aho 

@esmalTT to try what is going on...

**Comment by tt-aho** [comment]
@uaydonat @esmalTT follow up, it might not be a hang but ci timeout might be too low so it just kills the job in mamba test, I'm investigating if this is the cause

**Comment by esmalTT** [comment]
@

> @uaydonat @esmalTT follow up, it might not be a hang but ci timeout might be too low so it just kills the job in mamba test, I'm investigating if this is the cause

To add to this - I ran several hundred iterations of this test in release and debug on main and was unable to replicate it locally. 

I will increase the generation length and run again overnight. I'll let you know if I find any issues.

**Comment by tt-aho** [comment]
Seems like it's due to ci timeout. Job seems to have large variance time on ci (~20min variation). I'm increasing the timeout and adding the test back to ci. Closing.

**Comment by uaydonat** [comment]
If there is a large variance of runtime, we would like to figure out why.
