### ISSUE TITLE
Mixtral output mismatch on multi chip nightly

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#8147]
https://github.com/tenstorrent/tt-metal/actions/runs/8952213400/job/24590048040

This is seen without FD2 changes. After fd2 merge this pipeline hangs on an earlier test, so not sure how this test runs with FD2

**Comment by jliangTT** [comment]
@uaydonat , can someone on your team take a look at this? c.c. @yieldthought as well. 

Btw.. @tt-dma , was there a commit that this test pass before? (i double check your spreadsheet and it looks like multi-chip nightly was passing quite recently)

**Comment by tt-dma** [comment]
> @uaydonat , can someone on your team take a look at this? c.c. @yieldthought as well.
> 
> Btw.. @tt-dma , was there a commit that this test pass before? (i double check your spreadsheet and it looks like multi-chip nightly was passing quite recently)

@jliangTT I believe this test is new, it wasn't present in the nightly multi-chip runs for FD2, e.g. https://github.com/tenstorrent/tt-metal/actions/runs/8941347012

**Comment by uaydonat** [comment]
Yes, mixtral was added to CI on May 1st.

**Comment by yieldthought** [comment]
On it.

**Comment by uaydonat** [comment]
@yieldthought has fix, waiting for further testing

**Comment by uaydonat** [comment]
@yieldthought can we close this?
