### ISSUE TITLE
Hang in multi device open close after FD2 Merge

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#8148]
Hang in tests/ttnn/unit_tests/test_multi_device.py::test_multi_device_open_close_full_device_mesh_fixture[silicon_arch_name=wormhole_b0-silicon_arch_wormhole_b0=True]

https://github.com/tenstorrent/tt-metal/actions/runs/8952935174/job/24590887484

Looking at ci it might hang/crash on different variations of test_multi_device.py tests. These tests/hangs are both run/seen on nightly multi chip and multi chip pipelines.
Testing main without FD2 doesn't seem to hang here and fails later on so this seems most likely an fd2 issue

**Comment by aliuTT** [comment]
fixed on main
