### ISSUE TITLE
TTNN logit op - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8150]
For TTNN logit op:
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, its seems that it does not support BFLOAT8_B, neither ROW_MAJOR is not supported.

**Comment by Aswinmcw** [comment]
Will revisit this task and update it after migration task

**Comment by Aswinmcw** [comment]
Fix merged to main
