### ISSUE TITLE
TTNN mish - incomplete documentation 

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8156]
For TTNN mish op:
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, its seems that it does not support BFLOAT8_B type (only BFLOAT16 works), neither layout ROW_MAJOR is supported (TILE supported).

**Comment by KalaivaniMCW** [comment]
Fix provided in #8050  https://github.com/tenstorrent/tt-metal/pull/8050/

**Comment by mcw-anasuya** [comment]
Added supported datatypes and layouts and merged to main.
Closing this issue.
