### ISSUE TITLE
TTNN leaky relu - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8157]
For TTNN leaky_relu op:
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, its seems that it does support BFLOAT8_B type, but layout ROW_MAJOR is not supported (TILE supported).

**Comment by KalaivaniMCW** [comment]
Fix for this in PR #8050

**Comment by KalaivaniMCW** [comment]
Will revisit this task and update it after migration task

**Comment by mcw-anasuya** [comment]
Merged to main. Hence closing this issue.
