### ISSUE TITLE
TTNN Heaviside - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8158]
For TTNN Heaviside op:
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, its seems that it does support BFLOAT8_B type apart from BFLOAT16, but layout ROW_MAJOR is not supported (TILE supported).

**Comment by KalaivaniMCW** [comment]
Fix for this in PR https://github.com/tenstorrent/tt-metal/pull/8050

**Comment by mcw-anasuya** [comment]
Merged to main. Hence closing.
