### ISSUE TITLE
DPRINT only supports specific cb ptr for tile slices in BRISC/NCRISC

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#8164]
File `tt_metal/hw/inc/debug/dprint_tile.h`

```
#if defined(TRISC_PACK) || defined(COMPILE_FOR_NCRISC)
        this->ptr_ = cb_interface[cb].fifo_wr_ptr<<4;
#elif defined(TRISC_UNPACK) || defined(COMPILE_FOR_BRISC)
        this->ptr_ = cb_interface[cb].fifo_rd_ptr<<4;
#else
        this->ptr_ = 0;
#endif
```

Using tslice on brisc always assumes we are using the rd ptr (between cb wait/pop front) while on ncrisc it assumes we are using the wr ptr (between cb reserve/push back) but we can do either on ncrisc or brisc.

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent/tt-metal/pull/13489 implements this
