### ISSUE TITLE
Remove ttl custom matmuls and replace with ttnn matmuls

### ISSUE THREAD

**Issue by TT-BrianLiu** [tenstorrent/tt-metal#8174]
Remove all custom matmuls/bmms and replace with ttnn matmuls/linears. There might be minor host perf degradation since some of the asserts are in python now. 

List:
- [x] bert matmuls/bmms
- [ ] falcon matmuls/bmms
- [ ] resnet_matmul, matmul_1d

**Comment by davorchap** [comment]
> Remove all custom matmuls/bmms and replace with ttnn matmuls/linears. There might be minor host perf degradation since some of the asserts are in python now. 
> 
> 
> 
> List:
> 
> - [x] bert matmuls/bmms
> 
> - [ ] falcon matmuls/bmms
> 
> - [ ] matmul_1d
> 
> - [ ] Others...

With migration to C++ all of the asserts will be Program cached?

**Comment by TT-BrianLiu** [comment]
Asserts, getting program config, and ttnn tensor rank handling will eventually be cached (everything inside op struct essentially). But we need to review how we want to handle where this happens.

**Comment by TT-BrianLiu** [comment]
Tracked by this issue now: https://github.com/tenstorrent/tt-metal/issues/9492
