### ISSUE TITLE
Random Mistral ND Hangs in Nightly Fast Dispatch

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#8177]
On branch `aho/chi-check-disable` which is main without fd2 changes, I see a hang in Mistral tests after removing the hanging mamba test in #8146.

In this run was mistral embeddings
https://github.com/tenstorrent/tt-metal/actions/runs/8960407033/job/24631516556

With fd2 changes I saw hangs in rmsnorm and mlp so doesn't seem consistent
https://github.com/tenstorrent/tt-metal/actions/runs/8959824908/job/24605745360

Better to look into the without fd2 issue first since we're still ironing out some fd2 related bugs and it could be the same issue.

**Comment by tt-aho** [comment]
Follow up it might not be a hang, ci timeout might be too short, investigating

**Comment by tt-aho** [comment]
Seems like it's due to ci timeout. Job seems to have large variance time on ci. Closing.

**Comment by TT-billteng** [comment]
should we increase time limit?

**Comment by tt-aho** [comment]
Yes, I have a pr with the increased time limit about to merge #8138. I am increasing it from 30min -> 60min as I see sometimes it takes ~30min, and sometimes it takes ~50min
