### ISSUE TITLE
CMake precompiled headers 

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#8194]
Minor note. It'll be great if you could enable [precompiled headers](https://cmake.org/cmake/help/latest/command/target_precompile_headers.html) during build. Should cut down the build time by a lot for Metalium. TTNN takes a while to build, I think it'll greatly benefit from it.

_Originally posted by @marty1885 in https://github.com/tenstorrent/tt-metal/issues/7914#issuecomment-2097463664_

**Comment by vtangTT** [comment]
PCH for third party headers have been added. Unfortunately, right now it seems metal doesn't play well with pch due to the different build flags of our targets and rapidly changing header files.

**Comment by TT-billteng** [comment]
> PCH for third party headers have been added. Unfortunately, right now it seems metal doesn't play well with pch due to the different build flags of our targets and rapidly changing header files.

but you submitted to main? Something broken?

**Comment by marty1885** [comment]
> right now it seems metal doesn't play well with pch due to the different build flags of our targets and rapidly changing header files.

This doesn't sound right to me. CMake should automatically detect flag changes and recompile the PCH. Also due to how slow TTNN compiles. It should still result in faster built times even just within a single run.

**Comment by vtangTT** [comment]
From what I've observed the different build flags prevents us from using the `REUSE_FROM` option in `target_precompile_headers`. 

From my testing with PCHs with ttnn, I've observed slower single run compile times compared to without PCHs using both `make` and `ninja`. The branch I've been using is `vtangTT/testing_pch`, where you can see the headers I'm trying to pre-compile in `ttnn/CMakeLists.txt`

Please let me know if I'm misunderstanding what you meant in regards to using PCHs in ttnn.

**Comment by marty1885** [comment]
@vtangTT I'm currently dealing with some family affairs. I'll get back to you as soon as I'm done with it.

I think REUSE_FROM might be the issue. That imports some headers that might not be needed from library A into also compiling for library B. Each library/executable should have their own list of headers (even if it's just `string` and `fmt`).

**Comment by marty1885** [comment]
@vtangTT Which branch contains your PCH patches? I found `vtangTT/testing_pch` is this the one'?

**Comment by vtangTT** [comment]
Yes that is the one.

**Comment by TT-billteng** [comment]
using PCH now
