### ISSUE TITLE
SD fails when num_inference_steps < 4

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent/tt-metal#8196]
**Describe the bug**
If the num_inference_steps is < 4, we experience an error in the Stable Diffusion model.

**To Reproduce**
1. On the latest main, run the following command
```
pytest --disable-warnings --input-path="models/experimental/functional_stable_diffusion/demo/input_data.json" models/experimental/functional_stable_diffusion/demo/demo.py::test_demo

```

**Expected behavior**
Stable diffusion model is expected to run smoothly without any issues.

**Screenshots**
```
>           prk_timesteps = np.array(self._timesteps[-self.pndm_order :]).repeat(2) + np.tile(
                np.array([0, self.num_train_timesteps // num_inference_steps // 2]), self.pndm_order
            )
E           ValueError: operands could not be broadcast together with shapes (4,) (8,)

models/demos/wormhole/stable_diffusion/sd_pndm_scheduler.py:70: ValueError
```

**Comment by boris-drazic** [comment]
SD uses [`PNDMScheduler`](https://huggingface.co/docs/diffusers/main/en/api/schedulers/pndm#diffusers.PNDMScheduler), which implements  the pseudo linear multi-step and pseudo Runge-Kutta method. This is described in Algorithm 2 in [paper](https://arxiv.org/pdf/2202.09778.pdf). For this algorithm to work, there need to be at least 4 inference steps scheduled.

@Sudharsan-V please add a check to TT implementation of scheduler and if  num_inference_steps < 4 error out with message that minimal number of steps must be 4. Also add to readme that num_inference_steps must be at least 4.

**Comment by Sudharsan-V** [comment]
> SD uses [`PNDMScheduler`](https://huggingface.co/docs/diffusers/main/en/api/schedulers/pndm#diffusers.PNDMScheduler), which implements the pseudo linear multi-step and pseudo Runge-Kutta method. This is described in Algorithm 2 in [paper](https://arxiv.org/pdf/2202.09778.pdf). For this algorithm to work, there need to be at least 4 inference steps scheduled.
> 
> @Sudharsan-V please add a check to TT implementation of scheduler and if num_inference_steps < 4 error out with message that minimal number of steps must be 4. Also add to readme that num_inference_steps must be at least 4.

Sure @boris-drazic, Will add the required checks and update the commit.
