### ISSUE TITLE
Add feature support of 'out_channels' argument for the ttnn.conv operation

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#8201]
In UNet functional model, regarding the last conv, the output shape of ttnn conv is different compared to the output shape of torch.
In torch, the required out_channels is specified:` nn.Conv2d(in_channels=32, out_channels=1, kernel_size=1)`
In ttnn, adding out_channels feature is required, to match the expected output shape of ttnn conv as in torch conv.
Here is the [commit](https://github.com/tenstorrent/tt-metal/commit/63b548b9418b3db8aa1d947787d5865d405b4cf5) reproducing the issue.

Steps to test the commit:

Checkout to branch harini/unet_conv_unittest
Run the command: pytest tests/ttnn/integration_tests/unet/test_unet_conv_unittest.py

**Comment by nsmithtt** [comment]
@saichandax, I'm not sure I understand this request, `ttnn.Conv2d` does support `out_channels` (second argument to the class).

**Comment by nsmithtt** [comment]
I see, @saichandax, the output channels get padded to tile, we can take a look.

**Comment by sankarmanoj-tt** [comment]
The test case linked [here](https://github.com/tenstorrent/tt-metal/commit/63b548b9418b3db8aa1d947787d5865d405b4cf5) passes on main.

The new conv api pads to 32, and so it fails.

**Comment by sankarmanoj-tt** [comment]
https://github.com/tenstorrent/tt-metal/commit/5b57dbfa6ae48990a56c3c54a6566b61dbbfef38

**Comment by mbahnasTT** [comment]
@saichandax @HariniMohan0102 is that issue resolved?
