### ISSUE TITLE
Add user to tenstorrent-metal team in Cloud website

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/tt-metal#8235]
## Problem/Purpose
Following the guide:
https://github.com/tenstorrent-metal/metal-internal-workflows/wiki/Creating-a-virtual-machine-on-the-TT-Cloud#create-a-base-virtual-machine
> File an issue on https://github.com/tenstorrent-metal/tt-metal to be added to the "Tenstorrent Metal" team on the Cloud website. You cannot proceed to the next step until someone completes this request for you.

[not urgent]

**Comment by tt-rkim** [comment]
Closing this, let me know privately if you still see access problems
