### ISSUE TITLE
Back-to-Back runs of sharded allgather sees deterministic argument corruption after deterministic number of runs

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#8257]
When running sharded allgather in a loop, I get a hang/watcher error after 7 loop iterations:

```
Always | WARNING  | Watcher detected NOC error and stopped device: bad NOC unicast transaction.
Always | WARNING  | Device 0 worker core(x= 0,y= 1) phys(x= 1,y= 2): brisc using noc1 tried to access DRAM core w/ physical coords (x=0,y=5) DRAM[addr=0x00165800,len=8192]
Always | INFO     | Last waypoint: NAWW,CRBW,   W,   W,   W 
Always | INFO     | While running kernels:
Always | INFO     |  brisc : tt_eager/tt_dnn/op_library/all_gather/kernels/dataflow/worker_sharded_ring_gather_send_writer.cpp
Always | INFO     |  ncrisc: tt_eager/tt_dnn/op_library/all_gather/kernels/dataflow/worker_sharded_ring_gather_send_reader.cpp
Always | INFO     |  triscs: blank
Always | FATAL    | Watcher detected NOC error and stopped device: bad NOC unicast transaction.
```

When enabling DPRINT, you'll see for the reported core (Search for "eth_sender_l1_base_addr "), that the first couple runs have the correct value (an erisc L1 address), however, for the failing run, it should an address past the end of erisc l1. I printed this argument for all cores of this program and saw that all of them had the same value:
```
eth_sender_l1_base_addr = 1464320
...
eth_sender_l1_base_addr = 1464320
...
eth_sender_l1_base_addr = 1464320
...
```

Under normal/correct operation, each worker running this kernel expects a different value for this argument:
```
eth_sender_l1_base_addr = 102320
eth_sender_l1_base_addr = 120752
eth_sender_l1_base_addr = 139184
...
```

# Steps
- acquire t3000
- checkout `snijjar/sharded-allgather-args-issue`
- build: `make build tests/tt_metal tests/tt_eager -j32`
- setup env:
```
export TT_METAL_DPRINT_CORES=all
export TT_METAL_DPRINT_CHIPS=0
```
- run: `TT_METAL_LOGGER_LEVEL=Trace TT_METAL_LOGGER_TYPES=Op  TT_METAL_WATCHER=30 pytest -svv tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py -k "post_commit and  sharded" 2>&1 | tee run.log`

**Comment by SeanNijjar** [comment]
I'm leaning towards this being a dispatcher issue for a couple reasons:
- From what I could see in my logs, I never set `1464320` as a kernel argument for this kernel
- Allgather never does a noc multicast
- The kernel arguments are reliably correct for multiple back to back runs but deterministically get corrupted in the 7th run

**Comment by jliangTT** [comment]
assigning to FD2 board.

**Comment by aliuTT** [comment]
Not sure where you're seeing 7 loop iterations, are you referring to 
```
Call 0
Call 1
Call 2
Call 3
Call 4
Call 5
Call 6
Call 7
```

This is the input tensors right? What I'm seeing is that it hangs after first iteration. Symptoms are still what you described though. I will continue looking.

**Comment by aliuTT** [comment]
It's a program cache issue. If I remove `use_program_cache` from the test it passes a few iterations. I don't think it's necessarily the cached commands code path from command_queue.cpp. I tried regenerating all cmds even with `use_program_cache` enabled, still hangs. Digging around in python land to see if anything is weird

**Comment by SeanNijjar** [comment]
> Not sure where you're seeing 7 loop iterations, are you referring to
Yea I was referring to that. It gets printed for each all-gather invocation.

I took a look at the diff I gave you and need to apologize. I think I accidentally shifted the print Call line above the loop it was intended to be in 🤦 . Now I'm second guessing myself where I saw the correct values being passed in. Maybe for another chip but the same first run. 

Should I take this issue back in case I overlooked something due to this (foot shoot) misdirect?

**Comment by aliuTT** [comment]
I'll take a look for the rest of the day, collecting some data from command queue side to see if something is wrong there for cacheing.

**Comment by SeanNijjar** [comment]
Taking back ownership of this issue after identifying a bug in the override runtime args callback for sharded allgather. I initially didn't consider the callback as being a culprit due to the misdirect I did to myself from my previous comment... yay. Sorry @aliuTT

**Comment by davorchap** [comment]
> Taking back ownership of this issue after identifying a bug in the override runtime args callback for sharded allgather. I initially didn't consider the callback as being a culprit due to the misdirect I did to myself from my previous comment... yay. Sorry [@aliuTT](https://github.com/aliuTT)

thanks @SeanNijjar , will remove from FD2/P0

**Comment by SeanNijjar** [comment]
I've got a fix for this issue. PR coming tomorrow along with other allgather/sharded allgather improvements. However, after clearing this issue, I'm hitting the same problem seen in #6388.

**Comment by davorchap** [comment]
> I've got a fix for this issue. PR coming tomorrow along with other allgather/sharded allgather improvements. However, after clearing this issue, I'm hitting the same problem seen in #6388.

Do we know where it's hanging?

**Comment by SeanNijjar** [comment]
> Do we know where it's hanging?
Yes I know where it's hanging but just not sure of the why yet. The internal signalling between two workers in the allgather kernel somehow got messed up. (A random) one of the workers thinks it didn't get (or really didn't get) its last message available signal but EDM says it sent it. Current status is that I'm trying to root cause where/why this disagreement shows up.

**Comment by SeanNijjar** [comment]
The hang from this last comment was duplicate of #6388
