### ISSUE TITLE
Reshard Runtime Assert Issue 

### ISSUE THREAD

**Issue by tarafdarTT** [tenstorrent/tt-metal#8260]
Shows up with RN50:
This shows up after I made fixes to support uneven shards, so might be due to that. 

```
input_mem_config=
tt::tt_metal::MemoryConfig(memory_layout=TensorMemoryLayout::HEIGHT_SHARDED,buffer_type=BufferType::L1,shard_spec=tt::tt_metal::ShardSpec(grid={[(x=0,y=0) - (x=7,y=5)], [(x=0,y=6) - (x=0,y=6)]}, shape={320, 512}, orientation=ShardOrientation::ROW_MAJOR, halo=false))

output_mem_config
tt::tt_metal::MemoryConfig(memory_layout=TensorMemoryLayout::BLOCK_SHARDED,buffer_type=BufferType::L1,shard_spec=tt::tt_metal::ShardSpec(grid={[(x=0,y=0) - (x=7,y=7)]}, shape={1984, 64}, orientation=ShardOrientation::COL_MAJOR, halo=false))

```
CC @shwetankTT @mywoodstock @jliangTT

**Comment by tarafdarTT** [comment]
@shwetankTT @mywoodstock @jliangTT I think I have a fix: https://github.com/tenstorrent/tt-metal/pull/8279
I got this to work with the same shape in unit tests. 
One unrelated unit test is not working so I need to debug this before pushing, but it should be ready for your shapes.

**Comment by shwetankTT** [comment]
Thanks @tarafdarTT . I cherry picked your commit and now getting expected PCC from resnet batch 20.

**Comment by tarafdarTT** [comment]
Amazing, I will get this ready to merge today

**Comment by tt-rkim** [comment]
This has caused issues with  perf resnet and nightly pipelines
I will reverting `c95e6af65219cf3d5aca6bc5bbed5215c9557eaa`

**Comment by shwetankTT** [comment]
@tt-rkim  Please take a look at this PR: https://github.com/tenstorrent/tt-metal/pull/8283. We may see some performance degradation due to this fix for batch 20 on WH.

**Comment by shwetankTT** [comment]
Okay. The changes are a need to fix the PCC issue with resnet. The changes Naif has made was also a part of the fix. I will update the threshold if needed.

**Comment by tt-rkim** [comment]
Please do this from now on with your changes.

Please check both perf pipelines.

**Comment by tarafdarTT** [comment]
@shwetankTT ya I think we'll need to update the threshold. Even with my change it affects it. 
I think I can make difficult issue to investigate this however.
But ya bad PCC with good perf is worse than good PCC and worse perf. 


This fix is a bit more involved because it causes some failures in nightly that I am investigating. I think I'll need until tomorrow to fix this at the worse case scenario. Ideally finish by today.

**Comment by shwetankTT** [comment]
@tarafdarTT Once you are done with your changes Please do let me know. I need to test the performance impact for b20 resnet.

**Comment by tarafdarTT** [comment]
@shwetankTT I think I'm done. 
What I thought was broken on the nightly looks like is not due to my change according to : https://github.com/tenstorrent/tt-metal/issues/8555

So the only issue is the perf. Could you update the perf on my branch such that the perf test passes? You would have a better idea of what it should be. (Either update on my branch, or pull my fix into your branch and push it together as part of your PR). 

my branch is `tarafdarTT/reshard_with_padding_2` (note the 2, that's important )

**Comment by shwetankTT** [comment]
@tarafdarTT This branch is good. May be other commits are creating the problem.

**Comment by shwetankTT** [comment]
@tarafdarTT The issue is not fixed yet.


```
import pytest
import math
from typing import Union, Tuple
from loguru import logger
import torch
import tt_lib as ttl
import ttnn

from tests.ttnn.utils_for_testing import check_with_pcc_without_tensor_printout
from tests.ttnn.ttnn_utility_fuction import get_shard_grid_from_num_cores
from models.utility_functions import skip_for_wormhole_b0, skip_for_grayskull
from tt_lib.utils import (
    _nearest_y,
)

def test_reshard(device):
    batch_size, input_channels, input_height, input_width = 20, 512, 49, 49 #1, 1, 15680, 512
    input_shape = [batch_size, input_channels, input_height, input_width]
    torch.manual_seed(0)
    torch_input = torch.rand(input_shape, dtype=torch.bfloat16) * 2 - 1

    ## permute to N H W C, which is what the upsample op expects
    torch_input = torch_input.reshape(1, 1, batch_size * input_height * input_width, input_channels)
    input_tensor = ttnn.from_torch(
        torch_input, device=device, memory_config=ttnn.L1_MEMORY_CONFIG, dtype=ttnn.bfloat8_b, layout=ttnn.TILE_LAYOUT
    )
    core_grid = get_shard_grid_from_num_cores(49, device)
    print(core_grid)
    in_sharded_mem_config = ttnn.create_sharded_memory_config(
        shape=(320, 512),
        #shape=(512, 320),
        core_grid= core_grid,
        strategy= ttnn.ShardStrategy.HEIGHT,
        orientation=ttnn.ShardOrientation.ROW_MAJOR,
        use_height_and_width_as_shard_shape=True,
    )
    print("hello")
    input_tensor = ttnn.to_memory_config(input_tensor, memory_config=in_sharded_mem_config, dtype=ttnn.bfloat8_b)
    shard_config = ttnn.create_sharded_memory_config(
        shape=(1984, 64),
        core_grid= ttnn.CoreGrid(y=8, x=8),
        strategy= ttnn.ShardStrategy.BLOCK,
        orientation=ttnn.ShardOrientation.COL_MAJOR,
        use_height_and_width_as_shard_shape=True,
    ) 
    output_tensor = ttnn.to_memory_config(input_tensor, memory_config=in_sharded_mem_config, dtype=ttnn.bfloat8_b)
    output_tensor = ttnn.to_torch(output_tensor)
    passing, pcc_msg = check_with_pcc_without_tensor_printout(torch_input, output_tensor, 0.999)
    logger.info(pcc_msg)
    assert passing

```

**Comment by tarafdarTT** [comment]
looking at this now

**Comment by tarafdarTT** [comment]
> @tarafdarTT The issue is still in the mainline. Added the code to reproduce this issue.
> 
> ```
> import pytest
> import math
> from typing import Union, Tuple
> from loguru import logger
> import torch
> import tt_lib as ttl
> import ttnn
> 
> from tests.ttnn.utils_for_testing import check_with_pcc_without_tensor_printout
> from tests.ttnn.ttnn_utility_fuction import get_shard_grid_from_num_cores
> from models.utility_functions import skip_for_wormhole_b0, skip_for_grayskull
> from tt_lib.utils import (
>     _nearest_y,
> )
> 
> def test_reshard(device):
>     batch_size, input_channels, input_height, input_width = 20, 512, 49, 49 #1, 1, 15680, 512
>     input_shape = [batch_size, input_channels, input_height, input_width]
>     torch.manual_seed(0)
>     torch_input = torch.rand(input_shape, dtype=torch.bfloat16) * 2 - 1
> 
>     ## permute to N H W C, which is what the upsample op expects
>     torch_input = torch_input.reshape(1, 1, batch_size * input_height * input_width, input_channels)
>     input_tensor = ttnn.from_torch(
>         torch_input, device=device, memory_config=ttnn.L1_MEMORY_CONFIG, dtype=ttnn.bfloat8_b, layout=ttnn.TILE_LAYOUT
>     )
>     core_grid = get_shard_grid_from_num_cores(49, device)
>     print(core_grid)
>     in_sharded_mem_config = ttnn.create_sharded_memory_config(
>         shape=(320, 512),
>         #shape=(512, 320),
>         core_grid= core_grid,
>         strategy= ttnn.ShardStrategy.HEIGHT,
>         orientation=ttnn.ShardOrientation.ROW_MAJOR,
>         use_height_and_width_as_shard_shape=True,
>     )
>     print("hello")
>     input_tensor = ttnn.to_memory_config(input_tensor, memory_config=in_sharded_mem_config, dtype=ttnn.bfloat8_b)
>     shard_config = ttnn.create_sharded_memory_config(
>         shape=(1984, 64),
>         core_grid= ttnn.CoreGrid(y=8, x=8),
>         strategy= ttnn.ShardStrategy.BLOCK,
>         orientation=ttnn.ShardOrientation.COL_MAJOR,
>         use_height_and_width_as_shard_shape=True,
>     ) 
>     output_tensor = ttnn.to_memory_config(input_tensor, memory_config=shard_config)
>     output_tensor = ttnn.to_torch(output_tensor)
>     passing, pcc_msg = check_with_pcc_without_tensor_printout(torch_input, output_tensor, 0.999)
>     logger.info(pcc_msg)
>     assert passing
> ```

good news is @tt-aho's fix removes the runtim assert, bad news is that I am seeing a PCC issue. Is this a representative test case? if so I can look at fixing the PCC issue.

**Comment by tarafdarTT** [comment]
closing for now since @shwetankTT says RN50 is good
