### ISSUE TITLE
Add ttcluster apis to support Galaxy

### ISSUE THREAD

**Issue by ubcheema** [tenstorrent/tt-metal#8305]
get_mmio_device_tunnel_depth():
tunnel depth = number of remote chips serviced by the tunnel.
If mmio chip is connected to only 1 device in the remote chip set, tunnel depth = number of chips in remote group. Resolves to 1 on N300, T3000 per mmio device.

If mmio chip is connected to > 1 chips in the remote chip set, tunnel depth = number of chips in remote chip set divided by tunnel count.

get_mmio_device_tunnel_count(): tunnel count = number of unique remote_device_ids connected to mmio eth ports. 
If mmio decice has multiple ports to same remote chip, tunnel count = 1. e.g Should resolve to 1 on N300, T3000
If mmio chip has eth ports connected to multiple unique remote devices, tunnel count = num eth ports connected to unique remote devices. Should resolve to 2 for each gateway WH on TG.

**Comment by aliuTT** [comment]
APIs checked into `galaxy/main`

**Comment by ubcheema** [comment]
These commits on galaxy/main cause segmentation fault at end of test:
I did not check which of the following two is the culprit. But removing these two commits makes the tests pass cleanly.
With the commits, test passes, but there is a segmentation fault.

```
commit a5f72e20c1cfa4e5eafff8fae970619245b60a99 (HEAD -> galaxy/main, origin/galaxy/main)
Author: Allan Liu <aliu@tenstorrent.com>
Date:   Mon May 13 14:49:20 2024 +0000

    #8305: cleanup, add print

commit 13d134f0eaa25074f38421fbf8ddabb6ae247a18
Author: Allan Liu <aliu@tenstorrent.com>
Date:   Sun May 12 19:31:23 2024 +0000

    #8305: add Galaxy cluster apis
```

**Comment by ubcheema** [comment]
Doing a clean build gets rid of segmentation fault.
It was probably due to some stale build dependency.

**Comment by aliuTT** [comment]
Yea, this was the seg fault I mentioned to you on slack :( Incremental build doesn't pick up the board types I added to the cluster descriptor object used in tt silicon driver
