### ISSUE TITLE
Unsuccessful build on a new VM

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#8328]
Unable to successfully run the `make build` command.

VM: tt-metal-dev-mohammed-mcw-8
IP: 172.27.45.70

<img width="1314" alt="Screenshot 2024-05-10 at 3 48 10 AM" src="https://github.com/tenstorrent/tt-metal/assets/133634875/2ae3c363-6f5f-4db0-b62d-1a4eb1da5baa">

Error:

<img width="1006" alt="Screenshot 2024-05-10 at 3 50 43 AM" src="https://github.com/tenstorrent/tt-metal/assets/133634875/8a87c7b1-62a4-4726-b428-b2f03bb20bfc">

To reproduce:

`ssh ubuntu@172.27.45.70`
`cd tt-metal`
`git submodule update --init --recursive`
`export ARCH_NAME=wormhole_b0`
`export TT_METAL_HOME=$(pwd)`
`export TT_METAL_ENV=dev`
`export PYTHONPATH=$(pwd)`
`make build`

**Comment by shwetankTT** [comment]
Try Installing the system level dependencies mentioned here. https://github.com/tenstorrent/tt-metal/blob/main/INSTALLING.md
`sudo apt update
sudo apt install software-properties-common=0.99.9.12 build-essential=12.8ubuntu1.1 python3.8-venv=3.8.10-0ubuntu1~20.04.9 libgoogle-glog-dev=0.4.0-1build1 libyaml-cpp-dev=0.6.2-4ubuntu1 libboost-all-dev=1.71.0.0ubuntu2 libsndfile1=1.0.28-7ubuntu0.2 libhwloc-dev graphviz`

**Comment by saichandax** [comment]
We had clang++10.0 as default and installed in the VM alerady.
However, the build is looking for clang++6.0.
After installing clang++6.0 version, we were able to run the build successfully.
