### ISSUE TITLE
tt_lib.tensor.bmm and matmul - inconsistent documentation

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#8342]
For tt_lib.tensor.bmm and tt_lib.tensor.matmul ops:

The documentation does not state that operands need to be on device. But when operation is run with inputs in system memory we get error:

```
input_tensor_a.storage_type() == StorageType::DEVICE and input_tensor_b.storage_type() == StorageType::DEVICE
info:
Operands to matmul need to be on device!
```

**Comment by bbradelTT** [comment]
tt_lib bmm/matmul no longer exist and everything in python goes through ttnn matmul/linear. I updated the documentation for the latter to indicate that the tensors need to be on the device.
