### ISSUE TITLE
tt_lib.tensor.glu, geglu, reglu, swiglu - inconsistent documentation 

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#8343]
For ops:

 * tt_lib.tensor.glu
 * tt_lib.tensor.geglu
 * tt_lib.tensor.reglu
 * tt_lib.tensor.swiglu

The documentation does NOT state that operands need to be on device. But when operations are run with inputs in system memory we get error:

```
input_tensor_a.storage_type() == StorageType::DEVICE
info:
Operands to unpad need to be on device!
```

**Comment by mcw-anasuya** [comment]
Merged to main, hence closing this issue.
