### ISSUE TITLE
ttl.tensor.logical_andi operation failed with low PCC [Grayskull and Wormhole]

### ISSUE THREAD

**Issue by banekg** [tenstorrent/tt-metal#8355]
**Describe the bug**

Operation **ttl.tensor.logical_andi** breaks with low PCC error in some test cases.

**To Reproduce**

1. Checkout `main` branch
2. Run unit test `test_eltwise_logical_andi.py` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_logical_andi.py`
3. The same call should be used for the Wormhole, to avoid duplicating files.

**Expected behavior**

There is a test case presented in the unit test `test_eltwise_logical_andi.py` and it is expected to fail with low PCC error. 

**Getting Additional info for the operation under test and its behavior**

To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttl.tensor.permute and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_eltwise_logical_andi_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `logical_andi.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by mouliraj-mcw** [comment]
Hi @banekg 

- The Previousl logical_andi operation was designed for a tensor and a scalar. However, during the TTNN migration, it was replaced with a tensor-tensor(logical_and_) in-place version of the logical_and operation.
- As a result, I added new sweep tests for this in the TTNN infrastructure.(Passed)

**Comment by mouliraj-mcw** [comment]
Closing as completed
