### ISSUE TITLE
single-chip host perf thresholds for CNNs need to be updated

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#8372]

**Comment by davorchap** [comment]
we need to update the tresholds, there have been end2end gains in perf RN50: 2050 -> 2850 fps. 
other models probably was well, let's make sure we update so that we don't slide back

**Comment by AleksKnezevic** [comment]
Stable diffusion perf has been updated.

**Comment by mywoodstock** [comment]
stale issue, closing.
