### ISSUE TITLE
TTNN relational eltwise ops - incomplete documentation 

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8395]
For TTNN relational eltwise ops:
- gtz, ltz, gez, łez, nez

The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE) or ranks. In practice, its seems that they do support BFLOAT8_B type, but layout ROW_MAJOR for any type is not supported (TILE supported for both BFLOAT16 and BFLOAT8_B). Ranks 2,3,4 are supported.

**Comment by KalaivaniMCW** [comment]
will be revisited after TTNN migration

**Comment by mcw-anasuya** [comment]
Merged to main, hence closing.
