### ISSUE TITLE
TTNN xlogy op - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8397]
For TTNN xlogy op

The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE) or ranks. In practice, its seems that it does support BFLOAT8_B type for the first argument apart from BFLOAT16, but layout ROW_MAJOR for any type is not supported. Ranks 2,3,4 are supported.

**Comment by mcw-anasuya** [comment]
Merged to main, hence closing.
