### ISSUE TITLE
Untilize op hangs when running Falcon7b perf test with profiler

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent/tt-metal#8399]
The following Falcon7b perf test (single-chip n300, non-async) hangs when building with `ENABLE_PROFILER=1 ENABLE_TRACY=1 make build`. The hang seems to be occurring on the last op in the model ([this untilize op](https://github.com/tenstorrent/tt-metal/blob/3c9c641bd7ac8e28745d1bf66ae1bb5555795b18/models/utility_functions.py#L193)), as determined by adding `tt_lib.device.Synchronize(tt_tensors_device[i].device())` before and after the op.
Commit: 3c9c641
Command: `./tt_metal/tools/profiler/profile_this.py -n falcon7b_decode_1024 -c "pytest models/demos/falcon7b/tests/test_perf_falcon.py::TestParametrized::test_perf_wh_bare_metal[False-decode_batch32_1024_bf16_l1_sharded-falcon_7b]"`

**Comment by skhorasganiTT** [comment]
FYI @pavlejosipovic @pavlepopovic @s-jovic @johanna-rock-tt @djordje-tt

**Comment by skhorasganiTT** [comment]
@pavlepopovic Mo was not able to reproduce the hang using a clean build and I also could not reproduce it after retrying with `make nuke`. Could you try that as well to see if it fixes it for you?

**Comment by pavlepopovic** [comment]
Not able to reproduce on latest main with clean build

**Comment by mo-tenstorrent** [comment]
Will close the ticket then.

**Comment by mo-tenstorrent** [comment]
Was not reproducible after clean build.
