### ISSUE TITLE
TTNN squared difference - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8427]
For TTNN squared difference op:
The documentation does not cover supported data types (BFLOAT16/BFLOAT8_B) neither the supported layouts (ROW_MAJOR/TILE). In practice, its seems that it does support both BFLOAT16 and BFLOAT8_B types, but layout ROW_MAJOR is not supported (TILE supported). Ranks 2,3,4 are supported.

**Comment by KalaivaniMCW** [comment]
will be revisited after TTNN migration

**Comment by mcw-anasuya** [comment]
Merged to main. Hence closing.
