### ISSUE TITLE
TTNN polyval op - inconsistent documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8428]
For TTNN polyval op:

The documentation seems complete, but not aligned with actual execution outcomes.
It claims supported types (BFLOAT16/BFLOAT8_B) for TILE layout.
However, BFLOAT8_B is not supported, resulting with message:
input_tensor_a.get_dtype() == input_tensor_b.get_dtype()

**Comment by KalaivaniMCW** [comment]
will be revisited after TTNN migration

**Comment by mcw-anasuya** [comment]
Merged to main, hence closing
