### ISSUE TITLE
TTNN Unet inference pipeline

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#8455]
setting up inference pipeline with available PCC
Currently - PCC (~0.0)

Expected behaviour - To get PCC > 0.99

To reproduce: 
go to [harini/unet_inference](https://github.com/tenstorrent/tt-metal/tree/harini/unet_inference)
execute demo.py file.

**Comment by dvartaniansTT** [comment]
@saichandax and @HariniMohan0102 I am a little confused on this one. is this the same model as in #8454? do you mean when you provide a real image input, the pcc goes from 0.8 to 0?

**Comment by HariniMohan0102** [comment]
@dvartaniansTT We are using the same model as in [#8454](https://github.com/tenstorrent/tt-metal/issues/8454) to test inference with a real image input, the pcc drops from 0.8 to ~0.0

**Comment by nsmithtt** [comment]
@dvartaniansTT / @saichandax, can you try using the metal PCC visualizer to debug?

**Comment by mywoodstock** [comment]
@dvartaniansTT is this still valid?
