### ISSUE TITLE
TTNN activation supported ops - incomplete documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8488]
For TTNN supporting activation argument (having effect of op_and_apply_activation):
- subtract, multiply, add

The documentation seems complete when it comes to input types, layouts and ranks, but for argument activations: List[str] it should be stated which are all the supported activation functions that can be called. As for now, it seems to be working with:
- relu

However, if more of them are supported, please add them to documentation if possible.

**Comment by KalaivaniMCW** [comment]
TTNN updated sweeps and docs were in #8050 currently blocked due to TTNN refactoring. Once complete these changes will be merged.
