### ISSUE TITLE
ttnn.conv2d fails with L1 error for mobilenetv2 test cases

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#8490]
ttnn.conv2d is failing with L1 issue for some of the mobilenetv2 unit test cases.

**To Reproduce**
1. Checkout the branch [keerthanar/mobilenetv2_conv_l1_issue_cases](https://github.com/tenstorrent/tt-metal/tree/keerthanar/mobilenetv2_conv_l1_issue_cases).
2. Run the following command,
`pytest tests/ttnn/unit_tests/operations/test_conv2d.py:: test_mobilenetv2_conv_ttnn_l1_issue_case `
3. The following error will occur,
`E           RuntimeError: TT_THROW @ tt_metal/impl/allocator/allocator.cpp:118: tt::exception
E           info:
E           Out of Memory: Not enough space to allocate 98304000 B L1 buffer across 100 banks, where each bank needs to store 983040 B`

**Comment by dvartaniansTT** [comment]
@keerthana-r-mcw and @saichandax please make a new branch off of this one and only include the unit tests of interest: 
(32, 3, 480, 640, 3, 3, 2, 2, 1, 1, True), (24, 144, 120, 160, 1, 1, 1, 1, 0, 0, True), (1280, 320, 15, 20, 1, 1, 1, 1, 0, 0, True)

**Comment by keerthana-r-mcw** [comment]
Resolved with new conv-api
