### ISSUE TITLE
Falcon7b prefill and decode hanging with tracy

### ISSUE THREAD

**Issue by pavlepopovic** [tenstorrent/tt-metal#8492]
On main, falcon7b prefill and decode are hanging when ran with tracy.
Examples of commands that cause hangs:

decode
`python tt_eager/tracy.py -r -m "pytest models/demos/falcon7b/tests/test_perf_falcon.py -k \"test_perf_wh_bare_metal and decode_batch32_128_bf16_dram\""`

prefill
`python tt_eager/tracy.py -r -m "pytest models/demos/falcon7b/tests/test_perf_falcon.py -k \"test_perf_wh_bare_metal and prefill_seq128_bf16_dram\""`

Bisecting the history revealed that commit that caused this is: https://github.com/tenstorrent/tt-metal/commit/3c9c641bd7ac8e28745d1bf66ae1bb5555795b18 (Untilizing on device). Reverting changes from this commit locally made both commands finish.

When running without tracy, both prefill and decode are passing regularly

**Comment by skhorasganiTT** [comment]
This is a known issue that is being tracked in #8399. Closing as it's a duplicate.

**Comment by pavlejosipovic** [comment]
@skhorasganiTT at least give us an FYI when something like this happens we've lost some time debugging this issue and it hurt our productivity. 
In general I would not recommend checkin broken functionality.

**Comment by skhorasganiTT** [comment]
Hi @pavlejosipovic, this issue was recently discovered, not before checking in (and it does not break anything on main, it is a tracy specific issue that is being investigated). I will broadcast updates in advance.

**Comment by pavlejosipovic** [comment]
Yeah I get that it doesn't affect CI but we try to do profile and lost time on just give us a heads up, it is important dev functionality.
