### ISSUE TITLE
ttnn.MaxPool2d fails for shallow_unet_528x528 and  shallow_unet_528x256 unit test cases.

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#8498]
ttnn.MaxPool2d fails with `TT_ASSERT @ ./tt_metal/common/bfloat8.hpp:107: fp32_vec.size() % num_float_in_tile == 0` for shallow_unet_528x528 and shallow_unet_528x256 unit test cases.

**To Reproduce**
1. Checkout the branch [keerthanar/shallow_unet_maxpool_issue_unit_test](https://github.com/tenstorrent/tt-metal/tree/keerthanar/shallow_unet_maxpool_issue_unit_test).
2. Run the following command,
      `pytest tests/ttnn/unit_tests/operations/test_max_pool2d.py:: test_unet_max_pool_wh_issue_case `
3. The following error will occur,
`E           RuntimeError: TT_ASSERT @ ./tt_metal/common/bfloat8.hpp:107: fp32_vec.size() % num_float_in_tile == 0`

**Comment by dvartaniansTT** [comment]
@keerthana-r-mcw and @saichandax please create a new branch off of this one and only include the relevant/failing unit tests.
