### ISSUE TITLE
Low PCC for Shallow UNet FUSED Convs 

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#8510]
**Describe the bug**
In Unet functional model, the overall pcc drops due to less pcc in the following fused conv layers.
The [harini/unet_fused_conv](https://github.com/tenstorrent/tt-metal/compare/harini/unet_fused_conv) consists of unit tests of convs with less pcc

**To Reproduce**
1. Checkout to the branch [harini/unet_fused_conv](https://github.com/tenstorrent/tt-metal/compare/harini/unet_fused_conv) 
2. Run the command `pytest tests/ttnn/integration_tests/unet/unet_failing_fused_conv_test.py`

**Expected behavior**
The unit tests should be passing. Currently, it is failing due to PCC < 0.99.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: GS

**Comment by esmalTT** [comment]
This issue seems stale. UNet PCC is good on main since 2035fd074e4e60912763c917a607f7d7401de6b4. @dvartaniansTT @HariniMohan0102 can we close this?

**Comment by HariniMohan0102** [comment]
This issue can be closed.
