### ISSUE TITLE
OOM issue for Vanilla Unet model on WH device

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#8518]
**Describe the bug**
On running the Unet model on WH device, we face Out Of Memory (OOM) issue in fused convs. 

**To Reproduce**
1. Checkout  to [saichand/unet_on_wh](https://github.com/tenstorrent/tt-metal/tree/saichand/unet_on_wh)
2. Run the command `pytest tests/ttnn/integration_tests/unet/test_ttnn_unet.py`

**Expected behavior**
To test the model without any out of memory issue.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: WH

**Additional context**
We have unit test for some fused convs in the file: `tests/ttnn/integration_tests/unet/unet_fused_conv_test.py` where out of 16 convs, 7 of them are failing due to low pcc or  AssertionError: act_block_h must evenly divide out_block_h.
Debugging on unit tests is still in progress.

**Comment by dvartaniansTT** [comment]
@saichandax please confirm if this the vanilla UNet variant related?

**Comment by vshenoyTT** [comment]
To reproduce the error, follow step 4 of the installation guide and build with CMake, not Makefile. Run the test command, and make sure the virtual environment is activated. If Metal is not building properly, re-clone the repository and try again.

**Comment by HariniMohan0102** [comment]
@dvartaniansTT we worked on UNet and Shallow Unet models. This issue is related to UNet model.

**Comment by pavlejosipovic** [comment]
@HariniMohan0102 I've tried to check state on this issue but I couldn't rebase the branch and run it on top of latest main, 
can you help out with this?

**Comment by HariniMohan0102** [comment]
@pavlejosipovic Currently, this issue is invalid as this was issue faced on Old Conv API. So, this can be closed.
Thank you.
