### ISSUE TITLE
Deprecate and delete native makefile support 1 week after getting rid of it from CI (not docs)

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#8531]
@TT-billteng is in progress of deleting it from CI

We will be deleting all makefile support 1 week or later after this.

Likely date that Make will die is **May 24th**.

cc'ing those who will be partying in the streets: @ayerofieiev-tt @yan-zaretskiy @ttmchiou @vtangTT @mo-tenstorrent

**Comment by TT-billteng** [comment]
you mean May 24th?

**Comment by TT-billteng** [comment]
Queued it up 🤤
