### ISSUE TITLE
Option to allow use of multiple-producer SW queue mode

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#8538]
Build or run-time option to use either
* lock-free single-producer queue (default, internal design)
* lock-free multiple-producer queue: boost::lockfree::queue

**Comment by tt-asaigal** [comment]
Based on multiple offline discussions, we realized that third-party lock free queues cannot work for our use case, due to restrictions like these, on the data stored in the queue:

```
T must have a copy constructor
T must have a trivial assignment operator
T must have a trivial destructor
```

Instead, we gave moreh a locking based queue that can have its setting configured at runtime.
