### ISSUE TITLE
Add queue_id to the MNIST OPs

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#8539]
Parent Issue: #9106 

All of these need Q_ID, 
It's a dedicated optional argument.

**Tenstorrent team to add Q_ID to these Tenstorrent OPS**
- [x] #9108
- [x] #9109
- [x] #9110

**Moreh to add Q_ID to Moreh Ops using the above as examples:**
(update: completed by Moreh. Not blocking). 
- [x] Linear
- [x] Softmax
- [x] NLLLoss
- [x] SGD
- [x] Argmax
- [x] Sum

**Comment by jvasilje** [comment]
API change to add Q ID

**Comment by eyonland** [comment]
@tt-asaigal, can we move forward with https://github.com/tenstorrent/tt-metal/pull/7847 to move forward with Q ID?

**Comment by tt-asaigal** [comment]
> @tt-asaigal, can we move forward with #7847 to move forward with Q ID?

I'll make a proper PR with run_operation infra to support CQ id propagation. We can then migrate all these ops.

**Comment by eyonland** [comment]
Thanks for https://github.com/tenstorrent/tt-metal/pull/9039

**Comment by eyonland** [comment]
Moreh already completed the list.
