### ISSUE TITLE
ttnn.eq incorrect output for uint16 tensors 

### ISSUE THREAD

**Issue by sraizada-tt** [tenstorrent/tt-metal#8551]
ttnn.eq considers 1==0 True for uint16 tensors; unit test:
```
import ttnn 
from ttnn import ReplicateTensorToMesh, ConcatMeshToTensor
import torch 
def test_matmul(device_mesh):
    mask = ttnn.from_torch(
            torch.zeros(1, 1, 32, 32),
            dtype=ttnn.uint16,
            layout=ttnn.TILE_LAYOUT,
            device=device_mesh,
            mesh_mapper=ReplicateTensorToMesh(device_mesh),
        )
    output = ttnn.from_torch(
            torch.ones(1, 1, 32, 32),
            dtype=ttnn.uint16,
            layout=ttnn.TILE_LAYOUT,
            device=device_mesh,
            mesh_mapper=ReplicateTensorToMesh(device_mesh),
        )
    output_reduced = ttnn.eq(output, mask) 

    assert torch.all(ttnn.to_torch(output_reduced, mesh_composer=ConcatMeshToTensor(device_mesh, dim=0))==0 ).item()

```

**Comment by arakhmati** [comment]
Re-assigning this issue to @umadevimcw

**Comment by ruthreshx** [comment]
Hi @sraizada-tt ,
Could you please add the instructions in ticket to recreate the failure in VM ?
Thanks in advance!

**Comment by sraizada-tt** [comment]
lowering priority because we have a workaround

**Comment by KalaivaniMCW** [comment]
will be revisited after TTNN migration

**Comment by ruthreshx** [comment]
@sraizada-tt may I know the workaround that you have?

**Comment by ruthreshx** [comment]
Hi @sraizada-tt, @eyonland 
On analyzing the **ttnn.eq** I found that there is no such support for **tensor vs tensor** comparison for all the supported dtypes. Instead we have only tensor vs scalar for the similar ops such as GT, LT.

Should I goahead and implement the eq_unary(tensor vs scalar) and the API name as similar as torch API for ttnn.eq.

**Comment by sraizada-tt** [comment]
Hi, we are no longer using this op for our model. I think ttnn.eq already supports tensor vs scalar comparison. Should I close this issue now?

**Comment by ruthreshx** [comment]
> Hi, we are no longer using this op for our model. I think ttnn.eq already supports tensor vs scalar comparison. Should I close this issue now?

Hi @sraizada-tt Yes it supports tensor vs scalar comparison, hence we close the issue.
Thank you!
