### ISSUE TITLE
Handle static and dynamic OP validation performantly

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#8569]
* static OPs , always run validate, cache validate as part of Program cache
* dynamic OPs , need to explicitly tag OPs with `dynamic=true` so that infra knows which OPs are dynamic
  - for dynamic OPs we can globally disable validate `ttnn.disable_dynamic_op_validate()`

**Comment by arakhmati** [comment]
New device operation infrastructure requires `validate_on_program_cache_miss` and `validate_on_program_cache_hit` which solves this issue by allowing the user to validate less when the program cache is hit
