### ISSUE TITLE
Fix Clang-17 post-commit

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent/tt-metal#8579]
Failing post-commit: https://github.com/tenstorrent/tt-metal/actions/runs/9120504571

Checklist: 
- [x] #8618
- [x] #8619
- [x] #8620

Other pipelines: 
- metal microbenchmark: https://github.com/tenstorrent/tt-metal/actions/runs/9121786593
- device perf: https://github.com/tenstorrent/tt-metal/actions/runs/9121785507
- model perf (same as main): https://github.com/tenstorrent/tt-metal/actions/runs/9121788555
- nightly fd: https://github.com/tenstorrent/tt-metal/actions/runs/9199329749

Branch with clean Clang-17 build: `vtangTT/clang17`

Need to fix to do this: https://github.com/tenstorrent/tt-metal/issues/8460

Related PR: https://github.com/tenstorrent/tt-metal/pull/8516

CC: @TT-billteng @tt-rkim

**Comment by TT-billteng** [comment]
seems like we have 3 issues:

- [ ] FD SFPU test failures
- [ ] SD SFPU test failures
- [ ] TTNN test failures

How about the other pipelines?

**Comment by vtangTT** [comment]
Not tested yet, will run some tn to test the waters.

**Comment by tt-rkim** [comment]
how was?

**Comment by vtangTT** [comment]
linked above

**Comment by vtangTT** [comment]
post-commit: https://github.com/tenstorrent/tt-metal/actions/runs/9200186861

**Comment by vtangTT** [comment]
fixed
