### ISSUE TITLE
TTNN pow breaks when exponent is tensor

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#8594]
**ttnn.pow** operation fails in cases when both arguments are tensors - input and exponent. It seems to expect either float or int for exponent instead of tensor, but documentation claims tensor exponent support: 

```
1. (input: tt::tt_metal::Tensor, exponent: float, output_mem_config: tt_lib.tensor.MemoryConfig = tt::tt_metal::MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)) -> tt::tt_metal::Tensor
2. (input: tt::tt_metal::Tensor, exponent: int, output_mem_config: tt_lib.tensor.MemoryConfig = tt::tt_metal::MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)) -> tt::tt_metal::Tensor
```

**To Reproduce**
Checkout `main`  branch and run unit test `test_eltwise_pow.py ` (or others) using this command pattern:

```
pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_pow.py
```

**Expected behavior**
There are three test cases presented in the unit test and they all fail: `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_pow.py` and they are expected to fail with error 
```
TypeError: pow(): incompatible function arguments. The following argument types are supported:
```

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweep test:

```
tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_pow_test.yaml
```

To do this you should:

1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
4. Run sweeps by using `pytest tests/ttnn/python_api_testing/sweep_tests/run_sweep_test.py --input-path tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_pow_test.yaml --input-method cli --cli-input results_pow_broken`
5. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by mouliraj-mcw** [comment]
Hi @npetrovic-tenstorrent 
Currently, pow only supports the tensor-scalar variant, so I will update the documentation accordingly.
If tensor is passed as second input it displays `TypeError`
<img width="1287" alt="Screenshot 2024-10-19 at 8 21 35 PM" src="https://github.com/user-attachments/assets/7951cd60-46cd-48cd-9277-908dabb9e153">

**Comment by mouliraj-mcw** [comment]
Hi @npetrovic-tenstorrent 
Can I close the ticket, As we updated the documentation.

**Comment by npetrovic-tenstorrent** [comment]
> Hi @npetrovic-tenstorrent Can I close the ticket, As we updated the documentation.

Yes!

**Comment by mouliraj-mcw** [comment]
closing as completed
