### ISSUE TITLE
Mamba end-to-end perf hanging in CI pipelines

### ISSUE THREAD

**Issue by esmalTT** [tenstorrent/tt-metal#8606]
# Summary

Failed pipelines:
- https://github.com/tenstorrent/tt-metal/actions/runs/9099763560/job/25055147766

# Steps to reproduce

It does not seem possible to replicate this issue on regular lab machines, but I have been able to get this working on a machine closer to the CI configuration.

1. Get a bare-metal machine on the cloud VPN. I am using WH 130.
2. Build `main` in release mode. 
3. Run model perf pipeline with the following command: `./tests/scripts/run_tests.sh --tt-arch $ARCH_NAME --pipeline-type llm_javelin_models_performance_bare_metal`. This should hang on the Mamba test in a similar way to the pipeline linked above.

# Further Investigation

Reproducing this issue requires the Falcon7B tests to run before the Mamba ones. Reordering the Mamba and Falcon7B tests with a fresh build does not seem to also trigger a hang.

It appears that the hang is related to the persistent program cache, since disabling the persistent cache in the Mamba tests can get it to pass - even if Falcon7B ran previously.

The logs point to `ShardedToInterleaved` as the op where we are hanging:

```bash
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::to_memory_config
                     Op | DEBUG    | Launching Operation: "ShardedToInterleaved" (device<Tensors>)
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    |    grid_size = (x=8,y=7)
                     Op | DEBUG    |    sharded_op_type = ShardedOpType::ShardedToInterleaved
                     Op | DEBUG    |    output_mem_config = tt::tt_metal::MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::L1,shard_spec=std::nullopt)
                     Op | DEBUG    |    output_dtype = DataType::BFLOAT8_B
                     Op | DEBUG    | Input Tensors:
                     Op | DEBUG    |    0: tt::tt_metal::Tensor(storage=tt::tt_metal::DeviceStorage(memory_config=tt::tt_metal::MemoryConfig(memory_layout=TensorMemoryLayout::WIDTH_SHARDED,buffer_type=BufferType::L1,shard_spec=tt::tt_metal::ShardSpec(grid={[(x=0,y=0) - (x=7,y=4)]},shape={32, 128},orientation=ShardOrientation::ROW_MAJOR,halo=0))),shape=ttnn.Shape([1, 1, 32, 5120]),dtype=DataType::BFLOAT8_B,layout=Layout::TILE)
                     Op | DEBUG    |
                     Op | DEBUG    | Program Hash: 16324976833888547997 (HIT)
```

**Comment by tt-rkim** [comment]
Is there update to this? Are we just running it manually to get perf numbers?

**Comment by esmalTT** [comment]
> Is there update to this? Are we just running it manually to get perf numbers?

We were never able to replicate this issue locally. There was an FD hang that was fixed this week, it may have been related. 

I would suggest we re-enable this for a few days to see if the issue is still occurring.

**Comment by tt-rkim** [comment]
Looks like it hung: https://github.com/tenstorrent/tt-metal/actions/runs/9407769341/job/25914428732

It seems that `tt_cache_path` is still set to `None` though unless I'm reading the code wrong... so it can't be a cache problem?

**Comment by esmalTT** [comment]
Is it possible we are just timing out?
________________________________
From: Raymond Kim ***@***.***>
Sent: Thursday, June 6, 2024 7:28:59 PM
To: tenstorrent/tt-metal ***@***.***>
Cc: Evan Smal ***@***.***>; Author ***@***.***>
Subject: [CAUTION - External Sender] Re: [tenstorrent/tt-metal] Mamba end-to-end perf hanging in CI pipelines (Issue #8606)


Looks like it hung: https://github.com/tenstorrent/tt-metal/actions/runs/9407769341/job/25914428732<https://www.google.com/url?q=https://github.com/tenstorrent/tt-metal/actions/runs/9407769341/job/25914428732&source=gmail-imap&ust=1718321340000000&usg=AOvVaw23IAmbvovRU0O7WHTwD7XQ>

It seems that tt_cache_path is still set to None though unless I'm reading the code wrong... so it can't be a cache problem?

**Comment by tt-rkim** [comment]
<img width="691" alt="Screenshot 2024-06-07 at 8 38 38 AM" src="https://github.com/tenstorrent/tt-metal/assets/109366641/2e4a2359-0809-4a89-9cf2-eab86d29e7fd">

Maybe, but is this supposed to take over 15 mins on such a powerful BM like this?

**Comment by tt-rkim** [comment]
bumped up to 40 min to see if we need more time https://github.com/tenstorrent/tt-metal/actions/runs/9419004292

**Comment by tt-rkim** [comment]
@esmalTT Looks like it took 4 mins on the Single-card BM.
Running a couple more times, but my initial guess is that it's ND hanging.

**Comment by esmalTT** [comment]
@tt-rkim Yeah looks like it 🥲

**Comment by esmalTT** [comment]
I added some more information to the issue description. In short, I think the issue is persistent program cache. 

I would suggest that we disable persistent program cache in the Mamba perf test so that we can re-enable it in CI.

**Comment by uaydonat** [comment]
@tt-rkim 

As per our discussion in https://github.com/tenstorrent/tt-metal/issues/9137,
is the `built` folder cached between different CI runs?

**Comment by esmalTT** [comment]
I believe that Falcon7B and Mamba performance tests live in the same CI run:

https://github.com/tenstorrent/tt-metal/blob/62ff3d0b04c077c46242db491db885070f9bd19c/tests/scripts/run_performance.sh#L32C1-L46C2

**Comment by uaydonat** [comment]
I am thinking this is fine, the problem happens when we do `git pull`, kernels may change but the kernel-cache is not invalidated (need to delete built folder), so using old kernels with the new stack.

**Comment by esmalTT** [comment]
The issue seems to be in `ShardedToInterleaved`. I will try to isolate the issue and create a test case.

**Comment by esmalTT** [comment]
I've opened #9405 to track the bug causing this hang. I will plan to close this issue in a few days if the pipelines seem stable with the workaround (disabling persistent kernel cache).

**Comment by esmalTT** [comment]
Workaround seems to be holding up on CI. Closing this and tracking the root cause in #9405.
