### ISSUE TITLE
TTNN test failures

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#8620]

**Comment by vtangTT** [comment]
These tests are failing: https://github.com/tenstorrent/tt-metal/actions/runs/9120504571
`tests/ttnn/unit_tests/test_reports.py`
`tests/ttnn/unit_tests/test_print_tensor.py` 

Top level issue: https://github.com/tenstorrent/tt-metal/issues/8579

**Comment by vtangTT** [comment]
for `tests/ttnn/unit_tests/test_reports.py::test_enable_logging_and_enable_detailed_buffer_report` looks like it's not create the `buffers` database properly..?

**Comment by vtangTT** [comment]
fixed: https://github.com/tenstorrent/tt-metal/actions/runs/9199328999

ty! @arakhmati
