### ISSUE TITLE
Support for UINT8 DataType

### ISSUE THREAD

**Issue by dongjin-na** [tenstorrent/tt-metal#8630]
**Is your feature request related to a problem? Please describe.**
- Implementing the GenerateRandomBitMask operation requires using a bitmask tensor with the UINT8 data type.
- Currently, the tt_eager library does not support the UINT8 data type, making it impossible to create tensors of this type. The code snippet below illustrates this limitation.
```
// tt_eager/tensor/types.hpp
enum class DataType {
    BFLOAT16 = 0,
    FLOAT32 = 1,
    UINT32 = 2,
    BFLOAT8_B = 3,
    BFLOAT4_B = 4,
    UINT16 = 6,
    INT32 = 7,
    INVALID = 8,
};
```
``` 
# example to create UINT8 tt tensor
def test_uint8_tensor(device):
    npu_dtype = ttl.tensor.DataType.UINT8
    cpu_dtype = torch.uint8
    npu_layout = ttl.tensor.Layout.TILE
    input = torch.randint(0, 128, (32, 32), dtype=cpu_dtype)
    tt_input = ttl.tensor.Tensor(input, npu_dtype).to(npu_layout).to(device)
# E       AttributeError: type object 'tt_lib.tensor.DataType' has no attribute 'UINT8'
```

**Describe the solution you'd like**
- We propose adding the UINT8 enum value to the DataType enum class, along with the necessary support in related code to handle this data type.

**Additional context**
- Our primary use case for the UINT8 data type tensor is **only within a data movement kernel.**

**Comment by razorback3** [comment]
@jliangTT
Could you find appropriate assignee for this issue?
This is very similar to issue #5472. It does not require any llk changes.

**Comment by sangwon-chae** [comment]
@arakhmati Hi, would you please share the current status?

**Comment by jvasilje** [comment]
@sangwon-chae can you use UINT16 for now? 
Is this a blocker?

**Comment by eyonland** [comment]
Is it possible to just use UINT16 here?
Also, what is the use-case needed?

**Comment by razorback3** [comment]
We could go on with UINT16 but it will make our code messy.
I know we have to weigh between the importance of the issue and the complexity of a solution.

To the best of my knowledge, this issue requires simple changes exactly the same as #7424 (https://github.com/tenstorrent/tt-metal/pull/7424/files). The only difference is that int32 should be changed to uint8.

If the Metal team is busy with other issues, I do not mind Moreh raising PR for this issue and the Metal team to review it.

**Comment by razorback3** [comment]
We could go on with UINT16 but it will make our code messy.
I know we have to weigh between the importance of the issue and the complexity of a solution.

To the best of my knowledge, this issue requires simple changes exactly the same as #7424 (https://github.com/tenstorrent/tt-metal/pull/7424/files). The only difference is that int32 should be changed to uint8.

If the Metal team is busy with other issues, I do not mind Moreh raising PR for this issue and the Metal team to review it.

@jvasilje

**Comment by sangwon-chae** [comment]
@jvasilje Please let us know your feedback regarding Jaehoon's comment.

**Comment by arakhmati** [comment]
@sangwon-chae @razorback3 you can guys can go ahead and implement it. Just make sure to update unit tests here: tests/tt_eager/python_api_testing/unit_testing/misc/test_tensor.py
