### ISSUE TITLE
Conv layer (low PCC) in yolov4 Head module

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#8640]
Reproducible script for the Conv failing case is at the branch:
https://github.com/tenstorrent/tt-metal/compare/main...ankit/head_c11_unittest

Please checkout to the branch and
execute the unit test file.

```
git checkout ankit/head_c11_unittest
pytest tests/ttnn/unit_tests/operations/test_conv_head_c11_yolov4.py 
```

We are currently getting Low PCC (0.6444111739627862).

Expected behavior: To achieve PCC of close to 0.99

**Comment by tt-rkim** [comment]
@mbahnasTT Can you explain why this is P0 now?

**Comment by mbahnasTT** [comment]
We are going to sync more with Jasmina and Sid on pumping the priority of some customer models, so this issue is among the ones that will enable the high priority customer models.

**Comment by tt-rkim** [comment]
OK no problem. Please update this soon with an explanation when you have it. Thank you.

**Comment by punithsekar** [comment]
Note: The unit test branch is up to date https://github.com/tenstorrent/tt-metal/compare/main...ankit/head_c11_unittest.

**Comment by tt-rkim** [comment]
@mbahnasTT @dvartaniansTT how is this going?

**Comment by punithsekar** [comment]
The head sub-module works fine for yolov4 model, PCC > 0.99 in new conv API.
Hence, closing this issue. Please refer PR #10068 for implementation of head sub_module using new conv API(ttnn.conv2d) with PCC>0.99.
