### ISSUE TITLE
Add asan build to CMake

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#8643]
We originally had asan build with make flow, would be good to have for cmake as well to help debug memory issues.
asan for whole build is fine (what we originally had for make as well).

I also wasn't able to get asan build to work with running python tests when using the make flow, was only able to run c++ tests. Not sure if that was expected/if I was missing/doing something wrong. Would be nice if we could figure out how to get it working but not a requirement.

**Comment by TT-billteng** [comment]
This can be achieved manually with CMake as follows:

```
cmake -B build -G Ninja -DCMAKE_CXX_FLAGS="-fsanitize=address -g" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address"
cmake --build build --target install
```

**Comment by yan-zaretskiy** [comment]
> Still currently not sure if we should add a CMake option to do this automatically for user.

We totally should, IMHO.

**Comment by tt-rkim** [comment]
Probably an interface target with those flags that we attach to another common interface lib used in all libs/tests, that's default off but on if an option is set?

`cmake -B build -GNinja -DBUILD_ASAN`?

**Comment by TT-billteng** [comment]
closing in favor of #11453
