### ISSUE TITLE
Implement Argmax OP on RISC-V, as a data movement kernel

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#8662]
**Is your feature request related to a problem? Please describe.**

Currently, argmax returns a bfloat16 type. Recently, I discovered a serious bug due to argmax returning a bfloat16 type.
https://github.com/tenstorrent/tt-metal/pull/8202#discussion_r1604618288

In a tensor that is originally of a floating type, decimal errors do not significantly impact the results. However, errors in a tensor used for indexing can lead to completely different outcomes. For example, in a classification problem where the decision is between "road" and "car", an error in the index could lead to a wrong judgment between a car and a road, potentially causing a car accident.

The test case where the problem occurs is as follows:

file: https://github.com/tenstorrent/tt-metal/blob/main/tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_argmax_padding.py
input_shape: torch.Size([5, 4, 3, 20])
dim: 3
all: True
In this case, the correct value returned by torch is 1025, but tt is returning 1024. This seems to be an issue because the output dtype is bfloat16.

Below issue also appears to have arisen because the output is in bfloat16.
https://github.com/tenstorrent/tt-metal/issues/4787

**Describe the solution you'd like**

Goals:
1. Need to change argmax to return a signed integer type.
- The reason we need a signed output type is to match the behavior of PyTorch's argmax.
- https://pytorch.org/docs/stable/generated/torch.argmax.html

2. Need to modify the atol and rtol to 0 in the following test code and ensure the test passes.
-  https://github.com/tenstorrent/tt-metal/blob/main/tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_argmax_padding.py#L56

**Comment by umadevimcw** [comment]
@hschoi4448 For BF16 conversion even in pytorch there is loss in data after bf16 to float conversion. Please find the attached image
<img width="1014" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/29221091/0e1647c8-2583-4180-b482-6298767dba46">

**Comment by umadevimcw** [comment]
@tt-aho Do you have any idea on how to store int data in owned buffer without any loss in data and use it for computation?

Below is the module used for index calculation in argmax/armgin implementation. You can find this in `functions.hpp` files

```
template <typename T>
static Tensor index_all(
    const Shape& shape,
    DataType data_type,
    const Layout layout = Layout::ROW_MAJOR,
    Device* device = nullptr,
    const MemoryConfig& output_mem_config = MemoryConfig{
        .memory_layout = tt::tt_metal::TensorMemoryLayout::INTERLEAVED}) {
    auto owned_buffer = tt_metal::owned_buffer::create<T>(tt_metal::compute_volume(shape));
    std::fill(owned_buffer.begin(), owned_buffer.end(), -std::numeric_limits<float>::infinity());
    auto& up_shape = shape.without_padding();
    auto index = 0;
    auto value = 0;
    auto rank = up_shape.rank();
    auto penultimate = rank - 2;
    auto ultimate = rank - 1;
    for (uint32_t b = 0; b < up_shape[rank - 4]; b++) {
        for (uint32_t c = 0; c < up_shape[rank - 3]; c++) {
            for (uint32_t y = 0; y < up_shape[penultimate]; y++) {
                for (uint32_t x = 0; x < up_shape[ultimate]; x++) {
                    owned_buffer[index++] = T(static_cast<float>(value));
                    value = value + 1;
                }  // dim W
                index = index + (shape[ultimate] -  up_shape[ultimate]);
            }// dim H
            index = index + ((shape[penultimate] -  up_shape[penultimate]) * tt::constants::TILE_WIDTH);
        }          // dim C
    }              // dim N
    auto output = Tensor(OwnedStorage{owned_buffer}, shape, data_type, Layout::ROW_MAJOR).to(layout);
    if (device != nullptr) {
        output = output.to(device, output_mem_config);
    }
    return output;
}
```

**Comment by hschoi4448** [comment]
> @hschoi4448 For BF16 conversion even in pytorch there is loss in data after bf16 to float conversion. Please find the attached image
> 
> You can `1025` become `1024` same for `257` become `256`
> <img alt="image" width="1014" src="https://private-user-images.githubusercontent.com/29221091/333552180-0e1647c8-2583-4180-b482-6298767dba46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTA5OTYsIm5iZiI6MTcxNjU1MDY5NiwicGF0aCI6Ii8yOTIyMTA5MS8zMzM1NTIxODAtMGUxNjQ3YzgtMjU4My00MTgwLWI0ODItNjI5ODc2N2RiYTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDExMzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYTQ1MDEyNzQ0YzQxYTQxM2YwNDgzZDkwNDM3Y2NkZjBmYzhkYmVmM2Y2Yjg1OWU5YmYyOGViYmU5NTE3YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VGdBhjgGg_qtgHKHs1t5ZciKNJw9bnyE3o3Wbho1Vk">

Yes, the bfloat16 issue also occurs in PyTorch. 
However, since the return type of PyTorch's argmax is a `signed integer`, this problem should not occur. 

How is the above discussion related to the argmax output type?

**Comment by umadevimcw** [comment]
@hschoi4448 Since for index calculation we are using an owned buffer with the BF16 data type there is always a delta of 1 in the index value. Hence I am trying to fix that and int output as well.

**Comment by tt-aho** [comment]
@umadevimcw storing int in owned buffer is fairly trivial. Your function is already templated on tensor dtype, so use INT32 instead of BFLOAT16 and change `std::numeric_limits<float>::infinity()` to `std::numeric_limits<int>::max()`, `static_cast<float>` to `static_cast<int>`. (you can use constexpr expressions based on type to make this generic)

**Comment by umadevimcw** [comment]
Issue similar to this https://github.com/tenstorrent/tt-metal/issues/8540#issuecomment-2141014370

**Comment by eyonland** [comment]
There are three issues: (Note, it is not an eltwise operation)
1. Return tensor should be an integer 
2. The value of the tensor is incorrect
3. Fallback is a composite and one of micro-ops is a fallback.

**Comment by xanderchin** [comment]
The initial integer version of ArgMax has been implemented on riscv with passing tests cases for vectors in this issue.

Unit tests: `pytest  tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_argmax_int.py::TestArgmax::test_argmax`

Current restrictions:
- Limited to the "all" case where the max index of the entire tensor is returned
- Input needs to be `bfloat16` and memory layout needs to be interleaved
- Output is in `uint32`
- Optional output tensors and q_ids are currently not supported. Support planned in #9189 

@hschoi4448 @razorback3 please see Issue #9190 for further discussion
