### ISSUE TITLE
[Bug Report]  'tt_metal/third_party/umd' did not contain 49038c8f92 (wrong repo pointer?)

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#8664]
**Describe the bug**
Failed to update tt-umd during update from and earlier Meralium repo.

I'm updating Metalium so I can try out @vtangTT's code mentioned in #8194. But failing to update. The commit ID seems to come from [tenstorrent/tt-umd](https://github.com/tenstorrent/tt-umd). But git modules is pointing to [tenstorrent-metal/umd](https://github.com/tenstorrent-metal/umd). Can you update repo/close the duplicate/update the pointer?

**To Reproduce**

```
> git submodule update
fatal: remote error: upload-pack: not our ref 49038c8f9246391cbf4edfb6ffef929435588b19
fatal: Fetched in submodule path 'tt_metal/third_party/umd', but it did not contain 49038c8f9246391cbf4edfb6ffef929435588b19. Direct fetching of that commit failed.
```

**Expected behavior**
Should be able to update git submodules.

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by tt-aho** [comment]
Could you try running `git submodule sync`, and then try updating submodules again?

**Comment by marty1885** [comment]
Ah ok. I'm bad at using git. Sorry for the trouble
