### ISSUE TITLE
Op Migration Blockers

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#8680]
LLKs are needed to unblock work from MCW

- [x] #8681
- [x] #8682
- [x] #8683
- [x] #8684
- [x] #4858
- [x] #8945
- [x] #8944

Also in WHB0, comparing positive inf and negative inf/nan is not working. We need guidance for that as well

**Ops depends on Floor** 
- ElemwiseUnary/ELEMWISE_UNARY_FLOORDIV
- ElemwiseBinary/ELEMWISE_BINARY_FLOORDIV
- ElemwiseUnary/ELEMWISE_UNARY_FLOOR
- ElemwiseUnary/ELEMWISE_UNARY_FLOORDIVIDE
- ElemwiseBinary/ELEMWISE_BINARY_FLOORDIVIDE
- ElemwiseUnary/ELEMWISE_UNARY_FRAC
- ElemwiseUnary/ELEMWISE_UNARY_RFLOORDIV
- ElemwiseUnary/ELEMWISE_UNARY_ROUND
- ElemwiseBinary/ELEMWISE_BINARY_FLOOR_MOD
- ElemwiseBinary/ELEMWISE_BINARY_LCM
- ElemwiseBinary/ELEMWISE_BINARY_GCD

**Ops depends on Shift** 
- ElemwiseBinary/ELEMWISE_BINARY_BITWISEAND
- ElemwiseBinary/ELEMWISE_BINARY_BITWISEOR
- ElemwiseBinary/ELEMWISE_BINARY_BITWISEXOR
- ElemwiseUnary/ELEMWISE_UNARY_BITWISENOT
- ElemwiseUnary/ELEMWISE_UNARY_BITWISEOR
- ElemwiseUnary/ELEMWISE_UNARY_BITWISEXOR
- ElemwiseUnary/ELEMWISE_UNARY_BITWISEAND
- ElemwiseBinary/ELEMWISE_BINARY_LEFT_SHIFT
- ElemwiseUnary/ELEMWISE_UNARY_LEFT_SHIFT
- ElemwiseBinary/ELEMWISE_BINARY_RIGHT_SHIFT
- ElemwiseUnary/ELEMWISE_UNARY_RIGHT_SHIFT
- ElemwiseUnary/ELEMWISE_UNARY_INVERT
- ElemwiseUnary/ELEMWISE_UNARY_CEIL

**Ops depends on Mod**
- ElemwiseBinary/ELEMWISE_BINARY_REMAINDER
- ElemwiseUnary/ELEMWISE_UNARY_REMAINDER
- Tan (need to use it for reduction technique)

**Ops depends on Trunc** 
- ElemwiseBinary/ELEMWISE_BINARY_DIVTRUNC
- ElemwiseUnary/ELEMWISE_UNARY_DIVTRUNC
- ElemwiseUnary/ELEMWISE_UNARY_RDIVTRUNC
- ElemwiseUnary/ELEMWISE_UNARY_TRUNC
- ElemwiseUnary/ELEMWISE_UNARY_FMOD
- ElemwiseBinary/ELEMWISE_BINARY_FMOD

**Comment by umadevimcw** [comment]
@rtawfik01 Please find the PR where we have included the skeleton of the above required 4 ops (floor, mod, shift both left and right) and trunc)

**Comment by rtawfik01** [comment]
Hi @umadevimcw. It seems there is possibly conflicting commits? These ones have the wormhole_b0 implementations, and no GS implementations, and also include scaffolding for the operations:
Floor : https://github.com/tenstorrent/tt-metal/pull/8285
Unary left shift : https://github.com/tenstorrent/tt-metal/pull/8712
Unary Right Shift : https://github.com/tenstorrent/tt-metal/pull/8921

While these only have the scaffolding of the operations?
Floor : https://github.com/tenstorrent/tt-metal/commit/7e6076d299fc893b14dd12151603bd5ef007e1fb
Unary left shift : https://github.com/tenstorrent/tt-metal/commit/44c1dd3f4ecdfcedc5d033eca9b0e531f7607d79
Unary Right Shift : https://github.com/tenstorrent/tt-metal/commit/5d5c29253fb13f9509a3302e8edc04ae395afb76

It will be good if we continue down the path of having scaffolding + whb0 implementation when possible, and re-assigning back to me for GS. Also let me know if whb0 implementation is not possible.

**Comment by umadevimcw** [comment]
@rtawfik01 Will share you the PR that has scaffolding for GS and implementations for WHB0

**Comment by VirdhatchaniKN** [comment]
Ops implemented with scaffolding + WH_B0 implementation

- Floor , Trunc : #8285
- Unary left shift : #8712 
- Unary Right Shift : #8921

**Comment by rtawfik01** [comment]
Mod PR is here:  https://github.com/tenstorrent/tt-metal/pull/9365

MCW team will push when ready

**Comment by VirdhatchaniKN** [comment]
Updated List of ops that are to be implemented : 
[Pending op list.pdf](https://github.com/user-attachments/files/15914678/Pending.op.list.-.Pending.Op.List.1.pdf)

**Comment by Aswinmcw** [comment]
Closing as all ops merged to main
