### ISSUE TITLE
Implement mod op

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#8682]
With the help of modulo support we achieve more range in trigonometry function `tan` using range reduction techniques where mod is required 
- we can also achieve basic functions that are supported in pytorch like remainder, fmod, etc..

**Comment by eyonland** [comment]
[MOD issues.pdf](https://github.com/user-attachments/files/15789493/MOD.issues.pdf)

**Comment by rtawfik01** [comment]
Mod PR here: https://github.com/tenstorrent/tt-metal/pull/9365/

MCW team will push when ready

**Comment by VirdhatchaniKN** [comment]
Unary MOD : #9365 - Merged to main
Binary MOD : #9391 - Merging to main
for WH_B0

**Comment by VirdhatchaniKN** [comment]
Closing this issue as WH_B0 implementation is merged to main - Comment [Link](https://github.com/tenstorrent/tt-metal/issues/8684#issuecomment-2148713843)
