### ISSUE TITLE
[Blackhole bringup] Writing GO signal in stream registers

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#8703]
Metal does not use stream registers, so these can be repurposed as space to write GO signal. 

On GS/WH BRISC does 1 write to L1 when writing GO signal for NCRISC/TRISC. 

TODO:
- Confirm whether writes to stream regs are byte addressable otherwise BRISC will need to do multiple writes for GO. 
- Investigate sets available in register map to confirm there is a contiguous block that can be used

**Comment by abhullar-tt** [comment]
BTW @pgkeller writes to registers are not byte addressable, writes will write to entire register

**Comment by pgkeller** [comment]
I lean towards keeping this in L1 and using mem flush/invalidates rather then regs, this also improves visibility w/ watcher

**Comment by abhullar-tt** [comment]
> I lean towards keeping this in L1 and using mem flush/invalidates rather then regs, this also improves visibility w/ watcher. That is, if it is doable...

why would this not be do-able? is the worry here issues that will arise due to synchronization issues with L1 cache?

**Comment by pgkeller** [comment]
> > I lean towards keeping this in L1 and using mem flush/invalidates rather then regs, this also improves visibility w/ watcher. That is, if it is doable...
> 
> why would this not be do-able? is the worry here issues that will arise due to synchronization issues with L1 cache?

should be doable - we just need to know what the full list of primitives available is

**Comment by abhullar-tt** [comment]
Closing this since opting towards keeping GO signals in L1
