### ISSUE TITLE
ttnn implementation for segformer_b0 model

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#8717]
reference implementation for segformer_b0: https://huggingface.co/docs/transformers/en/model_doc/segformer

To implement ttnn model, starting with sub-module implementation, testing and then the whole model.

**Comment by punithsekar** [comment]
Torch interpolate is used in segformer semantic segmentation sub-module.

**Comment by punithsekar** [comment]
Closing this issue, Since Segformer is in main.
