### ISSUE TITLE
LEI forward op

### ISSUE THREAD

**Issue by mouliraj-mcw** [tenstorrent/tt-metal#8721]
Add LE_ op ( less than or equal to op , in_place operation)

**Comment by umadevimcw** [comment]
https://github.com/tenstorrent/tt-metal/issues/8885#issuecomment-2248268819

**Comment by KalaivaniMCW** [comment]
will be revisited after TTNN migration

**Comment by mouliraj-mcw** [comment]
Closing the issue as it's completed.(#8790)
