### ISSUE TITLE
Enable jit compile for BH

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#8735]
@rtawfik01 `abhullar/bh-compile-fw` has some fixes for initializing UMD on BH and getting to FW compile step. 

Ill merge this to main so you can take a look at resolving the llk errors

**Comment by rtawfik01** [comment]
Merged here: #8809 & #8880.

Once runtime works, more llk compilation might need to be fixed, but we can open separate issues for that
