### ISSUE TITLE
reshard output mismatch

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent/tt-metal#8808]
There's a pcc mismatch on reshard with row major tensors. To reproduce run `pytest -svv "tests/ttnn/unit_tests/operations/test_core.py::test_reshard[input_height=512-input_width=1280-input_memory_layout=Layout.ROW_MAJOR-input_sharded_memory_config_args={'core_grid': ttnn.CoreGrid(x=8, y=4), 'strategy': <ShardStrategy
.BLOCK: 3>}-output_sharded_memory_config_args={'core_grid': ttnn.CoreGrid(x=8, y=8), 'strategy': <ShardStrategy.BLOCK: 3>}-input_override=None-output_override=None]"`

on `aknezevic/reshard_pcc`

**Comment by ntarafdar** [comment]
will be tracked with subsequent reshard sweep .
