### ISSUE TITLE
Perf report CSVs are empty

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#8850]
[perf-report-csv-cnn_javelin-grayskull-bare_metal](https://github.com/tenstorrent/tt-metal/actions/runs/9236940070/artifacts/1537656905) is empty

[Model perf regressions and output report · tenstorrent/tt-metal@36d305b](https://github.com/tenstorrent/tt-metal/actions/runs/9236940070)

![image](https://github.com/tenstorrent/tt-metal/assets/3885633/897772f8-b7d6-4696-8aff-bfc57e562dd5)

**Comment by tt-rkim** [comment]
It's expected to be.

Solution is to prune jobs that are meant to be empty and assert that the CSVs are not empty when uploading
