### ISSUE TITLE
reduce use of events/waits

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#8855]
we presently send events and waits after every EWB, EP.  instead the host should be smart about what was done last and send events lazily when needed, eg, before a EP that was preceeded by an EWB.

**Comment by pgkeller** [comment]
@tt-asaigal is this done?  or can I assign it to you?

**Comment by tt-asaigal** [comment]
We no longer record events after every command type. EWB,EP, ET, etc. bypass this entirely. I think this should be done.

**Comment by pgkeller** [comment]
beautiful, closed
