### ISSUE TITLE
Build fails in SSH 172.27.45.232

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#8867]
Build is failing in SSH 172.27.45.232. 

**To Reproduce**
1. Run the following commands,
`git submodule foreach 'git lfs fetch --all && git lfs pull'`
`export ARCH_NAME=wormhole_b0`
`export TT_METAL_HOME=$(pwd)`
`export PYTHONPATH=$(pwd)`
`export TT_METAL_ENV=dev`
`make nuke`
`./build_metal.sh`
2. The following error will occur,
`ttnn._ttnn: Failed to import, skipping`

**Comment by saichandax** [comment]
VM 172.27.45.232 is released. No longer relevant.
