### ISSUE TITLE
Failing Convs in Segformer_b0 Model 

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#8868]
The following branch contains the failing convs in the segformer_b0 ttnn implementation for resolution 512x512.
[punith/segformer_unit_test_new_conv](https://github.com/tenstorrent/tt-metal/compare/main...punith/segformer_unit_test_new_conv)

We have unit_test for all conv configurations which is invoked in the model.

- To test conv which are failing, use command:` pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_conv_for_segformer_512x512`

Note: I have commented convs which are passing.

Device: WH - n150

**Comment by dvartaniansTT** [comment]
@saichandax please add unit test command as well as system info i,e GS e150 or WH N150 etc ...

**Comment by punithsekar** [comment]
@mywoodstock @dvartaniansTT , I have updated the issue description with unit_test of conv using new conv API.

**Comment by punithsekar** [comment]
(1, 256, 150, 128, 128, 1, 1, 1, 1, 0, 0, 1, True, None, False)

The above config was working fine until yesterday [main](https://github.com/tenstorrent/tt-metal/commit/e6f4c7023b882a46e0ad38bf28cdf9a9d78bb7de). In latest main we face issue the following error:

```
RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp:977: bias_shape.without_padding()[-1] == b_shape[-1]
E       info:
E       Unsupported bias shape: last dimension not equal to second input's last dimension.
E       backtrace:
E        --- ttnn::operations::matmul::Matmul::validate(std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor const>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor const>>> const&) const 
```

Updated the config in [punith/segformer_unit_test_new_conv](https://github.com/tenstorrent/tt-metal/compare/main...punith/segformer_unit_test_new_conv) branch.

**Comment by sankarmanoj-tt** [comment]
@punithsekar It's failing due to [this change.](https://github.com/tenstorrent/tt-metal/commit/7cd61f48619c12fd655ec1d046e438df3aa29069)

**Comment by punithsekar** [comment]
@sankarmanoj-tt ,
(1, 256, 150, 128, 128, 1, 1, 1, 1, 0, 0, 1, True, None, False)

The above test_case still fails with error, 

```
RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp:977: bias_shape.without_padding()[-1] == b_shape[-1]
E       info:
E       Unsupported bias shape: last dimension not equal to second input's last dimension.
E       backtrace:
E        --- ttnn::operations::matmul::Matmul::validate(std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor const>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor const>>> const&) const 
```
In the `test_conv_for_segformer_512x512` method in `test_new_conv2d.py` file which you pushed to main has   `has_bias=False` that's why we didn't face that issue in your unit_test. But we need with has_bias=True.

**Comment by sankarmanoj-tt** [comment]
This has been fixed in the branch [`smanoj/segformer_bias_fix`](https://github.com/tenstorrent/tt-metal/tree/smanoj/segformer_bias_fix)

**Comment by punithsekar** [comment]
@sankarmanoj-tt , When we can expect the branch on main?

**Comment by mywoodstock** [comment]
@sankarmanoj-tt is this done?

**Comment by mywoodstock** [comment]
this has been merged.
