### ISSUE TITLE
ttnn.as_tensor does not place DeviceMesh tensors on device when it generates them

### ISSUE THREAD

**Issue by yieldthought** [tenstorrent/tt-metal#8895]
`ttnn.as_tensor` does not work properly with device_mesh:
1. The first time the cache is generated, the tensor is left on the host. Loading the tensor from cache places it on device.
2. Calling the returned tensor.device() works, but the device that is returned auto-closes the device on its destruction.

I've added a unit test for this on branch 8895-as-tensor-device-mesh that currently fails. It can be tested with:

`pytest tests/ttnn/unit_tests/test_as_tensor.py::test_as_tensor_with_device_mesh[silicon_arch_name=wormhole_b0-silicon_arch_wormhole_b0=True-width=3-height=7]`

**Comment by cfjchu** [comment]
Fix merged into main
