### ISSUE TITLE
T3000 program cache corruption

### ISSUE THREAD

**Issue by mtairum** [tenstorrent/tt-metal#8902]
On a T3000 using `t3k_device_mesh` and with program cache enabled, some ops are outputing empty tensors.

This was observed in Mixtral attention test: `models/demos/t3000/mixtral8x7b/tests/test_mixtral_attention.py`, but it's likely also affecting other models such as Llama.

For the mixtral case, in the attention module (`models/demos/t3000/mixtral8x7b/tt/mixtral_attention.py`), key slicing using the ttlib op `nlp_kv_cache_load_slice` leads to bad PCC if program cache is enabled. Changing to the slicing below fixes PCC for 1 iteration, but on 2nd iteration onwards the mismatch continues, so there is a different op/tensor getting corrupted by program cache.

```
# values_1BPD = ttnn.experimental.tensor.nlp_kv_cache_load_slice(values_1BPD, seq_len_start=0, seq_len_end=padded_layer_past_len)

values_1BPD = values_1BPD[:, :, :padded_layer_past_len, :]
```

**Comment by mtairum** [comment]
This is related to issue: https://github.com/tenstorrent/tt-metal/issues/7159

Deleting the attention input and mask after pushing to model fixes the PCC issue, in conjunction with the slice fix in the description.

**Comment by caixunshiren** [comment]
Similar problem with kv_cache load slice op was found on Llama 2. After more debugging I found a bug in the override runtime args in the op. I've added the fix in this commit `bb73b8033b2d21ac398b670530910473c66a89cc` and it worked for llama2. Please try it on Mixtral. Thanks!

**Comment by caixunshiren** [comment]
Merged the fix into main. Please cherry pick the commit from main branch to avoid merge conflict on latest main, or try rebase. 

commit: 65c68109b25d4809657d6ff24885b44c28125b3d

**Comment by mtairum** [comment]
Fix merged: https://github.com/tenstorrent/tt-metal/pull/8928
