### ISSUE TITLE
Add Slack Notifications to T3000 tests

### ISSUE THREAD

**Issue by dimitri-tenstorrent** [tenstorrent/tt-metal#8904]
Use @tapspatel as the owner of the pipeline.

https://github.com/tenstorrent/tt-metal/actions/runs/9268903614/workflow

**Comment by tapspatel** [comment]
you can do it for all [T3K] pipelines
https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml
https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-frequent-tests.yaml
https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-model-perf-tests.yaml
https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-profiler-tests.yaml
https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml
