### ISSUE TITLE
Page Size error in Swin_s model

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#8926]
**Describe the bug**
On testing the Shifted Window Attention submodule of Swin_s functional model, while testing the features.1.0 block of Swin_s model having parameters as dim = 96, num_heads = 3, facing the error:
```
E       RuntimeError: TT_FATAL @ ../tt_metal/impl/buffers/buffer.cpp:31: valid_page_size
E       info:
E       For valid non-interleaved buffers page size 6 must equal buffer size 1012. For interleaved-buffers page size should be divisible by buffer size
```
To note, the error is not faced while testing the features.3.0 block where the parameters are dim = 192, num_heads = 6.
**The same issue is observed in whole model pipeline after integrating the modules, in issue: [9011](https://github.com/tenstorrent/tt-metal/issues/9011)** 

**To Reproduce**
1. Checkout to the branch [harini/shiftattention_pagesize](https://github.com/tenstorrent/tt-metal/compare/harini/shiftattention_pagesize)
2. Run the command: `pytest tests/ttnn/integration_tests/swin_s/test_ttnn_shifted_window_attention.py`

**Expected behavior**
Expected to run model without getting the error for specified parameters.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: GS

**Comment by punithsekar** [comment]
Closing this issue since, We don't face this issue in recent implementation of shiftedWindowAttention of swin_s.
