### ISSUE TITLE
Clean up profiler python_env build flow

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent/tt-metal#8943]
No need for profiler to ask for the python_env folder under the build folder. 

https://github.com/tenstorrent/tt-metal/blob/0c829a3d5eb0a1daaa1d7a340bb1b9d0ee70a55b/scripts/build_scripts/build_with_profiler_opt.sh#L25

Failing tests should be updated to not care about this.  

e.g.
https://github.com/tenstorrent/tt-metal/blob/0c829a3d5eb0a1daaa1d7a340bb1b9d0ee70a55b/tests/scripts/run_profiler_regressions.sh#L57

**Comment by mo-tenstorrent** [comment]
@tapspatel

**Comment by vtangTT** [comment]
https://github.com/tenstorrent/tt-metal/pull/8949 fix in main
