### ISSUE TITLE
Provide guidance on handling cases where -0.0 cannot be calculated on device

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#8944]
Status: The tests will be updated to reflect an expected failure condition and this ticket will be referenced.  @ttmtrajkovic and team will also be adding documentation.

See #7749  and  #6728

Also in WHB0, comparing positive inf and negative inf/nan is not working. We need guidance for that as well

**Comment by ttmtrajkovic** [comment]
Number -0.0 cannot be produced as part of FPU ops (matrix multiply, eltwise add (add_tiles), eltwise mul (mul_tiles), while sfpu ops should be able to produce -0.0. 
Value of -0.0 should be able to get preserved if no conversion to bfloat8 (block-float) is done. bfloat16 should be able to preserve and carry -0.0 around

Could you please list the problem you were seeing with not having -0.0?

**Comment by ttmtrajkovic** [comment]
NaN and +/- infinity numbers are only detected through sfpu (there's a sticky flag that says NaN / infinity seen). NaN / inf as inputs of operands will be treated as any other number and math operation will be done regardless of any special handling. 

if FPU ops are used - add_tiles, mul_tiles or matmul_tiles, then some special handling of Inf operands is going to be OK, others are just treated as regular inputs and results are unpredictable:


±Infinity × ±Infinity​ | ±Infinity​
-- | --
±finite × ±Infinity​ | ±Infinity​
Infinity + Infinity​ | +Infinity​
-Infinity – Infinity​ | – Infinity​

With SFPU ops, any special handling with regards to these numbers should be added explicitly, by the designed.

Doing any math with NaN / inf isn't likely to produce good and reliable results so no support for that has been added in TT hardware. With the ability to detect NaN / Inf numbers in sFPU ops, the programmer has the ability to see that somewhere in the calculations NaN / inf has been found and discard results (or work on fixing them not to appear).

**Comment by ttmtrajkovic** [comment]
@eyonland, who should read this answer and get guidance?

**Comment by eyonland** [comment]
@umadevimcw / @razorback3,  see comments.
