### ISSUE TITLE
Reshard Error in RN-50 for b20 

### ISSUE THREAD

**Issue by shwetankTT** [tenstorrent/tt-metal#8952]
Config is mentioned here
Tensor Details: --> shape=Shape([1, 1, 62720, 64]), dtype=DataType::BFLOAT16, layout=Layout::ROW_MAJOR

Input Config: `tt::tt_metal::MemoryConfig(memory_layout=TensorMemoryLayout::HEIGHT_SHARDED,buffer_type=BufferType::L1,shard_spec=tt::tt_metal::ShardSpec(grid={[(x=0,y=0) - (x=7,y=7)]}, shape={980, 64}, orientation=ShardOrientation::ROW_MAJOR, halo=false))`

Output Config
`
tt::tt_metal::MemoryConfig(memory_layout=TensorMemoryLayout::HEIGHT_SHARDED,buffer_type=BufferType::L1,shard_spec=tt::tt_metal::ShardSpec(grid={[(x=0,y=0) - (x=7,y=6)]}, shape={1120, 64}, orientation=ShardOrientation::ROW_MAJOR, halo=false))
`

Error detals.
```
E           RuntimeError: TT_THROW @ ../tt_metal/impl/kernels/kernel.cpp:220: tt::exception
E           info:
E           1760 Bytes unique+common runtime args targeting kernel reshard_reader on (x=0,y=0) are too large. Cannot be written as they will run into memory region reserved for result. Max allowable size is 1024 Bytes
```

**Comment by tt-aho** [comment]
@shwetankTT do you want to try cherry-picking this commit and seeing if it works? (I haven't looked into optimizing perf much for this, but this should be performant unless there are congestion issues)
[bf4ebf8db39b7136dc2a8b3af4a0533cbe7e6f7e](https://github.com/tenstorrent/tt-metal/commit/bf4ebf8db39b7136dc2a8b3af4a0533cbe7e6f7e)

**Comment by shwetankTT** [comment]
@tt-aho Yeah your commit seems good. Can you please merge it.

**Comment by tt-aho** [comment]
@shwetankTT this is merged now

**Comment by tarafdarTT** [comment]
Closing issue, thanks @tt-aho
