### ISSUE TITLE
Failing tests on Galaxy

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent/tt-metal#8953]
From CPP gtests suite `CommandQueueSingleCardFixture`, running on all 8 chips for one gateway chips, these are failing:

HANGING:
- `CommandQueueSingleCardFixture.TestWrapHostHugepageOnEnqueueReadBuffer`
- `CommandQueueSingleCardFixture.TestIssueMultipleReadWriteCommandsForOneBuffer`
- `CommandQueueSingleCardFixture.TestWrapCompletionQOnInsufficientSpace`
- `CommandQueueSingleCardFixture.TestWrapCompletionQOnInsufficientSpace2`

Event ID Mismatch, seems to happen on tunnel depth 3 chip:
- `CommandQueueSingleCardFixture.WritesToRandomBufferTypeAndThenReadsBlocking`
- `CommandQueueSingleCardFixture. ShardedBufferReadWrites`
- `CommandQueueSingleCardFixture. ShardedBufferLargeReadWrites`

**Comment by ubcheema** [comment]
Fixes pushed to `galaxy/main` for these two kinds of failures.
Tests don't hang or fail anymore.
