### ISSUE TITLE
[Feature Request] Support signed integer index for moreh_getitem

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#8976]
`moreh_getitem` takes a signed integer tensor as the index tensor.

**Comment by sangwon-chae** [comment]
@adifrancescoTT There is no assignee regarding this issue.

**Comment by hschoi4448** [comment]
> @adifrancescoTT There is no assignee regarding this issue.

My mistake. I'm handling this issue. (https://github.com/tenstorrent/tt-metal/pull/8978)

@sangwon-chae @adifrancescoTT
