### ISSUE TITLE
CI frequent Tests fail on Falcon40b

### ISSUE THREAD

**Issue by djordje-tt** [tenstorrent/tt-metal#9005]
Falcon40b CI frequent tests fail when ran after mixtral and llama tests: [CI link](https://github.com/tenstorrent/tt-metal/actions/runs/9314923091/job/25640205091)

Falcon40b tests are at the beginning of CI tests, everything passes: [CI link](https://github.com/tenstorrent/tt-metal/actions/runs/9317651097/job/25648518753)

**Comment by djordje-tt** [comment]
fyi @tapspatel

**Comment by skhorasganiTT** [comment]
Same issue occured on the t3k demo pipeline: 
Running Mixtral before Falcon7b caused the Falcon7b output to be garbage: https://github.com/tenstorrent/tt-metal/actions/runs/9323064847
Running Mixtral after Falcon7b passed (and Mixtral output looked okay): https://github.com/tenstorrent/tt-metal/actions/runs/9323275631

cc @mtairum

**Comment by skhorasganiTT** [comment]
Possibly related to #8965

**Comment by mtairum** [comment]
Yeah, it seems somewhat related to #8965. I think for now just change the order of the tests as mixtral at the end looks unafected.

**Comment by mtairum** [comment]
Looking into this. 

The issue is somewhere on the Mixtral MoE module. Will run some of its ops isolated with falcon40b and triage the source of the problem.

**Comment by mtairum** [comment]
The issue seems to be related to topK op. You can replicate this locally. Only when resetting the device this issue goes away.

If you run the following test before falcon40b decode test you should see a falcon40b decoder PCC output of `PCC: 0.8449`.

My runs were:

1. `pytest models/demos/t3000/mixtral8x7b/tests/test_mixtral_falcon_pcc.py`
2. `pytest models/demos/t3000/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-8chips]`


```
import torch
import ttnn

def test_mixtral_moe_inference(t3k_device_mesh, use_program_cache, reset_seeds):
    gate_shape = [1,1,32,64]
    gate_torch = torch.randn(gate_shape)
    gate_logits_1SB8 = ttnn.from_torch(
        gate_torch,
        dtype=ttnn.bfloat16,
        layout=ttnn.TILE_LAYOUT,
        memory_config=ttnn.L1_MEMORY_CONFIG,
        device=t3k_device_mesh,
        mesh_mapper=ttnn.ReplicateTensorToMesh(t3k_device_mesh),
    )
    topk_values, topk_indices = ttnn.experimental.operations.primary.topk(gate_logits_1SB8, 32)

```

**Comment by mtairum** [comment]
Created related issue #9206

**Comment by uaydonat** [comment]
I am curious how this was only caught in CI and not before pushing and how we can improve our process. 

Is it because when we push a change to mixtral (for example), we only test mixtral and we do not run the pull pipelines?

**Comment by mtairum** [comment]
I often overlook if other tests are failing when running our CI tests, as long as the model with added changes are passing.

Typically just do a quick glance at the pipelines to check if it was showing red recently but that's about it. 
Going forward I'll be more diligent in pinging other model owners when we see their tests failing.

**Comment by uaydonat** [comment]
Yeap, this is understandable. This is a tough bug. 

Probably everybody needs to pay more attention to this. We will talk about it in the group meeting.
