### ISSUE TITLE
Runtime Error: Preprocess_model fails with valid_page_size error

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#9011]
**Describe the bug**
On testing the SwinTransformer module (i.e. Swin_s model pipeline), facing valid_page_size error at preprocess_model function of the module. 

**The same issue we get from ShiftedWindowAttention (submodule of Swin), more details on the issue: [8926](https://github.com/tenstorrent/tt-metal/issues/8926)**

**To Reproduce**
1. Checkout to the branch [harini/swin_shiftattention](https://github.com/tenstorrent/tt-metal/tree/harini/swin_shiftattention)
2. Run the command: `pytest tests/ttnn/integration_tests/swin_s/test_ttnn_swin_transformer.py`

**Expected behavior**
Expected to run preprocess_model without the valid_page_size error.

**Screenshots**
We face the following error when we run the above command.
`
E       RuntimeError: TT_FATAL @ ../tt_metal/impl/buffers/buffer.cpp:31: valid_page_size
E       info:
E       For valid non-interleaved buffers page size 6 must equal buffer size 1012. For interleaved-buffers page size should be divisible by buffer size`

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: GS

**Comment by punithsekar** [comment]
Closing this issue since, We don't face this issue in recent implementation of swin.
