### ISSUE TITLE
Increase frequency of T3K demo tests pipeline

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#9016]
Currently, the T3K demo tests are scheduled to run once a week, however this is insufficient to catch regressions in the model demos. If possible, the frequency should be increased to at least once every couple days.

**Comment by tapspatel** [comment]
thanks, can you paste a green run of the demo pipeline? ill make the change to run every 2 days after that

**Comment by skhorasganiTT** [comment]
Passing pipeline: https://github.com/tenstorrent/tt-metal/actions/runs/9323275631

**Comment by tapspatel** [comment]
reassigning to @ttmchiou . Let me know if you have questions or how to trigger

**Comment by skhorasganiTT** [comment]
FYI @uaydonat, t3k demo pipeline is now more frequent
