### ISSUE TITLE
[Bug Report] cq_id < sw_command_queues_.size() on Readme TTNN example

### ISSUE THREAD

**Issue by ttssokorac** [tenstorrent/tt-metal#9066]
**Describe the bug**
Running the sample TNNN python code from TTNN fails with this error after completing:

```
                 Always | FATAL    | cq_id 0 is out of range
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ ../tt_metal/impl/device/device.cpp:1673: cq_id < sw_command_queues_.size()
info:
cq_id 0 is out of range
backtrace:
 --- tt::tt_metal::Device::command_queue(unsigned long)
 --- tt::tt_metal::detail::DeallocateBuffer(tt::tt_metal::Buffer*)
 --- tt::tt_metal::Buffer::deallocate()
 --- /localdev/ssokorac/work/tt-metal/build/lib/libtt_eager.so(+0x4e5ec4) [0x7f626a975ec4]
 --- /localdev/ssokorac/work/tt-metal/build/lib/libtt_eager.so(+0x4e5c26) [0x7f626a975c26]
 --- /localdev/ssokorac/work/tt-metal/build/lib/libtt_metal.so(+0x10eec7) [0x7f626a395ec7]
 --- tt::tt_metal::Device::push_work(std::shared_ptr<std::function<void ()> >, bool)
 --- /localdev/ssokorac/work/tt-metal/build/lib/libtt_eager.so(+0x4e4f08) [0x7f626a974f08]
 --- tt::tt_metal::Tensor::~Tensor()
 --- /localdev/ssokorac/work/tt-metal/tt_eager/tt_lib/_C.so(+0x1e4252) [0x7f626ad8b252]
 --- /localdev/ssokorac/work/tt-metal/tt_eager/tt_lib/_C.so(+0xd142b) [0x7f626ac7842b]
 --- /localdev/ssokorac/work/tt-metal/tt_eager/tt_lib/_C.so(+0xd0fe4) [0x7f626ac77fe4]
 --- python(_PyModule_ClearDict+0x8ec) [0x5a436c]
 --- python(PyImport_Cleanup+0x2be) [0x67a6ae]
 --- python(Py_FinalizeEx+0x7f) [0x67423f]
 --- python(Py_RunMain+0x32d) [0x6b418d]
 --- python(Py_BytesMain+0x2d) [0x6b43fd]
 --- /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f626bce9083]
 --- python(_start+0x2e) [0x5da67e]
```

I ran this on a standard Buda docker env, on n150, built tt-metal and python env from scratch.

**To Reproduce**

1. Check out 6db0c7d1d22a0ad04a06ed70966f9dfad15933a1
2. Setup env vars from INSTALLING.md and build metal and python env with ./buid_metal.sh and ./create_venv.sh
3. Put the code from "Using TT-NN ops and tensors" section into foo.py
4. Run 'python foo.py'
5. Test runs, print the correct result, then fails with the above error

**Expected behavior**
No error

**Please complete the following environment information:**
git hash: 6db0c7d1d22a0ad04a06ed70966f9dfad15933a1
env: Buda docker (Ubuntu 20.04)

**Additional context**
Thinking about what's unique with my setup, this machine has an unharvested WH, with forced harvesting in FW.

**Comment by tt-rkim** [comment]
I've seen this too - specifically on WH

A lot of the NN examples have been written with only GS in mind because we were only on GS at the time.

This is affecting #8764 

We need to find an owner to fix this bug.

cc: @Shubhamsaboo

**Comment by s-jovic** [comment]
This is the same error reported in https://github.com/tenstorrent/tt-metal/issues/8965 - which is a tensor deallocation issue, you can check out the comments for more information

**Comment by tt-rkim** [comment]
Closing in favour of #8965
