### ISSUE TITLE
[Bug Report] Env `enable_fast_runtime_mode` not working on tt_lib

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#9083]
**Describe the bug**

Recently, an environment variable called enable_fast_runtime_mode was added, and its default value is set to true. When this variable is set to true, operations skip the validation process.

While this value is applied correctly to ttnn functions, it is not applied correctly to tt_lib functions.

ex) tt.exp (o), tt_lib.tensor.exp(x), 

Currently, the tests included in tests/tt_eager/ are implemented using tt_lib, so `no validation is being tested`.

**To Reproduce**
1. Checkout branch: https://github.com/tenstorrent/tt-metal/tree/hyungsuk/enable_fast_runtime_mode_bug
2. Copy below code
```Python
import torch
import ttnn
import time


def test_ttnn():
    device_id = 0
    device = ttnn.open_device(device_id=device_id)

    torch_input_tensor = torch.ones((1,1,32,32), dtype=torch.float32)
    input_tensor = ttnn.from_torch(torch_input_tensor, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)

    # Running the first time will compile the program and cache it
    start_time = time.time()
    output_tensor = ttnn.exp(input_tensor)
    torch_output_tensor = ttnn.to_torch(output_tensor)
    end_time = time.time()
    duration = end_time - start_time
    print(f"duration of the first run: {duration}")

    # Running the subsequent time will use the cached program
    start_time = time.time()
    output_tensor = ttnn.exp(input_tensor)
    torch_output_tensor = ttnn.to_torch(output_tensor)
    end_time = time.time()
    duration = end_time - start_time
    print(f"duration of the second run: {duration}")

    ttnn.close_device(device)

def test_ttlib():
    import tt_lib as tt_lib

    device_id = 0
    device = ttnn.open_device(device_id=device_id)

    torch_input_tensor = torch.ones((1,1,32,32), dtype=torch.float32)
    input_tensor = ttnn.from_torch(torch_input_tensor, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)

    # Running the first time will compile the program and cache it
    start_time = time.time()
    output_tensor = tt_lib.tensor.exp(input_tensor)
    torch_output_tensor = ttnn.to_torch(output_tensor)
    end_time = time.time()
    duration = end_time - start_time
    print(f"duration of the first run: {duration}")

    # Running the subsequent time will use the cached program
    start_time = time.time()
    output_tensor = tt_lib.tensor.exp(input_tensor)
    torch_output_tensor = ttnn.to_torch(output_tensor)
    end_time = time.time()
    duration = end_time - start_time
    print(f"duration of the second run: {duration}")

    ttnn.close_device(device)

test_ttlib()
test_ttnn()
```

3. Set Env Variable
```Python
export TTNN_CONFIG_OVERRIDES='{"enable_fast_runtime_mode": false, "enable_logging": true}'
```
4. Run test
ex) python test.py

**Expected behavior**

The environment variable needs to work correctly with tt_lib functions as well.

**Screenshots**

The screenshot below shows the different application of the enable_fast_runtime_mode value when calling ttnn.exp and tt_lib.tensor.exp.

![image](https://github.com/tenstorrent/tt-metal/assets/48243030/5ab2cc90-3eb1-4ecd-a5cc-7b62d8c6b38c)

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit https://github.com/tenstorrent/tt-metal/tree/hyungsuk/enable_fast_runtime_mode_bug)

**Additional context**

**Comment by arakhmati** [comment]
I re-added validation. Closing the issue
