### ISSUE TITLE
N300 demo issues

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#9092]
**Describe the bug**
I've been testing the demos from main for N300. And, It has not been smooth. There are several issues which I will list here. 

**To Reproduce**
1. from main and commit 0a220d9eff00fdf9bc9641f0ab8573d67bd9b04b
2. Followed the [instrctions from the READMEs per model mentioned here for WH](https://github.com/tenstorrent/tt-metal?tab=readme-ov-file#wormhole-wh-models) and tested on a N300. 

**Errors or issues**

1. READMEs are not up to date with main. 

- mamba mentions building with `make build CONFIG=release` which is no longer supported in main.
- almost all demos tests need to export `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml ` but it is not mentioned in their README.
- The build command in Build and activate step from [here](https://github.com/tenstorrent/tt-metal/blob/main/INSTALLING.md) is not in the correct order. I'd recommend: 
`# If you would like an out-of-the-box virtual environment to use,
./create_venv.sh
source python_env/bin/activate
./build_metal.sh`
 - Mistral required downloading and copying weights to the machine and renaming them. It would be best to automate the download similar to the other models. 
 - I had to reboot the machine several times due to hangs. 

2. Mistral test fails. I will add the exact test command and the fail error as comments attached to this issue.
3. Bert_large fails.  I will add the exact test command and the fail error as comments attached to this issue.
4. mamba passed once but it failed on a second run. I will add the exact test command and the fail error as comments attached to this issue.

**Expected behavior**

1. update the README files to match the latest in main; build requirements, env variable requirements, .... 
2. tests should not fail 
3. weight downloads/data downloads should be automated. 

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- main commit 0a220d9eff00fdf9bc9641f0ab8573d67bd9b04b
- N300

**Comment by dvartaniansTT** [comment]
command:
`WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest --disable-warnings models/demos/metal_BERT_large_11/demo/demo.py::test_demo[models/demos/metal_BERT_large_11/demo/input_data.json-1-batch_7]`

Error:
`================================================================================= ERRORS ==================================================================================
______________________________________ ERROR at setup of test_demo[models/demos/metal_BERT_large_11/demo/input_data.json-1-batch_7] _______________________________________

request = <SubRequest 'device' for <Function test_demo[models/demos/metal_BERT_large_11/demo/input_data.json-1-batch_7]>>, device_params = {}

    @pytest.fixture(scope="function")
    def device(request, device_params):
        import tt_lib as ttl
    
        device_id = request.config.getoption("device_id")
    
>       num_devices = ttl.device.GetNumPCIeDevices()
E       RuntimeError: Cluster Generation with create-ethernet-map Failed!

conftest.py:269: RuntimeError
========================================================================= short test summary info =========================================================================
ERROR models/demos/metal_BERT_large_11/demo/demo.py::test_demo[models/demos/metal_BERT_large_11/demo/input_data.json-1-batch_7] - RuntimeError: Cluster Generation with create-ethernet-map Failed!
====================================================================== 1 error in 1801.38s (0:30:01) ======================================================================
`

**Comment by dvartaniansTT** [comment]
Bert large fails when I try without setting the env variable in the command: 

`(python_env) ttuser@sjc-lab-not3002:~/N300-demosTestsJune3_24/tt-metal$  pytest --disable-warnings models/demos/metal_BERT_large_11/demo/demo.py::test_demo[models/demos/metal_BERT_large_11/demo/input_data.json-1-batch_7]
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.10, pytest-7.2.2, pluggy-1.5.0 -- /home/ttuser/N300-demosTestsJune3_24/tt-metal/python_env/bin/python3
cachedir: .pytest_cache
rootdir: /home/ttuser/N300-demosTestsJune3_24/tt-metal, configfile: pytest.ini
plugins: timeout-2.2.0, split-0.8.2, anyio-4.4.0, dash-2.15.0
timeout: 2400.0s
timeout method: signal
timeout func_only: False
collecting ... 2024-06-04 04:13:06.558 | DEBUG    | ttnn:<module>:139 - Initial ttnn.CONFIG:
{'cache_path': PosixPath('/home/ttuser/.cache/ttnn'),
 'comparison_mode_pcc': 0.9999,
 'enable_comparison_mode': False,
 'enable_detailed_buffer_report': False,
 'enable_detailed_tensor_report': False,
 'enable_fast_runtime_mode': True,
 'enable_graph_report': False,
 'enable_logging': False,
 'enable_model_cache': False,
 'model_cache_path': PosixPath('/home/ttuser/.cache/ttnn/models'),
 'report_name': None,
 'root_report_path': PosixPath('generated/ttnn/reports'),
 'throw_exception_on_fallback': False,
 'tmp_dir': PosixPath('/tmp/ttnn')}
collected 1 item                                                                                                                                                          

models/demos/metal_BERT_large_11/demo/demo.py::test_demo[models/demos/metal_BERT_large_11/demo/input_data.json-1-batch_7]                  Device | INFO     | Opening user mode device driver
  Detecting chips (found 1)
  Chip initialization failed
          (899/900) [15/16] ETH
[5]: Waiting for initial training to complete`

**Comment by dvartaniansTT** [comment]
mistral tests also fails:

run command: 

`WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest --disable-warnings -q -s --input-method=cli --cli-input="Tell me about computers!"  models/demos/wormhole/mistral7b/demo/demo.py` 


`models/demos/wormhole/mistral7b/demo/demo.py                  Device | INFO     | Opening user mode device driver
  Detecting chips (found 1)
  Chip initialization failed
          (899/900) [15/16] ETH
[5]: Waiting for initial training to complete
                                                                                                                                                                           

^CE

================================================================================= ERRORS ==================================================================================
________________________________________________________________ ERROR at setup of test_demo[user_input0] _________________________________________________________________

request = <SubRequest 'device' for <Function test_demo[user_input0]>>, device_params = {}

    @pytest.fixture(scope="function")
    def device(request, device_params):
        import tt_lib as ttl
    
        device_id = request.config.getoption("device_id")
    
>       num_devices = ttl.device.GetNumPCIeDevices()
E       RuntimeError: Cluster Generation with create-ethernet-map Failed!

conftest.py:269: RuntimeError
========================================================================= short test summary info =========================================================================
ERROR models/demos/wormhole/mistral7b/demo/demo.py::test_demo[user_input0] - RuntimeError: Cluster Generation with create-ethernet-map Failed!
====================================================================== 1 error in 1598.45s (0:26:38) ======================================================================
(python_env) ttuser@sjc-lab-not3002:~/N300-demosTestsJune3_24/tt-metal$ 
`

**Comment by dvartaniansTT** [comment]
mamba test passed for me once but on a second try it fails:

command:
`WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest --disable-warnings -q -s --input-method=cli --cli-input="Tell me about computer architecture"  models/demos/mamba/demo/demo.py`


Error:
================================================================================= ERRORS ==================================================================================
______________________________________________________________ ERROR at setup of test_demo[user_input0-100] _______________________________________________________________

request = <SubRequest 'device' for <Function test_demo[user_input0-100]>>, device_params = {}

    @pytest.fixture(scope="function")
    def device(request, device_params):
        import tt_lib as ttl
    
        device_id = request.config.getoption("device_id")
    
>       num_devices = ttl.device.GetNumPCIeDevices()
E       RuntimeError: Cluster Generation with create-ethernet-map Failed!

conftest.py:269: RuntimeError
========================================================================= short test summary info =========================================================================
ERROR models/demos/mamba/demo/demo.py::test_demo[user_input0-100] - RuntimeError: Cluster Generation with create-ethernet-map Failed!
====================================================================== 1 error in 1608.49s (0:26:48) ======================================================================
(python_env) ttuser@sjc-lab-not3002:~/N300-demosTestsJune3_24/tt-metal$ ^C
(python_env) ttuser@sjc-lab-not3002:~/N300-demosTestsJune3_24/tt-metal$ sudo reboot 
[sudo] password for ttuser: 
Connection to 10.230.36.52 closed by remote host.
Connection to 10.230.36.52 closed.
dvartanians@Dalar-Vartanians's-Macbook-Pro yolov4RebasedOrNot %

**Comment by tt-rkim** [comment]
Thanks to @mtairum , we are officially calling the work for mistral for both N150 and N300 completed.

**Comment by tt-rkim** [comment]
@kpaigwar @esmalTT to work on mamba feedback

**Comment by tt-rkim** [comment]
@dvartaniansTT Can you please check that you followed the process properly to clone, build , and install?

you should have been able to clone everything properly with `git submodule update --init --recursive`. `RuntimeError: Cluster Generation with create-ethernet-map Failed!` suggests either a problem with the card, or user clone error. The former is very rare.

**Comment by tt-rkim** [comment]
@esmalTT @kpaigwar mamba ready to reviewed again?

**Comment by esmalTT** [comment]
> @esmalTT @kpaigwar mamba ready to reviewed again?

Yes - just note that:
- We haven't addressed the `RuntimeError: Cluster Generation with create-ethernet-map Failed!` failure because this is an issue with metal, not specific to Mamba. 
- The perf test is still disabled but we are actively looking into it.

**Comment by tt-rkim** [comment]
@esmalTT 

Thanks

I addressed the ethernet map issue above... hopefully @dvartaniansTT has a chance to re-read and re-clone. Certainly either a card or git clone issue

Please remove the perf test or put it in an "under construction" section - think that should help until we can figure out what's going on

**Comment by tt-rkim** [comment]
Can we close this soon?

**Comment by esmalTT** [comment]
> Can we close this soon?

@tt-rkim Sorry, didn't realize this was still open. We can close, the issues with the perf test was fixed a while back.
