### ISSUE TITLE
66207ac breaks ArgMax Test

### ISSUE THREAD

**Issue by tt-asaigal** [tenstorrent/tt-metal#9093]
The following test is failing on CI with bad PCC and is current being skipped:
`pytest -svv tests/ttnn/unit_tests/test_multi_device_async.py::test_multi_device_argmax`

Reverting the entire commit resolved the issue.

Reverting the changes to `composite_ops::_argmax` did not resolve the failure. Seems like something else is broken in one of the ops that was changed. This is a multi-device test that can be run on an N300.

**Comment by KalaivaniMCW** [comment]
Hi @tt-asaigal , it seems like I do not have access to the wormhole machine assigned to us 172.27.28.130. However our team tried running `tests/ttnn/unit_tests/test_multi_device_async.py ` but all the tests were skipped. 

![Screenshot 2024-06-04 at 12 36 55 PM](https://github.com/tenstorrent/tt-metal/assets/156762498/acb8e109-3270-4ed9-a56f-173577879b9a)

![image (56)](https://github.com/tenstorrent/tt-metal/assets/156762498/2596430b-a2b1-4244-84f9-819c63e63f71)

![Screenshot 2024-06-04 at 3 43 07 PM](https://github.com/tenstorrent/tt-metal/assets/156762498/4810d895-0429-4624-8be4-7f90331477bd)

**Comment by tt-asaigal** [comment]
Hey, here is a code snippet providing the equivalent test that can run on a single device (grayskull or wormhole):

```
@pytest.mark.parametrize("layout", [ttnn.TILE_LAYOUT, ttnn.ROW_MAJOR_LAYOUT])
@pytest.mark.parametrize("mem_config", [ttnn.DRAM_MEMORY_CONFIG, ttnn.L1_MEMORY_CONFIG])
def test_single_device_argmax(device, layout, mem_config):
    device.enable_async(True)

    torch.manual_seed(0)
    torch_input = torch.randn(1, 1, 32, 4096)
    reference_output = torch_input.squeeze(1).view(32, 1, -1).float().squeeze().argmax(axis=-1)

    tt_out_11BH = ttnn.from_torch(
        torch_input,
        dtype=ttnn.bfloat16,
        layout=layout,
        device=device,
        memory_config=mem_config,
    )

    tt_out_11BH = ttnn.experimental.tensor.argmax(tt_out_11BH, dim=-1)
    tt_out_1B = ttnn.reshape(tt_out_11BH[:1, :, :, :], ttnn.Shape([1, 32]))
    tt_out_1B = ttnn.to_torch(tt_out_1B)[0]

    assert_with_pcc(tt_out_1B, reference_output, pcc=0.97)

    device.enable_async(False)
```

I ran this on Grayskull with latest main and saw that it just hangs. On Wormhole, I'm seeing asserts and PCC issues.

**Comment by KalaivaniMCW** [comment]
Hi @tt-asaigal , I think there were some issues with argmax and recently it's implementation has been changed. I am not clear on the details as I work on elementwise ops. https://github.com/tenstorrent/tt-metal/issues/9189
@eyonland may have some information on this.

**Comment by KalaivaniMCW** [comment]
Argmax has been implemented as a kernel op in ttnn `ttnn.argmax`
