### ISSUE TITLE
[CI] Adding Llama3 weights to T3K CI machines

### ISSUE THREAD

**Issue by mikevin920** [tenstorrent/tt-metal#9103]
[Here are the insturctions of adding Llama3 weights](https://github.com/tenstorrent/tt-metal/tree/main/models/demos/t3000/llama3_70b)

**Comment by mikevin920** [comment]
@cglagovichTT @caixunshiren @avoraTT

**Comment by tapspatel** [comment]
cc: @tt-rkim 

The ask is to install weights for llama3 onto the t3k CI machines.

1. We have 4 t3k CI runners, user account is ubuntu. The boys keys have been added
2. Current model weights are located in `/mnt/MLPerf/tt_dnn-models/` ex: `/mnt/MLPerf/tt_dnn-models/llama-2/`. You can create an equivalent folder for llama3
3. I usually just set all permissions for everything in the folder to `chmod -R 777`
4. Current way to switching between local path to cached files and ci path is via env variables. Eg you can check: `https://github.com/tenstorrent/tt-metal/blob/main/tests/scripts/t3000/run_t3000_frequent_tests.sh`, for `run_t3000_llama2_70b_tests ` you will see some env var exports `export LLAMA_CKPT_DIR`. However, we want to move away from this, and have the user set the path in their test itself by querying whether the test is running in CI or not. ex: `models/demos/t3000/mixtral8x7b/demo/demo.py` you can see them do this `if os.getenv("CI") == "true":`
5. This user may need to preprocess the weights. The onus is on them to create a branch, run a workflow and trigger the preprocess step. They may have to run it couple of times to ensure it completes (else it will time out)

What is needed from INFRA
You can either give them access to a CI runner or Mo's/ Eyon's machine in the t3k list. All wekas are connected in all t3k machines in Austin colo vpn. Then create a folder for them with appropriate permissions. @mikevin920 can then access and download the weights themselves.

DEV
After files are downloaded, @mikevin920 + team will need to modify their test files to point to correct path and trigger pipeline runs to ensure cache is generate correctly.

**Comment by mikevin920** [comment]
@ttmchiou Hi Michael is there a timeline of giving access to a CI runner to download the weights ourselves?

**Comment by tapspatel** [comment]
I can take over this for now. @mikevin920 pinged you offline

**Comment by tapspatel** [comment]
`/mnt/MLPerf/tt_dnn-models/llama-3` Path created here. Please store files here once you get access to Austin colo vpn. 

You can access one of the t3000 connected machines which all have weka cloud. Access this path and install your weights.

Please reopen if you face any issues
