### ISSUE TITLE
Add Q_ID to ElemwiseBinary/ELEMWISE_BINARY_EQ

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#9109]
Please have two api calls.   
The original api(args...), without the queue_id, that calls the one that requires the queue_id by setting queue_id to 0?
api(args...)
api(queue_id, args...)
This is better than having a default argument for queue_id.

**Comment by ayerofieiev-tt** [comment]
Working on this now.

**Comment by ayerofieiev-tt** [comment]
This PR adds support for queue_id argument in ttnn C++/py.
Please read PR description for details/usage example:
https://github.com/tenstorrent/tt-metal/pull/9071

**Comment by KalaivaniMCW** [comment]
I tested the EQ output in int and here are the results. 
https://docs.google.com/spreadsheets/d/1us0n4F3Sm90IhB07rWP2j-x4ANu8ssehnVGfSUzjMN8/edit?usp=sharing
#9177 adds cq_id support  Binary EQ in tt_lib.

**Comment by ayerofieiev-tt** [comment]
@KalaivaniMCW , thank you! Looks good. Merged now.
