### ISSUE TITLE
Add Q_ID to Typecast

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#9110]
Please have two api calls.   
The original api(args...), without the queue_id, that calls the one that requires the queue_id by setting queue_id to 0?
api(args...)
api(queue_id, args...)
This is better than having a default argument for queue_id.

**Comment by ayerofieiev-tt** [comment]
In progress now

**Comment by ayerofieiev-tt** [comment]
Implemented here
https://github.com/tenstorrent/tt-metal/pull/9146/files

Not merged yet, test found an issue with typecast itself

**Comment by ayerofieiev-tt** [comment]
Completed here
https://github.com/tenstorrent/tt-metal/pull/9146
