### ISSUE TITLE
[Blackhole bringup] LLK reduce compile fails

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#9143]
Repro steps:

1. Checkout `abhullar/bh-bringup`
2. Run `./build_metal.sh`
3. Run `TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/test_reduce_h`

**Comment by abhullar-tt** [comment]
@rtawfik01 assigning this to you for now, feel free to re-assign as you see fit

**Comment by rtawfik01** [comment]
Pushed compile fix here: https://github.com/tenstorrent/tt-metal/pull/9175
but test hangs, you can open an issue for all the hanging tests
