### ISSUE TITLE
Add Optional output tensor and Q_ID support for Prod

### ISSUE THREAD

**Issue by umadevimcw** [tenstorrent/tt-metal#9150]
Add optional output tensor and q_id support

**Comment by VirdhatchaniKN** [comment]
Hi @eyonland , @tt-aho 

Regarding Prod for output tensor and q_id support ( `Tensor prod( const Tensor& input_a, bool all_dimensions = false, int64_t dim = 0, const MemoryConfig& output_mem_config = operation::DEFAULT_OUTPUT_MEMORY_CONFIG);` )

Prod op has three implementation to be addressed

- Prod in composite file [File : `tt_eager/tt_dnn/op_library/composite/composite_ops.cpp` ]
     - Here, we have used `permute` and `unpad` ops .
         - permute is fully dependant on `launch_with_autoformat`, Would like to know how can we provide output tensor support in permute?
         - For dim 2, unpad is the final operation that's used here in prod. So if unpad has output tensor support, we can try to pass output tensor for the final result calculation. But permute is going to be a problem here.
- Prod along N,C dimensions [File : `tt_eager/tt_dnn/op_library/prod/prod_nc_op.hpp`]
     - Output tensor and q_id is possible here I guess. We will try that.
- Prod along all dimensions [File : `tt_eager/tt_dnn/op_library/prod/prod_op_all.cpp`]
     - Here the operational flow goes like `kernel implementation-->tiled prod (ckernel implementation)--> Host multiplication (based on architecture)`.
          - Output tensor can only be passed till tiled prod. 
          - Since this implementation depends on host side calculation for the final part, how should we proceed on this? Should we copy the final value using assign or how can we proceed on this.
       
Would like your inputs to proceed further on this.
Thanks

**Comment by KalaivaniMCW** [comment]
As per discussion with @eyonland,  these are out of scope
