### ISSUE TITLE
[Help] what is different between interleave and shard Tensor

### ISSUE THREAD

**Issue by ahuizxc** [tenstorrent/tt-metal#9153]
hello, I am a new user
After read the source code and docs, I still a little confused about the interleave and shard layout.
According to my understanding, the interleave layout regardless the shape and just split the tensor's storage to each core,
and the shard layout can shard in HEIGHT/WIDTH/BLOCK, and split according to shard type to each core
Do I understand correctly?
Thanks a lot!

**Comment by ayerofieiev-tt** [comment]
@ahuizxc , please let me know if this helps

### Interleaved
Means data is interleaved across memory banks, which emulates ”shared global memory”​.
on Greyskull:
DRAM interleaved across all 8 memory banks
L1 interleaved across cores up to 128

### Sharded
Means data is broken into blocks and each block is distributed to a corresponding DRAM/L1 bank.
If you want to do eltwise A + B, you can shard A and B. Data is conveniently placed in such a manner that each tensix gets its portion of A + B to be able to make a + b.

**Comment by ahuizxc** [comment]
> @ahuizxc , please let me know if this helps
> 
> ### Interleaved
> Means data is interleaved across memory banks, which emulates ”shared global memory”​. on Greyskull:
> 
> * DRAM interleaved across all 8 memory banks
> * L1 interleaved across cores up to 128
> 
> ### Sharded
> Means data is broken into blocks and each block is distributed to a corresponding DRAM/L1 bank. If you want to do eltwise A + B, you can shard A and B. Data is conveniently placed in such a manner that each tensix gets its portion of A + B to be able to make a + b.

totally understand! thanks a lot!

**Comment by tt-rkim** [comment]
@ahuizxc Thank you for your response

Please close this issue if your question has been addressed.
