### ISSUE TITLE
Model perf regressions: Stable diffusion times out (hang?)

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-metal#9158]
Model perf regressions: Stable diffusion times out (hang?)

Test command:
```
tests/device_perf_tests/stable_diffusion/test_perf_stable_diffusion.py::test_stable_diffusion_perf[2-4-3600-0.28-device_params0]
```

Job failure: https://github.com/tenstorrent/tt-metal/actions/runs/9382083861/job/25832971014

**Comment by nsmithtt** [comment]
@AleksKnezevic, can you triage?

**Comment by nsmithtt** [comment]
Job started failing at commit [6e889fb](https://github.com/tenstorrent/tt-metal/commit/6e889fbcfe6f9a0ea71f1f5e7a29b85fec6b4fd3).

Last known good:  baef03c

**Comment by AleksKnezevic** [comment]
Thanks @nsmithtt, looking into it.

**Comment by AleksKnezevic** [comment]
It's been fixed on latest main: https://github.com/tenstorrent/tt-metal/actions/runs/9382108040/job/25832837038
