### ISSUE TITLE
[Llama3] Support 8k context length

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent/tt-metal#9159]
Llama3 has to be able to support prefill and decode up to the max native context length which is 8k tokens.
This issue tracks the changes that will have to be made to support 8k context.

### Issues
- `fused_qkv` matmul fails due to L1 space
```
 Always | FATAL    | Statically allocated circular buffers on core range [(x=0,y=0) - (x=7,y=7)] grow to 2225984 B which is beyond max L1 size of 1499136 B
```
### Solutions
Chunk activation sequence length and push these chunks into the batch dimension. Matmul 2D can accept `fuse_batch=False` so it will create an outer loop over the batch. Ex:
```python
x = ttnn.reshape(x, (1, 4, 2048, 8192))
fused_qkv_out = ttnn.matmul(x, wqkv)
fused_qkv_out = ttnn.reshape(fused_qkv_out, (1, 1, 8192, 1280)
```

Prefill has matmuls of the following shapes:

qkv
`S, 8192 @ 8192, 1280`
dense_out
`S, 8192 @ 8192, 1024`
FF1
`S, 8192 @ 8192, 4096`
FF2
`S, 32768 @ 32768, 1024`

S will be up to 8192.

### Issues
- `unpad k cache` fails due to L1 space
```
Always | FATAL    | Out of Memory: Not enough space to allocate 35651584 B L1 buffer across 32 banks, where each bank needs to store 1114112 B
```
### Solutions
We need a FlashDecode op which implements SDPA without loading K, V into L1 or materializing scores matrix.

**Comment by pavlepopovic** [comment]
Regarding prefill matmuls, I think you can do them in multiple slices with interleaved2shardedpartial/sharded2interleavedpartial, which would effectively be t slicing

**Comment by cglagovichTT** [comment]
Thank you @pavlepopovic , I'll test out partials for initial functionality bringup. I suspect we'll need matmul2D to implement t-streaming to get highest possible performance.

**Comment by cglagovichTT** [comment]
Update: I was able to get 8k context length functionally correct for a 1 layer prefill test by reshaping the activations before and after large matmuls, pushing chunks into the batch dimension.

**Comment by cglagovichTT** [comment]
We are going to limit Llama3 to have a batch size of 16 when context_length=8192. This will require at least one change:
- `nlp_create_qkv_heads_decode` should take a "unpadded_batch_size" argument so it can take an input of `32[16], 1280` to output `16, 32[8], 128` for Q, similar for K and V.

**Comment by cglagovichTT** [comment]
Llama support matrix:
| batch size | max context length|
| -|-|
| 32 | 2048|
|16| multiples of 2048 up to 8192|

**Comment by cglagovichTT** [comment]
The last thing necessary to enable 8k context in decode is to modify `FlashAttention`. This is the PoR:

```python
# Q: height sharded on batch, logical shape [1, batch, n_heads_padded, d_head]
# K: interleaved in DRAM, logical shape [1, batch, max_context_len, d_head]
# V: same config as K
# padded_seq_len = nearest_32(current_tok_index)
# attn_mask: interleaved in DRAM, logical shape [1, batch, n_heads_padded, padded_seq_len]

attn_output = tt_lib.operations.primary.transformers.scaled_dot_product_attention(
        Q, K, V, attn_mask, is_causal=False
    )

# attn_output: height sharded on batch, same shape as Q
```

**Comment by uaydonat** [comment]
Since we have some extra cores, maybe we can shard the attention on both the batch and the valid_length since it can be really large.

**Comment by cglagovichTT** [comment]
The ideal op would implement [FlashDecode](https://pytorch.org/blog/flash-decoding/) to parallelize along `valid_length`. For a first pass, it will be very quick to bring up functionality with small changes to `SDPA` op which only parallelized on batch.

After we have long context functionality, I'd like to come back and plan a more optimized attention op. This is because if we make major changes to parallelize SDPA across K length, we should also consider the other attention optimizations in the pipeline (paged KV cache, ring attention on Galaxy, ...)

**Comment by cglagovichTT** [comment]
@yieldthought @johanna-rock-tt 
Could you please tell me your batch, num_q_heads, num_kv_heads, max_context_length, and dhead? I'd like to know what these numbers are for a single chip in your fractured models, i.e. Llama has `num_q_heads=64` fractured by 8, so our numbers are
```
batch = 16
num_q_heads = 1
num_kv_heads = 8
max_context_length = 8k
dhead = 128
```

**Comment by johanna-rock-tt** [comment]
Falcon40b has
```
num_q_heads = 16
num_kv_heads = 1
max_context_length = 2k
dhead = 64
```
for decode we currently have `batch = 32` and for prefill we have `batch = 1`

**Comment by sraizada-tt** [comment]
for mixtral we have, 
```
batch = 32
num_q_heads = 4
num_kv_heads = 1
max_context_length = 8k
dhead = 128
```
