### ISSUE TITLE
Use project paths in CMake

### ISSUE THREAD

**Issue by jeongu-moreh** [tenstorrent/tt-metal#9200]
Using `CMAKE_SOURCE_DIR` and `CMAKE_BINARY_DIR` in CMake causes problems if tt-metal is imported as a subproject. It is recommended to use `PROJECT_SOURCE_DIR` and `PROJECT_BINARY_DIR` instead.

Here is the patch file solving this issue: [cmake.patch.txt](https://github.com/user-attachments/files/15600988/cmake.patch.txt)
All third-parties are not affected.

**Comment by razorback3** [comment]
@TT-billteng, how do you think about this issue?
(cc. @davorchap )

**Comment by TT-billteng** [comment]
yes we should do this @vtangTT

**Comment by TT-billteng** [comment]
After this change, are you able to use Metal as a submodule?

**Comment by razorback3** [comment]
> After this change, are you able to use Metal as a submodule? I'm curious as we have received community requests to build on top of Metal as a submodule/dependency

Yes, it is. @jeongu-moreh already tested that use case.

**Comment by vtangTT** [comment]
https://github.com/tenstorrent/tt-metal/pull/9259 merged to main. Please give it a try.

**Comment by jeongu-moreh** [comment]
Now it works without a problem. Thanks!
