### ISSUE TITLE
Segmentation fault when closing devices for Falcon7b decode perplexity test

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#9268]
Segmentation fault occurs after the test passes successfully as devices are being closed:
![image](https://github.com/tenstorrent/tt-metal/assets/159165450/b7718067-75de-4c44-b88e-ae90037ebbea)

Commit: `a5a6ddb93a`
Command: `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/demos/falcon7b/tests/test_perplexity_falcon.py::test_perplexity[1-True-decode_1024_l1_sharded]`

**Comment by skhorasganiTT** [comment]
Possibly related to #8637

**Comment by uaydonat** [comment]
could be related to https://github.com/tenstorrent/tt-metal/pull/9380

**Comment by skhorasganiTT** [comment]
Not able to reproduce on main (5196c48052) on sjc-nmrk-t3001. It was potentially fixed by #8615, or only occurs on certain machines like #9430.
