### ISSUE TITLE
Allow accumulation in dst for add_tiles api

### ISSUE THREAD

**Issue by caixunshiren** [tenstorrent/tt-metal#9271]
LLKs like matmul has the feature which the output can accumulate in dest. In current implementation of add_tiles, if A is stored in dst and add_tiles(B,C) is performed, the behavior is to have B+C stored in dst. It would be good to also enable the feature where A+B+C can be accumulated in dest.

FYI @cglagovich @cglagovichTT

**Comment by rtawfik01** [comment]
Merged here: https://github.com/tenstorrent/tt-metal/pull/9272. Let me know if you have any issues.
