### ISSUE TITLE
WH: assert failure running on double nebula machine

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#9325]
WH machine w/ 2 n300s
Run: pytest -svv tests/ttnn/unit_tests/test_multi_device_trace.py::test_multi_device_single_trace
Hits an assert in llrt.cpp write_launch_message_to_core from initialize_command_queue initialize device 2:

python3: ../tt_metal/llrt/llrt.cpp:164: void tt::llrt::write_launch_msg_to_core(chip_id_t, const CoreCoord, launch_msg_t *): Assertion `is_active_eth_core or is_inactive_eth_core' failed.

The set of cores that are passed into write_launch_msg_to_core are:
----(x=9,y=0)
----(x=2,y=10)
----(x=1,y=10)
----(x=4,y=10)
----(x=3,y=10)
----(x=9,y=0)
Is the issue that the last shows up twice?

fyi @ubcheema @tt-asaigal

**Comment by ubcheema** [comment]
y=10 is not a valid physical row for eth cores.
eth cores are on physical y=0 and y=6.
the cores with y=10 are probably tensix dispatch cores, mislabeled somewhere as eth cores.

**Comment by pgkeller** [comment]
possibly related to #9518? same machine was in linear config at the time

**Comment by pgkeller** [comment]
Use machine 172.27.28.27, e09cs07

**Comment by pgkeller** [comment]
doesn't reproduce at present, closing
