### ISSUE TITLE
ND Hang behaviour on f10cs08 in T3000 LLM model perf tests

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#9345]
Noticed starting ~2 weeks ago on ci (ci before this was not stable/had other failing issues, not sure when exactly this started happening/if it started happening earlier or not).

f10cs08 would ND hang during the LLM perf test, normally in one of the falcon variants. Sometimes the board dies and can't be reset, so host reboot is required. I've only noticed this on f10cs08, and not the other two ci machines (06 and 07).

Note some of the following were run from a branch I had that passed on 06 and 07, and also passed on 08 after it was rebooted.

Example hangs:

- https://github.com/tenstorrent/tt-metal/actions/runs/9423929528/job/25963318033
- https://github.com/tenstorrent/tt-metal/actions/runs/9376031179/job/25815396775
- https://github.com/tenstorrent/tt-metal/actions/runs/9334458454/job/25692767657
- https://github.com/tenstorrent/tt-metal/actions/runs/9333369790/job/25690348875
- https://github.com/tenstorrent/tt-metal/actions/runs/9332809587/job/25689172749
- https://github.com/tenstorrent/tt-metal/actions/runs/9331392813/job/25686030136

Example board dies during a run:

- https://github.com/tenstorrent/tt-metal/actions/runs/9383003204/job/25835828919
- https://github.com/tenstorrent/tt-metal/actions/runs/9335272075/job/25694522379

Example board can't be reset after board died during previous run:

- https://github.com/tenstorrent/tt-metal/actions/runs/9383258833/job/25836621577
- https://github.com/tenstorrent/tt-metal/actions/runs/9335463744/job/25694912179

@tt-rkim

**Comment by tt-rkim** [comment]
cc: @TT-billteng @ttmchiou 

Something to investigate later

**Comment by tt-rkim** [comment]
@tapspatel Anything unusual off the top of your head that you know about `f10cs08`?

**Comment by s-jovic** [comment]
Seems that 08 has old fw (last message in #tt-metal-pipelines) - although 06 and 07 have it too, however we already know that not all N300 machines expose nd hangs, so it might be that 08 is the only problematic one. Could we get 8.12 bundle installed on all machines?

**Comment by smehtaTT** [comment]
@ttmchiou - can you help update the 4 T3000 FW today please? thanks

**Comment by ttmchiou** [comment]
t3000 fw all flashed to 8.8.12.0

**Comment by TT-billteng** [comment]
let's see what stability is like in the next few days

**Comment by tt-rkim** [comment]
ThaNK YOU 🐐 @ttmchiou

**Comment by tt-rkim** [comment]
@s-jovic @tt-aho 
let us know if you see anything

**Comment by s-jovic** [comment]
Thanks a lot! So far no hangs, I will keep monitoring.

**Comment by s-jovic** [comment]
Looking at the timing, this doesn't seem like a hang to me - the 7b test didn't run 75min, seems that it was cut off because the whole pipeline shouldn't last longer than 75min (@ttmchiou if I understood correctly). In any case, new fw is out now, so I will check if this happens again.

**Comment by ttmchiou** [comment]
@s-jovic https://github.com/tenstorrent/tt-metal/actions/runs/9904963917
```
Fri, 12 Jul 2024 10:19:15 GMT
Loading decoder layers: 100%|██████████| 32/32 [00:08<00:00,  4.34it/s]
Fri, 12 Jul 2024 10:19:15 GMT
Loading decoder layers: 100%|██████████| 32/32 [00:08<00:00,  3.87it/s]
Fri, 12 Jul 2024 10:19:18 GMT
2024-07-12 10:19:18.532 | INFO     | models.demos.falcon7b.tests.run_falcon_end_to_end:run_test_FalconCausalLM_end_to_end:198 - Running Falcon model once to fill caches
Fri, 12 Jul 2024 10:21:28 GMT
2024-07-12 10:21:28.205 | INFO     | models.demos.falcon7b.tests.run_falcon_end_to_end:run_test_FalconCausalLM_end_to_end:276 - Enable profiler
Fri, 12 Jul 2024 10:21:28 GMT
2024-07-12 10:21:28.399 | INFO     | conftest:cancel:[543](https://github.com/tenstorrent/tt-metal/actions/runs/9904963917/job/27363820345#step:10:544) - Cancelling timer
Fri, 12 Jul 2024 10:21:28 GMT
models/demos/falcon7b/tests/test_perf_falcon.py::TestParametrized::test_perf_t3000_bare_metal[prefill_seq2048-falcon_7b] 
Fri, 12 Jul 2024 11:29:58 GMT
Error: The action 'Run model perf regression tests' has timed out after 75 minutes.
```

The pipeline here did cut off at 75min but it looks here that this machine running on v8.8.12.0 fw did hang at 10:21GMT time and hanged all the way til we hit the 75min timeout

**Comment by s-jovic** [comment]
Yeah, you are right, actually here is another example on `f10cs08` with v8.12.0 fw where we have `Read 0xffffffff from PCIE` error: https://github.com/tenstorrent/tt-metal/actions/runs/9907578155/job/27382164252.

**Comment by s-jovic** [comment]
Since the rollout of new firmware (80.9.3), so for a week now (I was checking since July 15), there hasn't been a falcon7b hang on the following pipelines:
- T3K model perf
- T3K demo
- T3K perplexity

@ttmchiou I think we can close the issue if you agree?

**Comment by ttmchiou** [comment]
Yes, I think we can close this issue now since there haven't been any more ND issues observed on this machine.
