### ISSUE TITLE
Debug mode compilation does not include debug symbols

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#9357]
Debug symbols are missing from the `CONFIG=Debug` compiled artifacts.

**Comment by vtangTT** [comment]
CC: @TT-billteng

**Comment by TT-billteng** [comment]
is this fixed with the gdb 14.2 upgrade?

**Comment by tt-rkim** [comment]
Helloooooo update? @mywoodstock

**Comment by tt-rkim** [comment]
You use default compiler for `gcc` on tracy for this one PR I saw from you

**Comment by mywoodstock** [comment]
> You use default compiler for `gcc` on tracy for this one PR I saw from you

That was a workaround for a different issue (compilation errors with tracy enabled.)

@vtangTT any update on this issue/eta?

**Comment by vtangTT** [comment]
Is GDB 14.2 able to pick up the debug symbols? It should be available in our docker image now.

**Comment by mywoodstock** [comment]
> Is GDB 14.2 able to pick up the debug symbols? It should be available in our docker image now.

yes, looks like its working now with 14.2 :)

I guess we can close this? @vtangTT

**Comment by vtangTT** [comment]
Sounds good to me 👍
