### ISSUE TITLE
ttnn.conv2d fails with L1 OOM issue for FADNetPP

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#9372]
ttnn.conv2d fails with Out of memory (L1 issue) for FADNetPP_960x576 unit test case.

**To Reproduce**
1. Checkout the branch [keerthanar/fadnetpp_conv_l1_unit_test](https://github.com/tenstorrent/tt-metal/tree/keerthanar/fadnetpp_conv_l1_unit_test).
2. Run the following command,
`pytest tests/ttnn/unit_tests/operations/test_conv2d.py:: test_conv_fadnetpp_l1 `
3. The following error will occur,
`RuntimeError: TT_THROW @ ../tt_metal/impl/allocator/allocator.cpp:118: tt::exception
E           info:
E           Out of Memory: Not enough space to allocate 272640 B L1_SMALL buffer across 12 banks, where each bank needs to store 22720 B`

**System info**
Ubuntu, GSE150

**Comment by mywoodstock** [comment]
@keerthana-r-mcw Could you please give this another try -- it should be resolved with latest `main`.

**Comment by pavlejosipovic** [comment]
@keerthana-r-mcw 
I was able to get this running on latest main
https://github.com/tenstorrent/tt-metal/tree/pjosipovic/fadnetpp_conv_l1_unit_test
I had to enable shallow conv feature for first conv which has small number of input channels (3).
Second one just worked.

If this is good enough for you can you pls close the issue?
