### ISSUE TITLE
Loading weight cache on LLM models hangs

### ISSUE THREAD

**Issue by mtairum** [tenstorrent/tt-metal#9400]
This issue is caused by commit [d35ea9d833037ef8d8f1b47ed404a5ff057cf64c](https://github.com/tenstorrent/tt-metal/commit/d35ea9d833037ef8d8f1b47ed404a5ff057cf64c)

The behaviour we are seeing across LLMs is a hang when loading cache files. It can also be seen in T3K CI pipelines: https://github.com/tenstorrent/tt-metal/actions/runs/9482174428

I'm assigning this to @ubcheema for now, since they authored the above commit.
Feel free to re-assign if applicable.

The issue seems only to affect multi-device. I've tested with mistral-7B on single device and loading cached weights is fine.

## Reproduction
Unfortunately, this is not reproducible with dummy weights. It has to download the cache files.

I've tested with mixtral attn and mlp tests. For more info on how to get the mixtral weights please look at the comment below in the issue, or check the Mixtral README file.
- `pytest models/demos/t3000/mixtral8x7b/tests/test_mixtral_mlp.py`
- `pytest models/demos/t3000/mixtral8x7b/tests/test_mixtral_attention.py`

Alternative you can try the falcon-7B 4chips demo. Just feed the following json inputs files instead of the one provided in the folder: 
[inputs_128.json](https://github.com/user-attachments/files/15817638/inputs_128.json)

`pytest --disable-warnings -q -s --input-method=json --input-path=<JSON FILE> models/demos/t3000/falcon7b/demo_t3000.py::test_demo_multichip[user_input0-4-True-default_mode_stochastic]`

This will download the falcon7B weights and hang on `1st run prefill stage with compile`.

FYI: @tapspatel @tt-rkim 

FYI: @esmalTT @skhorasganiTT @cglagovich @kevinmiTT11

**Comment by ubcheema** [comment]
I am getting this error when running test_mixtral_mlp.py

```
>      assert os.path.exists(
        self.DEFAULT_CKPT_DIR
      ), f"Checkpoint directory {self.DEFAULT_CKPT_DIR} does not exist, please use export MIXTRAL_CKPT_DIR=..."
E      AssertionError: Checkpoint directory /proj_sw/user_dev/hf_data/mistral/Mixtral-8x7B-v0.1 does not exist, please use export MIXTRAL_CKPT_DIR=...

models/demos/t3000/mixtral8x7b/tt/model_config.py:74: AssertionError
============================================================================== short test summary info ==============================================================================
FAILED models/demos/t3000/mixtral8x7b/tests/test_mixtral_mlp.py::test_mixtral_mlp_inference[wormhole_b0-True] - AssertionError: Checkpoint directory /proj_sw/user_dev/hf_data/mistral/Mixtral-8x7B-v0.1 does not exist, please use export MIXTRAL_CKPT_DIR=...
================================================================================= 1 failed in 9.39s =================================================================================
```

**Comment by mtairum** [comment]
Pasting the instructions for downloading mixtral weights here as well:

You can either download the weights (check readme below) or copy from another machine.
Some t3000 have the weights already. They are 87 GB.

For example:

- t3002 (10.229.36.111)
  - `/home/mtairum/mistral/Mixtral-8x7B-v0.1/repack_weights.pt`
  - `/home/mtairum/mistral/Mixtral-8x7B-v0.1/tokenizer.model`

- or t3008 (10.229.36.205)
  - `/home/mtairum/mistral/Mixtral-8x7B-v0.1/instruct/repack_weights.pt`
  - `/home/mtairum/mistral/Mixtral-8x7B-v0.1/instruct/tokenizer.model``

Once you have the repack weights you just have to point the folder in the flags:

```
export MIXTRAL_CKPT_DIR=<repacked_output_dir>
export MIXTRAL_TOKENIZER_PATH=<path_to_tokenizer_dir>
export MIXTRAL_CACHE_PATH=<weights_cache_dir>
```

Readme has more info:

https://github.com/tenstorrent/tt-metal/blob/main/models/demos/t3000/mixtral8x7b/README.md

**Comment by mtairum** [comment]
Updated the falcon4b example to run on 4 devices instead of 8

**Comment by mtairum** [comment]
@ubcheema I'm not sure what happened but the issue has seemingly gone away?

I've retested in separate machines this morning (one of them the same as of yesterday) and I can't replicate the hangs. 
There is however a new problem in main, but is not related to this issue.

I'll lower to P1 and ask the other model owners to test this commit again today to see if the hangs persist.

@esmalTT @kevinmiTT11 Can you folks retry your tests that were seeing the same hangs yesterday on this commit `d35ea9d833037ef8d8f1b47ed404a5ff057cf64c` and report back if it works today?

**Comment by mo-tenstorrent** [comment]
@kevinmiTT11 pointed me to this ticket. I am actually hitting a similar issue with commit which I though I should share [d35ea9d833037ef8d8f1b47ed404a5ff057cf64c](https://github.com/tenstorrent/tt-metal/commit/d35ea9d833037ef8d8f1b47ed404a5ff057cf64c)

With it, 

```
pytest -svv models/experimental/llama2_70b/tests/test_llama_perf_decode.py::test_Llama_perf_host[wormhole_b0-True-gen32]
```
hangs at : 
```
2024-06-12 19:51:10.731 | INFO     | models.experimental.llama2_70b.tests.test_llama_perf_decode:run_test_LlamaModel_end_to_end:203 - Running 1st run decode stage with compile...
2024-06-12 19:51:10.732 | INFO     | models.experimental.llama2_70b.tests.test_llama_perf_decode:run_inference:116 - Generating token: 1
2024-06-12 19:51:11.648 | DEBUG    | ttnn.operations.core:as_tensor:698 - Loaded cache for /mnt/MLPerf/tt_dnn-models/llama-2/llama-data-cache/weights-cache-2/rot_mat_decode_0_multi_device_dtype_BFLOAT16_layout_TILE.bin of shape ttnn.Shape([1, 32, 128, 128])
2024-06-12 19:51:12.173 | DEBUG    | ttnn.operations.core:as_tensor:698 - Loaded cache for /mnt/MLPerf/tt_dnn-models/llama-2/llama-data-cache/weights-cache-2/attn_masks_decode_0_multi_device_dtype_BFLOAT16_layout_TILE.bin of shape ttnn.Shape([1, 1, 32, 32])
```

This running on fresh main on normal build and after a full reboot. 

Rolling back to the commit right before metal galaxy support takes the hang away.

I am not blocked by this as I was actually testing something else and older commits are fine.

**Comment by ubcheema** [comment]
I have pushed fix to main @ [1a9485e](https://github.com/tenstorrent/tt-metal/commit/1a9485ee7b1ccf1b2f70683d7398d9309cbe67f8)

The hang is not related to [d35ea9d833037ef8d8f1b47ed404a5ff057cf64c](https://github.com/tenstorrent/tt-metal/commit/d35ea9d833037ef8d8f1b47ed404a5ff057cf64c) but was being exposed by this commit for some reason.

The problem was in the kernel build flow that was using incorrect headers when building kernels for mmio vs remote devices.

**Comment by tt-rkim** [comment]
Did we verify that the pipeline is ok>?

**Comment by mtairum** [comment]
@kevinmiTT11 Have the hangs gone away in Llama as well, with the above commit?

If so I will close this ticket.

**Comment by mtairum** [comment]
Closing this issue has a fix was pushed and no more observations of the issue since then.
