### ISSUE TITLE
16 bits are unpacked when unpacking fp32 CB

### ISSUE THREAD

**Issue by dongjin-na** [tenstorrent/tt-metal#9410]
As discussed on Slack, in FP32 mode, when an fp32 CB is unpacked, only 16 bits are unpacked instead of 19 bits. 
You can verify the issue in the `fp32_unpack` branch.

I modified the `bmm_large_block_zm_fused_bias_activation.cpp `kernel.
If you enable debug print and run the test script, you can verify that only 16 bits are unpacked.
```
export TT_METAL_DPRINT_CORES=0,0
pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_bert_ops.py::test_fp32_unpack

[DEBUG] 0. matmul_pack_tile after matmul_block
0100 1100 0110 0100 0010 0100 0101 1000   <--- represent the first element as a binary number. (32bits)
[DEBUG] 1. enable_reload. reload_from_cb_to_dst
[DEBUG] 2. matmul_pack_tile to check bits
0100 1100 0110 0100 0000 0000 0000 0000 <---- 16bits
[DEBUG] 3. unpack again. reload_from_cb_to_dst
```

I found a way to unpack 19 bits. Change USE_UNPACK_HACK to 1 in the kernel and then run the test script. 
I hope this helps.

```
[DEBUG] 0. matmul_pack_tile after matmul_block
0100 1100 0110 0101 1010 0100 0101 1000
[DEBUG] 1. enable_reload. reload_from_cb_to_dst
[DEBUG] 2. matmul_pack_tile to check bits
0100 1100 0110 0101 1010 0000 0000 0000 <---- 19bits
[DEBUG] 3. unpack again. reload_from_cb_to_dst
```

**Comment by sangwon-chae** [comment]
@ttmtrajkovic Would you please share the current status of this issue? Thanks.

**Comment by ttmtrajkovic** [comment]
@rdjogoTT,
You should've already added this as part of typecast fp32 <-> fp16b conversion. Could you please share here how to utilize the unpack to fp32 and keep full precision?

Milos

**Comment by rdjogoTT** [comment]
In https://github.com/tenstorrent/tt-metal/pull/9528/files I added the parameter "preserve_fp32_precision" to tt_metal::ComputeConfig. Setting this value to true enables fp32 values to be unpacked in full 32 bit precision in to Dest.

**Comment by rdjogoTT** [comment]
@dongjin-na Would you mind clarifying which use case you need between the following two:
1. You want to unpack fp32 datums into srcA/B to be used in FPU math or
2. You want to unpack fp32 datums directly to dest and keep the highest precision possible

**Comment by dongjin-na** [comment]
@rdjogoTT , thank you for your question. 
We need the second use case. 
Typically, in a compute kernel, we temporarily store the results saved in the dest register to CB and later unpack them back to the dest register for reuse. 
So, it's important to unpack fp32 datums directly to the dest register while maintaining the highest precision possible.

CC: @razorback3, @sangwon-chae

**Comment by rdjogoTT** [comment]
> @rdjogoTT , thank you for your question. We need the second use case. Typically, in a compute kernel, we temporarily store the results saved in the dest register to CB and later unpack them back to the dest register for reuse. So, it's important to unpack fp32 datums directly to the dest register while maintaining the highest precision possible.
> 
> CC: @razorback3, @sangwon-chae

Ok great, that is what my change in https://github.com/tenstorrent/tt-metal/pull/9528/files accomplishes as well. By setting "preserve_fp32_precision = true" in the tt_metal::ComputeConfig (in tt_eager/tt_dnn/op_library/bmm/multi_core_reuse_mcast_2d_optimized/bmm_op_multi_core_reuse_mcast_2d_optimized.cpp - line 632) this should set proper datatypes for hw to know to unpack fp32 to dest.

**Comment by dongjin-na** [comment]
Hi @rdjogoTT, 
thank you for the update. 
I have rebased `fp32_unpack` branch with the latest main and added `preserve_fp32_precision = true` as suggested. However, the results did not change after testing.


I have created and pushed a new branch named `fp32_unpack_with_preserve`. Is there anything I missed?

```
diff --git a/tt_eager/tt_dnn/op_library/bmm/multi_core_reuse_mcast_2d_optimized/bmm_op_multi_core_reuse_mcast_2d_optimized.cpp b/tt_eager/tt_dnn/op_library/bmm/multi_core_reuse_mcast_2d_optimized/bmm_op_multi_core_reuse_mcast_2d_optimized.cpp
index f0ad856690..d3f710d571 100644
--- a/tt_eager/tt_dnn/op_library/bmm/multi_core_reuse_mcast_2d_optimized/bmm_op_multi_core_reuse_mcast_2d_optimized.cpp
+++ b/tt_eager/tt_dnn/op_library/bmm/multi_core_reuse_mcast_2d_optimized/bmm_op_multi_core_reuse_mcast_2d_optimized.cpp
@@ -632,6 +632,7 @@ operation::ProgramWithCallbacks create_program_mcast_in0_in1(
         tt_metal::ComputeConfig{
             .math_fidelity = math_fidelity,
             .fp32_dest_acc_en = fp32_dest_acc_en,
+            .preserve_fp32_precision = true,
             .math_approx_mode = math_approx_mode,
             .compile_args = compute_kernel_args,
             .defines = mm_kernel_defines});
```


```
(python_env) ubuntu@tt-metal-dev-moreh-wh-14:~/tt-metal$ cat built/7168/kernels/bmm_large_block_zm_fused_bias_activation/9686221648875303714/chlkc_unpack_data_format.h
constexpr std::int32_t unpack_src_format[32] = {
    5,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,5,255,255,255,255,255,255,255,0,255,255,255,255,255,255,255,
};
constexpr std::int32_t unpack_dst_format[32] = {
    5,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,5,255,255,255,255,255,255,255,
};
```

**Comment by rdjogoTT** [comment]
@dongjin-na It looks like both unpack_src/dst_format[0] and [1] are set to bfloat16_b (5) rather than fp32 (0). These would need to be set to fp32 for my change to work.

**Comment by dongjin-na** [comment]
If the source format is bfloat16_b but the intermediate format is float32, is it not possible to use preserve_fp32_precision for unpacking the intermediate CB?

**Comment by rdjogoTT** [comment]
Ok I see, the actual issue was that unpack_src/dst_format[24] needed to both be "0". I have updated genfiles.cpp: https://github.com/tenstorrent/tt-metal/pull/9885/files , can you test with this change to see if that solves the issue. I tested it and it looks like it works. If it solves the issue then I will merge my change and you can rebase onto it

**Comment by dongjin-na** [comment]
Hi @rdjogoT,

It works! It maintains FP32 precision during both unpacking and packing in the intermediate CB (24). Thanks for your patch. Will you merge it into the main branch? :)

**Comment by rdjogoTT** [comment]
Yes I will merge it now as soon as post-commit passes. As for adding `preserve_fp32_precision` to `DeviceComputeKernelConfig`, I don't really have the time right now. However, this is likely going to be part of a greater clean-up task down the road as some ops other than matmul don't even make use of this struct in the first place. But if you want to add it, go ahead.

**Comment by dongjin-na** [comment]
Thanks for the work. I will close this issue.
