### ISSUE TITLE
typecasting from uint16 to uint32 gives wrong outputs

### ISSUE THREAD

**Issue by sraizada-tt** [tenstorrent/tt-metal#9441]
To reproduce:
```
import torch
import ttnn
from models.utility_functions import (
    comp_pcc,
    comp_allclose,
)
def test_typecasting(device):
    torch_input = torch.randint(0, 32000, (1, 1 ,32, 32), dtype=torch.long)
    tt_input = ttnn.from_torch(
        torch_input,
        device=device,
        dtype=ttnn.uint16,
        layout=ttnn.TILE_LAYOUT,
    )
    tt_input = ttnn.experimental.tensor.typecast(tt_input, dtype=ttnn.uint32)   
    tt_input_to_torch = ttnn.to_torch(tt_input)
    passing, pcc = comp_pcc(tt_input_to_torch, torch_input, 0.99)
    print(passing, pcc)
    assert passing, f"Typecasting failed"
```

We are asking for UINT16->UINT32 because the top-k op outputs UINT16 only but the embedding op accepts UINT32 only and LLMs need to chain these together.

An alternative is UINT32 top-k output or UINT16 embedding input support.

**Comment by sraizada-tt** [comment]
uint16 -> bfloat16 - uint32 also gives bad outputs:
```
def test_typecasting(device):
    torch_input = torch.randint(0, 32000, (1, 1 ,32, 32), dtype=torch.long)
    tt_input = ttnn.from_torch(
        torch_input,
        device=device,
        dtype=ttnn.uint16,
        layout=ttnn.TILE_LAYOUT,
    )
    tt_input = ttnn.experimental.tensor.typecast(tt_input, dtype=ttnn.bfloat16)
    tt_input_to_torch = ttnn.to_torch(tt_input)
    passing, pcc = comp_pcc(tt_input_to_torch, torch_input, 0.99)
    print(passing, pcc)

    tt_input = ttnn.experimental.tensor.typecast(tt_input, dtype=ttnn.uint32)
    tt_input_to_torch = ttnn.to_torch(tt_input)
    passing, pcc = comp_pcc(tt_input_to_torch, torch_input, 0.99)
    print(passing, pcc)
    assert passing, f"Typecasting failed"
```

**Comment by sraizada-tt** [comment]
fyi - @ttmtrajkovic

**Comment by rdjogoTT** [comment]
I have merged typecast support for uint16->32

**Comment by sraizada-tt** [comment]
Hey @rdjogoTT , the uint16 -> 32 test above is still failing and this conversion doesn't seem to be included in the unit tests https://github.com/tenstorrent/tt-metal/blob/11bd0fec21c8f217042cd841e1051bd5bfa1474a/tests/ttnn/unit_tests/operations/test_eltwise_typecast.py#L61

**Comment by rdjogoTT** [comment]
@sraizada-tt so the above test you provided actually calls `ttnn.experimental.tensor.typecast`, but should call `ttnn.typecast` instead:
```
import torch
import ttnn
from models.utility_functions import (
    comp_pcc,
    comp_allclose,
)
def test_typecasting(device):
    torch_input = torch.randint(0, 32000, (1, 1 ,32, 32), dtype=torch.long)
    tt_input = ttnn.from_torch(
        torch_input,
        device=device,
        dtype=ttnn.uint16,
        layout=ttnn.TILE_LAYOUT,
    )
    tt_input = ttnn.typecast(tt_input, dtype=ttnn.uint32)   
    tt_input_to_torch = ttnn.to_torch(tt_input)
    passing, pcc = comp_pcc(tt_input_to_torch, torch_input, 0.99)
    print(passing, pcc)
    assert passing, f"Typecasting failed"
```
I think the experimental one was a previous attempt at typecast which was abandoned. When I try the updated case above, it actually passes and looks correct.

As for unit testing, `test_eltwise_typecast.py` looks like it was added recently and I wasn't aware of it. But I was aware of `test_typecast.py` in the same directory which also tests typecast. Do you know which of these files we are going to use?

**Comment by sraizada-tt** [comment]
That works, thank you! I don't know which one is used but uint16-> 32 is missing in test_typecast.py as well

**Comment by rdjogoTT** [comment]
@sraizada-tt Ok I added tests for all the different typecasts with my latest merge.
