### ISSUE TITLE
Explore removing initialization of "my_x" and "my_y" in noc_init 

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#9446]
Will reduce code space

**Comment by pgkeller** [comment]
I don't understand - what's the alternative, how would moving it reduce code space?

**Comment by abhullar-tt** [comment]
Im not sure if I remember why this was came up, it may have been related to setting some state multiple times that could have been done in noc_init. Maybe we should close this and open it up if it comes up again

**Comment by pgkeller** [comment]
sounds good, closing can reopen as needed
