### ISSUE TITLE
Investigate what slowed down device perf by almost 2x for certain tests

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#9467]
Before libc++: https://github.com/tenstorrent/tt-metal/actions/runs/9521692385

After libc++: https://github.com/tenstorrent/tt-metal/actions/runs/9530903488

Looks like a lot of tests lengthened in time... almost double.

We need to investigate if libc++ is the culprit. These two runs should be 1 commit apart.

cc: @mo-tenstorrent @yan-zaretskiy @TT-billteng @vtangTT

**Comment by yan-zaretskiy** [comment]
@tt-rkim Just to clarify — do you mean the timeout issue above for the GS device perf job? I don't see any slowdowns on the N300 WH job. Both took 17 mins and 50ish sec to run and the perf report is very close, prob within the measuring error margin.

**Comment by tt-rkim** [comment]
Yes just the GS device perf job. Which is super weird because the only thing that can explain Still, not sure what would cause such a difference... not sure if we see this with all the models. So perhaps certain ops cause a slowdown. For ex. we don't run bert perf on WH

The re-run on the commit before libc++ passed. Running again

**Comment by mo-tenstorrent** [comment]
Trying to reproduce locally as well. 

Post commit profiler is also lengthened. @tt-rkim can you think of any other cI job that runs pytest on GS?

**Comment by mo-tenstorrent** [comment]
Ok so tt_metal `ReadFromDevice` went from ~2-3s on each call to ~17-18s. 

Before:
<img width="738" alt="Screenshot 2024-06-17 at 10 27 03 AM" src="https://github.com/tenstorrent/tt-metal/assets/109363418/f062b291-c481-4157-ad0a-6f888f25f315">

After:
<img width="961" alt="Screenshot 2024-06-17 at 10 26 31 AM" src="https://github.com/tenstorrent/tt-metal/assets/109363418/477541c7-f703-406f-8955-0ef4a4446630">

Device perf regression calls it to get profiling data from DRAM that is why many other places GS is fine. 

I would say we up the timeout on Device Perf CI for now and start a separate ticket on the `ReadFromDevice` regression.

**Comment by tt-rkim** [comment]
Sounds good, will increase timeout

Did you see what the underlying call times are like between the two?

**Comment by mo-tenstorrent** [comment]
I was trying Bert and the run went from ~1min to 1min 30 seconds. So all of the time increase is coming from `ReadFromDevice`

**Comment by tt-rkim** [comment]
Is that tracy? Is it showing anything underneath?

**Comment by mo-tenstorrent** [comment]
Oh I see, no, no further child calls are recorded.

**Comment by mo-tenstorrent** [comment]
A bit more info on this, 

<img width="1718" alt="Screenshot 2024-06-17 at 3 08 11 PM" src="https://github.com/tenstorrent/tt-metal/assets/109363418/d02645b2-fd29-4bb9-81cb-13bbabf2f381">

So the elongation is coming directly from umd `read_from_device` calls.

**Comment by tt-rkim** [comment]
@mo-tenstorrent we can close?

**Comment by mo-tenstorrent** [comment]
Yes, #9516 fixed this
