### ISSUE TITLE
Move CCL ops to ttnn

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/tt-metal#9486]
Consolidate Tensor Manipulation ops in ttnn

### Plan
all_gather
- [x] replace c++ usage (not used)
- [x] replace python usage #9517
- [x] remove python binding
- [ ] consolidate into proper structure

line_all_gather
- [x] replace c++ usage (not used)
- [x] Add ttnn op
- [x] replace python usage
- [x] remove python binding
- [ ] consolidate into proper structure

reduce_scatter
- [x] replace c++ usage (not used)
- [x] Add ttnn op
- [x] replace python usage
- [x] remove python binding
- [ ] consolidate into proper structure

CCL common (test and source) after above are done
- [x] remaining standalone and ccl common files under `tt_eager/tt_dnn/op_library/ccl`
  - [x] ccl_common, README, ccl_host_datastructures, and contents of `tt_eager/tt_dnn/op_library/ccl/shared_with_host/`
- [ ] Unit tests under `tests/tt_eager/ops/ccl`

### Work done so far:

- All 3 CCL ops are merged to main

### Testing
For the best coverage, I recommend to run these workflows. If some of them fails, check if it is the same fail as on main:
-  Post commit CI
-  [post-commit] models tests
-  Device perf regressions and output report
-  Model perf regressions and output report
-  Nightly fast dispatch model regression CI
-  T3000 frequent tests
-  T3000 demo tests

**Comment by SeanNijjar** [comment]
Added a few extra bullets for all the CCL common code/tests

**Comment by SeanNijjar** [comment]
Last remaining items are the (gtest) unit tests.

**Comment by SeanNijjar** [comment]
> All 3 CCL ops are now merged to main cc. @SeanNijjar @ayerofieiev-tt

Thanks @Aswinmcw!

**Comment by ayerofieiev-tt** [comment]
> Last remaining items are the (gtest) unit tests.

Is it on @Aswinmcw ?

**Comment by Aswinmcw** [comment]
If moving gtests are in priority, I guess only few modifications are needed, if needed, let me know, I will try and raise one PR in couple of days
