### ISSUE TITLE
Move Ternary ops to ttnn

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/tt-metal#9491]
The ternary ops currently do not have an ttnn C++ version.  These need to be targeted as well. (ref https://docs.google.com/spreadsheets/d/1zykrpmyvdNgO8eMEAozDZwLetTumaBd4G6TuTZ-9NbU/edit#gid=0)

- [x] ttnn.addcdiv
- [x] ttnn.addcmul
- [x] #10587 
- [x] #10474

**Comment by ruthreshx** [comment]
@ayerofieiev-tt All ternery has been with latest code cleanup.
