### ISSUE TITLE
Conv fails with Segmentation fault

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#9505]
**Describe the bug**
ttnn.conv2d is failing with Segmentation fault for the conv unit test of Fadnet++ model.

**To Reproduce**
1. Checkout the branch [harini/dispnetres_predres5_unittest](https://github.com/tenstorrent/tt-metal/compare/harini/dispnetres_predres5_unittest)
2. Run the command: `pytest tests/ttnn/unit_tests/operations/test_conv2d.py::test_dispnetres_conv`
3. The following error will occur:
`2024-06-18 11:13:52.332 | DEBUG    | tt_eager.tt_dnn.op_library.sliding_window_op_infra.tt_py_composite_conv:determine_parallel_config:203 - PARALLEL CONFIG :: True :: 512 :: 1 :: SlidingWindowOpParams(stride_h=1, stride_w=1, pad_h=1, pad_w=1, window_h=3, window_w=3, batch_size=1, input_h=30, input_w=18) :: {'act_block_h': 32} -> 17 :: [12, 2] :: 1 :: 1
Fatal Python error: Segmentation fault`

**Expected behavior**
To run without segmentation fault.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: GS

**Comment by pavlejosipovic** [comment]
@HariniMohan0102 
I've test this case on latest main on this branch 
https://github.com/tenstorrent/tt-metal/tree/pjosipovic/test_dispnetres_conv
running `pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_dispnetres_conv2`
and it's working now.

Can we close this one?
