### ISSUE TITLE
Remove use of WH_ARCH_YAML env-var to toggle tensix vs eth dispatch

### ISSUE THREAD

**Issue by tt-asaigal** [tenstorrent/tt-metal#9514]
This should be toggled using a device fixture instead.

**Comment by pgkeller** [comment]
Some issues:
 - need better ethernet dispatch coverage in CI
 - expose in device pool where we manage dynamic (multi cq) dispatch cores.  this is prior to device construction, all devices will run w/ same settings

**Comment by aliuTT** [comment]
Done, it's in main https://github.com/tenstorrent/tt-metal/commit/509b2159ac3af3f6ad2301294a45df5bf1ce7d46
