### ISSUE TITLE
[Bug Report] create_output_tensors which return optional tensors not implemented

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#9552]
**Describe the bug**

https://github.com/tenstorrent/tt-metal/blob/main/docs/source/ttnn/ttnn/dependencies/tt_lib.rst
```C++
struct <NewOperation> {
    void validate_with_output_tensors(const std::vector<Tensor> &input_tensors, const std::vector<std::optional<Tensor>>& output_tensors) const;
    std::vector<Shape> compute_output_shapes(const std::vector<Tensor> &input_tensors) const;
    std::vector<std::optional<Tensor>> create_output_tensors(const std::vector<Tensor> &input_tensors, const std::vector<std::optional<Tensor>>& output_tensors) const;
    operation::ProgramWithOptionalOutputTensors create_program(const std::vector<Tensor>& input_tensors, std::vector<std::optional<Tensor>> &output_tensors) const;

    static constexpr auto attribute_names = std::forward_as_tuple();
    const auto attribute_values() const {
        return std::forward_as_tuple();
    }
};
```
According to the document, there is a `create_output_tensors` function that returns an optional tensor.

```C++
        create_output_tensors_impl_{
            [](const storage_t& storage,
               const Tensors& input_tensors,
               const OptionalTensors& output_tensors) -> const Tensors {
                const auto& operation = *reinterpret_cast<const std::decay_t<T>*>(&storage);
                if constexpr (detail::implements_create_output_tensors_with_optional_output_tensors<T>()) {
                    return operation.create_output_tensors(input_tensors, output_tensors);
                } else {
                    return operation.create_output_tensors(input_tensors);
                }
            }},
```
https://github.com/tenstorrent/tt-metal/blob/main/tt_eager/tt_dnn/op_library/operation.hpp#L586

According to the code, the return value of create_output_tensors is always fixed to Tensors, making it seem that the version returning optional tensors cannot be used.

```C++
 create_program_impl_{
            [](const storage_t& storage,
               const Tensors& input_tensors,
               const OptionalConstTensors& optional_input_tensors,
               OutputTensors& output_tensors) -> CacheableProgram<OutputTensors> {
                const auto& operation = *reinterpret_cast<const std::decay_t<T>*>(&storage);
                if constexpr (detail::implements_create_program<T>()) {
                    TT_ASSERT(optional_input_tensors.empty());
                    return operation.create_program(input_tensors, output_tensors);
                } else if constexpr (detail::implements_create_program_with_optional_input_tensors<T>()) {
                    TT_ASSERT(not optional_input_tensors.empty());
                    return operation.create_program(input_tensors, optional_input_tensors, output_tensors);
                } else {
                    static_assert(tt::stl::concepts::always_false_v<T>, "Operation doesn't implement create_program");
                }
            }},
```
https://github.com/tenstorrent/tt-metal/blob/main/tt_eager/tt_dnn/op_library/operation.hpp#L597

Additionally, based on the code, it appears that the version of create_program which takes optional output as an input parameter is also not implemented.

Problem 1.
Currently, due to the absence of the two functionalities mentioned above, there is an issue when handling multiple optional outputs.

In moreh_layer_norm, there are three optional outputs: `output`, `mean`, and `rstd`. If only two of these are to be returned, supporting optional tensor returns in `create_output_tensors` would allow us to return them in a clear manner, such as `(output, null, rstd)`.

 However, since only tensors are supported in reality, we can only return `(output, rstd)` and must use a separate boolean vector to determine whether the second value in the `vector<tensor>` is `mean` or `rstd`.

Problem 2.
The issue arising from not being able to take optional output as an input parameter in `create_program` is as follows:

As described above, when there are only two optional outputs, instead of having `(output, null, rstd)`, we receive `(output, rstd)` as a vector<tensor>. Therefore, we need to implement additional logic to analyze which tensor is in each position of the vector.

The version of create_program needed for implementing `moreh_layernorm` should accept `inputs`, `optional inputs`, and `optional outputs` as parameters.

**Comment by sangwon-chae** [comment]
@adifrancescoTT Would you please check this bug report with the team? Thanks.

**Comment by arakhmati** [comment]
We have added new way of writing device operations that allows for any type of input/output tensors.

The infra is merged in and we will merge in the documentation soon: https://github.com/tenstorrent/tt-metal/pull/9841

**Comment by hschoi4448** [comment]
Thank you. I will refer to this when working on `TTNN` in the future.

**Comment by arakhmati** [comment]
@hschoi4448 here is the link to the doc:  https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/adding_new_ttnn_operation.html

I will be working on updating it actively and will add more descriptive examples
