### ISSUE TITLE
WatcherFixture.TestWatcherWaypoints non-determinstically fails

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#9566]
https://github.com/tenstorrent/tt-metal/actions/runs/9587337327/job/26437275525
https://github.com/tenstorrent/tt-metal/actions/runs/9587826535/job/26438807217

```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] WatcherFixture.TestWatcherWaypoints

 1 FAILED TEST
  YOU HAVE 4 DISABLED TESTS
```

I've been able to repro this locally with 

```
TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=WatcherFixture.TestWatcherWaypoints --gtest_repeat=-1 --gtest_break_on_failure
```

**Comment by TT-billteng** [comment]
can we disable this test for now @tt-dma ?

**Comment by tt-dma** [comment]
Sure let's disable for now. Do we have any idea when this started, or how often it happens?

**Comment by TT-billteng** [comment]
not sure, it could be due of the switch to libc++ from libstdc++

**Comment by tt-dma** [comment]
This test will be fixed and re-enabled with Paul's next round of runtime arg changes

**Comment by pgkeller** [comment]
I re-enabled this locally, ran on my dual n300 for 100 iterations and everything passed.  Submitted to CI and it failed.  I'm going to assign back to @tt-dma for now to triage the current issue, kick it back to me if needed.

**Comment by tt-dma** [comment]
https://github.com/tenstorrent/tt-metal/pull/10491 Has some fixes/workarounds for this test, we can reopen this issue if it comes back
