### ISSUE TITLE
Request for a new T3K pipeline to run accuracy/perplexity evaluations

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#9613]
As the models team brings up additional tests for evaluating accuracy/perplexity on real datasets, a more suitable ci pipeline will be needed to run the tests. These tests should belong to a separate pipeline than the t3k demo pipeline (which currently contains a couple of these tests) as they are longer running than typical demo tests (due to processing datasets) and different in purpose. The new pipeline would not have to run very frequently, a schedule such as once every other day would suffice.

CC @uaydonat

**Comment by skhorasganiTT** [comment]
@tt-rkim Does this sound okay to you? If so, would you be able to assign as you see fit?

**Comment by cglagovichTT** [comment]
fyi @avoraTT @mikevin920

**Comment by tt-rkim** [comment]
@ttmchiou @TT-billteng 
So this sounds like a nightly sort of pipeline?
Similar to nightly fast dispatch for single card.

**Comment by tt-rkim** [comment]
Note that the more pipelines we have, the higher the load on us to maintain green without more help

**Comment by TT-billteng** [comment]
If there is an owner of the tests on the model side, we can add a new workflow to ensure it's green

**Comment by tt-rkim** [comment]
@uaydonat Any update on getting an owner?
Otherwise we're going to add this, and without proper ownership and care this pipeline will just end up in the same state as the others.

**Comment by uaydonat** [comment]
Any tests we add to these nightly/bi-nightly CIs will be owned by the model owners just like in post-commit CIs.

I think @skhorasganiTT 's ask here is to have a bi-nightly CI because the perplexity tests that he (and other team members) will add will take hours to run.

**Comment by TT-billteng** [comment]
Can we wait until we get the new cloud T3K machines up and running and see how overloaded (or not) they are?

**Comment by uaydonat** [comment]
> Can we wait until we get the new cloud T3K machines up and running and see how overloaded (or not) they are?

This pipeline can run every other day, or twice a week, or even once a week on the weekends if necessary. We do not want this to be a burden on the machine workload, so we should not need to wait for new machines.

**Comment by ttmchiou** [comment]
Are there any other tests to be run here for this pipeline besides the one listed?
Who would be the owner?
@uaydonat @skhorasganiTT  
pytest  tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py -k nightly
pytest  tests/tt_eager/python_api_testing/unit_testing/misc/test_reduce_scatter_nightly.py

**Comment by SeanNijjar** [comment]
> Are there any other tests to be run here for this pipeline besides the one listed? Who would be the owner? @uaydonat @skhorasganiTT pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py -k nightly pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_reduce_scatter_nightly.py

Just making sure we're on the same page. I'm the owner of these two listed tests but someone else will own these new correctness based pipelines.

**Comment by skhorasganiTT** [comment]
@ttmchiou The model correctness/stress tests will be owned by the model team as per Utku's comment above. We can add the tests in when the pipeline is ready. @SeanNijjar I'm not sure if this would be a suitable location for the CCL op tests since this pipeline may run infrequently (e.g. once a week) and you probably want those to be run nightly, is that correct?

**Comment by SeanNijjar** [comment]
That's right. I'd want my ccl op nightly tests ideally run once a day

**Comment by uaydonat** [comment]
Our request to have a infrequent pipeline (maybe twice a week for now) to run the perplexity tests. We will own this pipeline and we have add new tests to it.

@SeanNijjar maybe you can file a separate issue for a nightly pipeline to put your tests in.

**Comment by SeanNijjar** [comment]
> Our request to have a infrequent pipeline (maybe twice a week for now) to run the perplexity tests. We will own this pipeline and we have add new tests to it.
> 
> @SeanNijjar maybe you can file a separate issue for a nightly pipeline to put your tests in.

Sounds good. At the moment, there is already a place for these "nightly" ccl tests so there is no additional ask. Since the new tests mentioned in this issue are going to be a separate pipeline altogether, there is no need for changes for my tests.

**Comment by ttmchiou** [comment]
@skhorasganiTT @uaydonat 
t3k weekly perplexity test pipeline is online and available. Runs every saturday at noon.
Frequency can be adjusted as we see what kind of loads this pipeline will see
