### ISSUE TITLE
TestPrintFromAllHarts hangs on N300x2

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#9615]
100% repeatable even as a single test (ie, not carried state)
N300's configured in a mesh
Last output looks like:
                   Test | INFO     | Running test on device 0.
                   Test | INFO     | Finished running test on device 0.
                   Test | INFO     | Running test on device 1.
                   Test | INFO     | Finished running test on device 1.
                   Test | INFO     | Running test on device 2.
^C

**Comment by pgkeller** [comment]
Issue was repeatable even after resets. Rebooted and it still hung, but now on device 3.  Odd...

**Comment by pgkeller** [comment]
Also, fast dispatch unit test hung in: TestWatcherRingBufferErisc

**Comment by tt-dma** [comment]
First issue is a confirmed bug and fixed with above commit. Second issue filed separately, will look at if we decide N300x2 support is needed (the test runs fine on N300x1 and T3000): https://github.com/tenstorrent/tt-metal/issues/13649
