### ISSUE TITLE
Update the README instructions in v49 and main for ResNet to use the functional demo pytest script 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#9621]
**Describe the bug**
The link to ResNet demo suggests an older version for pytest that errors out on v49. the command should be updated from 

`pytest --disable-warnings models/demos/resnet/demo/demo.py::test_demo_sample[8-models/demos/resnet/demo/images/]`

to `pytest models/demos/resnet/tests/test_metal_resnet50_2cqs_performant.py::test_run_resnet50_2cqs_inference[LoFi-activations_BFLOAT8_B-weights_BFLOAT8_B-batch_20-device_params0]`

Please also correct any other potentially outdated suggested pytest command in the README for ResNet. 

**To Reproduce**
1. checkout to  v49 tag
2. build via v49 instructions (built from src)
3. run: `pytest --disable-warnings models/demos/resnet/demo/demo.py::test_demo_sample[8-models/demos/resnet/demo/images/]`
4. you will see a segmentation fault error
5. 
![image](https://github.com/tenstorrent/tt-metal/assets/132954887/606e87b8-9e12-422c-b390-db1755d5ca10)

**Expected behavior**
updated to the functional script:
`pytest models/demos/resnet/tests/test_metal_resnet50_2cqs_performant.py::test_run_resnet50_2cqs_inference[LoFi-activations_BFLOAT8_B-weights_BFLOAT8_B-batch_20-device_params0]`

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software ([v0.49.0](https://github.com/tenstorrent/tt-metal/tree/v0.49.0/models/demos/resnet))
- GS e150

**Comment by mywoodstock** [comment]
The readme was fixed with the B=20 version through this commit: https://github.com/tenstorrent/tt-metal/commit/3f6dab2dc4c3eba3380533f68fd209768807691f
