### ISSUE TITLE
Move Binary backward ops to ttnn

### ISSUE THREAD

**Issue by umadevimcw** [tenstorrent/tt-metal#9628]
Migrating binary backward ops to TTNN 
Master issue : #9322 

### List of binary ops 
Implementation PRs - #9570 (Set 1), #9771 (Set 2), #9846 (Set 3)

- [x] complex backward ops - #9806 
- [x] atan2_bw
- [x] embedding_bw
- [x] addalpha_bw (without optional return support )
- [x] add_bw
- [x] subalpha_bw (without optional return support )
- [x] sub_bw
- [x] hypot_bw
- [x] squared_difference_bw
- [x] ldexp_bw
- [x] xlogy_bw
- [x] logaddexp_bw
- [x] lodaddexp2_bw
- [x] binary_eq_bw
- [x] concat_bw
- [x] bias_gelu_bw
- [x] binary_le_bw
- [x] rsub_bw
- [x] binary_assign_bw
- [x] binary_ne_bw
- [x] binary_ge_bw
- [x] binary_lt_bw
- [x] binary_gt_bw
- [x] div_bw
- [x] max_bw
- [x] min_bw
- [x] lerp_bw
- [x] mul_bw

**Comment by VirdhatchaniKN** [comment]
Tracking #10163 separately. Closing this issue for now
