### ISSUE TITLE
Conv fails with "Statically allocated circular buffers" error

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#9629]
**Describe the bug**
In the DispNetRes module of Fadnet++ functional model, conv op fails in 2 input configurations with the following error:
`Statically allocated circular buffers in program {} clash with L1 buffers on core range [(x=0,y=0) - (x=11,y=8)]. L1 buffer allocated at {} and static circular buffer region ends at {}`

**To Reproduce**
1. Checkout to the branch [harini/dispnetres_conv_unittest](https://github.com/tenstorrent/tt-metal/compare/harini/dispnetres_conv_unittest)
2. Run the following command to reproduce the issue: `pytest tests/ttnn/unit_tests/operations/test_conv2d.py::test_dispnetres_conv`

**Expected behavior**
To run conv op for the specific input configurations without error.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: GS

**Comment by mywoodstock** [comment]
@HariniMohan0102 I believe this should be resolved now, could you please give it a try?

**Comment by pavlejosipovic** [comment]
@HariniMohan0102 I was able to run these test cases on latest main with auto shard and with disabling output in row major
here is the branch https://github.com/tenstorrent/tt-metal/tree/pjosipovic/test_dispnetres_conv
To get row major output you can run a separate op after conv.
Is this good enough for you?

**Comment by mbahnasTT** [comment]
yes, thanks @pavlejosipovic
