### ISSUE TITLE
Optimize folding of first conv input to Resnet on host

### ISSUE THREAD

**Issue by sankarmanoj-tt** [tenstorrent/tt-metal#9685]
**Is your feature request related to a problem? Please describe.**
Conv Input folding is currently implemented in Python.

**Describe the solution you'd like**
Implement folding using torch APIs like reshape & permute.

**Describe alternatives you've considered**
On-device op for folding of inputs

**Additional context**

**Comment by sankarmanoj-tt** [comment]
Old time taken is  0.8824536800384521 s
New time taken is  0.009305953979492188 s

**Comment by davorchap** [comment]
> Old time taken is 0.8824536800384521 s New time taken is 0.009305953979492188 s

the new time of 9.3 ms -- is this on host or device?

is this the fast host OP variant that @tt-aho and @tt-asaigal have been working on, or a different impl?

**Comment by tt-aho** [comment]
This is a separate impl.
I think the 9ms measurement doesn't include everything needed for preprocessing (it's just fold). There is still a permute and pad afterwards, and when we write data to device we will need to make the data contiguous. I need to recollect current perf data to see if this is still accurate but for the GS Resnet, we were last targeting ~2-3ms for total preprocessing

**Comment by sankarmanoj-tt** [comment]
This time includes folding, permutation and padding.

**Comment by tt-aho** [comment]
> This time includes folding, permutation and padding.

I see, so this measurement doesn't come from the `test_pad_fold.py` script then? As I see in that script it only measures `pad_and_fold_act_2`, but the actual `preprocessing` function does `pad_and_fold_act_2`, and then a permute and pad.

**Comment by mywoodstock** [comment]
@yugaoTT FYI
