### ISSUE TITLE
CI: When a test crashes remaining tests in the pipeline are not run

### ISSUE THREAD

**Issue by uaydonat** [tenstorrent/tt-metal#9692]
Here is an example: 

https://github.com/tenstorrent/tt-metal/actions/runs/9658690952/job/26640646448

because `test_llama_decoder_t3000.py` fails with some invalid cache error, the test that comes after it is not run.

 ```
pytest models/experimental/llama2_70b/tests/test_llama_decoder_t3000.py
 pytest models/experimental/llama2_70b/tests/test_llama_model_t3000.py

```

FYI @skhorasganiTT @mtairum @cglagovichTT @tt-rkim @TT-billteng @ttmchiou

**Comment by uaydonat** [comment]
The feedback from Raymond:

> If someone on your team has time, then we'd love for them to do something similar to tests/scripts/single_card/nightly/run_wh_b0_only.sh . We create symlinks in the tests/ folders and point it to the appropriate pytest file. We can then do pytest <path_to_symlinks> which will run everything, even if one fails. We can make folders such as tests/performance/t3000_e2e_perf , tests/demos/t3000 etc. This will require pytests to be refactored so that only the appropriate tests are captured. We had an understanding of this with the models team to eventually do this in https://github.com/tenstorrent/tt-metal/issues/7586

**Comment by tt-rkim** [comment]
Yes, for example check out this new folder we made a while back for nightly fast dispatch on single-card:

```
rkim@Raymond-Kim's-Macbook-Pro tt-metal % find tests/nightly/wh_b0_only/ -type l
tests/nightly/wh_b0_only//tests/ttnn/integration_tests/unet
tests/nightly/wh_b0_only//models/demos/mamba/tests/test_mamba_ssm.py
tests/nightly/wh_b0_only//models/demos/mamba/tests/test_benchmarks.py
tests/nightly/wh_b0_only//models/demos/mamba/tests/test_residual_block.py
tests/nightly/wh_b0_only//models/demos/mamba/tests/test_mamba_block.py
tests/nightly/wh_b0_only//models/demos/mamba/tests/test_mamba_demo.py
tests/nightly/wh_b0_only//models/demos/mamba/tests/test_full_model.py
tests/nightly/wh_b0_only//models/demos/mamba/tests/test_reference_model.py
tests/nightly/wh_b0_only//models/demos/wormhole/mistral7b/tests/test_mistral_embedding.py
tests/nightly/wh_b0_only//models/demos/wormhole/mistral7b/tests/test_mistral_rms_norm.py
tests/nightly/wh_b0_only//models/demos/wormhole/mistral7b/tests/test_mistral_mlp.py
```

You can see that these are symlinks to already existing files elsewhere in the repo. Namely `models/`, which your team obviously touches a lot.

We would like to reduce the scripts to target only one directory with pytest so your team and anyone else doesn't have to add cases manually. In fact, we don't like that convention, and we ask that future tests be written in a way that all tests you want are captured by calling on such a directory. This means going forward, unless we're making a new pipeline, there should be very few changes to the test scripts.

This means that the above files do not contain tests that are not meant to be run on single-card. This would require some refactoring of your tests on the model teams part. I have already given this feedback to some PRs from the models team. This is your action item. We can help with direction.

Test script example for single-card nightly fast dispatch:

```
rkim@Raymond-Kim's-Macbook-Pro tt-metal % cat tests/scripts/single_card/nightly/run_wh_b0_only.sh 
#/bin/bash

set -eo pipefail

if [[ -z "$TT_METAL_HOME" ]]; then
  echo "Must provide TT_METAL_HOME in environment" 1>&2
  exit 1
fi

echo "Running nightly tests for WH B0 only"

# Ideally only one command here
env WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest tests/nightly/wh_b0_only_eth
env pytest tests/nightly/wh_b0_only
```

**Comment by tt-rkim** [comment]
Here is a specific example of what I do NOT want to see. This is from T3K demos:

```
  # Falcon7B demo (perf verification and output verification)
  WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest --disable-warnings -q -s --input-method=json --input-path='models/demos/t3000/falcon7b/input_data_t3000.json' models/demos/t3000/falcon7b/demo_t3000.py::test_demo_multichip[user_input0-8-True-perf_mode_stochastic_verify]
  WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest --disable-warnings -q -s --input-method=json --input-path='models/demos/t3000/falcon7b/input_data_t3000.json' models/demos/t3000/falcon7b/demo_t3000.py::test_demo_multichip[user_input0-8-True-default_mode_greedy_verify]

  # Falcon7B perplexity test (prefill and decode)
  WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/demos/falcon7b/tests/test_perplexity_falcon.py::test_perplexity[True-prefill_seq1024_dram]
  WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/demos/falcon7b/tests/test_perplexity_falcon.py::test_perplexity[True-decode_1024_l1_sharded]
```

We don't want to see `::` or `[]`. The answer is to split out the tests into more specialized files. We already have buy-in from models team members like @cglagovichTT

**Comment by TT-billteng** [comment]
fixed by @vtangTT https://github.com/tenstorrent/tt-metal/pull/9677
