### ISSUE TITLE
classification model bring up

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#9694]
**Is your feature request related to a problem? Please describe.**
Bring up classification model on TTNN
needs support for convs with dilation > 1 

please checkout to this [commit](https://github.com/tenstorrent/tt-metal/commit/29402c69ea2611ef2b17d745a2fd8f9f7dfac7d8)

and run` pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_model_k_new_conv`

system info:
Ubuntu 20
E150

**Comment by mywoodstock** [comment]
@dvartaniansTT 
I take that this issue is for us to add support for dilation > 1 in convs. 
Can we update the title/description to reflect this? (I am assuming the model bringup is in someone else's plate?)

**Comment by saichandax** [comment]
@mywoodstock ,
We don't have the implementation in a branch.
however, the commit in the description has unti tests for dilation>1 support request, as you mentioned.

**Comment by mywoodstock** [comment]
@dvartaniansTT The support for dilation > 1 has landed in `main`. I think we can close this?

**Comment by mbahnasTT** [comment]
Thanks @mywoodstock !
