### ISSUE TITLE
[Bug Report]  resnet demo failed on E150

### ISSUE THREAD

**Issue by yasuhiroitoTT** [tenstorrent/tt-metal#9704]
**Describe the bug**
Resnet demo failed with Segmentation fault. 

**To Reproduce**
1. Building the latest metalium by cloning master release
2. Kicking 'pytest --disable-warnings models/demos/resnet/demo/demo.py::test_demo_sample[8-models/demos/resnet/demo/images/]'

**Expected behavior**
Model execution finished with throughput . 

**Screenshots**

<img width="1094" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/113104662/d2530c90-d9ca-419e-b6aa-139ec269fcab">

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Version of software: metallium commit id: dc6ab5d592345f583964216a4f54ee7adcfdb82e
- FW, KMD: see attached  
<img width="1114" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/113104662/a29cf0d9-75c7-4b53-83e4-100f1a3a02a8">

**Additional context**

**Comment by tt-aho** [comment]
This has been resolved on latest main. The new command should be `pytest --disable-warnings models/demos/resnet/demo/demo.py::test_demo_sample[20-models/demos/resnet/demo/images/-device_params0]` if you rebase to 3f6dab2 or later
