### ISSUE TITLE
Move single-card WH device perf pipeline to a virtual machine to reduce load on WH perf machine

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#9714]
Per @tt-aho and @mo-tenstorrent , we can likely move to a regular VM for this pipeline and increase timeout to account for slower host, rather than eat up precious cycles on the WH perf machine.

**Comment by tt-rkim** [comment]
Getting `inf` on falcon seq 2048, need to check if it's only on BM
Checking on BM now: https://github.com/tenstorrent/tt-metal/actions/runs/9715218511/job/26816092749

**Comment by tt-rkim** [comment]
Damn you right, it did get killed. We don't record exit code but likely

```
Loading decoder layers: 100%|██████████| 32/32 [00:12<00:00,  2.54it/s]Killed
```

How sad.

Should we spin up a VM with some higher RAM and see how it does? @TT-billteng @ttmchiou  It would go against our 48GB VM pattern.

**Comment by TT-billteng** [comment]
I don't see a high RAM option for WH VM?

**Comment by tt-rkim** [comment]
You're right...

**Comment by tt-rkim** [comment]
Should we ask cloud to make one? Either that, or we may need to take away a WH BM from devs...

**Comment by tt-rkim** [comment]
Yeah not enough memory.
