### ISSUE TITLE
Extend build-artifacts to produce profiler build, preferably on demand

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#9715]
This is to enable build-artifacts flow for profiler-based jobs

Not blocking or critical, but definitely will be a big step up and will reduce load on our machines

cc: @TT-billteng @ttmchiou @mo-tenstorrent

**Comment by mo-tenstorrent** [comment]
Can we have non-post commit jobs (e.g. device perf) to pick up the correct build artifact as well. Post commit must have made it by the time they get to run

**Comment by tt-rkim** [comment]
Done so closing for now, but recording here that:

We see errors on tracy builds when built with `e04cs05`: #10375
