### ISSUE TITLE
test_nlp_create_qkv_heads_decode tests failing without L1 clear

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent/tt-metal#9719]
For minimum repro, on N150 or N300 or T3000:
PASSING:
```
git checkout main
pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_nlp_create_qkv_heads_decode.py
```

FAILING:
```
git checkout main
TT_METAL_CLEAR_L1=0 pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_nlp_create_qkv_heads_decode.py
```

If you try to use ethernet or profiler, it may be buggy, since there are some L1 state variables there that actually need to be set to 0. Maybe try cherry-picking `812f513c99`.

**Comment by cglagovichTT** [comment]
@mikevin920 is on this

**Comment by caixunshiren** [comment]
fixed. Turns out the issue is in the test case. We were comparing the padded parts to ground truth and we assumed the padded part being 0s. For maximum perf, there's no need to explicitly write 0 to the padded part because they will be masked out anyway.
