### ISSUE TITLE
Publish nightly builds as pre-releases instead of drafts

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/tt-metal#9725]
**Context**
We are building a compiler on top of ttnn here
https://github.com/tenstorrent-metal/pytorch2.0_ttnn/

This python module depends on ttnn wheel. Library is under active development and requires frequent update and test with latest ttnn wheel. Unfortunately, there is no convenient way to access latest nightly wheels of ttnn. Thats because they are not published and stay as drafts. 

**Expected behavior**
Please publish nightly builds with ttnn wheels artifacts as pre-release, instead of a draft release.

**Comment by tt-rkim** [comment]
Do you know off the top of your head if we can have multiple pre-releases?

We could also weekly scrub pre-releases of previous versions, if you have any input on scrubbing.

**Comment by ayerofieiev-tt** [comment]
@tt-rkim yes, I checked it yesterday - we can have multiple pre-releases.

I recommend to discuss the retention policy with @TT-billteng . 
Ideally we want things clean, but I don't know how heavy is the lift.

I'd typically upload artifacts to Google Cloud Storage, specify short life by default and only retain explicitly if needed. That's important for GCS because you pay $$$ for storage. But as we leverage Github, I am not sure what are the cost implications.

**Comment by tt-rkim** [comment]
Github artifact and release storage are completely, 100% FREE :)

And sounds good, will widely publish a retention policy once we're confident. For now we're going with GitHub defaults, which I believe is 90 days for drafts.

**Comment by ayerofieiev-tt** [comment]
@tt-rkim sounds good! This is not urgent, but can you set an expectation on when you think we can start publishing?

**Comment by tt-rkim** [comment]
Can we close?

**Comment by tt-rkim** [comment]
Or are there other issues with the wheel per what we saw yesterday? @artem
