### ISSUE TITLE
ResNet50: Investigate PCC error for B=16 on WHB0 (New version)

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#9734]
Branch: `asarje/resnet-highres-20240624`
Test: `pytest "tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet50_new.py::test_resnet_50[batch_size=16-act_dtype=DataType.BFLOAT8_B-weight_dtype=DataType.BFLOAT8_B-math_fidelity=MathFidelity.LoFi-device_params={'l1_small_size': 24576}]"`

The PCC is about 0.72, needs investigation/debugging.

**Comment by shwetankTT** [comment]
Completed.

**Comment by mywoodstock** [comment]
Thanks @nkpatel-tt and @shwetankTT  for the investigation. This is now done.
