### ISSUE TITLE
Deprecate old conv. Delete code from python and c++. Deprecate all ttnn and ttlib tests that use old conv api.

### ISSUE THREAD

**Issue by tt-nshanker** [tenstorrent/tt-metal#9738]
Current issues that prevent deprecation of old conv:

(TODO: please add links to the issues below)

- [x] 1. Enable all tests that use new conv api in CI (like Resnet50 with new conv api on GS) -
- [x] 2. Resnet50 with new conv api on WH - 
- [x] 3. SD conv unit tests with new conv api on WH - 
- [x] 4. Shallow Unet with new conv api on GS and WH - 

All 3 above tests with new conv api must be enabled in CI after they are fixed.

Note: by "old conv" I mean the sharded version of conv which uses old conv api (the non-JIT version). The files for this conv are under ttnn (python) and ttlib (c++) folders.

"ttlib old conv" is the non sharded version of conv which is not exposed in ttnn and all files for that can be deleted now. Nothing is gating the deprecation for that.

**Comment by bbradelTT** [comment]
Last part was done in https://github.com/tenstorrent/tt-metal/issues/12009 and two corresponding PRs:
- https://github.com/tenstorrent/tt-metal/pull/12270
- https://github.com/tenstorrent/tt-metal/pull/12400

Closing
