### ISSUE TITLE
Test prefetcher hanging with changes to get around asserts

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent/tt-metal#9778]
Repro hang:
- `git checkout aliu/test-prefetcher-hang`
- `CONFIG=Release ./build_metal.sh` or `CONFIG=Debug ./build_metal.sh`
- `TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/perf_microbenchmark/dispatch/test_prefetcher -t 1 -i 5 -ss 16384`

The changes on the branch are to get around asserts seen with Debug build. Seems like the test should be still valid, but probably a new test case.

**Comment by pgkeller** [comment]
I reproduced the hang, fixed a couple of test sizes, then cannot reproduce a hang on either GS or WH after a few hundred iterations.

**Comment by aliuTT** [comment]
Changes in main. Closing
