### ISSUE TITLE
Complex backward ops Blockers

### ISSUE THREAD

**Issue by Aswinmcw** [tenstorrent/tt-metal#9806]
**Complex binary ops are need to be merged to TTNN**

- [x] complex_mul_bw
- [x] complex_div_bw
- [x] complex_sub_bw
- [x] complex_add_bw

**Issues:**
Complex ops are implemented in two methods. One is using separate Complex structure and another one is using regular tensor by splitting into two like a tensor of [1,1,32,64] contains the first [1,1,32,32] as real part and the next [1,1,32,32] as imaginary part.
We need clarification on how to proceed with this.

**Comment by eyonland** [comment]
@arakhmati and I took a look at this together.   We are going to keep ComplexTensor as-is for now.  In the future ComplexTensor itself needs to be updated a bit differently but the general idea is about right.  However the code within the `#define CHECK_FOR_COMPLEX ` looks like garbage to both of us.  We like ComplexTensor implementations but we both really do not like this other ugly looking code that uses the splitting like you described.  This code will end up being hard to maintain.   I would rather us re-code these ups with the ComplexTensor.  Can you help me understand the scope creep here?

**Comment by VirdhatchaniKN** [comment]
Implementation in #10003
