### ISSUE TITLE
[Blackhole bringup] Hitting ASSERT(count <= (mcast ? max_write_packed_cores / 2 : max_write_packed_cores)) in RT args tests

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#9815]
See [test spreadsheet](https://docs.google.com/spreadsheets/d/1LxyKnAyXay92LaXhtOjkP1hJIhUQbN_39JPpuKzDicc/edit?pli=1&gid=1343607013#gid=1343607013) for the specific tests

**Comment by tt-aho** [comment]
If you're able to rebase to latest this issue might go away. We added some host side support for splitting cmds that exceed this threshold.

**Comment by abhullar-tt** [comment]
> If you're able to rebase to latest this issue might go away. We added some host side support for splitting cmds that exceed this threshold.

Thanks, I'll try that! Im not sure this is a true error or if there is some alignment issue thats causing that is causing count to be picked up as an incorrect value so I need to double check that

**Comment by abhullar-tt** [comment]
Fix on branch, the BH compute grid is larger than 108 cores but we have hardcoded `constexpr uint32_t max_write_packed_cores = 108;`

Passing this in as a compile time arg now
