### ISSUE TITLE
Apply first solution of the stagger on all matmul ops

### ISSUE THREAD

**Issue by ttmtrajkovic** [tenstorrent/tt-metal#9857]
Identify all the ops that invoke matmul operations. These are currently:
```
op_library/bmm/kernels/compute/bmm_large_block_zm_fused_bias_activation.cpp
op_library/bmm/kernels/compute/bmm_large_block_zm_fused_bias_activation_inline_untilize_out.cpp
op_library/sdpa/kernels/compute/sdpa_noncausal.cpp
op_library/sdpa/kernels/compute/sdpa.cpp
```

The length of stagger is set to 12k cycles which has been confirmed on the scope to help for both n150 and n300. This value will be tuned later, but right now it is best to proceed with this value and aim for fixing instabilities.

Current plan for rolling this out:
 - **[@pavlepopovic]** Apply the stagger to matmul ops that are not convolutions. Convs are short and 12k stagger will impact them, besides, they are low utilized and just margin seems to work
 - **[@pavlepopovic]** For matmul ops where stagger will be applied, apply it on ops bigger than 48 cores (6x8)
 - **[@pavlepopovic]** For matmul ops where stagger will be applied, apply it on Wormhole B0 arch only, exclude for others
 - **[@ttmtrajkovic/syseng]** Milos provided alternate solution for stagger, fully implemented in LLKs, without OP logic to determine which cores to delay. Syseng team needs to verify this on scope to confirm the same effects as previous solution

FYI @uaydonat, @davorchap, @jvasilje, @s-jovic, @pavlejosipovic 

Milos

**Comment by pavlepopovic** [comment]
Note: make sure to do this for WH only, and exclude GS and BH

**Comment by davorchap** [comment]
Also Convs

**Comment by ttmtrajkovic** [comment]
> Also Convs

@davorchap, what did you mean by this, exclude the solution for convs or include it for convs? The initial plan is to **exclude** it for convs (as per first bullet)

**Comment by uaydonat** [comment]
We saw 8x7 matmuls do not hit di/dt issues, so we use 8x7 grid in our models. 

Should we apply stagger only to 8x8 matmuls maybe? 

We want to reduce perf hit in models as much as possible. Even if the perf hit is temporary, it will make perf tracking harder.

**Comment by pavlepopovic** [comment]
@uaydonat we’ve had a 57 core grid hit a di/dt in7b prefill, so it’s not 8x8 only, so we don’t have an exact defintion of a core grid that makes di/dt happen.
So the current plan is to apply it only to big matmuls ( > 48 cores, that was chosen arbitrarily). Does that sound ok?

**Comment by ttmtrajkovic** [comment]
@uaydonat, my first goal here is stability and not perf so I'd prefer to be on the safer side (hence, to apply to every op). I can't guarantee that anything more than half cores doesn't have a problem because staggering half cores is what helps. 
I am not sure how much workarounds like 8x7 have been tested because we could've only reduced the repro rate.

on large LLMs that take milions of cycles, how much perf impact is really 12k cycles? Are we talking bigger than 1%?
Convolutions are a different story which is why we plan to skip them, but didt stability has been hitting us really bad so I'm hoping we can suffer few pct of perf on this - definitely better than running at lower AICLK.


Milos

**Comment by uaydonat** [comment]
@s-jovic or @johanna-rock-tt may have more specific numbers, but in the worst case, the extra 12k cycles may degrade perf 3-4%. The overall llm takes millions of cycles, but there 6-7 matmuls per layer, and 60-80 layers. It depends on how many of these are using >48 cores.

However, I agree, if we cannot guarantee stability if we use more half the cores, then it makes sense to take the perf hit for stability. Hopefully, we can reduce the overhead soon.

**Comment by s-jovic** [comment]
`TT_METAL_ENABLE_STAGGER` env var can be set to enable stagger on matmuls running on more than 48 cores (wh_b0). Commit: https://github.com/tenstorrent/tt-metal/commit/53f02fb796a78c6b9af04f1684f4c28ec8b058fd

@ttmtrajkovic can we close the issue?

**Comment by ttmtrajkovic** [comment]
Yes, all is good - thank you @s-jovic.
