### ISSUE TITLE
[Bug Report] N300 hangs on the second call when calling CreateDevice for each device.

### ISSUE THREAD

**Issue by namhyeong-kim** [tenstorrent/tt-metal#9860]
**Describe the bug**
On N300, `tt::tt_metal::GetNumAvailableDevices()` returns 2. Calling `CreateDevice(0)` and then `CreateDevice(1)` results in a hang on the second call `CreateDevice(1)`.
Additionally, running `run_many_times.cpp` also causes a hang when calling `CreateDevice` for each device as shown in the code snippet.

```cpp
auto num_devices = tt::tt_metal::GetNumAvailableDevices();
vector<Device*> devices_;
for (unsigned int id = 0; id < num_devices; id++) {
    // It hangs when id = 1.
    auto* device = tt::tt_metal::CreateDevice(id);
    devices_.push_back(device);
}
```

**To Reproduce**
1. build tt-metal repo with build_metal.sh
2. run command `TT_METAL_SLOW_DISPATCH_MODE=1 build/test/tt_metal/unit_tests_frequent`
3. It hangs.

**Expected behavior**
N300 should not hang when calling `CreateDevice` for each device.

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by razorback3** [comment]
@adifrancescoTT Would you help triaging this issue? (cc. @sangwon-chae)

**Comment by aliuTT** [comment]
Taking a look

**Comment by aliuTT** [comment]
Hmm it seems like we have limited testing  for Slow Dispatch with multi device create and close. @tt-dma Do you know if `TT_METAL_SLOW_DISPATCH_MODE=1 build/test/tt_metal/unit_tests_frequent` is in CI for N300?

**Comment by aliuTT** [comment]
@namhyeong-kim Do you have need for multi device testing to work with Slow Dispatch? Is it possible to leverage Fast Dispatch for your use case? That is the main flow for ops/models testing that ttmetal supports.

**Comment by namhyeong-kim** [comment]
Without Slow Dispatch, `run_many_times.cpp` hangs on the second call, and we do not use Slow Dispatch in our application.
It hangs on below code snippet which temporarily comments out the slow dispatch check section.
Command : `TT_METAL_SLOW_DISPATCH_MODE=0 build/test/tt_metal/unit_tests_frequent`

```cpp
TEST(Common, AllCoresRunManyTimes) {
    // Temporarily comment out the slow dispatch check section below
    // auto slow_dispatch = getenv("TT_METAL_SLOW_DISPATCH_MODE");
    // Skip fast dispatch until it's supported for remote device.
    // if (!slow_dispatch)
    //    GTEST_SKIP();
    // Run 500 times to make sure that things work
    for (int idx = 0; idx < 500; idx++) {
        log_info(LogTest, "Running iteration #{}", idx);
        // Need to open/close the device each time in order to reproduce original issue.
        auto num_devices = tt::tt_metal::GetNumAvailableDevices();
        vector<Device*> devices_;
        for (unsigned int id = 0; id < num_devices; id++) {
            auto* device = tt::tt_metal::CreateDevice(id);
            devices_.push_back(device);
        }

        // Run the test on each device
        for (Device *device : devices_) {
            RunTest(device);
        }

        // Close all devices
        for (unsigned int id = 0; id < devices_.size(); id++) {
            tt::tt_metal::CloseDevice(devices_.at(id));
        }
    }

}
```

**Comment by aliuTT** [comment]
For FD mode, there are some api changes. I can push that for this test.

**Comment by aliuTT** [comment]
Check out the latest version of this test file. That should be the device init apis going forward for multi device. We will probably deprecate CreateDevice for non-mmio devices.
