### ISSUE TITLE
CCL ops support for Galaxy 2D grid configuration

### ISSUE THREAD

**Issue by mikevin920** [tenstorrent/tt-metal#9866]
**Proposal:**
Add optional parameters in CCL ops to all_gather or all_reduce along a specific axis if device_mesh is initialized as a 2D  grid.

**1. All-reduce along y:**
  `FF2_act = ttnn.all_reduce(FF1_output, op=ttnn.ReduceOp.SUM, cluster_axis=1)`
**2. All-gather along x:**
  `output = ttnn.all_gather(output, dim=3, cluster_axis=0)`

Open questions:

- [ ] Does multi-device tensors know how to gather on a specific cluster axis?
- [ ] Should we pass in device_mesh to the CCL ops, and should device_mesh contain in the info of the cluster shape?

**Example:**
First open device mesh with this config:
```
  device_grid, device_ids = ttnn.DeviceGrid(4, 8), ttnn.get_device_ids() # User determined
  multi_device = ttnn.open_device_mesh(device_grid, device_ids)
```
Then shard activations and weights in this way:
```
act = ttnn.from_torch(
    act_pt,
    dtype=ttnn.bfloat16,
    layout=ttnn.TILE_LAYOUT,
    device=device_mesh,
    mesh_mapper=ShardTensor2dMesh(device_mesh, dims=(3, None), cluster_shape=cluster_shape),
)
# shape=Shape([1, 1, 32, 2048]) on 32 devices
weights = ttnn.from_torch(
    weights_pt,
    dtype=ttnn.bfloat8_b,
    layout=ttnn.TILE_LAYOUT,
    device=device_mesh,
    mesh_mapper=ShardTensor2dMesh(device_mesh, dims=(2, 3), cluster_shape=cluster_shape),
)
# shape=Shape([1, 1, 2048, 4096]) on 32 devices
```

Llama FF1_output tensors after matmul on 32 devices sharded on a **(4,8) grid** each is **Shape([1, 1, 32, 4096])**,

We want to all-reduce along the x axis in groups of 4 
**All-Reduce along x axis**
`FF2_act = ttnn.all_reduce(FF1_output, op=ttnn.ReduceOp.SUM, cluster_axis=0)`
FF2_act is replicated along the x axis **4 times**, **shape is (1, 1, 32, 4096)**

After FF2 matmul we want to all-reduce along the y axis in groups of 8
**All-Reduce along y axis**
`output = ttnn.all_reduce(FF2_output, op=ttnn.ReduceOp.SUM, cluster_axis=1)`
output is replicated along the y axis **8 times**, **shape is (1, 1, 32, 2048)**

Finally we do an **All-Gather along the x axis** to assemble the final output back to
the original shape of (1, 1, 32, 8192) with every device having a complete activation tensor
`output = ttnn.all_gather(output, dim=3, cluster_axis=0)`

**Diagram:**
<img width="779" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/45493463/e1e408d7-472e-430a-be89-befb60ecac5c">

<img width="837" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/45493463/cfa2a30a-b211-4b8e-bac9-457f8060c1a1">

**Comment by aliuTT** [comment]
@SeanNijjar Do you know the status of AllReduce op? If there are any plans to add that op anytime soon?

**Comment by SeanNijjar** [comment]
@aliuTT There is currently no all-reduce op but this general ask applies to all CCL ops since it's more of a mesh (tensor) and op invocation concern.

**Comment by mikevin920** [comment]
Requested support from ttnn multidevice: 
- ttnn.all_gather with a multidevice tensor, device mesh, dim, and cluster axis firing off all the linear allgathers that are necessary

Eg.
The user would supply a multi-device tensor initialized from the 2d cluster shape (4,8) , calling `output = ttnn.all_gather(output, dim=3, cluster_axis=0)` would group the first 4 tensors in a group and linearly all-gather them on dim=3. The result would be the same tensor replicated 4 times in the first row and similariy the other rows would also linear all-gather on dim=3.

**Comment by cfjchu** [comment]
Hey @mikevin920 / @cglagovichTT, I synced with @SeanNijjar and @aliuTT. To make progress on this issue we need:
- https://github.com/tenstorrent/tt-metal/pull/9909 to be merged
- https://github.com/tenstorrent/tt-metal/issues/10166

Once those are merged, I can make progress on your request.

**Comment by aliuTT** [comment]
I've merged changes for getting devices by row and col: https://github.com/tenstorrent/tt-metal/issues/10166.

**Comment by uaydonat** [comment]
Raising priority to P0 since this is blocking llama bring up on Galaxy's.

**Comment by SeanNijjar** [comment]
Is there anything else blocking progress here?

**Comment by cfjchu** [comment]
I'm unblocked to make progress on this issue. I'll prioritize this work to unblock llama galaxy bringup

**Comment by SeanNijjar** [comment]
btw in terms of the workaround that model team is currently doing to get the model working on TG (i.e. copying back to host and running all-gather). Is there a reason we're not just manually invoking the parallel all-gather ops per line, similar to how we used to invoke all gather several months ago by manually launching the all-gather kernel per chip (but in this case it's per row/col)?

**Comment by cglagovichTT** [comment]
Launching each line-all-gather in parallel is definitely what we want. Does that mean that all of the logic has to be within `launch_op`?

**Comment by SeanNijjar** [comment]
> Launching each line-all-gather in parallel is definitely what we want. Does that mean that all of the logic has to be within `launch_op`?

We can't do it in the op because multiple rows/cols worth of tensors will be presented and it will be ambiguous how many line gathers are desired and where. Instead, I'm proposing that until the syntactic sugar is added, you could do something like:

```
full_galaxy_input_tensors = ttnn.get_device_tensors(input_mesh_tensor)
per_row_tensors = [ # This could be saved somewhere for reuse
[<I don't know the exact ID's but these would correspond the the chip order],
[],
[],
[],
]

outputs = []
for r in range(nrows):
  # If mesh tensor enabled
  row_mesh_tensor = ttnn.aggregate_as_tensor([full_galaxy_input_tensors[i] for i in per_row_tensors[r]])
  output_mesh_tensor = ttnn.line_all_gather(row_mesh_tensor, ... rest of args)
  outputs.append(output_mesh_tensor)
  
  # if no mesh tensor
  row_tensors = [full_galaxy_input_tensors[i] for i in per_row_tensors[r]]
  row_outputs = ttnn.line_all_gather(row_tensors, ... rest_of_args)
  outputs.append(row_outputs)


# This might need to be reverse mapped to match the chip order
output_mesh_tensor = ttnn.aggregate_as_tensor(itertools.chain(outputs))
```
