### ISSUE TITLE
'ModuleNotFoundError'

### ISSUE THREAD

**Issue by colchocor** [tenstorrent/tt-metal#9882]
I'm working through trying to test out the Grayskull e150 card and I'm running into a ModuleNotFoundError. I'm trying to run the Resnet Demo in tt-metal. Let me know what I can do. Thanks.

![Image](https://github.com/tenstorrent/tt-metal/assets/174486051/82fcffc6-f9ea-468e-ab4f-e8842dacf527)

https://github.com/tenstorrent/tt-metal/tree/main/models/demos/resnet

**Comment by cfjchu** [comment]
@tt-aho can you take a look?

**Comment by TT-BrianLiu** [comment]
Your missing the python path. Here are some common exports:
```
export TT_METAL_ENV=dev && export TT_METAL_HOME=$PWD && export ARCH_NAME=grayskull && export PYTHONPATH=$TT_METAL_HOME && source build/python_env/bin/activate
```

**Comment by tt-aho** [comment]
Hey @colchocor, have you set up the environment and env vars as described in https://github.com/tenstorrent/tt-metal/blob/main/INSTALLING.md, specifically `TT_METAL_HOME ` and `PYTHONPATH` should be the tt-metal root directory.

I don't see the module not found error but we've deprecated support for batch 8 with this implementation of Resnet, so the demo will fail for a different issue. I am working on uplifting this to work with our latest batch 20 implementation

**Comment by tt-aho** [comment]
I've updated the demo and associated readme with new instructions/commands. Let me know if you still see any issues running the demo.

**Comment by ayerofieiev-tt** [comment]
Closing this ticket for inactivity. Please reopen if this issue is still not resolved. Thank you!
