### ISSUE TITLE
Flakiness in test MultiCommandQueueSingleDeviceFixture.TestAsyncRuntimeAllocatedBuffers

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#9888]
Seeing flakiness in MultiCommandQueueSingleDeviceFixture.TestAsyncRuntimeAllocatedBuffers when running post commit on branch `abhullar/max-unicast-arg` 

Failing run on branch: 
- https://github.com/tenstorrent/tt-metal/actions/runs/9754688545

Failing run on main
- https://github.com/tenstorrent/tt-metal/actions/runs/9779145192/job/26998035540

Passing runs:
- https://github.com/tenstorrent/tt-metal/actions/runs/9765736726
- https://github.com/tenstorrent/tt-metal/actions/runs/9764961673
- https://github.com/tenstorrent/tt-metal/actions/runs/9762277266

Changes on this branch should not have impacted async functionality (turned a hardcoded value into compile time arg for a kernel)

**Comment by pgkeller** [comment]
@abhullar-tt @tt-asaigal any idea if this is still relevant?  Does it repro only on CI machines?

**Comment by tt-asaigal** [comment]
> [@abhullar-tt](https://github.com/abhullar-tt) [@tt-asaigal](https://github.com/tt-asaigal) any idea if this is still relevant? Does it repro only on CI machines?

I don't think there's flakiness here anymore. I pushed a commit a while back that resolved the issue, just never updated this. Will close.
