### ISSUE TITLE
[Feature Request] Define `DISABLE_STATIC_ASSERT_TESTS` when using reflect library

### ISSUE THREAD

**Issue by jeongu-moreh** [tenstorrent/tt-metal#9902]
**Is your feature request related to a problem? Please describe.**
There are static assert tests in reflect library header file by default but they slow down the compilation speed.

**Describe the solution you'd like**
Add compile definition `DISABLE_STATIC_ASSERT_TESTS` with cmake in targets using reflect library

**Comment by razorback3** [comment]
@eyonland @TT-billteng

**Comment by razorback3** [comment]
https://github.com/boost-ext/reflect/tree/v1.1.1?tab=readme-ov-file#FAQ

> Can I disable running tests at compile-time for faster compilation times?
> 
> When DISABLE_STATIC_ASSERT_TESTS is defined static_asserts tests won't be executed upon inclusion. Note: Use with caution as disabling tests means that there are no gurantees upon inclusion that given compiler/env combination works as expected.

I think this should be done by individual developers in their code locally depending on their requirements.
