### ISSUE TITLE
CoreRange::diff calculation seems incorrect (core_coord.h)

### ISSUE THREAD

**Issue by nobradovictt** [tenstorrent/tt-metal#9903]
<img width="972" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/132568163/4c5c4382-c739-4358-9a2f-961334493b0e">

Besides that expression:
```
if (this->start.x < cr.start.x < this->end.x)
            xs.insert(cr.start.x);
```
Will not yield expected results in C++ as it will most likely every time evaluate to true because first part of the expression is evaled to bool(0 or 1) it also fails to compile(rightly so) with latest versions of clang(19.0):
tt-mlir/third_party/tt-metal/src/tt-metal/tt_metal/common/core_coord.h:134:40: error: comparisons like 'X<=Y<=Z' don't have their mathematical meaning [-Werror,-Wparentheses]
  134 |         if (this->start.x < cr.start.x < this->end.x)

**Comment by TT-billteng** [comment]
Code isn't used anymore and I've deleted it
