### ISSUE TITLE
sum/reduce op does not work for random inputs

### ISSUE THREAD

**Issue by johanna-rock-tt** [tenstorrent/tt-metal#9908]
**Describe the bug**
The sum op (reduce) has large error for non integer inputs. Currently in `test_sum.py` only the summation of integers is tested - this is not sufficient and fails for random fp32 and bfloat16 inputs.

I added a test that uses random inputs and different data formats, and compares using `comp_allclose`. This test should pass.

What I see:

BF16 shape = (1, 1, 32, 32)
ref vs tt = Max ATOL Delta: 0.0625, Max RTOL Delta: 0.068359375, PCC: 0.9999956409523759, Allclose check failed

FP32 shape = (1, 1, 32, 32)
ref vs tt = Max ATOL Delta: 0.05738258361816406, Max RTOL Delta: 0.02300325594842434, PCC: 0.9999959183719673, Allclose check failed

BF16 shape = (1, 1, 32, 1024)
ref vs tt = Max ATOL Delta: 2.75, Max RTOL Delta: 0.279296875, PCC: 0.9998845309940628, Allclose check failed

FP32 shape = (1, 1, 32, 1024)
ref vs tt = Max ATOL Delta: 1.9558944702148438, Max RTOL Delta: 0.3209826350212097, PCC: 0.9998569160517634, Allclose check failed

Even adding two numbers fails:

```
Two input numbers: 1.9297, 1.4844 (all other numbers in tensor are zero)

Sum over that dim:
Torch reference (bf16): 3.4062
Torch reference (fp32): 3.4141
FP32: 3.4219
BF16: 3.4219
BFP8_B: 3.4375 
BFP4_B: 3.0
```

For larger shapes, e.g. [32, 1024] or [2048, 1024], this error accumulates to very large numbers.

**To Reproduce**
1. Checkout `jrock/reduce-issue`
2. Run `pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum`

**Comment by johanna-rock-tt** [comment]
The issue also exists with different reduction dims:

Two input numbers: 1.9297, 1.4844
dtype=bfloat16

sum_global 
torch: 3.4062
tt: 3.4219

grep -Rnw 'built' -e 'REDUCE_DIM'
built/2052/kernels/reduce_w/4495494718154647535/defines_generated.h:2:#define REDUCE_DIM ReduceDim::REDUCE_ROW
built/2052/kernels/reduce_h/15874065893775173914/defines_generated.h:2:#define REDUCE_DIM ReduceDim::REDUCE_COL

Sum in H
torch: 3.4062
tt: 3.4219

grep -Rnw 'built' -e 'REDUCE_DIM'
built/2052/kernels/reduce_h/15874065893775173914/defines_generated.h:2:#define REDUCE_DIM ReduceDim::REDUCE_COL


Sum in W
torch: 3.4062
tt: 3.4219

grep -Rnw 'built' -e 'REDUCE_DIM'
built/2052/kernels/reduce_w/4495494718154647535/defines_generated.h:2:#define REDUCE_DIM ReduceDim::REDUCE_ROW

**Comment by johanna-rock-tt** [comment]
fyi: @uaydonat

**Comment by pavlejosipovic** [comment]
by taking a quick look at the impl it seems that reduce in metal doesn't support 32 bit acc (no matter which tensors are passed in)

**Comment by cglagovichTT** [comment]
## Repro
- branch: `cglagovich/fp32_slow_reduce`
```bash
pytest -svv  tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum[shape_dim0-BFLOAT16]
```

```
ref vs tt = Max ATOL Delta: 0.0625, Max RTOL Delta: 0.068359375, PCC: 0.9999956409523759, Allclose check failed
expect:  tensor([  6.9688,  -4.8750,   2.3125,   6.0000,   5.6562,  -7.2188,   4.8438,
          2.4688,  -0.8047,  -2.2500,   2.7656,   3.6875,  -1.5156,  -0.0605,
          0.7969,  -4.5938,  -6.1562,   5.8125,  -3.6562,   6.2812,  -6.8125,
          6.2188,   6.9062,   4.6562,  -6.0000,  -4.7188,   3.6094, -12.6250,
          6.2188,  -2.2188,  -9.8125,   7.0938], dtype=torch.bfloat16)
got:  tensor([  7.0000,  -4.8750,   2.3281,   6.0000,   5.6562,  -7.2188,   4.8750,
          2.4688,  -0.7812,  -2.2500,   2.7656,   3.7031,  -1.5234,  -0.0564,
          0.7891,  -4.5938,  -6.1562,   5.8125,  -3.6562,   6.2812,  -6.8125,
          6.2188,   6.9062,   4.6562,  -6.0000,  -4.7500,   3.6094, -12.5625,
          6.2500,  -2.2344,  -9.8125,   7.0938], dtype=torch.bfloat16)
```


Now I modify the `reduce_w.cpp` file to make the unpacker perform reduce_sum with fp32 accumulation.
These are the results with fp32 accumulation:
```
ref vs tt = Max ATOL Delta: 0.0625, Max RTOL Delta: 0.0069580078125, PCC: 0.9999964480552922, Allclose check failed
expect:  tensor([  6.9688,  -4.8750,   2.3125,   6.0000,   5.6562,  -7.2188,   4.8438,
          2.4688,  -0.8047,  -2.2500,   2.7656,   3.6875,  -1.5156,  -0.0605,
          0.7969,  -4.5938,  -6.1562,   5.8125,  -3.6562,   6.2812,  -6.8125,
          6.2188,   6.9062,   4.6562,  -6.0000,  -4.7188,   3.6094, -12.6250,
          6.2188,  -2.2188,  -9.8125,   7.0938], dtype=torch.bfloat16)
got:  tensor([  6.9688,  -4.8438,   2.3125,   5.9688,   5.6250,  -7.2188,   4.8125,
          2.4688,  -0.8008,  -2.2344,   2.7656,   3.6875,  -1.5156,  -0.0605,
          0.7969,  -4.5938,  -6.1562,   5.7812,  -3.6406,   6.2500,  -6.7812,
          6.2188,   6.9062,   4.6562,  -6.0000,  -4.7188,   3.5938, -12.5625,
          6.2188,  -2.2188,  -9.7500,   7.0625], dtype=torch.bfloat16)
```

All I can say with this result is that the `reduce_tile` impl lacking fp32 accumulation does not have an impact on single tile reductions. I would have to see if this holds for larger inputs.

**Comment by pavlejosipovic** [comment]
https://github.com/tenstorrent/tt-metal/tree/pjosipovic/reduce32_hack
I've hacked here an implementation for 32 bit (other data formats won't work), I'm getting significantly better absolute error with this one.
So our FPU supports only TF32 on input which is 19bit so you will get some error here converting from 32 -> 19 bits,
but accumulation for sum will be in 32 bit.

**Comment by johanna-rock-tt** [comment]
@pavlejosipovic Could you please post your concrete results in here?

**Comment by cglagovichTT** [comment]
It looks like `tt_metal/common/bfloat16.hpp` converts fp32 to bf16 with truncation. Another thing we can try is to use round to even to see if we match pytorch in bf16

**Comment by johanna-rock-tt** [comment]
I tested Pavles hack to use F32 accumulation + FP32 reduce scalar versus what we have in main.
I have:
- BF16 and FP32
- shape0 = [1,1,32,32], shape2=[1,1,2048,1024] <-- this is what we use in falcon40b/llama2

Here's the numbers:

Pavles hack:

```
tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum[shape_dim0-FLOAT16] 
ref vs tt = Max ATOL Delta: 0.0625, Max RTOL Delta: 0.0069580078125, PCC: 0.9999964480552922

tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum[shape_dim2-FLOAT16]
ref vs tt = Max ATOL Delta: 7.0, Max RTOL Delta: 146.0, PCC: 0.999613593394302

tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum[shape_dim0-FLOAT32] 
ref vs tt = Max ATOL Delta: 0.01207733154296875, Max RTOL Delta: 0.05839734151959419, PCC: 0.999999920943286

tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum[shape_dim2-FLOAT32] 
ref vs tt = Max ATOL Delta: 1.0089340209960938, Max RTOL Delta: 11.569167137145996, PCC: 0.9999937538630723
```

Main:
```
pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum[shape_dim0-BFLOAT16]
ref vs tt = Max ATOL Delta: 0.0625, Max RTOL Delta: 0.068359375, PCC: 0.9999956409523759

pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum[shape_dim2-BFLOAT16]
ref vs tt = Max ATOL Delta: 4.25, Max RTOL Delta: 177.0, PCC: 0.9998324133471583

pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum[shape_dim0-FLOAT32]
ref vs tt = Max ATOL Delta: 0.05738258361816406, Max RTOL Delta: 0.02300325594842434, PCC: 0.9999959183719673

pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_sum.py::test_sum[shape_dim2-FLOAT32]
ref vs tt = Max ATOL Delta: 4.801029205322266, Max RTOL Delta: 33.93199157714844, PCC: 0.9998304449987134
```

Conclusions:
- Pavles hack improves FP32 reduction around 5x.
- It also seems to increase error on BF16 for some number ranges? (see shape2 BF16 Pavles hack vs. main) @pavlejosipovic Is this expected based on the hard coded reduce factor? Or is that still surprising to be worse rather than the same?

**Comment by johanna-rock-tt** [comment]
I've also tested:
- Pushing data to device and back to host has 0 error for FP32 and BF16 (independent whether first converted to bf16 in torch or not)
- Error for FP32 through casting to TF32 in the SFPU seems to be ~ 0.0019 absolute / ~0.0009 relative
  - why do I think so:
  fp32 random tensor adding zeros (ttnn.add) gives `Max ATOL Delta: 0.0019366741180419922, Max RTOL Delta: 0.0008975895470939577, PCC: 0.999999973943056`
  the error should come exclusively from casting in the SFPU, right?
- BF16 pytorch vs FP32 pytorch:
```
shape0:
ref fp32 vs ref bf16 = Max ATOL Delta: 0.03125, Max RTOL Delta: 0.1328125, PCC: 0.9999988663652715

shape2:
ref fp32 vs ref bf16 = Max ATOL Delta: 0.5, Max RTOL Delta: 2.03125, PCC: 0.9999964523498722
```
So in almost all cases the pytorch difference between FP32 vs. BF16 is a lot less than the difference between pytorch and TT devices in the same dataformat.

**Comment by pavlejosipovic** [comment]
In my version only 32 bit works, disregard everything else. In the final solution we can make all cases work.

**Comment by johanna-rock-tt** [comment]
> It looks like `tt_metal/common/bfloat16.hpp` converts fp32 to bf16 with truncation. Another thing we can try is to use round to even to see if we match pytorch in bf16

In the following test I compared what happens if we push the input to device and just read it back without doing anything else with it:

```
inputs: pytorch ref fp32 vs pytorch ref bf16 = Max ATOL Delta: 0.015438079833984375, Max RTOL Delta: 0.0039054155349731445, PCC: 0.9999986212624355
inputs: pytorch ref fp32 vs tt fp32 = Max ATOL Delta: 0.0, Max RTOL Delta: 0.0, PCC: 1.0
inputs: pytorch ref bf16 vs tt bf16 conversion in TT, when pushing to device = Max ATOL Delta: 0.0, Max RTOL Delta: 0.0, PCC: 1.0
inputs: pytorch ref bf16 vs tt bf16 conversion in torch, then pushed = Max ATOL Delta: 0.0, Max RTOL Delta: 0.0, PCC: 1.0
```

So looks like the issue shouldn't be in the conversion, since pushing to device and reading it back is fine. So pytorch is probably doing the same?

**Comment by johanna-rock-tt** [comment]
> In my version only 32 bit works, disregard everything else. In the final solution we can make all cases work.

Would you still expect an improvement for BF16 with your hack when generalized? Due to the FP32 accumulate I suppose?

**Comment by pavlejosipovic** [comment]
Yes there would be some

**Comment by johanna-rock-tt** [comment]
@pavlejosipovic Could you take over the more general implementation for this? Or should we ask someone else for it?

**Comment by cglagovichTT** [comment]
Is it the case that the scalar dataformat must be the same as the input dataformat for `reduce_tiles`?

**Comment by pavlejosipovic** [comment]
If input is 32bit than scalar has to be 32bit to avoid converting input to 16 bit in the kernel.
For other input data types 16bit is fine.

**Comment by johanna-rock-tt** [comment]
@uaydonat @yieldthought What error do you think is realistic/expected here? How should we continue on this issue?

**Comment by uaydonat** [comment]
My understanding is that fp32 accum helps with the error. Because our inputs are fp16, we do not need the scalar->fp32 fix.

What's next?
1. port fp32 accum to SDPA kernel? see if pcc is fixed?
2. port fp32 accum to distributed layernorm? see if bad output tokens are fixed?

**Comment by uaydonat** [comment]
Raising priority since multiple tasks  are blocked by this.

**Comment by cglagovichTT** [comment]
I think the reason Johanna started looking into this is because her fp32 accum reduce_sum in distributed layernorm was producing more error than expected. In that case we need more data on this reduce_w test case to see if the error for bf16 inputs, fp32 accum makes sense

**Comment by johanna-rock-tt** [comment]
Correct. In distributed layernorm I'm passing in fp32 accumulation as argument but the error is still higher than expected and that's when I took a look at the test_sum test to double check.

**Comment by uaydonat** [comment]
what's the next step?
* do we have more investigation to do? what exactly? e.g. do we need Pavle's hack but with bf16 inputs?
* do we need to apply the hack to other kernels?
*

**Comment by johanna-rock-tt** [comment]
So Pavles hack was basically two things:
(A) use fp32 accumulation and
(B) use fp32 as reduce scalar.

(A) is (somewhat) helpful for both bf16 inputs and fp32 intputs but we've tried this also in e.g. distirbuted layernorm and the error is still large and more than we'd expect. So this is already used in other kernels and was only missing in the reduce op itself (but is used already in distributed layernorm and I believe in SDPA too).

(B) only helps in case of fp32 inputs but not for bf16 inputs.

I think we should
(1) At some point add Pavles hack for fp32 inputs (using the fp32 reduce scalar in that case improved the error 5x), but in my opinion that's not super high priority because we are not really interested in using fp32 inputs.
(2) Investigate further why we are still seeing so large error for both fp32 and especially bf16 inputs
  - @pavlejosipovic  is looking into this right now, he has learned that the reduce uses a matmul under the hood (and not SFPU as previously assumed) so it essentially does a dot product with all ones. This means there's more complexity than just adding two numbers including more configuration possibilities (e.g. HiFi settings make a difference there while they don't on SFPU). He's looking at a case where all numbers should be representable though bf16/fp32 and with fp32 accumulation there should in theory be no loss in precision - but he's also there seeing non negligible error there.

**Comment by pavlejosipovic** [comment]
I'm still looking into this. 
My new conclusion is that reduce sum works ok on dim 2 (reduce column), but reduce sum on dim 3 (reduce row) has issues with 32 bit accumulation and is loosing precision.
So depending on your use case if you are using dim 2 precision should be ok if you enable fp32 acc.
If you are using dim 3 there are precision issue and I'm working with @ttmtrajkovic to see if we can do something about it.

**Comment by pavlejosipovic** [comment]
@johanna-rock-tt check out this branch https://github.com/tenstorrent/tt-metal/tree/pjosipovic/reduce_via_matmul_32bit_acc
I've enabled 32bit acc by default for reduce h/w
And I've changed the implementation for reduce sum on w dimension to use matmul llk instead of reduce llk.
I'm seeing a lot better precision with this.
I don't have any support for 32 bit inputs on this branch
