### ISSUE TITLE
Move Unary Composite ops to ttnn

### ISSUE THREAD

**Issue by bharane-ab** [tenstorrent/tt-metal#9911]
TOATAL NUMBER OPS = 53

Work For: 49/53

- [x] #9913 
- [x] #10237
- [x] #10238
- [x] #10384
- [x] #10385
- [x] #10386
- [x] #10505

**Comment by ayerofieiev-tt** [comment]
There is progress on 20/53

**Comment by ayerofieiev-tt** [comment]
@KalaivaniMCW do you know what is missing to close this as Done?

**Comment by KalaivaniMCW** [comment]
@ayerofieiev-tt I have created two issues for the pending items
#10640 
#10820 
I am closing this issue with the intention that the above two issues are being tracked.
