### ISSUE TITLE
SD model fails from main on N150. 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#9938]
**Describe the bug**
SD demo test fails from the main branch. This should be resolved very soon with the WH launch coming up. 

**To Reproduce**
1. checkout to [commit](f587cb5b8cdbaf558078de3127fd526b4a8a680f) from main
2. run: `pytest --disable-warnings --input-path="models/demos/wormhole/stable_diffusion/demo/input_data.json" models/demos/wormhole/stable_diffusion/demo/demo.py::test_demo`
3. See error: `ERROR models/demos/wormhole/stable_diffusion/demo/demo.py - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Expected behavior**
demo pytest passes.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (f587cb5b8cdbaf558078de3127fd526b4a8a680f)
- N150

**Additional context**
Important for WH launch

**Comment by sankarmanoj-tt** [comment]
This is an issue with a version mismatch between numpy and torch. 
It can be fixed with `pip install numpy torch  --upgrade`

**Comment by dvartaniansTT** [comment]
thanks @sankarmanoj-tt ! should this be mentioned in the README file or pip install requirements file should be updates as part of the build process?

**Comment by mywoodstock** [comment]
Yeah probably should be in instructions if this error shows up -- although I tried this and I don't get the error. @tt-rkim do you know who would decide on the python packages version?

**Comment by TT-billteng** [comment]
do we need to update and pin new versions of `numpy` and `torch`?

**Comment by dvartaniansTT** [comment]
@TT-billteng and @sankarmanoj-tt and @mywoodstock it still failed wit the same error after running `pip install numpy torch  --upgrade` but I noticed when creating the virtual env and building from src the python version is 3.10 while 3.8 is recommended in Matalium main page. could this be the source of the issue? 

We have re-installed the sys dependencies, rebooted and will be testing again soon

**Comment by dvartaniansTT** [comment]
resolved now
