### ISSUE TITLE
BERT-Large model fails from main on Wormhole N300

### ISSUE THREAD

**Issue by vshenoyTT** [tenstorrent/tt-metal#9946]
**Describe the bug**
BERT demo test fails from the main branch.

**To Reproduce**
1. Checkout to [main](https://github.com/tenstorrent/tt-metal)
2. Run the command: 
'pytest --disable-warnings --input-path="models/demos/wormhole/stable_diffusion/demo/input_data.json" models/demos/wormhole/stable_diffusion/demo/demo.py::test_demo`
3. See the error: `FAILED models/demos/metal_BERT_large_11/demo/demo.py::test_demo[models/demos/metal_BERT_large_11/demo/input_data.json-1-batch_7] - RuntimeError: TT_FATAL @ ../tt_eager/tt_dnn/op_library/bmm/multi_core_reuse_mcast_2d_optimized/bmm_op_multi_core_reuse_mcast_2d_opt..`

**Expected behavior**
The PyTest passes.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software ([f587cb5](https://github.com/tenstorrent/tt-metal/commit/f587cb5b8cdbaf558078de3127fd526b4a8a680f))
- N300

**Comment by tt-aho** [comment]
The repro command is incorrect and from WH.

Looking at the error, it seems like the command would be `pytest models/demos/metal_BERT_large_11/demo/demo.py::test_demo[models/demos/metal_BERT_large_11/demo/input_data.json-1-batch_7]`.

I do not see an error and this passes for me on 6cf8607f70afc79e0cf501cd6e912eb17c8f78c5

**Comment by vshenoyTT** [comment]
Apologies, I attached the wrong command to the Issue. However, I was using the command for Bert, not Bert Large.  The test has now passed on my end.
