### ISSUE TITLE
Mistral-7B model fails from main on Wormhole N300

### ISSUE THREAD

**Issue by vshenoyTT** [tenstorrent/tt-metal#9947]
**Describe the bug**
Mistral demo test fails from the main branch. I added the correct path for the weights (which were fully downloaded, and I double checked the path) and it did not work. I manually added the exact same path to the weights in the testing code, and then it worked.

**To Reproduce**
1. Checkout to [main](https://github.com/tenstorrent/tt-metal)
2. Run the command: 
'pytest models/demos/wormhole/mistral7b/tests/test_mistral_model.py::test_mistral_model_inference[17-generative]`
3. See the error: 'FAILED models/demos/wormhole/mistral7b/tests/test_mistral_model.py::test_mistral_model_inference[17-generative] - AssertionError: weights consolidated.00.pth file does not exist. Please use the script `models/demos/wormhole/mistral7b/scripts/...'

**Expected behavior**
The PyTest passes.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software ([f587cb5](https://github.com/tenstorrent/tt-metal/commit/f587cb5b8cdbaf558078de3127fd526b4a8a680f))
- N300

**Comment by TT-billteng** [comment]
did you forget to download something? Please show the full log 

 Please use the script `models/demos/wormhole/mistral7b/scripts/...'

**Comment by vshenoyTT** [comment]
Got it working on my end today after a new clone and build. Closing the issue accordingly.
