### ISSUE TITLE
ttnn.depthwiseconv fails for MobilenetV2 conv2d test case

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#9952]
**Describe the bug**
ttnn.depthwiseconv fails with assertion error for MobilenetV2 conv2d test case

**To Reproduce**
1. Checkout the branch [keerthanar/mobilenetv2_depthwise_conv_issue](https://github.com/tenstorrent/tt-metal/tree/keerthanar/mobilenetv2_depthwise_conv_issue)
2. Run the following command 
`pytest tests/ttnn/unit_tests/operations/test_depthwise_conv1d.py::test_mobilenetv2_depthwiseconv`
3. The following error will ooccur,
`E       AssertionError: Input and kernel width must be 1, only 1D convolutions are supported in this test
E       assert (128 == 1)`

**Comment by mywoodstock** [comment]
@tt-asaigal Could you please take a look into this issue? Thanks!

**Comment by mywoodstock** [comment]
@tt-asaigal sorry wrong person :) 

@kpaigwar could you please take a look at this? Thanks!

**Comment by kpaigwar** [comment]
@keerthana-r-mcw 
Presently, the op `tttnn.depthwise_conv1d ` is developed to support 1D inputs. It will fail on 2D images.
I would suggest to use normal ttnn.conv2d and set groups according to your configuration

**Comment by dvartaniansTT** [comment]
@keerthana-r-mcw have you seen @kpaigwar comment on this?

**Comment by keerthana-r-mcw** [comment]
Yes @dvartaniansTT, as @kpaigwar said, we are using `ttnn.conv2d`, since we don't have support for 2D images in `ttnn.depthwise_conv1d`.

**Comment by sankarmanoj-tt** [comment]
From my discussion with @keerthana-r-mcw, the [corresponding op in the reference code](https://github.com/tenstorrent/tt-metal/blob/e12e91700aaedeeac612ba45be2bd93335200c41/models/experimental/functional_mobilenetv2/reference/mobilenetv2.py#L13) is a regular Conv2D which should work.
