### ISSUE TITLE
Update docs with missing operations

### ISSUE THREAD

**Issue by dveizovicTT** [tenstorrent/tt-metal#9983]
The following operations:
Logical_ANDI
Logical_ORI
Logical_XORI
Logical_NOTI

aren't documented in: https://tenstorrent.github.io/tt-metal/latest/ttnn/index.html

**Comment by mcw-anasuya** [comment]
Closing since these ops have been renamed as follows and the documentation is present in [documentation](https://tenstorrent.github.io/tt-metal/latest/ttnn/index.html):
Logical_ANDI --> logical_and_
Logical_ORI --> logical_or_
Logical_XORI --> logical_xor_
Logical_NOTI --> logical_not_
